### ISSUE TITLE
Activity

### ISSUE THREAD

**Issue by 63502** [HellFirePvP/AstralSorcery#1]
HI. I SEE YOU BEING ACTIVE AGAIN.

I have had no luck reaching T145 for anything for the past 6 weeks or thereabouts, so yeah...stuck in limbo there... -_-

Not to mention life being MUCH more of a pain than usual... -_-

So..... How have all the things gone so far?

**Comment by HellFirePvP** [comment]
You do remember me telling you my opinion about him pretty early on right? Seems like i wasn't so wrong after all.

Working on the mod, finished the first 1/3rd of the GUI yesterday.

If you're interested: https://www.youtube.com/watch?v=cjdGDEFFKqI

**Comment by 63502** [comment]
Looking really cool, its like an end portal but better. :D

**Comment by HellFirePvP** [comment]
Well, not the effect i was going for, but well.

**Comment by 63502** [comment]
Its cool anyways. 

Be sure to PM me when the mod is ready for its first test run. I would love to help out. I also have some new ideas for how the lore of the mod can work. I will be making a new google doc to lay out some of them for you to see. I will send you the link when its ready.

**Comment by HellFirePvP** [comment]
Well i guess we should talk again somewhat soon since some design ideas changed and the google sheet is not actually really up-to-date anymore...
