### ISSUE TITLE
[FATAL] Crash on startup, unable to play (FTB Revelations)

### ISSUE THREAD

**Issue by Tenkaofao** [HellFirePvP/AstralSorcery#1001]
**I am currently running the latest version of Feed The Beast: Revelations**

I have made no modifications and was just playing the game with a friend, the issue occurred when we powered on a miner from the IndustrialCraft mod. (I believe this is what caused it from the error log.. maybe update with some functionality or support for this mods miner?)

Now, it began to mine, doing its thing, and I mined down a block in front of the machine to see its mining process, before it instantly crashed.

Oh well, I thought, maybe it was an issue that could be fixed with a restart... **WRONG!**

The server crashes every time it starts up, I removed the mod and it worked fine, re-adding it in crashed it every single time. I noticed FTB is not up to date but on a previous version, tried the newest one, and still nothing happened.

Server Error: https://pastebin.com/raw/Fxh4S4af
 
Note: The server says it is generating a debug.log but it isn't, so if you need more info then the above I can't provide it to you. Try running the latest FTB Revelations with the world above to try it yourself and debug from there if the debug.log generates for you. (Been having this issue for a while..)

--- 

No other errors came up from this mod, and to guarantee this, and my 'miner' was not mining any sort of ground item that came from this mod. Please look into this, for now, I have to sadly disable this mod as it makes our game unplayable. We really want to add it back though! _But I guess we wouldn't be able to do this without having to restart since all the world gen is removed because of us removing the mod from our server.._

**Comment by Doomgull** [comment]
Actually an IC2 issue, fixed a while ago. See #963.
