### ISSUE TITLE
Liquid starlight and water can create a huge mess.

### ISSUE THREAD

**Issue by farigiss** [HellFirePvP/AstralSorcery#1003]
If  you pour liquid starlight and water down for example a mountain, the starlight freezes flowing water, forming ice, but the light level of the starlight unfreezes it, creating water source blocks, which in turn create infinite water sources, which also start running down, getting frozen and unfrozen creating more water and ice. 
The mess it creates can be in the thousands of blocks of cleanup and cleaning up infinite water sources is not easy to begin with.

**Comment by Doomgull** [comment]
This is hilarious to watch, though.

**Comment by HellFirePvP** [comment]
Yea... this can happen.. not my fault for this mess though :P
Just cause it can be used this way doesn't mean you have to do it :P

So... in the light of this madness, now i don't even want to fix that and sell it as feature
