### ISSUE TITLE
Multi MC

### ISSUE THREAD

**Issue by SilverCyndaquil** [HellFirePvP/AstralSorcery#1005]
Astral Sorcery 1.12 doesn't seem to work with Multi MC which sucks because it's the only way mods work on my computer.

**Comment by Doomgull** [comment]
I've launched over a dozen times in the laat week alone off multimc, so how about some more info?

**Comment by SilverCyndaquil** [comment]
Never mind. It appears one of the mods I was trying to use alongside it makes either it or Multi MC glitch out. I'll update you after I find out what mod it is.
