### ISSUE TITLE
Forge Version Issue

### ISSUE THREAD

**Issue by KillerKorgi** [HellFirePvP/AstralSorcery#1006]
11 days ago the build requirement was changed to be 2781 or greater. The recommended build currently is 2768 and the latest is 2814. Any version you try to download from curseforge wants the 2781 min (I think I went through like 10+ of your builds last night)

This seems like an error to me. Why would you have a requirement more than the recommended but not the latest? 2781 was a build back in November, there have been 20+ iterations since then.

**Comment by Doomgull** [comment]
Because that was the version needed to build against. Go talk to forge if you want to know why the recommended build is nearly half a year old.
