### ISSUE TITLE
Grindstone won't sharpen crystal pickaxe

### ISSUE THREAD

**Issue by Pyrosminecraft** [HellFirePvP/AstralSorcery#1007]
Currently playing the Sevtech Ages modpack that includes Astral Sorcery version 1.8.10. I've made a crystal pickaxe and have used liquid starlight to increase its size to 2700, maximum. However, the grindstone will not allow me to place the pickaxe on it, nothing happens when rightclicking, making it so that I cannot increase the cutting stat.

**Comment by Doomgull** [comment]
Was fixed a very long time ago. Sevtech is on a horrifically outdated version.
