### ISSUE TITLE
Why Geolosys sample needs OreStages? 

### ISSUE THREAD

**Issue by SihenZhang** [HellFirePvP/AstralSorcery#1008]
I'm confused that why sample needs OreStages so that it will be registried. 

https://github.com/HellFirePvP/AstralSorcery/blob/85412708c63c7790ed2947c47ab54f936af1511f/src/main/java/hellfirepvp/astralsorcery/common/registry/RegistryBlocks.java#L62-L65

**Comment by Doomgull** [comment]
Because it was added specifically for sevtech.

**Comment by HellFirePvP** [comment]
Yea. because it is/was specifically and only for sevtech and nothing else.
