### ISSUE TITLE
Cannot bring Constellation into focus on a certain world

### ISSUE THREAD

**Issue by Scorpinox** [HellFirePvP/AstralSorcery#101]
On my testing world, I have managed to successfully map out constellations and have them appear in the sky using the hand telescope and relevant constellation paper. However, on my main world, I cannot bring constellations into focus. I can see the edges of the large-starred constellation , but attempting to bring the constellation into the center of the telescope's view causes the constellation to completely vanish. I have tested this with all possible GUI scales, and have tested this at multiple locations in my world. Any ideas what may be causing this? I can send a copy of the relevant world if needed.

I am using the latest version of AllTheMods for 1.10.2.

**Comment by HellFirePvP** [comment]
Depending on your AstralSorcery - version this might already be fixed. What's the version you're playing with?

**Comment by Scorpinox** [comment]
With the latest version, the problem has changed. Now the constellation continuously pops in and out of visibility for what appear to be single frames, moving each time. This also happens on all worlds, not just the original world with the problem.

**Comment by HellFirePvP** [comment]
This is known and solved in-dev
you can craft & use the mounted telescope until the next version hits~

**Comment by Scorpinox** [comment]
Thank you very much!
