### ISSUE TITLE
Crash Due to Possible Index Translation Error with Crafttweaker

### ISSUE THREAD

**Issue by Vyraal1** [HellFirePvP/AstralSorcery#1010]
https://gist.github.com/Vyraal1/4ba5c5892f59fa4d2cf5612fb80c4d87

This was the script: https://gist.github.com/Vyraal1/72f5d754a0f880f03f49eb26f0275427
Relevant lines are the Alcara Constellation Paper crafting at line 278

Made some debug scripts here: https://gist.github.com/Vyraal1/c068ea9536448f3d13cec232c2b47796

The first recipe for making a chest crashes as it only has 25 items, the second recipe works fine to make a cobweb.

**Comment by IRSmoh** [comment]
For laziness one of the recipes looks similar to this: https://media.discordapp.net/attachments/527215210768105481/546137487957950467/unknown.png

in so much as, there are no items that are needed in the relay(s); while the tier requirement is still iridescent.
