### ISSUE TITLE
Scorching Heat + Fortune Not working

### ISSUE THREAD

**Issue by Xen122** [HellFirePvP/AstralSorcery#1013]
It's in the title when using scorching heat and fortune, fortune doesn't work as intended and instead i get 1 of the ore instead of 2

**Comment by Doomgull** [comment]
What AS version and Forge version?

**Comment by Xen122** [comment]
> 
> 
> What AS version and Forge version?

Using AS version 1.10.10
Using Forge version 14.23.5.2808

**Comment by HellFirePvP** [comment]
If there's no furnace recipe or the pack removes that recipe, it won't work.
You obviously don't get extra chance on getting an ore_block_ of course, only smeltable results.

**Comment by Xen122** [comment]
> 
> 
> If there's no furnace recipe or the pack removes that recipe, it won't work.
> You obviously don't get extra chance on getting an ore_block_ of course, only smeltable results.

I understand that, but I am referring to vanilla ore such as emerald,diamond,lapis,redstone, coal etc.  I have done some testing on my own and did find out that it is indeed the enchantment that is causing the issue. 
When breaking a coal ore block with a fortune 3 pickaxe, most times I receive a total of 2 coals, but when applying the scorching heat enchantment, I receive one coal/diamond/etc.
