### ISSUE TITLE
Increased maximum lifes perks take hunger on each world load

### ISSUE THREAD

**Issue by BuggaNoia** [HellFirePvP/AstralSorcery#1017]
Version: astralsorcery-1.12.2-1.10.11 (and astralsorcery-1.12.2-1.10.10)
Pack: Enigmatica Expert 1.56 (and 1.49)

What happens: I added several perks to my player like "*% Increased maximum life". After shutdown and reload the world my character starts without this extra life and then it get added as they are just gained. This results in hunger.
In other words: the "Increase max. life" perks eats through my food on each world load.

What is expected: The extra hearts get added on pre launch as the HPs of e.g. a Cyclic's heart container or Spice of Life's extras by different food.

Alternative solution: Config option to disable extra life to safe the food. (Disabling unwanted perks in config might be in general great.)

**Comment by Doomgull** [comment]
Welcome to what happens when leveraging vanilla health boosts. Both cyclic and sol use a custom handler to set it instead.

You can already use a perk seal to make perks you have selected not take effect.

**Comment by BuggaNoia** [comment]
Thx for your quick response. Is there any up to date wiki that tell me how to seal perks?

**Comment by Doomgull** [comment]
The Astral Tome is always up-to-date, and should always be considered the primary source of knowledge for this mod.
