### ISSUE TITLE
Server Crash when Iridescent alter placed

### ISSUE THREAD

**Issue by lifepack1** [HellFirePvP/AstralSorcery#1019]
Modpack: All The Mods 3 Remix 1.1.0
AS version: 1.10.11
Crash report: https://pastebin.com/axFbX38x
Issue: The server crashed the instant i placed the Iridescent alter after assembling the structure

**Comment by Doomgull** [comment]
While it happened when you placed an astral sorcery block, astral sorcery is not in that crash Trace. You need to open a ticket with this mod instead:

it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$MapIterator.nextEntry(Long2ObjectOpenHashMap.java:636)
