### ISSUE TITLE
Not sure how to setup spectral relay.

### ISSUE THREAD

**Issue by GeekBeam** [HellFirePvP/AstralSorcery#102]
The documentation on setting up the spectral relay to relay starlight to an altar does not specify how these sparks that go to the altar show up, and if they are a "stream" of sparks, then I have either not set it up correctly, or the relay isn't able to find my altar (which is about 6 blocks away)

**Comment by HellFirePvP** [comment]
Be sure the structure around it is correct. It - as expected - also needs a view to the sky. Additionally, as described in the journal, you need to place a glass lens onto it. If you've verified all that and it still doesn't seem to function properly, place the altar again and place the relay again. The order in which relay & altar are placed shouldn't matter either way normally.

**Comment by GeekBeam** [comment]
seems to work okay in single player, but not in a server environment. I placed everything correctly according to the journal, but it adds SO little starlight that it's hardly worth it. is one meant to put this in a spot of focused starlight?

**Comment by HellFirePvP** [comment]
It follows the same rules for collection as the altar *minus* the point where you have to place it in a spot of focused starlight. So night = more, higher up = more, has to have clear view of the sky, ...

**Comment by GeekBeam** [comment]
the particles are very different in singleplayer (there is no stream in MP at all, no matter how many times I replace altar and relay) and gives white and blue particles, while in SP, it gives grey particles. is that important at all?

**Comment by HellFirePvP** [comment]
Grey should never come up as color...
I'm going to double check this.

**Comment by HellFirePvP** [comment]
yep. confirmed. will fix for next version - idk about wht the particles are grey tho. must be some sort of lighting interaction

**Comment by HellFirePvP** [comment]
*Sigh* This bug came forth from my derpyness at porting the changes from 1.11.2 to 1.10.2 ... this will be fixed next version... :| Sorry for the inconvenience~

**Comment by GeekBeam** [comment]
I'm currently playing this on 1.11.2, it only shows up on the SMP server I play on.

the Relay works in Singleplayer, but NOT in SMP.

**Comment by HellFirePvP** [comment]
>_> pls kill me. i ported it correctly, the 1.11.2 version had the same problem >_> Sorry D:
