### ISSUE TITLE
Shooting Stars stuck in a loop near height limit

### ISSUE THREAD

**Issue by KumulaKai** [HellFirePvP/AstralSorcery#1021]
![2v2rtl](https://user-images.githubusercontent.com/17375475/53690509-e5820380-3d28-11e9-874b-463a5d37c965.gif)

Sorry it's not great, it was hard to capture. 
This is the pack we are using: https://drive.google.com/open?id=1RRAtrzS2AiCRcEMbRDCilQILbZKE6Hl9

I've seen up to 3 stuck at once. We are running it on a Serverminer server. Happens for everyone on the server. Any ideas on what it might be?

**Comment by HellFirePvP** [comment]
Most likely a desync between server and client.

**Comment by GalvenTreenock** [comment]
Alright, Thank you. I will see if i can do anything about it.
