### ISSUE TITLE
EntityLiquidSpark Lag

### ISSUE THREAD

**Issue by farigiss** [HellFirePvP/AstralSorcery#1023]
I ran TickProfiler to diagnose a lag problem, it showed EntityLiquidSparks taking up a lot of time.

So I teleport to my (not chunkloaded) Astral Sorcery base, When I get there I'm get <1FPS. Can't see the issue but when I run "/cofh killall EntityLiquidSpark" it killed 850 of them and the server lag and framerate problem went away immediately. 

This is on Direwolf20 v2.4.0 for 1.12.2 

Not sure why stuff is happening there when it's not chunkloaded either.

**Comment by Doomgull** [comment]
Chalice interaction entities. Sounds like your base is near the area of "partial loading" near worldspawn.

**Comment by farigiss** [comment]
It's about 800 blocks from spawn on a mountain in the middle of the ocean 500 blocks away from anything.

I don't think deactivating it with redstone is a solution. The chalice exists to automate things in the first place so I should be able to keep it running. 
Besides, this is on a server. You can't expect everyone on the server to know the chalice can get heavy on performance. And if people who think it's harmless log off, it will keep running because servers don't stop when the player quits.

Is there any reason these have to be entities rather than client-side particles?

**Comment by Doomgull** [comment]
Because that's how it handles creating new reaction outputs. The only way this could happen is if the chunk is loaded enough that tile entities are running, but entities are not, so it's caching them all until it loads. Hence why I asked about the spwn distance.

No different than a mob farm, ranch, normal farm, quarry, etc

**Comment by farigiss** [comment]
Then the fix would be to count the amount of entities spawned and stop spawning more, quite some time before it reaches 850. That's what nearly all mob spawners these days do.

Turns out Integrated Dynamics was loading the area, even though it shouldn't. I'm going there next.

**Comment by farigiss** [comment]
You can tag it "not a bug". I know it's not. But should you close it? It's still a legitimate issue. 
It's still an issue when 850 entities spawn to cripple your server for what is essentially a pretty particle effect.

**Comment by Doomgull** [comment]
It is no different than someone's farm overflowing items, or a quarry being set up inproperly.

**Comment by farigiss** [comment]
Yes but a quarry I can turn off, fix the error I made, and turn it back on. 
With this thing I can turn it off, report to the devs to fix it (because it's out of my control), then turn it back on. 

Also, it's doing it again and this time I'm there. No other mods doing anything with chunk loading this time. Went from completely unloaded to this. https://i.imgur.com/eGtNE9p.png. There's only about 300 entities and loading into the area was really choppy.

**Comment by Doomgull** [comment]
Should move them another 2 blocks apart so room to interact.
