### ISSUE TITLE
F3+T and AS CT integration

### ISSUE THREAD

**Issue by Yoghurt4C** [HellFirePvP/AstralSorcery#1025]
reloading resources makes JEI "forget" to relist all of the added [Altar](https://crafttweaker.readthedocs.io/en/latest/#Mods/Astral_Sorcery/Altar/) recipes; they still work ingame, but you're unable to look them up

constellating over from https://github.com/codewarrior0/coop/issues/1
AS 1.10.11
CT 4.1.14/15

**Comment by Saereth** [comment]
we are also experiencing this issue with jenkins build 82
we are able to reproduce this with the following modlist:
astral + JEI + Crafttweaker + the one probe

**Comment by Saereth** [comment]
xposted to jei
https://github.com/mezz/JustEnoughItems/issues/1508
