### ISSUE TITLE
Client crash: NPE in PerkLevelManager.resolveLevelCap

### ISSUE THREAD

**Issue by iarspider** [HellFirePvP/AstralSorcery#1026]
Modpack: Modern Skyblock 3
AS version: 1.10.11
GameStages version: 2.0.112
Forge: 14.23.5.2808

Crash log: https://gist.github.com/iarspider/10e64ff244fa44e45d0d239f834cfb90

**Comment by Doomgull** [comment]
That's an interesting one I've not seen before. Has it repeated?

**Comment by iarspider** [comment]
Already twice, both on first login to a server. Subsequent logons are fine (until server restart).

**Comment by iarspider** [comment]
_Maybe_ this happens because I've spend 1 skill point while still on 1.9.x version, and then updated to 1.10.11...

**Comment by Doomgull** [comment]
Would have overwritten, wouldn't trigger this.

**Comment by MishTish** [comment]
Hello, I also get a crash on MSB3, (don't know if it's this one, but log looks kind of similar) there is something with astral sorcery in my log.
It crashes when I enter my world. I tried loading a backup and that helped... but, now the backup version also crashes

https://pastebin.com/ng3XSYmB

**Comment by Doomgull** [comment]
Can you verify the level cap setting in client config and server config, and also upload your player.astral file?

**Comment by MishTish** [comment]
I:levelCap=30
in my config file

[a6278038-fe4e-4257-bdfe-fe50dbd892cf.astral.txt](https://github.com/HellFirePvP/AstralSorcery/files/2946109/a6278038-fe4e-4257-bdfe-fe50dbd892cf.astral.txt)

**Comment by Doomgull** [comment]
And in the server config file?

**Comment by MishTish** [comment]
where it's located?

**Comment by Doomgull** [comment]
On the server

**Comment by MishTish** [comment]
I'm playing in singleplayer (Sorry for being stupid)

**Comment by iarspider** [comment]
Server `I:levelCap=30`
Client `I:levelCap=30`

<uuid>.astral file (inside zip):

[57cc09c4-0440-4eef-9419-8aa4425cfe12.zip](https://github.com/HellFirePvP/AstralSorcery/files/2947168/57cc09c4-0440-4eef-9419-8aa4425cfe12.zip)
