### ISSUE TITLE
[Possible Bug] Sky is rendered purple instead of blue

### ISSUE THREAD

**Issue by WesCook** [HellFirePvP/AstralSorcery#103]
I'm not sure if this is a feature or a bug, so please excuse me if this is known.  I couldn't find any relevant bug reports.

In recent versions of Astral Sorcery, the sky is purple instead of blue.  I checked out some old betas to see when this changed, and it looks like 1.1.4 was the first build to change this.

Latest (v1.3.0)
![2017-04-10_12 29 25](https://cloud.githubusercontent.com/assets/792101/24878807/781d598a-1de9-11e7-84ce-5398b09b7b5a.png)

Normal (v1.1.3)
![2017-04-10_12 27 33](https://cloud.githubusercontent.com/assets/792101/24878813/7b555486-1de9-11e7-9485-88bfc62ba788.png)

I can replicate this with just Astral Sorcery using default configs.  Tested in Forge versions 13.20.0.2282 and 12.18.3.2281 (current latest beta).

**Comment by HellFirePvP** [comment]
Uhh...... my bad. derp.
