### ISSUE TITLE
[Suggestion] Config to change ability of spectral wings key perk

### ISSUE THREAD

**Issue by Water-Cat1** [HellFirePvP/AstralSorcery#1033]
I am trying to create a pack that does not include creative flight in survival. So I was wondering if it would be possible to have a way to change the spectral wings perk to something else or disable it. 

As I am still allowing elytra style flight, a possible change of effect could be an elytra rocket boost ability. Such an ability would be when flying with the vicio mantle, right clicking with an empty hand produces a boost effect like using a firework rocket.

**Comment by Doomgull** [comment]
Use the existing CT integration to disable that perk from the tree:
https://github.com/HellFirePvP/AstralSorcery/blob/master/AS-Example.zs

You cannot add new perk effects, only modify the values, or remove perks.

**Comment by Water-Cat1** [comment]
Oh thank you! Did look at CT but must have missed the documentation for this.
