### ISSUE TITLE
IIngredient Support for Light Transmutation

### ISSUE THREAD

**Issue by Vyraal1** [HellFirePvP/AstralSorcery#1036]
Would it be possible to get IIngredient support for Light Transmutation? I can iterate through an oredict and get each iitemstack individually but it would also flood JEI with a lot of redundant copies (especially if there are variant in ores such as Endstone iron, Netherrack Iron, Granite Iron ores like in Gregtech).

**Comment by HellFirePvP** [comment]
Not being addressed as light transmutation itemstacks are converted into blockstates and are only passed as itemstacks due to legacy support and JEI display.
