### ISSUE TITLE
Chrash while loading

### ISSUE THREAD

**Issue by Rams59** [HellFirePvP/AstralSorcery#1037]
I try to make myself a Modppack but Evilcraft always chrashes while Initialising

[crash-2019-03-20_16.12.33-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/2988836/crash-2019-03-20_16.12.33-client.txt)

**Comment by Doomgull** [comment]
AS isn't listed in that trace? Check with evilcraft/cyclops core.
