### ISSUE TITLE
[1.11.2 - 1.3.0b] Astral Relay does not give gathered starlight to nearby altar in multiplayer environment.

### ISSUE THREAD

**Issue by GeekBeam** [HellFirePvP/AstralSorcery#104]
after making sure I had it setup correctly, and checking in singleplayer, the relay does NOT connect to the nearby altar when it should (I mirrored the setup from singleplayer into the multiplayer environment).

in singleplayer, the particles of the relay are uniformly gray colored, but there is a small stream of particles pointing towards the altar.

in Multiplayer, the Particles render with the correct set of colors (white and blue) but there is no stream of particles pointing at the altar, NOR is there any change in the amount of starlight within the altar (tested with multiple relays, all active, and inactive).

**Comment by HellFirePvP** [comment]
Duplicate - See #102 for details
*runs in shame*
