### ISSUE TITLE
Enigmatica 2 Expert pack - Astral Rituals blocked by Thaumcraft Arcane Lamp 'light'

### ISSUE THREAD

**Issue by 64Hz** [HellFirePvP/AstralSorcery#1041]
Astral Sorcery version 1.10.11 on the Enigmatica 2 Expert modpack on Twitch.

It seems that the artificial 'invisible' light sources creative by the Thaumcraft Arcane Lamp blocks the ritual pedestal/structure from working. As the light source is invisible I had to fill in the block spaces by around 15 y levels to get rid of the light source.

Only other light source available for my current area was the 'Cave Illuminator' so I suspect the Arcane Lamp is at fault.

Could this light source be whitelisted to allow the rituals to work regardless?

**Comment by Doomgull** [comment]
Yes, anything within the space of the multiblock will cause it to fail to form. This is by design. #986 for more information.
