### ISSUE TITLE
Client Crashes since I attuned

### ISSUE THREAD

**Issue by lilpup618** [HellFirePvP/AstralSorcery#1044]
I got myself attuned, and now it crashes me whenever I try to load into the world.

**Comment by lilpup618** [comment]
Its a multiplayer server on a custom pack based off of enigmatica 2 expert.

**Comment by Doomgull** [comment]
Please upload a log to pastebin and link it here. Cannot do anything without logs. That's like telling your mechanic over the phone "My car makes a noise". Literally useless.

**Comment by lilpup618** [comment]
https://cdn.discordapp.com/attachments/557518273630175255/558846639524020242/crash-2019-03-22_19.55.28-client.txt

**Comment by Doomgull** [comment]
Delete your client side config for astral sorcery, and try again. Something is desync between client and server.

**Comment by lilpup618** [comment]
Where would the config be?

**Comment by lilpup618** [comment]
https://pastebin.com/iGJhtmri

**Comment by Doomgull** [comment]
#1026
