### ISSUE TITLE
Crash when trying to infuse stuff

### ISSUE THREAD

**Issue by Flamebom** [HellFirePvP/AstralSorcery#1045]
https://paste.dimdev.org/fepoveroho.mccrash

I'm pretty sure it's astral sorcery because it was the only mod i was doing anything with at the time. Also couldn't infuse stuff after rightclicking with wand. (Made sure i had 12 buckets of liquid starlight too)
Items aren't rendering on the infuser either

**Comment by Doomgull** [comment]
It's a vanilla network error. Can you try without vanillafix? It does some weird things.

**Comment by Flamebom** [comment]
yeah works fine without vanilla fix, i'll just have to deal with the rendering issue i guess
