### ISSUE TITLE
Containment chalice interactions bug

### ISSUE THREAD

**Issue by PCThrow** [HellFirePvP/AstralSorcery#1048]
Three chalices in a triangle, but only two interact like they are supposed to.  Turns out that the chalice at the top is on the edge of a chunk and the chalice that doesn't interact is on the other side, effectively the next chunk over, even if it's only 3 blocks away.  Is this supposed to happen?

**Comment by Doomgull** [comment]
Screenshot?

**Comment by PCThrow** [comment]
Ok, I can't.  It is working fine when I moved the chalice back to the previous position, on the other side of the chunk line.  Still not getting drops from that chalice and the liquid starlight, but am getting them from the chalice with lava in it.  It looks like the lava entities are killing the starlight ones and making it to the water ones first.

**Comment by PCThrow** [comment]
Found it again.  Here is a screenshot.
