### ISSUE TITLE
[1.12.2-1.10.12] Game keeps giving Astral Tome on each time you load game

### ISSUE THREAD

**Issue by Kazzamkablam** [HellFirePvP/AstralSorcery#1052]
Yeah, it's filling my inventory with Astral Tomes for some reason.

**Comment by Doomgull** [comment]
Already fixed in-dev.

**Comment by kreezxil** [comment]
I've got a ton of players getting free books that they are funneling into recycling machines, didn't find that out till tonight. Can you please push the indev to curseforge? And yes great mod.

**Comment by captcookie** [comment]
yes this is so broken.

**Comment by Doomgull** [comment]
Pull the indev version from jenkins in the discord server, then, if it's that important. You DO realize the reason it's not been pushed to curse is because there's more stuff involved than just that one thing, right? And there's partial code involved?

**Comment by kreezxil** [comment]
actually, I guess I should've responded again, that I realized that it
wasn't pushed because there's a config that turns it off, so problem solved
partially via config.
