### ISSUE TITLE
[suggestion]Whitelist for Lucerna Ritual (Slimes!)

### ISSUE THREAD

**Issue by Dr-Zoidberg-de** [HellFirePvP/AstralSorcery#1055]
a config entry for mobs (vanilla mobs are sufficient) to ignore them in the lucerna ritual would be more than awesome (if technically possible) 
i just realized all my mana pools are empty due to lucerna blocking the narslimmus
sorry if this had been suggested before, i checked but i tend to overread stuff.

**Comment by Doomgull** [comment]
Configurable whitelist/blacklists are already on the master suggestion tracking list.
