### ISSUE TITLE
[Enhancement] Add a way to visualize a multiblock structure similar to botania.

### ISSUE THREAD

**Issue by levicc00123** [HellFirePvP/AstralSorcery#1056]
I'm not one of those people who can look at a picture and replicate it. If there is already such a thing in game, please accept my apology, as I was not able to find it.

**Comment by Doomgull** [comment]
Sextant does this.

**Comment by HellFirePvP** [comment]
Sextant does this.

Also, the structure preview has now been changed to be similiar/akin to how i changed it in Modular Machinery. So it's more helpful and clearly outlined and serves as build-guide layer-by-layer, only advancing if the previous layer matches what's required. This will be then released with the next update.
