### ISSUE TITLE
How to break Crystal Collector that you made?

### ISSUE THREAD

**Issue by SolSavvy** [HellFirePvP/AstralSorcery#1058]
I might be stupid, but I have searched for 3 days now trying to find out how to break Collector Crystals that i made myself. I need to move it out of the way to install a Celestial Collector Crystal Multi-Block structure, but nothing will break it. Do crystal tools break them, because thats the only thing i havent tried yet?

**Comment by SolSavvy** [comment]
I cheated and gave myself a Crystal pickaxe to break it. the astral sorcery guide needs to speak more plainly

**Comment by Doomgull** [comment]
Needs to be the equivalent of vanilla diamond pickaxe. No different than rock crysytal ore.
