### ISSUE TITLE
Attunement Altar recipe not appearing

### ISSUE THREAD

**Issue by SolSavvy** [HellFirePvP/AstralSorcery#1059]
I removed the relays that were previously set down forming Armara, then I held the Aevitas scroll in my hand/off-hand to look for the blue recipe markers to place them down, but they wont appear. I quit and restarted and it still wont appear. I dont remember the recipe off the top of my head so this is brought my progress on my Mantle of Stars Attunement. Please Help? 

![2019-04-08_01 28 21](https://user-images.githubusercontent.com/27328200/55700749-8904aa80-599e-11e9-81b9-1cd003905551.png)

edit: the snow covering has never impeded me putting down relays before so i dont know why it would start now

**Comment by Doomgull** [comment]
Because it breaks the multiblock check. No sparkles on the sooty marble means it isn't fully formed. Not formed, no blue smoke indicators. Come to the discord server if you still have issues afterward.
