### ISSUE TITLE
[1.11.2 - 1.3.0b] Ticking Entity Crash. 

### ISSUE THREAD

**Issue by GeekBeam** [HellFirePvP/AstralSorcery#106]
not sure exactly why this happened...maybe you can figure this out?

[[Log]](http://puu.sh/vgqif/729e07f2ca.txt)

**Comment by HellFirePvP** [comment]
Uhh... Given that this map actually never becomes 'null' anywhere, i'm uncertain how it can even reach this state. Will look into it.

**Comment by HellFirePvP** [comment]
i'm not entirely sure why this happened to begin with, but i've added a small safety-check around it so it shouldn't happen anymore at least.
