### ISSUE TITLE
Dupe bug with RFTools Storage Scanner and Ritual Pedestal

### ISSUE THREAD

**Issue by Fladorius** [HellFirePvP/AstralSorcery#1061]
I found a dupe bug using the Ritual Pedestal and RFTool Storage Scanner. It seems like it can dupe any item, but only one item at a time, and doesn't seem like it can be easily automated. Steps are below, and I have a short video that demonstrates it, starting from step 3. This was in single player with just the mods below (and their dependencies). I haven't had a chance to verify if the issue still exists in a MP server environment or not.

Versions:
MC 1.12.2
Forge: 14.23.5.2825
Astral Sorcery: 1.10.12
RF Tools: 7.61

Steps:
1) Set down a AS Ritual Pedestal, RFTools Storage Scanner, feed the scanner power.
2) In the Storage Scanner UI, increase the scan radius to pick up the pedestal, then scan, then make the pedestal a routable inventory.
3) Insert into the blue slot of the scanner the item you want to dupe (or shift+click)
4) Click the item out of the scanner UI in the upper right.
5) Go to the ritual pedestal and shift right click to remove a duplicated item.

https://youtu.be/asJqI8OudCI

**Comment by Doomgull** [comment]
Considering the inventory isn't supposed to be directly acessible via "normal" methods, such as pipes, but only by right clicking, this probably needs a ticket opened with rftools for how it interfaces with the internal inventory slot.
