### ISSUE TITLE
Astral Sorcery - Mekanism crash conflict

### ISSUE THREAD

**Issue by Byomakuta** [HellFirePvP/AstralSorcery#1064]
there seems to be a conflict with crafting ingredients between mekanism with Astral Sorcery's new update
[astral_sorcery_-_mekanism_crash.txt](https://github.com/HellFirePvP/AstralSorcery/files/3066456/astral_sorcery_-_mekanism_crash.txt)

**Comment by HellFirePvP** [comment]
Same as #1063
