### ISSUE TITLE
crash with fluid rarities server side

### ISSUE THREAD

**Issue by Saereth** [HellFirePvP/AstralSorcery#1068]
We saw this crash once before in beta, dont remember how we fixed it but some people are reporting this again but it doesnt happen for everyone, I myself can't reproduce it. 

https://hastebin.com/vowojevoca.sql

content of fluid rarities file:

```
data {
    S:data <
        oil;4000000000;1000000000;7500
     >
}
```

**Comment by ClockwiseGear** [comment]
I'm seeing this as well in FTB Interactions whenever I create a new world:
https://pastebin.com/55229vZ7

**Comment by brad18** [comment]
I'm experiencing this as well. FTB interactions 1.2 server boots up fine when creating a new world but crashes with the below error when trying to load my FTB interactions 1.0.1 world.

[crash-2019-04-11_23.31.48-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/3070845/crash-2019-04-11_23.31.48-server.txt)

**Comment by zepanv** [comment]
FTB Interactions upgraded from 1.1.2 to 1.2.0, was fine for a bit, started exploring and now world crashes on load.

https://paste.feed-the-beast.com/view/0ee538e4

**Comment by kynapse** [comment]
Server-side crash after we upgraded FTB Interactions to 1.2.0

https://gist.github.com/kynapse/146839ea62cf8f9a872b7fb68ec5162e

**Comment by bobwood** [comment]
Updated from 1.0.1 to 1.2.0 beta.  Crashes when entering world.

[crash-2019-04-11_17.48.14-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/3070905/crash-2019-04-11_17.48.14-server.txt)

**Comment by hobnob11** [comment]
https://paste.feed-the-beast.com/view/6fbb61bc
server crash playing ftb interactions after updating to 1.2.0

**Comment by darthvader925** [comment]
[crash-2019-04-11_15.50.15-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/3070918/crash-2019-04-11_15.50.15-server.txt)

**Comment by Dr-Turtle** [comment]
https://pastebin.com/90SvtCSr
Game and server crashed after entering the overworld from the voidworld. Server now crashes on login. One of the attempts showed some loaded chunks in the overworld for about a second, followed by server crash.

**Comment by bobwood** [comment]
May be related to certain numbers in AS fluid_rarities.cfg being larger than max int.

**Comment by Kanzuke117** [comment]
Setting values down to maxint allowed the player near the affected chunk to rejoin again without crashing.

**Comment by Doomgull** [comment]
If others could confirm Kanzuke117's config change works on their side, could be helpful.

**Comment by darthvader925** [comment]
it seems the config file here fixed it when replaced
[fluid_rarities.cfg.txt](https://github.com/HellFirePvP/AstralSorcery/files/3070998/fluid_rarities.cfg.txt)

**Comment by kynapse** [comment]
Kanzuke117's config change works for me.

**Comment by Glorken** [comment]
Can confirm that capping it at maxint stopped the world from crashing on join.

**Comment by hobnob11** [comment]
Kanzuke has saved our server, all is fixed now because of him.

**Comment by The-Snakes** [comment]
Can confirm issue is resolved after changing line 12 from fluid_rarities.cfg file.

Before:
        oil;4000000000;1000000000;7500
After:
        oil;4000000;1000000;7500

You can replace the file from below path with the one attached after removing .txt extension.
Local:
C:\Users\%username%\Documents\Curse\Minecraft\Instances\FTB Interactions\config\astralsorcery\
Server:
FTBInteractionsServer_1.2.0\config\astralsorcery\

[fluid_rarities.cfg.txt](https://github.com/HellFirePvP/AstralSorcery/files/3071610/fluid_rarities.cfg.txt)

**Comment by HellFirePvP** [comment]
Before we all comment "same" or "thanks, fixed it for me too":

The first and 2nd number added together must not exceed 2147483647. That's the whole "magic" behind the fix. So adjust the numbers as you see fit or wait for a FTB Interactions update.

Please refrain from adding more "same" or "that fixed it for me" comments.
Thank you.

**Comment by Saereth** [comment]
this was actually a simple typo, the numbers should quite literally both have one less zero
