### ISSUE TITLE
VR compatablity issues

### ISSUE THREAD

**Issue by SteamDoge9000** [HellFirePvP/AstralSorcery#1069]
Hello it apears as if this mod glitches out a mod called Vivecraft

a Virtual Reality mod

it causing some severe gamebreaking issues

i recomdend investigation

let me know if the issue is relivent
[latest.log](https://github.com/HellFirePvP/AstralSorcery/files/3071090/latest.log)

**Comment by Doomgull** [comment]
#1036

Update to 1.10.14 or install crafttweaker

**Comment by SteamDoge9000** [comment]
nvm
jsut an issue just notieced the update
