### ISSUE TITLE
Celestial Gateways are not teleporting

### ISSUE THREAD

**Issue by JackRuby1** [HellFirePvP/AstralSorcery#1073]
Celestial Gateways are not teleporting the player around, when looking at the star and pressing shift, it zooms in and does the effects over and over again like it's teleporting you, but you go no where. This is happening from both sides of it, it's even got the snapshot image of the destination.
version astralsorcery-1.12.2-1.10.12 (2) in sf4 beta

**Comment by Doomgull** [comment]
Any claiming involved, or plugins that might involve player movement?

**Comment by justinrusso** [comment]
No claiming type mods or plugins (I play on the same server)

**Comment by darkphan** [comment]
This happens with just Astral Sorcery, no other mods.

**Comment by HellFirePvP** [comment]
Astral Sorcery version was outdated

**Comment by JackRuby1** [comment]
Thanks HellFire!
