### ISSUE TITLE
Iridescent Altar crafting not startable if JEI autofill is used.

### ISSUE THREAD

**Issue by Janitor53** [HellFirePvP/AstralSorcery#1075]
Forge-14.23.5.2816
Astral Sorcery: 1.10.15
When I started to craft observatory and first ghost image of the illumination powder appears at the spectral relay I figured out that I forgot to craft those powders. So I terminate the process by removing attuned rock crystal from altar (idk why). Then I crafted all the powders I need and returned to the altar, but I can't craft Observatory again. There is no resulting image on the right side of GUI and right clicks with resonating wand does nothing.
I tried to remove/replace the altar, try another night, but no results.
Images:
https://i.imgur.com/YjEGeaE.png
https://i.imgur.com/yYoYvYd.png
**Upd:** Downgrade to mod version 1.10.14 fixed this.

**Comment by washinoboku** [comment]
Same problem here with 1.10.15. Can't craft at first try even if everything is correct. Downgrade to 1.10.14 fixed.

**Comment by HellFirePvP** [comment]
Cannot reproduce this..

**Comment by washinoboku** [comment]
I was checkin my custom modpack, delete NoMoreRecipeConflict 0.13 and update Astral Sorcery to 1.10.17, well every recipe for Iridiscent Altar works again.
Sorry for not figured out this earlier.

**Comment by Fedwick** [comment]
this happened to me too, i was unable to craft the observatory in enigmatica 2 expert and in my custom test pack. the versions i tried are .15 and .17. You can not reproduce it because you summon the infused glass needed in the recipe in cheat mode and the recipe works, though if you manually try to craft it (the infused glass ) in survival the recipe for the observatory does not work ! also if you try to craft the resplendent prism the altar does not work, but if you summon the shifting star, that it is needed by the recipe, using cheat mode and then craft it, it works. I hope this makes sense.

**Comment by Doomgull** [comment]
Sounds like the modpack changed recipe then

**Comment by Fedwick** [comment]
enigmatica 2 expert does not change these 2 recipes,  it's a bug a tried it in my custom mod pack too and above a gave you the way to replicate it.

**Comment by Doomgull** [comment]
And yet, the recipes have had no changes in many, many versions. Especially not across the ones you listed didn't work, vs the ones that did.

And I will test again, but I don't creative mode pull items to test with in the first place.

**Comment by Fedwick** [comment]
if you cant replicate cancel the recipe and try again as the guy that reported first said

![New Bitmap Image](https://user-images.githubusercontent.com/24882575/56773659-ca32f200-67c7-11e9-85a6-9f2f32349daf.jpg)
![New Bitmap Image (2)](https://user-images.githubusercontent.com/24882575/56773663-ce5f0f80-67c7-11e9-8d75-862fdd62273c.jpg)

**Comment by HellFirePvP** [comment]
On that note i did re-test it by crafting all components individually and then using the crafted ones instead ones from JEI or creative-tab. Cannot reproduce this. Am gonna try checking mod interactions with other mods potentially attaching data or stuff..

**Comment by CoffeeFueledPanda** [comment]
Hey all,

I can confirm that the recipe didn't work, until I cheated in the item as displayed in the images.

**Comment by Doomgull** [comment]
@CoffeeFueledPanda what pack?

**Comment by CoffeeFueledPanda** [comment]
@Doomgull It's a self put together collection of mods, did update to latest update and hopefully it will behave now.

**Comment by Fedwick** [comment]
jei_1.12.2-4.15.0.275 enigmatica
jei_1.12.2-4.14.4.264 my pack
astralsorcery-1.12.2-1.10.17 both packs

**Took me a few days but i found out that jei autocomplete is to blame for this issue !**
tested in enigmatica 2 expert and in my test pack

every time you auto complete this recipe it brakes it for the survival crafted infused glass

1.manually place all the ingredients in the altar with the survival crafted infused glass --> it works
2.jei auto complete with the survival crafted infused glass --> does not work
3.try to manually place all the items again and it does not work till you restart your game !
4.jei auto complete with the "cheated in" infused glass --> it always works

note : cheated in infused glass has an nbt value and survival crafted infused glass does not
![2019-05-04_03 00 46](https://user-images.githubusercontent.com/24882575/57171465-6179f400-6e1d-11e9-8ecd-2d2c4b9406cf.png)

shall i report this to JEI ?

**Comment by pulli23** [comment]
For me this "trick" also doesn't seem to work. What works is "restarting" the server many times and just trying each time - before opening inventory or any crafting station.
