### ISSUE TITLE
I know the issue is AstalSorcery but what is it conflicting with?

### ISSUE THREAD

**Issue by RepoDraghon** [HellFirePvP/AstralSorcery#1076]
If I disable AS the game works, so what is it conflicting with?
[crash-2019-04-15_18.53.38-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/3082727/crash-2019-04-15_18.53.38-client.txt)
[2019-04-15-1.log.gz](https://github.com/HellFirePvP/AstralSorcery/files/3082729/2019-04-15-1.log.gz)
[debug.log](https://github.com/HellFirePvP/AstralSorcery/files/3082730/debug.log)

**Comment by Doomgull** [comment]
Not AS, just AS triggering it:

"java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded."

**Comment by RepoDraghon** [comment]
so how do I fix it so it wont trigger it?

**Comment by HellFirePvP** [comment]
> maximum id range exceeded

you ran out of item ids. whatever your pack is, it's too large.

**Comment by RepoDraghon** [comment]
interesting since I didn't have this issue before... I recently had to reinstall my OS and before that the mods I had all worked fine... it's only now that I'm getting this error... thanks for your help

**Comment by RepoDraghon** [comment]
Hey, just wanted to let you know, I figured out the problem... A necessary mod called NotEnoughIDs wasn't installed in the Direwolf20 pack... that mod's purpose is to extend the limit you told me about...
