### ISSUE TITLE
Astral Progression Bugged

### ISSUE THREAD

**Issue by Hikuno** [HellFirePvP/AstralSorcery#1077]
Alright, so my friends and I are running a dedicated server. Specifically we are using a modpack from FTB (feed the beast). The mod pack is 'FTB Revelation (v2.7.0) Minecraft Version 1.12.2' 

I unlocked Radiance in the progression line of Astral Sorcery, made myself Attuned to Discidia, made an enchantment table from AS. Wrote down my knowledge on a scroll to turn it into a scroll of written knowledge to catch up a friend and showing him the ropes of AS. Shortly after I noticed that my attunement altar was not lighting up anymore. I switched constellations even. I also noticed that the constellations in the sky were no longer showing. I can no longer attune anything to a constellation. 

Did I screw up by making the scroll of knowledge? I have tried switching dimensions to see if it was ui error, but got nothing. There were no changes in any ini or config files for the server.

**Comment by Doomgull** [comment]
Those things are unrelated. Has the server been restarted?

**Comment by Hikuno** [comment]
Yes a couple of times. We just had another person on the server start their AS progression from the very beginning and they themselves can not see constellations either.

**Comment by Doomgull** [comment]
Was time changed via command?

What version of AS is involved?

What does your tome contain for chapters?

**Comment by Hikuno** [comment]
Time has been changed via command by operators of the server.

Astral Sorcery Version 1.12.2-1.10.10

Tome has Radiance.

If it's an issue with the time being changed due to commands, it was not a problem previously. Though I am not on all the time, so I can not say what time commands have been used. The most frequent one that is used in the server is the day/night advancement that is integrated into the JEI UI display.

**Comment by Doomgull** [comment]
Reason I asked is #875.

**Comment by Hikuno** [comment]
Hmm, is there a sort of fix for it that you know of? 
I read through the post and went to direct link from the FTB forum post also.

"Discovered constellations still show up blue but the sky is otherwise black. " In my instance there are no signs of any constellations faded or bright.

**Comment by Doomgull** [comment]
Can tet the "/time set night" command, but other wise goibg to need one of the player.aatral files for a player affected to look at.

Is there sponge installed on the server?

Again, the systems are
