### ISSUE TITLE
World leaking memory.

### ISSUE THREAD

**Issue by Roonas** [HellFirePvP/AstralSorcery#1079]
Mods installed:
- Baubles 1.5.2
- Astral Sorcery 1.10.3
- Forge 14.23.5.2768

Log throwing _[19:23:50] [Server thread/DEBUG] [FML]: The world 23f63a11 (New World) may have leaked: seen 35 times._ Happens consistently across new or established worlds across multiple tests. Analytics are showing that this is not a potential leak, but an ongoing one based off consistent rise is memory use.

[Log here.](https://paste.ee/p/nWFqc)

**Comment by Doomgull** [comment]
Your AS version is massively out of date. Update to newest and try again.

**Comment by Roonas** [comment]
Updated to Forge version 14.23.5.2781 and the latest version of AS 1.10.15, a fresh world is already leaking memory. [Log](https://paste.ee/p/VKBXd)

**Comment by Doomgull** [comment]
It isn't a leak if it is in use. Run the log for more than 3 minutes in a new world.

Or perhaps something actually useful other than forge guessing based on memory usage.

**Comment by Roonas** [comment]
I am open to suggestions as to what constitutes as "more useful." Will update this comment with a new log recording 30min if you'd like.

**Comment by Doomgull** [comment]
Get a VisualVM profile running showing exactly what is eating memory. Export it for tracing.
