### ISSUE TITLE
[AstralSorcery-1.11.2-1.3.0-Beta] Sky changes color at Y: 92

### ISSUE THREAD

**Issue by DeadPigman17** [HellFirePvP/AstralSorcery#108]
![2017-04-11_17 46 05](https://cloud.githubusercontent.com/assets/22800252/24917867/ca362620-1ede-11e7-84eb-6dd5e37d6d77.png)
![2017-04-11_17 46 09](https://cloud.githubusercontent.com/assets/22800252/24917883/cf82d164-1ede-11e7-9038-b709ed476f53.png)

I have other mods installed, but I've tested this without AstralSorcery installed and the sky color is fine.

**Comment by HellFirePvP** [comment]
I know this is happening, however i couldn't find the source for it yet. Will continue to search :|

**Comment by HellFirePvP** [comment]
Well, i guess i'm gonna adress this with the first solution that solved this problem; It's not a great one so i'll need to get back to it eventually, but it'll solve this for now with no visible other issues.
