### ISSUE TITLE
Invalid meta type 14 - causing server disconnections

### ISSUE THREAD

**Issue by Yorkforce** [HellFirePvP/AstralSorcery#1080]
With this mod enabled our bungeecord reports an invalid meta type error and kicks players from the server:

Server Log:
https://pastebin.com/5RRyJR7A

Tested on 1.10.13 and 1.10.15 both cause the problem.
Version 1.8.5 works fine.
(Sorry for the odd version tests, we just happened to have 3 modpack servers running, the one with 1.8.5 doesn't have a problem, the other 2 with 1.10.X do).

https://github.com/Darkosto/SkyFactory4Issues/issues/307
https://github.com/SpigotMC/BungeeCord/issues/2294

**Comment by HellFirePvP** [comment]
Bungeecord issue, not my mess.
Custom data serializers for entities are commonplace in a forge environment and are supported by forge.
If md5 doesn't wanna do anything to support a forge feature, guess i'll call this complete incompatibility.

Case closed.

**Comment by Yorkforce** [comment]
No worries I understand

We usually run into this problem, one person says this, another says that, another turns their back while the blame game and stubbornness begins and so it has been for years in the minecraft modding community.
Can't say I blame people for standing thier ground though, just a shame there are hardly any modded servers left, or players, but with so much hassle in hosting modded servers, it's not all that surprising.

Just hope none of the other 212 mods in the pack start using custom data serializers that cause issues, else it could actually become a common problem and there won't be any servers left. Hard to see any mods or modpacks then.

**Comment by Doomgull** [comment]
Could also not run bungeecord like most servers out there.

**Comment by Yorkforce** [comment]
Wish we could but with 12 other servers on our network, that would be extremely difficult. We can only get 4 IPs from our dedibox provider so we would have to start asking players to use multiple server URLs with ports on the end instead of just a single url for all of them.

**Comment by i9hdkill** [comment]
`Custom data serializers for entities are commonplace in a forge environment`
Sorry, but that isn't true. We run major modpacks just fine with Sponge and Bungee for years. This mod is one of the veeery few that are doing that stubborn stuff

`Could also not run bungeecord like most servers out there.`
Thats like the most idiotic answer on this
