### ISSUE TITLE
Night Vision enchantment can be put on all armor pieces but works only on helmets

### ISSUE THREAD

**Issue by Hubry** [HellFirePvP/AstralSorcery#1081]
Self explanatory title. Tested on 1.10.15, on Forge 14.23.5.2836. 

While I am sure the solution people want is "make it work on everything", you would rather make it actually only go on helmets.

**Comment by HellFirePvP** [comment]
https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/enchantment/EnchantmentNightVision.java#L30

Some mod apparently ignores as to what it can be put on. Because the "normal" way, you can only get it on helmets as intended.

**Comment by Hubry** [comment]
Hellfir I tested this on an instance with literally only AS as a content mod, I can retest this after disabling literaly everything else real quick :P

**Comment by Hubry** [comment]
Literally just AS + Baubles.
![image](https://user-images.githubusercontent.com/26120076/56371176-e7325880-61fc-11e9-99f2-d25148b303af.png)
