### ISSUE TITLE
Crash when creating Single Player world with V 1.10.16

### ISSUE THREAD

**Issue by aking4125** [HellFirePvP/AstralSorcery#1083]
Game crashes with 1.10.16 when creating a single player world. Works fine in 1.10.15

https://paste.dimdev.org/onaxeqolir.mccrash

**Comment by HellFirePvP** [comment]
Happens in an environment without crafttweaker. fix coming up in a second.

**Comment by aking4125** [comment]
Whoops. Didn't know crafttweaker may have been required

**Comment by HellFirePvP** [comment]
1.10.17 is released that fixes this.

No it's not required, but there was some "weird" dependency as it crashes without it. I don't wanna go into further detail for simplicity's sake.
