### ISSUE TITLE
server perk crash

### ISSUE THREAD

**Issue by kreezxil** [HellFirePvP/AstralSorcery#1085]
I don't know what my players were doing to trigger this

http://paste.ubuntu.com/p/hHMZkQrgT9/

version: 1.12.2-1.10.17
pack: World of Dragons (mine)
MC VERSION: 1.12.2-14.23.5.2836

**Comment by HellFirePvP** [comment]
Does this happen 'often'? If so, this happened on someone connecting to the server, so maybe try nailing down who this could be - should it be a somewhat smaller server - and try to replicate this. 

Should it be somewhat reproducible, please do consider turning on perk logging (astralsorcery.cfg -> general -> debug_logging -> PERKS) and then do this again. The log will then contain essential information that'll help me greatly fixing this...

**Comment by kreezxil** [comment]
are these perks for players who have donated to you patreon? or is it
something else?

I'll turn that on, hopefully the crash will happen again.

**Comment by Doomgull** [comment]
There is nothing mechanical for patreons. All patreon effects are untied to any other AS system, and purely decorative.

**Comment by ChakatSilverpaw** [comment]
I think I have a similar error going on. It happens every time I try to Log in, It brings the server down.
https://pastebin.com/s7xZFdfw

**Comment by Doomgull** [comment]
@kreezxil See hellfire's instructions above

**Comment by liny-odell** [comment]
Just a note, ChakatSilverpaw's crash log is from their client, not the server, however, the server goes down with the same crash log, but which crashes first seems random, but both make the same stack (they play on my server so im the one now dealing with how to clean up the crash). Ill run the server with debug logging enabled and past the logs for that in a bit.

**Comment by liny-odell** [comment]
Ok, this was a weird one, fired up the server with debug logging enabled like asked, had silverpaw try to connect, they did, but were dead on logging in, they tried to respawn but it wouldnt let the, but each time they tried, the server spat out the same callstack but didnt crash. Stopped the server then collected the log file and here it is, hope this helps.

[latest.zip](https://github.com/HellFirePvP/AstralSorcery/files/3159522/latest.zip)

**Comment by HellFirePvP** [comment]
Thank you very much, yes!

**Comment by HellFirePvP** [comment]
Is it possible to get to know what modifiers the gem has that `Chakatsilverpaw` has in the gem socket?

**Comment by ChakatSilverpaw** [comment]
7% movement speed, 7% reach, I beleive.

**Comment by liny-odell** [comment]
if wanted, i can package up the world folder and send it if it will help any

**Comment by HellFirePvP** [comment]
Yes i found the exact issue. Will fix this reasonably soon.
