### ISSUE TITLE
Irradiant star wont craft?

### ISSUE THREAD

**Issue by Mase7139** [HellFirePvP/AstralSorcery#1086]
when trying to craft the star the altar wont show anything or accept it
![2019-04-26_23 32 38](https://user-images.githubusercontent.com/39789159/56804967-a5985200-687b-11e9-91e2-09c3440962cf.png)

**Comment by Doomgull** [comment]
I'm having issues replicating.

Can you confirm it was night time, the recipe matches what was in the Tome, and pack and AS version?

**Comment by Deregorn** [comment]
I can confirm this, I have the same issue. I tried to craft an Irradiant Star (Aevitas). The recipe is correct (same as in the picture). It was night time, I used an Aevitas Collector Crystal above the altar and inserted a Celestial Crystal attuned to Aevitas in the left slot of the altar. I tried with both 6 relays and 8 relays placed around the altar. The starlight bar was completely filled.

Btw, this was happening in the modpack SkyFactory 4.

Astral Sorcery version: 1.10.17

**Comment by pulli23** [comment]
I can also second this, I also notice that after many times restarting the pack it "suddenly" works. (Next time I try it fails again though), and many is literary dozens of times.

This is happening at sev tech.

**Comment by Doomgull** [comment]
Single player or server?

**Comment by Deregorn** [comment]
In my case it was in single player mode.

**Comment by yagomont** [comment]
I am having the same problem. Strange thing is, crafting an attuned wand worked while none of the irradiant stars did.

**Comment by Doomgull** [comment]
Used JEI autofill?

**Comment by yagomont** [comment]
Yes. Is it the issue?

**Comment by Doomgull** [comment]
Yup. Using jei autofill breaks it until restart.

**Comment by yagomont** [comment]
Solved. Autofill does break it.

**Comment by Doomgull** [comment]
Going to duplicate this to #1075
