### ISSUE TITLE
vicio mantle/elytra gliding dont count for vicio EXP

### ISSUE THREAD

**Issue by majijn** [HellFirePvP/AstralSorcery#1088]
is this intended?

**Comment by HellFirePvP** [comment]
Well, it currently runs off of calculating differences in the sprint, walk and fly stats. Elytra-flying doesn't have a stat to it unless it's counted into flying. Not sure what/how much i can do about that..?

**Comment by majijn** [comment]
elytra flight does have a stat 
or do you mean that mojang implemented it weird and its not really usable?

**Comment by HellFirePvP** [comment]
'AVIATE_ONE_CM' not very obvious that this is related to elytra flight..

**Comment by majijn** [comment]
instead of implementing it weird they named it weird, got it! lmao
