### ISSUE TITLE
On the server, there is no dropping Rock Crystal when breaking Rock Crystal Ore

### ISSUE THREAD

**Issue by Flandoll** [HellFirePvP/AstralSorcery#1089]
When I am in single player mode, the ore can drop the crystal, but it will not drop any items when destroying the ore on the server.
MC: 1.12.2
AS: astralsorcery-1.12.2-1.10.17
Server: spongeforge-1.12.2-2768-7.1.6-RC3680
Forge: forge-1.12.2-14.23.5.2836-universal

**Comment by Doomgull** [comment]
Need to test the server world without sponge running, since that will be your difference between the two.

Also, is there a reason you are running a release candidate version of spongeforge and not the stable GA release?

**Comment by Flandoll** [comment]
No errors in the pure forge server environment.
In addition, the SpongeForge-7.1.5 GA has the same error.

As for the RC version, it may contain more bug fixes.

**Comment by Doomgull** [comment]
So sounds like you need to open a ticket with spongeforge, aince it doesn't happen without it.
