### ISSUE TITLE
Crafting Tweaks conflict - MC 1.12.2 / Forge 14.23.5.2823

### ISSUE THREAD

**Issue by CoffeeFueledPanda** [HellFirePvP/AstralSorcery#1090]
Hello Hellfire,

Issue: Crystal not connecting to the crafting table and recipes not working.

Preliminary info:

- MC version: 1.12.2
- Forge version: 14.23.5.2823
- Mod that seems to be causing the conflict: Crafting Tweaks (CraftingTweaks).

**Current workarounds:** Using the scroll of "Written Expertise" seems to allow me to use the luminous crafting table, unfortunately it also unlocks all research which is 'meh'. Or starting a new world with "Crafting Tweaks" removed seems to fix the issue, without using the scroll of "Written Expertise", however the affected/original world even after removing the mod, will still be affected.

I have no idea; if you're able to perhaps get in touch with the Crafting Tweaks author, but either way i thought you should be made aware of this issue, just in case.

**Comment by Doomgull** [comment]
What version of AS?

Please provide a full mod list where this is occurring.

**Comment by CoffeeFueledPanda** [comment]
**AS version: 1.10.14**
**Mod list:**
![ModlistPart1](https://user-images.githubusercontent.com/22580785/56893890-828cbe80-6a84-11e9-997f-5cc3fffc1115.png)
![ModlistPart2](https://user-images.githubusercontent.com/22580785/56893891-828cbe80-6a84-11e9-9bca-5ec378ea0629.png)
![ModlistPart3](https://user-images.githubusercontent.com/22580785/56893892-828cbe80-6a84-11e9-8fa9-9cb25fa2dc8d.png)

**Comment by Doomgull** [comment]
Can you provide the log output of using the /slnetwork command (in creative mode) on both the crystal that should be linking, as well as the table that should be linking?

Will likely need to put the log output up into pastebin or gist.

**Comment by CoffeeFueledPanda** [comment]
Hey there Doomgull,

Unfortunately I got rid of the "Crafting Tweaks" mod and started a new save, so regretfully I think that information may be unobtainable at this point in time.
