### ISSUE TITLE
Crash when loading world, seems related to Astral Sorcery perks? [Sevtech]

### ISSUE THREAD

**Issue by X3n0n3x** [HellFirePvP/AstralSorcery#1092]
## Bug Report

Last night everything seemed to be working fine, but now trying to play again, every time I go to "SinglePlayer" then select my world and click "Play" and it starts loading, after ~30 seconds or so it notes that it's "Shutting down internal server" then closes the game out and gives me a crash report.  This happens every time, and even when attempted to load slightly earlier backups.

## Expected Behaviour

I should be able to load and play my world normally.

## Possible Solution

The first bunch of entries in the crash report are all things like:

`java.lang.NullPointerException: Unexpected error at hellfirepvp.astralsorcery.common.constellation.perk.PerkLevelManager.resolveLevelCap(PerkLevelManager.java:110)`

so it makes me think it could be related to the Astral Sorcery perk system?  (Although I'm playing it as part of the Sevtech 3.1.1 modpack)

This makes sense because last night is when I unlocked the Astral Sorcery perk system for the first time, in Age 2. Additionally, while I picked the attunement which levels up by placing blocks first, I noticed that it leveled up extremely slowly, taking quite a while to just get halfway up level 1, so I crafted & used a "Shifting Star" item to swap my attunement to 'Vicio," which levels up by moving instead. Suddenly I was gaining whole attunement levels just from walking from one side of my base to the other (I had on Wild Dog boots, lots of Dirt Paths, and a few 5x Horse Totems around, so I run at a decent speed I guess). After a half hour or so of just moving around my base and fiddling with more Astral Sorcery stuff, I was at attunement level 14, which seems ridiculously quick given how slowly I was leveling up with the old constellation. Perhaps this is related to my current crash? I continued playing for another few hours after this without noticing any problems, it is only now when trying to load the world that it crashes.

I've heard about some kind of perk debug logging, but when I check my astralsorcery.cfg file I don't see any mention of debug_logging or an option to enable for perk logging.  Maybe because Sevtech v3.1.1 is using a slightly older version of astral sorcery?

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log: latest.log at  https://gist.github.com/X3n0n3x/689efacb45e19859c458ab0b52b888d1
* Crash Log: crash-2019-05-01_13.14.29-client at https://pastebin.com/W9TCRfQN

## Client Information

* Astral Sorcery Version: 1.12.2-1.10.11
* As part of Sevtech Version: 3.1.1
* Java Version: Java v1.8.0.181 (64 bit)
* Launcher Used: Twitch, with JAR Launcher
* Memory Allocated: 8192 MB
* Server/LAN/Single Player: Singleplayer 
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: Sevtech v3.0.8 (I updated to Sevtech v3.1.1 at the very end of Age 1, just before advancing to Age 2, so before I started any Astral Sorcery or perks or anything)

* Additional Content Installed: No other mods, but I disabled "SmoothFonts" via Twitch profile options for performance, and am also using these "Additional Arguments" in Twitch Launcher:
`-XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M`

**Comment by Doomgull** [comment]
#1026

Fixed several versions ago, with version 1.10.12. Current version is 1.10.17.

**Comment by X3n0n3x** [comment]
Thanks for the info!  Updating Astral Sorcery to v1.10.17 via the Twitch app button seems to have gotten things working again now! I did get a crash-to-desktop when using "Save and Quit to Menu" pause menu option, but otherwise the game loads up and runs now.  

However, simply walking around in my base still seems to give me attunement level experience at a crazy high rate.  Does anyone know whether this is working as intended, or just something I can bandaid over by adjusting the experience gain rate in the astralsorcery.cfg file?

**Comment by Doomgull** [comment]
Likely needs an xp rate config change, if not at default values.

Or perhaps sevtech had previously nerfed the values.

**Comment by X3n0n3x** [comment]
Well the values for experience rate I see in the astralsorcery.cfg file are all set to the default of 1x as far as I can see, the same as they were before I updated to v1.10.17 e.g.

```
    root_vicio {
        # Sets the exp multiplier exp gained from this root-perk are multiplied by. (So higher multiplier -> more exp) [range: 0.0 ~ 1024.0, default: 1.0]
        S:Exp_Multiplier=1.0
```

But possibly some other file is applying a multiplier to that elsewhere?  I could still lower the one for Vicio from 1.0 down to 0.2 or 0.1 so it feels more "reasonable" I suppose.

At any rate, this is my first time playing either Sevtech or Astral Sorcery, so I technically have no reason to suspect that something is malfunctioning, other than how strange it feels to already be more than halfway to the level 30 cap for Vicio by accident after only an hour or so working in my base, combined with the huge speed difference when I tried out the Aevitas constellation first.

For example, [this gallery](https://imgur.com/a/08Q4Crk) shows the increase in experience from 30 seconds to place and remove half a stack of dirt with Aevitas, increasing the gauge by a sliver.  Using a Builder's wand to place the same amount of dirt gave an even smaller sliver of experience.  However spending those same 30 seconds with Vicio to just run from one end of my base to the other 3 or 4 times fills half of the experience gauge, even at level 17.  It just intuitively feels like something must not be working as intended, since I've heard people warn against using a Shifting Star at a high level and "losing all your attunement progress," but that would be a silly warning if you could earn it all back in 30-45 minutes as I currently could.

Is there a ballpark on how long it's supposed to take to level up in attunement "normally," at least in Sevtech?  Or does sound like normal behavior?

**Comment by Doomgull** [comment]
Vicio is based on distance traveled atats. Whereas aevitas is based on hardness of block placed. You're effectively comparing xp gained while sneaking with no speed boost, to xp gained while sprinting by comparing dirt to walking/ moving around.

**Comment by X3n0n3x** [comment]
Ahhh OK, I didn't realize block hardness was a factor for Aevitas, so I really was attempting it one of the slowest ways possible!  

Knowing that, I suppose the very fast rate of growth with Vicio I noticed is indeed intended, and I was just accidentally doing Aevitas unusually slowly?  

In that case I may just leave things as they are, then.  I was worried that I had accidentally broken something, causing me to gain experience much faster than normal, and would trivialize the challenge of the content by becoming too powerful too quickly, faster than the mod was designed to handle.  I guess I had assumed that getting to level 30 in attunement was sort of a "mid/late-mod" goal within Astral Sorcery, and not something to feasibly obtain right away just after getting access to the Attunement Altar.

Thanks again for the helpful info!
