### ISSUE TITLE
server perk crash ~

### ISSUE THREAD

**Issue by deepgui** [HellFirePvP/AstralSorcery#1093]
hi~Hellfire
This option may have caused my player to crash directly after entering the.
![1](https://user-images.githubusercontent.com/49181637/57129041-e0dcd880-6dc7-11e9-9450-c266bf5c6dbb.png)

https://paste.ubuntu.com/p/WFPDFjyhHh/

version: 1.12.2-1.10.17
forge: 1.12.2-14.23.5.2815

**Comment by Doomgull** [comment]
#1085
