### ISSUE TITLE
Crash with better hud

### ISSUE THREAD

**Issue by cjser** [HellFirePvP/AstralSorcery#1094]
Getting crash to main screen when I try to break the spectral relaysy.
[crash-2019-05-04_02.36.42-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/3144457/crash-2019-05-04_02.36.42-client.txt)

**Comment by Doomgull** [comment]
Where did you get the relay from? What lens was in it? What were the stats on it?

"java.lang.NullPointerException
    at hellfirepvp.astralsorcery.common.tile.network.TileCrystalLens.writeCustomNBT(TileCrystalLens.java:228)"

**Comment by cjser** [comment]
I was wrong. I was breaking a crystal lens.Sorry I remember bad when I was writing it. It doesnt happen again. Not sure what happens then.

**Comment by Doomgull** [comment]
Only way it happens is if the lens has malformed nbt data. Usually from a custom acquidition method that was bad.
