### ISSUE TITLE
MC won't start even thou i've removed Astral Sorcery

### ISSUE THREAD

**Issue by IgnitusCoding** [HellFirePvP/AstralSorcery#1096]
so. me and my friends tried to add Ast.Sor to our pack, but we couldn't launch it due to the Forge issue, so i deleted it from my pack. now heres the problem: it still thinks its in my Pack and won't lemme start until i get a forge fer it, unfortantly no forge past 14.23.5.2772 wants to work fer me. anyone know a fix??

**Comment by Doomgull** [comment]
Need a log or screenshot. Either way, removing the mod has no impact in that. Sounds like you have something messed up there.

**Comment by IgnitusCoding** [comment]
https://docs.google.com/document/d/1dqsbPdmb9xB3XLr2MtskQQ40-ov5WKnnIGKjYe4gTtI/edit?usp=sharing

this is a copy of the Log from from earlier when i did a run of it to test
if it was working. still didn't then, so hopefully you can gimme a hand
with this.

**Comment by Doomgull** [comment]
It says it won't load because the forge version required by AS is too low.

And it is, by 20-odd versions.

**Comment by HellFirePvP** [comment]
> net.minecraftforge.fml.common.MissingModsException: Mod astralsorcery (Astral Sorcery) requires [forge@[14.23.5.2781,)]

yea. forge version outdated, so. remove AS or update forge.
