### ISSUE TITLE
Isn't the light from the sun starlight as well? What (do you think) makes starlight special?

### ISSUE THREAD

**Issue by yagomont** [HellFirePvP/AstralSorcery#1097]
First off, I love how the astral tome is written but once you begin clinging to a mod you kind of begin to question ways you would expand it and so on. But mods like TC and Astral Sorcery bring a narrative where the character studies the world around them and figures out how to use its fundamentals to their will. Kind of makes you wonder about the lore too. I hope lore discussion is acceptable and something people are looking for.

So, what exactly is stopping us from having the sun as a source of starlight? Does it have something to do with the stars necessarily being in a constellation?
Also, how did you come up with the names for the constellations? ( I know some exist IRL, like Octans and Horologium)

Of course, the sun would break the entire mod was that the case. But it doesn't help to stay silent.

**Comment by Doomgull** [comment]
Because the stars that provide magical power aren't actually stars. They're magical constructs. Otherwise they wouldn't have an appearance that was periodic with the moon cycles.
