### ISSUE TITLE
Rock/Celestial crystals have no pickup delay when dropped

### ISSUE THREAD

**Issue by truenachtara** [HellFirePvP/AstralSorcery#1098]
When I try to drop a rock crystal or celestial crystal, it takes several tries before I'm actually able to get it to stay in the world. Many times it will go back into my inventory before it's even settled on the ground, requiring some interesting gymnastics in order to get the crystal to stay out of my inventory.

**Comment by Doomgull** [comment]
That has absolutely nothing to do with this mod. Zero code involving that.
