### ISSUE TITLE
Shooting stars seem to disappear near the height limit.

### ISSUE THREAD

**Issue by zach2045** [HellFirePvP/AstralSorcery#1100]
So this has actually been an issue on both servers I have run AS on in the past few weeks. When a shooting star appears in the sky it will seem to be falling as normal but once it gets to a certain point it just kinda disappears and will never land. I am not sure if this is something I am missing or doing wrong but I wanted  to ask about it here to see if there was a way to maybe resolve it to get them working on our server.

**Comment by Doomgull** [comment]
If they move into an unloaded chunk, they will despawn. Gotta chase them quick.

**Comment by zach2045** [comment]
Oh alright. Thank you for the quick response. I will keep that in mind and let the players know that they just need to be quick on there toes.
