### ISSUE TITLE
KeyChainMining and getASFakePlayerServer causing server freeze

### ISSUE THREAD

**Issue by Sir-Will** [HellFirePvP/AstralSorcery#1101]
As you can see in the gist below the KeyChainMining causes the server to freeze which seems to be caused by it creating a FakePlayer for each block instead of reusing it, if I did read it correctly.

astralsorcery-1.12.2-1.10.17

https://gist.github.com/Sir-Will/06d21b9e498b07218b22d76e5483fe88

**Comment by HellFirePvP** [comment]
Seems odd to take up such a significant amount of performance.
And i remember to at least not use a random UUID per player, uh.... i wonder where i derped there. Will fix in a minute.
