### ISSUE TITLE
Null crash from TileCrystalLens

### ISSUE THREAD

**Issue by runescapejon** [HellFirePvP/AstralSorcery#1103]
Hello it seem there a null error on TileCrystalLens https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/tile/network/TileCrystalLens.java#L228

here is the crash report https://pastebin.com/raw/i9JThs6S

**Comment by JimDeRoberto** [comment]
Hello, it was I who ran into this issue. I was setting up a ritual from astrial sorcery using Aevitas. Setting up the attuned crystal altar (the one with the star light around it) with Aevitas attuned on it, beaming at the ritual altar with the celestial shard attuned to Aevitas as well. I also linked 5 lenses up to redirect the beams of light back at the ritual. my garden was in line with all this going in a straight line. I put a prism above the garden, and attempted to connect the Aevitas celestrial crystal (the first thing) to the prism thru another lens. It was at this point all beams of light just stop. I tried to relog to see if it fixed the issue, but then i couldnt get back on, kept getting internal errors and such. When I finally do get back in, i messsed around trying to fix this issue. I did find one curious problem in that when i broke the prism, it wasnt really there. I put a prism back there, and it looked like it placed but then i clicked again and it looked like i placed another. I break the first one and get nothing, but if I break the second one that shouldnt of even placed, it comes back to me. I tried with another block in the space where that prism WAS supposed to go, and id get that block back and a prism would show up there, but if i break it just goes away all over again. No matter what I cannot seem to get this to fix itself. I even tried moving the real prism forward one and redoing the whole ritual setup, but it once again kicked me off and would not let me back, giving the same internal server errors. 

I hope this wasnt too confusing, thank you for reading.

**Comment by JimDeRoberto** [comment]
PS what rune posted was about my issue btw. that crash report is mine.

**Comment by Doomgull** [comment]
What pack, and how did you get each of those lenses? Only way that crash is possible is if the lens had incorrect NBT data somehow.

**Comment by JimDeRoberto** [comment]
I was on Runes Modded Networks Mystical Times mod pack, and i crafted each one myself thru normal means.

**Comment by JimDeRoberto** [comment]
OH and it was all done on the maxed out crafting altar for astrial as well if that helps at all.

**Comment by Doomgull** [comment]
Default recipe, or was the recipe changed for the pack? Only way it should happen is if NBT is malformed, or if the lens isn't actually there somehow (odd desync or something)

**Comment by JimDeRoberto** [comment]
Default recipe. Could be the desync thing....was super weird for sure.

**Comment by HellFirePvP** [comment]
It's literally just missing data.
If you hover over the lens or prism in JEI you can see (by holding shift) that those have stats on them; size, purity and cutting.
If the lens that you crafted doesn't have that, that means it's lacking that data. So placing it will result in a crash.
The crucial point now would be to find out if either the crystal you used to craft with didn't have those 3 stats either OR if they disappeared with the crafting process, so the resulting lenses didn't have stats eventhough the crystal had.
If the crystal didn't have stats to begin with, find out how you obtained them. Crystals without stats are an important problem as anything that'll use them will result in issues and crashes.

**Comment by JimDeRoberto** [comment]
Everything has stats on em, all perfect stats 900 size, purity and cutting 100% on all the lenses and prisms. all say 1 NBT tag on em too, not sure if that means anything or not but lol. Even the attuned collector crystal and the attuned crystals are with those stats as well.

**Comment by JimDeRoberto** [comment]
![Screenshot_330](https://user-images.githubusercontent.com/50504939/57569755-b7274100-73c7-11e9-91d3-c831e5f27216.jpg)
![Screenshot_331](https://user-images.githubusercontent.com/50504939/57569756-b7274100-73c7-11e9-97f7-8d4a6f9a4549.jpg)
![Screenshot_332](https://user-images.githubusercontent.com/50504939/57569757-b7274100-73c7-11e9-99c5-3ac863541862.jpg)
![Screenshot_333](https://user-images.githubusercontent.com/50504939/57569758-b7274100-73c7-11e9-935f-45f0753cac8a.jpg)

**Comment by JimDeRoberto** [comment]
just realized i could post screenies here lol....does this help at all?

**Comment by JimDeRoberto** [comment]
Also, i have placed those lenses and beamed them all back to the ritual crystal just fine, and did 5 of them. It dont seem to happen until I attempt to link it to a 6th crystal and then to a prism. not 100% sure exactly when this happens but I am looking to see if I can figure out the exact moment today so maybe we can get to the bottom of it.

**Comment by runescapejon** [comment]
well here more information the item was place on the ground and it kick us and this is what it gave us 
https://pastebin.com/raw/0rvvyxJj
also i had manage to get online find a workaround to the kicking with error and manage to pick-block in creative to see the nbt and this is what was inside 
```
 astralsorcery {
 crystalProperties {
 collectiveCapability=100
 fract=0
 purity=100
 size=900
 sizeOverride=-1
 }
}
```
Item: PrismLens
hope this help with information more

**Comment by runescapejon** [comment]
Closing, I don't see how this can be useful.
