### ISSUE TITLE
Amulet Capability Break Manual Drawer/Barrel Usage

### ISSUE THREAD

**Issue by natedogith1** [HellFirePvP/AstralSorcery#1104]
The amulet capability stores nbt data on held items (even if no enchantments are being applied).  This prevents me from either placing items into drawers and barrels by hand (because the item in my hand has non-matching nbt) or by automation (because the item in the drawer has leftover nbt from when I put it in).  This causes issues when filling barrels with things like bows or cakes.

**Comment by Doomgull** [comment]
There is a compound tag regardless of whether you have held it or not. The tag is only applied to non-stacking items, and is "empty" when not being boosted.

Ergo, the nbt will match unless under active effect from an amulet modifying it.

**Comment by natedogith1** [comment]
I don't have an amulet, so it shouldn't be under any active effects.

**Comment by Doomgull** [comment]
> There is a compound tag regardless of whether you have held it or not. The tag is only applied to non-stacking items, and is "empty" when not being boosted.

> Ergo, the nbt will match unless under active effect from an amulet modifying it.

**Comment by natedogith1** [comment]
Having looked at the nbt tag of a held cake (via FTBUtil's nbtedit command), it has tags for the holder uuid.  And having tested, if I right click a cake into a barrel, automation won't be able to insert cakes, and the "double right-click to insert all matching items in inventory" feature doesn't work. And on the reverse, if I insert a cake with automation, i can't right-click the cake in my hand into the barrel.

**Comment by Doomgull** [comment]
I would quote myself a third time, but let's go with this instead:
"Sounds like you need to stick to one method of insertion. This isn't something that will change, since the only other methods of controlling the enchantment boosting would involve insanely heavy explicit lists or ASM that would break many other things. This is working as intended."
