### ISSUE TITLE
Illegal Async Chunk Load

### ISSUE THREAD

**Issue by ObjecT767** [HellFirePvP/AstralSorcery#1107]
**I am currently running**

- SpongeForge version: 1.12.2-2825-7.1.6-RC3713
- Forge version: 14.23.5.2837
- Java version: 8 Update 211
- Operating System: Win 10

- Plugins/Mods:
 
![Mod List](https://user-images.githubusercontent.com/49611562/57951933-ebc95a00-78eb-11e9-986b-4f44d6eab677.JPG)

**Issue Description**

When I trying to change Constellation (Astral Sorcery) on Attunment Altar (break Spectral Relay) , this error occure.
I copy 1:1 files from dedicated server and run it on my PC, everything works fine.

Error: https://gist.github.com/ObjecT767/8803d2ce8083ee02bc0407be14bdf28f
[latest.log](https://github.com/HellFirePvP/AstralSorcery/files/3192845/latest.log)

**Comment by Doomgull** [comment]
What version of Astral sorcery

**Comment by ObjecT767** [comment]
AstralSorcery-1.12.2-1.10.18

**Comment by maldiablo** [comment]
Could this be linked to this?

https://github.com/HellFirePvP/AstralSorcery/issues/1112

**Comment by Doomgull** [comment]
No
