### ISSUE TITLE
Attuned Mantle of the Stars requires base mantle being equipped before can be crafted

### ISSUE THREAD

**Issue by NillerMedDild** [HellFirePvP/AstralSorcery#1110]
A few of my users are reporting that they are unabled to craft attuned Mantle of the Stars. They've tried with several different attuned crystals and recipes. 

One of the players was able to craft one Attuned Mantle of the Stars after restarting his game, but was unable to craft it after that. Restarting the game again allowed him to craft one more.

I've asked for a latest.log from the players, in case you need one.

### Versions
- Forge-1.12.2-14.23.5.2836
- astralsorcery-1.12.2-1.10.18

Original issue: https://github.com/NillerMedDild/Enigmatica2Expert/issues/1198

**Comment by yagomont** [comment]
This happens to me too on single player. However, equipping the mantle and then taking it off makes it craftable. Same with a shifting star- right click it once and it will not glitch when used to craft other stars.

Jei's autofill might be causing crafting issues too.

**Comment by Doomgull** [comment]
Is the recipe modified in the pack? Also there is #1075 which is the likely culprit if it fixes on restart.

**Comment by NillerMedDild** [comment]
The recipe is not modified, and you're probably right, closing as a duplicate.

**Comment by Doomgull** [comment]
Feel free to reopen if it's not the jei issue

**Comment by Doomgull** [comment]
Nope, pulling back open. Was able to get confirmation outside the pack of the need to equip then de-equip for it to work.

**Comment by treeofchaos** [comment]
I have done some testing on this issue, here are the results:
Mod List: Astral Sorcery 1.10.18, Baubles 1.5.2, Botania r1.10-361, EmbersRekindled 1.13-hotfix2, jei 4.15.0.268, roots 2 0.104, soot 1.6

Tests done:
Baseline Test - crafted a base mantle, picked it up, attempted to craft attuned mantle and failed.
Test One - crafted a base mantle, picked it up, threw it on the ground to obtain NBT data, picked up, attempted to craft attuned mantle and succeeded.
Test Two - crafted a base mantle, picked it up, equipped it, de equipped it, and successfully crafted attuned mantle
Test Three - crafted a base mantle, picked it up, equipped it, de equipped it, threw it on the ground to obtain NBT data (NBT data was the same as Test One), picked up, successfully crafted attuned mantle.
Test Four - crafted a base mantle, picked up, shift clicked into a chest, shift clicked out of a chest, failed to craft attuned mantle.
Test Five - crafted a base mantle, picked up, manually placed into a chest, shift clicked out of a chest, failed to craft attuned mantle.
Test Six - crafted a base mantle, picked up, shift clicked into a chest, manually took out of a chest, failed to craft attuned mantle.
Test Seven - crafted a base mantle, picked up, manually placed into a chest, manually took out of a chest, failed to craft attuned mantle.
Test Eight - crafted a base mantle, picked up, manually moved within inventory, successfully crafted attuned mantle.

**Comment by treeofchaos** [comment]
if further testing is needed, let me know via ping on discord
