### ISSUE TITLE
Perks are removed upon travelling to other dimensions - specifically those made through Mystcraft

### ISSUE THREAD

**Issue by Kizzycocoa** [HellFirePvP/AstralSorcery#1114]
I must admit, I've not tested this on the Nether etc - I've not reached that point in my world. But it seems all perks are lost when travelling to other dimensions, specifically RE Mystcraft. Perks are regained by disconnecting/reconnecting.

**Comment by Doomgull** [comment]
Full pack list, AS version, Forge version? Single player or Multiplayer?

Sounds like a desync issue between client and server. Are they actually lost, or only the display of having them.

**Comment by HellFirePvP** [comment]
Most likely caused by mystcraft not firing entity clone.

**Comment by Kizzycocoa** [comment]
@Doomgull I am using 84 mods. these mods are:

Damage Indicators 3.4.7
Mo Villages 1.5.4
AbyssalCraft 1.9.7
Advanced Fishing 1.3.3
Ambient Sounds 3.0.9
Antique Atlas 4.5.1
Astral Sorcery 1.10.18
Atum 2.0.7
Backpack 3.0.2
Baubles 1.5.2
BiblioCraft 2.4.5
BiomesOPlenty 7.0.1.2439
Bonsai Trees b144
Bookshelf 2.3.577
CameraObscura 1.0.3
Capes Mod
Chameleon 4.1.3
Chisel 0.2.1.35
Clay Soldiers 3.0.0-Beta2
CodeChickenLib 3.2.2.353
CreativeCore 1.9.45
CTM 0.3.3.22
Decocraft 2.6.2
Dimensional Doors 3.0.9.287
Enchanting+ 5.0.177
End Spectre 1.0
Endercrop 1.6.0
Ender Storage 2.4.5.135
Erebus 1.0.29
Extra Discs 1.0.2 Build 5
Fancy Block Particles 2.4.1
Furniture 6.2.1
Future Versions
Game Stages 2.0.112
Googly Eyes 7.1.0
Gravestone Graves 1.3.1
Gravestone Extended 1.3.5.1
Grue 1.4.0
Guidebook 2.9.1
Hats 7.0.2
Hat Stand 7.0.1
iChun Util 7.2.1
Industrialcraft 2 2.8.152-ex112
Iron Chest 7.0.64.843
Just Enough Items 4.15.0.279
Labyrinth 1.0
Librikka 1.0.0
Little Tiles 1.5.0-pre135
Longfall Boots 1.2.1b
ltta 1.3.1
Magical Sculpture 1.0.0
Mob Amputation 7.0.0
Mob Dismemberment 7.0.0
Modular Powersuits 1.0.41
Multimob 1.0.5
Mutant Mobs 1.0.0
Mystcraft 0.13.7.03
More Mystcraft 0.5.6
Natures Compass 1.5.1
Nether Dungeon 1.0.1
No More Recipe Conflict 0.13
Not Enough Items 2.4.2.240
Numina 1.0.38
Open Computers 1.7.4.153
Optifine HD U E3
Pam's Harvestcraft 1.12.2zc
Portal Gun 7.1.0
Portality 1.2.2-14
Primitive Mobs 1.2.3a
PTRLib 1.0.4
Rex's Additional Structures 2.2.2
Roguelike Dungeons 1.8.0
SanLib 1.5.1
SBM Baggable Mobs 1.0.0b20190504162032
Simple Trophies 1.1.0
StorageDrawers 5.3.8
Swamp 2.2
Thaumcraft 6.1.BETA26
The Beneath 1.5.1
The Betweenlands 3.4.6
The Midnight 0.3.1
Tiny Mob Farm 1.0.5
Trap Expansion 1.0.0
Tree Chopper 1.2.4

For Forge, I am using 1.12.2-14.23.5.2838

It is currently Singleplayer, but I will hopefully make it Multiplayer in the near future

**Comment by Kizzycocoa** [comment]
After further testing with ATUM 2, this issue does indeed seem to be isolated to Mystcraft

**Comment by HellFirePvP** [comment]
Related: https://github.com/XCompWiz/Mystcraft-Issues/issues/340

**Comment by HellFirePvP** [comment]
Said issue is fixed with the latest release of mystcraft btw

**Comment by SeseMueller** [comment]
This also happens when travelling to the Nether and/or returning from the Nether. Most notably is the reach I perked up to 10 blocks being reduced to the default. 
(Weirdly enough, the Extra Health I got stays.)
Modpack is E2E via Twitch Launcher on the latest Version: astralsorcery-1.12.2-1.10.20.jar.
