### ISSUE TITLE
Phoenix Fire perk needs immediate tweaking

### ISSUE THREAD

**Issue by yagomont** [HellFirePvP/AstralSorcery#1115]
[Click here for video proof/demonstration of this issue](https://streamable.com/m6rvb)

As it is right now, the Phoenix Fire perk from the perk tree will make the player completely unable to die. Except if you are hit by a blue chaos projectile from DE. Even the guardian's fireball barrage is completely unable to kill. I have also tested Chaos Island explosions, two flux infused swords hitting me at the same time... Completely immortal.

I am under the impression this is not how this perk was meant to be used, as it is completely broken in terms of balance. It needs a cooldown.

**Comment by Doomgull** [comment]
What version of AS?

**Comment by yagomont** [comment]
Latest from Curseforge - 1.10.18

**Comment by Doomgull** [comment]
There's a 50 second cooldown, so...
https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/constellation/perk/tree/nodes/key/KeyCheatDeath.java#L81-L83

What mods do you have, and anything involving potion effects?

**Comment by yagomont** [comment]
It's Enigmatica 2: Expert
Uh oh. The code is right there, but. It doesn't work?
Maybe it's my JVM. I need to do some tests.

**Comment by Doomgull** [comment]
Would also help knowing what your other perk attunements were, what you were wearing, any AoE buffing in the world nearby, etc.

**Comment by yagomont** [comment]
Nutrition was giving me resistance, strength and toughness. I also had the diamond skin perk, no knockback perk, and the three initial Shielding perks. 

I was wearing: a holy Botania cloak, a Ring of Odin from Botania, a meat feeder from IF, vis amulet from TC6 and Lifegiver Verdant Heart pendant from TC6.

Currently waiting for MC to load so I can test on Oracle JRE 8 instead of AdoptOpenJDK's OpenJ9   Java 8 JRE.

**Comment by yagomont** [comment]
Good Lord. Oracle Java is a massive memory hog. 

Well, same result. It's not the exotic JVM's fault. I tried to suicide with the powerful flux infused bow and quiver and Phoenix Fire still didn't have a cooldown.

**Comment by yagomont** [comment]
I will start up Astral Sorcery alone to rule out any mod interactions now.

**Comment by yagomont** [comment]
Confirmed AS bug -> Not a mod interaction, Phoenix Fire's cooldown is not functional. 

I tried drowning myself and it kept activating once HP went to 0, regenerated for a few seconds, and did the thing again. I tried again with skeletons to the same result. I should note the cycles take much less than 50 seconds as is denoted by the 1000 tick cooldown in my config file.
