### ISSUE TITLE
Floating shrine crystals only interact with the vanilla crafting table

### ISSUE THREAD

**Issue by Winddbourne** [HellFirePvP/AstralSorcery#1117]
All of the recipes use the ore dictionary for crafting tables, but if I place a tinker's construct crafting bench or a workbench from primal core under the crystal it doesn't get starlight . . .  It doesn't even work if I use the linking tool to link the crystal manually to the crafting table.  I looked in the cofig and there doesn't seem to be a spot where I can tell the program which other blocks it should consider as "crafting tables".

**Comment by HellFirePvP** [comment]
> It doesn't even work if I use the linking tool to link the crystal manually to the crafting table.

Because the recipe works with the vanilla crafting table gui & container; which aren't strictly location bound, so there's quite a bit of code around it to make it work to begin with. Custom crafting tables and whatever that deviate from the vanilla one will not be supported.
