### ISSUE TITLE
Mod interaction bug AE2 and Ceramics

### ISSUE THREAD

**Issue by Sunekaer** [HellFirePvP/AstralSorcery#1118]
FTB Issue tracker: FTBTeam/FTB-Builders-Paradise#31

Hi,

Clay Buckets from [Ceramics](https://minecraft.curseforge.com/projects/ceramics) with fluid are stuck in ME Drive, Clay Buckets without fluid or with vanilla in can be taken out of the ME Drive without problems.
Removed/disabling Astral Sorcery fixes the issue

Issue can be recreated with only the mods below
![image](https://user-images.githubusercontent.com/18720460/58438188-d7484700-80cd-11e9-8165-8dd74b5e669b.png)

**Comment by Doomgull** [comment]
Most likely due to capability discussed in #762. Address with AE2 or Ceramics.

**Comment by Sunekaer** [comment]
Ceramics can't do anything about this, it's AS there is doing something so these items are stuck in the AE2 system.

**Comment by Doomgull** [comment]
You clearly didnt read the linked ticket. AS does nothing to AE, except add an nbt tag to non-stackable items.

**Comment by Doomgull** [comment]
You clearly didnt read the linked ticket. AS does nothing to AE, except add an nbt tag to non-stackable items.

**Comment by LatvianModder** [comment]
Why does it add any data to non-stackable items? That seems like a bad idea 🤔

**Comment by Doomgull** [comment]
Because the alternative is maintaining an exhaustive list of every equippable item that exists in modded. There is no other way to indicate whether an item is an equippable for adding the capability to it, other than adding the capability to every non stacking item. Or maintaining thousands of lines of tracking for items

**Comment by LatvianModder** [comment]
No, I'm pretty sure the alternative is checking `Item#isValidArmor(ItemStack, EntityEquipmentSlot, Entity)` or `Item#getEquipmentSlot(ItemStack) != null` and only adding cap to those items. And/Or not add cap at all and only add NBT data when necessary/its actually changed/added by AS mod.

**Comment by Doomgull** [comment]
Except that doesn't prevent people from adding or duplicating insane numbers of enchantments, which can then be stripped off and reapplied, using one of the many methods to pull items out of inventory without the player de-equipping them creating a loop. That is why the capability is there.

Again, this is something not being handled properly with the NBT tag written to the item when it's being stored. Assuming that there is not an issue with how ceramics handles its bucket code, this needs to go to AE to have them address it on their side.
