### ISSUE TITLE
Octans' Unwavering ability is not mentioned in the Astral Tome. Also, the effect is not reversed upon taking the mantle off.

### ISSUE THREAD

**Issue by yagomont** [HellFirePvP/AstralSorcery#1120]
After looking at the file for the cape, I found out that the Octans mantle does in fact have an antiknockback feature. This, however, is not mentioned in the Astral Tome, and for me, I wouldn't use it at all weren't for the antiknockback. Definitely an information that needs to be there.

Plus, the Octans Unwavering effect is not reversed upon removing the Octans Mantle or even replacing it with another mantle. Entering another dimension will make the effect go away, though. I believe this is an issue with most perks, not just this one. This also fundamentally means you can stack this effect with other mantles, which is not very nice.

**Comment by Doomgull** [comment]
Csn you replicate using AS 1.10.19?

**Comment by yagomont** [comment]
I am on AS 1.10.19

**Comment by HellFirePvP** [comment]
Hard to say if this is fixable.
This uses the Vanilla minecraft's armor attributes to add the knockback resistance.
If it's not removed after switching the armor, something went awry in the attribute code of minecraft...

**Comment by yagomont** [comment]
In that case, some mod is probably altering that part of Minecraft and causing this to happen.

Well, at least the Astral tome can be edited to explain the mantle's power.

**Comment by HellFirePvP** [comment]
Have at it doom :P

**Comment by yagomont** [comment]
Bonp

**Comment by Doomgull** [comment]
The tome was updated already.
