### ISSUE TITLE
Armara ritual prevents lightwell collection

### ISSUE THREAD

**Issue by TheRealWebGremlin** [HellFirePvP/AstralSorcery#1125]
Lightwells do not function under the effect of the Armara ritual. Once I moved the lightwell out of the ritual's area of effect the lightwell started collecting liquid starlight again.

In addition, botania's mana spreaders do not work either within the Armara ritual. I can understand why that wouldn't work, as mana bursts are entities. But this, in combination with not being able to collect starlight either, makes the Armara ritual situationally useful at best, and is outshined in nearly every way by the Lucerna ritual.

If changes are made to allow the lightwell to function under Armara's effects, perhaps you can look into making Botania's mana pulses work as well?

**Comment by HellFirePvP** [comment]
The lightwell's starlight collection isn't prevented by the armara ritual.

Yes, botania mana burst entities are affected by the ritual. Also, with a set of lenses, they're not always just friendly, so i'll keep it this way.
