### ISSUE TITLE
Neromantic Prime ignores Chunk loading

### ISSUE THREAD

**Issue by Markus-Plankensteiner** [HellFirePvP/AstralSorcery#1127]
Pack: FTB Interactions 1.7.0
AS Version: 1.10.18

Issue: Neromantic Prime ignores chunk loading from FTB Utilities and won't generate Fluids when no player is nearby.

**Comment by Doomgull** [comment]
Any modifications to the pack? Is Sponge being run on the server??

**Comment by Markus-Plankensteiner** [comment]
There are no modifications to the pack or the Server. It is the unmodified Forge Server and Client of Interactions 1.7.0. I have not tried it on Singleplayer yet however.

**Comment by SiliconEnt** [comment]
Does it work with chunk loading from mods other than FTB Utilities? E.g. ChickenChunks, Persistent Bits, Weirding Gadget? I've heard plenty of (admittedly anecdotal) evidence suggesting that chunk loading mods vary in reliability.

**Comment by Markus-Plankensteiner** [comment]
Yes I've tried it with the weirding Gadget as well. It too doesn't work. No fluid gets put into the chalice when no player is nearby.

**Comment by HellFirePvP** [comment]
Happens because the liquid transfer from the fountain -> chalice is done via entities, which despawn if there's no player nearby.
Fixed in upcoming version.
