### ISSUE TITLE
collector crystal and all altars duplicating particles

### ISSUE THREAD

**Issue by MasterSloth1** [HellFirePvP/AstralSorcery#1129]
playing enigmatica 2 expert mode mod pack on a server with sponge and a few plugins when i started to do astral sorcery i noticed my fps getting worse and worse.I have to disconnect from the server then reconnect and it fixs it, if i leave the area and come back its still the same. Its also happening with all particle generating items.
![2019-06-07_17 09 57](https://user-images.githubusercontent.com/34207969/59082571-de7e1900-8947-11e9-8964-c94b2e665a5b.png)
![2019-06-07_20 05 11](https://user-images.githubusercontent.com/34207969/59090025-b39fbf00-895f-11e9-8280-9597158c1dac.png)

enigmatica 2 expert mode version - 1.64d
sponge version - 1.12.2-2825-7.1.7-RC3767
griefprevention version - 1.12.2-4.3.0.689.jar
forge version -14.23.5.2836
astral sorcery version - 1.12.2-1.10.18.jar

**Comment by MasterSloth1** [comment]
i cant seem to replicate this in singleplayer

**Comment by Doomgull** [comment]
That's going to make it a sponge issue, then.
