### ISSUE TITLE
Resplendant Prism sharpness not applying.

### ISSUE THREAD

**Issue by Gorgok** [HellFirePvP/AstralSorcery#1131]
forge-14.23.5.2838

astralsorcery-1.12.2-1.10.19.jar
Baubles-1.12-1.5.2.jar
DynamicSurroundings-1.12.2-3.5.4.3.jar (damage indicators)
OreLib-1.12.2-3.5.2.2.jar
MmmMmmMmmMmm-1.12-1.14.jar (test dummy)

Using the test dummy or damage indicators on mobs it appears the sharpness (or all existing enchants) does not actually apply. Tested with +2 existing sharpness, +1 sharpness +1 existing sharpness, and +2 existing all, with diamond sharpness 1, 3 and 5 swords (to compare like for like). 

Damage does not raise to the next enchant level with bauble equipped, remains at base enchant level no matter what. 

Tooltip does correctly raise damage indicated and enchant level though. 

Started out in a large modpack and carved out most of it trying to narrow down a conflict, but no luck. I did also test without Dynamic Surroundings and its associated OreLib, and the same issue is present. And tested without MmmMmmMmmMmm but damage indicators on and again issue is present. Even tested with an older version of Baubles. Have not tested other version of forge however.

**Comment by yagomont** [comment]
If the enchantment is actually getting raised while the resplendent prism is equipped then AS is doing its job right.

The problem here might actually be the limits Minecraft is setting, though, it's just my suspicion. This mod might interest you:

https://minecraft.curseforge.com/projects/attributefix

**Comment by yagomont** [comment]
I'm on the same version of forge as you are and tried to reproduce this bug (without AttributeFix)

-> enchanted a diamond sword with Sharpness VI

-> attacked dummy for 16 damage

-> equipped resplendent prism, raised sharpness to VIII

-> attacked dummy for 17 damage

So yes, it's working as intended. I can't reproduce your issue, at all.

**Comment by HellFirePvP** [comment]
MmmMmmMmmMmm does its damage calculation clientsided - so the numbers you see there were never on the server or calculated there.

Damage calculations are only done on serverside by default and their result is sync'd back to the client - aka how much health the mob now has, if it should play a being-damaged animation and the like. The resplendent prism only functions on serverside, so where the actual damage happens. Don't trust the target dummies.
