### ISSUE TITLE
Mod crashes when launched through Steam

### ISSUE THREAD

**Issue by starlingfire** [HellFirePvP/AstralSorcery#1133]
Astral Sorcery crashes when I try to launch it through Steam for In-Home streaming. I am playing it as a part of the FTB Interactions modpack.

Here is a snippet of the crash report, though full one is linked below:
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Astral Sorcery (astralsorcery)
Caused by: java.lang.UnsatisfiedLinkError: com.sun.imageio.plugins.jpeg.JPEGImageReader.initReaderIDs(Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/Class;)V
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.initReaderIDs(Native Method)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.<clinit>(JPEGImageReader.java:96)
	at com.sun.imageio.plugins.jpeg.JPEGImageReaderSpi.createReaderInstance(JPEGImageReaderSpi.java:85)
	at javax.imageio.spi.ImageReaderSpi.createReaderInstance(ImageReaderSpi.java:320)
	at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:529)
	at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:513)
	at javax.imageio.ImageIO.read(ImageIO.java:1443)
	at javax.imageio.ImageIO.read(ImageIO.java:1352)
```

## Version: 
1.10.17

## Bug Report:
Launching the game works fine through the Minecraft launcher directly, but crashes when trying to launch through Steam as a manually-added game.

## Expected Behavior/Suggestions:
I would expect this to launch normally.

## Is It Repeatable? Steps to Reproduce: 
* https://youtu.be/e0dKcBwt9lE

## Link to Log or Crash File Paste: 
* https://pastebin.com/WDtejMSS

## Attempted Fixes (none known to work): 
* Removed all dimensions from skySupportedDimensions and weakSkyRenders
* Removed all custom java parameters except RAM allocation

## System Setup
* Solus linux x64
* Nvidia 1080 Ti w/drivers 430.14
* Intel i7-7700K

**Comment by Doomgull** [comment]
That looks like a Java error, is that the same Java version that's being run to launch without using in home?

**Comment by starlingfire** [comment]
I think so, yes. As a test, I wrote a shell script to output the java version to a file, and then added it as a Steam game, then "played" it. This is the output I got:

```sh
ERROR: ld.so: object '/home/[user]/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
openjdk version "1.8.0_192-solus"
OpenJDK Runtime Environment (build 1.8.0_192-solus-b26)
OpenJDK 64-Bit Server VM (build 25.192-b26, mixed mode)
```

**Comment by Doomgull** [comment]
May want to try a different java version, if possible. I'm unsure what the Solus notation indicates is changed for the os vs a normal java release.

Also, because it's steam in-home, you may want to just try launching from whatever passes for a desktop for that client, instead of launching through steam. It will let you do that

**Comment by HellFirePvP** [comment]
Yea, this is nothing on AS' end. Some extension or library or whatever seems to be missing from your installation. Can't really provide more support than that.

**Comment by yagomont** [comment]
Hey, there. I'm also on Linux, and if there's something java-related I can recommend you is to swap your jvm to this: [OpenJ9](https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=openj9)

Along with being an upgrade to newer builds that may or may not fix the problem, the OpenJ9 JVM has been proven again and again to be of superior performance than the more common Hotspot in an environment like Minecraft. You might also want to grab one of the nightly builds to get the latest stuff (maybe the image plugin has got a bug fixed, or whatnot.)

**Comment by HellFirePvP** [comment]
Gonna close this as it is not strictly related to AS.
