### ISSUE TITLE
Breaking Aim Perk has a 100% chance of activating.

### ISSUE THREAD

**Issue by TheDieselPunk** [HellFirePvP/AstralSorcery#1134]
Pack: FTB Revelation 3.0.1
AS Version: 1.10.18

Issue: Used against other players, the disarm perk "Breaking Aim" has a 100% chance of success despite any changes to "S:DropChance=" in "key_disarm".

**Comment by yagomont** [comment]
It also has a 100% activation chance when used on mobs. Plus, the "disarm" part actually is reminiscent of taking off your enemy's weapon, not undressing them. Maybe the perk should be changed to reflect that.

Needless to say there were a lot of pants-stealing jokes on my server that day.
