### ISSUE TITLE
Astral Sorcery adding NBT tags to items, making them not stack with unmodified items

### ISSUE THREAD

**Issue by object-Object** [HellFirePvP/AstralSorcery#1137]
Modpack: custom on 1.12.2 (Twitch's generated mod list: https://pastebin.com/xy7bDtf5)
AS version: 1.10.19

Astral sorcery is, seemingly randomly, adding NBT tags to items, which prevents them from stacking with items that haven't been modified. It doesn't happen immediately upon getting the items, and it happens to the entire stack of items in the slot, however many that is. The NBT tags look like `"astralsorcery":{}`. I haven't figured out how to make it happen, but it's been happening fairly often.

**Comment by Doomgull** [comment]
It's not at random. It's for non-stacking items, applied as part of the capability to handle the Prism's enchantment modifications while preventing enchantment dupe bugs. This has been a part of AS code for a VERY long time, now. #762

**Comment by object-Object** [comment]
Is it supposed to happen with stackable items - for example, dirt? Because that's what's happening.
