### ISSUE TITLE
IllegalStateException: Asynchronous Async Player Chunk Add!

### ISSUE THREAD

**Issue by BlayzerQ** [HellFirePvP/AstralSorcery#1139]
MC: 1.12.2
Mod version: astralsorcery-1.12.2-1.10.18
https://gist.github.com/BlayzerQ/e1c813e12f95cee231aa5a5c75b3d993

**Comment by Doomgull** [comment]
Update to 1.10.19 and check for repeats.

**Comment by BlayzerQ** [comment]
On 1.10.19 problem has still

**Comment by Doomgull** [comment]
Does it happen without spugot.
