### ISSUE TITLE
Atral Sorsery 1.12.2 Perks don't upgrade

### ISSUE THREAD

**Issue by BUBLYU** [HellFirePvP/AstralSorcery#1140]
In the Astral Sorcery mod, when charging to the star Discidia, LVL is not pumped in, which is necessary for the development of the skills of the pack. (It is pumped in due to the damage caused by DMG, but I killed more than 20 mobs and it wasn’t pumped in absolutely)

**Comment by Doomgull** [comment]
What version of Astral Sorcery? What other mods in the pack? What are you attacking with?

Experience is based on damage dealt, not kills.
