### ISSUE TITLE
Scorching Heat enchantment-related crash

### ISSUE THREAD

**Issue by yagomont** [HellFirePvP/AstralSorcery#1142]
Tested on version 1.10.19, on both SSP and SMP (sponge)
This problem happens anywhere, and is not related to server software such as sponge.

[Crash Report Sponge](https://cdn.discordapp.com/attachments/584908311762305024/594541823951634433/crash-2019-06-29_10.19.35-server.txt)

[Crash Report SSP](https://github.com/HellFirePvP/AstralSorcery/files/3342028/crash-2019-06-10_12.24.20-server.txt)

The game will crash at random after trying to break a block with the AS Scorching Heat enchantment. I have no idea how to consistently reproduce this issue, but it does become more common (albeit, is not exclusive to) when using AoE digging mechanics such as the evorsio mantle. It's unclear if this is triggered by the fortune enchantment being in the tool as well. But in the end the enchantment seems to be doing bad math on the items that it's going to drop.

**Comment by HellFirePvP** [comment]
Probably related to Quark's root block (as seen in the stacktrace) or a problematic type of list being passed into the method that doesn't implement AbstractList#add properly... https://i.imgur.com/SEYBr27.png
Hard to say; and not really sure if this is mainly related to AS doing something wrong.

Responsible code: https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/event/listener/EventHandlerServer.java#L363

**Comment by yagomont** [comment]
Most likely fix then is to disable quark's root blocks.

**Comment by HellFirePvP** [comment]
Really hard to say tbh... something's odd with the list being passed into the event... huh.
