### ISSUE TITLE
Tree beacon sometimes bugs out and locks saplings into being trees

### ISSUE THREAD

**Issue by Shovinus** [HellFirePvP/AstralSorcery#1143]
Sometimes the saplings themselves because the "ghost" blocks and cannot be destroyed without destroying the entire farm

https://imgur.com/a/BRJl9Y6

**Comment by Doomgull** [comment]
There's some debug logging for this that can be enabled in the config, if it's still occurring.

**Comment by Shovinus** [comment]
It is the FTB interactions modpack, I don't play anymore so wont have it available unfortunately.

**Comment by Doomgull** [comment]
#1060 will need debug logging to investigate if it repeats, only seeing this in that modpack and need to know where the interaction is occurring (no pun intended).
