### ISSUE TITLE
Hiking Boots conflict with VanillaFix

### ISSUE THREAD

**Issue by daPoseidonGuy** [HellFirePvP/AstralSorcery#1144]
Astral Sorcery Version: 1.12.2-1.10.19

VanillaFix version: 1.0.10-99

Cannot auto step up blocks (walking into them just stops you like normal)

**Comment by Doomgull** [comment]
Sounds like VanilaFix is doing somethi g to the player attribute system and overriding, then.

**Comment by daPoseidonGuy** [comment]
Not sure what help this is, but removing VanillaFix from the server but keeping it on the client solves the issue.

Playing Singleplayer doesn't work even with VanillaFix's bugfixes disabled in config.
Haven't messed with other vanillafix config options yet.
