### ISSUE TITLE
Luminus Crafting Table doesn't work at all.

### ISSUE THREAD

**Issue by EnderBro123** [HellFirePvP/AstralSorcery#1145]
The Luminous Crafting Table doesn't work at all.

**CURRENT MODS IN USE:**

![image](https://user-images.githubusercontent.com/51277766/60995941-7d5fb180-a308-11e9-9e8c-4fdf4f8b7f0a.png)

![image](https://user-images.githubusercontent.com/51277766/60995958-8781b000-a308-11e9-91c1-eb9810a37194.png)

**FORGE INFO**
![image](https://user-images.githubusercontent.com/51277766/60996009-a3855180-a308-11e9-9b81-ad2b5204c280.png)

Not sure if this is enough info, but I'm using the latest versions of all of these mods.

**Comment by Doomgull** [comment]
Need to know what's not working, since it's working for a great number of people. Specifics.

This is likely a user-error issue that would have been better addressed via the Discord server.

**Comment by EnderBro123** [comment]
> Need to know what's not working, since it's working for a great number of people. Specifics.
> 
> This is likely a user-error issue that would have been better addressed via the Discord server.

Issue resolved in Discord.
