### ISSUE TITLE
Constellation papers staying blank (1.12.2)

### ISSUE THREAD

**Issue by ObsidianFlight** [HellFirePvP/AstralSorcery#1146]
I was only able to find the five bright constellation papers and then all the rest appear as blank

**Comment by HellFirePvP** [comment]
You can only discover dim ones after attuning yourself, the faint ones after additionally having progressed further.

**Comment by ObsidianFlight** [comment]
y u no add this in the book??

**Comment by yagomont** [comment]
It is in the book.
