### ISSUE TITLE
Forced disconnection while walking

### ISSUE THREAD

**Issue by 3269199948** [HellFirePvP/AstralSorcery#1147]
[err.txt](https://github.com/HellFirePvP/AstralSorcery/files/3406771/err.txt)

all error log

**Comment by Doomgull** [comment]
Does it replicate? If it's replicable, try using the latest jenkins build (accessible via discord). Should be fixed for next release if jenkins build solves.

**Comment by 3269199948** [comment]
> Does it replicate? If it's replicable, try using the latest jenkins build (accessible via discord). Should be fixed for next release if jenkins build solves (ticket dupe to #1112).

I don't quite understand what you mean, many players like this

**Comment by Doomgull** [comment]
Are you using Spongeforge on the server?

Wait until the next AS update.

**Comment by 3269199948** [comment]
> Are you using Spongeforge on the server?
> 
> Wait until the next AS update.

I am using catserver, I am looking forward to the next update

**Comment by Doomgull** [comment]
Catserver isn't aupoorted for this mod,and so there may be limited action we can take.

**Comment by 3269199948** [comment]
> Catserver isn't aupoorted for this mod,and so there may be limited action we can take.

No bugs are enough :)
