### ISSUE TITLE
Star ability collapse

### ISSUE THREAD

**Issue by 3269199948** [HellFirePvP/AstralSorcery#1148]
In the use of chain mining (translated into Chinese is such a skill, similar to chain mining), after use, the server crashes, crashes when used (server crash), this problem is the response of the server player

According to the server player, this is one of the "star capabilities"

All logs after the server crashed

[err.txt](https://github.com/HellFirePvP/AstralSorcery/files/3414560/err.txt)

**Comment by Doomgull** [comment]
This should be reported to Spigot, per their watchdog alert.
`[11:41:58] [Spigot Watchdog Thread/ERROR] [Minecraft]: Please report this to http://www.spigotmc.org/
[11:41:58] [Spigot Watchdog Thread/ERROR] [Minecraft]: Be sure to include ALL relevant console errors and Minecraft crash reports
[11:41:58] [Spigot Watchdog Thread/ERROR] [Minecraft]: Spigot version: git-1468a63-Community (MC: 1.12.2)`

Non-Forge only deployments aren't supported by Astral Sorcery.
