### ISSUE TITLE
Cant get the Crafting altar to work.

### ISSUE THREAD

**Issue by panslothda** [HellFirePvP/AstralSorcery#115]
So ive counted the blocks numerous times and also rebuilt the structure 2 times confirmed it with vallens video and with the ingame guide. i just cant get it to work and i am sooo confused atm.
https://gyazo.com/02666848b3cb25d94a44c1ef36f58f73
https://gyazo.com/8740461a5faad9d627fb7e1b81589b21
https://gyazo.com/b2fca322390bc7b7834f11313ffd7894

there probably is something i am doing wrong and just beeing stupid but i cant figure it out.

**Comment by panslothda** [comment]
So much for that. Restarted game and did it anpther time and worked. No clue whatsup with that but works now

**Comment by HellFirePvP** [comment]
Get rid of the torches on the sooty marble and inside the crafting area. Those will (currently) cause the multiblock-check to fail.

**Comment by panslothda** [comment]
And snow also makes it not work. Soooo when having built the thing in a cold biome you cna packup and leave basicly

**Comment by HellFirePvP** [comment]
It's changed in the upcoming version.. :P
