### ISSUE TITLE
Config option to not start with tome

### ISSUE THREAD

**Issue by CheshireSwift** [HellFirePvP/AstralSorcery#1152]
It'd be nice if there was an option to disable the Tome on spawn.

In my case I'm giving players an Akashic Tome containing all the books they would spawn with instead. I could give them an empty tome and let them put the books in themselves, but that seems like a bit of a waste of their time :)

**Comment by Doomgull** [comment]
This has existed as long as the mod has. Check your config file again. Key should be "giveJournalAtFirstJoin" iirc.
