### ISSUE TITLE
(Suggestions) Tweakable astral tome research & progression + Dimensions settings

### ISSUE THREAD

**Issue by bloche14** [HellFirePvP/AstralSorcery#1154]
Any chance we could have the ability (through crafttweaker or something else) to customize the contents of the astral tome, such as when researches are unlocked, or to disable some entirely, add new pages to the tome, etc? (For example in a modpack it might make more sense for the Celestial gateway to be unlocked much later in the game than by default.)

Another thing that would be useful is the ability to enable / disable constellations and starlight in given dimensions, as well as a set a general multiplier for starlight similar to the one given by altitude. For example, the Aether could be configured to have a higher starlight amount since it is "above" the overworld. 
As for disabling AS in dimensions, I know that some things are disabled in dimensions without flowing time, but starlight gathering still works in them and sometimes it might make sense to disable AS even in dimensions that do have flowing time.

**Comment by Doomgull** [comment]
You can already gate constellation unlocks using the gamestages integration, along with perk level limits.

The tome itself is not something that's easily modified that way, though you could make additions with an add-on mod.

Modifiable starlight values for the world isn't something that will be added.
