### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by Shadesnow** [HellFirePvP/AstralSorcery#1155]
When connected to the server, the warn is in the console and does not allow it to the server. https://pastebin.com/Trj60SNg

Last build

**Comment by Doomgull** [comment]
Full log please. Not partial.

**Comment by Shadesnow** [comment]
warn repeats, that's all there is to the problem
https://pastebin.com/crwf9Jqz

**Comment by Doomgull** [comment]
Then need pack name, astral sorcery version, and forge version

**Comment by Shadesnow** [comment]
Forge 2838, mod version : astralsorcery_1.12.2_1.10.19 and i don't understand what is "pack name". Full log will give nothing and there is a lot of private information.

**Comment by Doomgull** [comment]
It gives the full versions of mods involved. Java version. Several other pieces of info, like context before and after.

**Comment by Shadesnow** [comment]
"Java is OpenJDK 64-Bit Server VM, version 1.8.0_212, running on Linux:amd64:3.10.0-957.21.3.el7.x86_64, installed at /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre"

Players just can not log into the server with an error in the console, which I showed above. After the server is restarted, the players can log in again and everything is fine with them until a certain point. Dependencies to obtain such a result could not be found.

**Comment by Shadesnow** [comment]
I found the same or similar problem on mod GitHub (here), and it seems like it was said that the problem was solved.

**Comment by Doomgull** [comment]
If the ticket isnt closed with a marked release, the fixed code isnt released yet.

**Comment by Doomgull** [comment]
@Shadesnow care to elaborate on your last post? Closing this ticket otherwise.

**Comment by Shadesnow** [comment]
I gave all the necessary info

**Comment by Doomgull** [comment]
What was the ticket number you were referenc8ng.

**Comment by Shadesnow** [comment]
https://github.com/HellFirePvP/AstralSorcery/issues/1016
