### ISSUE TITLE
Resonating wand not working for others

### ISSUE THREAD

**Issue by Akagex** [HellFirePvP/AstralSorcery#1157]
Hello people,
We just made the luminous crafting table and we're playing on a FTB Interactions Server.
Whenever I want to craft anything it works just fine.
But when my friend (in the same party, same permissions level everything same) wants to craft something and klicks the table nothing happens for him and when he gives me the wand, it works just fine.
Does anyone have an Idea what could be causing this problem?
Ofc he tried left/right klickin and everything! :D
Restarting Server and Client does not work :(
Thanks in advance!

**Comment by Doomgull** [comment]
he does not have the required advancement. If his version of the Astral Tome does not show the item to be crafted, that's going be part of the problem. If you craft the LCT, and he has not done such a thing, and no one has created a scroll of knowledge sharing, he will need to also craft one.

**Comment by Akagex** [comment]
He crafted it by himself and I crafted mine by myself. But we'll give a lock if he maybe is missing something. Since he did the most progress in magic and not me that seems not to be the problem, since we also share progress.

**Comment by Doomgull** [comment]
Discord with screenshots for help then. Not a bug issue.
