### ISSUE TITLE
Celestial Gateway Completely crashes server

### ISSUE THREAD

**Issue by Piman801** [HellFirePvP/AstralSorcery#1159]
When ever I or anyone else on the server uses a Celestial gateway to teleport, The entire server crashes and gives everyone the crash "java io.ioexception forcibly closed by remote host". I don't have any crash logs, since I'm not the owner of the server.

**Comment by Doomgull** [comment]
Need to get logs from the server owner, then. Sounds like socket disconnection based on that error message, but it's literally guessing on source.

**Comment by Doomgull** [comment]
@Piman801 needs logs or I'm closing this, because there's literally no information to operate from. The error is a socket disconnection timeout, need to see what precedes it to know what is going on, and what's sending enough data it times out the connections.
