### ISSUE TITLE
Possible incompatibility with Lumien's Blood Moon mod

### ISSUE THREAD

**Issue by Sunconure11** [HellFirePvP/AstralSorcery#116]
https://minecraft.curseforge.com/projects/bloodmoon

The two mods run fine, but it seems the moon is not colored red during a blood moon event.

**Comment by HellFirePvP** [comment]
That's on lumien's end.

Instead of unsafely ASM'ing into the renderSky method he could've just made a chaining worldprovider.

**Comment by HellFirePvP** [comment]
Uncertain if this is actually doable without ASM - or rather: doable in a mod-compatible manner...

**Comment by HellFirePvP** [comment]
Welp, not much i can do at my end for this besides writing specific integration for this. Looking about bloodmoon's calculations for this, i would rather decline on that one... So, gonna close this.
