### ISSUE TITLE
E2E: The Amazing Disappearing Cursor

### ISSUE THREAD

**Issue by bluewarbler** [HellFirePvP/AstralSorcery#1161]
I'm playing the modpack Enigmatica 2: Expert, and when I use the hand telescope, it instantly disappears my cursor.  Not just on the hand telescope, it just permanently leaves, and the only way to get it back is to completely restart Minecraft.

**Comment by Doomgull** [comment]
I'm betting you're using a Mac, aren't you? #12

**Comment by bluewarbler** [comment]
I am indeed. The Force Quit thing works.
