### ISSUE TITLE
Connecting to another server with astral sorcery progression prevents login - unless I restart client

### ISSUE THREAD

**Issue by JayaramV-Hexaware** [HellFirePvP/AstralSorcery#1162]
I maintain 2 servers that are identical in all respects, except I have chosen different perks in Armara in each.  When I try to login to server 1, everything's fine.  When I logout and try to connect to server 2, I get the attached client crash.  If I restart the client and connect to server 2, everything's fine.

https://paste.dimdev.org/upodukiqil.mccrash

**Comment by Doomgull** [comment]
Update AS version. That is super super old, and the perk map stuff was already fixed:
"Astral Sorcery 1.10.10"

You'll need to run the "/as migrate-data" command after updating the mod.
