### ISSUE TITLE
Crash with Wings mod installed.

### ISSUE THREAD

**Issue by SirAron111** [HellFirePvP/AstralSorcery#1163]
Crash with Wings mod installed.

Wings 1.1.5 for Minecraft 1.12.2
MC 1.12.2
Forge 14.23.5.2838
AstralSorcery-1.12.2-1.10.19.jar

https://pastebin.com/FB3D2XN3

https://github.com/pau101/Wings/issues/39 more info here

**Comment by Doomgull** [comment]
What is the amulet "FogDad" is wearing have on it? And is he using anything from the Wings mod?

**Comment by SirAron111** [comment]
Don’t know exactly will have him tell me once he is back. Or send him here directly so he can provide the information as this one happened to him.

**Comment by pau101** [comment]
Hey, Wings dev here.

I have looked into this a bit and I believe I have some suspect code: https://github.com/HellFirePvP/AstralSorcery/blob/67b7e6e49b763d61c33d037bfa5807b882657c8e/src/main/java/hellfirepvp/astralsorcery/common/enchantment/amulet/EnchantmentUpgradeHelper.java#L271-L281

The `FMLCommonHandler.instance().getSide()` statement returns the physical side, not logical. As such when this function is called on the integrated server it will access the main thread/logical client's player instance and not the server's. This is the cause of the CME, the code can be corrected to use `FMLCommonHandler.instance().getEffectiveSide()`.

**Comment by HellFirePvP** [comment]
Well, if you're that dead set on this being the issue, i call it fixed then.
