### ISSUE TITLE
Rock/Celestial Crystal Dust?

### ISSUE THREAD

**Issue by Hallowizer** [HellFirePvP/AstralSorcery#1165]
Hi! I am working on a modpack, and I thought it would be helpful to have Rock Crystal Dust made on the Grindstone. However, I am not able to do this, because of the special handling of Rock Crystals. Instead of breaking when Rock Crystals are ground down to 0 size, can they become Rock Crystal Dust, or can they drop Rock Crystal Dust as they are ground down? Thanks!

**Comment by yagomont** [comment]
This could potentially be a config file option for modpack devs, as the dusts don't have any particular application by themselves.

**Comment by f-sage** [comment]
what purpose would the dust serve?

**Comment by Doomgull** [comment]
Grindstone won't be present in initial 1.14 mechanic changes, so irrelevant.
