### ISSUE TITLE
Wonky Staging On Newer Items' Descriptions

### ISSUE THREAD

**Issue by dualinfinities** [HellFirePvP/AstralSorcery#1167]
Certain knowledge items have descriptions that reference items unlocked in later chapters, resulting in the description being more confusing than helpful. The items in question are things that are related to Radiance items, but were added after them to the earlier Attunement chapter. These are : Domic Resonator (says modes can be changed "as before" when it is the first available resonator upgrade), Active Channeling(?) (what is an alignment gauge? it isn't anywhere in Attunement), and Perk Sealing (directly references the Irradiant Star, which requires an Iridescent Altar to craft).

**Comment by HellFirePvP** [comment]
More or less adjusted with the AS 1.14 tome/text changes.
