### ISSUE TITLE
Dupe telescope

### ISSUE THREAD

**Issue by bigenergy** [HellFirePvP/AstralSorcery#1170]
The bug is reproduced using a large axe and telescope from Astral Sorcery. We put the telescope, break it and get two working telescopes.

Forge 2838
astralsorcery-1.12.2-1.10.20

Video https://www.youtube.com/watch?v=Nry9GhBbRBg

**Comment by Doomgull** [comment]
What mod is the axe from? What launcher are you using?

**Comment by bigenergy** [comment]
@Doomgull Axe 3x3 from Tinkers Construct

![image](https://user-images.githubusercontent.com/17977139/64624425-4e8eb600-d3f3-11e9-81f5-488a58da18d6.png)

**Comment by Doomgull** [comment]
This sounds more like an issue with tinkers, to be quite honest.

Does it also occur if using an infused starlight axe?

**Comment by bigenergy** [comment]
@Doomgull I found a problem, the point is the enchantment of Scorching Heat.
If you remove this enchantment from any tool - there is no such bug

**Comment by bigenergy** [comment]
@Doomgull any ideas?

**Comment by bigenergy** [comment]
@HellFirePvP any ideas?
