### ISSUE TITLE
Astral Sorcery Treasure Shrines only Mining Stone

### ISSUE THREAD

**Issue by TheSmiffster** [HellFirePvP/AstralSorcery#1171]
Treasure Shrine Config file is fine and has ores configured but only smooth stone is spawning from the center stone block

and is enabled in astralsorcery.cfg

Any suggestion?

using the Dungeons Dragons and Space Shuttles modpack

Astral Sorcery Version: astralsorcery-1.12.2-1.10.19

**Comment by Doomgull** [comment]
Oredict entries only,
