### ISSUE TITLE
Crashing Logging into a Server (1.12.2)

### ISSUE THREAD

**Issue by veronicaaj** [HellFirePvP/AstralSorcery#1172]
My friend has been trying to get into my server, but he crashes as soon as it loads. He has all the same versions of mods and forge as I do, and I can get on just fine. 
pastebin.com/EVUXDeMy
He also crashes when opening a singleplayer game. He took out Astral Sorcery and he was able to open a singleplayer game without it crashing.

**Comment by Doomgull** [comment]
Something didn't install cleanly, looks like.

Recommend attempting to use twitch launcher with the mods instead of multimc and seeing if it makes a difference.

**Comment by veronicaaj** [comment]
That worked, thank you!
