### ISSUE TITLE
[Suggestion]Bukkit plugin Multiverse-core support

### ISSUE THREAD

**Issue by RisingInIris2017** [HellFirePvP/AstralSorcery#1173]
When create a new dimension by using this command:
[/mv create my_world NORMAL](https://github.com/Multiverse/Multiverse-Core/wiki/Command-Reference#create-command)
Multiverse will create a dimension like Vanilla Overworld, and nearly all resources added by mods will be generated.
But AstralSorcery's ores and Temples don't.
I think that it is needed to allow AstralSorcery generate its resources in another dimensions besides the Vanilla Overworld.

Here are some links you may need:
Multiverse's GitHub Wiki: https://github.com/Multiverse/Multiverse-Core/wiki
Multiverse's SpigotMC page: https://www.spigotmc.org/resources/multiverse-core.390/

**Comment by Doomgull** [comment]
"-Sponge or other server software is NOT supported. Any issues that arise when using Sponge (or other third-party server software other than Forge) that can't be reproduced in a Forge environment will not be fixed."

Also worldgen outside dim 0 is already supported in the configs.
