### ISSUE TITLE
1.12.2 client crash & graphic issues

### ISSUE THREAD

**Issue by RisingInIris2017** [HellFirePvP/AstralSorcery#1174]
When I joined a server installed AstralSorcery, some graphic issues occured, just like this:
![](https://i.imgur.com/dJvKNpj.png)
![](https://i.imgur.com/zH2AvAS.png)
Then game crashed, here are two crash-reports:
https://paste.ubuntu.com/p/5Gb4C5PqfN/
https://paste.ubuntu.com/p/R54bmwtrmy/

Other players didn't report these issues.

**Comment by Doomgull** [comment]
Does it happen without phosphor?

**Comment by RisingInIris2017** [comment]
Removed Phosphor from client's mods folder, but my game still crashed.
Phosphor is also installed on server-side, should I remove it too?

**Comment by Doomgull** [comment]
Gui are client side, no. Something is conflicting and causing things that shouldnt be null, to be null.

Does it happen in single player?

**Comment by RisingInIris2017** [comment]
Yes, both single player and multiplayer.

**Comment by Doomgull** [comment]
Unless you are accessing an observatory, I don't see why it should be called at all.

Would recommend test single player and removing mods until it stops happening, perhaps starting with AnotherCommonBugFix mod, as I am not familiar with it, but I see it does a lot of changes to various GUI calls.

Does your mod list perfectly match people not having the issue? If not, that may also be a place to check.

**Comment by HellFirePvP** [comment]
Yea, this in the observatory gui.
If you're not actively opening any gui as you stated and just logged onto the server, i suppose some mod is opening gui's seeingly at random.
Try binary search on which mod it could be. This isn't AS' fault.

**Comment by RisingInIris2017** [comment]
I got a hs_err_pid.log file. Maybe it's useful.
https://paste.ubuntu.com/p/CHXDxQbk3Z/

**Comment by Doomgull** [comment]
That means java suffered a fatal exception. Unrelated to this mod.
