### ISSUE TITLE
Hiking Boots not working

### ISSUE THREAD

**Issue by aaronhowser1** [HellFirePvP/AstralSorcery#1177]
FTBTeam/FTB-Academy/issues/61
Playing FTB Academy, which has astralsorcery-1.12.2-1.10.20.

I got the Hiking Boots perk on a server and it doesn't allow me to walk up single blocks.

**Comment by aaronhowser1** [comment]
I just made the Celestial Altar and now it's working

**Comment by Doomgull** [comment]
Those two things are unrelated. Something else in the pack is doing something unclean with the step height attribute system, like constantly setting it to some other value instead of adding or reducing height to it.
