### ISSUE TITLE
[Suggestion] New Version

### ISSUE THREAD

**Issue by Gekocaretaker1** [HellFirePvP/AstralSorcery#1178]
Is it possible for you to update it to 1.14 please?

**Comment by Doomgull** [comment]
It's been a work in progress for the last 6 months. Check the discord channel for updates in the git channel.

**Comment by Gekocaretaker1** [comment]
There's a discord?

**Comment by Doomgull** [comment]
Yes, it is clearly linked on the front page of this GitHub, as well as on the curse page for the mod.
