### ISSUE TITLE
Feature request - Privatized Celestial Gateways

### ISSUE THREAD

**Issue by aaronhowser1** [HellFirePvP/AstralSorcery#1179]
Some way to make it so that only specific players can access your Gateways would be amazing. Maybe like, right click the Gateway with a renamed Name Tag with that player's username to add them to the list of people that can see it? Default to allow anyone, until the nametag thing is done maybe

**Comment by aaronhowser1** [comment]
I made this issue because someone came through my portal while I was fighting monsters on the platform, and I instantly murdered them on accident

**Comment by squirrelkiller** [comment]
I was just about to suggest this, I would also like to request whatever method that is used, allows for easily adding new gates to a private network without having to carry 2 or 3 name tags for everyone concerned on hand.

**Comment by Doomgull** [comment]
Consolidating into #495 due to age.
