### ISSUE TITLE
[Suggestion] Creative menu journal - all knowledge unlocked

### ISSUE THREAD

**Issue by Tetrajak** [HellFirePvP/AstralSorcery#118]
As the title says, I'd suggest making the journal that is in the creative menu be one with all the knowledge unlocked. That way experimentation in creative is a lot easier.

**Comment by HellFirePvP** [comment]
/as help

most commands are listed there, they can be used to unlock all progression instantly. a creative journal is not planned atm; though it might not be too much work, but other things have priority atm.

**Comment by HellFirePvP** [comment]
Added next version
