### ISSUE TITLE
Constellations Not Being Discovered

### ISSUE THREAD

**Issue by ally135** [HellFirePvP/AstralSorcery#1181]
When I started playing my game I began to look for the shrines for constellation paper, as directed. When I found my first shrine, as well as many others I collected a bunch of constellation paper, yet only four of the bright constellations showed up. This is a brand new world, and I haven't previously discovered any of the constellations, and am aware that once they are all discovered the paper will stay as "there is nothing here"
My mod is at the most recent version, with only JEI installed at it's most recent. The papers just say that there is nothing there. I can drag them to my inventory from the JEI screen to discover a constellation, but it won't work naturally, and the description does not change to the name of the constellation.

**Comment by Doomgull** [comment]
Because you need to attune yourself to discover more constellations than the initial Brights.

**Comment by ally135** [comment]
Oh! Thank you soso much for your help. I'm new to this mod and wasn't aware. I wanted to try without looking at guides but I guess maybe I should've haha!
