### ISSUE TITLE
suggestion: option to disable/enable the "Trash to Treasure" Perk. 

### ISSUE THREAD

**Issue by weightmaker** [HellFirePvP/AstralSorcery#1183]
i read a few other issues about toggling different perks but i thought i'd raise attention to it anyway. 
The trash to treasure is basicly a trap imo. By reading the tooltip it sounds amazing, but it makes it so you can never get any cobble/dirt/etc blocks again until you un-attune yourself. 
I think even a keybind to toggle every perk would be better than having static buffs. 
This is just my thoughts tho and im interested to hear your thoughts.

**Comment by Doomgull** [comment]
Perk Seals are you temporary toggle
