### ISSUE TITLE
Mobs and Overall Graphics Being Weird

### ISSUE THREAD

**Issue by ally135** [HellFirePvP/AstralSorcery#1184]
Hi! I know I posted about some other weird issue a little bit ago, and thanks to you it was now fixed! Sadly, now I am having another issue. I loaded my game, which had previously had no problems with Astral Sorcery and found this weird graphic in what appear to be the mobs. I noticed other weird graphics before being able to screenshot this, but now I'm very confused. I tried removing Astral and that seemed to fix everything, but I don't want to have to play without it as it's a lot of fun to play with!

![image](https://user-images.githubusercontent.com/54923851/64902298-b9015980-d672-11e9-89b9-2016c094082e.png)

**Comment by Doomgull** [comment]
Some other mod isnt properly handling rendering code. It only becomes obvious with AS installed since there is something to interact with.
