### ISSUE TITLE
Allow changing the max level to beyond 100

### ISSUE THREAD

**Issue by martmists** [HellFirePvP/AstralSorcery#1189]
Some users/modpack devs may want to allow users to get even more perks and use quests to award points to the players or reward grinding these things. However, the cap of 103 skill points makes it difficult to get everything one would like. Please allow modifying this cap to allow being set to `nodes.length - 3` (-3 due to the +3 of the center node)

**Comment by Doomgull** [comment]
"Free"/granted/whatever perk points don't count towards the 100 cap. Only ones from levels gained.

**Comment by martmists** [comment]
How does one give perk points besides setting xp?
