### ISSUE TITLE
Cannot Retrieve the /dank/null/MK VI from the ME System (any storage cell)

### ISSUE THREAD

**Issue by brim4799** [HellFirePvP/AstralSorcery#1192]
Related to:  https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4168

That issue is closed with a note this is a known bug with Astral Sorcery but I do not find reference to it here.

**Description**
I put my /Dank/null from the mod /dank/null into the ME system by accident as it is something that can help me carry me more items.
When i tried to retrieve the /dank/null/MK VI from the storage cells it was stored in, it wouldn't let me.

**Environment**
So i tried to export it using a filter with the /dank//null in it, but it didn't work.
Using any type of exporter to retrieve the item from the system didnt work.
I identified the cell in which it was stored in and put it in a seperate ME network.
I tried again the Storage bus, export bus and the IO port to move the item, but it just doesnt.
Im not the only one that had this problem, my friend who plays on the same server ( Project ozone 3 version 3.1.44) also had the issue.
We now have 2 /dank/null/MK VI stuck inside 2 different storage cells...

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7
- Forge Version: 14.23.5.2838

**Comment by Doomgull** [comment]
I'm assuming it's related to https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4091 but I don't know what he's referring to, unless it's specific to how they match NBT compound tags because of the tag added to unstackable items (See #762 for explanation).

Which sounds like an AE2 issue doing something wrong. Would love to know why Yueh thinks it's an AS bug. Should probably press him for that. Especially if it's the issue I referenced, as that's 100% on them.

**Comment by urikkiru** [comment]
Just fyi, this is identical to an old reported issue: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2702

The solution is to use an Export Bus with a Fuzzy Card. I had the same issue, and was able to extract my dank/null that way.

**Comment by bulletproofbeard** [comment]
Fuzzy card worked like a charm.  I tried to the just the export before i found this thread and of course that didn't work.

**Comment by MalseJesse** [comment]
Can someone explain how this works in simple steps, bc I tried the export bus and Fuzzy card, but it still doesnt work, bc where do you connect it to?

**Comment by SkyElevation** [comment]
If none of the above things work for you create another /dank/null of the same type and set it as a filter for an export bus. I had to put my Disc with the /dank/null in an ME Chest and export it with a duplicate set as a filter.
