### ISSUE TITLE
1.12.2 Visual glitch with perk screen

### ISSUE THREAD

**Issue by algul** [HellFirePvP/AstralSorcery#1193]
Hovering over perk in the tome doesn't display perk description, but instead show full screen texture. This texture is not from astralsorcery mod, I checked. Running astral sorcery as the only mod works fine so it must be some kind of texture conflict, but I don.t know how to narrow it down with more than 100 mods other that adding 1 mod at a time. Is there any way to narrow it faster? What happens in the code when you hover over perk, does it render any texture? If yes, maybe I can narrow it by name of the texture.

**Comment by Doomgull** [comment]
50/50 the mods. If the half in the pack doesnt cause it, it isnt any of them. Keep adding half of the remaining until you find it happens again.

**Comment by algul** [comment]
I was able to determine that the problem mod is most likely ToughAsNails. But not 100% sure. With all other mods it works fine, when I add TaN it breaks. But running only AstralSorcery+TaN works fine as well. There must be third mod involved somehow. Also the texture that
 is displayed insted of the perk tooltip doesn't come from TaN either. This is the texture 
![minecraft](https://user-images.githubusercontent.com/8774483/66877558-398ae100-efb6-11e9-8229-735bc1c33fa9.png)
