### ISSUE TITLE
Attuned Collector Crystals + Pedestral causing Cursed Earth not to work properly

### ISSUE THREAD

**Issue by HerrGrinsel** [HellFirePvP/AstralSorcery#1194]
MC 1.12.2 / (FTB Revelation)

When you build a mob spawner using cursed earth to spawn mobs (and a mob crusher to kill them) it works out fine at the beginning althought the mobs get naturally pushed backed by the force field.

But when you switch on the light to pause the "spawner" (cursed earth) and turn it off after a while there won't be any more spawns.  Exchanging earth does not work not even "recursing" the dirt. Only if you move to a new location it will work once again.

**Comment by Doomgull** [comment]
What attunement? I am assuming Armara, but want to be certain.

Also, rituals give off light, are you sure that isn't the problem, and it working initially isn't the bug? A screen ahot would be helpful.

**Comment by HerrGrinsel** [comment]
I am sorry, of course it is Armara...forgot to mention it

**Comment by Doomgull** [comment]
Has this replicated for you? I have been unable to replicate it, and the ritual itself has no interactions with CE outside of giving off light.
