### ISSUE TITLE
Armara ritual breaks Botania mana spreaders.

### ISSUE THREAD

**Issue by davidgillen** [HellFirePvP/AstralSorcery#1195]
Have logged a bug on the botania side too. https://github.com/Vazkii/Botania/issues/2994

# Version Information
Forge version:  8.0.99.99
Botania version:  r1.10-362
Astral Sorcery: 1.10.20

# Further Information
Create a Ritual Pedestal with an Armara attuned crystal. This causes a push back for mobs and arrows.
Within the radius of the ritual try to use mana spreaders.

What I expected to happen:
The mana spreaders send mana to where I link them.

What happened instead:
The Armara ritual causes the mana to be fired away and lost.

**Comment by Doomgull** [comment]
That is because mana bursts are entities affected by knockback.

**Comment by ben-mkiv** [comment]
They are EntityThrowable, so IProjectiles while your mod does change their motion
https://github.com/HellFirePvP/AstralSorcery/blob/b8419dd3e8bfa9539fe6f09f05989bf6243ddfe3/src/main/java/hellfirepvp/astralsorcery/common/constellation/effect/aoe/CEffectArmara.java#L134-L143

So how about a configurable Blacklist for the Ritual or a Interface that others could implement to avoid their Entities to be affected by the Ritual?

**Comment by HellFirePvP** [comment]
> a Interface that others could implement

exists. check the first line you referenced.

In other news mana bursts, the entities fired by the mana spreader, can be damaging with the correct lens. making them a potential harm to either players or other entities.
