### ISSUE TITLE
[1.11.2] Client crash with 1.3.2

### ISSUE THREAD

**Issue by ruyanve** [HellFirePvP/AstralSorcery#120]
Using Forge 2282
https://gist.github.com/ruyanve/31491f048ee182a0cc7142b5638b433e

**Comment by HellFirePvP** [comment]
heavy derp. will re-release those versions...

**Comment by HellFirePvP** [comment]
fixed and re-uploaded.

**Comment by ruyanve** [comment]
Cheers!
