### ISSUE TITLE
Heavy Load Time on Server Startup (Profiling Data)

### ISSUE THREAD

**Issue by TheRealHypo** [HellFirePvP/AstralSorcery#1200]
Hey, I don't know if I did this totally right but for some days, rather weeks now the server starts slower and slower each day. Now I've took the time to profile it and it appears that something with Astral Sorcery is causing the Server to have a really bad hickup, after the dimensions are loaded. 

See this paste for some profiling data. I'll try to collect more.
[Pastebin](https://pastebin.com/yZenyEF3)

Current load time at that point is 10+ minutes, if no player accidentally already connects. If that happens, the Server won't start ever.

**Comment by Doomgull** [comment]
What version of AS?

Do you have a profiler output showing what is going on?

If the server started before AS 1.10.13, and is now at or after 1.10.13, was the "/as migrate" command ever run? If it is pre-1.10.13, upgrade and run it instead.

**Comment by TheRealHypo** [comment]
I might have to apologize, since a second profiling run shows another much worse culprit.

**Comment by TheRealHypo** [comment]
Profiling data shows that Non filled Fluid Tanks are the culprit. Sorry for the misinterpretation of my data :D
