### ISSUE TITLE
efab and Astral Sorcery

### ISSUE THREAD

**Issue by bdog73** [HellFirePvP/AstralSorcery#1201]
in efab the crafting grid cant craft tool if you Astral Sorcery is install.

**Comment by Doomgull** [comment]
Mod versions would be good, along with Forge version and what is trying to be crafted (and its ingredients). Full mod list, too.

I imagine it is an instance of #762 and a mod not properly handling compound tags, but really need useful information to work from. You have done the equivalent of calling an auto mechanic, telling him your car makes "a noise", and asked him to replace parts blind.

**Comment by bdog73** [comment]
mod version 0.2.0  forge version 2.6.2.83 
![2019-11-18_09 43 51](https://user-images.githubusercontent.com/51036217/69186384-6d41b500-0ae6-11ea-8314-1e382936eff8.png) when i click start nothing happen and i only have efab and Astral Sorcery.

**Comment by Doomgull** [comment]
And the astral sorcery version?

Does it work without AS?

**Comment by bdog73** [comment]
yes and 1.10.20

**Comment by Doomgull** [comment]
What is in the recipe jsons? Efab is a packbuilder tool.

**Comment by bdog73** [comment]
what?

**Comment by Doomgull** [comment]
Have there been any modifications to the stock recipe sample set it comes with. It's designed to be used as a pack Builder tool to expand out custom crafting, in a fashion not entirely unlike that of modular Machinery, though it does have a different set of functions for that. 

If there have been any modifications, additions, or config changes, it would be good to post those.

**Comment by bdog73** [comment]
i don't think so.

**Comment by Doomgull** [comment]
Only happens to non-stackable items, and only for the efab crafter. Issue can also be seen with vanilla armor, and a normal crafting table has no issues crafting them. 

Recommend re-opening your ticket on efab (https://github.com/McJtyMods/EFab/issues/42) and asking him to look into it there, as AS doesn't alter the recipes or crafting at all. It DOES however, add a capability tag to non-stackable items for leveraging the Resplendent Prism's temporary enchantment boosts while worn, (#762).
