### ISSUE TITLE
own server crash

### ISSUE THREAD

**Issue by LynicTaken** [HellFirePvP/AstralSorcery#1203]
I cant create my own server. Im try early versions mod and forge but its not working. I only have AstralSorcery and Baubles mod.

This attach my last try, last version mod but 2824 version for forge.

[crash-2019-11-21_21.41.02-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/3876233/crash-2019-11-21_21.41.02-server.txt)

**Comment by Doomgull** [comment]
Does it happen on relaunch?

**Comment by LynicTaken** [comment]
I cant launch, directly crashing.

**Comment by Doomgull** [comment]
Try forge 14.23.5.2846 instead.

**Comment by LynicTaken** [comment]
Crashed again.
[crash-2019-11-22_00.02.27-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/3876750/crash-2019-11-22_00.02.27-server.txt)

**Comment by Doomgull** [comment]
I'm unable to replicate this. Maybe try deleting and recreating the instance in whatever launcher you are using? 
![image](https://user-images.githubusercontent.com/12677933/69387168-06153380-0c93-11ea-8696-8593db61403c.png)

**Comment by LynicTaken** [comment]
I dont understand but Im using original Minecraft launcher. I can play normal minecraft with mod but cant start a server.
![Adsız](https://user-images.githubusercontent.com/43323950/69424549-f866b900-0d39-11ea-8597-aa42ec85dc66.png)

**Comment by Doomgull** [comment]
Again, unable to reproduce for server launch or client launch on my side. How are you launching the server, and what from?

**Comment by LynicTaken** [comment]
Im creating a server for playing with my friends. Not a official job. Im just starting a port server with .bat (cmd) program. But its crashing every time. If I delete Astral mod then I can start but with Astral mod I can start server.

**Comment by LynicTaken** [comment]
Here my server files;
http://www.mediafire.com/file/1pq2hue3k7e75vh/mc_server.zip/file

**Comment by Doomgull** [comment]
Issue was turkish language for java resulting in malformed name translation. Won't happen in 1.14 release, unlikely to see a code change in 1.12 to address, however. Specify using a non-turkish language for java as workaround.
