### ISSUE TITLE
Overworld structures always spawn in buggy

### ISSUE THREAD

**Issue by Velocihater** [HellFirePvP/AstralSorcery#1204]
![2019-11-22_22 23 52](https://user-images.githubusercontent.com/40730042/69473375-42bb5a80-0d79-11ea-9445-68940dbbbc15.png)
![2019-11-22_22 23 56](https://user-images.githubusercontent.com/40730042/69473376-43ec8780-0d79-11ea-9744-5622b7fa8345.png)
![2019-11-22_22 23 59](https://user-images.githubusercontent.com/40730042/69473377-451db480-0d79-11ea-9a9e-f6788b2ece00.png)

This isn't the only instance btw. They always spawn in over empty gaps, making them look weird and incomplete. Perhaps there could be a check that would only allow them to spawn in if there's terrain under?

**Comment by HellFirePvP** [comment]
"Always" is a pretty harsh statement.

It does check for discrepancies on the corners and center regarding the distance to the ground vs. the lowest spawned block and limits that usually to 2-3 blocks. If you always check for guaranteed flat surface, try finding one by chance on a hilly terrain. Either you accept the way this is or you get basically no structures spawning at all. It's fine as it is and i'll leave it like this.

**Comment by Doomgull** [comment]
Also, you can make the spawn config parameters more harsh. This already exists as a feature.

**Comment by HellFirePvP** [comment]
Right. you can navigate to the configuration's "worldgen" section, pick the structure you're looking for and set the "heightThreshold" to 1. that'd check more accurately, but will also result in drastically fewer structures - as there are far less appropriate places found to spawn the structure at.

**Comment by Velocihater** [comment]
![2019-12-24_00 59 35](https://user-images.githubusercontent.com/40730042/71631606-1e039f80-2bcf-11ea-8344-b8ddc7152e6b.png)
![2019-12-23_14 15 42](https://user-images.githubusercontent.com/40730042/71631612-28259e00-2bcf-11ea-877d-97e6fe445e2e.png)
![2019-12-19_20 44 52](https://user-images.githubusercontent.com/40730042/71631615-2e1b7f00-2bcf-11ea-805e-bc808b6759a8.png)
![2019-12-07_20 04 52](https://user-images.githubusercontent.com/40730042/71631640-530ff200-2bcf-11ea-8785-38a337dc7ac3.png)
![2019-12-08_18 22 24](https://user-images.githubusercontent.com/40730042/71631644-5acf9680-2bcf-11ea-9498-a7978ddbda60.png)
![2019-12-07_20 03 49](https://user-images.githubusercontent.com/40730042/71631646-5c00c380-2bcf-11ea-82bd-7e2c33a59e97.png)

I set it to heightThreshold 1, and it works better for the most part. However, some structures still spawn weird. Anyway to ensure that they won't spawn over cliffs? I'm honestly okay if they would spawn less

**Comment by Doomgull** [comment]
Continue to tweak the spawn parameters in the config to be more restrictive. Get ready for potentially very very very large distances between them, though.
