### ISSUE TITLE
Chiseling "base" Sooty Marble

### ISSUE THREAD

**Issue by TrekGIneer22** [HellFirePvP/AstralSorcery#1205]
Is there a reason you need to craft Astral Sorcery Sooty Marble into bricks before you can chisel it? You can chisel base Astral Sorcery Marble, just seem like an odd thing, and it leaves me with 1-3 leftover "base" blocks at times.

I asked this over at Chisel and they say it is on your end not theirs?

**Comment by Doomgull** [comment]
Because base sooty isn't tagged for it, and all non-base sooty is only decorative.

**Comment by TrekGIneer22** [comment]
I am playing on a pack (and new to modded) and for a minute I thought something was messed up, but the community for the pack helped me out but suggested I report it.
