### ISSUE TITLE
Too many structures spawning after update.

### ISSUE THREAD

**Issue by leglerm** [HellFirePvP/AstralSorcery#121]
Today we updated to the newest version (1.3.2 according to curse and i dont know if its the "new" 1.3.2 or the "old") and after exploring this happened:

![2017-04-17_16 22 27](https://cloud.githubusercontent.com/assets/13408657/25091556/1e0e8b8e-238a-11e7-8fba-9a3ffa89a4a1.png)

**Comment by Tarod7** [comment]
same here
![2017-04-17_09 29 48](https://cloud.githubusercontent.com/assets/27015966/25091811/895cf14e-2350-11e7-9f33-7189441ffc64.png)

**Comment by HellFirePvP** [comment]
Re-upload done, the new 1.10.2 version should be available in a few minutes~
