### ISSUE TITLE
Hall of Mirrors effect while holding an Armourer's Workshop reskinned item

### ISSUE THREAD

**Issue by DoomRater** [HellFirePvP/AstralSorcery#1212]
The bottom of the sky, sun, and moon fail to render correctly while an item is held that has been reskinned by Armourer's Workshop, producing a hall of mirrors effect.  I've observed this effect using AS 1.10.20 and Armourer's Workshop 0.49.1.481. The stable of Armourer's also does it, which is version 0.49.1.6.

I'm not entirely sure where the issue is, but RiskyKen seems easy enough to approach and has open source code which hopefully should help.

**Comment by Doomgull** [comment]
Sounds like an improper glstate being set by AW.
