### ISSUE TITLE
Custom Modpack cant launch, stops responding in Initializing mods Phase 1

### ISSUE THREAD

**Issue by RappidZz** [HellFirePvP/AstralSorcery#1213]
Hi! I installed a custom modpack and everything seemed correct until now, when i launch the launcher it stops loading and responding in Phase 1. I attach a screenshot, the file and the log.

Screenshot: https://gyazo.com/e11cc07791b513ae9c2e1446806d67d9

Log: [Log.txt](https://github.com/HellFirePvP/AstralSorcery/files/3981402/Log.txt)

Mod File: https://we.tl/t-yo36X3L7WI

Tell me if you need ant further information. Hope it gets fixed.

Thanks for the help!

**Comment by RappidZz** [comment]
I uninstalled minecraft and isntalled again, deleted .minecraft file completely and now it isn´t launching either without any mod. The heck.

**Comment by Doomgull** [comment]
I see no AS related or triggered errors in there.
