### ISSUE TITLE
Change XP per Level to be a config option.

### ISSUE THREAD

**Issue by V2LenKagamine** [HellFirePvP/AstralSorcery#1214]
On ATM3:R, the max level is 100. To get past 32, you basically have to farm for an hour or set the exp mutli to X2 to make ANY progress. So could we get an option to HOW the exp per level is calculated?
For example, instead of the current (I assume) logarithmic function, a linear XP or [Level * 1000]+ 1000.
This may cause serious balance issues if changed, but I think it should be up to the user if they want to make the mod broken OP.

**Comment by V2LenKagamine** [comment]
changed my mind

**Comment by Doomgull** [comment]
It is intentionally absurd. There are far fewer complaints about xp rate than there were for people asking for more levels. There exists the ability to use commands to increase the XP and bypass this, which work with Quest Books, there's also craft tweaker support for items to add additional perk points if you want more points without actually increasing levels. And this is never changing.
