### ISSUE TITLE
NBT being a layer deep makes problems

### ISSUE THREAD

**Issue by aaronhowser1** [HellFirePvP/AstralSorcery#1215]
Putting all NBT in {astralsorcery:{}} makes a lot of problems for NBT-matching. Is there any reason to have everything in one NBT tag? Stuff like the upgrade status of sextants and wands, why is that two layers deep? And the bound location for sextants. It makes it hard to make quests for those items, since the NBT for the location a Sextant is bound to is in the same place as whether or not it's upgraded. I can't remove the NBT for its location and have it to only match the upgrade status either, because it's more than 1 layer deep. Is there any reason to having them all be inside {astralsorcery:{}}? Maybe that could be changed when the mod updates to 1.14+, since that requires basically a full rewrite anyway?

**Comment by Doomgull** [comment]
Because that's how compound NBT tags are supposed to work. It's the whole point of that system.

**Comment by aaronhowser1** [comment]
@Doomgull I've not seen another mod that does this though. Botania doesn't put Mana or SoulbindID in {botania:{}}, it just does like `{mana:10000}` and {soulbindUUID:XXXXXXXXXXXX}`. That means its easy to filter for amount of mana etc.

**Comment by Doomgull** [comment]
That is because some mods you use Simple NBT tags, or never changed over when updating. all of which is 100% irrelevant. Handing out a prebound Sextant is well outside the scope of how that system is supposed to function in the first place
