### ISSUE TITLE
Nullpointerexception during login for playertick

### ISSUE THREAD

**Issue by chuggafan** [HellFirePvP/AstralSorcery#1216]
https://pastebin.com/SZVBCn6t

This is the line causing the nullpointerexception:
https://github.com/HellFirePvP/AstralSorcery/blob/baeb33d771da21662798987d8fee2c32144a52b7/src/main/java/hellfirepvp/astralsorcery/common/auxiliary/tick/TickManager.java#L91

The relevant lines that seem to be called causing this from galacticraft are: https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/entities/player/GCEntityClientPlayerMP.java#L388

As far as I can tell, Galacticraft is attempting to update the player entity and the astral sorcery tick handler is catching this and attempting to iterate through the registered tick handlers, but here somehow no registered tick handlers exist, which means that the onUpdate call was called before the constructor was completed (I am guessing). 

This is happening on login for a multiplayer server and since I don't know the exact cause of this (or any blocks) I can only post this here for now.

Also, I'm not sure who to ping for this issue but since the nullpointerexception is occurring here and Galacticraft at least seems to not be doing anything wrong as far as I can tell I'll put it here.

**Comment by Doomgull** [comment]
Pretty sure it's because it eventually polls back to the use of EntityPlayerSP and not EntityPlayerMP on their side, but will look deeper into it.

**Comment by chuggafan** [comment]
So with the help of a server admin I've gotten it solved for me on login, somehow by changing the onGround property from true to false this was fixed, I have no idea why or how but it was.

**Comment by Doomgull** [comment]
The property in your player file? Or is this a config value somewhere

**Comment by chuggafan** [comment]
The property in my player file specifically. They also moved me to spawn beforehand but that didn't solve the issue when it was done alone.
