### ISSUE TITLE
Phoenix player health threshold may be incorrect.

### ISSUE THREAD

**Issue by borg286** [HellFirePvP/AstralSorcery#1217]
https://github.com/HellFirePvP/AstralSorcery/blob/2c9b329876dc48e344d20bee391fc5a969532bbe/src/main/java/hellfirepvp/astralsorcery/common/constellation/perk/tree/nodes/key/KeyCheatDeath.java#L80

After looking through the code and thinking about situations where I would want this perk to apply, it seems that the conditional to only apply when the player is low on health may be misplaced.
It seems to be written to only trigger when the player is just about to die (player health <= 4, incomming damage >= 6), but wouldn't seem to apply to really hard hits like from this dude: https://abyssalcraft.fandom.com/wiki/J%27zahar,_Gatekeeper_Of_The_Abyss
I realize that abysalcraft probably should redesign itself so as to not deal so much damage, but these one-hit-wonders are just the kind of thing that I'd want phoenix to apply to as a get-out-of-jail-free card.
I don't know of the event that this code is listening to has damage post or pre armor/toughness calculations.  Of course I wouldn't want it applying every time I face some shogoths when my armor would reduce the damage anyways.  Still I'd like it to handle a god-smack when I come at him with full health.

**Comment by yagoplx** [comment]
Huge damage hits also seem to be the case with the chaos guardian from Draconic Evolution. There's already a Chaos Damage reduction on the mantles so this would be a good extra touch.

**Comment by Doomgull** [comment]
Sorry, missed this.

The point of the values is that in a pack with a use-case instance like that, you would want to change the thresholds so they matched. By default, if the player takes a hit that would kill them while at less than 4 health (controlled by thresholdApplyPerkHealth, which is a config value), or if they take a hit that would kill them that is greater than 6 damage (thresholdApplyPerkDamage, which is a config value), it will trigger. This covers all those big bosses that just deal shit tons of damage for no reason other than just to force people to use something from that same mod to mitigate it and/or due up bad mob/mod design within MC. The "normal" use cases aren't going to end up outside of these parameters. If your pack includes something that should be seeing this regularly, AND you feel as a pack dev that this perk should be a guaranteed trigger every single time, then please alter the config defaults.
