### ISSUE TITLE
Add option enable horologium affect player

### ISSUE THREAD

**Issue by JackCarterSmith** [HellFirePvP/AstralSorcery#1218]
Hi,
I would like to know if it was possible to make the horologium ritual possible on the players. For example the classic ritual, would add speed to the players, while the corrupt will slow down the player enormously, close to immobilization.

Maybe a boolean to be activated in the config?

**Comment by Doomgull** [comment]
It is possible, but outside the scope of the desired power for the ritual. Tick acceleration is already very powerful, and adding speed on top would be pretty strong. You can also gain haste and speed from potions crafted using Horologium.

Also, alcara already does that.
