### ISSUE TITLE
Starlight produces water particle

### ISSUE THREAD

**Issue by TheUntamed** [HellFirePvP/AstralSorcery#1219]
Throwing something into Liquid Starlight, or stepping into it produces blue water particles.
Maybe that could be changed.

**Comment by Doomgull** [comment]
Does this happen with AS as the only mod?

**Comment by HellFirePvP** [comment]
Is known and due to how they get created, i can't do much about it without a large amount of hackery. That being said, i won't tackle this in the 1.12 build(s) anymore.
