### ISSUE TITLE
Worldgen overpopulating

### ISSUE THREAD

**Issue by charlesbevans** [HellFirePvP/AstralSorcery#122]
I've seen more shrines and sanctuaries than I expected generated in certain BoP biomes, especially cold deserts, glaciers, ice plains, etc. None of these are at high altitude either. Today I started a new world and was greeted by 17 shrines at spawn. (I just updated to 1.10.2-1.3.2-Beta.)
![2017-04-17_08 29 20](https://cloud.githubusercontent.com/assets/15851438/25093941/98c5cb30-2349-11e7-9a0c-ebaa21a1f69d.png)
![2017-04-17_08 30 17](https://cloud.githubusercontent.com/assets/15851438/25093942/9a8703ee-2349-11e7-95c6-b507316cba9b.png)
![screen shot 2017-04-17 at 8 43 51 am](https://cloud.githubusercontent.com/assets/15851438/25094032/0d1291a8-234a-11e7-911c-6c6185f54eee.png)

**Comment by Saereth** [comment]
Duplicate of https://github.com/HellFirePvP/AstralSorcery/issues/121, download the reuploaded file from curse.

**Comment by HellFirePvP** [comment]
> (I just updated to 1.10.2-1.3.2-Beta.)

you *still* get that issue on 1.3.2 ? it stopped happening for me in the dev environment - odd..

**Comment by Saereth** [comment]
I just tested the newly updated one and we arent seeing it happen... will try a few other bop options

**Comment by Saereth** [comment]
http://imgur.com/a/TuNAQ
actually had to fly around for a while before finding even one. This is a fresh install/fresh world as of 2-3 mins ago.

**Comment by HellFirePvP** [comment]
Uhh.. so i suspect the reported screenshots were on an outdated version..

**Comment by charlesbevans** [comment]
Could another mod be interacting with the generation? I literally updated the mod, loaded MC, and started a fresh world to pregen chunks to profile for Just Enough Resources.
![screen shot 2017-04-17 at 9 12 08 am](https://cloud.githubusercontent.com/assets/15851438/25094899/faf01b72-234d-11e7-8909-63e9adf60e88.png)

**Comment by HellFirePvP** [comment]
Alright, try reproducing it with only AS, forge and BOP. Try letting the config for AS recreate (backup the config & delete it - in case you actually modified the config).

**Comment by charlesbevans** [comment]
I'll play with this later today and tomorrow and see if I can find the culprit.

**Comment by charlesbevans** [comment]
It seems my copy of Astral Sorcery was the culprit. Apparently the StructureAncientShrine.class, StructureDesertShrine.class, and StructureSmallShrine.class differ from the 1.3.2 file when I download it fresh. Does this have anything to do with the re-upload?
