### ISSUE TITLE
Health Lost Upon Server Restart

### ISSUE THREAD

**Issue by FoxMcloud5655** [HellFirePvP/AstralSorcery#1220]
When the server restarts, the player will lose health down to their max health as defined by their playerdata before the perks can kick in and set the appropriate max health.

One way this may be possible to fix (if there's no easy way to fix this) is to save the current HP of the player upon server close, then wait for a second after the server opens to reset their HP to the stored value and clear it out.

**Comment by Doomgull** [comment]
#1166 still applies.

**Comment by FoxMcloud5655** [comment]
My apologies.  I did a quick search for "health" and didn't find anything, so I created a new issue.
