### ISSUE TITLE
[1.12.2] Linking lens to alter seems to be crashing the server

### ISSUE THREAD

**Issue by Nelly1234567** [HellFirePvP/AstralSorcery#1221]
It would seem, for whatever reason, when linking a lens to the alter it will crash my server. This is using the latest version of 1.12.2 forge (forge-14.23.5.2847).

Here's a link to the crash log: **https://paste.dimdev.org/obagamajub.rb**

Hope this can be resolved soon!

**Comment by Nelly1234567** [comment]
P.S. Forgot to add that I did not see this issue looking through the other opened issues. Apologies if I missed it.

**Comment by Doomgull** [comment]
What did you do to obtain the lens? What are the stats on the lens? It should not be possible to receive an NPE there unless something is pretty broken in the world.

**Comment by Nelly1234567** [comment]
Unfortunately, it wasn't me that caused the issue or was working with it but, a user of my server was the one causing the crash and they found the issue. They had duplicated the lens with the Project EX (a Project E addon) Final Star on the Dark Matter Pedestal causing the server to crash or at least crash when using one of those copied lenses. This is due to how it removes any needed NBT information and makes it an absolute base item that otherwise would not be possible to get.

This issue should be resolved now.

My apologies for the inconvenience.
