### ISSUE TITLE
Change Mineralis Block to change from?

### ISSUE THREAD

**Issue by drago87** [HellFirePvP/AstralSorcery#1224]
Is it possible to change the block the Mineralis Ritual cyhanges?

**Comment by Doomgull** [comment]
Not presently.

**Comment by SeriousCreeper** [comment]
This would be super useful for pack making. Currently trying to integrate AS with TerraFirmaCraft, which replaces all vanilla stone with custom ones. Having a ReplacementStone list like the rock crystal config would be really awesome.
