### ISSUE TITLE
Disable this item?

### ISSUE THREAD

**Issue by Yourname942** [HellFirePvP/AstralSorcery#1225]
Is it possible to disable/blacklist the nightvision enchantment book?

**Comment by Doomgull** [comment]
AS doesn't add it to the vanilla enchanting table, check with the mod doing that.

**Comment by Yourname942** [comment]
I'm not sure what is..

Here is my current modpack setup:
[test1-1.0.0.zip](https://github.com/HellFirePvP/AstralSorcery/files/4055186/test1-1.0.0.zip)

**Comment by Doomgull** [comment]
Unsure, lot of mods I'm uncertain of their inner workings.

Also we don't support disabling enchants from this mod in general #495 since they shouldn't show under the normal enchanting table unless another mod is interacting with it.
