### ISSUE TITLE
Feature Request: Cave Deluminator

### ISSUE THREAD

**Issue by kiyanis** [HellFirePvP/AstralSorcery#1228]
On servers, aesthetic builds are constantly ruined by players forgetting to seal the Miner's Delight perk. Would it be possible to add a block similar to the Cave Illuminator that instead targets and removes all Miner's Delight / Cave Illuminator light sources in a large area of effect?

**Comment by Doomgull** [comment]
Already in the "master denial" ticket. Use the illumination wand to remove them, or teach people to be courteous about playing on a server or with other people.
