### ISSUE TITLE
Can not scroll to the right in the Astral Tome or Telescope

### ISSUE THREAD

**Issue by Bradley-Ford32** [HellFirePvP/AstralSorcery#1229]
When I am searching for constellations using the telescope, I am able to scroll left, but not able to scroll right.  I addition (and more frustrating), when I am using the Tome, I am unable to scroll right.  This keeps me from being able to see any of the constellation pages except the first page.  I am not sure what information I can provide.  Everything else seems to be working just fine.

**Comment by Doomgull** [comment]
Have you rebound your movement keys?

**Comment by Bradley-Ford32** [comment]
I have not rebound my movement keys, but I have rebound some others.

**Comment by Doomgull** [comment]
Modlist? I cannot replicate this, and assume something is interfering. Maybe a screenshot of what it looks like on your side?

**Comment by Bradley-Ford32** [comment]
I apologize for the screenshots.  I figured that was the easiest way to show you all of the mods and my system specs.  If there is a better way that will make solving this easier, I'm happy to do it.  Some additional information, the Dank/Null mod does not work properly either, but I have been able to fix it.  Once I have "filled" my Dank Null, it does not automatically void the extra items.  They just end up in my inventory.  Maybe this is totally unrelated, but I figured all of the information I could share would be best.  Thanks for the help.

![image](https://user-images.githubusercontent.com/38791429/73124664-c9540a00-3f6b-11ea-93b2-eeb1a0d71e83.png)

![image](https://user-images.githubusercontent.com/38791429/73124668-d3760880-3f6b-11ea-9012-77a24dfb21a2.png)

![image](https://user-images.githubusercontent.com/38791429/73124670-da9d1680-3f6b-11ea-9175-784bd3922a31.png)

**Comment by Bradley-Ford32** [comment]
Any ideas on how I can get this corrected or what mod may be interfering.
My mod list is mostly the FTB Revelation pack.  I've just added a few
additional mods as well as updated a few of the mods that were having
issues.

**Comment by Doomgull** [comment]
Could always try making a copy of your world and using it for testing by removing the extra mods you added outside of that pack and seeing if it's still occurs then. I can't replicate it, and we've not had any reports of this happening otherwise with PCs.

**Comment by HellFirePvP** [comment]
Did this resolve itself? Or what's the status here.
