### ISSUE TITLE
Conflict with RealBench

### ISSUE THREAD

**Issue by raltus** [HellFirePvP/AstralSorcery#123]
I had RealBench in my mod list when I went to the temple to start this mod. When I placed the crafting bench the beam of light never happened. I figured that it might be the conflict and took the mod out but it still wouldn't work even without RealBench. I had made a copy of the world and tried it in the newly loaded temple and it worked. I ended up using MCEdit to delete the temple and regen the chunks, it worked after I did. Since I don't know which mod is directly responsible I'm posting this conflict at both.

**Comment by Doomgull** [comment]
Considering realbench modifies vanilla crafting tables, going to go out on a limb and say RealBench. There's a reason Ticon extends crafting tables for their stuff instead of ASKing vanilla ones.

**Comment by HellFirePvP** [comment]
RealBench does a metric ton of ASM and adds tileentities to each crafting table in order to render the items on top of it via TESR

This is on RealBench's end and i won't fix that.
