### ISSUE TITLE
Server console error

### ISSUE THREAD

**Issue by EnterFor** [HellFirePvP/AstralSorcery#1231]
![image](https://user-images.githubusercontent.com/10114685/74088279-8b102c00-4acf-11ea-98dd-22ea1c6f2d97.png)

Forge：2847
Mod version：1.10.22
Server：CatServer-universal

The reason is unknown, the console appears repeatedly
Sorry, my English is not good. I'm Chinese

**Comment by xGarionx** [comment]
Same issue same Mod version. In our case its the Amara Constellation firing this issue on player join , claiming he is hit be a wooden spike and force disconnets him after several error repeats. The general issue however is the same. Prior to that but maybe unrelated is a error that occured calling it.unimi.dsi.fastutil.chars.AbstractChar2ObjectFunction.put(AbstractChar2ObjectFunction.java:119) ~[fastutil-7.1.0.jar:?]  wich resulted in a Unsupported Exception.

**Comment by Doomgull** [comment]
Server log upload for review would be appreciated.

**Comment by EnterFor** [comment]
Sorry, the log is gone. I will upload the full log when it appears again

**Comment by xGarionx** [comment]
here the server log https://hastebin.com/piciculoru.shell

**Comment by xGarionx** [comment]
and the corresponding client crash log .  https://hastebin.com/zawuhadali.rb

The disc/error server side and the crash client side are pretty close on the time scale (difference in hours are related to time zones), still both might be unrelated to each other.

**Comment by EnterFor** [comment]
> here the server log https://hastebin.com/piciculoru.shell

The report you provided was not AstralSorcery's fault

**Comment by EnterFor** [comment]
> and the corresponding client crash log . https://hastebin.com/zawuhadali.rb
> 
> The disc/error server side and the crash client side are pretty close on the time scale (difference in hours are related to time zones), still both might be unrelated to each other.

Please remove VanillaFix

**Comment by xGarionx** [comment]
Thanks for the help that apperently fixed it for the User ^^

**Comment by HellFirePvP** [comment]
Uhm, i guess this is resolved then?

**Comment by xGarionx** [comment]
Mostly i guess, it seems to be still a mod interaction issue at least in some corner cases,other user didnt report any issues and only in this case of him trying to connect the console fired null pointer exceptions like crazy.
