### ISSUE TITLE
Change colour contrast 

### ISSUE THREAD

**Issue by AllySummers** [HellFirePvP/AstralSorcery#1232]
Hi.

I've been trying to enjoy some things with Astral Sorcery, but I've noticed a lot of things within the mod have very poor colour contrast (especially to those with varying degrees of colour blindness).

The contrast on the browns in the journal was, in my opinion, very poor and at least initially made it difficult for me to find buttons, especially on some of the pages like shown below.
![image](https://user-images.githubusercontent.com/9024018/74094496-68652e00-4b36-11ea-9081-c564d576a25c.png)

This example here was much worse, especially for me. The pink lines tend to almost blend in with the gray, unless you look very very closely and the straight line on the right was basically invisible to me.
![image](https://user-images.githubusercontent.com/9024018/74094474-06a4c400-4b36-11ea-9581-8e6b64e4d413.png)

I'm not sure how many other people have this problem, but it could be an idea to change the button colours for example on the journal to have a box with a solid colour, and a colour that stands out in relation, like this example from EnderIO with the white/grey buttons on the right: 
![image](https://user-images.githubusercontent.com/9024018/74094512-a2363480-4b36-11ea-9864-1b5d3e9ababd.png)

And with the colours on the iridescent altar, it could help to be able to make it something such as green, or allow a user configurable option.

Although not super important, here's the versions:
**Astral Sorcery Version**: 1.10.22
**Minecraft Version**: 1.12.2
**Forge Version**: 14.23.5.2847
**Modpack**: Project Ozone 3

**Comment by Doomgull** [comment]
Consolidating into #495 due to age.
