### ISSUE TITLE
Shooting stars damage terrain in a circle around chunks loaded over time

### ISSUE THREAD

**Issue by darchitectlp** [HellFirePvP/AstralSorcery#1233]
Firstly, thanks for a great mod. Now on to the trouble.

It looks like AS shooting stars are destroying loads of terrain in a circle around the edge of my loaded chunks... I switched off explosions in the config now to stop that. However, can you make the description in the config a little more specific, i.e. specify that "little explosion" means actual terrain damage?

And, not that this is a bug or that you should care... but why is it a perfect circle around the edges of my loaded chunks? My render distance is set to 21, and I don't think I've ever seen a shooting star at all... I'm wondering if maybe the stars don't render? Or they originate overhead and then fly as close to the render distance as they can? I'm just kind of fascinated by that. Anyway, here's the imgur album I posted to reddit when I was trying to figure out what was doing this. The terrain damage can be seen inside the white circle. It seems to be particularly dense in the southeast and northwest.

https://imgur.com/a/fd6IcHI

**Comment by Doomgull** [comment]
They spawn overhead around midnight, travel fairly flat around y500 for a bit, then crash down. Normally they would pass into an unloaded chunk and despawn if not being chased, but at 21 chunk render distance that won't happen. If you aren't looking up when they are there, you won't likely see them.

How much more descriptive does a config value need to be for the use of "explosion" to be considered like all MC explosions and be terrain destructive? It is the same term used for creepers, tnt, and wither heads.

**Comment by DoomRater** [comment]
I guess people think "If I disable mobGriefing, it'll disable it for everything" even though that won't save someone's world from flux rifts or similar destructive events in other mods.  Ice and Fire has config option levels to allow dragons to do more damage regardless of mobGriefing settings or disable their damage even without mobGriefing.

This is a reminder I need to turn that damage off for my server world lest it actually smash someone's decorative build.

**Comment by darchitectlp** [comment]
Set to true to make shooting stars do a little explosion **and terrain damage** where they land [default: true]
@Doomgull If I had read that in the config initially, I would have completely understood what was happening. Just saying, add three words and eradicate confusion on the user's end. Up to you. Terrain destruction is a big deal for a lot of people. But thank you again for your help.
