### ISSUE TITLE
[Request] Possible interaction with Immersive Engineering and Lights in general

### ISSUE THREAD

**Issue by DoomRater** [HellFirePvP/AstralSorcery#1234]
I was reading a post about how developed countries differ from developing ones and one of the comments pointed out the sheer number of lights in developed countries.  They make things safe, but boy do they make it hard to see the sky with all that light pollution.

Is it possible to obscure the night sky a bit more, making constellations harder to see if there are powered lanterns on in the surrounding area?  Or floodlights, or arcane lamps from Thaumcraft that are turned on?  I'm not sure how someone would go about implementing this well- standing in or near light is one thing, but standing in a mob-proofed area due to powered lanterns would be another.

**Comment by HellFirePvP** [comment]
Right.
While this sounds pretty neat in concept, doing this as actual mechanic would be very impactful on performance.
So while i would like - and to some degree attempted to in the past - pursue this idea, i see no real way to actually pull that off in a performant manner that.. doesn't ruin servers trying to run the mod.

Sorry.

**Comment by DoomRater** [comment]
Thanks for the quick reply.  Now hopefully others can search and see that it's been suggested before.
