### ISSUE TITLE
Constellations Not Showing up in sky at night 

### ISSUE THREAD

**Issue by Freedom16789** [HellFirePvP/AstralSorcery#1235]
i have a mod in that incresses the day and night time lasts for dont no if that is the cause of this change the dayLength in the AstralSorcery config to the time and thay still dont show up any help would be appreciated

I add the cfg so you can see if that is the problem
[astralsorcery.txt](https://github.com/HellFirePvP/AstralSorcery/files/4195085/astralsorcery.txt)

**Comment by Doomgull** [comment]
Probably. Better place for this would be the mod's Discord though.

**Comment by Freedom16789** [comment]
where in the discord?

**Comment by Doomgull** [comment]
#starry-sky
