### ISSUE TITLE
I cant use the lens (Crash)

### ISSUE THREAD

**Issue by Eojii** [HellFirePvP/AstralSorcery#1237]
When I craft the lens and place it on the ground my game immediately crashes.

https://pastebin.com/7CpVXPgW

Thanks

**Comment by Doomgull** [comment]
It is crashing with nbt write to the block. What stats does the lens have? Does this happen without reskillable?

**Comment by Eojii** [comment]
I havent tried it without reskillable

**Comment by Doomgull** [comment]
Any other information? This should normally be impossible without another mod causing interaction issues.
