### ISSUE TITLE
[1.12.2]Console error

### ISSUE THREAD

**Issue by EnterFor** [HellFirePvP/AstralSorcery#1239]
1.12.2
Forge：2847
Mod：1.10.22

This is the wrong part of the intercept
https://paste.ubuntu.com/p/SMqdRVFvsT/

If you need a complete log, you can leave an email and I'll send it to you
I don't know how to use github to upload attachments
Sorry, my English is not good. I'm Chinese

**Comment by EnterFor** [comment]
The cause of the trigger is unknown, and many occur every once in a while

**Comment by Doomgull** [comment]
#513
