### ISSUE TITLE
Shaders

### ISSUE THREAD

**Issue by Grimmspecter** [HellFirePvP/AstralSorcery#124]
Could you make this compatible with shaders thats the only issue i have ever had with this mod other then that i love what it adds to my game,maybe make it so that with an eyepiece on it blocks out everything but the constellations but without it the sky would be default so that shaders dosnt flip out when i play

**Comment by HellFirePvP** [comment]
Try #13 to lessen the amount of things i do to the sky. other than that, i'm not going to fix much about shaders.

**Comment by Deadder** [comment]
_Thanks for the response @HellFirePvP !_

__I already found the weakSkyRenders option and it is set and the sky works as intended - which is awesome!__

_**However**_, that is not what I am referencing - particles are the issue.  If you set down, for instance the tree beacon the particles distort the entire area and parts just make the world transparent when looking through them with a shader pack installed.  Like i mentioned above the rest of the mod works in sharder packs with a little tweaking - except particles.  I can try to grab a screenshot tonight if that helps.
