### ISSUE TITLE
[1.12.2] Recipe changes in Astral Tome don't work!

### ISSUE THREAD

**Issue by MrLador** [HellFirePvP/AstralSorcery#1240]
Does not work:
mods.astralsorcery.Altar.removeAltarRecipe("astralsorcery:shaped/internal/altar/constellationpaper/aevitas");
and replacing with a modified recipe
The entire recipe:
mods.astralsorcery.Altar.removeAltarRecipe("astralsorcery:shaped/internal/altar/constellationpaper/aevitas");
mods.astralsorcery.Altar.addConstellationAltarRecipe("astralsorcery:shaped/internal/altar/constellationpaper/aevitas", <astralsorcery:itemconstellationpaper>.withTag({astralsorcery: {constellationName: "astralsorcery.constellation.aevitas"}}), 2000, 400, [
	terra, salisMundis, terra,
	aquamarineGem, parchment, aquamarineGem,
	terra, scribingTools, terra,
	illuminationPowder,illuminationPowder,illuminationPowder,illuminationPowder,
	<ore:dustAstralStarmetal>,<ore:dustAstralStarmetal>,<ore:dustAstralStarmetal>,<ore:dustAstralStarmetal>, null, null, null, null]);

**Comment by Doomgull** [comment]
What is the error in the logs on startup? What if you check the ct syntax via command?

Why did you open a bug ticket instead of coming to the discord for help on implementation?

**Comment by MrLador** [comment]
You mean the channel in Discord. I only found out about it today.
My problem is that the new constellation aevitas recipe is not accepted in Astral To me, the command is correct.
