### ISSUE TITLE
Russian Language Bug

### ISSUE THREAD

**Issue by ThePoputchik** [HellFirePvP/AstralSorcery#1241]
I opened the book and the language in the game broke. The same game began to lag
link to video - https://drive.google.com/open?id=1jRIvfxyUy1BsWqBjlHklKN_avnfeX0lg

**Comment by Doomgull** [comment]
If you change the language from russian to english, does it replicate?

Is there a client log that might have more information?

**Comment by Doomgull** [comment]
Any update to the above request?

**Comment by Leneri** [comment]
> Any update to the above request?

Have the same problem. Changing the language to english solves the problem.

**Comment by yagoplx** [comment]
Have you tried setting Force Unicode Font to true in language settings?
