### ISSUE TITLE
Astral Sorcery won't work when I try to run FTB Academy on MultiMC

### ISSUE THREAD

**Issue by Jellex111** [HellFirePvP/AstralSorcery#1242]
I try to play the FTB Academy modpack using MultiMC 5 (ver 0.6.8-1419 on win32). It works fine up until it has to load Astral Sorcery, where it stops and gives me this error report: https://paste.dimdev.org/liwogiziko.mccrash

Any help to fix this would be greatly appreciated.

**Comment by Doomgull** [comment]
Not AS issue. It calls out that you don't have enough memory allocated in the beginning of the trace. 1 gb allocated is about 30% of what any modded pack should have allocated in 1.12. Push it to 3 gb and try again.

**Comment by Jellex111** [comment]
That's the problem, all good now, thanks!
