### ISSUE TITLE
Can't have a Custom Skybox

### ISSUE THREAD

**Issue by Azuriuz** [HellFirePvP/AstralSorcery#1243]
Hello there, I'm making a modpack and it uses a resource pack with an absolutely fantastic skybox that really completes the ambience of the world.
However with Astral Sorcery added to the mix, the custom skybox does not render. I have tested this with only optifine and astral sorcery to make sure it was this mod (optifine being required to enable custom skybox from the resource pack). Removing astral sorcery from the modpack causes the skybox to render just fine. 
I also looked up others with this issue, who edited the weak sky render by adding 0; however this does nothing to enable the custom skybox in my modpack. I really want to have a good playthrough of astral sorcery, please please help me solve this confliction? I don't want to have to choose between a beautiful sky and beautiful sky magic!

**Comment by Doomgull** [comment]
the weakSkyRender option is the closest you'll get to compatibility.

**Comment by Azuriuz** [comment]
Please tell me then, am I putting a 0 in the wrong place or something?

    # IF a dimensionId is listed in 'skySupportedDimensions' you can add it here to keep its sky render, but AS will try to render only constellations on top of its existing sky render. [default: ]
    S:weakSkyRenders <
     >0

**Comment by Doomgull** [comment]
Should go between the angled brackets:

S: weakSkyRenders <
0
>

**Comment by Azuriuz** [comment]
It works! Thank you for checking back to help me figure it out, definately my mistake; still a little new to editing configs and such.

I have a final question if you don't mind? 

Is this config change server side or client side? 
I ask because I know custom skyboxes can mess with the later progression in astral sorcery, and I want to know if giving my players a temp config file to restore default will work when they log onto the server? I don't want to prevent players from being able to fully progress the mod either, but if it's a client side change they can just use a temp config to be able to explore anything otherwise difficult with weak sky render.

**Comment by Doomgull** [comment]
Client only. All rendering in mc only runs on client.
