### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by origamer29** [HellFirePvP/AstralSorcery#1244]
Hi!, I was creating a modpack to play it, but i  have a problem with this mod, please anyone can help  me. Here you have the crash report: https://paste.dimdev.org/tewavaqifi.mccrash

**Comment by Doomgull** [comment]
Not an AS issue, just triggered by AS. You have too many IDs from mods for MC to handle: pack is too big.

Either remove mods that add tons of items, or add the nod Not Enough IDs.
