### ISSUE TITLE
[MC 1.12.2] [AS 1.10.22] Evorsio ritual breaking its own ritual anchor

### ISSUE THREAD

**Issue by I-Need-A-Username** [HellFirePvP/AstralSorcery#1247]
I looked around and found that this was an issue that previously existed and was supposed to be fixed here https://github.com/HellFirePvP/AstralSorcery/issues/480 but I'm playing in version 1.10.22 and am experiencing the same issue where the Evorsio ritual will break its ritual anchor that it is bound to, but not the one above it, and then move to operating around the ritual pedestal itself.

**Comment by Doomgull** [comment]
Can you provide some screenshots of the setup you're seeing the issue occur within, for reproduction?

**Comment by I-Need-A-Username** [comment]
setup
![2020-03-06_14 02 16](https://user-images.githubusercontent.com/15763131/76122528-78482480-5fb3-11ea-8c06-43d8f950a62f.png)
in progress
![2020-03-06_14 02 42](https://user-images.githubusercontent.com/15763131/76122538-81d18c80-5fb3-11ea-9e8d-e3ef54caef05.png)
anchor broke
![2020-03-06_14 02 54](https://user-images.githubusercontent.com/15763131/76122560-8b5af480-5fb3-11ea-9fbc-9729cad592be.png)
ritual working at pedestal now
![2020-03-06_14 04 32](https://user-images.githubusercontent.com/15763131/76122582-9ca40100-5fb3-11ea-8352-ac0a6e3d258a.png)
I do have my crystal modified with Ulteria, but I tested with an unmodified crystal as well and had the same results

**Comment by HellFirePvP** [comment]
Unfortunately, with the way the rituals in AS 1.12 work, this would require a lot of work to fix. In an effort to push for newer versions faster, i won't have the time to properly fix this.

**Comment by HellFirePvP** [comment]
Nvm. i'll just make the ritual not break anchors at all....
