### ISSUE TITLE
[1.12.2] How to delete Rock Crystal entities?

### ISSUE THREAD

**Issue by Hexxonite** [HellFirePvP/AstralSorcery#1249]
Hello there,

I am hosting a 1.12.2 modpack server for some friends. However one of them went a little overboard with mining and left a lot of Rock Crystals laying around in the world.
As the server performance is not the best right now, I am trying to get rid of these.

Since they **don't despawn** automatically and seemingly dont get picked up by the
`/kill @e[type=item,r=512]`
command I was wondering how to do this correctly.

I hope there is another way, because even if I sent the person picking all of these items up, I don't think he would get all of them...

***Edit:**
Astral Sorcery Version: 1.10.22

Thanks in advance!

**Comment by Doomgull** [comment]
How many crystals are we talking about? They're just items, it is no different than eggs or feathers shedding from chickens in-world.

Additionally, the command won't catch anything in unloaded chunks. MCedit would be recommended, but I cannot possibly think of a scenario where enough rock crystals could be left laying around in a world from mining where it would cause an impact normally.

**Comment by Hexxonite** [comment]
Thanks for the quick reply.
I guess we are talking about a several hundred oveerall? The Pack is "Project Ozone 3" and apparently changes how the Rock Crystal Ore generates so it's a lot more common to find...
Additionally most of us have "Luck" entchantments so one Ore will drop a lot of Crystals.

Also thanks for the tip with MCEdit, but doesn't that cause issues when editing a modpack-world?

**Comment by Doomgull** [comment]
It shouldn't, but unsure. This is kind of well outside the scope of the mod with it being modified like that by the pack, to be quite honest. 

Can you profile the server with Sampler or Warmroast, or the like and make sure you're not trying to run down a red herring and the item load from the crystals sitting in the world actually IS the issue? There may be something else being "covered up" by assuming it's items.

**Comment by Hexxonite** [comment]
Oh, ok I will try to do some profiling and report back if that's still an issue asap.

**Comment by Hexxonite** [comment]
![image](https://user-images.githubusercontent.com/5312542/77197509-98183600-6ae5-11ea-9604-8cab0d8f70cc.png)

P.S. here you can see even items right in front of me not being picked up by the kill command, which is a bit weird \:

**Comment by Doomgull** [comment]
And it's pretty much exactly how the kill command is supposed to work for items that are set not to despawn. You might want to look into one of the mods that that clears loose items , maybe something there will work for you

**Comment by Awesomespore** [comment]
Can't you just chuck them into lava or at a cactus?

**Comment by HellFirePvP** [comment]
rock crystals aren't items. so type=item won't find them as they are, as said, not items.
you're probably looking for astralsorcery:entitycrystal
