### ISSUE TITLE
[1.12.2] Altars no close gui dupe

### ISSUE THREAD

**Issue by bigenergy** [HellFirePvP/AstralSorcery#1250]
1. Place any altar
2. Spill water or place rails with a trolley
3. Get in the trolley, quickly open the altar and put any object in it
4. As soon as you sail away or move away from the chunk with the altar - its interface is still open, just pick up the item from the interface
5. Close the interface
6. Return to the altar, open it and pick up the same item in double quantity

All altars of this mod are subject to this error.

**Comment by Doomgull** [comment]
Is this able to be reproduced with only Forge, astral sorcery, and baubles?

**Comment by bigenergy** [comment]
Yes, this is reproduced on a clean server only with astral
The problem is that if you open the container of the altar and if you somehow move away from it, it will not close

**Comment by BartolomeoDR** [comment]
reproduced
https://youtu.be/cTxjTLrKxcw?t=143

**Comment by bigenergy** [comment]
Maybe you should rewrite canInteractWith https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/container/ContainerAltarBase.java#L93
