### ISSUE TITLE
An internal error occured

### ISSUE THREAD

**Issue by xANoyU** [HellFirePvP/AstralSorcery#1251]
https://paste.ubuntu.com/p/956t6VFTMR/

**Comment by Doomgull** [comment]
Reproduce without plugins please. So many spigot plugin modifications in that stack.

**Comment by xANoyU** [comment]
> Reproduce without plugins please. So many spigot plugin modifications in that stack.

I added the protocolib plugin, is this a problem with this plugin?

**Comment by xANoyU** [comment]
> 星界巫术不支持普通伪造之外的任何环境。其中包括诸如spigot之类的东西，它们修改了底层代码，Sponge之类的东西。
> 如果呼叫无法按照他们在Forge中应有的方式运行，事情就会变得松散。尤其是因为protocollib修改了一大堆基本事物，并声称可以使事物运行得更快。事情不会因为您使用快捷方式而运行得更快，而是因为基础代码首先是高效的，所以它们运行得更快。我的世界在这方面有问题。
> 
> 因此，是的，protocollib的影响遍及整个堆栈跟踪，而这是网络堆栈上并发修改异常的错误，而protocollib对其进行了大量修改，这就是问题所在。如果在没有协议，海绵或其他任何东西的情况下无法复制该协议，那么在拉下protocollib之后，您可能会决定将其放进去，这实际上不是一个星体巫术问题，应该交给那些开发者。



> Astral sorcery does not support any environment outside of normal Forge. This includes things like spigot that modifies underlying code, Sponge, anything like that.
> When calls don't function the way they're supposed to in Forge, things can get squirrelly. Especially because protocollib modifies a whole bunch underlying things with the claimed intent of making things run faster. Things don't run faster because you take shortcuts, they run faster because the base code is efficient in the first place. Minecraft has issues in this regard.
> 
> So yes, effects of protocollib is all throughout that stack trace, and that it's an error for a concurrent modification exception on the network stack, which is something that protocollib heavily modifies, is the problem. If it can't be reproduced without spigot, or sponge, or anything else you may decide to put in there after pulling protocollib, it's really not an astral sorcery issue and should be taken to the dev of those instead.

Thank you for your reply. I see
