### ISSUE TITLE
Telescope not showing sky map but looking glass does. 

### ISSUE THREAD

**Issue by DelviousCrafts** [HellFirePvP/AstralSorcery#1252]
Using the telescope doesn't work at all. No stars in the night sky can be seen. However the looking glass has absolutely no problem whatsoever. This was working just fine in version 1.10.21 version. This is in a custom modpack and happening on server only. Working just fine in single player mode. 

Astral Sorcery version: 1.10.22
Minecraft: 1.12
Forge: 14.23.5.2847
Sponge forge not installed

![2020-03-24_20 22 24](https://user-images.githubusercontent.com/46658624/77499021-3c63ea80-6e0e-11ea-95cc-6159eeddc699.png)
![2020-03-24_20 22 39](https://user-images.githubusercontent.com/46658624/77499034-41289e80-6e0e-11ea-9452-0c3d096e78f8.png)

**Comment by Doomgull** [comment]
Is that the same world, telescope position, and surrounding block positions? Because looks like your telescope is adjacent to a wall there in that second screenshot, which means it won't work...as the Tome states.

**Comment by DelviousCrafts** [comment]
Well i feel a little silly now. There is actually a space there in the wall where the telescope lies which is why i chose that area. But apparently the wall detection goes out further than I thought. I made the mistake of testing in single player mode in a different location. Thank you for looking into it so quickly.
