### ISSUE TITLE
crashing when discovering constellation, because of sponge version

### ISSUE THREAD

**Issue by davizon200** [HellFirePvP/AstralSorcery#1254]
i cannot change the sponge version due to all the rest of the mods in the modpack being compatible.

Only thing im asking is a way to be able to use a command to discover constellations, or a different way to discover them!

thanks in advance,

Alfkors.

**Comment by Doomgull** [comment]
Sponge isn't supported at all.

Best option would be to use `/as help` and check the command syntax there.
