### ISSUE TITLE
[MC 1.12.2] Game crashing at opening

### ISSUE THREAD

**Issue by Mariadevis** [HellFirePvP/AstralSorcery#1255]
[crash-2020-03-28_20.54.50-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/4397822/crash-2020-03-28_20.54.50-client.txt)
maybe it's some mods conflicts or just too much mods.

**Comment by Doomgull** [comment]
Your custom npcs version is from the beginning of 2018.

It is also what is causing the crash, as shown in the stack. Update it, since it shouldn't have the crash issue in this instance.

#762

**Comment by Mariadevis** [comment]
thanks!
