### ISSUE TITLE
Possible Unintended Behaviour- Slimesling.

### ISSUE THREAD

**Issue by JustLiam040** [HellFirePvP/AstralSorcery#1257]
Modpack: Sevtech Ages, 1.12.2

Now this isn't really an issue per say but may be a bit of a bug, or it could be intended who knows. When attuning yourself to Vicio you gain your experience from movement, however if you equip a slimesling and fling yourself horizontally  (doesn't work vertically), you will gain experience at quite a quick rate, at higher levels i can't really see this being an issue but at a lower level it allows you to basically bang out loads of perks without any real effort. Now for all i know this could be intended behaviour, but i thought id open this thread on the off chance it wasnt!

**Comment by Doomgull** [comment]
There is already a gain rate cap in place.
