### ISSUE TITLE
Sextant not working after crash

### ISSUE THREAD

**Issue by SirGeremiah** [HellFirePvP/AstralSorcery#1259]
I had a crash recently that caused no real harm (except within Refined Storage, but that's another thing, entirely), except that I cannot now use my sextant. I have it in my hand, and right-click, and it just jiggles my hand. I'm able to use the looking glass and telescope fine.

Achievements (but not quests) were reset, so I'm wondering if that is somehow related. And I'm also wondering if this is even a problem. Given the looking glass and telescope seem to work fine, can I still get all constellations (I'd only gotten one with the sextant before this happened), or are some sextant-only?

I'm playing in FTB Academy, so the full list of mods in that pack (and nothing added). If you need, I can pull the full list and post here, but I expect you know that list better than me.

**Comment by Doomgull** [comment]
Sextant has nothing to do with constellations.

Sounds like the crash corrupted your progress file. Would recommend recovering your astral tome progress to where you can craft the sextant again and checking then.

Also: mod devs have no clue what is in a modpack outside of going and pulling the mod list thrmselves, same as the ticket filer would.

**Comment by SirGeremiah** [comment]
I'll try crafting the sextant again, but if all constellations can be sighted with the telescope, I'm not sure it matters if it's not working, unless I'm going to run into another need for it later.

**Comment by Doomgull** [comment]
Sextant has nothing to do with locating Stars.

**Comment by SirGeremiah** [comment]
So, just as an update, it looks like you were right about needing to re-do everything up to that point. Once I got there and built a new sextant, the old one also worked.

I'm actually re-doing all the quests/achievements up to where I was now, in hopes everything works thereafter.

_(Side note to Doomgull: Since sextant can be used to locate and mark early constellations, as well as for finding stars that mark shrine locations, it's not quite accurate that it has nothing to do with locating stars. Just noting that lest it confuse someone who reads this later.)_
