### ISSUE TITLE
[Inquiry] Is World Gen Required?

### ISSUE THREAD

**Issue by KaneHart** [HellFirePvP/AstralSorcery#126]
Is World Gen Required mainly structures and if so what ones are a must to make the mod work?

Thanks.

**Comment by HellFirePvP** [comment]
By default, worldgen is required for progression, yes.
However, you can work around that by removing/adding recipes through minetweaker/crafttweaker to work around the things that normally require worldgen.

**Comment by HellFirePvP** [comment]
To close this off: Anyone who comes across this post and has the same question:

As for 1.3.2 and prior: Worldgen *is* required to progress. You can work around it by adding recipes depending on the current structure/progression of your pack.
The things dependent on worldgen are:
 - Resonating Wand (ideally 1x craft)
 - Luminous Crafting Table (ideally 1x craft)
 - Starmetal Ore (you'll require multiple; only for the 1st few ores. After that, the mod has options to work around the worldgen requirement by itself for this)
 - Constellation Paper (you'll require multiple; found in loot chests, mainly in the structures' loot chests)

However, i suggest everyone that wants to work around worldgen that you play through the mod at least once to understand which feature/mechanic does what.

(And with that i'll mark this as resolved and close it)
