### ISSUE TITLE
Crystall Growth[Suggestion]

### ISSUE THREAD

**Issue by xomyakes** [HellFirePvP/AstralSorcery#1260]
Hi! I play with your mod a lot, and it's amazing! I realy enjoy it! But here's a one big problem. The mechanics of the crystal growth. When I try to make 900 100 100 crystal(it's no too fast) the crystals often despawns because server remove all dropped items. And it's so terrible. I've already lost 16 crysall(with 100 purity) in 2 last days. I spend more than 4 hours for it and they just disappeared. So can you make a device, just like well but which would be able to hold crystals and grow them without having to throw it on the ground?

**Comment by Doomgull** [comment]
Talk to the server admin about whitelisting the crystals in whatever they are using to clear items from the ground. The crystals do not naturally despawn with age normally.

Alternatively, set up a timer to pick up any loose crystals before the clearing happens, then place them back down after the clear occurs.

Adding a machine or device to prevent this further isn't something that will be added. This should be solved by player ingenuity and automated systems instead, or the server admin modifying whatever plugin is in-use to not work against a core mod mechanic.
