### ISSUE TITLE
[MC 1.12.2] Efficiency 5 not working on tools + AS Pickaxe not breaking non-Vanilla blocks at normal speed

### ISSUE THREAD

**Issue by Hidaro** [HellFirePvP/AstralSorcery#1261]
Hello, this issue is happening on the 1.10.22 and  1.10.23 of AS.
I have two tools, almost full size, 100% purity and 100% cutting with enchants on them (put with an anvil) that have major issues in breaking blocks.
The pickaxe is working fine with Vanilla blocks and AS blocks, but when I try to break Chisel's blocks or Biomes O plenty stone, it goes from diamond level to stone/wood speed-wise, and the Shovel is not breaking any blocks faster than by hand, with or without the enchant.
![Screenshot_76](https://user-images.githubusercontent.com/29508049/79075303-4c2a6c80-7cf2-11ea-917b-f4e104bac15a.png)
![Screenshot_77](https://user-images.githubusercontent.com/29508049/79075311-58aec500-7cf2-11ea-8b0f-9f5cb93210e2.png)

**Comment by Doomgull** [comment]
Likely related to code changes for #1185 . Will look deeper.

**Comment by alpharou** [comment]
Can replicate

![VIh0kbkmWZ](https://user-images.githubusercontent.com/8113318/79690165-4cc68400-8259-11ea-9f1f-daa839c50d01.gif)

AstralSorcery-1.12.2-1.10.23
forge-14.23.5.2847
