### ISSUE TITLE
[1.12.2] java.lang.NullPointerException: Ticking entity

### ISSUE THREAD

**Issue by MusicMaestro123** [HellFirePvP/AstralSorcery#1266]
Well it would appear I had a crash! Here's the crash report: [click me!](https://pastebin.com/hDWrkzr0)

The crash was server-side.

Mod version: 1.12.2-1.10.23

**Comment by MusicMaestro123** [comment]
#106

**Comment by MusicMaestro123** [comment]
Just thought that I may as well mention that as it is still NOT fixed!

**Comment by Doomgull** [comment]
Despite the similarity in crash header line, it is not the same as that other ticket. I have removed the reference to that ticket.

Just thought I would mention that.

**Comment by MusicMaestro123** [comment]
Oh it's just I couldn't access the log file of that person's crash so I was unsure. Didn't mean to sound rude.
