### ISSUE TITLE
[Enhancement] Celestial and starmetal tools

### ISSUE THREAD

**Issue by alpharou** [HellFirePvP/AstralSorcery#1269]
I know theres already am issue about Starmetal tools, but was 3 years ago.

Starmetal (which is said to have similar properties to iron) should be able to form starmetal tools that could look like iron when not under starlight, and shine accordingly when exposed. 

Celestial crystals should also be able to create shiny sprinkly deep blue tools that resemble starmetal, currently the tools made with both crystals look the same, which seems odd to me.

**Comment by HellFirePvP** [comment]
As with 3 years ago, still, starmetal tools won't be a thing.

Yes, i am aware of the white/blue disparity on crystal tools; however, what's with 1celestial+2rock crystals? does that need a 1/3 blue and 2/3 white sprite? (...)

While, yes, pushing down the rabbithole here is besides the point. i'll keep an eye on this and maybe add it at some point, however i don't see the point atm and would rather focus on other/more important things mechanically and actually-being-able-to-play-it-on-1.14+-at-all.
