### ISSUE TITLE
Crash on selecting constellation.

### ISSUE THREAD

**Issue by Syncyy** [HellFirePvP/AstralSorcery#127]
Hi
I've crashed twice now after clicking a discovered constellation inside the book. Looking at the papers themselves does not crash me.
New to github and posting issues but here is what I got from Multimc.

> Time: 4/21/17 11:01 AM

> Description: Updating screen events
> 
> java.lang.NullPointerException: Updating screen events
> 	at hellfirepvp.astralsorcery.client.gui.GuiJournalConstellationDetails.buildLines(GuiJournalConstellationDetails.java:79)
> 	at hellfirepvp.astralsorcery.client.gui.GuiJournalConstellationDetails.<init>(GuiJournalConstellationDetails.java:69)
> 	at hellfirepvp.astralsorcery.client.gui.GuiJournalConstellationCluster.func_73864_a(GuiJournalConstellationCluster.java:274)
> 	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
> 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)
> 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
> 	at net.minecraft.client.main.Main.main(SourceFile:124)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
> 	at org.multimc.EntryPoint.main(EntryPoint.java:54)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Client thread
> Stacktrace:
> 	at hellfirepvp.astralsorcery.client.gui.GuiJournalConstellationDetails.buildLines(GuiJournalConstellationDetails.java:79)
> 	at hellfirepvp.astralsorcery.client.gui.GuiJournalConstellationDetails.<init>(GuiJournalConstellationDetails.java:69)
> 	at hellfirepvp.astralsorcery.client.gui.GuiJournalConstellationCluster.func_73864_a(GuiJournalConstellationCluster.java:274)
> 	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
> 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)

**Comment by HellFirePvP** [comment]
Known, fixed in dev, will be then in the next version.
