### ISSUE TITLE
[1.14.4-indev] Some models are not loaded.

### ISSUE THREAD

**Issue by yagoplx** [HellFirePvP/AstralSorcery#1272]
Relevant section of log: https://pastebin.com/gMeBJeyC
This does not seem to affect all collector crystals.
[
![2020-04-21_00 52 54](https://user-images.githubusercontent.com/57966308/79823808-f9dcf180-836a-11ea-8472-bbd126063c32.png)
](url)

**Comment by Doomgull** [comment]
Tickets shouldn't be filed for unreleased versions. Some things don't work in the git code that work in the closed dev, or aren't converted yet.

**Comment by yagoplx** [comment]
Yikes. I still feel that any feedback I am able to give has a net benefit to AS's development, so I will keep this issue around for any bugs I find on the git code, instead of putting them on individual issues (to prevent spam!)

You can keep this closed if you want, just do remember to keep an eye on it 👀

**Comment by yagoplx** [comment]
If anyone else is interested on helping with the development of the future release of AS 1.14.4, I've fabricated a little script that spits out usable mod jars to put in the game, and makes clean changes to the original repository to facilitate making pull requests:

https://github.com/yagoplx/HellfireBuilder

**HellfireBuilder** does not contain any proprietary code and is compliant with the Astral Sorcery License.

**Comment by yagoplx** [comment]
Removed the first "bug report" because it is not a bug- just user error due to lack of knowing.
Found out that generating the mod's datapack and resourcepack is done by `./gradlew runData`.

Yet, running `./gradlew build` afterwards does not package the generated vanilla resources into the jar. How is this done in a development setup? Can't really figure it out by myself... @HellFirePvP 
Neither does `./gradlew runClient` have any of these resources loaded.

I've worked around this by having HellfireBuilder make a datapack that I put in the worlds datapack folder, and making a resource pack that goes in the instance resourcepack folder. This makes AS 1.14.4 work as intended- with all features showcased in the devlog videos.

This was quite fun, but I guess I got what I wanted in the first place.  
Now we get developing!

![2020-04-21_19 57 29](https://user-images.githubusercontent.com/57966308/79923623-4b898880-840c-11ea-87f8-aede917d6ba5.png)

I'm mostly going to use this to make memes and the likes, as my knowledge of Java is abysmal and I've realized that I cannot be of much help, further than this.

**Comment by yagoplx** [comment]
**Suggestion: Review the Illumination Wand's code.**

Some tile entities can be illuminated and this leads to weird behaviour.  
Some things should not be affected by the wand.

[Click me to see this issue in action](https://thumbs.gfycat.com/CommonIdenticalIrishredandwhitesetter-mobile.mp4)

**Comment by yagoplx** [comment]
**Suggestion: Review the Ritual Pedestal.**

Upon having starlight shot into it, the functioning Ritual Pedestal will instantly render all the "leaking" starlight beams. They are purely visual and don't do anything.
Amongst other oddities.  

This might not be of interest to HellFirePvP, as he has previously expressed interest in remaking the Rituals in a different way. I don't know if this is still the case.
![2020-04-21_23 54 30](https://user-images.githubusercontent.com/57966308/79935972-9adfb100-842c-11ea-8486-566189a4286c.png)

**Comment by yagoplx** [comment]
**Suggestion: Review the Attunement Altar's code.**

The Attunement Altar, once built, and tuned to a constellation, will not remember that it is tuned to that constellation if you leave the world at day, return, and set the time to midnight. (happens too if the transition from day->night is natural)  

This is anomalous because the constellation is still on the sky.
![2020-04-22_02 28 43](https://user-images.githubusercontent.com/57966308/79944243-6d513280-8441-11ea-8dc7-41bfe029c2ba.png)

**Comment by yagoplx** [comment]
**Bug: Changing resource packs permanently screws up the skybox**

Yes, this is on the unmodified debug source, [assets are being packaged into the jar as HF told me to do.](https://github.com/yagoplx/HellfireBuilder/blob/4314845b0c0dec0b2257c1760563a5d949fa4792/make.sh#L109)

[Click here to see this bug in action](https://www.youtube.com/watch?v=hRQ0heBiXcE&feature=youtu.be)
