### ISSUE TITLE
craaaaaaaash while attempting to load world

### ISSUE THREAD

**Issue by Hound0** [HellFirePvP/AstralSorcery#1274]
[crash-2020-04-21_01.29.36-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/4507885/crash-2020-04-21_01.29.36-client.txt)

**Comment by yagoplx** [comment]
What does this have to do with Astral Sorcery? The crash never blames it at all, and is inconclusive.

Regardless, I can't help but notice that both your Java and Forge are quite outdated.

**Comment by Hound0** [comment]
I am only using the necessary mods for astral to function as I can't get it
to work in my main file. All others work and I just updated java last I
checked. Is the forge version listed not the correct one?

**Comment by Doomgull** [comment]
That is a minecraft error, not an astral one. I would recommend updating your forge version as it's about 20 releases behind (current 1.12.2 release is 14.23.5.2847).

Not something we can help with, either way.
