### ISSUE TITLE
Bizzare behavior with consistent luck perk and resplendent prism

### ISSUE THREAD

**Issue by ComplainingSkelzie** [HellFirePvP/AstralSorcery#1276]
I used horologium in the stellar refraction table to give fortune VI to an infused crystal pickaxe and a diamond pickaxe. this is my perk tree: ![perk tree](https://i.imgur.com/DjK82G0.png)

I wore a resplendent prism with +2 to all existing enchantments and mined 64 diamond ore with each pickaxe, both with and without consistent luck sealed. I also tested with the perk unsealed using an unenchanted pickaxe of each type. These were my results, with the seal next to the pickaxe indicating the perk being sealed: ![test results](https://i.imgur.com/wGM84by.png)

Furthermore, when mousing over tools when held with the perk sealed, the enchanted tools displayed fortune IX and the unenchanted tools displayed no enchantments. With the perk unsealed, the enchanted tools displayed fortune V (lower than their base value of VI?), the unenchanted infused crystal pickaxe displayed fortune II, and the unenchanted diamond pickaxe displayed "Fortune enchantment.level.-2147483646"

My mods are astral sorcery, baubles, comforts, ctm, jei, and just enough throwing in fluids.

**Comment by HellFirePvP** [comment]
Related: #1290

**Comment by HellFirePvP** [comment]
This weirdness probably occurred due to a number overflow on the fortune? I can't reliably reproduce this...
