### ISSUE TITLE
[1.14.4-indev] [Suggestion] Add startup effect to the Attunement Altar

### ISSUE THREAD

**Issue by yagoplx** [HellFirePvP/AstralSorcery#1277]
Currently, even with the new particle effects on the relays, I think it is still a bit jarring how the Attunement Altar goes from 0 to 100 in a few seconds. Perhaps have it flicker for a while before displaying its fully powered once there is enough starlight on the sky?

**Comment by Doomgull** [comment]
Consolidating into #495.
