### ISSUE TITLE
[1.14.4-indev] [Suggestion] Add bucket sounds for liquid starlight

### ISSUE THREAD

**Issue by yagoplx** [HellFirePvP/AstralSorcery#1278]
This one is for TechnoMysterio :)

Was wondering what liquid starlight would sound being poured + scooped up by a metal bucket, this is a very minor detail, but you could consider putting it into the mod.

[Looks like forge allows changing your bucket sounds](https://github.com/MinecraftForge/MinecraftForge/blob/27bd0de5ebc3540e3693ebf0cbf887d38da1701f/src/main/java/net/minecraftforge/fluids/FluidAttributes.java#L73), but I haven't seen anyone do it yet.

**Comment by Doomgull** [comment]
Consolidating into #495 due to age.
