### ISSUE TITLE
[Question] How do Spectral Relays work?

### ISSUE THREAD

**Issue by Syncyy** [HellFirePvP/AstralSorcery#128]
I've got one setup a few blocks away from my starlight altar but still on the same y level and both in the same starlight area . The Relay multiblock sparkles are showing but nothing else is happening. Does this just mean you can't double dip in the same starlight or have I done something wrong?

**Comment by HellFirePvP** [comment]
relays don't work on dedicated servers atm.. this is known and fixed for the current version. (my derp, sorry..)

If it 'shows sparkles' you built it correctly and put the glass lens in as 'intended' - but well... :| it's broken atm, the next version will come soon-ish and that'll fix that.
