### ISSUE TITLE
Crash when chopping trees with Infused Crystal Axe (possible incompatibility with Dungeon Tactics)

### ISSUE THREAD

**Issue by aleferna12** [HellFirePvP/AstralSorcery#1284]
Hi!

I've seen crashes whenever using the Infused Crystal Axe to chop down trees. I believe the crash is related to the mod Dungeon Tactics, as removing it from the modpack no longer causes any issues. I'm therefore not sure whose problem this is but thought contacting both would be a good idea.

Versions:
MC - 1.12.2
Forge - 14.23.5.2854
AS - 1.10.23
DT - 0.16.6
Crash Log:
(https://github.com/HellFirePvP/AstralSorcery/files/4603463/crash-2020-05-09_13.29.39-server.txt)

**Comment by Doomgull** [comment]
What tree are you chopping down? The NPE comes from dungeontactics.

**Comment by aleferna12** [comment]
I believe this particular crash comes from chopping a Acacia Tree (vanilla) but others resulted in the same behaviour

________________________________
De: Doomgull <notifications@github.com>
Enviado: sábado, 9 de maio de 2020 15:31
Para: HellFirePvP/AstralSorcery
Cc: aleferna12; Author
Assunto: Re: [HellFirePvP/AstralSorcery] Crash when chopping trees with Infused Crystal Axe (possible incompatibility with Dungeon Tactics) (#1284)


What tree are you chopping down? The NPE comes from dungeontactics.

**Comment by HellFirePvP** [comment]
Not an AS issue.
The only thing that _can_ be null here is his own internal random-generator. which he doesn't initialize i suppose. This has nothing to do with AS.
![image](https://user-images.githubusercontent.com/7419378/81479487-d39cca00-9223-11ea-8905-a79488bbf689.png)
