### ISSUE TITLE
Bastion of Flesh doesn't work properly. Also Vis Inoculation issue

### ISSUE THREAD

**Issue by A-Myr** [HellFirePvP/AstralSorcery#1285]
When using the perk, all the armor perk increases are converted, but for some reason not my base armor, which stays as it should be. It seems like that should also be converted because of the "no armor" line.

Another issue is with Vis Inoculation. When I use the perk, I lose all my armor instead of having a 75% reduction.

**Comment by Doomgull** [comment]
What pack/mod list? Sounds like something is interfering.

**Comment by A-Myr** [comment]
It seems like both issues were resolved when I re-entered the game. One thing I'm not sure about however is if Bastion of Flesh should or should not convert my normal armor to hp. Right now it removes all my armor, but only converts my armor perk bonuses to hit points.

**Comment by Doomgull** [comment]
If the base armor you are wearing isn't converted, something else is interfering there.
