### ISSUE TITLE
Celestial Gateway Visibility Not Always Predictable

### ISSUE THREAD

**Issue by EArkham** [HellFirePvP/AstralSorcery#1286]
We're running Minecraft 1.12 with the Eternal-1.3.5.3 modpack on our server and have the following setup for six gateways (lines originating from gateway A).  Images taken from our dynmap.  Saw a previous issue #734 which has been closed and looked resolved, and is the basis for the visibility we're expecting from each gateway.

![astral_gate_issue](https://user-images.githubusercontent.com/3612166/81505883-a4886600-92c0-11ea-8cf0-13b46f6b2f04.jpg)

Gateway A is at a fairly high elevation (around Y 190-200), Gateways B & C are around Y 70ish, Gateway D is at a very high elevation (Y 230+), Gateway E is around Y 70ish, Gateway F is around Y 110ish.  Gateway F is the most recently added to the network.

From gateway A, we can see gateways B, C, D, and E, but NOT gateway F, which is unexpected.

From gateway D, we can see gateways A, E, and F, but NOT gateways B or C (mostly expected, though C looks like it is large enough of an angle to be visible from D as well)

From gateway F, we can only see gateways A and D, but NOT gateway B, C or E (very unexpected).

![astral_gate_issue_F](https://user-images.githubusercontent.com/3612166/81506090-05646e00-92c2-11ea-9c16-229b42a06f23.jpg)

From gateway E, we can see D, F, and A, but not B & C (somewhat expected).

All gateways are open to the sky and have no obstructions within the black dome.

I'm aware that the gateways hide overlaps, but this behaviour from Gateway F is very unexpected.

Is there an option in the config to turn down the sensitivity of the overlap or disable it entirely?  Our group really doesn't mind having a cluttered interface if it means we go directly to our destination.

Thanks.

**Comment by HellFirePvP** [comment]
Yes, it removes additional points that are too close to others. while it should show actually show E, the nodes/stars for A B and C are so close together, it choses one of those to display and does not display ones that are very very close to that one (by angle). That way you still have one choice rather than a bigger blob of stars, where selecting one specific one isn't reliably possible.

It is similar to what was described in the issue linked and as you've also mentioned ("From gateway E, we can see D, F, and A, but not B & C (somewhat expected).")

There is currently no option to remove this as, again, it would make selecting one specific one out of those a bit of an issue. I'll keep this in mind though.

**Comment by EArkham** [comment]
Thanks for the reply, if I can further the suggestion:

Could we get "ghost" stars when a location eclipses other gateways due to angles, that can be seen but not traveled to?  This would help indicate locations that lead to a more extensive local gateway network.  

These could be in a dark blue/red, not necessarily with the name, though an option to see the names as well would be appreciated, and could not be selected as travel targets... they would just show as reference or to help figure out better placements for the gateways.

Taking the pic as an example, that would mean if I were at gateway D looking at gateway A, I would also see ghostly/darkly coloured stars behind it, letting me know there were more locations accessible from A, but looking at F or E I would not see any ghost stars since those don't block any others from gateway D.

Also does the length of the gateway name play a factor in which takes precedence?

**Comment by Doomgull** [comment]
Consolidating into #495.
