### ISSUE TITLE
[Mod Incompatibility] [1.12.2] All tamed rats from Rats mod disappear after being attuned

### ISSUE THREAD

**Issue by QuietAsAMouse** [HellFirePvP/AstralSorcery#1288]
Minecraft Version: 1.12.2
Astral Sorcery Version:  1.10.23
Rats Mod Version: 3.2.11

Just as title says. Was playing in a survival world, teleported using Celestial Gateway with Astral Sorcery mod while attuned to the star Vicio. All of my tamed rats disappeared, including two sitting in my house and one on my head. Tested a little in creative, and it only seemed to happen when I am attuned. VanillaFix suggested that Rats was causing a problem, however, I thought I would add it here as well.

**Comment by HellFirePvP** [comment]
I'm teleporting the player, much like an enderpearl does if it's in the same dimension. I'm teleporting the player the same way the nether portal does if you're not teleporting from/to the same dimension.

I'm very doubtful this is on AS' end.

**Comment by QuietAsAMouse** [comment]
Yeah, I thought I would just bring it up here just in case.  I added another thread to the Rats mod page when the bug occurred, so they can also take a look into it.  Thanks for the explanation.
