### ISSUE TITLE
Odd server NPE during sync packets

### ISSUE THREAD

**Issue by Saereth** [HellFirePvP/AstralSorcery#129]
Multiplayer, astralsorcery-1.3.2-beta
Player got disconnected trying to sync AS packets and everyone else gets disconnected trying to join now. Server restart cleared up the issue.

Here is the Logfile error that was thrown (not a crash, just from the fml-server-latest.log)
https://hastebin.com/yolovilobe.vbs

**Comment by HellFirePvP** [comment]
<Thonk>
Seems like the socket or channel didn't initialize properly? At least that's what that suggests..
