### ISSUE TITLE
[1.12.2] Consistent Luck bugs when Amulent Enchantments increase is higher than +50%

### ISSUE THREAD

**Issue by twewy02** [HellFirePvP/AstralSorcery#1290]
Forge Version: 14.23.5.2847
Mod Version: 1.10.23
This was tested with a clean installation of Forge, AS and Baubles with no other mods to make sure it wasn't caused by incompatibilities or by changed configurations from a modpack.

At first I suspected it was caused by a high increase in Perk Effectiveness, but it was working as expected even when it was higher than +100% so I then tried with the only perks that affect enchantments

when Amulet Enchantments is lower than +50% Consistent Luck still works as expected, giving the unenchanted pickaxe Fortune I
![Normal Fortune](https://user-images.githubusercontent.com/65254238/81751735-a3e50080-9475-11ea-83fc-ff4367bce811.png)

but after increasing it past +50% the fortune level bugs out
![Bugged Fortune](https://user-images.githubusercontent.com/65254238/81751845-dd1d7080-9475-11ea-82d3-3a95794efe91.png)

and it also appears to be lowering the level of existing fortune enchants when wielding the pickaxe
![Lowering Level](https://user-images.githubusercontent.com/65254238/81751951-1655e080-9476-11ea-8dab-a5cd11df1109.png)

This bug persists after reconnecting or restarting the game, and even after resetting your perks and taking Consistent Luck again without the increased amulet effectiveness perks.

**Comment by HellFirePvP** [comment]
derp
