### ISSUE TITLE
Armor perks bug

### ISSUE THREAD

**Issue by Critteros** [HellFirePvP/AstralSorcery#1291]
![2020-05-14_14 29 41](https://user-images.githubusercontent.com/41534816/81936408-86897100-95f2-11ea-822f-4bd78b22645c.png)
Base armor amount is read incorrectly ,thus armor perks do not grant any extra armor rendering them useless. Running DD&SS v7.3a modpack with AS v.1.10.23

**Comment by Doomgull** [comment]
Base armor for any player is 0. Add some Added flat armor perks to gain base armor. Worn armor is not base.

**Comment by daddy77gaming** [comment]
Bulwark and the 3 nodes before give armor, TBH I have not seen many players use armara. As it seems like an attunement that only benefits when levelled up quite a bit, and other attunement offer effective perks early into your attunement ( also handing out armor % buffs that are useless at least until you have bulwark which is minimal 9 points ) Just feel it to be at least fair to Armara to let people that choose this to start out with a flat armor increase so they dont feel they have a useless attunement early on
