### ISSUE TITLE
Attunement Altar not forming

### ISSUE THREAD

**Issue by Hgwells1** [HellFirePvP/AstralSorcery#1292]
Hi, I'm running a SpongeForge server 1.12 running modpack PO3 kappa mode and I can not get the attunement altar to form properly.

I've checked the structurematcher.dat and I can see that the structure is recognised and the tag isMatching is 1 which I can only assume is True for structure astralsorcery:pattern_attunement_frame.

I can not see any issues when checking the logs in this regard so I'm kinda stuck as to what the issue could be, I have a feeling that sponge may be interferring but my questions are a)can I fix this or b)Can I force a player attunement or additionally force the structure into being.

**Comment by Doomgull** [comment]
Sponge has interfered in the past, but if you're running an updated version of sponge that should no longer be an issue.

Right click the altar block with a sextant to reveal if any blocks in the multiblock are placed incorrectly (or missing). If that reveals no issues, shift-right-clicking in creative mode will forcibly build the structure for whatever block you've clicked. There is also a command for this, which can be referenced using `/as help` in-game when sufficient permissions are granted.

**Comment by Hgwells1** [comment]
Thanks, the sextant thing worked in theory but the structure was correct to begin with. I can't really update the sponge forge as it's the highest version for the modpack it can run on. The /as commands helped me to force the progress though and I can at least create a trade system for spawning in attuned items. Many thanks for the help.
