### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by TheUntamed** [HellFirePvP/AstralSorcery#1293]
Hello,

i'm creating a mod that adds different variants of ores to the game (e.g. netherrack ore)
and I would like to do this for the ores of this mod too. Am I allowed to use the textures of your blocks as a base to create those? After reading the license I wasn't sure and wanted to ask first.

**Comment by HellFirePvP** [comment]
Yes, you may you use the ore textures for creating corresponding nether-ores; only those textures and only for that purpose.
Thank you for asking first.

**Comment by TheUntamed** [comment]
Thank you :)
