### ISSUE TITLE
Alpha crash with Xeno's Reliquary

### ISSUE THREAD

**Issue by Dayyer1** [HellFirePvP/AstralSorcery#1296]
The game crashes on load when Xeno's Reliquary is installed.

[crash-2020-06-01_18.23.44-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/4714042/crash-2020-06-01_18.23.44-client.txt)

The crash is caused by another mod, but I still thought you should know.

...#masterbugfinder2020

**Comment by HellFirePvP** [comment]
I'll just try-catch around it... >_>
