### ISSUE TITLE
Suggestion for a new repairing-all-things (almost) device

### ISSUE THREAD

**Issue by kakas123455** [HellFirePvP/AstralSorcery#1297]
"Liquid starlight is well known for its mending and repairing purposes regarding crystal tools and rocks.Experimentation has showed that by mixing liquid starlight with regenerative-themed materials such as ghast tears and mossy rock,gives it all-purposed mending powers and can repair almost anything,provided its put in a place of focus and the items are bathed in it. For that,a new piece of apparatus is required."
The items needed to be thrown into liquid starlight to create mending starlight can be different,I just couldn't think of anything else.The device can look like a 1 wide 2 blocks tall "piano" without the musical keyboard with 2 slots in its place,in a dent.It can be covered from above.It will be made from infused wood mostly and for the recipe,it will be quite expensive,needing radiance chapter expensive materials and 2 celestial crystals,that also act as the slot base,as a small purple cube. The device will have 2 buckets reservoir and each mb will repair 4 durability. I know this is not going to get implimented straight up,and thats what I am hoping. Your imagination is far better,as I have seen it inside the mod. I hope that at least I gave you some ideas.
PS: Now that I think about it,how about infusing a liquid starlight bucket under an aevitas engraved glass in a stellar refraction table? It would need some JEI compatibility though,so I understand its quite hard to implement.

**Comment by Doomgull** [comment]
Consolidating into #495.
