### ISSUE TITLE
Spacial Manipulation Perk causes the Enchant Scorching Heat to not work 

### ISSUE THREAD

**Issue by PokeMaserJ** [HellFirePvP/AstralSorcery#1298]
Tested with 1.10.22, but should also apply to 1.10.24 since I just found out about the cause after 1.10.24 was released.

**Comment by Doomgull** [comment]
@PokeMaserJ may be related to #1290, can you verify in 1.10.24?

**Comment by PokeMaserJ** [comment]
It's still a thing in 1,10.24 just tested it.
