### ISSUE TITLE
Compatibility Request - Tree Beacon currently not working with TerraFirmaCraft trees

### ISSUE THREAD

**Issue by SeriousCreeper** [HellFirePvP/AstralSorcery#1299]
Heya,

currently the trees from TerraFirmaCraft aren't being affected by the tree beacon. TFC changes so much of how things work, i'm not surprised. 

Was wondering though if it'd be possible to get support for them? 
Here is a quick video of showing it in (or not) action: https://streamable.com/cfhear 

First sapling is a TFC sapling, 2nd one is a vanilla oak (just wanted to confirm it works with the vanilla ones still). 

Cheers,
SC

**Comment by Doomgull** [comment]
Unsure on this one, because of how the tree operate. This would likely require special casing, and unsure if that's something that would be added to 1.12 releases due to them being under maintenance for bugs only while 1.14/1.15/1.16 are under dev.

**Comment by SeriousCreeper** [comment]
That's unfortunate but understandable! Appreciate taking a look at the issue! If special casing would be acceptable way of solving this, would you guys accept pull requests for 1.12 still?

**Comment by HellFirePvP** [comment]
TerraFirmaCraft trees would need to fire the SaplingGrowTreeEvent like vanilla trees, the sapling should be either IGrowable or receive random block ticks (which i'd assume it is) and the terrafirmacraft log-blocks need to return true for the `isLog` method call.

This is rather something to be fixed on TFC's end.
