### ISSUE TITLE
[1.12.2] ConcurrentModificationException

### ISSUE THREAD

**Issue by Luohuayu** [HellFirePvP/AstralSorcery#1301]
https://paste.ubuntu.com/p/ZhRhx8VX5B/

**Comment by Doomgull** [comment]
Need replication without protocollib and/or bukkit involved. It's all up in that stack trace before and after AS's involvement, and the network code in 1.12 is already weird enough as it is without other things involved.

**Comment by Luohuayu** [comment]
> 
> 
> Need replication without protocollib and/or bukkit involved. It's all up in that stack trace before and after AS's involvement, and the network code in 1.12 is already weird enough as it is without other things involved.

This is not a problem caused by Bukkit and ProtocolLib.
1.12.2 writePacketData method is executed asynchronously. But the list container in PlayerAttributeMap is not thread-safe.
I add lock in PlayerAttributeMap, it works fine.
