### ISSUE TITLE
[1.12.2] Severe Resplendent Prism, Dungeon Tactics bug

### ISSUE THREAD

**Issue by myj99** [HellFirePvP/AstralSorcery#1302]
As best I can tell, when the Resplendent Prism gets +1 to one of a few specific DungeonTactics enchantments (Cinder, Fade work), and +1 to all enchantments, hitting a mob with a tool will increase the enchantment level of every enchantment on that tool infinitely. 

A resplendent prism with +2 Cinder, +1 all existing enchants started causing the bug, as I first noticed. 

Equipment with existing levels of Cinder (from being used while the above resplendent prism was equipped) would continue to rise in level if used with a +1 all existing enchant +1 existing sharpness prism equipped.

This was tested in the MC Eternal 1.3.6 Modpack.

**Comment by Doomgull** [comment]
Can you test if this is still occurring with AS 1.10.25?

**Comment by HellFirePvP** [comment]
Dungeontactics' enchantments are blocked from the amulet for now.
