### ISSUE TITLE
Bug with the perk system.

### ISSUE THREAD

**Issue by Drifty6** [HellFirePvP/AstralSorcery#1303]
I have attuned to Aevitas Constellation, but I am experiencing a weird bug. Other players in my server are reporting the same bug. When we enter the server, we don't have any of the effects we have unlocked with our respective perks. With my case in Aevitas, I don't get any extra health. But the moment we kill ourselves, we get our effects again. It is quite annoying to kill yourself every time you want to play because of this.

**Comment by Doomgull** [comment]
That's something outside of AS. Application of player attributes is handled by minecraft itself, plus any mods that may be modifying it.
