### ISSUE TITLE
Help with editing structures

### ISSUE THREAD

**Issue by Nohicom** [HellFirePvP/AstralSorcery#1304]
Hello! I have a bit of an issue/request.

I am making a modpack for myself and possibly some friends, which includes both Astral Sorcery and TerraFirmaCraft: The Next Generation. I was wondering if you could give me some assistance with changing the AS structures.
I would like to be able to change the water fountains on the structures that have them to be TFC fresh water instead of minecraft water, and would like to change the chests that spawn inside to be TFC chests instead (which hold less items, and adhere to the TFC item size/weight system).
I want to modify the loot tables the loot chests draw from as well, but I have a loot table editor mod for crafttweaker that should hopefully get the job done in that regard.

What would be the easiest way for me to do this? Or is this even possible without knowing how to write an entire mod for this purpose?
I have some basic coding experience (no java specifically yet unfortunately), and some knowledge of scripting.

**Comment by Doomgull** [comment]
That would require an add-on being written to change that, unfortunately.

**Comment by Nohicom** [comment]
Aw, that's disappointing. Well, I'll see what I can do I guess.

Thanks for your help anyway though! :D
