### ISSUE TITLE
[Suggestion] Spawner whitelist for Lucerna ritual

### ISSUE THREAD

**Issue by DAmNRelentless** [HellFirePvP/AstralSorcery#1307]
It would be cool if there was a way to whitelist specific spawners from the lucerna ritual which prevents mob spawning.
I know it doesn't block all mob spawns. For example cursed earth is still spawning mobs.

Would be nice to have the resturbed mob spawner from Extra Utilities working although the ritual is running nearby since spawning with this spawner is intended and shouldn't be prevented.

**Comment by Doomgull** [comment]
It doesn't block all spawns, just specific vanilla spawn calls. So if the mod overrides that, or has their own spawning call, it won't affect it.

**Comment by HellFirePvP** [comment]
I've changed the internal check from checking for an existing mob-spawner-logic reference to the deprecated isSpawner method. This will change as that method is redundant and to-be removed in newer versions already, though it might fix this behavior.

If not, there's not much i can/will do about it.
