### ISSUE TITLE
Config to disable Mantle's sparkle effect?

### ISSUE THREAD

**Issue by darchitectlp** [HellFirePvP/AstralSorcery#1310]
Love the mod! But the sparkly effect from the mantle is very distracting. Any chance it could be toned down or toggled off altogether?

Thanks for your hard work!

Edit: Actually, after playing some more, I really love the effect... and it really is just troublesome when you're trying to look down to build or attack. Is there anyway it could be modified so that the sparkles only trigger when you're moving? With maybe an ease-in, ease-out effect, so the longer distance you travel, the more pronounced the effect, but if you're making short, small moves, they don't appear at all.

**Comment by Doomgull** [comment]
It's changed some in the 1.14+ versions.
