### ISSUE TITLE
Collector Crystals not respecting chunk loading

### ISSUE THREAD

**Issue by Marzule-90** [HellFirePvP/AstralSorcery#1311]
As far as I can tell, collector crystals do not work with chunk loading and will only convert ore when in render distance. I have tested this in FTB Interactions and Enigmatica 2 Expert using a placer,breaker setup and flying outside of render distance while the chunk was loaded.

I have loaded the chunk both through FTB utils and weirding gadgets and neither has made a difference.

**Comment by Doomgull** [comment]
What version of AS in each? Crystals, the starlight network, and transmutation don't care about chunk loading, but they can't act on unloaded blocks.

**Comment by Marzule-90** [comment]
AS 1.10.22 in FTB:I and 1.10.23 in E2E. In both the cases the chunk is
loaded and other automation is working fine, but the crystal transmutation
isn't working on blocks it's linked to if i leave render distance.

**Comment by Saereth** [comment]
I can confirm this is happening with even vanilla+weirding gadgets chunk loading
