### ISSUE TITLE
[1.15.2] No config file generated

### ISSUE THREAD

**Issue by aprusik** [HellFirePvP/AstralSorcery#1314]
Not sure if this is intentional with the new 1.15 version being in alpha, but I couldn't find any config file generated after loading up the game with just Astral Sorcery, Curios, and Observerlib Installed.

**Steps to reproduce:**
I installed the mod into a fresh 1.15 client and loaded into a world.  Looks like the mod itself started fine because it shows up in the mod list and the Astral Tome spawns in my inventory.

**Additional Info:**
forge version 31.2.33

The only files in the config folder are:
```
curios-client.toml
curios-common.toml
fml.toml
forge-client.toml
```

**Comment by Doomgull** [comment]
It uses a serverconfig config file now. You'll want to look under <modpack>/saves/<world_name>/serverconfig directory now

**Comment by aprusik** [comment]
Got it. Sorry for the false report.

**Comment by Doomgull** [comment]
Not a problem, I flagged it internally first time I fired it up for internal testing, myself, until I realized what the change was due to config changes in later MC releases.

**Comment by aprusik** [comment]
I'm not familiar with the new config format. Does this mean Astral Sorcery will no longer have any client-side configuration options, or are they just not re-implemented yet?

**Comment by Doomgull** [comment]
Almost all AS configs have to match server and client anyway. Only ones that wouldn't involve particle displays, which function still from where they are now.

**Comment by aprusik** [comment]
Ah. The reason I ask is because the old weakSkyRenders config option was used for compatibility with things that changed the skybox and it doesn't seem to be present anymore.

**Comment by Doomgull** [comment]
Underlying code change. Whether it is needed/will make a return is yet to be seen. If you find conflict instances, would be good to document as a new ticket, though.

**Comment by aprusik** [comment]
Sounds good. I did find a conflict quickly testing out shaders with Optifine, but I'm not sure whether that is something that would be acceptable to post as a ticket giving the general consensus to not support anything having to do with Optifine or Shaders. (which is perfectly understandable)

**Comment by HellFirePvP** [comment]
That is unfortunate.. i would've hoped that with more streamlined rendering, more of the optifine shader stuff would disappear aswell. Seems like that is sadly not the case..

**Comment by aprusik** [comment]
Should write up a new issue regarding my experience just so it is documented somewhere, or would you rather just leave it for now?

**Comment by Doomgull** [comment]
Tracked internally now
