### ISSUE TITLE
[1.15.2] Luminous Crafting table doesn't show output item nor required starlight

### ISSUE THREAD

**Issue by TheUntamed** [HellFirePvP/AstralSorcery#1319]
If I place the items for a recipe in the Luminous Crafting table I cannot see how much Starlight is required and
if enough starlight is there the output item is not shown on the right of the crafting grid.
Were these features removed after 1.12 or is that a bug?
Note: The recipes itself and the crafting process are working. If starlight is there and I click on the table with the wand the item gets crafted.

No indicator about the required starlight:
![Screenshot_3](https://user-images.githubusercontent.com/48363903/89127790-cde81500-d4f0-11ea-9806-8402b16b826c.jpg)

Starlight is at maximum and the result item is not showing up:
![Screenshot_1](https://user-images.githubusercontent.com/48363903/89127796-dc363100-d4f0-11ea-8853-545e4c0ce7a4.jpg)

With a different recipe:
![Screenshot_2](https://user-images.githubusercontent.com/48363903/89127807-f8d26900-d4f0-11ea-8224-886be5a053d7.jpg)

I haven't tried it with another higher tier crafting table yet. Just with the Luminous.

**Comment by Doomgull** [comment]
Saw this in internal testing, wasn't able to reliably trigger. Do you have a list of other mods also being used at the same time so I can compare?

**Comment by TheUntamed** [comment]
It's an interaction with FTB Chunks and FTB Quests.

**Comment by Doomgull** [comment]
I have neither of those mods in the testing instance that produced this for me, so it's not that, or there's something else also messing with it.

**Comment by TheUntamed** [comment]
There ofc. might be more mods out there that break it. In my case I'm running a pack with over 200 mods and without these two ftb mods the visualization works fine. If I put one of these two mods in it breaks. I created a testing pack only containing one of these two mods and it broke again.

**Comment by Doomgull** [comment]
Hmm, so something common among more mods than just those, then. Definitely makes for a good basis to start investigating, though. Thanks!
