### ISSUE TITLE
Opening book after reattuning to new constellation causes server crash

### ISSUE THREAD

**Issue by gaggle331** [HellFirePvP/AstralSorcery#132]
astralsorcery-1.3.2-beta

Playing on Nuts and Bolts: Torqued on my private server with a friend. He used a shifting star to drop his attunement, then tried to attune to a couple other constellations which wouldn't even initiate attunement. Then he tried to attune to Vicio which seemed to kick off the attunement and finished attuning. After which he tried to open the journal and the whole server crashed. I've attached the crash report.

[crash-2017-04-22_19.05.21-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/949421/crash-2017-04-22_19.05.21-server.txt)

**Comment by HellFirePvP** [comment]
Can you reproduce this reliably every time or was this a 1-off thing? (This will most likely decide on how i'm gonna adress this)

**Comment by HellFirePvP** [comment]
Derp. found the issue.
