### ISSUE TITLE
Startup crash with Futurepack

### ISSUE THREAD

**Issue by Divineaspect** [HellFirePvP/AstralSorcery#1322]
https://pastebin.com/NRF1jkEu

**Comment by Divineaspect** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/687

**Comment by mcenderdragon** [comment]
hi, FuturepaclDev here, the code in Question is:
```
	@Override
	public int getMaxDamage(ItemStack stack)
	{
		int lvl = EnchantmentHelper.getEnchantmentLevel(Enchantments.UNBREAKING, stack);
		return super.getMaxDamage(stack) +(100 * lvl);
	}
```
EnchantmentHelper.getEnchantmentLevel, checks if Dynamic Enchanments are applyable, this checks if the ItemSTack is damageable, which directly check the maxDamage again. My best guess right now is to make a forge PR so patch ItemStack to call Item#isDamageable instead.

**Comment by mcenderdragon** [comment]
Made a PR to fix this https://github.com/MinecraftForge/MinecraftForge/pull/7222
