### ISSUE TITLE
[1.15.2] Missing Textures & Skybox Config

### ISSUE THREAD

**Issue by GatekeeperTDS** [HellFirePvP/AstralSorcery#1323]
Hi! So great to see Astral Sorcery again. Thanks for updating to 1.15!

I know this is an alpha build, but in case you didn't already know, a few blocks seem to be missing textures, even if I override them with textures of my own.

Aquamarine Shale -
![image](https://user-images.githubusercontent.com/66881994/89243235-75d50f80-d5d1-11ea-8cd9-244e8911a226.png)

Collector Crystal -
![image](https://user-images.githubusercontent.com/66881994/89243269-884f4900-d5d1-11ea-946d-992e91020426.png)

I think Rock Crystal Ore is also missing.

Additionally, the config files for the old versions used to have a way to disable the Astral skybox. As pretty as it is, I sometimes like to use my own skybox. Would it be possible to add an astralsorcery-client config file in addition to the server config file?

Thank you!

**Comment by Doomgull** [comment]
Optifine is causing the texture breakage. It's been discussed a lot on the AS discord already.

The weakskyrender wasn't re-added as it was expected that with various rendering changes in vanilla mc, it wouldn't be necessary, but...

Needs a ticket opened on optifine's end.

**Comment by GatekeeperTDS** [comment]
Thank you. Do you know what setting in Optifine causes the issue, or is it just Optifine in general?

**Comment by Doomgull** [comment]
Optifine is still pretty experimental in 1.15, last I saw. Unfortunately it is closed source so I cannot even attempt to hazard a guess.

**Comment by HellFirePvP** [comment]
Both config options to completely disable/enable the skyrendering in certain dimensionIds is still a thing, as is the weakSkyRender config option.
Check your running directory, ./config/astralsorcery-client.toml

Optifine causes these breakages. Nothing i can really fix about that since i also don't know what they're doing and what's broken about it in the first place.

**Comment by GatekeeperTDS** [comment]
https://github.com/HellFirePvP/AstralSorcery/issues/1337

**Comment by GatekeeperTDS** [comment]
https://github.com/sp614x/optifine/issues/4595
