### ISSUE TITLE
[1.15.2] Astral Relays Not Increasing Starlight In Celestial Altar

### ISSUE THREAD

**Issue by Plainedge** [HellFirePvP/AstralSorcery#1324]
I'm running into an issue where astral relays are not increasing the amount of starlight that my celestial altar has to craft with

Available starlight without any astral relays.
![image](https://user-images.githubusercontent.com/47410641/89268108-104f4600-d606-11ea-9337-27f865ea375f.png)

Available starlight when attempting to craft. 6 Astral relays are active (all are giving off the white and blue particle effects towards the celestial altar)
![image](https://user-images.githubusercontent.com/47410641/89267883-cb2b1400-d605-11ea-94a9-8047319e3f44.png)

I've tried recreating this in a testworld with only astral, curios, and observerlib installed but I run into a different issue of the starlight bar remaining white while being able to craft still. I think this may be user error but even while not being able to see the bar, I attempted the same crafting recipe shown above and even 9 astral relays activated were not able to complete the craft.

**Comment by Doomgull** [comment]
What if you move the relays further out, so the relay is 16 blocks from the altar?

**Comment by Plainedge** [comment]
Placing a few farther out at the maximum range also does not change the amount of starlight coming in. The starlight bar is still directly under the illumination powder in the shown recipe.
![image](https://user-images.githubusercontent.com/47410641/89299508-bf0a7b00-d634-11ea-9046-e8ae41272d33.png)
