### ISSUE TITLE
[1.15.2] Collector Crystals don't retain attuned constellations

### ISSUE THREAD

**Issue by tobi1449** [HellFirePvP/AstralSorcery#1328]
When crafting  a collector crystal it loses the attuned constellation of the input crystal.
This results in crafted collector crystals to not provide any starlight at all.
It also causes the game to crash when trying to place a crafted celestial crystal atop a collector enhancement structure.

**Comment by kalkafox** [comment]
Confirmed after replicating the steps above.

Here is a [log](https://github.com/HellFirePvP/AstralSorcery/files/5032925/log.txt) of the first error that leads up to the crash.

The crash report itself: [crash-2020-08-06_02.06.40-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/5032926/crash-2020-08-06_02.06.40-client.txt)
