### ISSUE TITLE
[1.15.2] Academy Shrine loot chest inaccurancy in Astral Tome -OR- loot missing from small Academy Shrines.

### ISSUE THREAD

**Issue by VallenFrostweaver** [HellFirePvP/AstralSorcery#1329]
Minecraft 1.15.2
Astral Sorcery 1.12.3
Forge 31.2.36

Small Academy Shrines don't have loot chests. The Astral Tome states that there will be loot chests in both sizes (located in the Academy Shrines chapter in Discovery).

**Comment by Doomgull** [comment]
Chance based from 0 to 4 chests now.

**Comment by VallenFrostweaver** [comment]
I checked 4 shrines. Read your reply. Checked the 5th and there it was. >.<
Well... at least it's here for any future issue reporting.
