### ISSUE TITLE
A lot of shrines all over the place

### ISSUE THREAD

**Issue by mankra** [HellFirePvP/AstralSorcery#133]
After updating to 1.3.2, I find a lot of shrines all over the place in new generated chunks.

![2017-04-23_11 41 28](https://cloud.githubusercontent.com/assets/22047030/25312486/f2048184-281a-11e7-8d96-1ec4243431df.jpg)

I assume this is not correct.

My config changes are:
ancientshrine and desertstructure I:Chance=160, smallshrine I:Chance=200

The S:idealDistance value is set to default values.

Minecraft: 1.10.2
Forge: 12.18.3.2254
Astral Sorcery: 1.3.2 beta

I also use mods affecting the world generation, if that matters:
Biomes O' Plenty: 5.0.0.2162
GeographiCraft: 0.8.7
Realistic Terrain Generation: 4.1.2.4

**Comment by mankra** [comment]
![2017-04-23_12 00 46](https://cloud.githubusercontent.com/assets/22047030/25312550/8e55e022-281c-11e7-9350-4125482f381a.jpg)

**Comment by mankra** [comment]
I tested without other mods, just Optifine and Astral Sorcery, and the issue still appears.

**Comment by mankra** [comment]
Well, I downgraded to 1.3.1, the issue was gone, then upgraded to 1.3.2 again and the issue is still gone. I'm confused... maybe I made a mistake updating the config in the first run...? Nevermind.

**Comment by HellFirePvP** [comment]
You might've used one of the versions that already got deleted again. There were 2 versions of 1.3.2 uploaded before the current one which had that bug.

**Comment by HellFirePvP** [comment]
First report for the Issue in question: #121
