### ISSUE TITLE
Resplendent Prism with +1/2 to all Existing Enchantments Breaks Fishing Rod with Lure?

### ISSUE THREAD

**Issue by Danekjovax** [HellFirePvP/AstralSorcery#1331]
First thing, this is a great mod! Thanks for providing a great magical mod for MC!  As I was playing this morning, however, I ran across this peculiar glitch and thought you'd like to know about it.

I have the following fishing rod:
![image](https://user-images.githubusercontent.com/10191173/89711074-f9865780-d955-11ea-94bd-d4cfc0df9930.png)
And by itself, it works just fine.

When I equip this resplendent prism:
![image](https://user-images.githubusercontent.com/10191173/89711123-45390100-d956-11ea-88f5-fc8dc4eb4961.png)
Things are also good; I still attract and catch fish.

However, with either of the following prisms equipped, the fishing rod no longer attracts fish:
![image](https://user-images.githubusercontent.com/10191173/89711171-9812b880-d956-11ea-8ebb-4111143c1f99.png)
![image](https://user-images.githubusercontent.com/10191173/89711153-76b1cc80-d956-11ea-8b3f-2ae1638538c7.png)

Please advise. ;2)

**Comment by Doomgull** [comment]
https://minecraft.gamepedia.com/Lure

"If commands are used to increase the enchantment level beyond 5, the wait timer does not start and fish do not bite."

Vanilla thing.

**Comment by Danekjovax** [comment]
I wasn't aware of that.  I'll see what we can do with it on our server. Thank you.
