### ISSUE TITLE
NBT Tag inventory bug

### ISSUE THREAD

**Issue by Thunder-Nova** [HellFirePvP/AstralSorcery#1335]
Posted it here because it was during my session in the official All the mods modpack, and noticed my drawers acting wonky.

Then noticed 2 random NBT out of nowhere.

So added a mod called NBT tooltips so I can see the NBT.

My held items gains 2 AS_Amulet_Holder NBT tags

![image](https://user-images.githubusercontent.com/31967337/89723386-80254e00-d9c3-11ea-98c5-7edf6a7120d0.png)

Quite problematic, and sometimes shift clicking that items will keep that NBT and not mix with the ones without.

Whole story:
https://github.com/AllTheMods/ATM-5/issues/216

**Comment by Doomgull** [comment]
#1334
