### ISSUE TITLE
[1.15.2] Crystal Merging sometimes merges a crystal with itself

### ISSUE THREAD

**Issue by tobi1449** [HellFirePvP/AstralSorcery#1336]
In MergeCrystalsRecipe.java, line 99
`CrystalAttributes mergeTo = attrOne.getTotalTierLevel() >= attrTwo.getTotalTierLevel() ? attrOne : attrOne;`
should be 
`CrystalAttributes mergeTo = attrOne.getTotalTierLevel() >= attrTwo.getTotalTierLevel() ? attrOne : attrTwo;`

Results in sometimes the second crystal being completely overwritten since it just merges the first crystal with itself.

**Comment by HellFirePvP** [comment]
... derp. thanks.
