### ISSUE TITLE
[1.15.2] Skybox Config / No Client Config File

### ISSUE THREAD

**Issue by GatekeeperTDS** [HellFirePvP/AstralSorcery#1337]
@HellFirePvP Hi - Sorry to be a pain, but for the life of me I can't find an astralsorcery-client file anywhere. This is in reference to #1323 

In the server files, the only astral-related config file is in the serverconfig directory -
![image](https://user-images.githubusercontent.com/66881994/89736632-afc26d80-da38-11ea-8f02-3f0bb494227e.png)

There are no astral config files in my client instance -
![image](https://user-images.githubusercontent.com/66881994/89736644-cf599600-da38-11ea-92fd-f7d080177ca9.png)

Is it perhaps not generating the file as it should? Thank you for your help.

**Comment by Tomatoh** [comment]
It creates a serverconfig under the worlds save file but no client. They need to move some options to a separate client file
