### ISSUE TITLE
[1.12.2] Funky ore textures

### ISSUE THREAD

**Issue by Awesomespore** [HellFirePvP/AstralSorcery#1338]
In version 1.12.2-1.10.24 of the mod, aquamarine shale and starmetal ore look really weird, with black and white "shadows" above and below the ore parts of the texture. I have tested this with and without optifine, and it makes no difference.
![2020-08-10_20 43 29](https://user-images.githubusercontent.com/59407684/89765333-374bd180-db4a-11ea-8b9c-c8d592152657.png)

Now what's especially strange about this is the fact that as items, they look completely normal ![image](https://user-images.githubusercontent.com/59407684/89765742-03bd7700-db4b-11ea-8ad7-dbc2373f4afc.png)

Mod list:
![image](https://user-images.githubusercontent.com/59407684/89765464-80038a80-db4a-11ea-9785-6275a0da2b1d.png)

**Comment by Awesomespore** [comment]
Judging by the lack of prior mention, I'm assuming it's an issue being caused by another mod, but I'm not sure which mod(s) would be causing it

**Comment by HellFirePvP** [comment]
optifine

**Comment by Awesomespore** [comment]
As I said, I tried it WITHOUT optifine and the result was the same. @HellFirePvP

**Comment by Awesomespore** [comment]
In other words, you didn't read the full report, did you?

>  I have tested this with and without optifine, and it makes no difference.

**Comment by Awesomespore** [comment]
I'm gonna test again to see if it is actually optifine or not. (I am aware that optifine tends to break many things)

**Comment by Awesomespore** [comment]
Alas, my testing was erroneous, it is indeed optifine causing it. Sorry about the hassle :)
![2020-08-20_15 03 30](https://user-images.githubusercontent.com/59407684/90712089-57238800-e2f6-11ea-9a49-e8891f7b1114.png)
