### ISSUE TITLE
When I click on a constellation in the book, the game locks up and crashes.

### ISSUE THREAD

**Issue by TheCommunityDev** [HellFirePvP/AstralSorcery#134]
I have the mod tied in with my FTB Beyond pack on my server and it crashes my client upon selecting a constellation in the book.

[crash-2017-04-23_05.01.18-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/949978/crash-2017-04-23_05.01.18-client.txt)

**Comment by HellFirePvP** [comment]
#131 #127
