### ISSUE TITLE
Inventory HUD 

### ISSUE THREAD

**Issue by MatestHD** [HellFirePvP/AstralSorcery#1340]
My inventory HUD background turned in the Starlight texture I suppose.
I only have a screenshot and I know that the baubles inventory turned it normal if I toggled it but would remain with the texture afterwards.
I restarted minecraft and it disapeared.
I don`t remember what I did to put it that way.
I tried searching for what it was and found nothing so I thought it was a bug.
![2020-08-09_18 43 46](https://user-images.githubusercontent.com/52674923/89805566-bda5ea80-db2d-11ea-8a1c-2f671aa64da1.png)

**Comment by Doomgull** [comment]
What Astral Sorcery version/MC version? What else are you running?

**Comment by MatestHD** [comment]
Im in version 1.12.2 in the latest release of Astral Sorcery.
I`ll write the mods I`m using:

Advanced Vanilla
Akashic Tome
Astral Sorcery
AutoRegLib
Backpack
Baubles
BetterAnimalsPlus
Better Caves
BetterMineshafts
BiomesOPlenty
BonsaiTrees
Botania
Chameleon
Charm
Chisel
CodeChickenLib
CoFHCore
CoFHWorld
Conarm
CraftableHorseArmour
CTM
Cucumber
DoggyTalents
EnderStorage
EndReborn
Fast Leaf Decay
Forgelin
Gravestone
Hwyla
ImmersiveEngineering
Industrial Foregoing
Inventory Tweaks
Ironchest
JEI
JER
Kiwi
LibraryEx
Mantle
Mcwdoors
Mcsfurniture
Mekanism
MekanismGenerators
Mystcraft
MysticalAgriculture
MysticalLib
Mystical World
Nature`s Compass
NetherEx
NoMoreRecipeConflict
OpenBlocks
OpenModsLib
Optifine HD F5
Patchouli
Placebo
Quark
RedstoneFlux
Savemystronghold
SimpleStorageNetwork
StorageDrawers
Tinkers Contruct
Tesla core lib
Tetra
Thermal Dynamics
Thermal Expansion
Thermal Foundation
Twilight Forest
UniDict
WanionLib
Waystones
Xaeros Minimap

**Comment by Doomgull** [comment]
"latest" is never an answer in general for any kind of report, regardless of mod. The number of times I've seen that and the actual answer is "Several versions behind" is staggering.

Try disabling fast-render in Optifine.

**Comment by MatestHD** [comment]
It was 

AstralSorcery-1.12.2-1.10.25.jar
--

**Comment by HellFirePvP** [comment]
Try without optifine.
