### ISSUE TITLE
missing textures

### ISSUE THREAD

**Issue by CosmicCato** [HellFirePvP/AstralSorcery#1341]
mkay so i was play the 1.15.2 version of the mod for the first time and i noticed a "few" missing textures on the game. i dont know if the data got corrupted somehow when i downloaded it or the textures just aren't there at all. the textures that dont work are all of the crystals that can be built, most of the attunement stuff, the ores, ect. i can give ya screen shots of the blocks/items labled if needed (i know im not good at explaning things) i do have other mods running so i took them off to check if that was the issue. it wasnt. i am running this on linux ubuntu if that effects anything. Thanks for listening to me. 

PS. i hecking love the mod. :3

**Comment by Doomgull** [comment]
#1323
