### ISSUE TITLE
[1.15.2] Crossbows with quick charge can break resplendent prisms.

### ISSUE THREAD

**Issue by Mad-Science-Matt** [HellFirePvP/AstralSorcery#1342]
When a crossbow with quick charge is reloaded, if an equipped resplendent prism boosts the level of the enchant to 5 [Quick Charge V], _all_ resplendent prisms stop providing bonuses entirely until Minecraft is completely restarted.

**Comment by HellFirePvP** [comment]
Can't replicate this behavior through the steps described.

**Comment by Doomgull** [comment]
Full list of other mods involved?
