### ISSUE TITLE
PacketHacks

### ISSUE THREAD

**Issue by TheKlimoT** [HellFirePvP/AstralSorcery#1343]
astralsorcery-1.12.2-1.10.25.jar=hellfirepvp/astralsorcery/common/integrations/mods/crafttweaker/network/GrindstoneRecipeRemove#read
astralsorcery-1.12.2-1.10.25.jar=hellfirepvp/astralsorcery/common/integrations/mods/crafttweaker/network/InfusionRecipeRemove#read
astralsorcery-1.12.2-1.10.25.jar=hellfirepvp/astralsorcery/common/integrations/mods/crafttweaker/network/LightTransmutationAdd#read
astralsorcery-1.12.2-1.10.25.jar=hellfirepvp/astralsorcery/common/integrations/mods/crafttweaker/network/LightTransmutationRemove#read
astralsorcery-1.12.2-1.10.25.jar=hellfirepvp/astralsorcery/common/integrations/mods/crafttweaker/network/WellRecipeAdd#read
astralsorcery-1.12.2-1.10.25.jar=hellfirepvp/astralsorcery/common/integrations/mods/crafttweaker/network/WellRecipeRemove#read

Fix It :)

**Comment by HellFirePvP** [comment]
You mind being more descriptive?

**Comment by TheKlimoT** [comment]
Check you mod - https://github.com/Zaxar163/HackFinder

**Comment by Doomgull** [comment]
No, you need to explain what the issue is, and why it's an issue.

**Comment by HellFirePvP** [comment]
Where did you download your AstralSorcery jar?
What this utility scans for is not in AstralSorcery's mod jar which i distribute via curseforge.

**Comment by HellFirePvP** [comment]
Going through it again, this doesn't affect AS and nothing can be "hacked" with this.
