### ISSUE TITLE
[1.15.2] Crashed at launch in Valhelsia 2 modpack

### ISSUE THREAD

**Issue by prothico** [HellFirePvP/AstralSorcery#1349]
It was a simple drag and drop of the new 1.15.2 update into Valhelsia 2 (which is a 1.15.2 modpack) mod folder. I am unsure if other steps needed to be taken, but just assume I wouldn't know to do x. So, probably less of an issue and more of me just being clueless.

**Comment by kalkafox** [comment]
Do you have a crash report/latest.log?

**Comment by Doomgull** [comment]
Need a crash log

**Comment by prothico** [comment]
I wasn't able to find the launch report from before so instead I tried launching again. This time it requested Observerlib 1.15.2 which I downloaded and also moved into the mods folder for Valhelsia 2. It was able to launch successfully and get into the start menu. It appears to be functional. I'll add anything if it becomes relevant.

**Comment by Doomgull** [comment]
That crashed because of a bat.
