### ISSUE TITLE
Loading NBT data Crash

### ISSUE THREAD

**Issue by CrowBBGN** [HellFirePvP/AstralSorcery#135]
I am running a server for me and a few friends and have a random teleport setup at spawn so they can explore. My friend, DWX, hits the button and.....    Server Crash...  

After the server starts back up and he tries to login, crash again.. 
All other players are fine. 
Going by the stacktrace, I assume it has to do with the generation of some rock crystal. Forgive me, I haven't really played with your mod yet, DWX wanted it added so my knowledge is limited at this time.
One time this happened I deleted the region he was in to let it regenerate and it still crashed once he logged in.
The only thing I can do is edit his player.dat file and set his POS somewhere else. Then he can login as normal and just not go to that area again. 

I have included the crash report and log starting from when he logs in.
If you need anything else I will be happy to provide.
Thanks.

Crash Report : https://hastebin.com/akupunesec.rb
Log : https://hastebin.com/uneqaqohas.md

Update:
Just happened again, this time I kept him where he was, backed up and removed the rcrystals.dat file and no crash.

**Comment by HellFirePvP** [comment]
Going to rewrite the WorldData handling for the next version, so things like this won't happen anymore. Can't say much about it at the moment though, however it seems something corrupted the rock crystals buffer file and led to this crash multiple times...

btw: you're not having a mod that does multithreaded chunk-generation right?

**Comment by HellFirePvP** [comment]
Much like the research file, the worlddata file now has in the next update a backup-file system. So. yea. next update. :|
