### ISSUE TITLE
Issues rendering ground properly. 

### ISSUE THREAD

**Issue by luna6667** [HellFirePvP/AstralSorcery#1350]
Lines appear between blocks at a certain distance from the player. images provided are both brand new worlds. 
![image](https://user-images.githubusercontent.com/11493210/90584439-9b9d0f80-e1a0-11ea-930c-abea1661db8c.png)
![image](https://user-images.githubusercontent.com/11493210/90584456-a5bf0e00-e1a0-11ea-8cc1-cba4987d734b.png)

**Comment by kalkafox** [comment]
This looks like a GPU rendering issue; I've had this issue occur before. Are you running on AMD or Nvidia? Is this also reproducible without Astral Sorcery installed?

**Comment by luna6667** [comment]
@kalkafox Running Nvidia. and it is in vanilla too. its been a while since i played 1.15.2 in general so i must've forgotten. Closing.
