### ISSUE TITLE
[1.15] reach increases doesn't affect combat

### ISSUE THREAD

**Issue by MuricanSWAG** [HellFirePvP/AstralSorcery#1354]
increases to reach work fine for breaking and placing blocks. When attacking mobs however, I still need to be in the default melee range to attack. 

as of AS version 1.12.6 on forge version 31.2.9

**Comment by Awesomespore** [comment]
From what I can tell this is not Astral Sorcery at fault. Even playing with Botania and using the Ring of Far Reach, the additional reach distance only applies to block-based interactions, and not entities.
I'm gonna blame this one on forge, much like the bizarre behavior with shears in forge 1.15...

**Comment by MuricanSWAG** [comment]
I have had the same issue using only AS, curios, obeserverlib and forge. It was fixed however in a new world with the same versions of everything. In the worlds I have the bug(one world with other mods and one with only AS and JEI), I have updated AS and/or forge multiple times  I guess the issue was either fixed by an update in a way that did not fix in existing worlds or it still exists and is triggered after some unknown event

**Comment by MuricanSWAG** [comment]
It looks like the bug is still there. In the new world I made, My range increase perks were working perfectly until I equipped a Bootes enhanced sword with 10% increased reach, resulting in the same bug. In this world, I have only used the latest versions of AS and forge and have no other mods besides AS and dependencies (not even JEI).

**Comment by MuricanSWAG** [comment]
So it seems the problem was completely different to what I thought before. Trying again, it was not the sword that messed with my reach at all. Rather, reach increases do work for combat in creative mode but do not affect combat in survival. This is consistent throughout all world, worlds with Just AS and worlds with other mods.

**Comment by HellFirePvP** [comment]
That i can reproduce

**Comment by HellFirePvP** [comment]
Fixed. the locals changed.

**Comment by HellFirePvP** [comment]
Thinking about it, i'll make a perk out of this.
