### ISSUE TITLE
[1.15.2] [Suggestion] Allow Marble to be used in the Stonecutter

### ISSUE THREAD

**Issue by Alan19** [HellFirePvP/AstralSorcery#1356]
Being able to choose which Marble variant you want in the Stonecutter makes crafting and creating multiblocks much more pleasant.

**Comment by Doomgull** [comment]
The what?

**Comment by Alan19** [comment]
The Stonecutter is a villager job site that allows you to turn blocks like Stone Bricks into Chiseled Stone Bricks, similar to what Chisel does.

https://minecraft.gamepedia.com/Stonecutter
