### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Rohzek** [HellFirePvP/AstralSorcery#136]
Upon updating Astral Sorcery to the most recent version (1.3.2-beta), I've found that clicking on a constellation on the page, rather you have researched/drawn it or not, causes the game to crash with a NullPointerException, while calling GuiJournalConstellationDetails#buildLines.
This occurs both in the server which had a world already generated, and in a brand new world generated with this version (tested in singleplayer).

Full crash log here:
https://pastebin.com/Z3DX5jFz

**Comment by Doomgull** [comment]
Already fixed for next version, it's had multiple issues opened for it, which have all been duped back to the original now, look at ticket 127.

**Comment by HellFirePvP** [comment]
Yey, another report...

#134 #131 #127
