### ISSUE TITLE
1.15.2での起動ができず、エラーが表示される（Cannot start with 1.15.2, and an error is displayed）

### ISSUE THREAD

**Issue by asagi-11** [HellFirePvP/AstralSorcery#1361]
私は英語ができません。日本語で書き込みますが、下に機械翻訳をかけたものを載せておきます。内容は同一のものです。

Minecraftのバージョンは1.15.2、Forgeは1.15.2-31.2.0を使用しています。
また、curios-FORGE-1.15.2-2.0.2.4、observerlib-1.15.2-1.2.0.v60を導入しました。
読み込み時にエラーが発生し、メインメニューに到達できません。添付ファイルはその時のlogです。
他のMODは導入していません。curiosとobserverlibのみの場合は正常に展開できます。
[latest.log](https://github.com/HellFirePvP/AstralSorcery/files/5119157/latest.log)

私はプログラミングに詳しくなく、初歩的な問題でも気づけない可能性が高いです。いろいろと試しましたが、原因がわからずこちらに書き込みました。
ASは1.12を導入していました。そちらは問題なく動きます。

ここから翻訳です/Translation from here

I can not do English. I will write it in Japanese, but I will post the machine translated version below. The contents are the same.

The version of Minecraft is 1.15.2, and Forge is 1.15.2-31.2.0.
Also, curios-FORGE-1.15.2-2.0.2.4 and observerlib-1.15.2-1.2.0.v60 were introduced.
There is an error loading and I cannot reach the main menu. The attached file is the log at that time.
No other mods have been introduced. If you only use curios and observerlib, you can deploy normally.
[latest.log](https://github.com/HellFirePvP/AstralSorcery/files/5119157/latest.log)

I'm not familiar with programming, and I'm likely not even aware of elementary problems. I tried various things, but I did not understand the cause and wrote it here.
AS had introduced 1.12. That works fine.

**Comment by Doomgull** [comment]
Update forge to latest release.

**Comment by asagi-11** [comment]
Forgeを安定板ではなく最新版に差し替えたら問題なく動きました！ありがとうございます！

I replaced Forge with the latest version, not the stabilizer, and it worked! Thank you!
