### ISSUE TITLE
[1.15.2] Multiplayer: Unable to claim perk from tree

### ISSUE THREAD

**Issue by kalkafox** [HellFirePvP/AstralSorcery#1363]
Reproduced on 9344a93, version 1.12.7. Despite having the qualifications, the ability to claim a perk does not work. This only happens on the multiplayer side.

[video log](https://imgur.com/a/XMjtM43)

![image](https://user-images.githubusercontent.com/9144208/91145842-10ca8200-e684-11ea-92ec-58d8fac9deaf.png)

No error is logged in the console while this is happening.

EDIT: This is not reproducible on LAN.

**Comment by HellFirePvP** [comment]
Derp. Fixed for next version.
Accidentally queried client-data on serverside.
