### ISSUE TITLE
[1.15.2] Unable to claim epiphany perk

### ISSUE THREAD

**Issue by kalkafox** [HellFirePvP/AstralSorcery#1364]
Reproduced on 9344a93, version 1.12.7. After claiming the first epiphany perk, the ability to claim another said perk fails. (The perk is highlighted as available, but upon clicking, it does not claim, and resets back to its original color.)

[video log](https://imgur.com/nHKKLzl)

**Comment by HellFirePvP** [comment]
Already fixed internally, will be available/fixed with 1.12.7
