### ISSUE TITLE
Crash when opening perk map 1.15.2

### ISSUE THREAD

**Issue by Secretlylemon** [HellFirePvP/AstralSorcery#1365]
The game crashes when trying to open the perk menu. Using a star to reset the perk map worked but has failed to do so after working once. Attached is the crash report i get every time it crashes. 

Astral sorcery is added to Valhesia 2 along with mahou Tsukai.
[crash-2020-08-26_13.53.35-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/5127543/crash-2020-08-26_13.53.35-client.txt)

**Comment by HellFirePvP** [comment]
Update to 1.12.7 please.
