### ISSUE TITLE
[1.15.2] Multiplayer: Tome GUI fails to open while on lectern

### ISSUE THREAD

**Issue by kalkafox** [HellFirePvP/AstralSorcery#1366]
Reproduced in f01e02a. Not reproducible in singleplayer. While using the Astral Tome with a Lectern in Multiplayer, the journal GUI does not open, and instead opens a default vanilla book GUI for a split second before disappearing.

[video log](https://imgur.com/Il1OYfM)

**Comment by HellFirePvP** [comment]
Thought i had fixed this..
