### ISSUE TITLE
Beam debug with shaders ?

### ISSUE THREAD

**Issue by Evademmm** [HellFirePvP/AstralSorcery#1367]
Hi, i just have a question, is there a way to fix the "beam" / "light" effect with the shaders like for the sky ?
In the config file or something ? by beam i mean for exemple when you place a crafting table near the temple.

**Comment by Doomgull** [comment]
Closest you will get is the weakSkyRender config option. Support alongside other shaders isn't really a thing.

**Comment by Evademmm** [comment]
sry i already fixed the sky i didn't mean to say that, i was searching a fix for the particles, like it's creating squares around them.
If there is no other config file option to set then no worries and thanks for helping.
