### ISSUE TITLE
"java.lang.NullPointerException: Saving entity NBT" Crash when trying to attune Player (Crystals are safe)

### ISSUE THREAD

**Issue by TeamEeveeG** [HellFirePvP/AstralSorcery#1372]
(Layout pretty much stolen from Pokecube's Issue Page): https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/issues
#### Issue Description:
Players using the Attunement Alter cause a NullPointerException caused from Saving entity NBT. Crystals (Rock and Celestial) are unaffected. Player can still rejoin, but need to step as far away from alter as possible

#### What happens:
I wanted to see what Astral Sorcery had in 1.15. I used it with my usual set of mods (BOP, the Quark group (Quark, Oddities, Charm, and Strange), JEI, and Pokecube), replacing HWYLA with TheOneProbe, my new favorite, along with some others. (full list and Forge/Minecraft version in crash report. When I went to attune myself (to Vicio), and I crashed with the exception in the title. I looked it up and found that it is caused when you mess up trying to change the player's data by either adding a new NBT tag onto them or changing an NBT tag the mod adds. I got back onto the world on a newer version of AS (the last one was from a week ago from the time of me typing this) to find that I wasn't locked out because of how it takes a while for AS to recognize that there was an accepted constellation. I backed out of the pull area the alter has. I tested it with a Rock Crystal and Celestial Crystal (Also Vicio because I was too lazy to set up another attunement). It worked as expected, but I had to take protective measures to avoid getting sucked into the alter and crashing (by which, I mean breaking an Astral Relay).

#### What you expected to happen:
To be able to attune myself to Vicio... mainly so I can look at the lesser constellations.

#### Steps to reproduce:
1. Set up an Attunement Alter and set it to attune to one of the bright constellations.
2. Step close enough to it. You don't even need to step into it, just step to the point will it had (in 1.12 and earlier) pulled you to the center and played the (awesome despite the lag) animation.
3. Congrats! You came all this way just to crash! Hope you can make it with only the bright Constellations! What's that? You need some of the darker constellations to progress? Too bad, hope you have cheats enabled because you'd need to enter creative mode (or JEI Cheat Mode) to get said item.

____
#### Affected Versions (Do *not* use "latest"):
(See crash report line 146 to 168)

____
#### Crash Report (most recent):
https://gist.github.com/TeamEeveeG/bfc4c0e9902b32c6e8545b432d4a5799

____
#### Notes:
I know it mentions Pokecube in the list of "at"s. If it turns out that it was Pokecube causing it, I will be copy/pasting this (with minor edits) on its issue page.

**Comment by HellFirePvP** [comment]
Not AS' fault.
