### ISSUE TITLE
Aevitas not showing up?

### ISSUE THREAD

**Issue by Zerahn** [HellFirePvP/AstralSorcery#1373]
I've been scanning the sky every night except for two, spaced three or so days apart, when it was raining. I have Aevitas' constellation paper stuffed in the back of my tome, but the constellation never shows up. It's the last one I need, and I always get one of the other ones that are already drawn.

I dunno if it was chance or what, but until Aevitas was the last one I needed, I never saw a discovered constellation in the looking glass, nor two constellations in the same night - just one that still needed to be drawn.

**Comment by Doomgull** [comment]
Because looking glass only ever will show one Bright constellation per night at a time. Upgrade to a telescope.

In the future, this is more a thing for the Discord, not a github ticket.
