### ISSUE TITLE
[1.15.2]Can't see anything in Telescope, No Stars

### ISSUE THREAD

**Issue by SampsonnZ** [HellFirePvP/AstralSorcery#1377]
![20200903010301](https://user-images.githubusercontent.com/9107855/92014113-4c9ad100-ed81-11ea-9a3b-b213dfb1c0bb.jpg)
No Optifine Installed
Forge 31.2.36
CPU: Intel Core i5-10210u
GPU: Intergrated Graphics
RAM: 16GB
Java 8 update 261, 64-bit.
I've updated the GPU driver to the latest version.

**Comment by SampsonnZ** [comment]
Mod List:
 • mods_folder astralsorcery-1.15.2-1.12.8.jar : astralsorcery (1.15.2-1.12.8) - 1
• mods_folder NetherPortalFix_1.15.2-6.0.2.jar : netherportalfix (6.0.2) - 1
• mods_folder aiotbotania-1.15.2-1.2.3.jar : aiotbotania (1.2.3) - 1
• mods_folder refinedpipes-0.4.2.jar : refinedpipes (0.4.2) - 1
• mods_folder SilentMechanisms-1.15.2-0.8.0+59.jar : silents_mechanisms (0.8.0+59) - 1
• mods_folder Neat 1.6-22.jar : neat (1.6-22) - 1
• mods_folder essentials-1.15.2-2.7.4.jar : essentials (1.15.2-2.7.4) - 1
• mods_folder TerraForged-1.15.2-0.1.2.jar : terraforged (0.1.2) - 1
• mods_folder CookingForBlockheads_1.15.2-8.0.3.jar : cookingforblockheads (8.0.3) - 1
• mods_folder Placebo-1.15.2-3.1.0.jar : placebo (3.1.0) - 1
• mods_folder Powah-1.15.2-1.1.15.jar : powah (1.1.15) - 1
• mods_folder Bookshelf-1.15.2-5.6.40.jar : bookshelf (5.6.40) - 1
• mods_folder u_team_core-1.15.2-3.0.2.169.jar : uteamcore (3.0.2.169) - 1
• mods_folder randompatches-1.15.2-1.22.1.1.jar : randompatches (1.15.2-1.22.1.1) - 1
• mods_folder DarkUtilities-1.15.2-3.1.8.jar : darkutils (3.1.8) - 1
• mods_folder Apotheosis-1.15.2-3.2.4.jar : apotheosis (3.2.4) - 1
• mods_folder ProgressiveBosses-2.1.5-mc1.15.2.jar : progressivebosses (2.1.5-mc1.15.2) - 1
• mods_folder MekanismGenerators-1.15.2-9.10.9.422.jar : mekanismgenerators (9.10.9) - 1
• mods_folder mysticallib-1.15.2-2.0.1.jar : mysticallib (1.15.2-2.0.1) - 1
• mods_folder absentbydesign-1.15.2-1.1.0.jar : absentbydesign (1.15.2-1.1.0) - 1
• mods_folder refinedstorage-1.8.8.jar : refinedstorage (1.8.8) - 1
• mods_folder structure-gel-api-1.15.2-1.1.0.jar : structure_gel (1.1.0) - 1
• mods_folder industrial-foregoing-1.15.2-2.3.3-e356e61.jar : industrialforegoing (2.3.3) - 1
• mods_folder useful_backpacks-1.15.2-1.10.1.70.jar : usefulbackpacks (1.10.1.70) - 1
• mods_folder torchmaster-2.2.2.jar : torchmaster (2.2.2) - 1
• mods_folder phosphor-forge-mc1.15.2-0.5.2+build.4.jar : phosphor (0.5.2+build.4) - 1
• mods_folder MekanismAdditions-1.15.2-9.10.9.422.jar : mekanismadditions (9.10.9) - 1
• mods_folder Lollipop-1.15.2-1.0.16.jar : lollipop (1.0.16) - 1
• mods_folder toughnessbar-5.0.jar : toughnessbar (5.0) - 1
• mods_folder SilentGear-1.15.2-1.11.3+160.jar : silentgear (1.11.3+160) - 1
• mods_folder simplefarming-1.15.2-1.3.0.jar : simplefarming (1.15.1-1.3.0) - 1
• mods_folder SolarFluxReborn-1.15.2-15.2.3.jar : solarflux (15.2.3) - 1
• mods_folder curios-FORGE-1.15.2-2.0.2.6.jar : curios (FORGE-1.15.2-2.0.2.6) - 1
• mods_folder Botania-r1.15-388.jar : botania (r1.15-388) - 1
• mods_folder Patchouli-1.15.2-1.2-35.jar : patchouli (1.15.2-1.2-35) - 1
• mods_folder config-2-3.0.jar : cloth-config2 (3.0) - 1
• mods_folder libnonymous-1.15.2-1.1.1.5.jar : libnonymous (1.1.1.5) - 1
• mods_folder elevatorid-1.15.2-1.7.1.jar : elevatorid (1.15.2-1.7.1) - 1
• mods_folder MekanismTools-1.15.2-9.10.9.422.jar : mekanismtools (9.10.9) - 1
• mods_folder furniture-7.0.0-pre16-1.15.1.jar : cfm (7.0.0-pre16) - 1
• mods_folder curiouselytra-FORGE-1.15.2-2.0.jar : curiouselytra (FORGE-1.15.2-2.0) - 1
• mods_folder cc-tweaked-1.15.2-1.91.0.jar : computercraft (1.91.0) - 1
• mods_folder observerlib-1.15.2-1.2.0.v60.jar : observerlib (1.15.2-1.2.0) - 1
• mods_folder cherishedworlds-FORGE-1.15.2-3.0.0.1.jar : cherishedworlds (FORGE-1.15.2-3.0.0.1) - 1
• mods_folder incubation-1.0.4-1.15.2.jar : incubation (1.0.4) - 1
• mods_folder FastLeafDecay-v22.jar : fastleafdecay (v22) - 1
• mods_folder CodeChickenLib-1.15.2-3.3.1.379-universal.jar : codechickenlib (3.3.1.379) - 1
• mods_folder BetterMineshaftsForge-1.15.2-1.3.jar : bettermineshafts (1.15.2-1.3) - 1
• mods_folder leavesdecayonotherleaves-1.1.jar : leavesdecayonotherleaves (1.1) - 1
• mods_folder BetterAdvancements-1.15.2-0.1.0.99.jar : betteradvancements (0.1.0.99) - 1
• mods_folder usefulsaves-0.1.1-1.15.2-31.1.12.jar : usefulsaves (0.1.1-1.15.2-31.1.12) - 1
• mods_folder QuarkOddities-1.15.2.jar : quarkoddities (1.15.2) - 1
• mods_folder TrashSlot_1.15.2-11.0.0.jar : trashslot (11.0.0) - 1
• mods_folder EquipmentTooltips-1.15.2-1.4.3+14.jar : equipmenttooltips (1.4.3+14) - 1
• mods_folder mining-helmet-1.15.2-1.0.8.jar : mining_helmet (1.0.8) - 1
• mods_folder Druidcraft-1.15-0.4.31.jar : druidcraft (0.4.31) - 1
• mods_folder AttributeFix-1.15.2-7.0.2.jar : attributefix (7.0.2) - 1
• mods_folder the-conjurer-1.15.2-1.0.7.jar : conjurer_illager (1.0.7) - 1
• mods_folder Abnormals-Core-1.15.2-1.0.6.jar : abnormals_core (1.0.6) - 1
• mods_folder Buzzier-Bees-1.15.2-1.5.2.jar : buzzierbees (1.5.2) - 1
• mods_folder Mekanism-1.15.2-9.10.9.422.jar : mekanism (9.10.9) - 1
• mods_folder caelus-FORGE-1.15.2-2.0-beta3.jar : caelus (FORGE-1.15.2-2.0-beta3) - 1
• mods_folder Upgrade-Aquatic-1.15.2-1.7.1.jar : upgrade_aquatic (1.7.1) - 1
• mods_folder create-mc1.15.2_v0.2.4d.jar : create (mc1.15.2_v0.2.4d) - 1
• mods_folder Waystones_1.15.2-6.0.2.jar : waystones (6.0.2) - 1
• mods_folder Clumps-5.0.2.6.jar : clumps (5.0.2.6) - 1
• mods_folder light-overlay-4.7.0.jar : lightoverlay-forge (NONE) - 1
• mods_folder comforts-FORGE-1.15.2-2.0.0.4.jar : comforts (FORGE-1.15.2-2.0.0.4) - 1
• mods_folder NaturesCompass-1.15.2-1.8.5.jar : naturescompass (1.15.2-1.8.5) - 1
• mods_folder SimpleStorageNetwork-1.15.2-1.0.1.jar : storagenetwork (1.15.2-1.0.1) - 1
• mods_folder BotanyPots-1.15.2-2.0.27.jar : botanypots (2.0.27) - 1
• mods_folder curioofundying-FORGE-1.15.2-3.0.jar : curioofundying (FORGE-1.15.2-3.0) - 1
• mods_folder BonsaiTrees-2.1.2.6.jar : bonsaitrees2 (2.1.2.6) - 1
• mods_folder mcjtylib-1.15-4.1.3-beta.jar : mcjtylib (1.15-4.1.3-beta) - 1
• mods_folder mapperbase-1.15.2-1.1.1.0.jar : mapperbase (1.15.2-1.1.1.0) - 1
• mods_folder ToastControl-1.15.2-3.0.1.jar : toastcontrol (3.0.1) - 1
• mods_folder mininggadgets-1.3.5.jar : mininggadgets (1.3.5) - 1
• mods_folder EnderStorage-1.15.2-2.5.0.151-universal.jar : enderstorage (1.15.2-2.5.0.151) - 1
• mods_folder mysticalworld-1.15.2-2.0.6.jar : mysticalworld (1.15.2-2.0.6) - 1
• mods_folder extradisks-1.15.2-1.2.2.jar : extradisks (1.15.2-1.2.2) - 1
• maven_libs forge-1.15.2-31.2.36-universal.jar : forge (31.2.36) - 1
• mods_folder Atum-1.15.2-2.1.4.jar : atum (1.15.2-2.1.4) - 1
• mods_folder Waddles-1.15.2-0.8.6.jar : waddles (1.15.2-0.8.6) - 1
• mods_folder WailaHarvestability-mc1.15.2-1.1.12.jar : wailaharvestability (1.1.12) - 1
• mods_folder ironchest-1.15.2-10.0.3.jar : ironchest (1.15.2-10.0.1) - 1
• mods_folder CraftingTweaks_1.15.2-11.0.1.jar : craftingtweaks (11.0.1) - 1
• minecraft forge-1.15.2-31.2.36-server.jar : minecraft (1.15.2) - 1
• mods_folder cofh_core-1.15.2-0.4.0b.jar : cofh_core (0.4.0b) - 1
• mods_folder ensorcellation-1.15.2-0.4.1b.jar : ensorcellation (0.4.1b) - 1
• mods_folder The-Endergetic-Expansion-1.15.2-v1.3.2.jar : endergetic (1.3.2) - 1
• mods_folder swingthroughgrass-1.15.2-1.4.0.jar : swingthroughgrass (1.15.2-1.4.0) - 1
• mods_folder ToolBelt-1.15.2-1.14.1.jar : toolbelt (1.14.1) - 1
• mods_folder titanium-1.15.2-2.4.2.jar : titanium (2.4.2) - 1
• mods_folder Psi r1.2-83.jar : psi (r1.2-83) - 1
• mods_folder ImmersiveEngineering-1.15.2-4.0.0-117.jar : immersiveengineering (1.15.2-4.0.0-117) - 1
• mods_folder SilentLib-1.15.2-4.6.6+59.jar : silentlib (4.6.6+59) - 1
• mods_folder forbidden_arcanus-1.15.2-1.5.jar : forbidden_arcanus (1.15.2-1.5) - 1
• mods_folder archers_paradox-1.15.2-0.4.0b.jar : archers_paradox (0.4.0b) - 1
• mods_folder ChickenChunks-1.15.2-2.5.0.77-universal.jar : chickenchunks (1.15.2-2.5.0.77) - 1
• mods_folder Atmospheric-1.15.2-1.4.1.jar : atmospheric (1.4.1) - 1
• mods_folder Savage-and-Ravage-1.15.2-1.1.4.jar : savageandravage (1.1.4) - 1
• mods_folder JAOPCA-1.15.2-3.2.0.14.jar : jaopca (3.2.0.14) - 1
• mods_folder serverconfigupdater-1.1.jar : serverconfigupdater (1.1) - 1
• mods_folder FastWorkbench-1.15.2-3.1.1.jar : fastbench (3.1.1) - 1
• mods_folder polymorph-FORGE-1.15.2-0.10.jar : polymorph (FORGE-1.15.2-0.10) - 1
• mods_folder AutoRegLib-1.5-40.jar : autoreglib (1.5-40) - 1
• mods_folder AkashicTome-1.3-13.jar : akashictome (1.3-13) - 1
• mods_folder Quark-r2.1-245.jar : quark (r2.1-245) - 1
• mods_folder Enhanced-Mushrooms-1.15.2-v1.2.2.jar : enhanced_mushrooms ($1.1.0) - 1
• mods_folder StorageDrawers-1.15.2-7.0.2.jar : storagedrawers (1.15.2-7.0.1) - 1
• mods_folder FluxNetworks-1.15.2-5.0.3-4.jar : fluxnetworks (1.15.2-5.0.3-4) - 1
• mods_folder DoubleSlabs-1.15-2.10.1.jar : doubleslabs (2.10.1) - 1
• mods_folder themidnight-0.5.9.jar : midnight (0.5.9) - 1
• mods_folder structurize-0.13.42-ALPHA.jar : structurize (0.13.42-ALPHA) - 1
• mods_folder FastFurnace-1.15.1-3.0.0.jar : fastfurnace (3.0.0) - 1
• mods_folder engineersdecor-1.15.2-1.1.1.jar : engineersdecor (1.1.1) - 1
• mods_folder refinedstorageaddons-0.6.3.jar : refinedstorageaddons (0.6.3) - 1
• mods_folder overloadedarmorbar-4.0.0.jar : overloadedarmorbar (4.0.0) - 1
• mods_folder OpenLoader-1.15.2-4.0.5.jar : openloader (4.0.5) - 1
• mods_folder DefaultOptions_1.15.2-11.0.1.jar : defaultoptions (11.0.1) - 1

**Comment by Doomgull** [comment]
Should probably move the telescope further away from nearby blocks.

**Comment by SampsonnZ** [comment]
I tried in a flat world, but still nothing in the telescope.
[screen record.zip](https://github.com/HellFirePvP/AstralSorcery/files/5172025/screen.record.zip)
![1](https://user-images.githubusercontent.com/9107855/92186888-c2d72a80-ee8a-11ea-91e0-10f82b71d6a2.png)
![2](https://user-images.githubusercontent.com/9107855/92186889-c5398480-ee8a-11ea-85c4-b406a989a232.png)

**Comment by Rithenar** [comment]
SampsonnZ did you figure anything out on this bug? I am experiencing the same issue.

**Comment by SampsonnZ** [comment]
> SampsonnZ did you figure anything out on this bug? I am experiencing the same issue.

Not yet.

**Comment by ThomasElvangMoeller** [comment]
I have had a similar issue with psi, where whenever the psi meter shows on my GUI (like when I hold a tool that uses psi, or my psi is recharging) the telescope is blank, but when the meter is gone the stars show up fine

**Comment by ElahiKeru** [comment]
Hey Everyone, i was having the same issue denoted here and i fixed mine by removing an environmental eye i had equipped which was showing the aura in the vicinity. Just figured i'd add this to help pinpoint cause. For the record Environmental Eye is from the Nature's Aura mod

**Comment by Doomgull** [comment]
Should open tickets on the githubs of these other mods so they properly close their rendering code instead of leaving it spread over others.

**Comment by PolShampon** [comment]
I've tested some things out and this bug is caused by any mod that adds something to your GUI eg. any jetpack from Iron Jetpacks, Environmental Eye from Nature's Aura, the psi meter from Psi, but GUI's from Immersive Engineering, Mekanism and Botania don't affect the telescope

**Comment by ThomasElvangMoeller** [comment]
Just to add to the pile. After unlocking perks when I hold the astral tome it shows my current level on the gui. While the level meter is showing the stars disappear

**Comment by ElahiKeru** [comment]
Another update on my side, I attempted a suggested fix via the author of Nature's Aura:

"If you disable the renderItemsOnPlayer config, does this issue persist?"

This suggestion did NOT correct the behavior in question. Further, In the process of testing this now I find that I cannot see stars regardless of what i do. I even stored my entire inventory, cleared out all of my gear and bauble equips, etc., and could still see no stars in the sky via the telescope at night.

**Comment by Doomgull** [comment]
Anyone with this issue, can you try replicating using the latest 1.12.11 AS release?

**Comment by PolShampon** [comment]
> Anyone with this issue, can you try replicating using the latest 1.12.11 AS release?

The Looking Glass and Telescope work now, tried all the GUI's I could
![2020-11-08_20 47 52](https://user-images.githubusercontent.com/63482321/98481551-b6ad7780-2203-11eb-9ac2-3e5ca754fdbb.png)
