### ISSUE TITLE
Astral Sorcery has failed to load correctly

### ISSUE THREAD

**Issue by Kozatron** [HellFirePvP/AstralSorcery#1378]
This is all it gives me. It's not a traditional crash where it takes me back to the launcher but instead similar to when you try to load the game when you are missing dependencies.

I get the error message, "Astral Sorcery (astralsorcery) has failed to load correctly" underneath that I get the message, "java.lang.NoClassDefFoundError:" and that's it.

the only mods I have installed are: astral sorcery, curios, and observerlib. All 1.15.2

![Screen Shot 2020-09-04 at 11 25 48 AM](https://user-images.githubusercontent.com/70766347/92256305-8e229d80-eea1-11ea-9877-46e607e93399.png)

**Comment by kalkafox** [comment]
What are the contents of `latest.log`?

**Comment by Doomgull** [comment]
Update to latest forge.
