### ISSUE TITLE
QOL issues/bugs?

### ISSUE THREAD

**Issue by Rithenar** [HellFirePvP/AstralSorcery#1379]
When playing 1.12 I used to be able to scroll the tome with W and S to zoom in and out of chapters in tome. Now the search bar in Tome is autoselected so when trying to use the keys they just type repeatedly in the search field
![image](https://user-images.githubusercontent.com/9939332/92308713-744a8e80-ef65-11ea-9001-f3b388307c43.png)
Another issue is that when I am in a specific chapter looking at an entry and I hit the back arrow, it brings me back to the main GUI on the tome instead of the chapter I was reviewing, making it so I have to manually mouse scroll every time I get out of a recipe or entry
https://youtu.be/4NgNW-JNkOk

**Comment by HellFirePvP** [comment]
You can double-click on one of the sections to instantly zoom in.
The forward & backward key-zoom won't make a comeback.

I don't know what resets the zoom and i can't really reproduce the bug. Might be an issue within your pack?

**Comment by scorpion451** [comment]
Is there a strong reason for it to not make a comeback? 
That was more a functionality/accessibility feature than just a quality of life thing for me at least: I find using scroll wheels awkward at best, and my mouse's wheel is not great on top of that. Moving to a new chapter is a 15-20 second process using scroll as opposed to 3 using the old key shortcuts.

**Comment by Doomgull** [comment]
between double-click instant zoom, and search, unlikely. Double-click removes the necessity for an alternate hold-key.

**Comment by Rithenar** [comment]
Thanks for the responses. I am playing a different modpack which is on 1.16.3 so I am ready to test these suggestions when the mod launches for 1.16.3.

**Comment by HellFirePvP** [comment]
Should this continue to be an issue in 1.15.2 or 1.16.4 that the zoom completely resets, reopen/comment again.
