### ISSUE TITLE
Crash when clicking on a constellation in the journal.

### ISSUE THREAD

**Issue by JadeDrgn** [HellFirePvP/AstralSorcery#138]
https://pastebin.com/ngNCc5FM

My game crashes whenever I try to click on the constellation named Discidia. Not sure if it happens with any others as that's the only one I found.

**Comment by HellFirePvP** [comment]
*sigh* alright i'm gonna leave this issue now open so it doesn't get reported 200 more times :P 

This issue is fixed in dev at the moment and the fix will be available when the next version hits.

**Comment by JadeDrgn** [comment]
Oh... sorry about that. I really need to pay more attention to the closed issues :L My bad.
