### ISSUE TITLE
missing textures on Aquamarine shales

### ISSUE THREAD

**Issue by IvorAmlug** [HellFirePvP/AstralSorcery#1380]
![2020-09-06_18 34 12](https://user-images.githubusercontent.com/38656481/92330510-9b8d8280-f06f-11ea-93e8-fdb553e9e0bc.png)
Im using the 1.12.9 version for minecraft version 1.15.2 and the Aquarmarine shales seem to have missing textures.

**Comment by soulerix** [comment]
same problem.. :-(

**Comment by IvorAmlug** [comment]
Well i guess it gets fixed someday.

**Comment by HellFirePvP** [comment]
Remove optifine. This is nothing AS can do anything about.
