### ISSUE TITLE
Issues with collector crystals (1.15.2)

### ISSUE THREAD

**Issue by Prolixitas** [HellFirePvP/AstralSorcery#1381]
I have been trying to use Astral Sorcery in Enigmatica 5 as an addition to the pack. When finding a large shrine with a collector crystal in the underground area of the shrine, I have attempted to turn iron ore in to starmetal ore, and turn a crafting table in to a luminous crafting table. The collector crystal was able to shine on to the crafting table as normal however it is unable to change the table in to a luminous one. I have attempted multiple shrines with multiple crafting tables and none have worked. When using the linking tool on iron ore, the crystal is able to shine on the ore as expected but it also does not transmute the ore in to starmetal.

**Comment by Doomgull** [comment]
Have you uncovered the crystal so no blocks are above it to block the path to the sky, as the Tome says?

**Comment by Prolixitas** [comment]
I had not, sorry for the false report!
