### ISSUE TITLE
[1.15.2] Aquamarine not tagged as a gem using forge tags

### ISSUE THREAD

**Issue by Peach774** [HellFirePvP/AstralSorcery#1383]
there are oredict tags in 1.15 for gems. Aquamarine should be tagged as "forge:gems/aquamarine". This would make it compatible with other aquamarine gems.

**Comment by Doomgull** [comment]
There were oredicts for them in prior versions, too. They weren't included by default for a reason, and pack authors can add them if needed for pack building.
