### ISSUE TITLE
[1.15.2-1.12.9] NullPointerException with Conversion wand

### ISSUE THREAD

**Issue by ThomasElvangMoeller** [HellFirePvP/AstralSorcery#1384]
The crash happened after I had selected a block with the Conversion wand **and** had a StorageDrawer nearby with some items in it.
I tested the wand in a new world without any StorageDrawers and it worked fine.
I am unsure which mod is at fault.
[crash log](https://gist.github.com/ThomasElvangMoeller/e14f7f6c076683b836efe2e7cb8e2afe)
edit: I am using StorageDrawers 1.15.2-7.0.2

**Comment by Doomgull** [comment]
That looks more like a StorageDrawers rendering error, can you clarify if you were replacing things, or was it just a drawer nearby unrelated to what you were doing with the wand?

**Comment by ThomasElvangMoeller** [comment]
I had a drawer nearby and I replaced some grass blocks nearby, And it was at the moment I replaced the grass that i crashed
