### ISSUE TITLE
[1.15.2] No recipes for grindstone and starmetal cutting tool

### ISSUE THREAD

**Issue by theCalcaholic** [HellFirePvP/AstralSorcery#1385]
I just updated to the latest beta ([1.15.2-1.12.9](https://www.curseforge.com/minecraft/mc-mods/astral-sorcery/files/3050832)) and I cannot craft either of the following items:

- astral sorcery grindstone (it's neither in the tome nor JEI - has it beein removed?)
- astral sorcery starmetal cutting tool (it's in the tome and JEI, but the starlight crafting altar won't produce the item, even at full starlight)
- astral sorcery sextant (similar to the grindstone - it's neither in the tome nor JEI)

Also, JEI doesn't show any recipe for the starmetal cutting tool (but for most other astral sorcery items).
I'm playing on the Valhelsia 2 modpack, so there's unfortunately a lot of mods that might conflict with AS.

If I can be of any further help debugging these issues, let me know

**Comment by Doomgull** [comment]
Grindstone and sextant were removed. Ignore jei, use the tome. If it wont craft, something is being done wrong. The discord server is the better avenue for this.
