### ISSUE TITLE
Clicking on the Containment Chalice in JEI while looking at the Iridescent Altar causes crash 1.15.2

### ISSUE THREAD

**Issue by MimirDroid** [HellFirePvP/AstralSorcery#1386]
Self made mod list running under forge-31.2.36

When I have the Iridescent Altar interface open and click on the Containment Chalice in JEI the game immediately crashes.

Link to crash error log [https://pastebin.com/QjGZXEfF](https://pastebin.com/QjGZXEfF)

astralsorcery-1.15.2-1.12.9.jar is the version I am using.

**Comment by MimirDroid** [comment]
Tried this again with  forge-31.2.41 and still had the crash.  I did find that you need to have all the required ingredients in your inventory for the crash to happen.  If you don't have them, it doesn't crash.

**Comment by Fade-Alchemist** [comment]
I can confirm this issue. I have had the same problem
