### ISSUE TITLE
Containment Chalice issues

### ISSUE THREAD

**Issue by KrAzYGEEK32** [HellFirePvP/AstralSorcery#1387]
MC: 1.15.2
Forge: 31.2.36
Mod: 1.12.9

issues:
1. Containment chalice is not pulling from a nearby lightwell as the book suggests, it used to behave this way in 1.12 
2. Containment chalice has a bigger buffer (says 24 buckets in the book) but its definitely bigger

comments:
there is a possibility that the entry isnt updated in the book yet, if that is the case and these above issues are intentional please close the ticket

**Comment by Doomgull** [comment]
Not implemented yet
