### ISSUE TITLE
Vicio mantle elytra flight doesnt work

### ISSUE THREAD

**Issue by KrAzYGEEK32** [HellFirePvP/AstralSorcery#1389]
Mod: 1.12.9
MC: 1.15.2
forge:31.2.36

issue: 
vicio mantle elytra flight is not working.

**Comment by Robertdebrus** [comment]
Did you recently cross dimensions? I've found that it disables sometimes, I've had to unequip mantle, toggle perks, reequip mantle

**Comment by KrAzYGEEK32** [comment]
No, I did not. Although I noticed that as well. I'm using creative flight perk now and when crossing dimensions, I have to re-equip the mantle for it to work

**Comment by Kaioso** [comment]
Version: 1.12.9-1.15.2
Forge: 31.2.41

I am having the same issue. Repeatedly pressing spacebar while in the air does not activate flight.

Attempted with both crafted and spawned in mantle. Personal attunement to Aevitas. Elytra confirmed to work.
Attempted with a new world seed with nothing done. No personal attunement. Full research unlocked.
Attempted with a new world seed with nothing done. No personal attunement. No research. No mods other than Astral Sorcery.

In all cases, tried many different combinations of equipping and unequipping, enabling and disabling perks. As one of the above comments suggested. Elytra was not tested in all cases.

**Comment by HellFirePvP** [comment]
Since the Forge 1.16 elytra changes got pulled into the 1.15 version of forge with forge version 31.2.37, any AS version after that has a broken elytra functionality. I will update to a newer forge version and change the underlying code, also making AS rely on forge 31.2.37+
