### ISSUE TITLE
[1.15.2] AS particles invisible through stained glass

### ISSUE THREAD

**Issue by kalkafox** [HellFirePvP/AstralSorcery#1390]
`1.12.9, v207`

Astral Sorcery particles are not visible through colored glass. As expected, they are indeed visible through regular glass.

![javaw_T9cSonyiPU](https://user-images.githubusercontent.com/9144208/93709010-d62ffa00-fb08-11ea-9d91-55942403efb2.png)

![javaw_OJuLF4976X](https://user-images.githubusercontent.com/9144208/93709013-dc25db00-fb08-11ea-8e35-e725557bcb13.png)

![javaw_4eEZpof4jy](https://user-images.githubusercontent.com/9144208/93709015-de883500-fb08-11ea-810b-a5e632ad8a7c.png)

![image](https://user-images.githubusercontent.com/9144208/93709022-efd14180-fb08-11ea-8df8-9cbefaf2ec7e.png)

**Comment by HellFirePvP** [comment]
Same happens with vanilla particles. Transcluent rendertyped blocks (such as stained glass, ice, nether portal, slime, honey, ...) draw before particles and do write to the depth buffer, thus ignoring things that draw afterwards behind it.
Can't do much about that. Vanilla issue, just place a torch behind stained glass and watch you not seeing particles.
