### ISSUE TITLE
[1.15] Crash while not using the newest forge version

### ISSUE THREAD

**Issue by Cheaterpaul** [HellFirePvP/AstralSorcery#1391]
Because AstralSorcery needs forge 28.2.* (dont know the exact version), it is unreasonable why the mod still accepts even 28.0 [(mods.toml)](https://github.com/HellFirePvP/AstralSorcery/blob/3866824e591b7e2deb1f65e6f9956f39aaf57885/src/main/resources/META-INF/mods.toml#L16) which results in a crash. The log only says NoClassDefFoundError DistExecutor#SafeSupplier, which is no helpfull. So it should be resonable to change the value in the mods.toml to the required forge version to avoid such things.

**Comment by HellFirePvP** [comment]
Right.. Sorry, didn't adjust that yet, will now properly be [31.2,) for a more up-to-date requirement

**Comment by Cheaterpaul** [comment]
its also very helpful to extract those values into a property file like [example](https://github.com/TeamLapen/Vampirism/blob/1.15/gradle.properties). So you only need to edit variables in one file and dont need to search for them.
You can even use the property inside the mods.toml file [mods.toml](https://github.com/TeamLapen/Vampirism/blob/46e8c51c6550d7c6f2c91fe853f04f6af903359c/src/main/resources/META-INF/mods.toml#L19)
