### ISSUE TITLE
[1.15.2] Server keeps disconnecting player

### ISSUE THREAD

**Issue by SuicidalSteve** [HellFirePvP/AstralSorcery#1396]
Decided to post this issue here as well, as Astral Sorcery showed up in the server console.
Link to original issue:
baileyholl/Ars-Nouveau#4

I was trying to make a glyph on a server, and just as I was about to put the TNT in the glyph press for what I vaguely recall was the explosion glyph I shortly saw the message about not having enough mana pop up in the chat, after which it disconnected me. I have been unable to join the server since.

The server didn't crash so there are no crash logs, the client logs don't seem to show anything related to what may have caused the disconnect.
Server console output at time of disconnection:
https://pastebin.com/v8bBJpjb

Versions:

- Forge 31.2.30
- Ars Nouveau 1.15.2 - 0.17.1
- astralsorcery-1.15.2-1.12.9

**Comment by Doomgull** [comment]
That's something client side, looks like. Server is receiving more data than it thinks it should be, so it's kicking off the player. Running anything like Sponge or some sort of plug-in manager?

This isn't exactly a new issue in MC, but it's usually solved by the client using a fresh instance to connect. There's a huge lack of log dump there.
