### ISSUE TITLE
[1.15.2] Astral Sorcery's recipes stop showing in JEI after using /reload

### ISSUE THREAD

**Issue by Unhook** [HellFirePvP/AstralSorcery#1399]
Versions:
Astral Sorcery: 1.15.2-1.12.9
Forge: 31.2.41

Description:
When using /reload, Astral Sorcery's recipes stop showing in JEI. Restarting the game fixes it again.

**Comment by HellFirePvP** [comment]
Test again with 1.12.10 now. I cannot reproduce this bug anymore.

**Comment by Unhook** [comment]
Indeed seems to have been fixed in 1.12.10
