### ISSUE TITLE
Crystal not shining on crafting table

### ISSUE THREAD

**Issue by Redmecha** [HellFirePvP/AstralSorcery#14]
I tried placing a vanilla crafting table next to a crystal in an ancient shrine but the light doesn't go from the crystal to the crafting table and I can't craft the Resonating Wand or Luminous Crafting Table.

I'm using a fairly large mod pack, so I'm guessing one of the mods is changing the vanilla crafting table in some way that's making it AS not see it.

Here's the [Mod list](http://pastebin.com/irpBuKXb) for my [Modpack](https://minecraft.curseforge.com/projects/mechacraft-2).

I'm working on trying to narrow which mod is causing it, if any. I decided i'd post this just in case I can't find it. I'll post an update if I figure it out.

**Comment by VallenFrostweaver** [comment]
Did you try this at night?

**Comment by HellFirePvP** [comment]
This (as one of the few exceptions :P ) can be done during the day aswell. So, it's most likely a mod interaction at work here, but he said he's gonna try narrow it down, so i'm waiting~

**Comment by Redmecha** [comment]
Finally narrowed it down. It seems to be Moving World(The core mod for Davincis Vessels).

**Comment by HellFirePvP** [comment]
Alright - i'll look through his stuff and see what i can find.

**Comment by HellFirePvP** [comment]
I couldn't really find what's causing the issue there... Kinda uncertain if this is fixable, since it'd mean it does add a hook into the chunk system, which i couldn't find. So.... idk.?

**Comment by Nova001Sol** [comment]
I'm having the same issue. However, I don't have Moving World installed. I'll try and figure out what mod does it for me.

**Comment by Nova001Sol** [comment]
Hm... How strange. It seems that on my side this bug is being caused by _VoxelMap_ of all things. Perhaps that is something you could look into?

**Comment by HellFirePvP** [comment]
_lol_ why voxelmap :P Will test that

**Comment by Rosethorns** [comment]
From what I am reading here, am I correct in assuming that /anything/ that hooks into the chunk system has the potential to upset the crystals?

MC: 1.11.2
Forge: 13.20.0.2252
Astral Sorcery: 1.2.0
Modlist: https://docs.google.com/spreadsheets/d/1cHo6_ozPvTp8125BVSYPvI2b9FdP15kCycA87tfdY-E/edit#gid=0

**Comment by HellFirePvP** [comment]
Ouh yea i should mention that this is going to be adressed and most likely fixxed with the next version. Just keeping this open for now.

**Comment by Leowbattle** [comment]
Well for me the light won't shine on the luminous crafting table.

**Comment by HellFirePvP** [comment]
It is not intended to in the 1.11.2 and 1.10.2 versions.

**Comment by Leowbattle** [comment]
I just figured it out after I left the comment. Since you can't get the telescope until you get a lens do you just have to wander around looking for an area with enough starlight?

**Comment by HellFirePvP** [comment]
In 1.10.2/1.11.2 unfortunately so. Or you can try find a good-ish enough one to make some relays and try boosting your starlight collection with that.

However, this is the wrong place to have this discussion, so either open another issue or join AS' discord if you have further questions. https://discord.gg/q37VRcT
