### ISSUE TITLE
Untraceable Constellation in Observatory

### ISSUE THREAD

**Issue by ArtOfCombat** [HellFirePvP/AstralSorcery#1403]
https://i.imgur.com/rzmNSIx.png

This constellation is NOT GELU. The middle is wrong. I cannot trace it, though I know all faint constellations.

Running Win10, AS v. 1.12.2-1.10.24, in MCEternal 1.3.7.1.

**Comment by Doomgull** [comment]
That is gelu. If you have gelu listed in your Tome, you can trace it, as long as you are accurate enough in your tracing.

Please use the discord server for this type of thing next time.
