### ISSUE TITLE
[1.15.x] Make observerlib a required dependency

### ISSUE THREAD

**Issue by cobbkris** [HellFirePvP/AstralSorcery#1404]
Please make **observerlib** a required dependency on CurseForge.  Minecraft throws an error without that mod.

**Comment by Doomgull** [comment]
It...already is.,

![image](https://user-images.githubusercontent.com/12677933/95023478-3ebfc080-064b-11eb-8228-571ffbb9962b.png)

**Comment by cobbkris** [comment]
Weird, it must be how CurseForge relates things, if you go to Astral mod then Relations, it is not listed.  It is indeed there when I click on the file and check where you showed.  Thank you.

![image](https://user-images.githubusercontent.com/34900042/95023777-e2f63700-064c-11eb-9a1c-b58442c621f1.png)
