### ISSUE TITLE
Crash when linking collector crystal to (lava) light well

### ISSUE THREAD

**Issue by Drakoflame** [HellFirePvP/AstralSorcery#1406]
Not entirely sure what happened, but I think that when trying to use the lightwells for making lava, they don't appreciate having blocks over the light well (not ontop of, but a few blocks above), as it crashed the server I was on the instant I linked it to the light well. Log is as follows:

https://pastebin.pl/view/34c80f76

Edit:
Forge 31.2.37
Astral (1.15.2) 1.12.9

**Comment by Doomgull** [comment]
For clarification, you linked a collector crystal to a lightwell that didn't have sky access, and that's when the error occurred?

**Comment by Drakoflame** [comment]
Shoot i'm sorry for not getting back sooner I've been busy and distracted, Yes. The crash only happened after I tried to link the collector crystal to a light well that didn't have direct LoS to the sky, it had some stairs placed over the top of it
