### ISSUE TITLE
Items that need 100% of a celestial altar starlight can not craft

### ISSUE THREAD

**Issue by ghzdude** [HellFirePvP/AstralSorcery#1411]
Trying to craft an item in a celestial altar that requires all of the possible starlight will start the crafting process and immediately stop.
To actually craft the item requires the iridescent altar, when it shouldn't be needed. If you need more info let me know. Discovered while playing FTB Interactions.

**Comment by Doomgull** [comment]
Working as intended. When crafting starts, there is a slight drop in total available starlight to thebaltar as usage and recharge are equal, but like with a battery, there is a slight "sag" in available power.

As far as I know, the only recipe like that in that pack was corrected a while ago.
