### ISSUE TITLE
[Compat] [Bug] "Flare" Mob Bugging with Morph

### ISSUE THREAD

**Issue by Tomodachi94** [HellFirePvP/AstralSorcery#1412]
Heyo,
Found a minor bug with Morph and Astral Sorcery installed.
HOW TO REPRODUCE:

1. Load Minecraft with Astral Sorcery, Morph, and related dependancies
2. /summon and kill a Flare.
3. Morph into a Flare, move around a bit, then morph back into a human.

ISSUE ON MORPH's GITHUB: iChun/Morph#1101

**Comment by Doomgull** [comment]
Not something we support.
