### ISSUE TITLE
Octans ritual appears to do nothing

### ISSUE THREAD

**Issue by MuteTiefling** [HellFirePvP/AstralSorcery#1415]
Version : astralsorcery-1.15.2-1.12.9

Set up an octans ritual in the middle of the ocean. Stood around for about 10 minutes and never saw any fish/loot pop up as expected. Is it that slow? Saw plenty of little smoke particles as if it were doing _something_. Just not clear what. 

Also did not seem to have any impact on my luck while fishing, but that's a bit harder to quantify in such a short period.

**Comment by HellFirePvP** [comment]
Included a fix that should more carefully assess is an entity may exist at a specific position, potentially taking care of this.

**Comment by HellFirePvP** [comment]
Please test again with the new 1.12.10 version.

**Comment by Jeuvke** [comment]
Fish very much drop out of the sky now. I'm not sure if fishing luck increased though, but I haven't tested it much.
