### ISSUE TITLE
[1.15] No way to create luminous crafting table

### ISSUE THREAD

**Issue by stepech** [HellFirePvP/AstralSorcery#1416]
Hello,
using all required libraries with their corresponding versions, even tested on latest:
- Forge: 31.2.35
- ObserverLib: 1.15.2-1.2.0
- Curios: 1.15.2-2.0.2.4 (tested on latest too)
- tested in modpack and also alone

it is impossible or badly described how to craft luminous crafting table. I am actually surprised that after more than a month of 1.15.2 AS version being public, I am the first one to mention it.
I tried method from previous version, as shown on the picture below and I also tried method described in the book - If I understand it correctly, placing it near a crystal should do the trick. Neither of those have worked. Hope it is just in me using wrong crafting recepy, but I can not find anywhere some alternative way to do it.

Solution might be to use some crafting tweaks and create my own recepy for the table, but that will break your mechanic a bit, where I have to find some crystal and craft it near it.

Thanks

![2020-10-16_01 07 45](https://user-images.githubusercontent.com/29132060/96195204-75031700-0f4c-11eb-9773-584ca7c43758.png)
![2020-10-16_01 07 52](https://user-images.githubusercontent.com/29132060/96195206-76344400-0f4c-11eb-8084-86c9f4cc5e75.png)

**Comment by Doomgull** [comment]
Please read the Tome's entry for the Luminous Crafting Table. It's no longer "Crafted", and the crystal needs line of sight to the sky as mentioned in the tome.
