### ISSUE TITLE
Storage Drawer/Formation Wand Crash

### ISSUE THREAD

**Issue by Zypher720** [HellFirePvP/AstralSorcery#1418]
If you allow the formation wands plane modes to display an ethereal sheet of blocks over a storage drawer, the game will immediately crash to desktop. 
[crash-2020-10-18_21.40.20-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/5398776/crash-2020-10-18_21.40.20-client.txt)

**Comment by Doomgull** [comment]
Should be reported to storage drawers, as the crash is triggering on their class.

**Comment by HellFirePvP** [comment]
https://github.com/jaquadro/StorageDrawers/blob/1.15/src/main/java/com/jaquadro/minecraft/storagedrawers/block/BlockDrawers.java#L235

.getPlayer can be null, this is explicitly defined as such. StorageDrawers doesn't check for this as they should. Not an issue on my end.
