### ISSUE TITLE
Aevitas Mantle Improving (As it currently breaks things)

### ISSUE THREAD

**Issue by EStuffs** [HellFirePvP/AstralSorcery#1425]
The Aevitas Mantle currently likes to break light sources created by the illumination wand, makes lenses pop off relays, breaks items that are in lightwells, and traps players underneath them... 
I suggest we make it not a real block technically or something... Some way where it wont effect the world other than when a player stands on it, as these things only get increasingly annoying...

**Comment by yagoplx** [comment]
Cyclic implements this nicely- they have a curio that negates gravity and doesn't affect the world with invisible blocks.
  
Have a look into the code for inspiration, @HellFirePvP, if you must.  
https://github.com/Lothrazar/Cyclic/blob/trunk/1.16/src/main/java/com/lothrazar/cyclic/item/bauble/AirAntiGravity.java

**Comment by HellFirePvP** [comment]
Has now custom block collision for 1.13.7
