### ISSUE TITLE
Problems with textures

### ISSUE THREAD

**Issue by Eduartomx** [HellFirePvP/AstralSorcery#1427]
I have problems with the textures of some blocks and with the interface of the telescope
![2020-11-02_00 13 00](https://user-images.githubusercontent.com/73807800/97826409-42715200-1ca0-11eb-8aff-bb279a214a1d.png)
 
![2020-11-02_00 12 42](https://user-images.githubusercontent.com/73807800/97826432-50bf6e00-1ca0-11eb-8d60-912c5e00f505.png)

**Comment by Doomgull** [comment]
Duplicate to #1380 and #1382 

Stop using optifine in 1.15, it does that to a lot of mods.
