### ISSUE TITLE
crystal won't shine on to the crafting table

### ISSUE THREAD

**Issue by okami465** [HellFirePvP/AstralSorcery#143]
as the title says, the crystal will not shine on the crafting able no matter what i do. i have placed it onto every possible block within the room the crystal spawns in and nothing. i tried the crafting recipes hoping that maybe it's just that the beam wasn't showing but it didn't work. here are the mods I'm using.

https://docs.google.com/spreadsheets/d/16xBp3cfPatOv7ccpGZkJh7GO7jy3PTk4iGJgIALQ7wU/pubhtml

**Comment by HellFirePvP** [comment]
Known to happen due to mods changing the CraftingTable GUI. Maybe have a look at #119 and tell me if that worked. It also only works with the vanilla crafting table. Not necessarily with ones other mods add that are "variants" of the vanilla table.

**Comment by okami465** [comment]
I am using the vanilla crafting table and the GUI for it is still the same as vanilla. The closest thing to the gui changing is the jei menu covering the right side of the screen

**Comment by Doomgull** [comment]
Doesn't matter if vanilla crafting table, if you have a mod installed that alters vanilla crafting tables mechanics in some way, it can happen.

**Comment by okami465** [comment]
Hmm. Vanila magic has a feature where you can hold a crafting table, right click, and access it without needing to place it down. Could that be causing it?

**Comment by Saereth** [comment]
confirmed busted: http://imgur.com/a/zNZoC
Vanilla magic + astral sorcery only, VM does break the AS changes to the table.

**Comment by okami465** [comment]
Ok, so all I need to do is remove vanilla magic, craft the 2 items the crystal is needed for, then just put vm back in? ( Vm is a mod that I find very useful and I would like to keep it at all costs)

**Comment by Saereth** [comment]
Technically, yeah that should work once you have the luminous table and wand you dont really need that mechanic anymore

**Comment by okami465** [comment]
Well crap. I got rid of vanilla magic but it's still not working. I don't know what else could be affecting it

**Comment by Saereth** [comment]
Uh, I think there might be some bigger issue here @HellFirePvP I removed Vanilla magic from my instance only mods are AS, journeymap and JEI and it isn't shining onto the crafting table. This is 1.11 MC instance with the latest build 1.3.2-beta.

**Comment by HellFirePvP** [comment]
Only collector crystals in structures will do the auto-link. Player-placed ones won't auto-link (this is to prevent potentially malicious behavior of users placing tens of crafting tables close to one of your setups and preventing 90% of all starlight transmitted :P)

**Comment by HellFirePvP** [comment]
So, uh. What about this issue now?

Regarding light-shining-on-crafting-table recipes, that's been slightly changed next version to potentially allow for more compatibility. I'll see how that'll work out. As for "the **structural** collector crystal doesn't link to the table at all": i'm uncertain if i can do something about that in the respective case.
