### ISSUE TITLE
Broken Projectiles and Crash /w iYAMATO's Mob Mod

### ISSUE THREAD

**Issue by ALJ323** [HellFirePvP/AstralSorcery#1434]
Minecraft 1.12.2
Astral Sorcery v1.10.27
iYAMATO's Mob Mod v0.2.1

No other mods involved.
Astral Sorcery prevents iYAMATO weapons from firing projectiles all together and throws errors, and crashes all together when using the Pulse Rifle and Flamethrower. Occurs consistently with all levels of the weapons. Does not affect the Stasis Module, Javelin Gun or Javelin Gun alt-fire.

Hotbar of the mod's weapons.
https://i.imgur.com/pB4RGE3.png

Crashlog
https://paste.ee/p/cm0Dc

**Comment by HellFirePvP** [comment]
Not my fault.
Simply query'ing if the shot projectile, which is an arrow supposedly, is set to be a critical hit or not. Any arrow-like entity has to support calling this method, which this apparently doesn't.
