### ISSUE TITLE
incompatibility with Dungeons Gear

### ISSUE THREAD

**Issue by aycfes** [HellFirePvP/AstralSorcery#1435]
according to the author of dungeons gear, it is because of the order at which the reach extending mixins are loaded or something similar, and he's not sure weather it's possible to fix it in 1.15, so, if only so you're aware, i'm posting it here.

[latest.log](https://github.com/Thelnfamous1/Dungeons-Gear/files/5494047/latest.log)
[debug.log](https://github.com/Thelnfamous1/Dungeons-Gear/files/5494049/debug.log)
[crash-2020-11-05_17.38.24-client.txt](https://github.com/Thelnfamous1/Dungeons-Gear/files/5496571/crash-2020-11-05_17.38.24-client.txt)

edit: also, this is probably already reported, but i might as well mention it; when optifine is installed, many of the blocks, such as the ores, crystals, and the prism become black and purple boxes, mussing both texture and model.

**Comment by Thelnfamous1** [comment]
I can fix it on my end, no need to worry about it. All I have to do is use forge's key input events to handle extended attack reach. I do wonder if I will also need to do this for the 1.16 versions.

**Comment by HellFirePvP** [comment]
AS specifically picks the 2 LDC instructions that load the constants into memory and the setting of the overreach check flag  and replaces those with method calls.
Not one of the most compatible injections if you're specifically picking those variable instructions, but i'm not sure if there's a good solution for this to be honest. Also don't know how surgically you can pinpoint select or search specific instructions in a method to target this?

Regarding optifine:
Yep. 1.15.2 issue of optifine not supporting forge block models. Can't do much about it, remove optifine if it's bothersome.
