### ISSUE TITLE
[suggestion] Crossbow refraction table enchantments

### ISSUE THREAD

**Issue by KobeCollison** [HellFirePvP/AstralSorcery#1437]
As of right now, when using astral to fully deck out your gear, It's hard for crossbows to keep up with bows. The damage boost+projectile speed is amazing, but bows get the same and more since they can get that power 7(11+ with a good amulet and perks). It would be cool to add some enchantments to the crossbow with the refraction table. The vanilla max for quick-charge is 3 and after level 5, there is no point in adding more. Maybe **Vicio could provide quick charge 2-4** and let a prism do the rest. **Quick charge could be added to Pelotrio and multishot could go to either Pelotrio or Vorux**. Those enchantments could be officered in the refraction table to override that and make both usable at the same time. This would separate Astral's endgame ranged weapons, leaving bows as the damage powerhouses and crossbows as the ultimate crowd clearers.

**possible tome entry changes for constellations:**
Evorsio  - "...Haste. Enchanted tools have greatly improved Efficiency, and crossbow bolts gain Piercing capabilities."
Vicio  - "...Speed. Enchanted boots greatly reduce damage from falling, and crossbow strings can be drawn effortlessly."
Pelotrio - "...to fish. Enchanted ranged weapons fire relentlessly. Bows have infinite ammunition, and crossbows can fire multiple shots at a time. "

( it would also make sense if quick-charge and multishot to be combined into Vorux (maybe even piercing too) )
Vorux - "...they strike. Enchanted crossbows react violently, firing at a faster rate, firing multiple shots at a time (, and piercing through targets with its ammunition)"

I tried to keep all the constellation suggestions in line with their themes.

**Comment by MuricanSWAG** [comment]
Whoops, posted this on the wrong account. ¯\_(ツ)_/¯

**Comment by Doomgull** [comment]
This has been talked about internally a bunch, will see about an update.
