### ISSUE TITLE
Constellation info in tome incomplete

### ISSUE THREAD

**Issue by Jeuvke** [HellFirePvP/AstralSorcery#1441]
The tome entries for every constellation are missing the page about the mantle effect and the corrupted ritual effect.
Edit: after upgrade from 1.12.10

**Comment by Doomgull** [comment]
Testing in Discord determined there was a trigger state missing from the player data file, and so the information did not show. Correcting this via command to cause the information to show properly. Will keep this open for a couple days to see if anyone else has a similar issue.
