### ISSUE TITLE
Dynamism gems are active when held.

### ISSUE THREAD

**Issue by Jeuvke** [HellFirePvP/AstralSorcery#1442]
But only in the main hand, not in the offhand. The tome says they need to be put in a gem socket to be active, so I don't think this is intended.

**Comment by Doomgull** [comment]
Which AS version?

**Comment by Jeuvke** [comment]
1.15.2-1.12.11

**Comment by Doomgull** [comment]
Updating here from discord, intended behavior when held in main-hand only.
