### ISSUE TITLE
Color of paper

### ISSUE THREAD

**Issue by WisterOnline** [HellFirePvP/AstralSorcery#1443]
Please i need help, for some reason the constellation paper became green, and i can't even know what are the constellations
![image_2020-11-10_122246](https://user-images.githubusercontent.com/65360588/98667951-722ef280-234f-11eb-87fb-dad3e3d19cfb.png)

**Comment by Doomgull** [comment]
Another mod is not cleanly handling its render code. You will have to determine which mod is causing thr conflict and open a ticket on their side.

**Comment by WisterOnline** [comment]
I play on the modpack ftb academy and the problem start when i logged in, last time i played the problem was not there

**Comment by Doomgull** [comment]
Doesn't change what I said. It isn't AS causing the issue.

**Comment by HellFirePvP** [comment]
Most likely whichever mod adds the overlay on the right.

**Comment by HellFirePvP** [comment]
As was stated previously, this is most likely the result of the overlay on the right side.
