### ISSUE TITLE
Talent issues

### ISSUE THREAD

**Issue by Lederrr** [HellFirePvP/AstralSorcery#1444]
Minecraft version 1.12.2
AS version 1.10.27
The talents are not displayed in the journal. In fact, they are there, but there is no texture. How can I fix it? What mods can get in the way?
![2020-11-10_18 56 34](https://user-images.githubusercontent.com/47238606/98699811-8f33e780-2388-11eb-870b-869838691103.png)
![2020-11-10_19 12 50](https://user-images.githubusercontent.com/47238606/98699986-c1454980-2388-11eb-8444-d109ae47242d.png)

**Comment by Doomgull** [comment]
Someone is doing very bad things with UI code and rendering, this is not an AS issue, but would need to remove mods to determine what is causing this.
