### ISSUE TITLE
Shale missing texture

### ISSUE THREAD

**Issue by Unusual-Danger** [HellFirePvP/AstralSorcery#1445]
I was playing A.S. in a new world. When I went out looking for shale I noticed that it was the bugged pink and black texture.
My version is 1.15.2
Another mod that I have installed that might be interfering with it is Tropicraft
My forge version is: 1.15.2-forge-31.2.45
The A.S. version is: 1.15.2-1 12. 11
Is this a version bug or an error?

**Comment by Doomgull** [comment]
It's optifine.

Duplicate to #1380
