### ISSUE TITLE
I think NBT data issue with large amounts of rock crystals, in containers, in a single chunk causes tps issues

### ISSUE THREAD

**Issue by DoomSquirter** [HellFirePvP/AstralSorcery#1446]
astralsorcery-1.12.2-1.10.27
ActuallyAdditions-1.12.2-r151-2
playing po3 kappa latest

I include aa version cause I was storing the crystals in the very large crates

I veinmined about 4 stacks of crystal ore and placed in about 5 of the large crates, each in a line, feeding the lightwells

server eventually crashed and when server comes up, it'd be at 6tps-8tps.  we looked at numerous things trying to figure out the problem and I decided to void all the crystals in all the chests, and server promptly came back to 20tps rather quickly.

I'm fairly certain, this is an issue completely out of your hands cause it probably has to do with too much nbt data in a chunk or something, so this isn't a request for help but just to let you know about this.

Thanks for the beautiful mod

**Comment by b0bst3r** [comment]
To give you some context on the container, it stores 13  columns by 9 rows over 3 pages, that's 351 Rock Crystals in a single block and Doom being Doom had 5 such containers.  So that's 1,755 Rock Crystals in the 5 containers in the chunk basically brought the server to its knees.

**Comment by DoomSquirter** [comment]
what I have learned in the last hr from mod dev friends is that if a chunk's nbt data goes over 64kb, the chunk will reset.  so I'm assuming i might have been close to that number or something?  that chunk would have just poofed out of existance if it passed that threshold.

**Comment by DoomSquirter** [comment]
also, I want to make it extremely crystal clear that the reason I did all of this was because a simple mechanical miner couldn't mine the ore as needed and supply the crystals that way cause it's intended that they be hard, if not impossible, to automate by design.

**Comment by HellFirePvP** [comment]
That issue overall is not specific to AS but to minecraft overall at this point.
