### ISSUE TITLE
CTD when hitting sheep with fist

### ISSUE THREAD

**Issue by Hiranus** [HellFirePvP/AstralSorcery#1451]
Title says it all. 

https://pastebin.com/UqJjHZNr

**Comment by Doomgull** [comment]
Please replicate with "dummmmmmy" removed.

**Comment by Hiranus** [comment]
Weird thing is, I can't reproduce it even with "dummy" mod. This is thread issue so it can be hard to reproduce to begin with, and I just had enough bad luck.

**Comment by Doomgull** [comment]
There'll be some code added to help try to protect against this in the future anyway.

**Comment by Hiranus** [comment]
Great, thanks. For now I will be playing without dummy mod. Can you give rough estimate when this modification will be implemented?

**Comment by HellFirePvP** [comment]
This is due to concurrent access to the same perk map; the player's key input runs on a GL spawned contextthread, so that might run into issues like this occasionally. this was already found in testing, fixed for next update.
