### ISSUE TITLE
Companion flares might need more vertical speed

### ISSUE THREAD

**Issue by yagoplx** [HellFirePvP/AstralSorcery#1454]
I was towering up high in a hurry, when I noticed that I sometimes couldn't place a block under me because my companion flare was still ascending and overlapped with the block to be placed. I think this might happen with bootes flares too.

This was on a big pack (E2E), so maybe there was some weird tickrate issue, but I didn't notice anything out of the ordinary, especially since I'm on singleplayer and in the wilderness.

**Comment by Doomgull** [comment]
The patreon flares aren't entities, but a particle, so not possible for them to do this. "normal" flares can, as they are an entity.

**Comment by yagoplx** [comment]
Weird tickrate issue it is then. I added some more mods recently, so that might just be it.

**Comment by yagoplx** [comment]
Culprit was https://www.curseforge.com/minecraft/mc-mods/performant

Avoid using it if you don't like block lag, I guess.
