### ISSUE TITLE
(FTB interactions) locked out of attunement gate to minor constellations

### ISSUE THREAD

**Issue by iah11** [HellFirePvP/AstralSorcery#1455]
I had my world corrupted, and rebuilt it. Because of this, I cheated in a luminous crafting table. However, while not gating attunement, it doesn't allow the player to access any attunement stuff other than the tree. this includes discovering minor constellations and seeing the attunement of things like rock crystals. (I have now crafted the table, but after original attunement) I tried a shifting star, and that didn't work. 

Also: Is there any way to fix this by commands?

**Comment by yagoplx** [comment]
At least on 1.12.2, you can do:
`/astralsorcery maximize @s`

This will give you all the knowledge. In the same way,
`/astralsorcery reset @s`

will put you back in the beginning.

**Comment by yagoplx** [comment]
Might want to look into getting some backup mod/software, they're real sweet when they're automatic.

**Comment by Doomgull** [comment]
The problem is you don't have progression unlocked for yourself. Progression is gated behind the various altars being crafted.

The command series `/as help` can be used to see all the options for commands. I would recommend just re-crafting the Luminous Crafting Table normally, however.
