### ISSUE TITLE
The telescope omits showing some constellations if there are 9 or more constellations in the sky that night

### ISSUE THREAD

**Issue by Jeuvke** [HellFirePvP/AstralSorcery#1457]
version 1.15.2-1.12.12
Pretty rare, but very frustrating when it happens with a rare constellation.

(My 9th constellation this night was Horologium. I hadn't traced it yet q.q)

**Comment by HellFirePvP** [comment]
That is indeed the thing the telescope does. Show up to 8 constellations at random per night, 1 per direction.
