### ISSUE TITLE
Small Shrines no chests.

### ISSUE THREAD

**Issue by Venomia** [HellFirePvP/AstralSorcery#1462]
I added Astral Sorcery to Valhesia 2 and went exploring.. found 2 small shrines but no chest... did something change on 1.15.2?
![image](https://user-images.githubusercontent.com/62031601/99355668-67c1ab00-28b1-11eb-9cb1-6640ceabe92c.png)

**Comment by HellFirePvP** [comment]
Yea, they have chances of generating one or multiple chests.
You unfortunately just got unlucky.
