### ISSUE TITLE
AS Perks Tab

### ISSUE THREAD

**Issue by KumaSamaVII** [HellFirePvP/AstralSorcery#1463]
![2020-11-17_04 03 21](https://user-images.githubusercontent.com/42952591/99369662-b4de5680-288a-11eb-8e1a-ff42dd197856.png)

How Fix???

**Comment by Doomgull** [comment]
What version of AS?

**Comment by KumaSamaVII** [comment]
AstralSorcery-1.12.2-1.10.27.jar

**Comment by Doomgull** [comment]
That looks to be a mod interaction. There's a lot of UI elements being added on that screenshot.

**Comment by KumaSamaVII** [comment]
I removed RPG-HUD and it solved the issue and also another issue i was having with the telescope so theres defintely a conflict there.

**Comment by Doomgull** [comment]
UI level fighting, most likely. Ticket should be opened for them for a doublecheck.
