### ISSUE TITLE
Impulsion wand bug

### ISSUE THREAD

**Issue by 500m1n** [HellFirePvP/AstralSorcery#1466]
1.15.2-1.12.9

If a player with an active impulsion wand dies. The effect of the impulsion wand stays within the client.
Confirmed that it's not affecting other players.

Has that been addressed in a newer update? In 1.15.2

**Comment by Jeuvke** [comment]
I'd recommend checking to see if 1.15.2-1.12.12 fixes it.

**Comment by HellFirePvP** [comment]
![image](https://user-images.githubusercontent.com/7419378/99877423-6b7d6680-2bfe-11eb-9693-7ed740c723c1.png)

After a player's death, the server does not send entity updates to that client. So, i'll adjust it so it doesn't pull the dead clientplayer, but removing & updating is the server's responsiblity.
As can be seen on the screenshot, the entities are not alive anymore on serverside, however their death/updates are not synced. As far as that goes, it's a vanilla behavior.

**Comment by HellFirePvP** [comment]
That being said, it doesn't pull a clientplayer. Just still exists. So i'm not sure what exactly is being referenced as issue here.

**Comment by 500m1n** [comment]
Ahh My apologies. I forgot to note that the player has to be in the same
chunk w/ other players. So that your entities don’t purged on death.

I’ll try to recreate the issue with my server and find out what exactly is
going on and how’s it’s being triggered.

**Comment by 500m1n** [comment]
I have recorded a video showing the bug. https://www.youtube.com/watch?v=z8sdyY62MGg
We're going to update the server and see if the issue is prevalent tomrorow.

**Comment by HellFirePvP** [comment]
Ah i see.
Yep this is broken on the mod's side and i'll fix that with the next update.

Thank you for the report and your patience.

**Comment by HellFirePvP** [comment]
1.16.4: Fixed with version 1.13.3

**Comment by HellFirePvP** [comment]
1.15.2: Fixed with version 1.12.14
