### ISSUE TITLE
father falling lev 0

### ISSUE THREAD

**Issue by modman484** [HellFirePvP/AstralSorcery#1467]
when i enchanted my Dimond boots with 3 vicio on the Steller refraction table is this a bug

**Comment by modman484** [comment]
15.2, also i have create installed

**Comment by Doomgull** [comment]
What version of Astral Sorcery?

**Comment by modman484** [comment]
1.15.2-1.12.12

**Comment by modman484** [comment]
![2020-11-20_14 50 05](https://user-images.githubusercontent.com/74793637/99851807-bbe8bb80-2b4d-11eb-91a6-2d8c10e0776e.png)

**Comment by HellFirePvP** [comment]
Fixed with
1.15.2-1.12.13
1.16.4-1.3.1
