### ISSUE TITLE
[1.16.4] Dedicated Server Crash

### ISSUE THREAD

**Issue by TwilightPSN** [HellFirePvP/AstralSorcery#1468]
Got all excited to add this to my modpack im working on and have a dedicated server crash.

https://gist.github.com/TwilightPSN/cf423314760e29a7a4d5822bc086391c

**Comment by Doomgull** [comment]
Adding another crash instance reported on discord:

https://gist.github.com/Doomgull/e4f2e7e6a8a4a43ca84b92f4bd3aee94

**Comment by dheivs** [comment]
Hi, I also have a crash log for 1.16.4.  It happened when an Ice Enderman tries to attack me.
Here you go: https://pastebin.com/9ccwmGuf
Just going to put this here to avoid spamming. Nice Mod SIR!!! I've been waiting for this to be in 1.16.4 for a long time.
