### ISSUE TITLE
can't create luminous crafting table

### ISSUE THREAD

**Issue by Warbringer12** [HellFirePvP/AstralSorcery#1469]
giant loop bug in the creation of a luminous crafting table
![2020-11-20_15 58 41](https://user-images.githubusercontent.com/44590540/99860942-7f1ac580-2b49-11eb-9c73-57a8b0f92f32.png)
![2020-11-20_15 58 45](https://user-images.githubusercontent.com/44590540/99860944-7fb35c00-2b49-11eb-9f29-ae0dd8d9bd13.png)
![2020-11-20_16 00 02](https://user-images.githubusercontent.com/44590540/99860948-80e48900-2b49-11eb-8fd4-203ab692270a.png)
![2020-11-20_15 58 47](https://user-images.githubusercontent.com/44590540/99860946-804bf280-2b49-11eb-9a82-2c1c96f05da1.png)

can't create luminous crafting table at all

**Comment by Doomgull** [comment]
You're misunderstanding how JEI works.

Place a crafting table within a few spaces of a crystal in a shrine after uncovering the crystal like the tome says. Just use the book.

**Comment by Warbringer12** [comment]
you cant use the book or the resonating wand to make the table at all

**Comment by Doomgull** [comment]
Go to the discord,you can get real time help there.
