### ISSUE TITLE
Crash when I click on a constellation in the book

### ISSUE THREAD

**Issue by fflortix** [HellFirePvP/AstralSorcery#147]
Hi,
I has click on a constellation in the book and the play have crashed.
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.62+beta.86.jar)
  BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.4.jar)
  AstralCore (astralsorcery-1.3.2-beta.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 4/28/17 9:30 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at hellfirepvp.astralsorcery.client.gui.GuiJournalConstellationDetails.buildLines(GuiJournalConstellationDetails.java:79)
	at hellfirepvp.astralsorcery.client.gui.GuiJournalConstellationDetails.<init>(GuiJournalConstellationDetails.java:69)
	at hellfirepvp.astralsorcery.client.gui.GuiJournalConstellationCluster.func_73864_a(GuiJournalConstellationCluster.java:274)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:544)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1695)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at hellfirepvp.astralsorcery.client.gui.GuiJournalConstellationDetails.buildLines(GuiJournalConstellationDetails.java:79)
	at hellfirepvp.astralsorcery.client.gui.GuiJournalConstellationDetails.<init>(GuiJournalConstellationDetails.java:69)
	at hellfirepvp.astralsorcery.client.gui.GuiJournalConstellationCluster.func_73864_a(GuiJournalConstellationCluster.java:274)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:544)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)

-- Affected screen --
Details:
	Screen name: hellfirepvp.astralsorcery.client.gui.GuiJournalConstellationCluster

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['fflorti'/274, l='MpServer', x=78.44, y=64.00, z=226.62]]
	Chunk stats: MultiplayerChunkCache: 286, 286
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (166,64,210), Chunk: (at 6,4,2 in 10,13; contains blocks 160,0,208 to 175,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 133034 game time, 128839 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 50 total; [EntityBat['Chauve-souris'/3846, l='MpServer', x=120.58, y=40.73, z=270.34], EntityBat['Chauve-souris'/3852, l='MpServer', x=77.64, y=18.17, z=255.34], EntityBat['Chauve-souris'/3853, l='MpServer', x=60.50, y=17.49, z=188.80], EntityBat['Chauve-souris'/3473, l='MpServer', x=124.21, y=43.03, z=293.56], EntityPlayerSP['fflorti'/274, l='MpServer', x=78.44, y=64.00, z=226.62], EntitySkeleton['Squelette'/3860, l='MpServer', x=87.50, y=14.00, z=173.50], EntitySkeleton['Squelette'/3861, l='MpServer', x=86.50, y=14.00, z=173.50], EntityBat['Chauve-souris'/3990, l='MpServer', x=22.93, y=17.02, z=201.20], EntityZombie['Zombie'/3864, l='MpServer', x=125.49, y=31.00, z=241.81], EntityZombie['Zombie'/3865, l='MpServer', x=124.70, y=30.00, z=245.63], EntitySkeleton['Squelette'/3866, l='MpServer', x=122.50, y=30.00, z=247.50], EntitySkeleton['Squelette'/3867, l='MpServer', x=124.50, y=30.00, z=246.50], EntitySpider['Araignée'/3995, l='MpServer', x=103.50, y=27.00, z=264.50], EntityCreeper['Creeper'/4005, l='MpServer', x=71.50, y=17.00, z=168.81], EntityCreeper['Creeper'/4006, l='MpServer', x=72.50, y=17.00, z=169.50], EntityCreeper['Creeper'/4007, l='MpServer', x=73.50, y=17.00, z=169.50], EntityZombie['Zombie'/2735, l='MpServer', x=5.50, y=38.00, z=187.50], EntityBat['Chauve-souris'/4017, l='MpServer', x=89.53, y=33.00, z=287.45], EntityBat['Chauve-souris'/4018, l='MpServer', x=90.93, y=32.41, z=283.46], EntityBat['Chauve-souris'/2869, l='MpServer', x=91.25, y=47.10, z=260.35], EntityPig['Cochon'/60, l='MpServer', x=77.50, y=66.00, z=276.32], EntityPig['Cochon'/61, l='MpServer', x=83.30, y=68.00, z=274.50], EntityPig['Cochon'/62, l='MpServer', x=78.25, y=70.00, z=269.51], EntityPig['Cochon'/63, l='MpServer', x=73.25, y=66.00, z=266.52], EntityWitch['Sorcière'/3909, l='MpServer', x=103.99, y=16.21, z=268.30], EntityPig['Cochon'/71, l='MpServer', x=76.61, y=62.27, z=235.45], EntityPig['Cochon'/72, l='MpServer', x=100.81, y=64.00, z=220.77], EntityBoat['Bateau'/2124, l='MpServer', x=58.86, y=62.52, z=206.31], EntityZombie['Zombie'/3535, l='MpServer', x=118.50, y=21.00, z=251.50], EntityCreeper['Creeper'/3922, l='MpServer', x=20.50, y=18.00, z=268.50], EntitySkeleton['Squelette'/3924, l='MpServer', x=99.50, y=41.00, z=278.50], EntityEnderman['Enderman'/3925, l='MpServer', x=74.50, y=29.00, z=248.50], EntityCreeper['Creeper'/3926, l='MpServer', x=74.50, y=29.00, z=250.50], EntityZombie['Zombie'/3161, l='MpServer', x=80.50, y=17.00, z=182.50], EntityPig['Cochon'/90, l='MpServer', x=128.78, y=69.00, z=214.51], EntityPig['Cochon'/91, l='MpServer', x=127.15, y=65.00, z=244.70], EntityPig['Cochon'/92, l='MpServer', x=110.50, y=70.00, z=259.23], EntityPig['Cochon'/93, l='MpServer', x=115.26, y=65.00, z=291.85], EntityBat['Chauve-souris'/3935, l='MpServer', x=72.25, y=28.05, z=304.61], EntityZombie['Zombie'/3424, l='MpServer', x=72.50, y=30.00, z=258.50], EntityPig['Cochon'/99, l='MpServer', x=130.45, y=67.00, z=210.43], EntityPig['Cochon'/100, l='MpServer', x=129.26, y=67.00, z=269.52], EntitySkeleton['Squelette'/3684, l='MpServer', x=76.50, y=37.00, z=286.50], EntityPig['Cochon'/101, l='MpServer', x=140.94, y=66.00, z=259.50], EntityPig['Cochon'/102, l='MpServer', x=141.83, y=66.00, z=277.75], EntityCreeper['Creeper'/3687, l='MpServer', x=153.48, y=26.00, z=260.78], EntityCreeper['Creeper'/3688, l='MpServer', x=152.50, y=29.00, z=256.50], EntityBat['Chauve-souris'/3817, l='MpServer', x=154.08, y=28.54, z=224.75], EntityZombie['Zombie'/3948, l='MpServer', x=74.28, y=23.00, z=242.49], EntityPig['Cochon'/111, l='MpServer', x=145.49, y=66.00, z=269.22]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:393)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 252486328 bytes (240 MB) / 762523648 bytes (727 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.38 Powered by Forge 13.20.0.2285 Optifine OptiFine_1.11.2_HD_U_B7 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2285.jar) 
	UCHIJAAAA	forge{13.20.0.2285} [Minecraft Forge] (forge-1.11.2-13.20.0.2285.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJAAAA	astralsorcery{1.3.2-beta} [Astral Sorcery] (astralsorcery-1.3.2-beta.jar) 
	UCHIJAAAA	betterfoliage{2.1.4} [Better Foliage] (BetterFoliage-MC1.11.2-2.1.4.jar) 
	UCHIJAAAA	guidebook{1.7.0} [Guide Book] (Guide-Book-Mod-1.11.2.jar) 
	UCHIJAAAA	inventorytweaks{1.62+beta.86.e69c6bf} [Inventory Tweaks] (InventoryTweaks-1.62+beta.86.jar) 
	UCHIJAAAA	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCHIJAAAA	treechopper{1.1.2} [Tree Chopper] (TreeChopper-1.11.2-1.1.2.jar) 
	UCHIJAAAA	veinminer{0.35.3} [Vein Miner] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	UCHIJAAAA	veinminermodsupport{0.35.3} [Mod Support] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.62+beta.86.jar)
  invtweaks.forge.asm.ContainerTransformer
BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.4.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
AstralCore (astralsorcery-1.3.2-beta.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4358' Renderer: 'Intel(R) HD Graphics 4000'
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2285
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.4358, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Français (France)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
	OptiFine Version: OptiFine_1.11.2_HD_U_B7
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.4358
	OpenGlRenderer: Intel(R) HD Graphics 4000
	OpenGlVendor: Intel
	CpuCount: 4`

**Comment by HellFirePvP** [comment]
There's even an open issue with almost exactly the same title as this. please look at least at open issues before reporting something duplicate.
