### ISSUE TITLE
Crash when starting up Minecraft

### ISSUE THREAD

**Issue by lartts** [HellFirePvP/AstralSorcery#1471]
I am currently using Astral Sorcery 1.12.2-1.10.27 and I keep getting this bug

Crash report:

https://pastebin.pl/view/e3ba5f3d

**Comment by HellFirePvP** [comment]
Could i get a full log please?

**Comment by lartts** [comment]
Sure
https://pastebin.pl/view/f41f74e8

**Comment by PocketfulOfGeese** [comment]
"net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: thaumcraft.common.lib.events.EntityEvents" not AS.
