### ISSUE TITLE
Cacti can grow through blocks when in range of an Aevitas ritual

### ISSUE THREAD

**Issue by Jeuvke** [HellFirePvP/AstralSorcery#1473]
1.15.2-1.12.12
![2020-11-20_14 24 34](https://user-images.githubusercontent.com/73312791/99879709-cd45cc80-2c0e-11eb-879c-57dea690730d.png)

**Comment by HellFirePvP** [comment]
Fixed with
1.15.2-1.12.13
1.16.4-1.3.1
