### ISSUE TITLE
Resonating Wand not emitting particles 

### ISSUE THREAD

**Issue by Unusual-Danger** [HellFirePvP/AstralSorcery#1474]
I was playing Minecraft 1.12.2 and had AC installed. When I had the Resonating Wand I didn’t show rock crystals. I do currently have Optifine installed.
Version: 1.10.19
Another mod I think might be interfering with AC is Westher2 Mod. I don’t know if the wand works in the rain since sometimes it “rains” without it being visual.
It is also not part of a modpack. 
Is there any way to fix this?

**Comment by Unusual-Danger** [comment]
Just tried it without Optifine but still no change

**Comment by Doomgull** [comment]
AS 1.10.9 is a year and a half out of date. Update the mod to latest please.

Also, make sure it is night time when you are looking for the plumes, that worldgen for the rock crystals is enabled in the mod config, and you are looking over a large enough area.

**Comment by Unusual-Danger** [comment]
Solved: For some reason no crystals generated in my area even though they were new chunks. I just went a little farther out and it started to work.
