### ISSUE TITLE
Celestial Gateways dyed black are practically invisible

### ISSUE THREAD

**Issue by Jeuvke** [HellFirePvP/AstralSorcery#1476]
1.15.2-.1.12.13
![2020-11-22_14 02 49](https://user-images.githubusercontent.com/73312791/99904568-f710f900-2ccb-11eb-832e-70690ec147da.png)
![2020-11-22_14 02 59](https://user-images.githubusercontent.com/73312791/99904569-f8422600-2ccb-11eb-8f98-012ea71a9b11.png)

**Comment by HellFirePvP** [comment]
1.16.4: Fixed with version 1.13.3

**Comment by HellFirePvP** [comment]
1.15.2: Fixed with version 1.12.14
