### ISSUE TITLE
The text on the star of a renamed Celestial Gateway is unreadable

### ISSUE THREAD

**Issue by Jeuvke** [HellFirePvP/AstralSorcery#1478]
1.15.2-1.12.13
I have pretty good eyes, but I sure can't read that.
![image](https://user-images.githubusercontent.com/73312791/99904705-0b092a80-2ccd-11eb-85f3-ee33639334c2.png)
![image](https://user-images.githubusercontent.com/73312791/99904711-2411db80-2ccd-11eb-9e9f-f10efd13fc61.png)

**Comment by HellFirePvP** [comment]
1.16.4: Fixed with version 1.13.3

**Comment by HellFirePvP** [comment]
1.15.2: Fixed with version 1.12.14
