### ISSUE TITLE
The Lucerna ritual does not prevent all hostile mob spawns

### ISSUE THREAD

**Issue by Jeuvke** [HellFirePvP/AstralSorcery#1479]
1.15.2-1.12.13
Zombies from zombie sieges, pillagers from pillager patrols, and phantoms still spawn in the area of an active Lucerna ritual.

Some other hostile mobs can also still spawn, but I assume this is intended. Namely:
-Raid mobs from raids
-Zombie pigmen from nether portals
-Any hostile mob from monster spawners

**Comment by Doomgull** [comment]
The point is that things like vanilla spawners and the like still function, and only cancels the wild spawns. Things like zombie sieges, Pillager raids, and Phantoms bypass the normal spawn restrictions in vanilla, so they still get to spawn.

A defensive-minded ritual would be the recommendation for things that are intended to be actual assaults, such as Armara, or Discidia.

**Comment by HellFirePvP** [comment]
Anything except random world spawning does not fire a event in forge atm.
In the light of not wanting to do forge's job, it will be unsupported until forge adds the proper events. In that case it'll automatically function correctly.
