### ISSUE TITLE
[1.16.4] Cannot mine 3x3 with Gobber

### ISSUE THREAD

**Issue by TwilightPSN** [HellFirePvP/AstralSorcery#1480]
When using Gobber 2 mods hammer, we are not able to mine a 3x3 of marble with it. Other mods hammers work fine but Gobber ones arent interacting properly.

**Comment by HellFirePvP** [comment]
Taking a quick glance at Gobber2, they're not breaking blocks, they're just setting those blocks to air and spawning block drops. As that is not how blocks are broken and as it does not fire any events, it's nothing i can do about.

Relevant code: https://github.com/kwpugh/gobber/blob/1.16.4/src/main/java/com/kwpugh/gobber2/items/toolbaseclasses/HammerUtil.java#L71
