### ISSUE TITLE
The Different Angles perk doesn't alway make pickaxes as fast as axes/shovels

### ISSUE THREAD

**Issue by Jeuvke** [HellFirePvP/AstralSorcery#1483]
1.15.2-1.12.13
When under the effect of haste with the Different Angles perk active, pickaxes aren't as fast as shovels or axes of the same type.

**Comment by HellFirePvP** [comment]
1.16.4: Fixed with version 1.13.3

**Comment by HellFirePvP** [comment]
1.15.2: Fixed with version 1.12.14
