### ISSUE TITLE
[1.16.4-1.13.1] [Cross-mod Compatibility] Crash when using "Phalanx" enchant on Shield from Ensorcellation

### ISSUE THREAD

**Issue by WayofTime** [HellFirePvP/AstralSorcery#1484]
When a shield is enchanted with "Phalanx" from Ensorcellation and right-click is pressed, a hard crash occurs. The log is below. When talking to KingLemming and then with Jane on the Discord, it was mentioned that this was most likely an old bug that was reintroduced in the port, dealing with when an attribute is removed.

[crash-2020-11-22_08.59.38-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/5580489/crash-2020-11-22_08.59.38-server.txt)

**Comment by HellFirePvP** [comment]
Upon taking a close look, it does not look to be caused or influenced by AS.
Should more concrete suspicion arise that it results from AS, the issue may be reopened of course.
