### ISSUE TITLE
[1.16.4] Crashing when astral tome tries to render...

### ISSUE THREAD

**Issue by thecow275** [HellFirePvP/AstralSorcery#1487]
Minecraft:1.16.4
Forge version: 35.1.1
AstralSorcery version: 1.16.4-1.13.1

Other mods: YES
Modlist: https://gist.github.com/thecow275/f79cb8fdc2da74b94117dbe5e876b7fd

Steps to reproduce:
1. open Astral tome
2. go to Attunement 
3. go to Starlight Attunement 
4. go to last page
5.render crash happens

latest.log:https://gist.github.com/thecow275/f99ffaba9b34e32c150ef79c47a2e0a1
debug.log:https://gist.github.com/thecow275/1902176ccb2e5dcf6055c873d2873d8f

**Comment by xaelith** [comment]
I'm having a similar issue in All The Mods 6 version 1.3.2c. After receiving the Luminous Crafting Table, I go to the "Research" tab in the astral tome, zoom in on "Exploration", click on the icon for the Starlight Crafting Altar, and click the arrow button for the next page where it shows the structure the table needs to be placed on. The moment I click on the arrow, the entire game freezes for a few seconds before closing the main window.

Minecraft: 1.16.4
Forge version: 35.1.4
Astral Sorcery version: 1.16.4-1.13.1

More info available in the crash report link below, but if there's anything else I can help with, please let me know.
https://gist.github.com/xaelith/a8875f1e0d20348aea00fd5a1c7e6d91

**Comment by Zero9o1o** [comment]
Getting the same crash it seem. Crashing when open a page that renders a structure.

Crash report:
https://gist.github.com/Zero9o1o/c14fe5a2e06039f0d1e7c80edbd3e49a

Minecraft: 1.16.4
Forge: 35.1.3
Mod version: 1.16.4-1.13.1

Modpack: Valhelsia 3
version: pre6-3.1.0

**Comment by Doomgull** [comment]
I'm unable to replicate any of these crashes with the specified forge versions for each.

**Comment by Zero9o1o** [comment]
I got it to crash with just astral sorcery. 
https://gist.github.com/Zero9o1o/b1a37e7506a03760262b29d7c950572e

It crashes when I enabled "experimentalForgeLightPipelineEnabled".

**Comment by xaelith** [comment]
> I got it to crash with just astral sorcery.
> https://gist.github.com/Zero9o1o/b1a37e7506a03760262b29d7c950572e
> 
> It crashes when I enabled "experimentalForgeLightPipelineEnabled".

Interesting...I know I have that enabled, as well. Refined Storage pops up a message in the chat log when first loading into a world asking to enable that setting. I'll take ugly-looking textures over crashes (assuming RS doesn't cause crashes for turning that setting off), but I wonder why one mod requires the setting, and the other doesn't? Furthermore, why is that enough to cause a crash in the first place?

**Comment by HellFirePvP** [comment]
Fixed with ObserverLib 1.16.4-1.4.4

**Comment by HellFirePvP** [comment]
That build is published and available now, fixing this issue.
Please update to it.
[https://www.curseforge.com/minecraft/mc-mods/observerlib/files/3123187](https://www.curseforge.com/minecraft/mc-mods/observerlib/files/3123187)

Thanks~
