### ISSUE TITLE
The corrupted Horologium ritual can cause severe client-side lag

### ISSUE THREAD

**Issue by Jeuvke** [HellFirePvP/AstralSorcery#1488]
1.15.2-1.12.13
The 'lightning' effects from the corrupted Horologium ritual (Horologium with a trait of Alcara) can be very big. This can cause severe drops in the frame rate, up to a 99.5% reduction in some cases.

Average time per frame: 8ms
Highest frame time I've seen so far: 909ms

https://streamable.com/enftme
They look so cool though.

**Comment by HellFirePvP** [comment]
1.16.4: Fixed with version 1.13.3

**Comment by HellFirePvP** [comment]
1.15.2: Fixed with version 1.12.14
