### ISSUE TITLE
The corrupted Horologium ritual freezes its own mirror lenses

### ISSUE THREAD

**Issue by Jeuvke** [HellFirePvP/AstralSorcery#1489]
1.15.2-1.12.13
This causes them to not be picked up, requiring a 'restart' of the ritual. The same thing happens with a ritual anchor above the pedestal, and with lenses linking a collector crystal to the pedestal.

**Comment by HellFirePvP** [comment]
1.16.4: Fixed with version 1.13.3

**Comment by HellFirePvP** [comment]
1.15.2: Fixed with version 1.12.14
