### ISSUE TITLE
[1.16.4] Corrupted Mineralis Ritual issues. 

### ISSUE THREAD

**Issue by luna6667** [HellFirePvP/AstralSorcery#1491]
Corrupted mineralis ritual is crashing when placing the crystal in the pedestal, and upon relog seems to be freezing entites, similarly to the corrupted horo ritual, instead of placing blocks.  Also has the same issue as #1488 and #1489 
[crash-2020-11-24_22.35.57-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/5594293/crash-2020-11-24_22.35.57-server.txt)

**Comment by luna6667** [comment]
If i could edit the title i would, but i wanted to add onto this issue. The pelotrio collector crystal seems to not want to link to anything, and i cannot tell if the ritual for pelotrio is working as intended, IE: killing an affected mob gives more drops. if i interpreted that correctly.

**Comment by Jeuvke** [comment]
Here is the crash report on pastebin:
https://pastebin.com/6sDm5iKU

**Comment by HellFirePvP** [comment]
1.16.4: Fixed with version 1.13.3

**Comment by HellFirePvP** [comment]
1.15.2: Fixed with version 1.12.14
