### ISSUE TITLE
Octans ritual particle effects are doubled when the ritual is transposed with a Ritual Anchor

### ISSUE THREAD

**Issue by Jeuvke** [HellFirePvP/AstralSorcery#1493]
1.15.2-1.12.13
When an Octans ritual is transposed with a Ritual Anchor, the "purple particle rain cloud" effect appears both above the Ritual Pedestal and above the Ritual Anchor it is transposed to. No fishing loot will drop from the cloud above the Pedestal, however.

**Comment by HellFirePvP** [comment]
Any ritual's particle effects are playing both on the ritual pedestal & ritual anchor's position.
