### ISSUE TITLE
unidentifed rock crystals dissapear (1.12.2)

### ISSUE THREAD

**Issue by onlymeandbanana** [HellFirePvP/AstralSorcery#1494]
i played a modpack with a recepie for rock crystals, an tried to autocraft clestrial crystals. i dropped cock crystals with a dropper that had just been crafted and haddent been in my inventory and they dissapeard. having them in my inventory befor putting them into the dropper however,  seamed to fix the isseu.

**Comment by Doomgull** [comment]
That should be taken up with the pack devs, since something isn't right thete.
