### ISSUE TITLE
Starlight Infusion not working

### ISSUE THREAD

**Issue by BluMasc** [HellFirePvP/AstralSorcery#1495]
i am playing the pre6 version of Valhelsia 3 and it contains the newest AS release. I can't get starlight infusion to work. 
i tried the crafting table near a spawnt crystal, a iron ore linked to the spawned crystal and an iron ore and a cheated in crystal. On all tries result in the particle effects but nothing else happening. I waited for multiple hours without any transformation.

Game information:
Minecraft: 1.16.4
Forge: 35.1.3
Astral Sorcery: 1.13.1
Modpack: Valhelsia 3 pre6-3.1.0

On a self hosted server.

**Comment by Doomgull** [comment]
Make sure the crystal has no blocks between it and the sky.

Should probably also go to the discord for hel0 with this.
