### ISSUE TITLE
Astral Tome displays wrong number of blocks needed to create multiblocks

### ISSUE THREAD

**Issue by themadjem** [HellFirePvP/AstralSorcery#1496]
Minecraft Version: 1.16.4
Astral Sorcery Version: 1.13.1

On pages that display the multi-block structures, the icon that tells you the amount of each item displays all of them as 1x.

![image](https://user-images.githubusercontent.com/17654014/100487295-ccf97580-30d5-11eb-961a-c890c732d829.png)

**Comment by Doomgull** [comment]
Yes, known issue
