### ISSUE TITLE
Models for ore blocks are missing when using OptiFine

### ISSUE THREAD

**Issue by TowardtheStars** [HellFirePvP/AstralSorcery#1497]
Minecraft Version 1.15.2
Astral Sorcery Version: 1.12.13
ObserverLib Version: 1.3.2
Forge Version: 31.2.46
OptiFine Version: HD_U_G5_pre1

All textures for 3 ore blocks are missing when OptiFine is installed. And OptiForge will not help.
![图片](https://user-images.githubusercontent.com/29396015/100515449-4cab4100-31b7-11eb-8a3d-186a62beab85.png)
![图片](https://user-images.githubusercontent.com/29396015/100515537-d9ee9580-31b7-11eb-88ff-aa8ebcda9331.png)

ResourceLocation for affected blocks: 
- astralsorcery:aquamarine_sand_ore
- astralsorcery:rock_crystal_ore
- astralsorcery:starmetal_ore

**Comment by Doomgull** [comment]
Can't help what a closed-source mod breaks.

Also, does no one search anymore before opening tickets? So many duplicates on this. #1380
