### ISSUE TITLE
Astral Sorcery crashing while flipping Astral Tome Pages

### ISSUE THREAD

**Issue by LogBomb** [HellFirePvP/AstralSorcery#1498]
Hi everyone,

I'm recently playing in a server with a couple of friends using the modpack "Valhelsia 3" for 1.16.4 which includes Astral Sorcery.

I've played with Astral Sorcery before (during 1.12) and never had problems.

However, this time around, when flipping certain Tome pages my game crashes completely. This happens to a friend of mine too.

Right now the 2nd page for the "Starlight Crafting Alter" is doing this. I can open the first page to see the recipe, but the second page with the structure required crashes the game. Crash Report is here: [crash-2020-11-29_10.31.43-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/5611951/crash-2020-11-29_10.31.43-client.txt)

Is this a known issue or should I re-install the modpack in my server to see if it resolves the issue?

Second question I have - I see the mod is quite changed from the last iteration I played. The Luminous Crafting Table has a different crafting method now for instance. Have the structures for any of the progression changed as well? I am not sure at this point if I can ignore the crash and just use the wiki for guidance, I wouldn't mind doing so if possible.

Thank you!

**Comment by HellFirePvP** [comment]
1) Dupicate: #1487

Structures have not changed except for the Starlight Infuser.

**Comment by LogBomb** [comment]
Sorry for that! I tried searching but am not familiar with GitHub at all

Thanks for the reply, I'll read through it!
