### ISSUE TITLE
Bubble columns are not considered a fluid by the corrupted Octans ritual

### ISSUE THREAD

**Issue by Jeuvke** [HellFirePvP/AstralSorcery#1499]
1.15.2-1.12.13
This means no fishing drops get spawned in them, but they don't get replaced by sand either. IMO, bubble columns should count as water for this.

**Comment by HellFirePvP** [comment]
1.16.4: Fixed with version 1.13.3

**Comment by HellFirePvP** [comment]
1.15.2: Fixed with version 1.12.14
