### ISSUE TITLE
Alternative to scrolling in the journal

### ISSUE THREAD

**Issue by Roxforbraynz** [HellFirePvP/AstralSorcery#15]
I use a mouse with a busted scroll wheel (Which works great otherwise, so I don't think it's worth replacing quite yet) and I find myself unable to look things up in the journal without an external program to simulate the scroll wheel with keyboard presses.

It'd be nice to have an alternative way to scroll so I don't have to keep opening up the external program whenever I want to play with the mod.

**Comment by HellFirePvP** [comment]
Zooming in and out is available in 1.1.3+ via your forward&backward movement keybindings.
