### ISSUE TITLE
Crash OpenGL ?

### ISSUE THREAD

**Issue by Nuwea** [HellFirePvP/AstralSorcery#150]
Hello,
Here is a recurring error when loading chunks
Do you know how to solve this problem?
Thank you

**server :**
minecraft (linux) v 1.11.2

**mods :**
AbyssalCraft-1.11.2-1.9.4-pre-2
**astralsorcery-1.3.0-beta**
extrautils2-1.11.2-1.3.3
ironchest-1.11.2-7.0.18.800
Minions-1.11.2
missing_pieces-1.11.2-4.1.2
PrimordialCrops-v1.7c_mc1.11
stacksize-1.11.2-1.0
WearableBackpacks-1.11.2-2.1.0
Zeiyocraft-1.11.2

**error :**
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AstralCore (astralsorcery-1.3.0-beta.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 4/29/17 2:01 PM
Description: Tesselating block model

java.lang.OutOfMemoryError: Tesselating block model
	at sun.misc.Unsafe.allocateMemory(Native Method)
	at java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at net.minecraft.client.renderer.GLAllocation.func_74524_c(SourceFile:41)
	at net.minecraft.client.renderer.VertexBuffer.func_181670_b(VertexBuffer.java:55)
	at net.minecraft.client.renderer.VertexBuffer.func_178981_a(VertexBuffer.java:421)
	at net.minecraftforge.client.model.pipeline.VertexBufferConsumer.put(VertexBufferConsumer.java:65)
	at net.minecraftforge.client.model.pipeline.VertexLighterFlat.processQuad(VertexLighterFlat.java:210)
	at net.minecraftforge.client.model.pipeline.QuadGatheringTransformer.put(QuadGatheringTransformer.java:63)
	at net.minecraftforge.client.model.pipeline.LightUtil.putBakedQuad(LightUtil.java:126)
	at net.minecraft.client.renderer.block.model.BakedQuad.pipe(BakedQuad.java:66)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:138)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:103)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:47)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:38)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:199)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at sun.misc.Unsafe.allocateMemory(Native Method)
	at java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at net.minecraft.client.renderer.GLAllocation.func_74524_c(SourceFile:41)
	at net.minecraft.client.renderer.VertexBuffer.func_181670_b(VertexBuffer.java:55)
	at net.minecraft.client.renderer.VertexBuffer.func_178981_a(VertexBuffer.java:421)
	at net.minecraftforge.client.model.pipeline.VertexBufferConsumer.put(VertexBufferConsumer.java:65)
	at net.minecraftforge.client.model.pipeline.VertexLighterFlat.processQuad(VertexLighterFlat.java:210)
	at net.minecraftforge.client.model.pipeline.QuadGatheringTransformer.put(QuadGatheringTransformer.java:63)
	at net.minecraftforge.client.model.pipeline.LightUtil.putBakedQuad(LightUtil.java:126)
	at net.minecraft.client.renderer.block.model.BakedQuad.pipe(BakedQuad.java:66)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:138)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:103)

-- Block model being tesselated --
Details:
	Block: minecraft:leaves[check_decay=false,decayable=true,variant=oak]
	Block location: World: (-150066,78,-149938), Chunk: (at 14,4,14 in -9380,-9372; contains blocks -150080,0,-149952 to -150065,255,-149937), Region: (-294,-293; contains chunks -9408,-9376 to -9377,-9345, blocks -150528,0,-150016 to -150017,255,-149505)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:47)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:38)

-- Block being tesselated --
Details:
	Block type: ID #18 (tile.leaves // net.minecraft.block.BlockOldLeaf)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-150066,78,-149938), Chunk: (at 14,4,14 in -9380,-9372; contains blocks -150080,0,-149952 to -150065,255,-149937), Region: (-294,-293; contains chunks -9408,-9376 to -9377,-9345, blocks -150528,0,-150016 to -150017,255,-149505)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Nuwea'/152136, l='MpServer', x=-149999.50, y=99.76, z=-149999.50]]
	Chunk stats: MultiplayerChunkCache: 281, 281
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,66,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 12216032 game time, 12223386 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 83 total; [EntityEvilCow['Cow'/152194, l='MpServer', x=-149958.50, y=70.00, z=-150059.50], EntityPlayerSP['Nuwea'/152136, l='MpServer', x=-149999.50, y=99.76, z=-149999.50], EntityBat['Bat'/152195, l='MpServer', x=-149980.49, y=12.12, z=-150003.30], EntityEvilCow['Cow'/152192, l='MpServer', x=-149956.50, y=70.00, z=-150058.50], EntityEvilCow['Cow'/152193, l='MpServer', x=-149955.50, y=70.00, z=-150059.50], EntityItem['item.tile.torch'/152198, l='MpServer', x=-149944.70, y=44.00, z=-150054.22], EntityEvilCow['Cow'/152199, l='MpServer', x=-149937.50, y=72.00, z=-150048.50], EntityEvilCow['Cow'/152196, l='MpServer', x=-149931.50, y=64.00, z=-150069.50], EntityEvilCow['Cow'/152197, l='MpServer', x=-149930.50, y=64.00, z=-150071.50], EntityEvilCow['Cow'/152200, l='MpServer', x=-149939.50, y=72.00, z=-150049.50], EntitySkeleton['Skeleton'/152210, l='MpServer', x=-150002.50, y=70.00, z=-149924.50], EntityZombie['Zombie'/152343, l='MpServer', x=-149999.50, y=56.00, z=-150027.50], EntityCreeper['Creeper'/152344, l='MpServer', x=-150001.50, y=56.00, z=-150027.50], EntityBat['Bat'/152348, l='MpServer', x=-150065.72, y=23.05, z=-150032.29], EntityBat['Bat'/152224, l='MpServer', x=-150043.41, y=16.02, z=-150029.24], EntitySkeleton['Skeleton'/152358, l='MpServer', x=-150025.50, y=74.00, z=-150065.50], EntityBat['Bat'/152362, l='MpServer', x=-150049.91, y=10.95, z=-150007.31], EntityZombie['Zombie'/152360, l='MpServer', x=-149987.50, y=65.00, z=-150032.50], EntityZombie['Zombie'/152374, l='MpServer', x=-149965.55, y=70.00, z=-150068.24], EntityZombie['Zombie'/152375, l='MpServer', x=-149963.50, y=70.00, z=-150063.50], EntityCreeper['Creeper'/152379, l='MpServer', x=-149963.50, y=70.00, z=-150066.50], EntityZombie['Zombie'/152248, l='MpServer', x=-150035.50, y=70.00, z=-150038.50], EntityCreeper['Creeper'/152376, l='MpServer', x=-149962.50, y=70.00, z=-150066.50], EntityBat['Bat'/152255, l='MpServer', x=-149985.47, y=59.43, z=-149943.71], EntityZombie['Zombie'/152252, l='MpServer', x=-149999.81, y=64.00, z=-149948.54], EntityZombie['Zombie'/152253, l='MpServer', x=-150000.50, y=64.00, z=-149949.50], EntityCreeper['Creeper'/152259, l='MpServer', x=-149997.50, y=56.00, z=-150028.50], EntityBat['Bat'/152256, l='MpServer', x=-149984.25, y=58.14, z=-149946.29], EntitySkeleton['Skeleton'/152262, l='MpServer', x=-150033.50, y=64.00, z=-150008.50], EntitySkeleton['Skeleton'/152263, l='MpServer', x=-150032.50, y=64.00, z=-150007.50], EntityCreeper['Creeper'/152260, l='MpServer', x=-149997.50, y=56.00, z=-150029.50], EntityBat['Bat'/152138, l='MpServer', x=-150061.75, y=43.03, z=-150045.25], EntityEvilCow['Cow'/152139, l='MpServer', x=-150072.50, y=63.00, z=-150029.50], EntitySkeleton['Skeleton'/152264, l='MpServer', x=-150033.50, y=64.00, z=-150010.50], EntityBat['Bat'/152137, l='MpServer', x=-150056.01, y=43.01, z=-150045.26], EntityZombieVillager['Zombie Villager'/152265, l='MpServer', x=-150026.50, y=64.00, z=-150007.50], EntitySkeleton['Skeleton'/152143, l='MpServer', x=-150063.50, y=63.00, z=-150025.50], EntitySkeleton['Skeleton'/152146, l='MpServer', x=-149942.50, y=70.00, z=-149960.50], EntityEvilChicken['Chicken'/152144, l='MpServer', x=-150065.50, y=64.00, z=-149975.50], EntitySkeleton['Skeleton'/152145, l='MpServer', x=-149943.50, y=70.00, z=-149959.50], EntityEvilCow['Cow'/152151, l='MpServer', x=-149978.50, y=66.00, z=-149935.50], EntityCow['Cow'/152154, l='MpServer', x=-149963.50, y=71.00, z=-149921.50], EntityCow['Cow'/152155, l='MpServer', x=-149965.50, y=70.00, z=-149922.50], EntityCow['Cow'/152152, l='MpServer', x=-149963.50, y=71.00, z=-149924.50], EntityCow['Cow'/152153, l='MpServer', x=-149963.50, y=71.00, z=-149921.50], EntityBat['Bat'/152158, l='MpServer', x=-149973.25, y=47.03, z=-149964.70], EntityEvilCow['Cow'/152159, l='MpServer', x=-150018.50, y=66.00, z=-149919.50], EntityEvilCow['Cow'/152156, l='MpServer', x=-149962.50, y=65.00, z=-149973.50], EntityEvilCow['Cow'/152157, l='MpServer', x=-149964.50, y=65.00, z=-149973.50], EntityBat['Bat'/152294, l='MpServer', x=-149942.66, y=44.15, z=-149972.08], EntityCreeper['Creeper'/152167, l='MpServer', x=-150018.50, y=68.00, z=-150018.50], EntityBat['Bat'/152295, l='MpServer', x=-149939.14, y=43.03, z=-149970.94], EntityBat['Bat'/152423, l='MpServer', x=-150071.04, y=31.94, z=-149969.42], EntitySkeleton['Skeleton'/152164, l='MpServer', x=-149977.50, y=31.00, z=-150067.50], EntitySkeleton['Skeleton'/152293, l='MpServer', x=-149932.50, y=44.00, z=-150046.50], EntitySheep['Sheep'/152170, l='MpServer', x=-149969.50, y=70.00, z=-150059.50], EntitySheep['Sheep'/152171, l='MpServer', x=-149969.50, y=70.00, z=-150061.50], EntityBat['Bat'/152299, l='MpServer', x=-149947.83, y=44.02, z=-149979.24], EntitySkeleton['Skeleton'/152168, l='MpServer', x=-150018.48, y=64.00, z=-149999.89], EntitySheep['Sheep'/152169, l='MpServer', x=-149969.50, y=70.00, z=-150060.50], EntityBat['Bat'/152297, l='MpServer', x=-149947.29, y=44.75, z=-149975.09], EntityWitch['Witch'/152174, l='MpServer', x=-150023.50, y=64.00, z=-149948.50], EntityItem['item.tile.torch'/152175, l='MpServer', x=-149945.54, y=46.00, z=-150042.88], EntitySheep['Sheep'/152172, l='MpServer', x=-149972.50, y=70.00, z=-150061.50], EntityEvilChicken['Chicken'/152173, l='MpServer', x=-149993.39, y=65.42, z=-150033.58], EntityZombieVillager['Zombie Villager'/152178, l='MpServer', x=-149961.50, y=66.00, z=-149992.50], EntityZombieVillager['Zombie Villager'/152179, l='MpServer', x=-149962.50, y=66.00, z=-149994.50], EntityEvilCow['Cow'/152176, l='MpServer', x=-149935.50, y=72.00, z=-150049.50], EntitySkeleton['Skeleton'/152177, l='MpServer', x=-149960.05, y=71.00, z=-149999.67], EntityEvilChicken['Chicken'/152182, l='MpServer', x=-149984.50, y=74.00, z=-150012.50], EntitySkeleton['Skeleton'/152183, l='MpServer', x=-150010.50, y=64.00, z=-149997.50], EntityEvilChicken['Chicken'/152181, l='MpServer', x=-149986.58, y=73.42, z=-150015.40], EntityCreeper['Creeper'/152186, l='MpServer', x=-150002.50, y=67.00, z=-149989.30], EntityBat['Bat'/152442, l='MpServer', x=-149939.25, y=57.02, z=-149992.43], EntityEvilCow['Cow'/152187, l='MpServer', x=-149936.50, y=66.00, z=-150069.50], EntityCreeper['Creeper'/152184, l='MpServer', x=-150012.50, y=64.00, z=-149995.50], EntityBat['Bat'/152440, l='MpServer', x=-149945.24, y=58.07, z=-149996.49], EntityCreeper['Creeper'/152185, l='MpServer', x=-150001.50, y=68.00, z=-149989.50], EntityBat['Bat'/152441, l='MpServer', x=-149941.52, y=58.27, z=-149994.69], EntitySpider['Spider'/152190, l='MpServer', x=-149995.35, y=66.00, z=-150027.02], EntitySpider['Spider'/152191, l='MpServer', x=-149996.73, y=66.00, z=-150026.96], EntityEvilCow['Cow'/152188, l='MpServer', x=-149937.50, y=66.00, z=-150066.50], EntityEvilCow['Cow'/152189, l='MpServer', x=-149941.50, y=64.00, z=-150066.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:49)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 330505632 bytes (315 MB) / 734760960 bytes (700 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.38 Powered by Forge 13.20.0.2228 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2228.jar) 
	UCHIJA	forge{13.20.0.2228} [Minecraft Forge] (forge-1.11.2-13.20.0.2228.jar) 
	UCHIJA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
	UCHIJA	abyssalcraft{1.9.4-pre-2} [AbyssalCraft] (AbyssalCraft-1.11.2-1.9.4-pre-2.jar) 
	UCHIJA	astralsorcery{1.3.0-beta} [Astral Sorcery] (astralsorcery-1.3.0-beta.jar) 
	UCHIJA	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.3.3.jar) 
	UCHIJA	ironchest{1.11.2-7.0.18.800} [Iron Chest] (ironchest-1.11.2-7.0.18.800.jar) 
	UCHIJA	minions{2.0.2} [Minions] (Minions-1.11.2.jar) 
	UCHIJA	missing_pieces{4.1.2} [Missing Pieces] (missing_pieces-1.11.2-4.1.2.jar) 
	UCHIJA	mc{1.7c} [Primordial Crops] (PrimordialCrops-v1.7c_mc1.11.jar) 
	UCHIJA	stacksize{1.0} [Stacksize Mod] (stacksize-1.11.2-1.0.jar) 
	UCHIJA	wearablebackpacks{2.1.0} [Wearable Backpacks] (WearableBackpacks-1.11.2-2.1.0.jar) 
	UCHIJA	zeiyocraft{0.8.1} [ZeiyoCraft] (Zeiyocraft-1.11.2.jar) 
	Loaded coremods (and transformers): 
AstralCore (astralsorcery-1.3.0-beta.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2228
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4430 CPU @ 3.00GHz

**Comment by HellFirePvP** [comment]
You're out of memory, 1GB isn't really enough. Try at least with 4.
