### ISSUE TITLE
Lan server connection issues

### ISSUE THREAD

**Issue by Boisq** [HellFirePvP/AstralSorcery#1500]
I was playing with my friend in a custom pack until yesterday, and today everytime i try to join i get dced, sometimes its instant and sometimes it takes a few seconds, he gets this message on his end (he is the server owner, its lan)

[Netty Server IO #6/ERROR] [minecraft/ArgumentTypes]: Could not serialize hellfirepvp.astralsorcery.common.cmd.argument.ArgumentTypeConstellation@11a6bb21 (class hellfirepvp.astralsorcery.common.cmd.argument.ArgumentTypeConstellation) - will not be sent to client!

yesterday i attuned myself not long before we stopped playing, nothing really happened at the time either, we tried a few things like restarting the modem and pc but it didnt help
AS version is 1.13.1

**Comment by HellFirePvP** [comment]
This needs a crash log from the one hosting this server.
Also, if your crash closes the application, i need one from you as well.

The stuff pasted above is just a warning notice, nothing that'd result in a disconnect.

**Comment by Boisq** [comment]
Yeah so, i think the dcs and that error are not related, as today we can play normally, we ran a connection test later and we werent getting any, he still got that error on his side tho, theres no crash log either as it doesnt crash, im gonna close this as there is not enough info for anything and theres no problem anymore (other than that message)
