### ISSUE TITLE
tree beacon crash with unknown mod in valhelsia 3

### ISSUE THREAD

**Issue by lag42** [HellFirePvP/AstralSorcery#1502]
in [valhelsia 3 pre7-3.1.0](https://www.curseforge.com/minecraft/modpacks/valhelsia-3/files/3123980)  if you grow an oak sapling with bone meal near a tree beacon that world will repeatedly crash, i cannot tell what other mod is doing this by the [crash log](https://gist.github.com/lag42/ab90aaf196d7dc6a651a92d73728a510) or the [full log](https://gist.github.com/lag42/ab19f612544ac9fe6b82836683e6bcbf) this does not appear to happen in a clean instance with just astral sorcery and optifine is not installed

i hope this is much easier for you to diagnose from your end, i couldn't get much good info on mine for you here unfortunately

**Comment by dsweber2** [comment]
I'm also having this issue, but on a server. The server itself is fine and doesn't encounter the error at all. The client, on the other hand, crashes (and is stuck in a loop doing so). Guessing this is expected for a rendering bug, but figured you may want to know.
