### ISSUE TITLE
(Infused) crystal tools can't obtain extra modifiers from the stellar refraction table

### ISSUE THREAD

**Issue by Jeuvke** [HellFirePvP/AstralSorcery#1506]
1.15.2-1.12.13
Crystal tools and their infused counterparts can't obtain any extra modifiers (+mining size, +mining speed, etc.) from a stellar refraction table.

**Comment by HellFirePvP** [comment]
1.16.4: Fixed with version 1.13.3

**Comment by HellFirePvP** [comment]
1.15.2: Fixed with version 1.12.14
