### ISSUE TITLE
Crash on Attunement (1.16.4)

### ISSUE THREAD

**Issue by shia1122** [HellFirePvP/AstralSorcery#1507]
Crashed on attempting to stand on the Attunement Altar, unsure if related to other mods but hoping to get some help. 
This is such a great mod.

https://pastebin.com/Wu5aHs4k 
https://pastebin.com/bL4Yr0f4

EDIT:
Since the initial crash, I can no longer take damage and hostile mobs completely ignore me. Is this a setting that gets enabled for the player during attunement that is not being removed as the attunement isn't being completed? Is there a workaround?

**Comment by HellFirePvP** [comment]
"Traveler's Index" is responsible for that.
