### ISSUE TITLE
Within Valhelsia 3 Attempting to craft the Luminous Crafting Table does not work.

### ISSUE THREAD

**Issue by Athougho** [HellFirePvP/AstralSorcery#1508]
I will be posting this in Valhesia too, but when placing the ingredients in the grid, there is no output.

**Comment by xaelith** [comment]
To my knowledge, there isn't a recipe for the luminous crafting table, a normal crafting table gets turned into one when placed near one of the collection crystals found in-world. Then again, I've been playing on All The Mods 6, so either pack could have changed things.

**Comment by lag42** [comment]
yes, there is no recipe since the update to 1.15, break the roof above the crystal and put a crafting table nearby if you're trying to make the **luminous** crafting table

**Comment by Athougho** [comment]
So, there is no way to proceed; to make the LMC or its' products?

**Comment by Doomgull** [comment]
In 1.15 and 1.16, there is no crafting recipe for a Luminous Crafting Table. It's an in-world crafting that is performed, like transmuting Iron Ore to Starmetal Ore. Place a crafting table near a crystal in a shrine, make sure the crystal has no blocks between itself and the sky (including cloud blocks), it'll transmute into a Luminous Crafting Table.

If the modpack you are using has changed this, you would need to address this through the modpack instead. If you are still having issues, this should be addressed through the Discord for more hands-on assistance to walk you through it.
