### ISSUE TITLE
Aevitas Mantle doesn't increase hunger like book states.

### ISSUE THREAD

**Issue by VallenFrostweaver** [HellFirePvP/AstralSorcery#1510]
MC: 1.16.4
AS: 1.13.1
Observlib: 1.4.4
Curios: 4.0.3.0
![image](https://user-images.githubusercontent.com/13642054/100881186-89bc4f80-34a5-11eb-9199-4812301ef974.png)

**Comment by HellFirePvP** [comment]
1.16.4: Fixed with version 1.13.3

**Comment by HellFirePvP** [comment]
1.15.2: Fixed with version 1.12.14
