### ISSUE TITLE
Pelotrio Mantle of the Stars ghost tools use pickaxe on wood and axe on stone, etc.

### ISSUE THREAD

**Issue by VallenFrostweaver** [HellFirePvP/AstralSorcery#1511]
MC: 1.16.4
AS: 1.13.1
Observlib: 1.4.4
Curios: 4.0.3.0
Using any axe will spawn a spectral tool that will harvest wood as well as stone. Using any pickaxe will do the same as well. This may be as intended but one would assume an axe would harvest axe items and a pick, pick items.

**Comment by HellFirePvP** [comment]
1.16.4: Fixed with version 1.13.3

**Comment by HellFirePvP** [comment]
1.15.2: Fixed with version 1.12.14
