### ISSUE TITLE
Push lens doesn't push in entire beam area.

### ISSUE THREAD

**Issue by VallenFrostweaver** [HellFirePvP/AstralSorcery#1512]
MC: 1.16.4
AS: 1.13.1
Observlib: 1.4.4
Curios: 4.0.3.0
There is an area not covered by the push lens on one side of the beam. Attached image shows it. If I stand on the other side (right of beam facing me) then I **do** get pushed but on the left I **don't**. One way to find it is to have a push lens pushing you against a wall and you try to push against it at a slight angle. Another way to find it is to spew a bunch of blocks accross the beam in an arc and those that remain represent the area it doesn't cover.
![image](https://user-images.githubusercontent.com/13642054/100890287-f89ea600-34af-11eb-9857-ba64c3d7ecd4.png)

**Comment by HellFirePvP** [comment]
1.16.4: Fixed with version 1.13.3

**Comment by HellFirePvP** [comment]
1.15.2: Fixed with version 1.12.14
