### ISSUE TITLE
Illumination wand second functionality makes a crashing chunk

### ISSUE THREAD

**Issue by kukuminer** [HellFirePvP/AstralSorcery#1513]
Using shift + right click function of illumination wand (to turn a block transparent like the book says) makes the chunk crash your game. 
Environment: Dedicated server, moving into chunk with "transparent" block caused a client crash, server unaffected
MC: 1.16.4
AS: 1.13.1
Modpack: Valhelsia 3.1.0 pre7. 
[crash-2020-12-02_11.22.17-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/5630805/crash-2020-12-02_11.22.17-client.txt)
[crash-2020-12-02_11.34.21-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/5630806/crash-2020-12-02_11.34.21-client.txt)
[crash-2020-12-02_11.43.22-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/5630807/crash-2020-12-02_11.43.22-client.txt)
[crash-2020-12-02_11.16.58-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/5630808/crash-2020-12-02_11.16.58-client.txt)

**Comment by 1285done** [comment]
FYI: For anyone who's currently stuck crashing with this, installing optifine should let you load back in to remove the transparent block.
