### ISSUE TITLE
The Different Angles perk does not work on some wooden blocks

### ISSUE THREAD

**Issue by Jeuvke** [HellFirePvP/AstralSorcery#1514]
1.15.2-1.12.13
The Different Angles perk does not make pickaxes mine some wooden blocks faster.
Blocks affected:
-All wooden slabs
-All wooden stairs
-All fences
-All fence gates
-Crafting table
-All signs
-All wooden trapdoors
-All wooden doors
-Barrel
and probably some more

**Comment by HellFirePvP** [comment]
Duplicate: #1483

**Comment by Jeuvke** [comment]
This bug is about different angles not working at all on some wooden blocks, while 1483 is about haste not affecting different angles.

**Comment by HellFirePvP** [comment]
They both stem from the same issue
