### ISSUE TITLE
Regeneration from the Aevitas ritual is bugged

### ISSUE THREAD

**Issue by Jeuvke** [HellFirePvP/AstralSorcery#1516]
1.15.2-1.12.13
The regeneration effect from the Aevitas ritual gets applied every tick, which for some reason heals half a heart every tick. This is much faster than the normal speed of half a heart every 25 ticks for normal regeneration II.

**Comment by HellFirePvP** [comment]
1.16.4: Fixed with version 1.13.3

**Comment by HellFirePvP** [comment]
1.15.2: Fixed with version 1.12.14
