### ISSUE TITLE
Crash of diary

### ISSUE THREAD

**Issue by forestbat** [HellFirePvP/AstralSorcery#152]
When I click on constellations in the diary，it crashed and this is the report：

[crash-2017-05-01_10.20.41-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/967218/crash-2017-05-01_10.20.41-client.txt)

**Comment by Doomgull** [comment]
There's l ready an open issue for this, dude.

It's also somethig already listed as fixed I the next release, by the multiple other closed issues that open one is duped to.

**Comment by forestbat** [comment]
@Doomgull Okay I’ll close the issue。
