### ISSUE TITLE
Constellations do not show up in the sky

### ISSUE THREAD

**Issue by thjungers** [HellFirePvP/AstralSorcery#1523]
Discovered constellations do not appear in the sky.

When loading the world, the following message appears in the server log:
`[Netty Epoll Server IO #5/ERROR] [minecraft/ArgumentTypes]: Could not serialize hellfirepvp.astralsorcery.common.cmd.argument.ArgumentTypeConstellation@4048e5fb (class hellfirepvp.astralsorcery.common.cmd.argument.ArgumentTypeConstellation) - will not be sent to client!`

Configuration:

- Minecraft 1.16.4
- Forge 35.1.0
- Astral Sorcery 1.13.1
- Curios 4.0.3.0
- ObserverLib 1.4.4

Additional mods:

- JEI 7.6.0.58
- HWYLA 1.10.11 B78
- Botania 409
- Cucumber 4.1.5
- Mystical Agriculture 4.1.3
- Mystical Agradditions 4.1.2
- Patchouli 48
- Blood Magic 1.13.1

**Comment by Jeuvke** [comment]
Try again with 1.16.4-1.13.4, see if it still happens.

**Comment by HellFirePvP** [comment]
If this is a world that was updated, please check your astralsorcery-client.toml configuration and in case 'skyRenderDimensions' lists a 0, replace that 0 with `"minecraft:overworld"`

**Comment by thjungers** [comment]
This was indeed an updated world (generated under MC 1.15.2, AS 1.12.13).
In `astralsorcery-client.toml`, `skyRenderDimensions `was `[0]`. Replacing `0` with `"minecraft:overworld"` solves the issue: the constellations now appear in the sky.
However, the error message in the server log remains (but does not seem to be related).
