### ISSUE TITLE
Irradiant Stars won't change your attunement

### ISSUE THREAD

**Issue by Jeuvke** [HellFirePvP/AstralSorcery#1526]
1.16.4-1.13.3
Using an Evorsio Irradiant Star when attuned to Vicio will not change your attunement to Evorsio.

**Comment by HellFirePvP** [comment]
Can't reproduce this..
Did you discover evorsio? Not just 'seen' but 'discovered/traced' ?

**Comment by Jeuvke** [comment]
No idea what was up with that. I'll just close it.
