### ISSUE TITLE
Luminous Table will not/is taking infinitely long to craft

### ISSUE THREAD

**Issue by scarredFalconer** [HellFirePvP/AstralSorcery#1528]
Hello

I made a luminous table as normal, but when ever I try to craft something using starlight, I get the audio and visual cues, then nothing happens. 

Game Version: 1.16.4
Mod Version: 1.13.3
Forge Version: 35.1.7

I made a clean instance of the game using MultiMC. The only mods I have installed are Astral Sorcery, observerlib(1.4.4) and curios for forge (4.0.3.0)

I started a world in survival mode with mods turned on and cheats enabled for testing.
Then used /locate to find a desert shrine (which was in a savanna...) 
switched my game mode to creative
teleported to the location, 
dug out the whole shrine (I realize there wasn't really a reason to do this, I just wanted to be throrough)
made a luminous crafting table the standard way (crafting table under collection crystal with sky access at night). up to this point everything works fine.

I built a platform at y level 150 
then put a luminous crafting table on the platform
then inserted the recipe for a light well. 
at this point I waited for it to be midnight and disabled day/night cycle using the /gamerule command
I rightclicked with a resonating wand that I had cheated in, set the day/night cycle to run again and waited.

The audio and visual cues triggered (angelic singing sound and light beams coming down on the table from above)
Then, well nothing happened. I waited 4 minutes and 30 seconds (I timed it) until the sun came up and the table lost starlight.

I have tried this with multiple recipes (namely the fosic resonator) on multiple worlds to the same effect. The luminous crafting table just sits there singing infinitely until the sun comes up the next morning.

**Comment by Doomgull** [comment]
Update the mod to 1.13.4.
