### ISSUE TITLE
[1.12.2] Crash on Attunement in Server

### ISSUE THREAD

**Issue by Bakapasha** [HellFirePvP/AstralSorcery#1533]
The game crashes when I tried to attune myself. The animation will be played after I stepped on the altar until the game crashes eventually. Attuning crystal won't cause any problem. I've tested in singleplayer and everything goes well, so I assume this might be an issue with server.

Here's crash report:
https://pastebin.com/rvbSjVy5

Here's how it looks like in the console:
08.12 13:23:21 [Server] Server thread/INFO Builder: Baka_Cirno
08.12 13:23:47 [Disconnect] User Baka_Cirno has disconnected, reason: Timed out
08.12 13:23:47 [Server] Server thread/INFO Baka_Cirno left the game

**Comment by PocketfulOfGeese** [comment]
Since it only happens on server, I assume something is being used like Sponge for plugins server-side. If so, this either had a config value added or was fixed a long time ago with Sponge. 

Either way, this is the result of something conflicting.

**Comment by Bakapasha** [comment]
Thank you for your reply. I deleted and reuploaded all files on server, now it functions perfectly. I will close this issue then.
