### ISSUE TITLE
Cant seem to get shrines to spawn in other dsimesions

### ISSUE THREAD

**Issue by benbenlaw** [HellFirePvP/AstralSorcery#1534]
Cant seem to get shrines to spawn in other dsimesions i have changed the configs and doesnt seem to do anything

**Comment by benbenlaw** [comment]
![image](https://user-images.githubusercontent.com/42780877/101462930-b0aad380-3934-11eb-8972-2e379fea9b50.png)

**Comment by PocketfulOfGeese** [comment]
I don't think "good_nights_sleep:dream" is a valid dimension name, is it?

Are there biomes in that dimension that are tagged according to the biomeCategoryNames entry?

AS Version?

**Comment by benbenlaw** [comment]
im not sure what that means haha

**Comment by benbenlaw** [comment]
what would it be to be in the end

**Comment by HellFirePvP** [comment]
Well, read through the "available categories" of biome categories and add the applicable ones for the biomes you want the structure to spawn in. Chances are, the biomes in the world you're trying to spawn it in aren't "icy" or "extreme hills" categories.

also, as it says in the world configuration: the world filter does not work for structures; by default, structures spawn regardless of world. no matter what's set there. So please read the comments on the configuration option you're modifying...
