### ISSUE TITLE
AstralSorcery's ConfiguredFeature shrines are not registered

### ISSUE THREAD

**Issue by TelepathicGrunt** [HellFirePvP/AstralSorcery#1536]
Hello! I was running my mod called Blame with a bunch of mods and it seemed to have found that AstralSorcery has a few ConfiguredFeatures that are not registered. This can be an issue for mod compatibility as under certain conditions, unregistered ConfiguredFeatures can basically prevent other mod's registered ConfiguredFeatures from spawning if in the same generation stage.

By that I mean, if mod A adds an unregistered CF to the ore generation stage and the biome's codec reaches it first, it will choke and basically nuke mob B's registered CFs afterwards. Here's a case where BetterCaves forgot to register their CF and caused several CFs from Oh The Biomes You'll Go to stop spawning in the world: yungnickyoung/YUNGs-Better-Caves#75

Here's a more detailed explanation of why this happens in the biome's codec:
![image](https://user-images.githubusercontent.com/40846040/95459000-ff41ee80-0940-11eb-8569-52a2be15cc4d.png)

Specifically, when you call .withConfiguration on a Feature, you create a ConfiguredFeature. This is what should be registered to the WorldgenRegisties at mod init (you can do it in FMLCommonSetupEvent so you have your config ready too if it is needed). 

Anyway here's an example from my mod RepurposedStructures of me registering all my ConfiguredFeatures.
https://github.com/TelepathicGrunt/RepurposedStructures/blob/584433a0745338802c84e9f498dc063c1f5505f8/src/main/java/com/telepathicgrunt/repurposedstructures/modinit/RSConfiguredStructures.java#L72-L74

I hope this helps!

From the log with Blame:
astralsorcery:ancient_shrine
astralsorcery:desert_shrine
astralsorcery:small_shrine

**Comment by HellFirePvP** [comment]
To my knowledge, structures are not ConfiguredFeatures, but StructureFeatures.
So this should have been fixed with 1.13.4
