### ISSUE TITLE
[1.16.4] Liquid Starlight on top of Chalise renders behind other object

### ISSUE THREAD

**Issue by MacAttack-UK** [HellFirePvP/AstralSorcery#1537]
Forge: forge-1.16.4-35.1.7
Astral: astralsorcery-1.16.4-1.13.4
Private Pack.

In this image the Liquid Starlight on top of the Chalice looks like it is rendered behind the Infuser further back.

![Astral-1 16 4-Liquid-Render](https://user-images.githubusercontent.com/13574886/101714657-e1544f80-3a91-11eb-9d45-a6bd21817d41.png)

**Comment by HellFirePvP** [comment]
Not sure i can do a whole lot about this as the render order is nothing i can directly influence.

Do forge's multilayer models not work for you?
The white "floating" bits around the starlight infuser should be encased in glass, but in the screenshot they are not. Do any other multilayer models work? Collector crystals, relays, prisms, ...?

**Comment by MacAttack-UK** [comment]
Hmmm, I just made a basic pack with JEI, FTB and Astral and I'm now able to see the 'Glass' around the white bits so I guess it's probably another mod casusing the issue.

Although in this pics I can see the 'Glass' the water on the hill in the background seems to be rendering wrongly together with the clouds and some grass when viewed through the liquid. It doesn't seem to happen during day time.

![image](https://user-images.githubusercontent.com/13574886/101762823-d02d3200-3ad5-11eb-9bbb-8754a561020b.png)

Could it be a GPU driver issue? I'll check for an update

I guess we are still in early 1.16.x days, thanks for your time :)

**Comment by MacAttack-UK** [comment]
I'll close this as it's probably not Astral anyway, just wanted to make you aware.

**Comment by HellFirePvP** [comment]
I'll test some stuff and see what options i have here. But i'm not sure what i can adress and what i can't.
