### ISSUE TITLE
Star Metal Duplication bug

### ISSUE THREAD

**Issue by Gekocaretaker** [HellFirePvP/AstralSorcery#1538]
There is a bug in Astral Sorcery that makes it when you start hitting a star metal ingot with the chisel, and it breaks into dust at the same time you pick it back up, it will make a new ingot and powder.

**Comment by BlueAgent** [comment]
IIRC this is intended. You can get multiple dusts from one starmetal ingot. Fortune also improves the chance you have of not breaking the ingot. You can't smelt the dust back into an ingot so it's not a dupe unless some pack or unification mod added a smelting recipe.

**Comment by HellFirePvP** [comment]
What blue said and as it was laid out on discord.
Not a bug.
