### ISSUE TITLE
[1.16.4] Wonky rendering of starlight beams when graphics quality is Fabulous - may also break other effects

### ISSUE THREAD

**Issue by yagoplx** [HellFirePvP/AstralSorcery#1542]
Note: Optifine is not installed

Botania's effects do not seem to be affected by changing the graphics quality.

Changing the graphics quality to fast will cause Starlight beams to render every once in a while. I suppose this is intentional to increase framerates? EffectHandler will report a lowered number of effects, but the fact that most of the time there is not a sliver of starlight beams rendering, this might be quite confusing to a player, who may think their networks are broken.

Changing the graphics quality to fabulous will cause Starlight beams to never render, but EffectHandler will report a normal number of complex effects. Flares in the world and mantle, lens sparkle effects will also never render, but collector crystal and item shininess will still render.

**Comment by Jeuvke** [comment]
No particles at all render when using 'Fabulous' graphics, it seems.

**Comment by HellFirePvP** [comment]
One or two effects still might look a bit odd, though most things should work as of the next version

**Comment by yavincl** [comment]
What was the issue exactly with Fabulous? :P

**Comment by HellFirePvP** [comment]
There is currently no hook to render things in fabulous into one of the designated framebuffers before those get merged onto the main framebuffer. One solution would've been to use vanilla's particle system, though that'd mean a massive rewrite, loss of functionality and a bigger performance hit from particles.
A ASM hook was needed before the designated framebuffers get written into the main one, different adjustments to renderypes and several adjustments to GL states that are different in fabulous mode compared to 'fancy'. On that note, some things still do not work properly, though adjustments there would take massively longer and not something i'm currently looking to do.
