### ISSUE TITLE
[Suggestion] Sky block compatiablity suggestion

### ISSUE THREAD

**Issue by fallenhunter1** [HellFirePvP/AstralSorcery#1545]
As searching for a dark sky area in a sky block void world is impractical/impossible(hard to see the blue fog on the ground when there is no ground). Is there a way to put the fog at a given height? (no idea of the code, but do so if for example, dim type = void, or some other such check, possibly check to see if there is ANY blocks below the item used, if so, behave normally, if not, assume void world.)

This is obviously not that big an issue, but something I would love to see happen, as I love the mod itself, and both Skyblock modpacks, as well as modpacks where I can build in void world (IE in space, or a RFTools dim).

Thanks!

Fallenhunter1

**Comment by HellFirePvP** [comment]
Added next version with a "minYFosicDisplay" client config option.

Allows for setting the minimum y level the fosic field will display on, this is a client setting as well, so it can be adjusted to whatever a player might need.
