### ISSUE TITLE
[1.16.4] Having the Spectral Thread perk breaks the Armara Mantle

### ISSUE THREAD

**Issue by yagoplx** [HellFirePvP/AstralSorcery#1546]
The perk makes it so you never have enough charge to make the Armara Mantle recharge, so it ends up doing nothing, forever.

Reduce the charge amount needed in the default config.

**Comment by yagoplx** [comment]
I've found out that enhancing armor with Lucerna and getting some additional perks may mitigate this- but isn't that an unreasonable obstruction just to get the mantle to do anything?

**Comment by HellFirePvP** [comment]
No, this is part of how starlight charge works.
