### ISSUE TITLE
[GalatiCraft incompatibility] Rock Crystals disappearing

### ISSUE THREAD

**Issue by izShelby** [HellFirePvP/AstralSorcery#155]
Hi.
On my private server running a few different mods and sponge, I am running into a weird problem where no Rock Crystal Ore spawns at all. Also, every rock crystal that is dropped into the world appears for a fraction of a second and then disappears into thin air with sponge giving me a huge error message (linked here: https://pastebin.com/DZLnNGF5). This obviously makes it very hard to play as I can't grind crystals without them vanishing, for example. I can't seem to find someone else having this issue either so I expect some error on my part, but really can't figure out where to look next.

Forge versions and stuff are listed at the bottom of the paste linked above.
In case it helps, I'm running the following mods:
https://pastebin.com/7nRX4w7x (Sorry about the horrible formatting, but I REALLY can't be arsed to type them all out myself, I'm sure you understand :P)

**Comment by Doomgull** [comment]
Might be Sponge

**Comment by izShelby** [comment]
Thanks for the quick response.
Of course I forgot to mention that I was retrogening with the respective config option enabled. And I found out that I'm an idiot too, because apparently I was too impatient with the retrogen. I found some rock crystal ore now. So my bad on that one.
The issue with the disappearing crystals still persists though and no crashes when shift-hovering over the crystal (Although shift doesn't change anything for me, it still just shows the following: http://imgur.com/a/e6j5X )
I just threw together a test server and will run some tests. I'll tell you as soon as I find something.

**Comment by HellFirePvP** [comment]
Ouh, yea, right i forgot that i made it crash-safe so it wouldn't crash your client in case the information is missing. It not displaying anything in the tooltip is an indication that its data is missing.
Set of questions:
- Does this only happen with cheated ones from JEI?
- Does it also happen with ones obtained by breaking the ore?
- Do other Items keep their data? (Specifically if you put a constellation paper into the journal, does it keep the constellation paper; is it "still there" if you open the journal-inventory again?)
- Do Constellation papers show the same behavior? (Specifically if you find one and it 'assigns' itself to a constellation you didn't know yet? Does it keep that constellation assigned to it? In case it does so you should be able to see the constellation's name in its tooltip and you should be able to 'open' it via right-click to see the constellation's shape)

**Comment by izShelby** [comment]
I swear the game is mocking me. And I think I'm still wasting your time by being an idiot. I started taking out mods when I got fed up with always typing /give astralsorcery:ItemRockCrystalSimple, set NEI/JEI to cheat mode and voilá, those crystals work just fine.
As to your questions, I still do not gain anything from breaking the ore. I am mining it with a simple diamond pick, as mischief of mice does in his tutorial.
All other items work as intended, apart from the crash when clicking on the constellations in the journal, which many people already reported.

Sorry for wasting your time if I'm just missing something here...

**Comment by Doomgull** [comment]
...Sponge?

**Comment by HellFirePvP** [comment]
Heh.... i know what it is probably. Try removing GalactiCraft.

**Comment by izShelby** [comment]
Indeed, removing Galacticraft did fix the issue. If I remove Galacticraft however, I will get murdered in my sleep by my friends playing on the server, so I guess I'll have to work around the issue for now.
Thanks for your help.
But how did you know?

**Comment by HellFirePvP** [comment]
> But how did you know?

I'm an all-seeing god. /s

GalactiCraft is overwriting the playerEntity on serverside and messes with some checks on my end, ultimately causing this to fail. Prepare for some more issues with it until i'm releasing the next update - which will most likely be in the next days.

**Comment by izShelby** [comment]
Great, thank you so much!
