### ISSUE TITLE
[1.16.4] [Suggestion] Add new Infusion/Transmutation recipes to match the new mechanics in 1.16.4

### ISSUE THREAD

**Issue by yagoplx** [HellFirePvP/AstralSorcery#1550]
Here are some examples of Starlight Infusion recipes I think should be in the base mod due to fitting in with the mod mechanic.

Ancient Debris -> 2 Netherite Scrap (New resource, it is meant to be grindy to get)
Nether Gold Ore -> 2 Gold Ingot (Nether gold is slightly less worth in bars compared to overworld gold)
Honeycomb -> 3 Honey Bottle (Instead of getting 1 honey bottle for each full beehive, you get 9 honey bottles with this recipe if you shear for the honeycombs instead. Nice!)

Some examples of Starlight Transmutation:

Obsidian -> Crying Obsidian (There are no other ways of getting this other than rare natural buildings and piglin trading, such a recipe could come in handy for builders)

**Comment by yavincl** [comment]
Are you considering using Netherite as a resource in the crafting of future AS items? Such as the petromantic prime, for example

**Comment by yavincl** [comment]
Bump, please see the comment above me.
I no longer use Discord, so I cannot really ask over there anymore.

**Comment by PocketfulOfGeese** [comment]
This is really not the place for discussions like that. Discord in a browser would be better, or just...waiting for a response.

**Comment by yavincl** [comment]
Figured he missed the comment, it happens.

No, I'm trying to avoid social media overall, so this will suffice for now unless I need to ask a lot of questions.
