### ISSUE TITLE
[1.16.4] Pelotrio ritual can spawn neutrals, but not hostiles

### ISSUE THREAD

**Issue by yagoplx** [HellFirePvP/AstralSorcery#1551]
I'm not sure if you changed this and it is intentional, because I remember Pelotrio would summon monsters at night in 1.12.

Pelotrio ritual will succeed in spawning loads of friendly mobs during the day, but as soon as night comes it spawns nothing; the particle effects still appear, but nothing is summoned. No matter how much you boost it, it will still not spawn hostiles. Same thing even if you put a roof on the linked ritual anchor to darken it some more.

This is unlike the Nocturnal Powder which seems to still spawn hostiles but at a much slower rate.

**Comment by HellFirePvP** [comment]
The ritual suffered from the same as #1548, hence i'll mark it as duplicate and tackle that in the same issue there.
