### ISSUE TITLE
[1.16-1.15] Armara Ritual will not protect from firework ammunition

### ISSUE THREAD

**Issue by yagoplx** [HellFirePvP/AstralSorcery#1552]
Since Crossbows were added, they can be used to shoot fireworks horizontally as a form of explosive, high-damage ammo.

An Armara Ritual seems to do nothing to deflect these fireworks away. It would seem that even with the Absorption buff refresh spam of the ritual a player can be made short work of with a maxed out crossbow and maxed fireworks, so that I...
![2020-12-11_12 56 17](https://user-images.githubusercontent.com/57966308/101925684-0d72ec00-3bca-11eb-8eff-4077c69cb776.png)

**Comment by HellFirePvP** [comment]
This is in the configuration as fireworks didn't have an actual gameplay-affecting feature when this feature was made.

Default configuration will be adjusted to not include them.
