### ISSUE TITLE
Retracting pistons in the AoE of a corrupted Horologium ritual creates invisible pistons

### ISSUE THREAD

**Issue by Jeuvke** [HellFirePvP/AstralSorcery#1556]
1.16.4-1.13.4
Retracting a piston within the area of effect of a corrupted Horologium ritual creates an invisible unbreakable piston. The piston appears to be normal at first, but powering it or attempting to break it makes it invisible and unbreakable.

**Comment by HellFirePvP** [comment]
Added to the default blacklist
