### ISSUE TITLE
[1.16.4] No config option to disable spawning with the Astral Tome

### ISSUE THREAD

**Issue by aaronhowser1** [HellFirePvP/AstralSorcery#1558]
Using `astralsorcery-1.16.4-1.13.4`

**Comment by HellFirePvP** [comment]
In the serverconfig, under general, "giveJournalOnJoin"

**Comment by aaronhowser1** [comment]
Oh gosh I forgot there even was a server config lol thanks

**Comment by Suraru** [comment]
I don't see a server config, only astralsorcery-client.toml and astralsorcery-common.toml

**Comment by aaronhowser1** [comment]
in 1.13+, each world has its own folder called `/serverconfigs/`. If you're making a modpack, copy any config files you change in there to a new folder called `/defaultconfigs/` at the base installation folder.

**Comment by Suraru** [comment]
Aha, thank you so much. I did not know that.
