### ISSUE TITLE
[1.16.4]Singleplayer High Ping Lags while playing with Astral Sorcery

### ISSUE THREAD

**Issue by Hidekiranier** [HellFirePvP/AstralSorcery#1559]
I get higher ms when holding items from Astral Sorcery in my hand. Items like Resonating Wand, Linking Tool, etc.
Also higher ms while interacting with Astral Sorcery Blocks, such as the Crafting Altar, Starlight Infuser, Attunement Altar, Lenses.

**Comment by yavincl** [comment]
You mean the time it takes for a tick to complete, not ping, this is singleplayer?

**Comment by Hidekiranier** [comment]
Yes its the tps. Minecraft is telling me that it is the ms. It happens in Singleplayer, because MC Singleplayer works using a local hosted server (without internet connection, dont ask why i dont know who invented that stupid concept).
Everytime i use something from AstralSorcery the ms(tps) rises.

**Comment by PocketfulOfGeese** [comment]
ms is not tps.

What version of Forge and Astral Sorcery are involved? What launcher do you use? What other mod(s) are running at the same time? Need more info to attempt replication, unless you can provide a VisualVM profiler output for it.

**Comment by Hidekiranier** [comment]
I use the new CurseForge Launcher.
And i should consider installing VisualVM for debugging, thank you for the reminder.

Forge Version: forge-35.1.7

Modlist:

Biomes O' Plenty
Forstride
BiomesOPlenty-1.16.4-13.0.0.422-universal.jar

Bookshelf
DarkhaxDev
Bookshelf-1.16.4-9.2.16.jar

Botania
Vazkii
Botania-1.16.3-409.jar

Chisels & Bits
AlgorithmX2
chiselsandbits-0.2.7-RELEASE.jar

GraveStone Mod
henkelmax
gravestone-1.16.4-1.0.2.jar

Mekanism
bradyaidanc
Mekanism-1.16.4-10.0.17.444.jar

Mekanism Additions
bradyaidanc
MekanismAdditions-1.16.4-10.0.17.444.jar

Mekanism Generators
bradyaidanc
MekanismGenerators-1.16.4-10.0.17.444.jar

Mekanism Tools
bradyaidanc
MekanismTools-1.16.4-10.0.17.444.jar

MythicBotany
noeppinoeppi
MythicBotany-1.16.3-1.1.12.jar

Nature's Compass
Chaosyr
NaturesCompass-1.16.4-1.8.5.jar

Silent Gear
SilentChaos512
SilentGear-1.16.3-2.4.2+185.jar

Xaero's World Map
xaero96
XaerosWorldMap_1.11.1_Forge_1.16.4.jar

AE2 Extras
tfarecnim
ae2extras-1.0a-1.16.4.jar

AIOT Botania
MelanX
aiotbotania-1.16.3-1.4.3.jar

AppleSkin
squeek502
AppleSkin-mc1.16.2-forge-1.0.14.jar

Applied Energistics 2
AlgorithmX2
appliedenergistics2-8.1.0.jar

Astral Sorcery
HellFirePvP
astralsorcery-1.16.4-1.13.4.jar

AzureDooms Angel Ring
AzureDoomC
doomangelring-1.16.4-1.0.0.jar

Botania Additions
ToMe250
BotaniaAdditionsMC1.16.3-1.0.3.jar

Building Gadgets
Direwolf20
buildinggadgets-3.7.2.jar

CodeChicken Lib 1.8.+
covers1624
CodeChickenLib-1.16.4-3.5.0.398-universal.jar

CoFH Core
TeamCoFH
cofh_core-1.16.3-1.0.4.jar

Cooking for Blockheads
BlayTheNinth
CookingForBlockheads_1.16.3-9.2.2.jar

Crafting Station
tfarecnim
craftingstation-4.1.1.jar

Crafting Tweaks
BlayTheNinth
CraftingTweaks_1.16.3-12.2.0.jar

CraftTweaker
Jaredlll08
CraftTweaker-1.16.4-7.0.0.63.jar

Cucumber Library
BlakeBr0
Cucumber-1.16.4-4.1.5.jar

Curios API (Forge)
TheIllusiveC4
curios-forge-1.16.4-4.0.3.0.jar

Dark Utilities
DarkhaxDev
DarkUtilities-1.16.4-7.0.3.jar

Decorative Blocks
stohun
decorative_blocks-1.16.4-1.6.0.jar

Ender Storage 1.8.+
covers1624
EnderStorage-1.16.4-2.7.0.159-universal.jar

EnderTanks
ShetiPhian
endertanks-1.16-1.9.3.jar

Environmental Core
ValkyrieofNight
envirocore-1.16.4-3.0.4.1.jar

Environmental Materials
ValkyrieofNight
enviromats-1.16.4-2.0.4.1.jar

Environmental Tech
ValkyrieofNight
envirotech-1.16.4-3.0.4.1.jar

Fast Leaf Decay
olafskiii
FastLeafDecay-v25.jar

Flux Networks
sonar_sonic
FluxNetworks-1.16.4-6.1.5.10.jar

ForgeEndertech
EnderLanky
ForgeEndertech-1.16.4-7.0.8.0-build.0028.jar

Immersive Engineering
BluSunrize
ImmersiveEngineering-1.16.4-4.1.1-128.jar

Immersive Petroleum
Flaxbeard
ImmersivePetroleum-1.16.3-3.0.0.jar

Industrial Foregoing
Buuz135
industrial-foregoing-1.16.4-3.2.5-74675d6.jar

Iron Chests
ProgWML6
ironchest-1.16.4-11.2.10.jar

JEI Integration
SnowShock35
jeiintegration_1.16.4-6.1.1.11.jar

JEITweaker
Jaredlll08
JEITweaker-1.16.4-1.0.1.5.jar

Just Enough Items (JEI)
mezz
jei-1.16.4-7.6.0.58.jar

Just Enough Resources (JER)
way2muchnoise
JustEnoughResources-1.16.4-0.12.0.103.jar

Large Ore Deposits
EnderLanky
AdLods-1.16.4-4.1.2.0-build.0027.jar

LibX
noeppinoeppi
LibX-1.16.3-1.0.5.jar

Mana Gear
Partonetrain
managear-1.16.3-2.2.1.jar

McJtyLib
McJty
mcjtylib-1.16-5.0.15.jar

Mouse Tweaks
YaLTeR
MouseTweaks-2.13-mc1.16.2.jar

Mystical Agradditions
BlakeBr0
MysticalAgradditions-1.16.4-4.1.2.jar

Mystical Agriculture
BlakeBr0
MysticalAgriculture-1.16.4-4.1.3.jar

ObserverLib
HellFirePvP
observerlib-1.16.4-1.4.4.jar

OpenBlocks Elevator
vsngarcia
elevatorid-1.16.4-1.7.8.jar

Pam's HarvestCraft 2 - Crops
pamharvestcraft
pamhc2crops-1.16.3-1.0.1.jar

Pam's HarvestCraft 2 - Food Core
pamharvestcraft
pamhc2foodcore-1.16.3-1.0.0.jar

Pam's HarvestCraft 2 - Food Extended
pamharvestcraft
pamhc2foodextended-1.16.3-1.0.0.jar

Pam's HarvestCraft 2 - Trees
pamharvestcraft
pamhc2trees-1.16.3-1.0.0.jar

Patchouli
Vazkii
Patchouli-1.16.4-48.jar

Placebo
Shadows_of_Fire
Placebo-1.16.3-4.3.3.jar

QuantumStorage
GigaBit101
QuantumStorage-1.16.4-5.3.0.jar

RFTools Base
McJty
rftoolsbase-1.16-2.0.8.jar

RFTools Builder
McJty
rftoolsbuilder-1.16-3.0.12.jar

RFTools Power
McJty
rftoolspower-1.16-3.0.8.jar

RFTools Storage
McJty
rftoolsstorage-1.16-2.0.7.jar

RFTools Utility
McJty
rftoolsutility-1.16-3.0.19.jar

Runelic
DarkhaxDev
Runelic-1.16.4-6.0.2.jar

ShetiPhianCore
ShetiPhian
shetiphiancore-1.16-3.8.4.jar

Silent Lib
SilentChaos512
SilentLib-1.16.3-4.9.0+63.jar

Simply Light
Flanks255
simplylight-1.16.4-1.1.1.jar

Spice of Life: Carrot Edition
lordcazsius
solcarrot-1.16.3-1.9.8.jar

Storage Drawers
Texelsaur
StorageDrawers-1.16.3-8.2.1.jar

SwingThroughGrass
exidex
swingthroughgrass-1.16.4-1.5.3.jar

The One Probe
McJty
theoneprobe-1.16-3.0.6.jar

Thermal Cultivation
TeamCoFH
thermal_cultivation-1.16.3-1.0.5.jar

Thermal Expansion
TeamCoFH
thermal_expansion-1.16.3-1.0.5.jar

Thermal Foundation
TeamCoFH
thermal-1.16.3-1.0.5.jar

Thermal Innovation
TeamCoFH
thermal_innovation-1.16.3-1.0.3.jar

Thermal Locomotion
TeamCoFH
thermal_locomotion-1.16.3-1.0.3.jar

Titanium
hrznstudio
titanium-1.16.4-3.2.2.jar

ValkyrieLib
ValkyrieofNight
valkyrielib-1.16.4-3.0.4.3.jar

Wawla - What Are We Looking At
DarkhaxDev
WAWLA-1.16.4-7.0.2.jar

Waystones
BlayTheNinth
Waystones_1.16.3-7.3.1.jar

Wither Skeleton Tweaks
Shadows_of_Fire
Wither-Skeleton-Tweaks-1.16.3-5.2.1.jar

Woot
Ipsis
woot-1.16.4-1.0.2.1.jar

Xaero's Minimap
xaero96
Xaeros_Minimap_20.28.2_Forge_1.16.4.jar

XNet
McJty
xnet-1.16-3.0.10.jar

**Comment by Hidekiranier** [comment]
To be more precise, the problem mostly only occurs when holding the resonating wand, the average ms doubles up and by holding it the first time i get a massive lag spike.
But it only happens while holding the wand.

**Comment by Hidekiranier** [comment]
![2020-12-13_10 53 16](https://user-images.githubusercontent.com/75905216/102008570-e6372e80-3d31-11eb-9093-edb514bc1263.png)

A screenshot of my ingame status while holding the resonating wand.

**Comment by Penrif** [comment]
Have seen similar issues on my MP server (Valhelsia3) while holding a Resonating Wand - here's a spark sampler capture:
https://spark.lucko.me/#PkiHGWfouN
It looks to me like the search for crystal ore is triggering chunk loads for some reason.

**Comment by Hidekiranier** [comment]
Yea i think that is the exactly same reason in my case.

**Comment by HellFirePvP** [comment]
Would you mind trying this version to see if that fixed it? It now includes a check if the associated chunks are present:

https://jenkins.hellfiredev.net/job/AstralSorcery/job/1.16-indev/47/artifact/astralsorcery-1.16.4-1.13.7.jar

**Comment by Penrif** [comment]
Confirmed - spike on server and FPS on singleplayer are resolved with 1.13.7 for me.  Could still see surface fx for crystal ores as well.

Pulled my MP world down local to repro the original issue and was successful - it was a 43% increase in avg fps on my setup fwiw (16->23) with a 1-2sec initial hitch.

**Comment by Hidekiranier** [comment]
@HellFirePvP Thank you the updated version fixes my problem.
