### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by Syncyy** [HellFirePvP/AstralSorcery#156]
World is a few hours old and was running well before shutdown.
The only thing other than normal world-gen I have in my world is illuminators which I cheated in when I made the world and hasn't given me problems before. I haven't done anything else with the mod except pickup two papers from inside a shrine.

[Crashlog](https://pastebin.com/Q80rZAve)

**Comment by HellFirePvP** [comment]
Heh.. i wonder why this was never reported before. Fixed for next version...

**Comment by Syncyy** [comment]
Can't wait to start your mod again. I only got to the start of attunement last time.
