### ISSUE TITLE
How to find Luminous crafting table recipe type?

### ISSUE THREAD

**Issue by SK808** [HellFirePvP/AstralSorcery#1560]
This is my code. Why it no work?

craftingTable.removeRecipe(<item:ars_nouveau:novice_spell_book>.withTag({mode: 0 as int, spells: ",projectile,touch,self,break,harm" as string}));

var novice_book = <item:ars_nouveau:novice_spell_book>.withTag({mode: 0 as int, spells: ",projectile,touch,self,break,harm" as string});
var book = <item:minecraft:book>;
var pure_crystal = <item:elementalcraft:purecrystal>;
var water_crystal = <item:elementalcraft:watercrystal>;
var air = <item:minecraft:air> * 0;

<recipetype:astralsorcery:simple_altar>("novice_book", novice_book, 200, 200, [
air, pure_crystal, air,
water_crystal, book, water_crystal,
air, pure_crystal, air
]);

**Comment by PocketfulOfGeese** [comment]
Assuming you're using a version for Minecraft 1.12....

What do the logs say?

**Comment by SK808** [comment]
sorry its in 1.16 i dumped allrecipe types and all it comes up with is simple_alter. Im using crafttweaker

**Comment by PocketfulOfGeese** [comment]
Why not use a vanilla datapack? There's no explicit CT support added in the 1.16 alpha release at this time due to datapack support being present.

**Comment by SK808** [comment]
im trying to avoid datapacks if possible

**Comment by PocketfulOfGeese** [comment]
That's the available option at the moment. Crafting recipes in Astral Sorcery in 1.16 are fully manageable via datapacks at present.

Is there a crafting involvement that requires CT versus a datapack for Astral Sorcery going on?

**Comment by SK808** [comment]
_**recipetype:astralsorcery:simple_altar**_("novice_book", novice_book, 200, 200, [

this is the bit that i cant get working, apparently it's not teh simple alter

**Comment by PocketfulOfGeese** [comment]
Yes. The CT integration that leveraged that in 1.12 isn't present in 1.16. Again, a datapack solves this.

**Comment by SK808** [comment]
:(

**Comment by HellFirePvP** [comment]
try just "recipetype:astralsorcery:altar" - that's how the recipe serializer is called.

**Comment by SK808** [comment]
so would it be 

"recipetype:astralsorcery:altar"("novice_book", novice_book, 200, 200, [

**Comment by HellFirePvP** [comment]
Please lookup how to add/remove recipes from recipetypes on the CT documentation.
In this manner, recipes can be added with the same syntax as AS' json recipes.

relevant links:
https://github.com/CraftTweaker/CraftTweaker-Examples/blob/master/1.14/recipetypes.zs
https://github.com/HellFirePvP/AstralSorcery/tree/1.16-indev/src/main/resources/data/astralsorcery/recipes/altar

That said, we're not a CraftTweaker helpdesk. If you have further questions on how to use CraftTweaker, ask on their end.

**Comment by SK808** [comment]
that recipe id thingy is wrong, i tried it but it didn't work
