### ISSUE TITLE
Visual bug when placing a non-full block atop a 1 high pillar.

### ISSUE THREAD

**Issue by SlyScroll** [HellFirePvP/AstralSorcery#1561]
When placing a non-full block atop the pillar, the top face of the astral pillar (one tile high varient) becomes invisible. In this case it is the pedestal from reliquary which happens to be a non-full block slightly smaller than the pillar.

Note: Reported to Reliquary who directed me to report it here instead because its to do with how astral renders the block.

![image](https://user-images.githubusercontent.com/14237643/101994092-987de000-3cb7-11eb-8480-8ebb4402bed7.png)

**Comment by HellFirePvP** [comment]
Their Bounding box is set up that it's filling the entire 12x12 box on the bottom, thus minecraft's rendering presumes that the entire area is filled with a solid model, as Reliquary's passive pedestal block is set up to count as a solid.

That's not my issue and nothing i can do about it from my end as it's their block's properties.
