### ISSUE TITLE
Liquid Starlight miscolor in 1.16.4

### ISSUE THREAD

**Issue by Vousha** [HellFirePvP/AstralSorcery#1564]
Liquid starlight is white in the Lightwell and in the Liquid Starlight Bucket texture but it is blue when placed.
![2020-12-13_09 41 23](https://user-images.githubusercontent.com/75943124/102016749-0530c300-3d28-11eb-9d5a-2711fa4ce68b.png)

**Comment by yavincl** [comment]
Does not happen to me, is this using Optifine?

**Comment by PocketfulOfGeese** [comment]
Something else is causing this, probably a GL State leak, not an astral sorcery issue
