### ISSUE TITLE
[1.16.4] Dropping crystals manually is broken, crashes the game when done with dropper or dispenser

### ISSUE THREAD

**Issue by lightningstudios126** [HellFirePvP/AstralSorcery#1565]
Dropping a rock crystal or celestial crystal manually, breaking rock crystal ore, and breaking celestial crystal clusters do not create item entities (also, nothing is picked up by a hopper). 
Dropping a rock crystal or a celestial crystal with a dropper or dispenser crashes the game. 
Using the /give command to give me a crystal puts an error message in chat: "An unexpected error occurred trying to execute that command: java.lang.NoSuchFieldException: skipPhysicRenderer", but still gives the item.
It might be just a Forge problem because I know there are more recent versions available, but the CurseForge launcher doesn't have those available.

Mod versions:
- Forge: 35.1.9
- Astral Sorcery: 1.13.5
- Curios: 4.0.3.0
- ObserverLib: 1.4.4

Crash log: https://pastebin.com/9FvgD5M3

**Comment by HellFirePvP** [comment]
Fixed with 1.13.6
