### ISSUE TITLE
Rock Crystals, Celestial Crystals, and Starmetal Ingots spaz out when dropped by droppers, dispensers, or Botania's Open Crate

### ISSUE THREAD

**Issue by Jeuvke** [HellFirePvP/AstralSorcery#1566]
Forge 1.16.4-35.1.13
AS 1.16.4-1.13.6
Botania 1.16.4-410
When an Open Crate from Botania drops a Rock Crystal, Celestial Crystal, or Starmetal Ingot, the items completely spaz out and fly multiple blocks in a random direction. They can even get stuck in other nearby solid blocks. No other items from either mod do this, so I assume this is an issue with how the item entities from these items are created.

**Comment by Hubry** [comment]
Also happens with vanilla droppers pointing downwards, and presumably Quark chutes. Caused by a larger hitbox of the entity - 0.5^3 instead of vanilla 0.25^3.
