### ISSUE TITLE
[1.16.4] PerkAttributeMap Crash

### ISSUE THREAD

**Issue by BumbleCrashes** [HellFirePvP/AstralSorcery#1568]
The game runs normally and i can play my worlds. But after some time of playing it just freezes and crashes.
This issue is marked as unexpected error but what i can read it is caused by: 
hellfirepvp.astralsorcery.common.perk.PerkAttributeMap.getModifier.
This issue has been happenning ever since the version 1.13.4 and still having it in the latest 1.13.6 version.

I know little about coding, but i can confirm it is caused by this since i reported this issue in the FeedTheBeastCrashes subreddit.
Here's the Latest log: https://pastebin.pl/view/20628dc7

**Comment by PocketfulOfGeese** [comment]
Can you provide a screencap of your perk tree's selections, as well as any gear you're wearing with Attributes on them via Refraction Table enchanting, any dynamism gems, etc?

**Comment by BumbleCrashes** [comment]
> Can you provide a screencap of your perk tree's selections, as well as any gear you're wearing with Attributes on them via Refraction Table enchanting, any dynamism gems, etc?

![2020-12-16_17 34 02](https://user-images.githubusercontent.com/76133686/102419483-72ad4f80-3fc5-11eb-9550-c5014788b247.png)
![2020-12-16_17 35 07](https://user-images.githubusercontent.com/76133686/102419498-77720380-3fc5-11eb-9847-8c81ed569d1e.png)

**Comment by HellFirePvP** [comment]
Would you mind testing this again with this version?

https://jenkins.hellfiredev.net/job/AstralSorcery/job/1.16-indev/48/artifact/astralsorcery-1.16.4-1.13.7.jar

**Comment by BumbleCrashes** [comment]
So far, almost 3 hours of playing and the game didn't crashed! 
it seems it's now fixed.
