### ISSUE TITLE
shaders problem

### ISSUE THREAD

**Issue by GnomTocha** [HellFirePvP/AstralSorcery#1571]
AstralSorcery-1.16.4-1.13.6.jar
shader:Chocapic13_V9.1_Extreme_Beta_4
when playing with shaders, the night is brighter than any day and shadows during the day, or only a broken sky.

**Comment by PocketfulOfGeese** [comment]
Shaders aren't supported at all, because of shader fighting.

Check the "weakSkyRender" client config, follow the instructions there, it's the closest you'll get to supported since it disables a good chunk of AS' sky rendering.
