### ISSUE TITLE
Phantoms sometimes do not flap when caught in a corrupted Horologium ritual

### ISSUE THREAD

**Issue by Jeuvke** [HellFirePvP/AstralSorcery#1576]
1.16.4-1.13.6
Phantoms sometimes don't flap their wings when affected by a corrupted Horologium ritual. This seems to occur randomly.
(Since #1573 turned out to be intended, that must mean this is a bug.)

**Comment by HellFirePvP** [comment]
As this is a purely visual issue and can happen with any potential entity, it's not going to be tackled further unless a gameplay issue should arise, such as the entity being invulnerable or related.
