### ISSUE TITLE
[1.16.4-1.13.6, 1.13.7, 1.13.8] Infused Crystal Tools Lost Abilities

### ISSUE THREAD

**Issue by Mikachuy** [HellFirePvP/AstralSorcery#1577]
I'm currently using the Velhelsia 3 Modpack, It had just updated to their version 1.16.4, but I believe this error was existing in Pre, as well. 

I have an infused Crystal Shovel and Infused crystal pickaxe.

Shovel: Usually able to use ability to dig a large area of dirt - now only able to dig one block at a time - does not show a cooldown, as if ability has not triggered.

Pickaxe: Usually able to mine in a 3x3, without any mining area perks. Now only able to mine one block at a time. Usually able to shift + right click to use ability - for finding ores. Now, shift + right clicking seems to do nothing - there is no indicator that the ability was registered or triggered in any way. 

Troubleshooting:
Attempted to soak tools in liquid starlight in order to charge/recalculate the metadata of the infusion.
Attempted placing items on infusion area to re-infuse them (this didn't work, as they are already marked as infused tools)
Attempted updating AS pack to 1.13.7 manually (Valhelsia 3 is currently running 1.13.6).
Attempted using AS 1.13.8 from [this thread](https://github.com/HellFirePvP/AstralSorcery/issues/1574).

**Comment by HellFirePvP** [comment]
Did you disable perk & tool abilities?
Check disabling/enabling tool/perk abilities with key "v" or check what that keybind is if it's rebound to something else.

**Comment by Mikachuy** [comment]
@HellFirePvP I had it bound to another key, but it seems when it was updated, that rebind was reset. That seemed to fix the issue. Thanks!
