### ISSUE TITLE
Client will freeze and close after 5 minutes in-game

### ISSUE THREAD

**Issue by capSAR273** [HellFirePvP/AstralSorcery#1579]
Modpack: Direwolf20 for MC 1.16, version 1.1.0

https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/issues/21

Removing Astral Sorcery from the pack fixed the memory leaking, the image in the issue above has the java dump breakdown. Looks like a lot of vectors full of collision data.

**Comment by ZeroNoRyouki** [comment]
The problem is probably here: https://github.com/HellFirePvP/AstralSorcery/blob/a4b4bec48c22365af8330dfef241c48e48073696/src/main/java/hellfirepvp/astralsorcery/common/util/data/SizeLimitMap.java#L30

It's not discarding old entries

**Comment by joshuathomas2** [comment]
Can confirm this. Slowly annihilated my TPS until the server died.

**Comment by RevenantWendigo** [comment]
Can confirm. This issue brought my server to its knees. 20TPS to 3TPS until it eventually crashed (span of 10 minutes after noticing the lag).

**Comment by HellFirePvP** [comment]
Java's LinkedHashMap has a feature that allows for removing old entries, via "removeEldestEntry"as ZeroNoRyouki pointed out. This doesn't always work and breaks at random occasions it seems.
