### ISSUE TITLE
rendering error. celestial collector crystal (i think)

### ISSUE THREAD

**Issue by ironfprcefeild** [HellFirePvP/AstralSorcery#1580]
there is an error when rendering a celestial collector crystal  latest version of 1.16. error attached: 
![image](https://user-images.githubusercontent.com/76414234/102730677-7a416100-4303-11eb-8041-dc79006bada0.png)
im playing with serval other mods in no real mod pack just ones i threw together

mods listed here
wymroost
fluid storage
undergarden
Gaia dimension
gobber 2
quark
xearos minimap 
neat.

I had signed out while filling up (the starlight in the little pool) a enhanced collector crystal, when i rejoined i had extreme lag. i think its a 1 off so i restart and then nothing renders. idk!

**Comment by ironfprcefeild** [comment]
help

**Comment by ironfprcefeild** [comment]
after sitting for 30 seconds the game crashes showing the saving world screen until i close it or leave the window. i also had shulkers in my inventory if that matters?

**Comment by HellFirePvP** [comment]
However you placed that collector crystal, it lost tileentity data.
Please refrain from using mods on AS' tileentities that allow moving tileentities without breaking the block and obtaining the item - like CarryOn - or otherwise allow moving the block without actually needing to break it.

**Comment by ironfprcefeild** [comment]
works perfectly thank you
