### ISSUE TITLE
Starlight Transmutation is not working at all(almost)

### ISSUE THREAD

**Issue by Tidaveel** [HellFirePvP/AstralSorcery#1584]
Me and a friend put together a modpack for private use on his server. It's a 1.15.2 server and has been using 1.12.14. As I started on Astral Sorcery for the first time, I found that on top of all the broken textures because of Optifine, Starlight Transmutation was almost completely broken. I didn't notice it immediately because, ironically, the only transmutation that works is that for the Crafting Table.

After a fair bit of testing, I just tried starting a fresh game with nothing but  observerlib-1.15.2-1.3.2, curios-FORGE-1.15.2-2.0.2.6 and astralsorcery-1.15.2-1.12.14, started a new world, located a Shrine and tried to Transmute, but it didn't work. Have also tried with 1.12.13 to see if that was the issue but the problem remains.

![2020-12-22_16 14 39](https://user-images.githubusercontent.com/76486666/102904757-754eef80-4472-11eb-80ad-e7d3951068ca.png)

I didn't find anyone else discussing it, which I found odd so I just assumed it was something on our side at first. Now I have no clue. As the screenshot shows, the particle effect isn't happening. The screenshot just shows Iron Ore, but I've tried the other recipes I found in JEI and the crystals only seem to recognize Crafting Tables.

Hope you have a good day!

**Comment by PocketfulOfGeese** [comment]
Remove the roof of the shrine. This is the kind of thing that should go to the Discord for assistance, btw.

**Comment by HellFirePvP** [comment]
The initial auto-linking feature only works for the crafting table -> altar conversion for collector crystals spawned in structures.
Everything else needs to be manually linked later in the mod.

**Comment by Tidaveel** [comment]
Oh. Sorry for being an idiot.
