### ISSUE TITLE
Break lens stops Breaking

### ISSUE THREAD

**Issue by Shzxap** [HellFirePvP/AstralSorcery#1586]
After leaving render distance sometimes Break Lenses stop working 
it happens randomly
they are still connected to blocks
i have to link them to a new block to make them work again

here is vid:    https://youtu.be/cSBqUTyuxLI

and for some reason relinking one starts activating other back to normal
MC:1.16.4 
AS:1.13.8

**Comment by Shzxap** [comment]
breaking blocks up to the connected block fixes it too 
it looks like it thinks there is block in front of it so its not working just like without any lens on it

**Comment by HellFirePvP** [comment]
I'm not really having any luck reproducing this with multiple different setups both in singleplayer with integrated server and on 
a dedicated server and dedicated client setup.
I could conceptually grasp as to what might be failing here, but i'm not able to create a scenario where this happens i'm afraid

**Comment by Shzxap** [comment]
another vid + logs : 
[MC logs.txt](https://github.com/HellFirePvP/AstralSorcery/files/5759396/MC.logs.txt)
https://youtu.be/zXkSJ9sH1fM
