### ISSUE TITLE
Cant make luminous crafting table 1.16.4

### ISSUE THREAD

**Issue by onemorelevel0** [HellFirePvP/AstralSorcery#1587]
There is no luminous crafting table recipe in jei, and after looking up the recipe through youtube showcases, I couldn't craft it anyway. And yes, trying to craft with starlight of a crystal in a shrine on an oak crafting table. Was thinking y might be too low, but theres no mention of that as being a requirement

**Comment by PocketfulOfGeese** [comment]
Please read the entry in the Astral Tome. You place a crafting table near a shrine crystal, after removing the roof from the shrine, as the Tome states.
