### ISSUE TITLE
void mechanic (suggestion)

### ISSUE THREAD

**Issue by ironfprcefeild** [HellFirePvP/AstralSorcery#1589]
the necromantic prime while activated should break bedrock the bedrock regenerates when you take the set up away or run out of fuel in the fountain. while the void is exposed all alters above the void will gain a new charge of void, it could be used to make new items and ways to increase its charge like void relays etc.. it would bring a really powerful use to a kind of useless item and could be  used to make stronger items such as a way to manage perks in the skill tree, maybe corrupted mantles similar to the effects of corrupted rituals. just trying to give ideas :D. something I think would be really cool for the mod.

**Comment by HellFirePvP** [comment]
Not interested in involving anything regarding that, also thematically not in tandem with any other part of the mod.
