### ISSUE TITLE
Minecraft Crashing when jumping on Attunement Altar to atune player (Armara attunement perks)

### ISSUE THREAD

**Issue by Freshkillo** [HellFirePvP/AstralSorcery#1594]
Astral Sorcery Version: 1.13.8
Forge Version: 35.1.12

Crash report: https://pastebin.com/ZtRUzWqX

Issue:
Im having this issue when I jump on the Attunement Altar to enchant myself with Armara perks.

**Comment by HellFirePvP** [comment]
This is an issue with Traveler's Index.

**Comment by Freshkillo** [comment]
Omg how fast do you reply?? Thanks a lot!!!
