### ISSUE TITLE
Seemingly Random Crash to Desktop

### ISSUE THREAD

**Issue by unfamoushero** [HellFirePvP/AstralSorcery#1597]
## Minecraft version:
1.12.2

#### Astral Sorcery version:
1.12.10 - 1.10.21

#### Forge version:
1.12-forge-14.23.5.2854

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
Sevtech Ages of the Sky modpack - https://www.curseforge.com/minecraft/modpacks/sevtech-ages-of-the-sky
with Optifine 1.12.2_HD_U_F5

## Link to full crash log
https://pastebin.com/JZD49nNx

#### How to reproduce:

1. Boot up the game with the aforementioned mods installed/active
2. Either enter the Betweenlands Dimension via the portal, or relog into minecraft after having exited/crashed inside said dimension.
2. Play the game inside the Betweenlands Dimension normally for roughly 5-10 minutes, within sight of the original portal tree
3. With no consistently perceivable trigger on my end, the game will crash to desktop.

#### Expected result:
Being able to explore the initial area of the Between lands and start getting into the mod for fun and profit.  

#### Actual result:
Game crashes after a short period of play.

#### Pictures:
n/a

It is worth mentioning that I originally submitted this same bug to the Betweenlands staff already, who indicated it seemed to be an issue in Astral Sorcery, rather than Betweenlands itself, so I came over here.

**Comment by HellFirePvP** [comment]
Well, after talking with the BL people, i'm not sure what the issue here would be unfortunately...
The report suggests a CME as potentially entries from the tick listener list for players get removed/added, however as that is not the case after startup finished for player-relevant tick-listeners, i'm not sure what's happening there.

**Comment by unfamoushero** [comment]
Do you have any general recommendations of things to try in this case?

**Comment by HellFirePvP** [comment]
Unfortunately since i don't really know the source of this issue, not really :|
