### ISSUE TITLE
Add ability to remove Astral Tome from Lectern

### ISSUE THREAD

**Issue by SynfulChaot** [HellFirePvP/AstralSorcery#1598]
There does not appear to be a way to remove the Astral Tome from a Lectern short of destroying the Lectern.  Could there be a method added that is less destructive?  I noted that the vanilla Book and Quill in a Lectern adds a 'Take Book' button below the normal UI.  Perhaps something similar could be added?

**Comment by HellFirePvP** [comment]
Due to the amount of work this poses, for now i won't look into this further.
