### ISSUE TITLE
[Suggestion] Sleep option

### ISSUE THREAD

**Issue by Endmateria** [HellFirePvP/AstralSorcery#160]
I ran into another mod (MDE Core) that has a config that allows you to sleep through the daytime.  I thought that might be a nice feature for your mod, considering it's a night themed mod.  Not that I can't just use his mod for this perk (which I mainly use with your mod in mind), it's just that less mods that do more is usually better than more mods that do less.

**Comment by HellFirePvP** [comment]
No. This has been suggested multiple times (not on the issue tracker yet though). I am very much against adding such a feature to AS itself. And IF then it'll be something that's very late-game into the mod.

The problem with this is that it immediately destroys parts of the mod's design and idea. so. no. will not happen anytime soon.

**Comment by Endmateria** [comment]
Yeah, sorry... I looked through all the open and closed issues before asking.  Was trying to avoid making an annoying and repetitive suggestion.  Oh well, thanks for the great mod man.  You do good work.
