### ISSUE TITLE
Weak Sky render in 1.16.4 and toml config formating.

### ISSUE THREAD

**Issue by PenumbraStar** [HellFirePvP/AstralSorcery#1600]
I frequently play with shaders, and noticed that the weak sky render is no longer available within the configs. I am assuming `skyRenderingConstellations `is the replacement to it, however It appears to not be functioning for me. Before I try and troubleshoot further I just wanted to check the format that you need to add dimension IDs to the list. Currently I only have `skyRenderingConstellations = ["minecraft:overworld"]`
Is this the correct format? Is the config not implemented yet? Or have I done something completely wrong.
Sorry about bringing up an issue that I know is not fully supported, thank you for all your hard work on the mod! I look forward to solving this issue.

**Comment by HellFirePvP** [comment]
That is indeed the correct config option and the correct dimension name for the overworld.

It seems like Optifine has changed something with its shaders in 1.15+ so i've seen a lot of examples where this still doesn't work properly. As it stands i can't do much about it either unfortunately.

**Comment by PenumbraStar** [comment]
Ah, sorry. Just wanted to try and see if there was anything I could do on my end to solve this. Thanks for the quick response!
