### ISSUE TITLE
Vicio Mantle with Flight Perk drains Starlight Charge in Vicio Ritual Area

### ISSUE THREAD

**Issue by Psithief** [HellFirePvP/AstralSorcery#1601]
Version: 1.16.4-1.13.6

If the player wears a Mantle of the Stars tuned to Vicio and has the Spectral Wings perk, they have flight, and it drains starlight charge.
They also have flight in the range of a Vicio Ritual.

If the player has both effects, the Spectral Wings perk still drains starlight charge but the player doesn't stop flying if it runs out.

**Comment by HellFirePvP** [comment]
While i can "fix" this for this specific instance, there's no way to track which mod might grant flight or if the player is currently flying through another mods' item/mechanic.
So this would still drain in case flight is granted through some other means by other mods.

**Comment by Psithief** [comment]
The issue is this makes using the formation wand difficult when trying to build, as there are often mods that give +block reach as an enchantment on armour and I wanted to place some blocks by hand and some with the formation wand.

**Comment by irisfofs** [comment]
A "fix" for just the Vicio mantle + Vicio ritual interaction would still be helpful, since it's local to this mod (and I'm currently dealing with it myself).
