### ISSUE TITLE
Add a way to disable the Mantle of Stars' Airwalk ability

### ISSUE THREAD

**Issue by carmeops** [HellFirePvP/AstralSorcery#1603]
i got the Aevitas Mantle, no need to care about food and health anymore, great!

but the air walk ability that goes with it is the most annoying of thing, on a laggy server it takes forever to go down one block at a time, and i already wear an angel ring from another mod, i don't care about falling, i want to fall! i want to go down the stairs without having to crouch the whole way down

the only control i could find is the keybind to "toggle perk and tool abilities" but even when i set to disable, i still airwalk! please add a keybind to toggle that as well, while keeping the food and health active, thanks

**Comment by HellFirePvP** [comment]
Added into the toggle perk & tool abilities keybind stuff

**Comment by CyanSlinky** [comment]
Keybind doesn't work properly, the bar over the xp bar drains when they keybind is enabled but the ability itself doesn't get disabled when you deactivate the keybind.
