### ISSUE TITLE
[1.16.4-1.13.8] Crystal Sword has incredibly low attack damage regardless of stats

### ISSUE THREAD

**Issue by Pelkel** [HellFirePvP/AstralSorcery#1605]
We updated our server to Astral Sorcery 1.13.8 and our Size/Shape VI Crystal Swords reduced their damage to only around 6.5 from their previous 12-13ish (do not recall exact numbers.  Had Sharpness VII on them so they were at 17.32).  I crafted a brand new sword and it also only had a damage modifier of 6.6 with similar stats.  Unsure if this is by design or potentially a bug as I noticed a previous report stating that Crystal Swords suddenly had very low damage suddenly after an update.

**Comment by HellFirePvP** [comment]
Yes, the attack damage for crystal swords was lowered one or two versions ago; not to have "incredibly low attack" but to be more in-line with existing options.
Exact values of AS tools and how much specific attributes impact the tool's efficiency or other properties are subject to adjustments, especially in its early development cycle for 1.16

**Comment by Pelkel** [comment]
Just so I know I'm doing everything correctly (and if so, then I suppose this would be my feedback), Size/
Shape VI are the highest the sword can achieve, correct?  Because if so, the reason I mention the attack as being incredibly lower is that a VI crystal sword is below both diamond and netherite with the updated numbers we've seen.  For the amount of work that goes into shaving and customizing all of the crystals and properly customize, it seems to me at least that I may as well stick with diamond then, or in the case of the pack we use (velhelsia 3), emerald via villager trades.

Either way, thank you for the timely response and answer.

**Comment by yavincl** [comment]
Reducing power creep? Nice.

Hope it does not get as bad as with 1.12.2 where you can become literally immortal and one shot things with a single mod about purple dragon ingots

That isn't astralsorcery's issue per se but what ends up in popular modpacks or not will see different outcomes.

-------- Mensagem Original --------
Ativo 28 de dez de 2020 11:18 AM, Pelkel escreveu:

**Comment by Pelkel** [comment]
Sure, and I'll definitely agree the last thing needed is to reach the ridiculous 65 Hearts of Damage for maxed out purple and orange ingots the mod (that was insane, no argument there, and I'll even agree the base purple 18(?) was suuuuuper high as well), but at the same time consider the following:

Iron Sword: 6 dmg base
Diamond Sword: 7 dmg base
Netherite Sword: 8 dmg base
Current Size/Shape VI Sword (according to the numbers I'm currently seeing): 6.6 dmg

-An iron sword just requires you to make a stone pick and dig down far enough to find an iron vein.  Easy Peasy.

-A Diamond Sword requires iron tools and going down towards lava, but vein mining is still a fairly successful tactic even these days.  This does require a bit of time.

-Netherite requires work.  Assuming you're using Astral, you can get away with 2 Debris and starlight infusion, + gold ingots.  Upgrade a Diamond Sword with a single ingot.  But you do have to Nether Dive.

-Size/Shape [VI] requires advancing into Astral, getting to at least Attunement so you can craft a Starmetal Cutting Tool to properly customize yours pieces.  It also requires you to have dug to bedrock and gotten lucky on your initial Rock Crystal hits.  You then have to grow/split/grow until you have the pieces you want, and then successfully shave them off into singular [I] chunks.  You then submerge those chunks into multiple buckets of Liquid Starlight with the other shaved [I] chunks to customize two crystals to your desired levels.

(Now I'll mention this part again as an aside:  To my knowledge, the highest a Sword can achieve is [VI] in a category where two separate crystals both have a [III] and get slammed into a sword formation.  I have attempted to achieve a [IV] on a crystal but it has never worked and I stopped trying after wasting 7 other crystals.  If [IV] on a single crystal is possible, the rng is so low that it isn't worth it, or something is bugged.  So in my experience, the highest a sword can achieve is three crystal stats at [VI] and one at [II], for a total of [XX] between all crystal stats.  If more is possible I would very much like clarification on how to achieve this.)

My argument is that for the level of work and time that has to be put into celestial crystals to achieve what is (again to my knowledge) the maximum level of sword, the damage of said sword should at least be on the level of Diamond, if not slightly higher, otherwise I may as well just slap unbreaking and mending on the Diamond Sword and call it a day, because those two enchants essentially negate the advantage of Astral Tool's high durability if I'm killing Skelebones and Zombos faster with Diamond than with Crystal when I'm out adventuring and caving.

I actually really enjoy Astral Sorcery.  When I finally learned the process when I first tried it in 1.12 (in a pack that also had purple and orange ingots), I came to really love everything about it aside from the tools, because they degraded over time and could never be restored to their full glory, losing a bit every time you put them through the repair and grind process, so I ignored them for things like Emeradic which were just...good.

When we switched over to the more up to date pack and server with Velhelsia, I went straight into Astral again.  And was really excited because the tools had changed how they operate and had become far more usable and useful.  But with this most recent change, there really is no point to using the sword (I do not consider infusion of crystal swords worthwhile as the AOE is indiscriminate in who it affects aside from the user, if I have to have a button to turn off the effect so I don't kill friendlies with it, I may as well just not use it).  I am far better off just taking anything I would do with a crystal sword and instead applying those things to a Diamond Sword + Mending/Unbreaking.

I dunno.  That's just how I see things at least.  Like, I get not wanting to powercreep everything out of existence, but when I can make something better just by attaching two diamonds to a stick instead of going through a whole process with multiple crystals and buckets of starlight...well, why would I do the latter?

**Comment by HellFirePvP** [comment]
As mentioned above, things will be adjusted with 1.13.9 ...

**Comment by Pelkel** [comment]
Oh, no, I'm aware.  Sorry if that came off...however it may have come off.  I was just trying to better explain my feelings.  I meant no offense or to "beat a dead horse" as it were.
