### ISSUE TITLE
java.lang.IllegalStateException: Already building!

### ISSUE THREAD

**Issue by erri120** [HellFirePvP/AstralSorcery#1607]
Exception when trying to use the Astral Gateway: https://gist.github.com/erri120/1958d3608ab2837f38718c1ef5404cf8

https://github.com/HellFirePvP/AstralSorcery/blob/1.16-indev/src/main/java/hellfirepvp/astralsorcery/client/util/RenderingUtils.java#L282

**Comment by HellFirePvP** [comment]
#1592
