### ISSUE TITLE
What Shader is compatible?

### ISSUE THREAD

**Issue by ELCuleroPingon** [HellFirePvP/AstralSorcery#1609]
Currently tried with the newest BSL shaders and I had varying effects on my two different pc's on one the skybox was a bunch of rays that made the game unplayable and on the other the sky's horizon doesn't exist.

**Comment by PocketfulOfGeese** [comment]
None are fully compatible. Some may be partially compatible if you use the weakSkyRender config in astralsorcery-client.toml, but it's unsupported either way.
