### ISSUE TITLE
Can't get attuned?

### ISSUE THREAD

**Issue by izShelby** [HellFirePvP/AstralSorcery#161]
Hi, me again.

I suspect I'm being an idiot again, but as this mod isn't on the minecraft forums, I have to ask here.
Here's the problem: My attunement altar works just fine, it even attunes the crystals with the proper constellation, but it won't attune me. Is there more to it than just standing on it when it's lit up and the respective constellation is visible?

(I even tried removing Galacticraft again, in case it's that. No such luck this time.)

**Comment by izShelby** [comment]
Issue randomly resolved itself. Go figure.

**Comment by Flexo013** [comment]
I am also encountering this issue. Maybe reopen it again?

I am using version 1.8.4 of Astral Sorcery as part of FTB Horizons III

**Comment by Doomgull** [comment]
No. Go to the AS discord and get some troubleshooting assistance.
