### ISSUE TITLE
Crash whenever Formation wand is crafted and held after a few moments.

### ISSUE THREAD

**Issue by RafikisCoconuts** [HellFirePvP/AstralSorcery#1610]
Using the Valhesia 3 modpack.

New to crash reports and tech jargon.

I used back ups to before the wand was crafted multiple times, doing things differently prior to crafting each time, i.e. moving the entire starlight altars location and waiting a few in game days to see if the issue was being caused by something else and the timing was coincidence(The game would continue until the wand was crafted and used). 
Also went into a creative world and used the wand with no issues, so if possible any help fixing this so I can utilize this mod further in my streaming would be SUPER helpful.

Much Thanks, 
Rafikis Coconuts

P.S. Go easy on this old timer, here is my crash report in its entirety.

Edit: https://gist.github.com/HellFirePvP/9f209449e2c702212f71ffea3254d2b5

**Comment by HellFirePvP** [comment]
https://github.com/jaquadro/StorageDrawers/issues/902
https://github.com/HellFirePvP/AstralSorcery/issues/1418
and others

**Comment by RafikisCoconuts** [comment]
Holy cow, sorry I didn't realize it had already been posted, as a google search for such results came up empty-handed. Thanks so much for the info. One final question involving the same problem.

Would this mean the wand will be fine so long as I stop using/stop looking at any of the drawers from StorageDrawers*?

Thanks again for the fast reply for my issue, you guys are really on it!

*Edit: StorageDrawers, not RefinedStorage

**Comment by HellFirePvP** [comment]
The drawers in question are from the StorageDrawers mod.

So yes, everything's fine, it's just that they didn't implement a check in the drawers and don't fix it i guess..

**Comment by RafikisCoconuts** [comment]
Thanks again for the quick answers and solving my issue the best you can. Means a great deal and I love what all your mod offers!
