### ISSUE TITLE
[1.16.4] Can I setup max lvl for perk tree? 

### ISSUE THREAD

**Issue by Donelllla** [HellFirePvP/AstralSorcery#1613]
I would like to be able to adjust the max level for a lot of fun.

**Comment by PocketfulOfGeese** [comment]
Yes, there's a config value for it.

**Comment by Donelllla** [comment]
Where can i find it?

**Comment by HellFirePvP** [comment]
Called "perkLevelCap"

**Comment by Donelllla** [comment]
I'm a little silly. Where to find this parameter. In the config folder, I only have the world generation settings

**Comment by HellFirePvP** [comment]
there's 3 configs, as per forge's config standard:

- \<mc directory>/config/\<modid>-client.toml - the client config for mods. is only loaded on the client
- \<mc directory>/config/\<modid>-common.toml - the common config for mods - is loaded for both server and client, but the server doesn't override client configs when joining a server
- for singleplayer servers:
\<mc directory>/saves/\<worldname>/serverconfig/\<modid>-server.toml
for setup dedicated server:
\<mc directory>/world/serverconfig/\<modid>-server.toml
the server config. is loaded on the server and gets sent to the client upon joining a server

what you're looking for is AS' server config.

**Comment by Donelllla** [comment]
Thank you very much
