### ISSUE TITLE
The Astral Tome does not list the correct modifiers for faint constellation ritual data.

### ISSUE THREAD

**Issue by Jeuvke** [HellFirePvP/AstralSorcery#1614]
The Astral Tome does not list the correct values for the modifier constellations Gelu, Ulteria, Alcara, and Vorux, which were updated in 1.13.8. It also does not list the new Potency modifier that was added in the same update.

**Comment by PocketfulOfGeese** [comment]
https://github.com/HellFirePvP/AstralSorcery/pull/1842 submitted to resolve.
