### ISSUE TITLE
Astral Sorcery Crash on load

### ISSUE THREAD

**Issue by bluev1121** [HellFirePvP/AstralSorcery#1615]
Occurs when starting Minecraft, very light modlist. Looks to be related to constellation rendering?

https://pastebin.pl/view/8f065aa5

**Comment by PocketfulOfGeese** [comment]
You're out of memory, allocate more. Not an error in code, only in memory cost. You have less than 1 GB of memory allocated:
"Memory: 305133816 bytes (290 MB) / 900878336 bytes (859 MB) up to 1037959168 bytes (989 MB)"

Time: 1/1/21 8:43 PM
Description: Registering texture
 
java.lang.OutOfMemoryError: Registering texture
        at org.lwjgl.system.MemoryUtil.nmemReallocChecked(MemoryUtil.java:484) ~[lwjgl-3.2.2.jar:build 10] {}

**Comment by bluev1121** [comment]
Got it, updated java version aswell and it seemed to fix the issue without allocating more memory... just posting this for information purposes cuz I think its interesting that the 64 bit version seems to run leaner
