### ISSUE TITLE
[1.16.4] Crystal Cluster might not spawn on the block the crystal submerged in liquid starlight is on.

### ISSUE THREAD

**Issue by Ruchian** [HellFirePvP/AstralSorcery#1618]
While trying to figure out how your mod works for days (in game... I should have read code I guess) on an online server in survival, I discovered a couple of issues.

There is no documentation about the stats and their limitations. Focus: stats, Purity,  are limited to II apparently while Size, Shape and Collection Strength are limited to III.
Each Crystal can only possess 10 stat points, which took me forever to figure out.
Once saturated, they will still consume crystals. They will also still turn into clusters if Starmetal Dust is provided in Liquid Starlight.
While not saturated they gain a random stat by leaving it in liquid starlight (usually Size or a Focus)

Throwing two crystals of the same size one pool with slightly different stats, trying to add them together might make them lose Purity. (the rate for this is kinda high), I am not sure why though.) For this reason currently you have to split one of them at risk of losing stats and make sure it has as little stats as possible. Purity is hard to get your hands on.
I noticed on the other hand, that there is an excessive amount of Focus: stats and Size for some odd reason. If you grow a crystal, they will get at least two focusses and they also seem to prefer dim constallation focusses to make it worse, since its difficult to attune those.
I have had so many crystals with either four focusses and Ritual Range or something kinda nonsense.
The manual doesn't make much sense either, as it says that you need to attune a crystal before it starts to focus, but you can have a focus and attune it to something else entirely.

Anyway, for my bug report:

Minecraft 1.16.4
Forge: 35,1.13
Mod version: 1.13.8
Dedicated Server
Modpack: yes (allthemods6 1.3.7, though I think this is present everywhere.)

When you submerge a crystal with starmetal dust in liquid starlight while it isn't completely sealed in 4 full blocks, if it is near the edge enough, the item will disappear, the starlight will remain, and where it spawns is next to the starlight liquid sourceblock, replacing what was next to it.
Poor me had next to it my tank filled with liquid starlight and it was overwritten by a cluster.
so uh, I lost 16 buckets like that, but yeah-
anyway, the pool where the item was in was still fine interestingly, so I guess it is suppose to replace that pool after the item disappears or something. I haven't checked the code.

Meh-
My experience was kinda hell, trying to get my crafting table to have max starlight without help or knowledge beforehand. That is also due to it all happening online in a dedicated server where people can instantly sleep the night away preventing mobs and my progression with this mod. As such I needed enough sources of starlight to use during the day to even do minimum crafting things, though yeah I realize this is a core mechanic being voided due to another mod. (it cannot magically keep it night or something).
People can be very annoying like that, but yeah anyway, as such I needed enough collector crystals which is why I spended real life days on that server opening lootboxes- I mean trying to get my hands on the right stat / slow liquid generation / exciting moment when that crystal finally ... maybe have grown a bit in a stat or gained a new one.. aaaa.
Anyway the experience made me dislike the mod completely.

Consider what I wrote about the manual a review. I realize you can't change people's behavior, nor have any influence on what they put in modpacks, but yeah- unfortunately sleep-away-instantly-mods (requiring only 1 out of 6 people to sleep or 2 out of 12 or something) kinda mess things up, especially the experience. (They log in, they sleep before you can even ask them not to.)

Reason for edit:
forgot something + ,more info.

**Comment by HellFirePvP** [comment]
If you wish to suggest changes or improvements, please do so in its own issue.
Keep 1 issue to 1 topic/suggestion/issue and don't mix multiple as it makes things harder to categorize.

Regarding the bug-part of this:
Result of mismatch between liquid-starlight entity collision and the entity position. Scheduled to be fixed for 1.13.10

Regarding the multiple "feedback" comments:
- Yes, crystal stats have different generation weights depending on their category.
- That unfortunately is the life on a multiplayer server. i don't feel like butchering the mod for the purpose of nicer gameplay on large MP servers though
- Yes crystals have property caps. I'll see to including a more clear description of that in the tome soon-ish

**Comment by yavincl** [comment]
I'm quite curious about what kind of monster computer is running that dedicated server. I haven't had much luck

with 1.16 packs or anything above 1.12 due to memory constraints mostly. Imagine ATM6.

**Comment by Ruchian** [comment]
I just wanted to report the bug.
My desire to vent a bit made me post a lot more. Thanks for reading at least.
I get you don't want to butcher the mod yeah, its just heavily unfortunate, the circumstances that are common place in servers. (including plugin vanilla servers). I am hoping at some point the likelihood of Focus stats is somewhat less common than the others or that they are limited to one per crystal, instead of having one consist of those entirely, but I think this stuff is still an experiment and being thought through so I just wanted to watch and see where the development was going basically. Its currently present at least.  Meh- Yes I get it make another topic for it, etc. I might do that at some point. xD Depends...

The mod is interesting at least and well programmed from what I can tell. Thanks for the quick reply as well. I did enjoy the light shows and reading the lore in the tome. xd

To answer the question comment. The server is run on Serverminer.com
yeah I can't run a dedicated server + my client on my own system either, but the server takes away some of the load making it playable.

**Comment by Algester** [comment]
Well I found out the Hammocks from Comforts mod makes it so if you sleep on it on the day time it turns to sun set... I havent tried how this mod interacts with a sleep voting system

**Comment by Ruchian** [comment]
This.... sounds convenient.
Awesome. ;p
I'll try that out next time to see what happens. xD
