### ISSUE TITLE
Tome says Rock Crystals generate more liquid starlight than Aquamarine. Tome is wrong.

### ISSUE THREAD

**Issue by Moleculor** [HellFirePvP/AstralSorcery#1619]
I set up twenty lightwells. Put in ten standard aquamarine. Put in ten Size 1 crystals. Before I could even *finish* putting in all ten rock crystals, one of the rock crystals had broken, and a second broke within seconds of me finishing placing the last one. 

By the time I was down to the last rock crystal, I still had seven aquamarine remaining. 

Rock crystals do not provide more liquid starlight than aquamarines. A large, well shaped one might, but the book does not say the crystal must be large and well shaped. 

![image](https://user-images.githubusercontent.com/3865976/103501283-5c9bed80-4e13-11eb-9546-ddc2a3f0ae04.png)

**Comment by yavincl** [comment]
I noticed this as well. Rock crystals need a buff on lightwells.
