### ISSUE TITLE
Server Crash Astral Sorcery 1.4.0 (1.11.2)

### ISSUE THREAD

**Issue by Endmateria** [HellFirePvP/AstralSorcery#162]
Downloaded the newest AS 1.4.0. for MC 1.11.2 and it immediately crashed server at startup.  Here is the crash log and crash report...

Crash Report: https://gist.github.com/Endmateria/16757d985228c266da483403d67b3874

Log: https://gist.github.com/Endmateria/3aa2333ea805f05103f7f7064d1e417c#file-latest-log

MC 1.11.2
Forge 2296
AS 1.4.0.

**Comment by HellFirePvP** [comment]
Yep, *facepalms*

**Comment by HellFirePvP** [comment]
Re-uploaded, should be approved soon-ish. once it is approved, i'm gonna close this issue.

**Comment by Endmateria** [comment]
This is why I don't ever want to be a coder.  One character out of place and the whole world goes to shit hahaha.  Thanks for the quick fix!

**Comment by HellFirePvP** [comment]
No problem, just waiting on the curse team to approve it...
