### ISSUE TITLE
The Mineralis ritual can convert stone into nether gold ore

### ISSUE THREAD

**Issue by Jeuvke** [HellFirePvP/AstralSorcery#1624]
1.16.4-1.13.9
Title. Maybe let netherrack be converted into it instead?

**Comment by PocketfulOfGeese** [comment]
Look into the "replaceableStates" serverconfig inside the astralsorcery.toml. This allows for setting what blocks the ritual can convert, and has been available since later MC 1.12 releases.

**Comment by Jeuvke** [comment]
> 
> 
> Look into the "replaceableStates" serverconfig inside the astralsorcery.toml. This allows for setting what blocks the ritual can convert, and has been available since later MC 1.12 releases.

You are completely misunderstanding what this is about. The bug is that the Mineralis ritual can convert stone into an ore that's based on netherrack, which makes no sense at all.

**Comment by HellFirePvP** [comment]
Unfortunately, nether gold ore is in the tag for gold ores :/
Making it kinda awkward to differentiate between normal gold ore and nether gold ore.. i'll see what there is i can do about this.

**Comment by HellFirePvP** [comment]
As was discussed on discord, nether gold ore doesn't pose a difference to normal gold ore in terms of resource outcome.
Additionally, many other mods include their marble/basalt/limestone/... ores into the normal ore tags, so if a pack wants to strictly only include stone-ores, the config provides the necessary configuration options.
