### ISSUE TITLE
Celestial Crystal cluster spawning improperly? (Bug?)

### ISSUE THREAD

**Issue by RightHandMan** [HellFirePvP/AstralSorcery#1627]
Essentially I set up a starmetal and liquid starlight block right next to one of the naturally spawning collector crystals to boost the growth of the crystal cluster once it formed. My best guess is the stardust and crystal items I dropped into the liquid starlight were physically in the block space of the crystal, so the cluster spawned in and deleted the Vicio collector crystal. It also did not consume the liquid starlight. I linked a screenshot if it helps. 

I'm using Astral Sorcery version 1.13.8 in Direwolf 1.16.4 if that helps at all. 

[https://imgur.com/a/gjbLgSo](url)

Edit: I just now confirmed that it is repeatable using the same world just in creative. 
[https://imgur.com/gallery/QWIck2m](url)

**Comment by PocketfulOfGeese** [comment]
#1618
