### ISSUE TITLE
Astral Sorery Configure Files not being Generated

### ISSUE THREAD

**Issue by Denthris** [HellFirePvP/AstralSorcery#1628]
In Previous versions of Astral Sourcery, alot of the configuration for the Mod showed up in config\astralsorcery.  While astralsorcery-common is being generated,  This prevents modifying of the rituals, such as the ores found in Mineralis, as its not creating any modded ore.

We are using a slightly modied Direwolf 1.6 pack.

**Comment by PocketfulOfGeese** [comment]
Config files have changed a lot in 1.16 versions. Server-side configs are located either in the pack's "defaultconfigs" directory where it applies to all worlds created using that pack, or inside the "saves" directory for the world.

Client configs are still where they are normally found, under the configs directory path.
