### ISSUE TITLE
Server stucks when player join in

### ISSUE THREAD

**Issue by calebxzhou** [HellFirePvP/AstralSorcery#1629]
Hello, I met a crash problem. 
When a player joined, the server stopped working and then crash.
The server is running on Forge 35.1.13.
[crash-2021-01-08_02.38.25-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/5785667/crash-2021-01-08_02.38.25-server.txt)

**Comment by calebxzhou** [comment]
The version of Astral Sorcery is 1.13.9.

**Comment by HellFirePvP** [comment]
Update ObserverLib to 1.5.1

**Comment by calebxzhou** [comment]
That works. Thanks.
