### ISSUE TITLE
Lightwell accepts more than one item in its inventory.

### ISSUE THREAD

**Issue by Perlo0ung** [HellFirePvP/AstralSorcery#1630]
More than 1 item can be inserted from the bottom into lightwells, tested with cc turtles and xnet. 

Version used: astralsorcery-1.16.4-1.13.8

![title](https://i.imgur.com/spkd7Jl.png)

**Comment by HostPants** [comment]
> More than 1 item can be inserted from the bottom into lightwells, tested with cc turtles and xnet.
> 
> Version used: astralsorcery-1.16.4-1.13.8
> 
> ![title](https://camo.githubusercontent.com/8394e8044dd1a9ca3ecd7a026133b78e241ffdd2a46f9f9ce4d4e509b74e23c4/68747470733a2f2f692e696d6775722e636f6d2f73706b64374a6c2e706e67)

I don't know if I should create new issue, but I think I stumbled across the variant of this bug where i could just repeatedly spam-right-click on a lightwell with aquamarine in my hand. It would use 1 item but produce more than 1000 mB liquid in total. I'm currently playing in ATM 6 v.1.3.9b on minecraft v.1.16.4.
