### ISSUE TITLE
[Suggestion] Support for Multiverse-Core plugins

### ISSUE THREAD

**Issue by yonghenglunhui** [HellFirePvP/AstralSorcery#1636]
1.15.2, Ancient Shrines cannot be generated in the world generated by Multiviverse-Core. This prevents my server from using this excellent mod  :(

**Comment by PocketfulOfGeese** [comment]
Non-Forge environments are not supported.

That said, that needs a ticket opened with the plugin to determine why the world generation from tgis mod is not working inside it.
