### ISSUE TITLE
[1.16] Lucerna ritual causing server crash

### ISSUE THREAD

**Issue by MuricanSWAG** [HellFirePvP/AstralSorcery#1637]
on an All the Mods 6 server I am playing on with friends, I am the only one who has done enough astral sorcery to have a ritual. The only ritual I have up is lucerna and I am pretty sure it has caused the server's last three crashes. I do not know if this is an issue with all rituals or just lucerna. running AS 1.16.4-1.13.9

[crash-2021-01-09_16.24.05-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/5792775/crash-2021-01-09_16.24.05-server.txt)

[crash-2021-01-09_15.55.22-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/5792776/crash-2021-01-09_15.55.22-server.txt)

[crash-2021-01-09_22.47.34-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/5792773/crash-2021-01-09_22.47.34-server.txt)

**Comment by HellFirePvP** [comment]
Nothing to do with AS or rituals.
Update observerlib.
#1629
