### ISSUE TITLE
astral sorcery x carry on dupe bug

### ISSUE THREAD

**Issue by Shzxap** [HellFirePvP/AstralSorcery#1638]
this duplicates container only

Expected Behavior
pick up chest

Actual Behavior
picking and braking chest at the same time

Steps to Reproduce
having active perk from astral sorcery "mining size"

Version of Minecraft, Carry On, Forge
minecraft 1.16.4
forge 35.1.28
carry on 1.15.1.7
astral sorcery 1.13.8

Screenshots encouraged
https://youtu.be/ZoidiqKOhbY

**Comment by HellFirePvP** [comment]
I might wanna add that CarryOn doesn't "check for protection stuff" as it proclaims in the relevant section of code.
So this might pop up again, but then with certain blocks which i can't do much against then.
