### ISSUE TITLE
Move Ritual with Pistons. Ritual now perm where it was moved from.

### ISSUE THREAD

**Issue by ChakatSilverpaw** [HellFirePvP/AstralSorcery#1639]
So, I was trying to get my ritual to Only effect a smallish portion of Ocean. So, I build it a decent distance away. It was too far, So I dug it up and moved it closer, like 3 times, Got sick of digging and replacing used Pistons to do it. Now Ritual is there forever with no Pedestal or Crystal. I have a Crash log caused by it, but unsure if the crash is directly related.
[crash-2021-01-10_11.47.58-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/5793785/crash-2021-01-10_11.47.58-server.txt)

**Comment by PocketfulOfGeese** [comment]
Don't use pistons to move TEs. Try using the "performNetworkIntegrityCheck" config in the astralsorcery.toml config in the serverconfig to force a rebuild, but...you may need to use external tools to correct.
