### ISSUE TITLE
Can' t enter the world

### ISSUE THREAD

**Issue by forestbat** [HellFirePvP/AstralSorcery#164]
I updated CCL，DE，AS and FTB mods to the latest，and the game stopped when the world is loading。
![qq 20170511172155](https://cloud.githubusercontent.com/assets/23413915/25954682/98d30b8e-3699-11e7-9eef-d2705bb5560d.png)
I think it has relation with AS，and this is the log：
[fml-client-latest.txt](https://github.com/HellFirePvP/AstralSorcery/files/993346/fml-client-latest.txt)

**Comment by HellFirePvP** [comment]
Journeymap is at fault

**Comment by Saereth** [comment]
pretty sure that's Mo'Creatures
