### ISSUE TITLE
Crashing when looking at certain blocks with formation wand.

### ISSUE THREAD

**Issue by Grzesiu447** [HellFirePvP/AstralSorcery#1641]
I was using formation wand, when I looked at some block from other mod.
I couldn't get back on the server, my friend had to teleport me.

Valhelsia 3 - 3.1.4 or 3.1.3

[crash-2021-01-06_18.42.10-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/5794469/crash-2021-01-06_18.42.10-client.txt)
[crash-2021-01-07_07.53.16-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/5794470/crash-2021-01-07_07.53.16-client.txt)

**Comment by HellFirePvP** [comment]
Duplicate of #1418 unfortunately
