### ISSUE TITLE
can not use starlight infuser on my server

### ISSUE THREAD

**Issue by lovedheretic** [HellFirePvP/AstralSorcery#1643]
i have a paid for server on scalacube. i launch using curseforge v 0.166.1.4 i am using forge-35.1.28 and its running the 1.16.4 game version. i have progressed enough to be able to craft it, placed it down, and built the surrounding alter as it wanted shown to me by using the resonating wand and filled the slots with liquid starlight however when i place anything into it aqua marine for example and right click with the wand it does nothing

**Comment by PocketfulOfGeese** [comment]
Should come to the discord for live assistance instead for this.
