### ISSUE TITLE
Aevitas Mantle Airwalk ability not deactivating with keybind.

### ISSUE THREAD

**Issue by CyanSlinky** [HellFirePvP/AstralSorcery#1646]
I tried re-opening issue #1603 but i guess I'm not allowed to? so I'm opening this new issue.

Keybind doesn't work properly, the bar over the xp bar drains when they keybind is enabled but the ability itself doesn't get disabled when you deactivate the keybind.

_Originally posted by @CyanSlinky in https://github.com/HellFirePvP/AstralSorcery/issues/1603#issuecomment-754880819_

**Comment by PocketfulOfGeese** [comment]
What version of AS are you using?

**Comment by CyanSlinky** [comment]
1.13.9 which i believe is the latest? i also tried installing the mod in an isolated instance and the keybind didn't deactivate the ability there either so it's not a conflict with another mod or anything.
