### ISSUE TITLE
Hostiles Spawning Despite Lucerna Ritual (& more)

### ISSUE THREAD

**Issue by Danekjovax** [HellFirePvP/AstralSorcery#1647]
(https://github.com/Freebi85/Explorico_Easy/issues/2)

Playing Explorico 1.7, with the following specs:
Forge: 1.16.4-35.1.36-universal
Ice&Fire: 2.1.5-1.16.4
Cyclic: 1.16.4-1.1.1
Astral Sorcery: 1.16.4-1.13.9

In darkened caves within rendering distance, Cyclic Toretoices and Ice&Fire Cave Trolls seem to spawn without limit.  This is despite the Astral Sorcery ritual Lucerna being active in the area.  I see two issues:

1) Toretoices are spawning with no spawn cap.
2) Cave Trolls are spawning despite an effect/ritual supposedly preventing hostile mobs from spawning.

Thanks.
![image](https://user-images.githubusercontent.com/10191173/104518864-6b7a6100-55c6-11eb-9866-5a1a6367eb64.png)

**Comment by PocketfulOfGeese** [comment]
Lucerna cancels vanilla spawn events, if the mod uses some other method to spawn creatures, it will bypass it. This is done so that it allows things like spawners to still work, mob Farm mechanics from other mods thatspecifically bypass, etc.

**Comment by Danekjovax** [comment]
OK, I'll check elsewhere.  Thanks for your time. :2)
