### ISSUE TITLE
Crash after using Formation Wand with the plattform modus

### ISSUE THREAD

**Issue by UnleashedEkko** [HellFirePvP/AstralSorcery#1650]
Hello,
 im playing on Direwolf20 1.16.4 version 1.2.0.

After changing the Formation Wand to the plattform modus, and looking, inside a JAVM void world, over some mekanism machines and some wither proof glass from Cyclic the World is saving and the game shuts down. Crash Report says something about Astral Sorcery. I hope this is the right place.

https://paste.ee/p/FyqFh

**Comment by xaelith** [comment]
Combing through the error log, the initial cause of the crash appears to be related to storage drawers. If that's the case, updating ObserverLib could help fix your issue.

**Comment by UnleashedEkko** [comment]
okay its definetly a problem with the Visuals of the Formation Wand and looking at Storage Drawer

**Comment by PocketfulOfGeese** [comment]
#1418 

Storage drawers issue.

**Comment by UnleashedEkko** [comment]
thank you, we could fix it withremoving the drawers temporarily before joining.

**Comment by xaelith** [comment]
Glad I was able to help 🙂
