### ISSUE TITLE
Rock crystals soaking in liquid starlight can delete adjacent blocks that don't take up a full block space

### ISSUE THREAD

**Issue by Starfang42** [HellFirePvP/AstralSorcery#1653]
Tested using:
- Minecraft 1.16.4
- Forge 35.1.36
- Astral Sorcery 1.13.9

Description: When a rock crystal is soaking in liquid starlight, if it is inside the blockspace of an adjacent non-full block, when the size updates it will delete the block. 

Steps to reproduce:
- Surround empty blockspace with glass panes
- Place liquid starlight
- Drop a rock crystal so that it is at the edge between the liquid starlight and one of the glass panes 
- Wait

**Comment by PocketfulOfGeese** [comment]
#1618
