### ISSUE TITLE
[Feature Request] Celestial Crystal Clusters turn Starmetal Ore into configurable block

### ISSUE THREAD

**Issue by davqvist** [HellFirePvP/AstralSorcery#1654]
Hi, Hellfire,

as you know I am working on a new pack. The pack has no Iron Ore, so I changed the Starmetal Ore recipe with a datapack. So far so good.
But growing Celestial Crystal Clusters on Starmetal Ore still reverts the ore to Iron Ore and it seems to be hardcoded.
https://github.com/HellFirePvP/AstralSorcery/blob/e1b8c88ba71360c36232abfafc9b97406c63c398/src/main/java/hellfirepvp/astralsorcery/common/tile/TileCelestialCrystals.java#L110 
Could you add a way to configure a custom block this turns into either as a config option or as a datapack configurable recipe?

Thanks in advance.
Qvist

**Comment by HellFirePvP** [comment]
Added as config option "starmetalRevertState" in 1.13.10
Added command "/as serialize look" to help getting valid configuration string
