### ISSUE TITLE
Meka-Tool from Mekanism crashing game when placed in Stellar Refraction Table 1.16.4

### ISSUE THREAD

**Issue by PurpleArrowhead** [HellFirePvP/AstralSorcery#1657]
When the Meka-Tool from the Mekanism mod is placed in the Stellar refraction table the game crashes immediately. I have all modules installed. The Infused glass doesn't make a difference. I haven't tested with the meka-armor. Other Mekanism items, such as the portable qio drive are fine. Perhaps the modules are conflicting with the table? Regular netherite tools and armour are fine so it isn't a client bug.

**Comment by Jeuvke** [comment]
A crash report would be helpful. Especially when uploaded to gist or pastebin.

**Comment by PocketfulOfGeese** [comment]
@PurpleArrowhead any update on the above log request?
