### ISSUE TITLE
[Mod Conflict] Can't support BreakableTables mods

### ISSUE THREAD

**Issue by yuanjie000** [HellFirePvP/AstralSorcery#166]
Can't craft Resonating Wand in craftingtable of BreakableTables mods.

**Comment by HellFirePvP** [comment]
Not much i can do about it since he completely replaces Craftingtable GUI + Block. I have no real way of tracing what's happening besides making a specific mod compatibility with that mod...

**Comment by HellFirePvP** [comment]
@Funwayguy - care to make your craftingtable in BreakableTables extend BlockWorkbench? You're basically overwriting anything of it anyway.

**Comment by Funwayguy** [comment]
They originally did but I changed that after a request to make them be able to store items like project tables. I'm a bit busy with University deadlines at the moment but I can try making that change when I get a chance.

**Comment by HellFirePvP** [comment]
Alright, just answer to this again and i'll close it once you're done.

**Comment by HellFirePvP** [comment]
This got fixed on BreakableTables some time ago supposedly this thread just got never updated... Calling it "fixed" until someone proves me wrong :^)
