### ISSUE TITLE
Enchantments are downgrading to Vanilla Standard.

### ISSUE THREAD

**Issue by SolSavvy** [HellFirePvP/AstralSorcery#1664]
I went to enchant a Infused Crystal Sword with an Enchanted Book I got from a refraction table Glass Lens. come to find out Sharpness six is downgraded to 5 and Sweeping edge 6 is downgraded to 3. Those are the only ones to apply to the sword. How do I fix not getting the proper levels that I should be.
![2021-01-20_12 55 56](https://user-images.githubusercontent.com/27328200/105215786-b8f35280-5b1f-11eb-9fe2-0b3882353b73.png)
![2021-01-20_12 56 01](https://user-images.githubusercontent.com/27328200/105215811-c14b8d80-5b1f-11eb-98b0-ab5d1505f671.png)

Astral Sorcery Mod: 1.16.4-1.13.9
Forge:1.16.4-35.1.35

**Comment by PocketfulOfGeese** [comment]
Vanilla anvil limits. You'll need to use another mod to apply enchantments beyond normal vanilla levels, use a mod that modifies vanilla anvil applications to remove the restriction, or enchant the item directly in the Refraction Table instead.

**Comment by SolSavvy** [comment]
recommendation for such a mod?
