### ISSUE TITLE
Server Crash in 1.16.5

### ISSUE THREAD

**Issue by thelizardcode** [HellFirePvP/AstralSorcery#1665]
### Issue:  Astral Sorcery crashes servers running 1.16.5

Astral Sorcery Version: 1.16.4-1.13.9
Forge Version: 36.0.1

Crash Report:
https://paste.ee/p/lSVbj

**Comment by PocketfulOfGeese** [comment]
There's not a 1.16.5 release for AS yet, so...yes.
