### ISSUE TITLE
[Forge 1.16.4][Client Side Mod Conflict] Enhanced Celestials' Moon Coloring Is not applied during E.C's Lunar events

### ISSUE THREAD

**Issue by CorgiTaco** [HellFirePvP/AstralSorcery#1666]
Hi, I'd like to report a discovered mod incompatibility with my mod Enhanced Celestials(https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials) which is a mod that adds lunar events such as blood moons and harvest moons and your mod. It seems to me that the moon coloring from my mod is not applied.

Relevant Code on my side: https://github.com/CorgiTaco/Enhanced-Celestials/blob/master/src/main/java/corgitaco/enchancedcelestials/mixin/MixinWorldRender.java

As seen here I do a highly compatible and unintrusive mixin here that even works with optifine, so it leads me to believe that A.S is at fault for the incompatibility.

This is what the coloring of each moon should be like: 

Blood Moon w/out Astral Sorcery:
![8u242-b08 Screenshot 2021 01 21 - 18 05 56 63](https://user-images.githubusercontent.com/66983020/105436064-61361380-5c13-11eb-9d4c-8a8e9347fef5.png)

Harvest Moon w/out Astral Sorcery:
![8u242-b08 Screenshot 2021 01 21 - 18 06 54 64](https://user-images.githubusercontent.com/66983020/105436116-74e17a00-5c13-11eb-8bc4-492a95f770c8.png)

Blood Moon w/ Astral Sorcery
![8u242-b08 Screenshot 2021 01 21 - 18 03 04 35](https://user-images.githubusercontent.com/66983020/105435843-f4bb1480-5c12-11eb-95e4-6afc45e91e95.png)

Harvest Moon w/ Astral Sorcery
![8u242-b08 Screenshot 2021 01 21 - 18 03 11 44](https://user-images.githubusercontent.com/66983020/105435847-f5ec4180-5c12-11eb-9949-a987490db517.png)

If you have questions comments or suggestions for me and my code please lmk!

Have good day, 
-Corgi Taco

**Comment by Yourname942** [comment]
I am also experiencing this issue.
Minecraft 1.16.4
Forge 35.1.29
Astral Sorcery: 1.16.4-1.13.9
Enhanced Celestials: 1.0-BETA-v2-1.16.4

**Comment by CorgiTaco** [comment]
Also forgot to mention this was an in an instance with these 2 mods alone

**Comment by Frazzelbeard** [comment]
I am also currently experiencing this exact same issue.

**Comment by HellFirePvP** [comment]
Your ASM patch does not support custom skyrendering. AS doesn't run vanilla skyrendering code, hence your patch doesn't do anything. As there is no forge hooks for custom moon coloring, this isn't supported.
So much for "compatible ASM".

**Comment by TelepathicGrunt** [comment]
Well, AstralSourcery does completely override the sky rendering for the overworld which is bound to break any mod that tries to mixin/asm the vanilla sky rendering code for compatibility with each other. It might be worthwhile though to have dedicated mod support for other mods to apply their changes. Or maybe expose an endpoint in your mod if Forge wont add hooks (I kind of doubt Forge will add hooks for this but maybe they will) 

However, when I asked around, it seems that ISkyRenderHandler is supposed to be for custom dimensions. And that changes to the vanilla skybox should be done with mixins/asm for maximum mod compatibility until Forge adds hooks. That isn't to say what you are doing is bad but just means you should consider adding explicit mod compatibility or hooks for other people to use in the meantime.
