### ISSUE TITLE
[Forge 1.16.5] Structures ignoring terrain when generating

### ISSUE THREAD

**Issue by ghost** [HellFirePvP/AstralSorcery#1668]
Small shrines and ancient shrines seem not to do any terrain checks when generating, showing up on uneven terrain, ice, and water.

See [this album](https://imgur.com/a/JfjxIUs) for examples.

**Comment by PocketfulOfGeese** [comment]
Yup, still beta and not tuned yet. Also not out for 1.16.5 yet.
