### ISSUE TITLE
1.12 Celestial Crystal despawns/disappears after throwing into liquid starlight 

### ISSUE THREAD

**Issue by ButtersYoureGrounded** [HellFirePvP/AstralSorcery#1670]
I've tried about 5 times to grow celestial crystals and each of those times, the crystal just despawns after awhile. I was wondering if anyone had the same problem or a fix for this. Thank you!

**Comment by PocketfulOfGeese** [comment]
Crystals are flagged to not despawn, so something outside this mod is causing that. Protection plugin, ground clearing plugin, etc.
