### ISSUE TITLE
Ritual Anchor (Mineralis Ritual) is off 1.16.4

### ISSUE THREAD

**Issue by Descus** [HellFirePvP/AstralSorcery#1671]
I just placed a Mineralis Ritual Anchor and kept it running for a while.

I then realized (measured with Tape Measure) that the Ritual Anchor has a diameter of 19 blocks while 10 blocks are on the bottom and the left and 8 are on the top and right.

Recreated it by moving the ritual anchor.

AS Version: _astralsorcery-1.16.4-1.13.9_

**Comment by PocketfulOfGeese** [comment]
#1642
