### ISSUE TITLE
[1.16.4] Ulteria Ritual Trait Effect is reversed

### ISSUE THREAD

**Issue by NielsPilgaard** [HellFirePvP/AstralSorcery#1673]
The Ulteria Ritual Trait Effect expands range and weakens effect of the Ritual.

### Versions
- astralsorcery-1.16.4-1.13.9
- Forge-1.16.4-35.1.37

Original report: https://github.com/NillerMedDild/Enigmatica6/issues/1067

**Comment by Jeuvke** [comment]
Cannot reproduce. Are you sure you're using 1.13.9? This was fixed in 1.13.7.

**Comment by NielsPilgaard** [comment]
I'll double check with the original reporter, thanks :)

**Comment by NielsPilgaard** [comment]
Yup he's sure. I'll try to reproduce as well.

**Comment by NielsPilgaard** [comment]
A server reinstall got it working for him :)
