### ISSUE TITLE
Armour attributes are sometimes not applied after rejoining a world

### ISSUE THREAD

**Issue by Jeuvke** [HellFirePvP/AstralSorcery#1676]
1.16.4-1.13.9
By armour attributes I mean the attributes armour can get from the stellar refraction table.
In singleplayer, taking off any piece of armour and putting it back on fixes it.
In multiplayer, taking off any piece of armour and putting it back on kinda fixes it, but also causes another bug (#1677).

**Comment by Paperweight82** [comment]
i posted a similar (i think) issue on DW20 github about block transmutation needing relinking after rejoining world. related? 

> Maintainer edit: removed link as unrelated issue.

**Comment by Jeuvke** [comment]
> 
> 
> i posted a similar (i think) issue on DW20 github about block transmutation needing relinking after rejoining world. related? [FTBTeam/FTB-Presents-Direwolf20-1.16#149](https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/issues/149)

That's probably a different issue. I vaguely recall seeing that reported before, so please search before reporting it.
