### ISSUE TITLE
Intangible Liquid Starlight

### ISSUE THREAD

**Issue by Zachattack525** [HellFirePvP/AstralSorcery#1678]
the liquid starlight doesn't actually interact with entities at all besides giving night vision, and that is _excusively_ in their source blocks. is this intended behavior?

Also while not related to the tangibility of liquid starlight, the starlight in the lightwell is still white instead of blue

**Comment by Jeuvke** [comment]
Starlight is supposed to be white. Optifine has a bug where it makes liquid starlight blue.

**Comment by PocketfulOfGeese** [comment]
It has been intangible like that for an incredibly long time.
