### ISSUE TITLE
[1.11.2] Crash when hovering over things in the Journal

### ISSUE THREAD

**Issue by drewbit** [HellFirePvP/AstralSorcery#168]
Log: https://paste.ee/p/k3mY2
Astral Sorcery Version: astralsorcery-1.4.0
Forge Version: 1.11.2-13.20.0.2294

One of the players on my server was looking around in the book, hovering over various things. After a bit, it crashed. Specifically when hovering over the "Recipe Requires Light Shining" icon.

**Comment by HellFirePvP** [comment]
Might be mod interact? Could you try and reproduce with only AS and forge? - just asking out of curiosity, will build a fix around this anyway, but would like to know if it's my fault or someone elses for future reference
