### ISSUE TITLE
Cannot attune Mantle of the Stars

### ISSUE THREAD

**Issue by MacrosNoKuroi** [HellFirePvP/AstralSorcery#1680]
I have a Mantle of the Stars. I've been trying to attune it to Vicio. I've a tuned crystal and enough starlight. The new Mantle appears in the box in the Irridecent Alter, but when I use my wand, the animation starts then abruptly stops.

**Comment by PocketfulOfGeese** [comment]
Come by the discord for operational help like this. Either need a little more starlight or you are missing something if it starts and stops progress.
