### ISSUE TITLE
[Question/Suggestion] moving main config back to the main config folder

### ISSUE THREAD

**Issue by Zygus42** [HellFirePvP/AstralSorcery#1681]
The config file with a lot of the important settings for is situated in the save folder serverconfig directory.  This means that it can't be changed until a world is already created, which in turn means that certain things have already been set.

As an example: 	#If set to 'true', the player will receive an AstralSorcery Journal when they join the server for the first time.
	giveJournalOnJoin = true

Surely this makes no sense - those items need to be changed before the world is created, not afterwards.

Also makes it a total pain in the proverbial to test new modpacks, because you have to:
(1) make a test world
(2) exit the test world
(3) change all the settings in the save folder config file
(4) reload the test world
This costs a ridiculous amount of time when you're making 20 to 30 test worlds, compared to just changing the main config file and starting a new test world.

**Comment by PocketfulOfGeese** [comment]
"defaultconfig" folder is where you want to put it, that makes it apply to all worlds made.

**Comment by Zygus42** [comment]
Oh, so I can just copy it from the save folder to the main config folder ?  I had no idea.

**Comment by PocketfulOfGeese** [comment]
Yes,that is how server configs work now.
