### ISSUE TITLE
Using the give command to give a player a constellation paper gives two papers instead of one

### ISSUE THREAD

**Issue by Jeuvke** [HellFirePvP/AstralSorcery#1682]
1.16.4-1.13.9
Title. Using `/give @s astralsorcery:constellation_paper` to give a blank paper gives 2 papers instead. Using `/give @s astralsorcery:constellation_paper{astralsorcery:{constellationName:"astralsorcery:vicio"}}` to give a Vicio paper also gives two papers.

**Comment by HellFirePvP** [comment]
Looks like a forge bug with custom item entities.
Reproducible with starmetal ingots, rock crystals and any variant of constellation paper

**Comment by HellFirePvP** [comment]
Opened an issue on MinecraftForge's issue tracker https://github.com/MinecraftForge/MinecraftForge/issues/7785

**Comment by HellFirePvP** [comment]
The Forge issue cannot be resolved by design, however a workaround has been added for the specific issues around /give.
