### ISSUE TITLE
The client disconnects

### ISSUE THREAD

**Issue by 3269199948** [HellFirePvP/AstralSorcery#1685]
Cutting Starmetal Ingot occurs on the server: Player xxx Tired to Attack an invalid entity

**Comment by Jeuvke** [comment]
What version of Astral Sorcery? Can you post the server log?

**Comment by PocketfulOfGeese** [comment]
That is another mod or plugin triggering that. Log and list, please.

**Comment by 3269199948** [comment]
![image](https://user-images.githubusercontent.com/41908013/106405747-3bf6a000-6472-11eb-9880-cf7e54583584.png)

no server plugins

server mods:
![image](https://user-images.githubusercontent.com/41908013/106405772-49ac2580-6472-11eb-9108-d619adf6c1de.png)

server log:
![image](https://user-images.githubusercontent.com/41908013/106405805-56c91480-6472-11eb-82cf-48b5adc6b43b.png)

Other than that, there is no other information

Even 1.16.4, still have this problem

I also found out how to use any tool to click and also disconnect

**Comment by PocketfulOfGeese** [comment]
This mod is not yet out for 1.16.5.
