### ISSUE TITLE
Celestial Gateway labels sometimes may not work when using Auto scaling

### ISSUE THREAD

**Issue by frootbirb** [HellFirePvP/AstralSorcery#1689]
I'm running a server with a few friends, playing Direwolf20 1.16 (version 1.5.1, but we started on 1.4.1 and had the same problem). This is unmodified Direwolf20, no config tweaks, no Optifine. The most recent version includes astralsorcery-1.16.4-1.13.9.jar.

For most people on the server, the Celestial Gateway labels work correctly - when they're named on an anvil, the name appears by the star. For two of us, including me, the labels do not work for any gateway.

This is true for me, despite my being an operator on the server, having created and named most of the gateways myself, and being fully able to travel to all of the gateways. It's also true for one other person who (to my knowledge) has created no gateways or even leveled up in the mod at all.

This is also true on a singleplayer test world I just created, so it doesn't seem to be server-specific. Since other people CAN see the expected labels, it seems like it's something wrong on my end.

**Comment by PocketfulOfGeese** [comment]
Tried removing optifine?

**Comment by frootbirb** [comment]
No Optifine install to begin with! It's not bundled with Direwolf20 1.16, and I didn't add it.

**Comment by PocketfulOfGeese** [comment]
Would recommend playing with graphics config until you figure out what triggers it, then. I am not able to replicate.

**Comment by frootbirb** [comment]
Are there significant configs other than the in-game settings? I've played with all video settings in the menu, and got no change in labels.

**Comment by PocketfulOfGeese** [comment]
Have you tried changing up/down from Fancy vs Fast rendering, etc?

What's your hardware on your system? Gpu drivers updated?

**Comment by frootbirb** [comment]
Yes, I tried toggling every video setting including rendering level.

GPU drivers up to date, 2080 Super, Ryzen 7 3800x

**Comment by PocketfulOfGeese** [comment]
..Are the gateways locked, perhaps, without you having permission to use them? Or are they locked and you DO have permission?

**Comment by frootbirb** [comment]
All unlocked, all fully travellable, and I personally made most of them so even if they WERE locked, I'd be the one who did it.

**Comment by arhalts** [comment]
I had a similar issue in my world and it turned out to be a load issue to our best guess. I had no labels until there was someone at either both ends in addition to me traveling at least once. (minimum 3 people or chunk loaders) Is there any chance that that is your problem?

**Comment by PocketfulOfGeese** [comment]
Can anyone experiencing this try changing their UI Scaling and see if it resolves it? Was reported in the Discord this fixed it for one player.

**Comment by frootbirb** [comment]
Yep - good call, that does the trick. Switching from Auto Scaling to any explicit value causes it to work.

In case this is relevant, I play Minecraft in 3440x1440 ultrawide, so it's possible there's some non-standard width issue?

**Comment by PocketfulOfGeese** [comment]
Scaling issues are usually due to auto being garbage.
