### ISSUE TITLE
The push lens doesn't make starlight beams push players

### ISSUE THREAD

**Issue by Jeuvke** [HellFirePvP/AstralSorcery#1690]
1.16.4-1.13.9
Title. The push lens does work on items and mobs, but not on players, even with the config set to true.

**Comment by Jeuvke** [comment]
Still in 1.13.12.

**Comment by IsaacWorkman** [comment]
Suggest this is related to issue #1835

**Comment by PocketfulOfGeese** [comment]
It's not, 1835 only showed up in 1.16.5 MC releases, worked fine in 1.16.4.
