### ISSUE TITLE
[1.16.4-1.13.9] Linking celestial collector crystal to lens caused client crash

### ISSUE THREAD

**Issue by NerdimusPrime** [HellFirePvP/AstralSorcery#1691]
Minecraft 1.16.5
Forge 36.0.14

I placed an Aevitas-attuned celestial collector crystal on the balancing structure, and when I tried to link it to a lens the client crashed with these errors: https://pastebin.com/eTjnKb0Z

I disabled AS, reloaded the world without error, quit, and re-enabled AS. Same crash occurred.

**Comment by PocketfulOfGeese** [comment]
Mod isn't out for 1.16.5 yet, so unsupported.

Try enabling the server config to reset thevstarlight network, however.

**Comment by NerdimusPrime** [comment]
ok thanks, I'll try that.
