### ISSUE TITLE
Stuck in void at overworld 

### ISSUE THREAD

**Issue by XGSC** [HellFirePvP/AstralSorcery#1694]
One day I loaded my save I found my self spawn in a void and everything disappear except the light from my crystal
![image](https://user-images.githubusercontent.com/36799015/107114277-a6a74180-689f-11eb-8812-42a4b64fc41d.png)
and they used look like that
![image](https://user-images.githubusercontent.com/36799015/107114285-b757b780-689f-11eb-84a6-37210d748141.png)
Tried everything like resouspack, shaders, update mods.... till now seems only way to fix that is to remove AstralSorcery from mod folder 
My minecraft version is 1.16.5 and mod version:1.16.4-1.13.9, forge: 36.0.14, this happened several month ago on older version of Astral Sorcery and forge still unchanged after I update everything 
btw that's what I'm doing before things happened:
I place Horologium under my Iridescent Altar see if it can speed up grow of crystal
and I got a Vicio nearby  so I can easily fly to Altar on the montain
Vicio are been strength by five lens and with trait of Gelu to reach the maximum range
And I think the Horologium are only strength by three lens and without any trait on it
before things happened I've been growing my crystals for several real time  days, and then it happen

**Comment by PocketfulOfGeese** [comment]
The mod isnt out for 1.16.5, so this is unsupported to begin with and there is no telling what bugs exist.

**Comment by XGSC** [comment]
> The mod isnt out for 1.16.5, so this is unsupported to begin with and there is no telling what bugs exist.

This issue happened at 1.16.4 version

**Comment by PocketfulOfGeese** [comment]
Cool, so are those pictures from 1.16.4? What's your full mod list? You said you turned off shaders, did you also remove optifine? This isn't something that happens with just AS, so it's a matter of figuring out what mod is causing either 1) world load issues, or 2) render fighting through not handling their GL state code properly.

What's your client log look like when it loads into the world? Pastebin upload it and link it here. Is it just rendering that's broken, or does the world never actually fully load? Information.

ALSO ALSO:
> My minecraft version is 1.16.5

**Comment by XGSC** [comment]
I tried to remove all mod except astral sorcery and still stuck after loading the world, also tried only remove astral sorcery and the problem solved.
I start Minecraft in 1.16.4 only with astral sorcery and it's relevant mod and load that save again and there is the logs I found in log folder 

> Maintainer edit: removed file downloads

**Comment by PocketfulOfGeese** [comment]
...Need the logs from when the issue happens.

And, again, pastebin. Not downloading files, because security risk.

**Comment by XGSC** [comment]
It's been too long I can't recognize which one is the one when issue happened. link below are the log mentioned before
https://paste.ubuntu.com/p/NFQt7m7x74/
https://paste.ubuntu.com/p/2Z96y3yj4z/

**Comment by PocketfulOfGeese** [comment]
Logs when it isnt happening are literally useless.

If you can replicate it, logs then would be good. Logs AND a Sampler taken would be better. Google java sampler for the second one, plenty of good tutorials out there, at least five minutes with it "stuck".


And, again: was the world frozen, or did things just not render?

**Comment by XGSC** [comment]
The world frozen, can open inventory switch item, sun and moon still moving but can't move or using command like /tp /gamemod

**Comment by PocketfulOfGeese** [comment]
Definitely need a Sampler for it, then.

**Comment by XGSC** [comment]
I just used nbtexplorer edit my position to another position and that seems solves the problem for now, I'll keep doing what I've done before the issue and send the log there when it happens again

**Comment by XGSC** [comment]
I spawn away from where the issue happened and everything is fine, than I go back to where the issue happened(my home), chunks around there all not rendering and I broke a block nothing drop
![image](https://user-images.githubusercontent.com/36799015/107123266-83988400-68d7-11eb-87d1-dc0c8c4d6b71.png)
with the log:
https://paste.ubuntu.com/p/29PCJy9XwT/

**Comment by XGSC** [comment]
I spawn away from where the issue happened and everything is fine, than I go back to where the issue happened(my home), chunks around there all not rendering and I broke a block nothing drop
![image](https://user-images.githubusercontent.com/36799015/107123266-83988400-68d7-11eb-87d1-dc0c8c4d6b71.png)
with the log:
https://paste.ubuntu.com/p/29PCJy9XwT/

**Comment by PocketfulOfGeese** [comment]
Interesting. Client doesn't appear to be logging anything, will need a Sampler output.

**Comment by XGSC** [comment]
I'll try working on it tomorrow
