### ISSUE TITLE
Loading new chunks crashes game.

### ISSUE THREAD

**Issue by GlacialSkyfarer** [HellFirePvP/AstralSorcery#1698]
[crash-2021-02-06_15.54.15-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/5937850/crash-2021-02-06_15.54.15-server.txt)
Whenever i try to load a new chunk or make a world itcrashes
[latest.log](https://github.com/HellFirePvP/AstralSorcery/files/5937841/latest.log)

**Comment by PocketfulOfGeese** [comment]
Like your other ticket, same cause, vanilla losing its mind. AS isnt even in that trace
