### ISSUE TITLE
[1.12.2] crash when respawning (something with being called on the wrong side)

### ISSUE THREAD

**Issue by Shibva** [HellFirePvP/AstralSorcery#1699]
[crash-2021-02-06_17.58.48-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/5937856/crash-2021-02-06_17.58.48-client.txt)

**Comment by PocketfulOfGeese** [comment]
Attribute map isn't happy. 1.12 is largely unsupported at this point, but what does your perk tree look like? Is it every death? Only certain times?

**Comment by Shibva** [comment]
no, but I have noticed that its might have something todo with the sky rendering, Thaumcraft is present and theres a visual glitch with the sky when an Eldritch guardian Spawn Warp event happens, it sort of does something with the sky,

as for the skill tree

![image](https://user-images.githubusercontent.com/38770780/107133880-c861f200-68ba-11eb-9a4b-f1b3bc85d293.png)

**Comment by Shibva** [comment]
![image](https://user-images.githubusercontent.com/38770780/107133913-255da800-68bb-11eb-80fa-ec128aeffd89.png)
this screenshot was taken when I was playing the game, it may seem out of context but was the last screenshot I took recently before I died and the game running into this error

as you can see, the sky is messed up and thaumcraft causes this when a specific Warp Event happens (it spawns in Eldritch Guardians) and the fog effect that it creates seems to cause this

**Comment by Shibva** [comment]
Hope that this can help, I understood part of the air message and something about the sky caught my eye, and this might be whats causing it. I hope that some support comes back to this mod for 1.12.2 it a great mod, I mean at least have it maintained every once in a blue moon or something

Edit: Just to clarify, I belive its being caused by its Custom Fog effect when one is present
