### ISSUE TITLE
Information request: Mineralis Ritual configuration

### ISSUE THREAD

**Issue by mivalsten** [HellFirePvP/AstralSorcery#1701]
Hello,
I'm playing DW20 1.16 pack with AS 1.13.9 version and I recently built mineralis ritual. However, it only generates coal, iron, gold, lapis, diamonds and emeralds and no modded ores. In previous versions there was a config option for it, but I can't find it in toml file. Has this been removed or just not implemented yet for this version?

Thanks for all your great work!
Mivalsten

**Comment by Makabriel** [comment]
I second this request. Been looking for the past hour or so for info.  THought about downloading an older version to see if I can find the config settings.

**Comment by PocketfulOfGeese** [comment]
Server-sided config files in 1.16 and later are located under the world save directory by default, unless you or the pack author has relocated them to the "Defaultconfigs" directory in the main mod directory, the specific option flag you want is "[registries.mineralis_ritual_ore]" in the astralsorcery.toml file.

**Comment by Makabriel** [comment]
Thanks for the reply, Doomgull.

There are two .toml files that reference astral sorcery that I could find.
Astralsorcery-common
Astralsorcery-client

Both do not reference [registries.mineralis_ritual_ore]. Is this an option that we add to one of these files? It seems to fit with the structure for astralsorcery-common, but what options do we call and how do we set them?

**Comment by BlueAgent** [comment]
To clarify what doom mentioned above.

Get to the server/main config file:
- Create a new singleplayer world or if you already have one go to next step
- Find it in `./saves/<world name>/serverconfig/astralsorcery.toml`
- For dedicated servers it'll be `./<world name>/serverconfig/astralsorcery.toml`

If you want that config to apply to new worlds created:
- Copy it after editing to `./defaultconfigs/astralsorcery.toml`

If you have more than one world you'd like to change the config on you'll need to copy the edited config to each world
