### ISSUE TITLE
Liquid Starlight is blue

### ISSUE THREAD

**Issue by GeekJokes** [HellFirePvP/AstralSorcery#1702]
![2021-01-28_18 06 04](https://user-images.githubusercontent.com/46690435/107301539-6b9d3d80-6a5a-11eb-9840-8c5a69076e65.png)
I don't know if it's a configuration problem or some compatibility problem, maybe with optifine
It looks normal inside tanks though, including the well and from other mods

im using the observerlib 1.5.1 and AS 1.13.9 on mc 1.16.4 with forge 35.1.32

**Comment by PocketfulOfGeese** [comment]
Optifine has a lot of incompatibilites with many mods in 1.16. Comes from being closed source.
