### ISSUE TITLE
[1.16.4 - 1.13.9] Rituals persisting after deactivating on servers

### ISSUE THREAD

**Issue by luna6667** [HellFirePvP/AstralSorcery#1703]
Reported by Evenry and Marumon the discord. 

Rituals seem to persist after dismantling them on servers, restarting them and resetting the network doesn't seem to fix it. the two mentioned above would have more info. Evenry had a custom modpack, Marumon was in Valhesia 3. Could be a mod conflict, but reporting it here anyways. 

EDIT 2/9/21: Upon more testing, restarting and disabling the ritual in the same place did not work, resetting the starlight network worked while the config option was set to true, but setting it back to false allowed the ritual to return. 
A series of restarts did not work either, which proceeds as follows: 
Restart 1: Disable ritual, enable starlight network rebuild (ritual effect in world gone)
Restart 2: Enable ritual, dont change starlight network rebuild (same as before, server console reported bad nodes removed)
Restart 3: Keep ritual enabled, disable starlight network rebuild (ritual effect in world re-enabled even with no source) 
The final test, restoring the region files in the world folder and repeating the steps above **finally** fixed the issue. You can find the steps that worked here: https://pastebin.com/dsnzSWMK

EDIT 2 2/10/21: Upon further testing, it seems that while the above solution does work, it only works once, and every other attempt afterwards does not work. The below screenshot is the message given every time the server starts, which means that the bad nodes are either being regenerated, or not actually being removed in the first place. 
![Error](https://user-images.githubusercontent.com/11493210/107586538-21d56400-6bce-11eb-9d95-7db597921bbd.png)
The issue was finally resolved by deleting the offending chunks in the "Light Network" folder. 

If anything else pops up, this post will be updated accordingly.

**Comment by HellFirePvP** [comment]
This should be addressed with the next update
