### ISSUE TITLE
The Skybox Config Setting Is Broken

### ISSUE THREAD

**Issue by SkullHunter55** [HellFirePvP/AstralSorcery#1704]
#Whitelist of dimension ID's that will have special astral sorcery sky rendering
	skyRenderingEnabled = []
	#If a dimension is listed here, the sky render will only render constellations on top of the existing skybox.
	skyRenderingConstellations = ["minecraft:overworld"]

This feature is broken as it doesn't render over my resource packs custom skybox, even when turning off the resource pack it doesn't work, adding them to both options will just turn on the astral rendering, and if you change it to 0 instead of minecraft: overworld nothing happens either

**Comment by PocketfulOfGeese** [comment]
Have to set them both.
