### ISSUE TITLE
[Suggestion] Ability to turn off the output of a lightwell with a Redstone signal

### ISSUE THREAD

**Issue by DracoPhoenix42** [HellFirePvP/AstralSorcery#1705]
(You can remove this if this is a thing and I'm just an idiot)
Title
In some of the more complicated machines/builds that use lightwells and containment chalices, especially the evershifting fountain, it could be useful to be able to stop lightwells from interacting with anything on command.

**Comment by PocketfulOfGeese** [comment]
Chalices already support redstone to enable/disable their interactions.

**Comment by DracoPhoenix42** [comment]
I was talking about specifically about the ability to turn off the output of a lightwell.

**Comment by PocketfulOfGeese** [comment]
Only thing a lightwell outputs to wirelessly is a containment chalice. The intended path for a fountain is to use a chalice, not a lightwell.

**Comment by DracoPhoenix42** [comment]
If you have a lightwell outputting a Redstone signal with a comparator, you could use the ability to stop it as a way to hold a specific signal strength with a lightwell. 
Wait it took me a sec to understand what I just said. =\ 
The ability to pause a lightwell's progress manually with a Redstone signal would be useful though

**Comment by HellFirePvP** [comment]
I will not include this option
