### ISSUE TITLE
altar recipetype and serializer don't match

### ISSUE THREAD

**Issue by Ultrasquid9** [HellFirePvP/AstralSorcery#1706]
In the .json files for altar recipes, the serializer is astralsorcery:altar. however, its actual recipetype is astralsorcery:simple_altar, causing incompatibilities with other mods, such as crafttweaker.

**Comment by HellFirePvP** [comment]
The recipetype will be renamed to "astralsorcery:altar" in 1.13.10 onwards

**Comment by BlueAgent** [comment]
There isn't actually a requirement to have them match. (Still a good change though.)

It was actually a limitation in crafttweaker that required the recipe type and recipe serializer to be the same. Could add the recipe just fine with datapacks or KubeJS.

Example being vanilla's crafting type is `minecraft:crafting` and two of the serializers are `minecraft:crafting_shaped` and 
`minecraft:crafting_shapeless` but it has more serializers (one recipe type can have many serializers).

More information here: https://github.com/HellFirePvP/AstralSorcery/issues/1715
PR that relaxes the restriction here: https://github.com/CraftTweaker/CraftTweaker/pull/1166
