### ISSUE TITLE
wrong max HP data in Statistical data in ability page

### ISSUE THREAD

**Issue by Pliosauroidea** [HellFirePvP/AstralSorcery#1709]
in the star ability(i dont know how to say it correctly) page,when my HP reach to the max number,the statistical data use my current HP as a basic number and gives a higher HP number which in fact I cant reach
(sorry for pic in Chinese
![image](https://user-images.githubusercontent.com/37920182/107520791-c36bae00-6bec-11eb-9039-6af9ab170875.png)

**Comment by Pliosauroidea** [comment]
version: minecraft 1.12.2
astralsorcery-1.12.2-1.10.19

**Comment by Jeuvke** [comment]
Update to 1.10.27 and see if it still occurs then.

**Comment by PocketfulOfGeese** [comment]
Any update @Pliosauroidea ?
