### ISSUE TITLE
Astral Sorcery Shaders Issue

### ISSUE THREAD

**Issue by Schwoomple** [HellFirePvP/AstralSorcery#1713]
Minecraft 1.16.5
Latest Optifine
Multiple Shaders tested
Astral Sorcery-1.16.4-1.13.9

I figured that it's a skybox bug
here is the result: https://imgur.com/a/nuyPe0i

I assumed it could be fixed in config but I'm not sure how.
Thank you.

**Comment by PocketfulOfGeese** [comment]
Astralsorcery-client.toml has the options needed to disable/minimize the AS sky render. Shaders aren't supported, so it's the closest you can get.

**Comment by Schwoomple** [comment]
Can you give me an example on how to disable it. I'm not very good with this sort of thing.
Edit: just a photo of sorts showing what the toml would look like

**Comment by PocketfulOfGeese** [comment]
I woyld recommend reading the entries, there are only 4 or 5 in that file, then visiting the discord for assistance after that. It is the more appropriate forum for non-bug assistance.
