### ISSUE TITLE
[1.16.4] Spreading Growth perk using all my Charge converting dirt blocks under surface to grass

### ISSUE THREAD

**Issue by Deiwos** [HellFirePvP/AstralSorcery#1714]
AS: 1.13.9

Like the title says, I took the Spreading Growth perk and, as Minecraft's dirt layer is generally a few blocks deep, all of my starlight charge is being constantly wasted turning the layer of dirt beneath the surface into grass - which then of course quickly returns to dirt again. Perhaps limit it to the block the player is standing on?

**Comment by HellFirePvP** [comment]
Changed to not convert a block if the block above it is not air.
