### ISSUE TITLE
1.12.2-1.10.27 The yellow lens in the server cannot destroy the block

### ISSUE THREAD

**Issue by DreamAer** [HellFirePvP/AstralSorcery#1717]
In offline mode,In offline mode, the yellow lens can destroy the block, but in the server, the lens cannot destroy the block.
Version number:1.10.27

**Comment by PocketfulOfGeese** [comment]
Online or offline has no impact on lens funcrion. Something about the server is causing that.

Also, really hope offline mode isn't being used due to piracy. That will cause all sorts of issues with this mod anyway.
