### ISSUE TITLE
Soaking Rock & Celestial Crystals in  Liquid Starlight only gives size attribute.

### ISSUE THREAD

**Issue by Silsec** [HellFirePvP/AstralSorcery#1719]
I have made another world and even deleted config files still getting only size. I wasn't getting any other attributes nor was any attributes accumulating other than size.

[2021-02-15-1.log.gz](https://github.com/HellFirePvP/AstralSorcery/files/5985645/2021-02-15-1.log.gz)

**Comment by BlueAgent** [comment]
This is working as intended. Soaking in starlight only increases size. To get specific attributes you either split crystals with the cutting tool and then merge them (both in the same liquid starlight), or grow a crystal (with starmetal dust + liquid starlight) to add on random stats.

**Comment by Silsec** [comment]
Ok thanks for the info.
