### ISSUE TITLE
[1.11.2] problem with first connection to server 

### ISSUE THREAD

**Issue by Terpo** [HellFirePvP/AstralSorcery#172]
I was trying to connect to my testserver with a large modpack. After the first try the console was spammed like hell and I got a disconnect. With the second try I was able to connect. 

Currently I am NOT sure if this problem was caused by AS but the serverlog was pointing to it.

Client Log: http://terpo.org/blog/upload/mc/connection.txt 
STRG+F for "Disconnected from server. Cleaning client cache"
Timestamp: 15:40:34

Server: https://gist.github.com/Terpo/909ff4eccaff8039e2ec82785f285990
Timestamp: 15:40:32

Current modlist: https://gist.github.com/Terpo/3f7271ed331422870929a244379d6d03
forge 2296

**Comment by HellFirePvP** [comment]
You might also wanna post this at DynamicSurroundings' issue tracker since like 99.999% of the errors are from that.
And as for the issue on my end: will look that up and fix it for the next version.

**Comment by Terpo** [comment]
This could also be caused by myself (AS related) because I forgot to add the CraftTweaker scripts to my new client instance.

**Comment by HellFirePvP** [comment]
Problem originates from InitialInventory by the way.

**Comment by Terpo** [comment]
Can you tell me where you found the information for InitialInventory? Timestamp would be enough, then I may open an issue there.

**Comment by HellFirePvP** [comment]
Not necessarily his issue, it just happens because he calls something eariler than i'd expect. Nothing too dramatic, i can work around that - as i did.

**Comment by Terpo** [comment]
I will call you if the problem still exists with the new build ;).

**Comment by HellFirePvP** [comment]
Please do.

**Comment by Terpo** [comment]
Updated my server and client. First test without problems.

**Comment by HellFirePvP** [comment]
Seems good
