### ISSUE TITLE
Cannot craft Telescope

### ISSUE THREAD

**Issue by Kry0hh** [HellFirePvP/AstralSorcery#1720]
So, I'm playing on Valhelsia 3. I'll make it short and blunt so it's easy. 
My alter (Starlight Crafting) is in the sky in a dense Fosic field. 
My alter has open sky above it.
My alter has 100% starlight.
It is nighttime when attempting to craft.
My alter can craft other items with complete ease. 
My recipe is correct, and is directly inputted by JEI, with no missing items error.
I'm right clicking the alter with the resonating wand like usual.
I have also tried putting in the materials manually, and breaking and replacing the alter.

However: The telescope does not appear in the crafting menu when the recipe is laid out. 

I'm pretty frustrated right now because I just can't seem to get this to work. The only possible thing I could think of is that I don't have all 5 constellation papers in my tome, but I do have them discovered and in my constellation section. Reason being, is that I ran out of inventory space when obtaining rock crystals, and had dropped 2 of them before I was told that I could store them in my tome. Now, I can't re obtain the constellation papers because it requires the absolute endgame alter, and dropping "blank" ones and picking them up again isn't working. I'm really, really, really, really, really, really hoping that this isn't the case, because if it is, I can't even spawn them in (Which I already don't want to do) I would have to cheat in the endgame alter, learn to build it, build it up from scratch, craft the papers, destroy the setup, then resume from where I left off.

If you guys have any other ideas, or need any further info, please let me know. I have absolutely no clue what to do, and I've already went to the modpack support channel and they, just like me, were pretty stumped. Thanks for reading.

**Comment by Jeuvke** [comment]
Can you show a screenshot of the recipe you're putting in, and a screenshot of the chapters you've unlocked in the tome?

**Comment by Kry0hh** [comment]
Sure thing! Here you go:
![Astral 1](https://user-images.githubusercontent.com/76639652/108031153-3312dc00-6fe5-11eb-8143-afc4936f7198.png)
![Astral 2](https://user-images.githubusercontent.com/76639652/108031157-33ab7280-6fe5-11eb-98cf-1ae061ad2ba1.png)
![Astral 3](https://user-images.githubusercontent.com/76639652/108031214-4e7de700-6fe5-11eb-82e1-fa33b74104bd.png)

And then, to save you 3 screenshots, the 3 papers in my shift-click menu are Armara, Aevitas, and Evorsio.

**Comment by Jeuvke** [comment]
Ah, that's not what I meant. I meant the chapters in the Research tab. My bad for not specifying.

**Comment by Kry0hh** [comment]
Oh, alright sure!  I have discovery, and exploration, oddly enough I don't see the telescope still, only the looking glass. Here are the screenshots. 
![Discovery](https://user-images.githubusercontent.com/76639652/108031518-d5cb5a80-6fe5-11eb-89b2-4aa08bdc91da.png)
![Exploration](https://user-images.githubusercontent.com/76639652/108031519-d663f100-6fe5-11eb-9c13-383bc17b86ea.png)

**Comment by Kry0hh** [comment]
But my understanding was that once I crafted the looking glass, I should be able to immediately upgrade to the telescope. I have even crafted a second one (which I did to test if crafting was working at all)

**Comment by Jeuvke** [comment]
Well, if you haven't unlocked it yet in the tome, you can't craft it.

**Comment by Kry0hh** [comment]
Hmm could I at least get confirmation to make sure that I don't in fact need the 5 constellation papers in my tome to craft it? I'm following along with another player's video guide, and he was able to craft it immediately after the looking glass, and that was the only difference I could think up.

**Comment by Jeuvke** [comment]
You can craft it as soon as you unlock the chapter the telescope is in. No other requirements.

**Comment by Kry0hh** [comment]
Okay, that's a relief. I'll attempt to continue progression then. Thanks for the help

**Comment by Kry0hh** [comment]
After backtracking, I realized it was because I hadn't upgraded my own altar (I was using my roommates after making my own Luminous, since he already had the next one up). Therefore I didn't meet the milestone to unlock the chapter. Man I feel stupid.
