### ISSUE TITLE
[1.16.4-1.13.9][Question] Horologium ritual and multiblock machines

### ISSUE THREAD

**Issue by NerdimusPrime** [HellFirePvP/AstralSorcery#1723]
I was looking at the config for the horologium ritual, which I'm using for Immersive Engineering multiblock machines. How does the ritual count those for number of blocks captured: as one big block, or does it count all the component blocks (27 for a 3x3x3 machine)?

**Comment by PocketfulOfGeese** [comment]
It's based on tickable blocks, not blocks.

**Comment by NerdimusPrime** [comment]
OK, thanks.
