### ISSUE TITLE
Special Sky Rendering Doesnt Work

### ISSUE THREAD

**Issue by SkullHunter55** [HellFirePvP/AstralSorcery#1724]
I currently have my config setup like this and I cant see the constellations on my resource pack skybox, when adding the id to both it also won't work...

#If a dimension is listed here, the skyrender will only render constellations on top of the existing skybox.
skyRenderingConstellations = ["minecraft:overworld"]

#Whitelist of dimension ID's that will have special astral sorcery sky rendering
skyRenderingEnabled = []

**Comment by PocketfulOfGeese** [comment]
Make the second look like the first. Like the many previous tickets on this issue. It works. Those options are for attempted shader compatibility, however.

If it doesn't work for whatever is modifying your skybox, it isn't an AS issue.
