### ISSUE TITLE
Rock Crystal can't reach max stats

### ISSUE THREAD

**Issue by Silsec** [HellFirePvP/AstralSorcery#1727]
Is there any reason why a rock or celestial crystal can't have a max amount of attributes apply to them? For instance I have a rock crystal with 2 size, 2 shape, 2 tool efficiency, 1 tool durability but I can't add another attribute onto it like shape or size assuming 8 is the max for this crystal.  I tried using shape II and size II crystals to merge with it as well soaking in starlight to increase the size but with no change.

**Comment by Jeuvke** [comment]
7 is the maximum for rock crystals. This is intended.

**Comment by Silsec** [comment]
I have another rock crystal with 3 size, 3 shape and 2 tool efficiency.

**Comment by Jeuvke** [comment]
Are you in 1.15? There's currently a bug in 1.15 where growing size with starlight bypasses the limit.

**Comment by Silsec** [comment]
Yes its 1.15.  What is the max limit for Rock and Celestrial Crystals for 1.15?

**Comment by Jeuvke** [comment]
For rock crystals it's 7. For celestial crystals it's 10.
