### ISSUE TITLE
[1.16.4] AS found a bug that crashes the client when player attunement starts

### ISSUE THREAD

**Issue by Nythirian** [HellFirePvP/AstralSorcery#1728]
I'm using a newer modpack called slightly cinnamon flavor on my server and i cant get ahold of the pack developer or submit the bug report I was hoping someone on here could help with this issue. after progressing to the attunement
[crash-2021-02-22_14.00.38-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/6025223/crash-2021-02-22_14.00.38-client.txt)

 alter i placed the focuses for vicio and stepped on to the alter at night. the client immediately crashes out and throws a report. upon logging back in i have this pseudo god mode going. 

thank you for any help you can give

**Comment by PocketfulOfGeese** [comment]
#1594 
#1507
