### ISSUE TITLE
sky bug - gaps in texture and daytime madness

### ISSUE THREAD

**Issue by catkaiju** [HellFirePvP/AstralSorcery#1729]
hi all,

using valhelsia 3, if i set sky rendering to work in the overworld (like normal), it looks like this (day and night)

![image](https://user-images.githubusercontent.com/79519496/108845338-34d83300-75d5-11eb-99bd-db807e2f5dad.png)
![image](https://user-images.githubusercontent.com/79519496/108845349-399ce700-75d5-11eb-990e-1a782781d6d4.png)

the only fix i've found is to disable the sky, but this has its own problems. i'm not able to see constellations. has anyone else had this issue?

using 1.16.5 minecraft, 36.0.15 forge, valhelsia 3 for 1.16.5 + optiforge 1.16.5-0.5.0. bsl shaders (though i don't think this is the problem..)

**Comment by PocketfulOfGeese** [comment]
The shaders are the problem. Shaders conflict. It's why AS says it isn't shader compatible on the cirse page and it has a config option in the client config to disable the AS render for the skybox to attempt compat.
