### ISSUE TITLE
Celestial Gateway error

### ISSUE THREAD

**Issue by izShelby** [HellFirePvP/AstralSorcery#173]
Hello again.

I have a problem with the celestial gateway. When I step into the middle after I start the server, the area around you goes dark as it should, but then it just goes back to normal. When I step into the middle again and look toward my second gateway, the HUD turns off and nothing else happens.

There's also this error message:
https://pastebin.com/Z7n104vS
Hope you can make any sense of this.

**Comment by HellFirePvP** [comment]
Yes i can, it's going to be fixed in the next update 1.4.1 which will most likely be released tuesday.

**Comment by izShelby** [comment]
Sadly, the issue still persists.

**Comment by HellFirePvP** [comment]
Adressed a second time now, will be fixed in the next bugfix update.
