### ISSUE TITLE
Error en subida de EXP en los perks del astral tome

### ISSUE THREAD

**Issue by Deimon49** [HellFirePvP/AstralSorcery#1733]
Hice la constelación vicio la cual se supone da algo de experiencia en la barra de arriba a la izquierda, la cual a mí no me sube, probe a quitar vicio y poner armada,pero tampoco me sirvió, necesito una ayuda porque me gusta el mod y me gusta esta mecánica (versión del juego: 1.12.2)

**Comment by PocketfulOfGeese** [comment]
If you are not gaining experience when moving around the world while attuned to Vicio, something is interfering in the modpack.

Also, the 1.12 version of this mod is no longer being updated.
