### ISSUE TITLE
[1.16.5] Necromantic Prime doesn't read from config

### ISSUE THREAD

**Issue by NielsPilgaard** [HellFirePvP/AstralSorcery#1734]
Original issue: https://github.com/NillerMedDild/Enigmatica6/issues/1452

Despite having quite a few additions to the Necromantic Prime in the `fluid_rarities` config, only water and lava is available. The player in the original issue has searched extensively, across 2 worlds.

Our config: `fluid_rarities = ["minecraft:water;2147483647;2147483647;14000", "minecraft:lava;4000000;1000000;7500","immersivepetroleum:oil;2500000,1000000,5000","mekanismgenerators:flowing_fusion_fuel,1000000,500000,100","industrialforegoing:sewage_fluid,10000000,5000000,250","bloodmagic:life_essence_fluid_flowing,5000000,2500000,250","industrialforegoing:sludge_fluid,1000000,1000000,200","immersivepetroleum:napalm,500000,500000,100","industrialforegoing:essence_fluid,500000,100000,300", "mekanism:flowing_heavy_water,10000000,2000000,2500"]`

### Versions
- astralsorcery-1.16.4-1.13.9
- Forge-1.16.5-36.0.40

**Comment by HellFirePvP** [comment]
> industrialforegoing:essence_fluid,500000,100000,300

please separate the values with ; not ,

**Comment by NielsPilgaard** [comment]
I feel slightly stupid, thanks for the help :P
