### ISSUE TITLE
[1.16.5] Max size rock crystal never splits in liquid starlight

### ISSUE THREAD

**Issue by LuciusV** [HellFirePvP/AstralSorcery#1735]
I tried about one hundred times to put size 3 rock crysta in liquid starlight and never get any additional rock crystal?

**Comment by LuciusV** [comment]
Not a bug, I read on reddit how to do this, but ingame documentation about this is very unclear.

**Comment by PocketfulOfGeese** [comment]
Because that is the old 1.12 method. As the documentation says now, use the starmetal cutting tool. Things like questions should come to the discord instead of github tickets.
