### ISSUE TITLE
[1.16] Crystal tools are damaged by ProjectE Repair talisman instead of repairing

### ISSUE THREAD

**Issue by LuciusV** [HellFirePvP/AstralSorcery#1737]
I firstly created this at ProjectE tracker, got response that problem is on AS side: https://github.com/sinkillerj/ProjectE/issues/2102

Astral Sorcery version : 1.16.4-1.13.9
ProjectE version : 1.16.5-PE1.0.0B
Forge version: 36.0.39

Steps to reproduce:

    Equip Repair talisman, make a Crystal Pickaxe from Astral Sorcery celestial crystals (3 size I crystals give 23478 total durability)
    Mine something to damage tool: it will start to degrade (but damage stops after some time)
    What I expected to happen:
    Tool repaired until full durability
    What happened instead:
    Tool is degrading randomly

**Comment by BlueAgent** [comment]
[Cannot reproduce](https://www.youtube.com/watch?v=eUTJzAgmZ-E). See [here](https://github.com/sinkillerj/ProjectE/issues/2102#issuecomment-788029838) for more info.
