### ISSUE TITLE
[1.16.5] Ensorcellation enchantments disabled in config still appear on resplendent prism. 

### ISSUE THREAD

**Issue by LuciusV** [HellFirePvP/AstralSorcery#1741]
Resplendent prism can still get config disabled Ensorcellation  enchantments.
Astral Sorcery version : 1.16.4-1.13.9
Ensorcellation version : 1.16.3-1.1.2
Forge version: 36.0.39

Firstly I talked in COFH discord, this is the way how they do check if enchantment is enabled and this will not change, as they will not unregister enchantment:

https://github.com/KingLemming/1.16/blob/d9702ea5ef50dad5578634cc636e22d3324f1932/CoFHCore/src/main/java/cofh/core/enchantment/EnchantmentCoFH.java#L71

**Comment by PocketfulOfGeese** [comment]
Resplendent Prism has its own config file and weighting populated initially by registered enchantments, which is where it should be controlled.
