### ISSUE TITLE
1.16.4 Lucerna blocking Pelotrio

### ISSUE THREAD

**Issue by AgeOfAutomata** [HellFirePvP/AstralSorcery#1744]
The guide advises that Pelotrio's ritual effect ignores Lucerna's, however the ritual is not spawning anything while Lucerna is active in the area.

**Comment by PocketfulOfGeese** [comment]
Have you confirmed it works without Lucerna being present?

**Comment by AgeOfAutomata** [comment]
I think it was a mod interaction. I have updated several other mods, and now it works. Unfortunately I'm not sure what mod it was that was interfering.

At the time it definitely worked without the Lucerna active.
