### ISSUE TITLE
Discidia ritual (not corrupt) hurting players

### ISSUE THREAD

**Issue by Shadow-223** [HellFirePvP/AstralSorcery#1745]
Enigmatica 6 Modpack version 1.16.5.  Astral Sorcery Version 1.16.4 - 1.13.9.   I have multiple rituals all operating as intended but when I try to use a Discidia ritual, it starts damaging me as soon as I place the crystal in the altar.   Here is the crystal I am using.
![FC9221AF-1BE7-43ED-A0F9-FDD28DFA6ABD](https://user-images.githubusercontent.com/80296742/110402005-7c2bde00-802f-11eb-93d2-9cf19979f6b9.png)

I have also tried it with a corrupted Discidia crystal to see if the effect were reveres.  It also damages me as soon as I place it.

**Comment by Floooly** [comment]
I do have the same issue, but with the skybees modpack (MC 1.16.5, forge 36.0.46, AS 1.16.4-1.13.9). I do play with friends on a server and it damages the whole group when ever one of us puts the cristal in the pedestal. We even made different discidia crystals  to check (the corrupt ones do lot more damage)

**Comment by HellFirePvP** [comment]
Discidia now cannot hurt players anymore.
