### ISSUE TITLE
Crystal Visual Effects

### ISSUE THREAD

**Issue by Khyram** [HellFirePvP/AstralSorcery#1746]
Is there some way a config option can be added to disable the light ray effects from collector crystals and dropped rock crystals? When using shaders and/or other mods they can render incorrectly. I understand this is not an issue or bug with AS but the config option would be a godsend as I adore this mod but I also adore it with shaders ;)

**Comment by PocketfulOfGeese** [comment]
Astral Sorcery does not support shaders. There is a configuration option for attempted support for conflicting sky shaders, but it has no support if it does not work. There is also a config option for particles/effects that may be of use.

All of these are in the "astralsorcery-client.toml" configuration file.
