### ISSUE TITLE
Add unattuned Collector Crystals to JEI so you can use it to find the recipe

### ISSUE THREAD

**Issue by aaronhowser1** [HellFirePvP/AstralSorcery#1747]
![image](https://user-images.githubusercontent.com/15698722/110600984-1e3fe900-814a-11eb-81d6-380486ec529b.png)
This recipe does not show up when you check the ones in JEI, because all of them are attuned to a constellation already.

This is using `astralsorcery-1.16.4-1.13.9`

**Comment by PocketfulOfGeese** [comment]
You can't create an unattuned collector. Every collector has to use an attuned crystal which is why searching JEI won't show an unattuned one.

**Comment by aaronhowser1** [comment]
Then preferably add recipes for each of them so they show up in JEI, right? So you don't have to open the book every time
