### ISSUE TITLE
Reg2 not working like it use to in Enigmatica 6

### ISSUE THREAD

**Issue by SilverGhostie** [HellFirePvP/AstralSorcery#1748]
I am going on old information from 1.12 so stick with me for a moment.  When making a ritual(im not going to butcher the name, its one of the A names.) it gives regen 2.  In 1.12 it worked so well it was near instant healing.  Great for Bloodmagic users who didnt have a well of suffering yet.  
However, now in 1.16 (at this moment we are playing Enigmatica 6 E6 1, version 4.1) when i made the ritual its not working like it use to.  it doenst even feel like its giving more then regen 1, and not really well.  i did some digging and found i can augment the ritual by adding one of the faints to it.  causeing the ritual to become 4x more powerful but reducing its size, which didnt matter to me because i just use an anchor to have the ritual hover over the blood alter.  and yet still not any stronger.  i even went so far as to set a regen lens up next to the blood alter aswell in hopes of maybe getting a stack effect or something.  nada.  is this just as good as it gets now?  or is there something wrong, wrong by me or maybe something else?

**Comment by Jeuvke** [comment]
The Aevitas ritual was bugged in 1.12 and early 1.16 releases, where the regeneration was way too fast. Regeneration 2 is just that slow. Also the level of regeneration you get is determined by the config, not by the ritual crystal's stats or its faint attunement.

**Comment by SilverGhostie** [comment]
Well, poop.  Wish they would've left it like that.  Thank you for the information!
