### ISSUE TITLE
Server Lag 

### ISSUE THREAD

**Issue by tyfighterepic** [HellFirePvP/AstralSorcery#175]
I run a private server with a group of friends, and one of the mods we have added is Astral Sorcery. Sadly, after the most recent update every time a chunk with astral sorcery is loaded, all other players in the server are affected with a lag of 30 seconds to a minute. I would like to not remove this mod, however it is making it unplayable. Do you know of any way to reduce the lag for players when AS chunks are loaded?

Thanks.

**Comment by HellFirePvP** [comment]
Nothing like this was ever reported by someone. Mind adding some profiling data to see what exactly takes so long?

**Comment by HellFirePvP** [comment]
Information never provided... *closed*
