### ISSUE TITLE
Marble blocks have unexpectedly high blast resistance

### ISSUE THREAD

**Issue by TheRealWormbo** [HellFirePvP/AstralSorcery#1752]
Marble blocks of any kind, whether in shrine structures or underground blobs appear to be pretty much completely explosion-proof to the usual sources of explosions. I tested TNT, TNT minecarts, end crystals, respawn anchors, charged creeper, and even summoned the wither to test its initial explosion. None of these managed to damage shrine structure or the random marble underground.

For a block that is still relatively easy to mine (compared to e.g. obsidian), that kind of blast resistance seems way higher than one would expect.

**Comment by Jeuvke** [comment]
Marble has a blast resistance of 25, which is indeed quite high. In vanilla there are no blocks with a blast resistance between 9 and 100 (9 for end stone, 100 for water/lava).
For comparison, the blast resistance of stone and cobblestone is 6.

**Comment by TheRealWormbo** [comment]
But is that an intentional change from the 1.12 version of this mod, where it worked pretty much like any other stone type? Marble doesn't feel like a block that should be blast-proof against all vanilla explosion sources.
