### ISSUE TITLE
Last +0.5 health perk on way to Stone Enrichnment does not work

### ISSUE THREAD

**Issue by LuciusV** [HellFirePvP/AstralSorcery#1753]
There are 3 perks which give +0.5 health each on way to Stone Enrichment perks, two first work, the last one does not
Astral Sorcery version : 1.16.4-1.13.9
Forge version: 36.0.39
![2021-03-14_11 31 48](https://user-images.githubusercontent.com/11925386/111056456-e58d7000-84b9-11eb-9cd8-849e9bbfb5ec.png)
![2021-03-14_11 31 59](https://user-images.githubusercontent.com/11925386/111056458-e7573380-84b9-11eb-9aa5-a50ad782fefb.png)

**Comment by Jeuvke** [comment]
They're all exactly the same, so there must be something special going on.
https://github.com/HellFirePvP/AstralSorcery/blob/1.16-indev/src/main/resources/data/astralsorcery/perks/aevitas_outer_enrich_1.json
https://github.com/HellFirePvP/AstralSorcery/blob/1.16-indev/src/main/resources/data/astralsorcery/perks/aevitas_outer_enrich_2.json
https://github.com/HellFirePvP/AstralSorcery/blob/1.16-indev/src/main/resources/data/astralsorcery/perks/aevitas_outer_enrich_3.json

**Comment by Jeuvke** [comment]
No wait, I know what the issue is. This is just intended, and not a bug. 0.5 health is 0.25 hearts, and minecraft visually displays health in full hearts. So the 0.75 heart gets shown as one.

**Comment by LuciusV** [comment]
I got it, should we close the issue then?

**Comment by Jeuvke** [comment]
Probably? The current report doesn't list a bug.
