### ISSUE TITLE
[1.12.2] AS Health reset after leaving the world

### ISSUE THREAD

**Issue by ReiDaTecnologia** [HellFirePvP/AstralSorcery#1754]
Mod version: 1.10.27
MC version: 1.12.2

Description:
When you leave and join the world, the health gained through Perks reset.

Perk list for reference:
![2021-03-14_02 03 58](https://user-images.githubusercontent.com/30323772/111057968-fadaae00-8469-11eb-9e3c-e733f0f265fe.png)

Before leaving the world:
![2021-03-14_02 03 43](https://user-images.githubusercontent.com/30323772/111057975-0fb74180-846a-11eb-973c-f70f3ca963fb.png)

After joining it:
![2021-03-14_02 04 18](https://user-images.githubusercontent.com/30323772/111057988-2198e480-846a-11eb-8c55-45797be00f04.png)

Log: N/A

Note: I know most modders don't support 1.12.2 anymore but i looked around and didn't find any warning saying you don't support 1.12.2 anymore, but in case you don't support 1.12.2 anymore (You should put a warning at the mod's curseforge page to avoid this :P) and/or this bug is too "low priority", i totally understand if you resolve not fixing it, i can live with it :D but i would love you if you fixed it <3.

**Comment by PocketfulOfGeese** [comment]
#1166
