### ISSUE TITLE
Sooty marble pillar hides flowing lava

### ISSUE THREAD

**Issue by Ouroboros42** [HellFirePvP/AstralSorcery#1759]
![image](https://user-images.githubusercontent.com/40540401/111220941-c255e400-85d1-11eb-85b3-fc98e74c928f.png)
Ass seen in the attached, flowing lava cannot be seen through the transparent part of a sooty marble pillar. This may be a more general issue, I have not done any testing.

This was in version 1.10.21 for mc 1.12

**Comment by Jeuvke** [comment]
1.12.2 AS is no longer being updated, and this bug is not present in 1.16.4. So this probably won't be fixed.

**Comment by PocketfulOfGeese** [comment]
Partial-blocks and flowing liquids did weird things a lot in 1.12, but yes 1.12 is no longer being updated.
