### ISSUE TITLE
Cave illuminator Question 1.11

### ISSUE THREAD

**Issue by Syncyy** [HellFirePvP/AstralSorcery#176]
Hi just wanted to ask if you changed anything with the cave illuminator since 1.3.2 . Do I need to unlock it first before it starts working or is there something else I need to do? I kinda cheat them in to make caving tolerable for me in the early game.

Right now I have about 6 around my base with maybe 60 blocks between them. I also have a few underground in a mine shaft /ravine hoping that would fix the problem.

I will afk the rest of the night to give it some more time, maybe there's a huge network its busy lighting that I just can't see.

**Comment by Syncyy** [comment]
Closing this, the ones outside my base were working but the one at the entrance to my mine was not and neither the ones inside the mine. Gonna try moving things around.

**Comment by Syncyy** [comment]
Left it over night with a illuminator at the entrance to my mine, one at either side of a ravine and one at the surface above the ravine. No lights.

**Comment by HellFirePvP** [comment]
I changed nothing except that a player has to place it now in order for it to function - reason for that was it 'accidentally' generating in certain worldgen things in packs which caused massive memory allocation for the host server.

So idk. i didn't change anything that'd mess with its logic and noone else seems to have this issue.
