### ISSUE TITLE
[1.16.5] Resplendent prism does not add level to existing Fortune VI enchantment

### ISSUE THREAD

**Issue by LuciusV** [HellFirePvP/AstralSorcery#1761]
Astral Sorcery version : 1.16.4-1.13.9
Forge version: 36.0.39

While my Fortune III pickaxe receives bonus, Fortune VI (enchantment from Stellar Refraction table) does not. I remember it was not like that in 1.12. If this is intended, this is somewhat defeats purpose of prism making it only slight bonus of extra enchantment slot...

**Comment by Jeuvke** [comment]
Can't reproduce. When you hold the fortune 6 pick in your hand, does it get the bonus?

**Comment by LuciusV** [comment]
No, it does not, keeping Fortune VI. And when I hold Fortune III pickaxe, it does get the bonus becoming Fortune IV. Do you mean that in your test you got Fortune VII on tool in your hand?

**Comment by LuciusV** [comment]
I did some tests and found that bug happens with Mystical Agriculture pickaxe, vanilla tools receive Fortune VII. How to check promblem is in AS code or in Mystical agriculture?

**Comment by LuciusV** [comment]
It works with mystical agriculture Soulium dagger and tools from other mods, so I believe problem is on mystical agriculture essence tools code, made an[ issue there](https://github.com/BlakeBr0/MysticalAgriculture/issues/395)

**Comment by LuciusV** [comment]
There is the reason why, could you please fix it? https://github.com/BlakeBr0/MysticalAgriculture/issues/395#issuecomment-991844246 
Thanks BlakeBr0 for finding that out.

**Comment by HellFirePvP** [comment]
Wrong tagging, my bad
Support for non-damageable, enchantable, non-book items will be added.

Should this cause issues down the line, i'll revert this
