### ISSUE TITLE
Gane crashing

### ISSUE THREAD

**Issue by BHGHOST5257** [HellFirePvP/AstralSorcery#1762]
Modpack: Direwolf20 1.16 - 1.7.0
Forge Version: 36.0.45
Astral Sorcery version: 1.16.4 - 1.13.9

Hello,

When I remove a death point from my map and try to exit the map astral keeps causing my game to crash. I contacted Ftb Chunks as I thought that's what was causing the crash but they informed me it was astral, am I do something wrong or is it a bug. I've attached the last 3 crash reports below. If you could help would be really appreciated.

[crash-2021-03-05_13.40.55-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/6153346/crash-2021-03-05_13.40.55-client.txt)
[crash-2021-03-08_14.01.58-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/6153348/crash-2021-03-08_14.01.58-client.txt)
[crash-2021-03-08_14.06.10-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/6153350/crash-2021-03-08_14.06.10-client.txt)

**Comment by Jeuvke** [comment]
The first crash is caused by Immersive Engineering, and the other two are caused by an invalid config file. Delete your `astralsorcery-common.toml` file and try again.

**Comment by PocketfulOfGeese** [comment]
The two for the invalid config are likely caused by other crashes of unsafe shutdowns while the file is being modified in some fashion, or the underlying storage was corrupted.
