### ISSUE TITLE
Celestial Altar Causes Severe Server Lag

### ISSUE THREAD

**Issue by halseyislife** [HellFirePvP/AstralSorcery#1763]
Recently in my server I had crafted a Celestial Altar atop a fosic field. Everything was okay for a bit until it started immense lag spikes ranging to 40000ms behind.

**Comment by PocketfulOfGeese** [comment]
Run a Sampler on the server to determine the cause and upload it please. Several minute duration.

**Comment by PocketfulOfGeese** [comment]
@halseyislife any update on the above request?
