### ISSUE TITLE
mark current version on curseforge for 1.16.5

### ISSUE THREAD

**Issue by EnderMelody** [HellFirePvP/AstralSorcery#1764]
It seems to work fine in 1.16.5, but you cannot add it to modpacks because it is not marked as compatible on the curseforge page.

**Comment by Shorepion** [comment]
Same experience here.

**Comment by PocketfulOfGeese** [comment]
There's some issues specific to 1.16.5 that need addressing. There is a patch in the works, but if it's not marked for a specific version...there's a reason.
