### ISSUE TITLE
[1.16.5] Getting Crystals or Constellation Papers to yourself via JEI or FTBQ quest rewards gives you one and drops a duplicate, both of which are real

### ISSUE THREAD

**Issue by aaronhowser1** [HellFirePvP/AstralSorcery#1766]
https://user-images.githubusercontent.com/15698722/111769317-159c9080-8877-11eb-81e7-53eafc04ba42.mp4
https://user-images.githubusercontent.com/15698722/111769695-82178f80-8877-11eb-8862-97fed6378e2b.mp4

This is using `astralsorcery-1.16.4-1.13.9`

**Comment by PocketfulOfGeese** [comment]
#1682

**Comment by aaronhowser1** [comment]
Fair enough 👌
