### ISSUE TITLE
Constellation paper duplication glitch with Mekanism Cardboard Box

### ISSUE THREAD

**Issue by gjerm** [HellFirePvP/AstralSorcery#1770]
Astral Sorcery version: astralsorcery-1.16.4-1.13.9
Forge version: 36.1.2
Mekanism version: Mekanism-1.16.5-10.0.21.448

Steps to reproduce: Put constellation papers in a chest, use the cardboard box on the chest, and all the constellation papers come out as items on the ground while also being inside the chest in the cardboard box. Repeatable to get infinite constellation papers.

**Comment by PocketfulOfGeese** [comment]
Sounds more like a mekanism issue, there's no special code in AS to cause this.

**Comment by BlueAgent** [comment]
This bug happens with anything that has a custom item entity, so for the other [custom item entities](https://github.com/HellFirePvP/AstralSorcery/tree/e8434f1a09356632babefee1925626dc3deefb2a/src/main/java/hellfirepvp/astralsorcery/common/entity/item) in Astral Sorcery and also for other mods that do the same.

I explained more here: https://github.com/mekanism/Mekanism/issues/7053#issuecomment-798826597

It's more of a maybe Mekanism, maybe Forge kinda bug / interaction.

Nothing to change on Astral Sorcery's side.

**Comment by gjerm** [comment]
Thank you!
