### ISSUE TITLE
Unable to join a server with the following error: Exception caught during firing event: Trying to modify PerkConverters while modifiers are applied!

### ISSUE THREAD

**Issue by Ridanisaurus** [HellFirePvP/AstralSorcery#1771]
One of the players on our server attempted to reset his point while they had Gems still equipped, and unspent perk points which led to a crash and they are unable to rejoin the server with the attached error.
https://gist.github.com/Ridanisaurus/964391e7d72c3d0c2ac47443b07d85ea
Version: astralsorcery-1.16.4-1.13.9
Forge: 36.1.0

**Comment by PocketfulOfGeese** [comment]
Looks like corruption. Deleting the <player>.astral file for that player and using commands to return their level and/or research unlocks should resolve, but resetting perk points with gems equipped doesn't natively cause that.

Have a pack list/modified pack-list?

**Comment by Ridanisaurus** [comment]
I did reset their astral player data, and that fixed the issue.
This occurred on Enigmatica 6 official server, on E6 0.4.3. I guess the list of mods for that version can be found here. https://www.curseforge.com/minecraft/modpacks/enigmatica6/files/3226572

**Comment by PocketfulOfGeese** [comment]
Has the player attempted resetting points again? I'm wondering if it's repeatable...

**Comment by Ridanisaurus** [comment]
I don't think he has. I attuned him through command and reseted all his points and all of that, so I doubt he had the need to attempt it again. I can ask him to try again tonight when they are online, and will let you know if it's repeatable.
