### ISSUE TITLE
[Question]Astral Sorcery v1.13.9 MC 1.16.5 - How can I edit shrine chests loot table?

### ISSUE THREAD

**Issue by Ashendale** [HellFirePvP/AstralSorcery#1772]
Thought it'd be best to come ask here. Basically title. There is the obvious answer of LootTweaker, but it does not seem to be out for 1.16+. Is there a way to do this within the AS configs and, if not, what is the recommended alternative for 1.16+ for LootTweaker? Editing datapacks?
Thank you for your time.
Also, great job on the mod, I love it.

**Comment by PocketfulOfGeese** [comment]
There is no way through the AS configs, but it should be modifiable via datapacks.
