### ISSUE TITLE
Liquid starlight bug?

### ISSUE THREAD

**Issue by Mr-kk20060135** [HellFirePvP/AstralSorcery#1773]
1. The color of the starlight is strange
2. It has properties similar to air, not water.(Bubble gauge does not come out during survival)

mcver:1.16.5
forgever:1.16.5-forge-36.1.0

↓mod list
> abnormals_core-1.16.5-3.1.1.jar
AI-Improvements-1.16.2-0.3.0.jar
AppleSkin-mc1.16.2-forge-1.0.14.jar
architectury-1.8.131-forge.jar
astralsorcery-1.16.4-1.13.9.jar
AutoRegLib-1.6-47.jar
BetterAdvancements-1.16.5-0.1.0.105.jar
Bookshelf-1.16.5-10.0.7.jar
Botania-1.16.4-414.jar
caelus-forge-1.16.5-2.1.3.0.jar
carryon-1.16.5-1.15.3.13.jar
chiselsandbits-0.3.4-RELEASE.jar
Clumps-6.0.0.17.jar
CodeChickenLib-1.16.4-3.5.1.408-universal.jar
Controlling-7.0.0.14.jar
create-mc1.16.3_v0.3e.jar
curios-forge-1.16.5-4.0.5.0.jar
curiouselytra-forge-1.16.5-4.0.2.3.jar
Cyclic-1.16.5-1.2.0.jar
DataFixerSlayer+1.0-3.jar
EnchantmentDescriptions-1.16.5-7.0.3.jar
endergetic-1.16.4-3.0.0.jar
EnderStorage-1.16.4-2.7.1.166-universal (1).jar
FastLeafDecay-v25.jar
FastWorkbench-1.16.4-4.5.0.jar
forge-1.16.5-36.0.48-installer.jar.log
forgery-1.3.4.jar
FpsReducer-mc1.16.4-1.18.jar
ftb-gui-library-1605.2.1.40-forge.jar
gravestone-1.16.5-1.0.1.jar
Hwyla-forge-1.10.11-B78_1.16.2.jar
invtweaks-1.16.4-1.0.1.jar
ironchest-1.16.4-11.2.10.jar
ironshulkerboxes-1.16.4-5.1.11.jar
jei-1.16.4-7.6.1.71.jar
jeiintegration_1.16.5-7.0.1.15.jar
journeymap-1.16.5-5.7.1.jar
JustEnoughCalculation-1.16.5-3.6.4.jar
JustEnoughResources-1.16.4-0.12.0.109.jar
LavaClearView-1.16.2-1.1.0.jar
MmmMmmMmmMmm-1.16-1.0.1.jar
Neat+1.7-27.jar
NetherPortalFix_1.16.3-7.2.1.jar
observerlib-1.16.4-1.5.1.jar
OptiFine_1.16.5_HD_U_G7.jar
OreExcavation-1.8.154.jar
Patchouli-1.16.4-50.jar
Placebo-1.16.4-4.4.1.jar
polymorph-forge-1.16.5-0.24.jar
QuantumStorage-1.16.4-5.3.0.jar
Quark-r2.4-308.jar
refinedstorage-1.9.12.jar
SolarFluxReborn-1.16.3-16.2.3.jar
solcarrot-1.16.3-1.9.9.jar
StorageDrawers-1.16.3-8.2.2.jar
UntranslatedItems-mc1.16.4-1.0.3.jar
WailaHarvestability-mc1.16.x-forge-1.1.14.jar
WAWLA-1.16.5-8.0.2.jar

![2021-03-25_15 40 09](https://user-images.githubusercontent.com/66465816/112430239-36864980-8d81-11eb-8fe5-2b9ca0ff751d.png)

**Comment by PocketfulOfGeese** [comment]
#1564 #1702 #1678

**Comment by Mr-kk20060135** [comment]
Bug 1 was fixed, but 2 wasn't.
Is this a specification?

**Comment by PocketfulOfGeese** [comment]
Please review the linked tickets. Specifically 1678.

**Comment by Mr-kk20060135** [comment]
Thank you
