### ISSUE TITLE
Liquid Starlight automation

### ISSUE THREAD

**Issue by MrPopannes** [HellFirePvP/AstralSorcery#1777]
Again, i'm looking into automating liquid starlight production.
Unfortunately the insertion of crystals into the Lightwell seems impossible without additional mods.

Am i overlooking any mechanics? Is there some high-end stuff that automates starlight production?

I would love to see a good way to automate the insertion via Astral+Vanilla-mechanics. Maybe a villager inserting crystals that are dropped nearby. And to keep going, you have to feed him golden nuggets once in a while.

I've searched the issues for any similar questions. Pardon me, if this is an old question already answered.

Love the mod! Thanks for your work!

**Comment by PocketfulOfGeese** [comment]
Mods that perform a right click can be used.

In the future, questions or suggestions should be directed onto the Discord server instead.
