### ISSUE TITLE
[Suggestion] Use Mantle on curios/bauble slot, or crafting a varaition to fit in such slot

### ISSUE THREAD

**Issue by Ashendale** [HellFirePvP/AstralSorcery#1778]
Title.
This would include the disabling of its armor stats if equipable on a curios slot, maintaining the attunement effect. I mean, if you're using Curios, odds are that you have other mods and might want the armor bonus from a set (Botania comes to mind, I use Ars and could use its armor mana bonus effects, etc).
Didn't see anything like this on the suggestion/denied megathread, thought it'd be something nice to have.

**Comment by PocketfulOfGeese** [comment]
Didn't look hard, since it is one of the oldest still open tickets. It is also pinned in the Discord.
