### ISSUE TITLE
Dupe Bug with Mekanism Cardboard boxes

### ISSUE THREAD

**Issue by MuteTiefling** [HellFirePvP/AstralSorcery#1779]
Mod Version: astralsorcery-1.16.4-1.13.9
Forge Version: 36.1.0

Mek Version: Mekanism-1.16.5-10.0.21.448

Steps to reproduce:
1.  Place any inventory from any mod or vanilla that is not coded to keep it's inventory on pickup (ie, not a shulker)
2.  Fill the inventory with Rock Crystals or Celestial Crystals
3.  Place a Cardboard box on the inventory

All the crystals in the inventory will spew out all over the ground, however they _remain in the inventory_ once the cardboard box is removed. 

https://streamable.com/hjc6u4

https://github.com/NillerMedDild/Enigmatica6/issues/1847

**Comment by MuteTiefling** [comment]
As near as I can tell this is only happening with Astral Sorcery items, and not all of them. For instance, it does not dupe collector crystals, as shown in the video. 

It does work with Starmetal Ingots, however. 

Also tested a few more random items like Glass Lenses, Resonating Gems, Starmetal Blocks, Marble, Illumination Powder, and Shifting Stars. None of these dupe.

**Comment by BlueAgent** [comment]
Same root cause (duplicate?) of https://github.com/HellFirePvP/AstralSorcery/issues/1770.
I don't think Astral Sorcery can do anything on their end to fix this.

**Comment by MuteTiefling** [comment]
Excellent, thanks. Glad you are at least aware and all parties are involved.

**Comment by PocketfulOfGeese** [comment]
#1770
