### ISSUE TITLE
issue with Optifine shaders (day/night) when looking straight up or down

### ISSUE THREAD

**Issue by phbarroshy** [HellFirePvP/AstralSorcery#1785]
Astral Sorcery makes shaders bug and change the "daytime" when looking straight up or down. Sometimes it bugs the sun position and mobs start spawning after 18h30 but the sun is still at 12h position.

**Comment by PocketfulOfGeese** [comment]
Astral Sorcery has it's own sky shader. Shaders do not typically mix when active at the same time. Astral Sorcery clearly states it is not compatible with other shaders on the mod page, but there is a config option for the client that will disable most of the Astral Sorcery sky shader.

Also, if the sun position is different for time than it should be, that's not Astral Sorcery.
