### ISSUE TITLE
Connecting a (Enhanced) Collector Crystal to a Crystal Lens causes a Server Crash

### ISSUE THREAD

**Issue by creed-us** [HellFirePvP/AstralSorcery#1789]
In my ATM6 server, running AS 1.13.9 on a 1.16.4 server, when any user tries connecting a regular or enhanced collector crystal to a crystal lens with or without a colored lens causes the server to crash due to a NullPointerException.

Furthermore, connecting a regular or enhanced collector crystal to a ritual pedestal seems to have no affect, as there are no additional rays projected by the ritual pedestal. (Where I'm mostly sure that behavior is expected.)

Relevant Crash Dumps:
[crash-2021-04-12_13.07.30-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/6299425/crash-2021-04-12_13.07.30-server.txt)
[crash-2021-04-12_13.48.31-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/6299429/crash-2021-04-12_13.48.31-server.txt)

**Comment by Jeuvke** [comment]
Your lens has no attributes, which is why it throws an NPE. How did you obtain the lens?

**Comment by creed-us** [comment]
It was made using the Celestial Altar.

**Comment by Jeuvke** [comment]
Did you perhaps move it with some moving gadget?

**Comment by creed-us** [comment]
The person that made it recently relocated their base, so it's probable. It's easy to mine it using just your fist, so I'm not sure why they would, but that might've caused it.

**Comment by PocketfulOfGeese** [comment]
Breaking the NBT on a lens or crystal will result in a crash, shouldn't be done.

No clue what they did to blow away the NBT like that, but whatever method they used should probably not be used anymore.
