### ISSUE TITLE
1.10.2 Conversion wand not working

### ISSUE THREAD

**Issue by Zygus42** [HellFirePvP/AstralSorcery#179]
astralsorcery-1.4.1

Shift-right clicking sets the block ok, and can then see a ghost image of what it's going to change, but right-clicking or left-clicking after that does nothing, even though I have plenty of the block to be replaced in my inventory.

**Comment by HellFirePvP** [comment]
For everyone else getting frustrated with this: Fix coming on Saturday with version 1.4.2
