### ISSUE TITLE
Duplication of constellation paper when using Mekanism cardboard boxes

### ISSUE THREAD

**Issue by localzuk** [HellFirePvP/AstralSorcery#1790]
When you have a constellation paper in a chest, and place a Mekanism cardboard box over it to move the chest, a duplicate of the constellation paper within pops out. However, the original is still in the chest when you remove the cardboard box.

This  seems to happen with any number of constellation papers. It also happens with both vanilla chests and chests from the Iron Chests mod.

This was experienced in the All The Mods 6 modpack (version 1.15.10b). 
Specific mod versions: astralsorcery-1.16.4-1.13.9.jar & Mekanism-1.16.5-10.0.21.448.jar

**Comment by PocketfulOfGeese** [comment]
#1770
