### ISSUE TITLE
Item duplication issue when crafting mantle of stars

### ISSUE THREAD

**Issue by pokematrix** [HellFirePvP/AstralSorcery#1791]
When crafting the mantle of stars I'm having an issue with the item in the relays around the altar.

After a second of crafting, one of the items on a relay will appear on a different relay overlapping the existing item.
When I break the relay, the duped item persists until I break the altar interrupting the crafting process.
The whole crafting process stops and only a single beam of light points at the duped relay.

I haven't been able to figure out how to craft the item with this issue.
![image](https://user-images.githubusercontent.com/82664516/115044050-07b94a00-9ecd-11eb-9add-34e070c11ba2.png)
In this case the stardust was duplicated. This was after I loaded the world in a backed up save.
Before I switched to a backup file, the feather would be duplicated without any of the other beams of light appearing.
Also, the feather would be opaque, rather than clear like the stardust here.

I can try to explain further if this explanation is too unclear

**Comment by pokematrix** [comment]
![image](https://user-images.githubusercontent.com/82664516/115044545-857d5580-9ecd-11eb-8284-bd377b4c4a2f.png)
This is the item after the relay has been removed, it cannot be picked up.

**Comment by luna6667** [comment]
The crafting process will "request" an item when it needs it. You then put that item in the relay that is requesting it, and it will request another. The ghost item is there to say "put this item here".
