### ISSUE TITLE
Horologium-Alcara ritual range is lying

### ISSUE THREAD

**Issue by cpaca** [HellFirePvP/AstralSorcery#1792]
In summary: As title says, the horologium-alcara ritual range is lying.

I ended up making a video of the situation, though I must apologize because there is quite a bit of deadtime (checking to see if the night is a Horologium night, etc.)

Video link: https://www.youtube.com/watch?v=qMy6X5WgVxM

MORE INFORMATION:

This is run on a server, on a modpack. Modpack is not on curseforge (i'm not admin, don't ask me). Folders list is here: https://drive.google.com/file/d/1u6Xj5YJ8l9__UE7H1NgHIoxL5xFqdwee/view?usp=sharing

Horologium Crystal Clusters are Size 3, Purity 2, Shape 2, Collection Rate 3

In the time it took me to upload the video, I went back to the minecraft world AND THE RITUAL WAS WORKING AGAIN. The only change I made was that I deleted the crystal that was in the SAME chunk, placed it back down, and did NOT relink it. (the one in the opposite chunk was left relinked) Removing and re-adding the horologium/alcara ritual reset range to default (broken) levels.

**Comment by PocketfulOfGeese** [comment]
Unable to reproduce.
