### ISSUE TITLE
Lightwell doesn't infuse wood.

### ISSUE THREAD

**Issue by Spongman** [HellFirePvP/AstralSorcery#1793]
The book says to throw wood into liquid starlight in order to infuse it. I can throw a stack of logs into a full Lightwell, and it looks like the logs are in the liquid starlight, but it never transforms. 

Either the Lightwell should transform the wood, or the book should say that you can't use a Lightwell for this.

**Comment by pokematrix** [comment]
I don't know if the starlight inside of the well counts as an actual liquid source.
If you use a bucket and place the liquid in a hole or something, it should infuse the wood after a while.

I haven't tried it myself, but that's how it works for crystal tools so I assume it would also be the case for the wood.

**Comment by Spongman** [comment]
yeah, that was my point: the book says putting the wood in starlight should work. i did put the wood in the starlight in the lightwell and it didn't work. the book is poorly written. that is the bug.

**Comment by PocketfulOfGeese** [comment]
The lightwell creates liquid starlight (or other liquids, based on the catalyst material placed into the lightwell). It's not a tool you craft inside of.

**Comment by Spongman** [comment]
yes, I understand that, i'm filing this bug because i believe there is an error in the text of the book - it is supposed to be helping a new user use the mod, but the text that it contains is confusing: it directs the user to perform an action that does not work. at no place in the text does it say "you need to take the liquid out of the lightwell, because even though it looks like there's a pool of liquid there and it looks like you can throw things into it, it doesn't. you need to take the liquid out of the lightwell and put it into the world."
