### ISSUE TITLE
Error when synchronizing baseline information

### ISSUE THREAD

**Issue by FluxMusic** [HellFirePvP/AstralSorcery#1794]
I was looking for many different solutions to this problem in the issue #513 section, but it wasn't able to fix anything. 

The problem persists that, the account marcel_0301 cannot connect to the server. With my account there are no problems. We have been using the same server setup for quite a while and there were no problems until one day I started Astral Sorcery and the server crashed. We tried setting up the server from scratch and adding java arguments, yet nothing seemed to help. I am sorry if I reopen the thread, but we do not want to remove Astral Sorcery from our modpack altogether. 

We are using a custom modpack with about 220 mods on 1.12.2.

The full log is visible on this link: [https://mclo.gs/t5aR2ry](url)

Thak you very much for your help in advance and I apologize for the inconveniences.

**Comment by PocketfulOfGeese** [comment]
MC 1.12 versions are no longer supported. There is no fix for the issue, and even forge devs couldn't determine the trigger. It is not present outside of 1.12 releases.
