### ISSUE TITLE
Mantle of Stars effects not working properly from 1.10.19 to 1.10.27

### ISSUE THREAD

**Issue by SemmelJochen** [HellFirePvP/AstralSorcery#1796]
Hi,
I am playing FTB Revelation (3.3.0) and noticed the Mantle of Stars effects are not present. I have tried the Aevitas and Armara one.
The Version I have tried and failed to use the Mantle: 1.10.19, 1.10.20, 1.10.27
The Versions I have tried and succeeded to use the Mantle: 1.8.10
I have not found any bug reports or help about this problem so, I hope someone can help me. I'd really love to use the Mantle in the MC 1.12.2 Version with the new Perks update in Revelation.

**Comment by PocketfulOfGeese** [comment]
MC 1.12 is unsupported anymore for this mod. That said, they are used normally under the latest 1.12 release of AS. Check the config files or check with the pack authors for information on this to ensure they did not disable them.
