### ISSUE TITLE
Questions about server & skyblock compatibility

### ISSUE THREAD

**Issue by Winddbourne** [HellFirePvP/AstralSorcery#18]
I'm looking at the idea of including this mod in a skyblock pack. I really love the way it brings focus to the sky and since my pack also has a focus on the night (including forbidding sleep) it seems like a perfect fit for the purpose of environmental immersion. However . . . 

- How does the skybox work in multiplayer worlds? I'm trying to keep my pack server friendly if I can and I'm worried that the visuals for the constellations might have issues. Obviously if this is rendered individually for each player there won't be any problems . . . but if every time someone finds a constellation it appears in everyone's sky that would take something away from future players immersion. 

-  I want to make sure that the crystals can be safely moved and spawned into the world. Using a void world type I'm not going to have a ton of landscape where these temples can spawn so I'd want to give them to a player in some other way, and most likely also allow the players to move them around as they build and rebuild their platforms.

**Comment by HellFirePvP** [comment]
> but if every time someone finds a constellation it appears in everyone's sky that would take something away from future players immersion.

Of course only the one that finds the constellation for his progress will see the constellation.

> I want to make sure that the crystals can be safely moved and spawned into the world.

Progression currently relies on you finding one of the shrines with a crystal. As this mod is in _Beta_ there are currently no options to spawn one in that has the properties of the ones that are generated. Moreso because the crystals in the shrines cannot be destroyed due to me trying to respect multiplayer environments, where potentially multiple people want to use the same one to progress.
There is however no real issue to Skyblock packs imo. You can just enable the user options to get the wand, constellation papers, the base altar, marble, aquamarine and rock crystal ores. As well as later on, given enough progression, the option to obtain the starmetal ore.
Potentially you should try and actually play with the mod yourself before including it in a pack.. because from how you described things, it'd seem to me that you weren't aware of some concepts.

**Comment by Winddbourne** [comment]
I've been playing through the pack with the mice and mischief bit by bit series as I consider it; which only gets me up to the exploration section. However before I went too far, invested too much time, and got my hopes up for adding it into a pack I wanted to ask a few questions. 

Playing further is definitely going to be needed for balance purposes as other than the improved tools there should be a lot of upcoming content that I simply haven't seen yet. I'm going to need to know the mod inside and out and that's going to take a big time investment. Given your answer I'm actually looking forward to it. :)

**Comment by HellFirePvP** [comment]
Let's phrase it that way: Vallen did only do 2/4 parts of the mod in his series and those were the smaller parts of it :P 

And regarding your last part: I heavily doubt that. from your current perspective it might seem so, however the temples are merely the starting point and they become increasingly obsolete in the end...

**Comment by Winddbourne** [comment]
Very nice. There is definitely a lot to learn. I'm playing around with the mod in creative now to figure a few things out. 

One problem I've run into is that I've given myself four constellation papers, marble, rock crystal, aqumarine, the resonating wand, and the sooty marble, plus a luminous crafting table . . . but I still haven't had my vision expand to show the second area.  I'm still stuck in exploration. 

Looking at the configs wands doesn't bring up anything about the resonating wand and though I can find options to turn off ores, shrines, etc . . . for spawning I don't see the player options for getting them some other way you mentioned. Am I missing something obvious?

**Comment by HellFirePvP** [comment]
> I'm still stuck in exploration.

you mean in discovery? Progression in research is (at least for all at the moment) gated behind crafting the next tier of the altar(s)

What would you want to config for the resonating wand?... there's nothing to config.. i meant adding crafting recipes via crafttweaker and related to either the vanilla crafting table or other things so you don't have to progress through the mod as normally intended.. so you can somehow skip the need for having to find/create/spawn-in the structures.

**Comment by Winddbourne** [comment]
Yes I mean exploration. LOL. I'm still in the first area and I
misunderstood and thought you meant there were player options included.
Tweaking a recipe in will be easy.

**Comment by HellFirePvP** [comment]
So, well, while this is not 100% adressed & stuff, recipes can be now tweaked in all kinds of ways granting options to make it compatible without needing structures & so on.

Thus, i think this might aswell be resolved.
