### ISSUE TITLE
[Mod Interaction] Modded Skyboxes

### ISSUE THREAD

**Issue by Glowstonesword** [HellFirePvP/AstralSorcery#1801]
With Advanced Rocketry installed, Astral Sorcery constellations do not show up in the sky. This is with the following config changes:
`
    #Whitelist of dimension ID's that will have special astral sorcery sky rendering  
    skyRenderingEnabled = ["minecraft:overworld"]  
    #If a dimension is listed here, the skyrender will only render constellations on top of the existing skybox.  
    skyRenderingConstellations = ["minecraft:overworld"]`

The skyRenderingConstellations does not seem to be functioning with Advanced Rocketry as of versions 1.13.8 (Astral Sorcery) and 2.0.0-10-universal (Advanced Rocketry).

Edit: Upon further testing, skyRenderingConstellations also does not seem to work with the Botania Garden of Glass skybox; this may be a wider modded skybox issue (Astral Sorcery overwrites GoG entirely, similar to Advanced Rocketry overwriting Astral Sorcery entirely). May be related to #1795

**Comment by luna6667** [comment]
Curious, have you tried with "minecraft:overworld" in just the skyRenderingConstellations box and not the skyRenderingEnabled box?

**Comment by Glowstonesword** [comment]
I attempted that, and it did not appear to work. Fully turning off the Advanced Rocketry skybox seemed to work, on the other hand.

**Comment by PocketfulOfGeese** [comment]
Shader fighting is unfortunately a thing that happens.
