### ISSUE TITLE
Mineralis ritual only generates iron, coal, and rarely redstone

### ISSUE THREAD

**Issue by Pyrosminecraft** [HellFirePvP/AstralSorcery#1802]
MC: 1.16.5
Forge: 36.1.3
Astral: 1.13.9
Modlist: https://pastebin.com/MVhtLLeJ

Mineralis ritual only generates iron, coal, and rarely redstone ores. The ritual also seems to function incredibly slowly, even with very good mods on the ritual stone, a high quality collector crystal, and 5 lenses. 

https://cdn.discordapp.com/attachments/837950110003625994/840457958348423178/unknown.png

**Comment by Jeuvke** [comment]
Can't reproduce. As for the ritual being slow, you added 5 lenses. Lenses massively increase the range of rituals, which makes them relatively slower.

**Comment by Pyrosminecraft** [comment]
Ok, that's interesting to know about the lenses, because that fact is not reflected in any documentation whatsoever. The ingame book states that lenses 'increase the ritual's operating speed'. The mineralis constellation itself states that "how often this transmutation occurrs increases as more starlight is channeled into the ritual'. If using lenses actually increases range but reduces the intensity of a ritual, that really should be laid out clearly, as opposed to the current situation which clearly states the **opposite**.

**Comment by Jeuvke** [comment]
The 5th lens you add increases the ritual's speed by 32%. But 5 lenses increase the ritual's volume by way more than 32%, so the relative speed decreases. So technically the tome isn't wrong.
