### ISSUE TITLE
Luminous crafting recipe won't work

### ISSUE THREAD

**Issue by soronorjs** [HellFirePvP/AstralSorcery#1806]
I do not know if this isn't a bug or if this is reported already but I can't craft the luminous crafting table, I have placed a crafting table right under the crystal I have a resonating wand and I think some rock crystals too I also have constellation papers but when I try to craft it it _**won't work**_. I also don't have the recipe in the _Astral Tome_.

If it is another recipe or I haven't unlocked it please tell me what I have to do, thanks.

**_soronorjs_**

**Comment by xaelith** [comment]
> I do not know if this isn't a bug or if this is reported already but I can't craft the luminous crafting table, I have placed a crafting table right under the crystal I have a resonating wand and I think some rock crystals too I also have constellation papers but when I try to craft it it _**won't work**_. I also don't have the recipe in the _Astral Tome_.
> 
> If it is another recipe or I haven't unlocked it please tell me what I have to do, thanks.
> 
> **_soronorjs_**

This has been brought up before (my apologies to the devs for not knowing a link off the top of my head). Unless the modpack you're playing has added a specific recipe, the intended way to receive a luminous crafting table is to place a normal crafting table under a collector crystal found in one of the larger Astral temples. Make sure said crystal also has direct view to the sky (no blocks above). Assuming all the requirements have been met, the crafting table will change into the luminous crafting table within a second or two.

**Comment by soronorjs** [comment]
> > I do not know if this isn't a bug or if this is reported already but I can't craft the luminous crafting table, I have placed a crafting table right under the crystal I have a resonating wand and I think some rock crystals too I also have constellation papers but when I try to craft it it _**won't work**_. I also don't have the recipe in the _Astral Tome_.
> > If it is another recipe or I haven't unlocked it please tell me what I have to do, thanks.
> > **_soronorjs_**
> 
> This has been brought up before (my apologies to the devs for not knowing a link off the top of my head). Unless the modpack you're playing has added a specific recipe, the intended way to receive a luminous crafting table is to place a normal crafting table under a collector crystal found in one of the larger Astral temples. Make sure said crystal also has direct view to the sky (no blocks above). Assuming all the requirements have been met, the crafting table will change into the luminous crafting table within a second or two.

Thank you, found that out a while ago but still thank you.
