### ISSUE TITLE
Broken starlight gen in 1.16 version

### ISSUE THREAD

**Issue by rbaker87** [HellFirePvP/AstralSorcery#1808]
When attempting to add Enhanced Collector Crystal structures to an Iridescent Altar I noticed that starlight caps out during the day at around 1/3 charge despite the fact that the Astral Tome clearly states that correct collector crystal setups can achieve maximum starlight during the day (EDIT: Now that I search for it, that apparently came from an external source rather than the in-game tome itself. Maybe this was an intentional change?...)
![image](https://user-images.githubusercontent.com/1047829/119007704-79b70000-b95f-11eb-847b-5b30d64e6e68.png)

No matter what amount of crystals are placed and in any given configuration, the same exact amount of starlight is produced
![image](https://user-images.githubusercontent.com/1047829/119008068-d31f2f00-b95f-11eb-94f2-70f88103e01b.png)

Combining the beams gives the same result:
![image](https://user-images.githubusercontent.com/1047829/119008309-0f528f80-b960-11eb-8585-2a2f469e06c1.png)

Even this abomination produces exactly the same amount of starlight:
![image](https://user-images.githubusercontent.com/1047829/119008448-2beec780-b960-11eb-880e-34ea5ae2916e.png)

These pictures were from tests in the Valhelsia3 modpack on astralsorcery-1.16.4-1.13.9, but I went and reproduced the exact same results using only astral sorcery and its 2 dependencies (curious-forge and observerlib). No matter what configuration is provided, starlight in an Iridescent Altar caps at about 1/3 during the day and at around 90-95% during the night.

**Comment by Jeuvke** [comment]
Not a bug. Each type of starlight collection has a cap in the altar. (Also I recommend you read up about starlight cannibalisation, since you're having a lot of it there.)

**Comment by HellFirePvP** [comment]
Indeed, multiple sources of starlight are needed.
Next update will also feature an indicator for when crystals are placed too close to each other. Their ideal distance is ~16 blocks apart.

**Comment by rbaker87** [comment]
> Indeed, multiple sources of starlight are needed.
> Next update will also feature an indicator for when crystals are placed too close to each other. Their ideal distance is ~16 blocks apart.

Sorry I don't mean to push a potential non-issue, but if this is indeed the case, then there may still be a bug to report or an unintentional cap in place. Multiple crystals spaced 16 blocks apart and of different types (different attunements, enhanced vs non-enhanced, celestial vs non-celestial, etc.) all cap out at roughly 1/3 starlight during the day and just shy of 100% during the night. Everything beyond that point produces no results.

I just tested every configuration that I could come up with of 2 starlight sources at a 15, 16 and 17 block spacing. No matter what setup I throw at it, a single enhanced collector crystal produces the "cap" (1/3 at noon). Two non celestial collector crystals of any quality produce the same cap. I also get the same results with two celestial collector crystals of any quality. So far as I can gather, crystal quality (size/purity/collection rate) has absolutely zero impact on reaching this starlight cap. You will always need 2 collector crystals or 1 enhanced collector crystal. Starlight cannibalism never has a chance to come into play since the 1/3 cap is so easily achieved even with low quality plain collector crystals.

Even if this cap is intentional, the difficulty curve probably isn't. There is basically no reason to ever create an enhanced collector crystal configuration for use in the altar. It's only purpose right now is for speeding up transmutations or effect lenses.
