### ISSUE TITLE
Skywave and Treelighting

### ISSUE THREAD

**Issue by chaoskie** [HellFirePvP/AstralSorcery#181]
Skywave fields give a blank/censored like texture when it gets night. 
Also trees change to extremely bright colours when this happens. 
Haven't made screenshots yet, will do so if you need it.

**Comment by HellFirePvP** [comment]
Yea. screenshots please. also be sure to test without optifine.

**Comment by HellFirePvP** [comment]
Information never provided. Reopen the issue once you want to add more information..

**Comment by chaoskie** [comment]
haven't been able to find a new astral field (they are extremly difficult to find for some reason)
perhaps an idea to make a spawn command for the field.
I'll keep searching  and when i encounter one I'll let you know if it still exists with provided screenshot. I have no optifine or other similar mods installed.
