### ISSUE TITLE
Create Mod Deployer block won't activate a Starlight Infuser with the Resonating Wand.

### ISSUE THREAD

**Issue by Echo343** [HellFirePvP/AstralSorcery#1811]
This is probably a bug for the Create Mod, but perhaps there is something different about the Resonating wand?

**Comment by Jeuvke** [comment]
Not a bug. To use the starlight infuser, you need to have certain progression unlocked. The deployer doesn't have this, therefore it can't activate it.

**Comment by HellFirePvP** [comment]
What Jeuvke wrote.
