### ISSUE TITLE
Spatial Manipulation doesn't pick up item drops "created" by mods

### ISSUE THREAD

**Issue by Zerino** [HellFirePvP/AstralSorcery#1812]
I have Spatial Manipulation on my perks, but it doesn't pick up monsters' heads dropped by a sword with Vorpal or an Axe of Cleaving. It also doesn't pick up a mob spawner dropped with Silk Touch. Interestingly, it does pick up Wither Skeleton Skulls that are naturally dropped.

The mod list is Valhelsia 3 for Minecraft 1.16.5, but the involved mods are:
Ensorcellation (adds Vorpal enchantment for sword and axe, chance to drop mob heads), ensorcellation-1.16.4-1.2.0
Eidolon (adds Axe of Cleaving, has a chance to drop mob heads), eidolon-0.2.7
Apotheosis (adds Spawner as a drop when mined by a pickaxe with Silk Touch), Apotheosis-1.16.4-4.5.2
Also, the Astral Sorcery file is astralsorcery-1.16.4-1.13.9

To reproduce, simply get one of the weapons mentioned and kill mobs that drop heads or a pickaxe with Silk Touch to mine a spawner.

**Comment by Zerino** [comment]
Adding to tests, tried out a profile with only the mentioned mods and their dependencies, Spatial Manipulation still didn't pick up heads or spawners, so no weird interactions from other mods in Valhelsia 3.

Here are the selected files from curse forge (dependencies installed automatically):
Ensorcellation (ensorcellation-1.16.4-1.2.0)
Eidolon (eidolon-0.2.7)
Apotheosis (Apotheosis-1.16.4-4.6.0)
Astral Sorcery (astralsorcery-1.16-1.16.5-1.13.10)

**Comment by HellFirePvP** [comment]
This will be adjusted for the next version.
Though it is notable to mention that this will mess up with other mods which collect/modify drops before AS now does, so other drops could end up dropping as items, while these are collected properly.
