### ISSUE TITLE
Fatal crash when creating celestial crystals with starmetal and collector crystals.

### ISSUE THREAD

**Issue by HoshinOFW** [HellFirePvP/AstralSorcery#1813]
I've tested this in singleplayer and multiplayer.
I don't know much about the code so I don't know about the specifics, but the crash happens when a chunk is loaded that contains a celestial crystal cluster on top of a starmetal ore that is linked directly to a collector crystal.
When you first create the cluster on top of the ore, it won't crash it immediately, but after the first crash the game will crash immediately every time after loading up the world.

Happened every time when I recreated that.
Tested in: Singleplayer modded, singleplayer without any other mods apart from astral sorcery dependencies, and multiplayer modded.

Tested in forge: 36.1.24 and 36.1.23

Crash report when in modded multiplayer:
https://pastebin.com/tFmx7yXA 

Crash report when in singleplayer with only dependencies installed:
https://pastebin.com/DR5CJdTk

First time submitting an issue, tell me if you need more info or something.

**Comment by SylvanusPC** [comment]
Just started getting this same crash on my server. Anyone who loads the chunks with the problem brings the whole server down. Unplayable for now.
