### ISSUE TITLE
Crash when trying to open Starlight Altar in Astral Tome [1.3.11]

### ISSUE THREAD

**Issue by Artimba** [HellFirePvP/AstralSorcery#1819]
Hey, I'm experiencing a crash whenever I try opening the starlight altar page in the Astral Tome due to java.lang.NullPointerException: mouseClicked event handler. I'm playing on a custom modpack and I recognize that it could be another mod causing this, but I wanted to throw this out before I do any further testing with the crash to see if anyone has experienced it. 
MC Version: 1.16.5
AS Version: 1.3.11
Forge Version: 36.1.0
https://hastebin.com/hewoxizepa.rb - Crash log

Update: Have tried standalone, as well as with the entire modpack enabled (with and without optifine), and with multiple computers. The crash only has happened on the initial server so far and has not been able to be replicated on singleplayer. I also am getting an additional crash when trying to preview the starlight crafting altar
https://hastebin.com/imuhuqeqej.rb - Crash log of preview

Update 2: The issue seems to be only in the structure renderer of observerlib, but I have failed in every attempt to replicate the issue. I have tried different servers, it only occurs in the world I have been playing on for about a week or so, I have also tried multiple players and multiple locations, it is consistently crashing upon needing the renderer. 

Update 3: The crash only seems to happen on dedicated server clients, able to replicate it in the full modlist, will work on narrowing down culprit tomorrow. (LAN and Singleplayer work completely fine)

***
**Update 4: Culprit found! The beta version of Better Weather causes this crash. I was able to get it to consistently crash try to see the preview of the starlight altar (Still on a dedicated server). I understand that this 100% is probably on better weather, but I thought it best to let you know
https://hastebin.com/kubapezewe.properties - Clean crash log of just the mods isolated**
***

**Comment by HellFirePvP** [comment]
Yes, this will be fixed with OL 1.5.3, i didnät push that into 1.5.2 (for some reason)
