### ISSUE TITLE
Scorching Heat enchantment cannot be applied to any tools

### ISSUE THREAD

**Issue by Ninjawolf0007** [HellFirePvP/AstralSorcery#1820]
In Astral Sorcery version 1.13.11 in the All The Mods 6 modpack (pack version 1.6.7), I am unable to add the scorching heat enchantment to any tools and JEI shows that there are no compatible tools for the enchantment.

**Comment by PocketfulOfGeese** [comment]
It is intended that this only be applicable via the refraction table.

**Comment by Eragoneq** [comment]
> It is intended that this only be applicable via the refraction table.

No it's not, it actually makes it so that the enchant cannot be applied to anything even via refraction table. In the night vision case it works both on anvil and in the refraction table. This should be considered a bug.

**Comment by PocketfulOfGeese** [comment]
That scorching heat cannot be applied is a separate issue (#1844), and doesn't change that scorching heat is intended to only be applicable via refraction table.

**Comment by Eragoneq** [comment]
> That scorching heat cannot be applied is a separate issue (#1844), and doesn't change that scorching heat is intended to only be applicable via refraction table.

Then idk if this is an inconsistency or is this supposed to be like this, but night vision can be applied on a book and then in an anvil.

Also as the temporary fix I would merge the https://github.com/HellFirePvP/AstralSorcery/pull/1824 , until there is no proper fix that requires more logic.

**Comment by Eragoneq** [comment]
The author of the pull request did the changes that I proposed so that it's consistent with Night Vision.

Please review this pull request  (#1824) and accept it until there is no proper change on your part.

**Comment by TheAussieSlime** [comment]
in 1.6.5 I am unable to apply scorching heat directly to any tools via the stellar refraction table, I tried all vanilla pickaxes and astral sorcery ones. I believe this issue still persists.
