### ISSUE TITLE
This is a very serious problem about star capabilities.

### ISSUE THREAD

**Issue by fkh233** [HellFirePvP/AstralSorcery#1821]
https://paste.ubuntu.com/p/qBHSfZQ5hB/
https://paste.ubuntu.com/p/49D78Km6SP/
The chain mining ability in the star capacity will cause the server card thread to cause the server to downtime.

**Comment by PocketfulOfGeese** [comment]
What versions of mods are in-use, forge version, and java version? I'm not seeing this replicated on some other servers.

edit: also MC 1.12 versions aren't supported anymore.

And neither is spigot, nor has AS ever supported it.
