### ISSUE TITLE
Sky bug with BSL Shaders

### ISSUE THREAD

**Issue by mysticetus09** [HellFirePvP/AstralSorcery#1822]
I'm new to submitting report of bugs like this, but I need help about how to fix the sky bug with BSL Shaders. I tried searching it upon the google, but only finding a different config file on the internet that doesn't exist on my files. 

" astralsorcery-client-toml "

[rendering]
	#Defines the minimum y-level the fosic resonator will display the fosic field on.
	#Range: 0 ~ 256
	minYFosicDisplay = 0
	#Enables/Disables all patreon effects.
	patreonEffects = true
	#If a dimension is listed here, the skyrender will only render constellations on top of the existing skybox.
	skyRenderingConstellations = []
	#Sets the amount of particles/effects
	#Allowed Values: NONE, MINIMAL, LOWERED, ALL
	particleAmount = "ALL"
	#Defines how close to the position of a particle/floating texture you have to be in order for it to render.
	#Range: 1.0 ~ 512.0
	maxEffectRenderDistance = 64.0
	#Whitelist of dimension ID's that will have special astral sorcery sky rendering
	skyRenderingEnabled = ["minecraft:overworld"]

while the other one is,
 " astralsorcery-common.toml "

[worldgen]

	[worldgen.small_shrine]
		#Sets the categories to generate this feature in. Available categories: none,taiga,extreme_hills,jungle,mesa,plains,savanna,icy,the_end,beach,forest,ocean,desert,river,swamp,mushroom,nether
		biomeCategoryNames = ["forest", "plains"]
		#Sets the worlds to generate this feature in. (Does NOT work for structures!)
		worldNames = ["overworld"]
		#Defines the structure spacing for worldgen
		#Range: 1 ~ 512
		spacing = 18
		#Defines the structure separation for worldgen
		#Range: 1 ~ 512
		separation = 4
		#Set this to true to let this feature generate in any biome.
		everyBiome = false
		#Set this to true to let this feature generate in any world. (Does NOT work for structures!)
		everyWorld = false
		#Set this to false to disable this worldgen feature.
		enabled = true

	[worldgen.marble]
		#Sets the categories to generate this feature in. Available categories: none,taiga,extreme_hills,jungle,mesa,plains,savanna,icy,the_end,beach,forest,ocean,desert,river,swamp,mushroom,nether
		biomeCategoryNames = []
		#Sets the worlds to generate this feature in. (Does NOT work for structures!)
		worldNames = []
		#Set this to true to let this feature generate in any biome.
		everyBiome = true
		#Set this to true to let this feature generate in any world. (Does NOT work for structures!)
		everyWorld = true
		#Set this to false to disable this worldgen feature.
		enabled = true

	[worldgen.glow_flower]
		#Sets the categories to generate this feature in. Available categories: none,taiga,extreme_hills,jungle,mesa,plains,savanna,icy,the_end,beach,forest,ocean,desert,river,swamp,mushroom,nether
		biomeCategoryNames = ["icy", "extreme_hills"]
		#Sets the worlds to generate this feature in. (Does NOT work for structures!)
		worldNames = ["overworld"]
		#Set this to true to let this feature generate in any biome.
		everyBiome = false
		#Set this to true to let this feature generate in any world. (Does NOT work for structures!)
		everyWorld = false
		#Set this to false to disable this worldgen feature.
		enabled = true

	[worldgen.desert_shrine]
		#Sets the categories to generate this feature in. Available categories: none,taiga,extreme_hills,jungle,mesa,plains,savanna,icy,the_end,beach,forest,ocean,desert,river,swamp,mushroom,nether
		biomeCategoryNames = ["mesa", "desert", "savanna"]
		#Sets the worlds to generate this feature in. (Does NOT work for structures!)
		worldNames = ["overworld"]
		#Defines the structure spacing for worldgen
		#Range: 1 ~ 512
		spacing = 18
		#Defines the structure separation for worldgen
		#Range: 1 ~ 512
		separation = 4
		#Set this to true to let this feature generate in any biome.
		everyBiome = false
		#Set this to true to let this feature generate in any world. (Does NOT work for structures!)
		everyWorld = false
		#Set this to false to disable this worldgen feature.
		enabled = true

	[worldgen.aquamarine]
		#Sets the categories to generate this feature in. Available categories: none,taiga,extreme_hills,jungle,mesa,plains,savanna,icy,the_end,beach,forest,ocean,desert,river,swamp,mushroom,nether
		biomeCategoryNames = []
		#Sets the worlds to generate this feature in. (Does NOT work for structures!)
		worldNames = ["overworld"]
		#Set this to true to let this feature generate in any biome.
		everyBiome = true
		#Set this to true to let this feature generate in any world. (Does NOT work for structures!)
		everyWorld = false
		#Set this to false to disable this worldgen feature.
		enabled = true

	[worldgen.ancient_shrine]
		#Sets the categories to generate this feature in. Available categories: none,taiga,extreme_hills,jungle,mesa,plains,savanna,icy,the_end,beach,forest,ocean,desert,river,swamp,mushroom,nether
		biomeCategoryNames = ["icy", "extreme_hills"]
		#Sets the worlds to generate this feature in. (Does NOT work for structures!)
		worldNames = ["overworld"]
		#Defines the structure spacing for worldgen
		#Range: 1 ~ 512
		spacing = 18
		#Defines the structure separation for worldgen
		#Range: 1 ~ 512
		separation = 4
		#Set this to true to let this feature generate in any biome.
		everyBiome = false
		#Set this to true to let this feature generate in any world. (Does NOT work for structures!)
		everyWorld = false
		#Set this to false to disable this worldgen feature.
		enabled = true

	[worldgen.rock_crystal]
		#Sets the categories to generate this feature in. Available categories: none,taiga,extreme_hills,jungle,mesa,plains,savanna,icy,the_end,beach,forest,ocean,desert,river,swamp,mushroom,nether
		biomeCategoryNames = []
		#Sets the worlds to generate this feature in. (Does NOT work for structures!)
		worldNames = ["overworld"]
		#Set this to true to let this feature generate in any biome.
		everyBiome = true
		#Set this to true to let this feature generate in any world. (Does NOT work for structures!)
		everyWorld = false
		#Set this to false to disable this worldgen feature.
		enabled = true

I don't see anywhere or seems I don't have the file that writes in it with "weakSkyrenders" or something.

**Comment by luna6667** [comment]
this is because "weakSkyRender" is for 1.12 and before. you will want to remove "minecraft:overworld" from here:
![image](https://user-images.githubusercontent.com/11493210/120654442-b13da600-c44f-11eb-9701-024165b69f63.png)
and move it here, if you still want to see the constellations: 
![image](https://user-images.githubusercontent.com/11493210/120654510-c581a300-c44f-11eb-8f20-5fe2857f53d4.png)
But it is generally not recommended to run optifine/shaders and astral sorcery.

**Comment by mysticetus09** [comment]
It kinda felt off not having shaders on it. Thanks for your help, everything is going well now.
