### ISSUE TITLE
no structures in custom made dimensions

### ISSUE THREAD

**Issue by benbenlaw** [HellFirePvP/AstralSorcery#1825]
unable to spawn structure in datapack creating dimensions
![image](https://user-images.githubusercontent.com/42780877/120801867-a5c6a980-c539-11eb-8353-9d7c0c6b38a9.png)
this works for other modded and vanilla structure but always get this error with astral

**Comment by PocketfulOfGeese** [comment]
You would need to review the logs to determine what is going on.
