### ISSUE TITLE
Formation Wand Glitch

### ISSUE THREAD

**Issue by T1M03** [HellFirePvP/AstralSorcery#1827]
when I try to build with the formation wand, i am only able to build the first block(using line towards player) and the rest of it just disappears but the used blocks for that section in my inventory is gone and I cannot pass through these "invisible" blocks since they are technically there but invisible. I always have to leave and rejoin the server for me to see these blocks

**Comment by PocketfulOfGeese** [comment]
This is a server/client desync based on description, and I cannot reproduce this. Sounds like there's a plugin or other mod interfering.
