### ISSUE TITLE
There are four lights!

### ISSUE THREAD

**Issue by benza59** [HellFirePvP/AstralSorcery#1828]
Tried linking collector crystal via lenses to the astral crafting table. Took down the server and kept it down untill it was rolled back

Modpack: ATM6 To the sky 1.1.0

[crash-2021-06-05_18.54.51-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/6615736/crash-2021-06-05_18.54.51-server.txt)

**Comment by Jeuvke** [comment]
You are using lenses with null attributes. Lenses need attributes or they will crash the server if linked.
