### ISSUE TITLE
AS binding tool bug

### ISSUE THREAD

**Issue by netish** [HellFirePvP/AstralSorcery#183]
Hey we're using this mod in our modpack and it caused the server to crash https://pastebin.com/ETBcjq5r when someone was right-clicking a lens using the AS binding tool. The weirdest part was after the server was restarted all the block ids of placed items were scrambled as well. For example - a cooking for blockheads book was instead a forestry squeezer. Upon resetting the server to an older save we were okay and we tested for repeatability and it didn't happen again so we're not sure if it was a one time thing or what. (I have a copy of the broken world saved let me know if you want to see that.)

**Comment by HellFirePvP** [comment]
Uh, so this crash is basically the result of something else going wrong - namely a lens that's missing its crystal properties completely... I'm uncertain how this could happen besides someone obtained a lens/prism without any properties through some invalid means... so.. yea. idk what say to this.
Any reliable way to reproduce this? Any way to obtain said lenses without properties?

**Comment by HellFirePvP** [comment]
Well, information never provided. At least more safety handling is in place for this now.
