### ISSUE TITLE
dimensions 

### ISSUE THREAD

**Issue by benbenlaw** [HellFirePvP/AstralSorcery#1830]
added a custom dimension through vanilla minecraft datpack pack to make a world thats always night. however the mod still follows the overworld "time" meaning that even in darkness luminous crafting doesnt work. Once the correct time is reached in the overworld this problem disappears

**Comment by PocketfulOfGeese** [comment]
Yes. There is no "day" or "night" time state, just world time in minecraft.

And if you locked world time to when it was always night, no time would pass and a chunk of the mod wouldn't work.

**Comment by benbenlaw** [comment]
so its not possible to do what i want then?
have a locked time and have astral sorcery recipes work if not i guess i will have to work something out

**Comment by PocketfulOfGeese** [comment]
Outside of recipes that require night time, you can already craft during the "day" hours as long as you have sufficient Starlight power. There are several ways to gain that during the day already.

Otherwise, no.

**Comment by benbenlaw** [comment]
thanks
