### ISSUE TITLE
Client side crashes in server when a person is trying to click a starlight crafting altar with a Resonating Wand, using minecraft 1.16.5 using latest astral Sorcery

### ISSUE THREAD

**Issue by lricciardi** [HellFirePvP/AstralSorcery#1831]
[crash-2021-06-09_20.30.03-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/6627594/crash-2021-06-09_20.30.03-client.txt)

**Comment by PocketfulOfGeese** [comment]
What were they trying to craft and with which tier altar? I cannot reproduce this with only Astral Sorcery.
