### ISSUE TITLE
Enhanced Celestial incompability (this is supposed to be a blood moon and the moon isn't red)

### ISSUE THREAD

**Issue by Sacri-Pan** [HellFirePvP/AstralSorcery#1832]
![2021-06-14_10 10 10](https://user-images.githubusercontent.com/74361905/121864093-d0b0ba80-ccfc-11eb-8a31-e912dd08ebbe.png)

**Comment by PocketfulOfGeese** [comment]
Conflicting shaders will cause incompatibilities,yes.
