### ISSUE TITLE
How to disable the Astral Tome auto-give in 1.16.5 ?

### ISSUE THREAD

**Issue by Sacri-Pan** [HellFirePvP/AstralSorcery#1833]

**Comment by Kutomi1** [comment]
I'd also like to remove it, but it seems there isn't an option for that in the config. However, you can use the Custom Starter Gear mod and use that to disable it for now I guess. (hopefully they'll add a config for it tho)

**Comment by Figgmastah** [comment]
This was just what I needed

**Comment by Figgmastah** [comment]
If you go in your serverconfigs folder you'll find astralsorcery.toml. put it in the defaultconfigs folder to make it work in every world and set giveJournalOnJoin to false 👌
