### ISSUE TITLE
Rock Crystals Duplicating When in Chest Covered by Mekanism Cardboard

### ISSUE THREAD

**Issue by mmansell-durex** [HellFirePvP/AstralSorcery#1836]
When there are rock crystals in a vanilla chest, applying the mekanism cardboard to move the chest will double the rock crystals in the chest.  I found this bug in Direwolf20's 1.16 modpack.

**Comment by Jeuvke** [comment]
This is a bug with forge. https://github.com/MinecraftForge/MinecraftForge/issues/7785
