### ISSUE TITLE
I can't move on...

### ISSUE THREAD

**Issue by ghost** [HellFirePvP/AstralSorcery#1838]
Im playing project ozone 3 normal mode and im doing astral sorcery rn. I made a celestial altar, but i am having trouble making the starlight infuser. I cant get enough starlight in the altar to craft it. I used the resonator to put the altar in a good spot, but now, when i use the resonator,all the particles moved over. Should i rebuild the altar in a patch of particles? will that help?

**Comment by xaelith** [comment]
While using the particle fields is a great starting point, building at a high y-level yields better results. I like to build my altars at about y=130, or a few blocks above where the "fancy" clouds would appear (the cloud layer that can be turned on or off in the Video Settings). Also, look into augmenting your already-built structure (unless you enjoy tearing down and rebuilding your altar). There is a passage about using a Spectral Relay and a Glass Lens in the "Exploration" chapter. Using one or two of the multi-blocks has helped me forego searching for the particle fields in many a modpack.

Best of luck 🙂👍
