### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by crazysycho** [HellFirePvP/AstralSorcery#1839]
Every time I tried to load my minecraft world, it crashes the game. I’ve tried to fix it and I cant

**Comment by PocketfulOfGeese** [comment]
Have you considered a crash log upload to pastebin?

**Comment by crazysycho** [comment]
Wdym

**Comment by PocketfulOfGeese** [comment]
You have basically walked into a mechanic shop and said "my car won't start", but didn't bring the car to be looked at.

Upload your client crashlog to pastebin.com and copy and paste the url as a comment here so it can be accessed. Do not paste the crash log to github directly.

**Comment by crazysycho** [comment]
<img width="697" alt="game crash" src="https://user-images.githubusercontent.com/71881068/122937376-454abf80-d3b5-11eb-8f2d-d03442941675.PNG">


this is all i get

**Comment by PocketfulOfGeese** [comment]
You need to look up your client crash logs. Google will help with locating those with your install.

What makes you think it's an Astral Sorcery issues?

edit: Actually, you should join the discord and get assistance there, instead.

**Comment by crazysycho** [comment]
file:///C:/Users/kavry/AppData/Roaming/.minecraft/crash-reports/crash-2021-06-22_23.47.54-server.txt

**Comment by PocketfulOfGeese** [comment]
That..doesnt help. Please go to the discord and ask for help in the off-topic channel for general minecesft troubleshooting assistance.
