### ISSUE TITLE
Area of Effect doesn't work on projectiles like thrown trident in survival mode.

### ISSUE THREAD

**Issue by Vearmus** [HellFirePvP/AstralSorcery#1840]
But it does work in creative mode.

**Comment by PocketfulOfGeese** [comment]
Can you clarify what this means? Area of Effect what?

**Comment by Vearmus** [comment]
The key perk ,"Area of Effect"
![QQ图片20210622223126](https://user-images.githubusercontent.com/47314691/122943465-a10f4b80-d3a9-11eb-8baa-cd2aefcec97c.png)
@Doomgull
