### ISSUE TITLE
Vicio Ritual not allowing flight - 1.16.5

### ISSUE THREAD

**Issue by NotWillFerrell** [HellFirePvP/AstralSorcery#1843]
The version of Astral Sorcery that I'm using is AstralSorcery-1.16.5-1.13.12

This is a somewhat large custom modpack, and however doubtful I am that this issue is just a mod conflict, I'll include a screenshot or two of the mod list at the end of this issue just to be sure.

The screenshots are from a friend's server, although it's also highly unlikely to be a server problem, as the same thing occurred when I went to recreate the problem in a singleplayer test world.

**The issue in question:** I've fully setup a pedestal for a Vicio ritual, and despite all signs showing that it should be granting me flight, it does not. 

The Pedestal:
![2021-06-22_06 04 06](https://user-images.githubusercontent.com/86395366/123204404-e47ebe00-d46c-11eb-8f1a-826fc2ab8350.png)

The Pedestal from a slightly worse angle:
![2021-06-22_06 04 20](https://user-images.githubusercontent.com/86395366/123204426-f3fe0700-d46c-11eb-9283-c96613e62b10.png)

Final screenshot with both chunk borders and Domic Resonator active
![2021-06-24_00 12 22](https://user-images.githubusercontent.com/86395366/123206233-3117c880-d470-11eb-942e-8f072da8daa6.png)

Here is a quick list of things I've tried to solve this:
- Move the ritual
- Make sure the entire ritual is in the same chunk
- Triple-checked that no fancy light sources or invisible blocks from other mods are inside the ritual multiblock area
- Add/remove any amount of lenses 
- Raise the Collector crystal above the pedestal (I don't know if that's even an actual mechanic, I was just trying anything at this point)
- Unequipping my Vicio-attuned Mantle of Stars
- Resetting my perks, which removed the perk that allows my Vicio Mantle to grant me flight instead of Elytra gliding
- Min/Max the stats of both the collector crystal and the ritual crystal as much as possible

The crystals in question:
- Ritual Crystal
![2021-06-24_00 05 04](https://user-images.githubusercontent.com/86395366/123205657-26106880-d46f-11eb-9bc3-8bf8bbaab56e.png)

- Collector Crystal
![2021-06-24_00 05 07](https://user-images.githubusercontent.com/86395366/123205665-290b5900-d46f-11eb-82ab-545c63c39a9c.png)

Do keep in mind, I kinda bum rushed through the progression of Astral Sorcery a bit in this world (courtesy of Mischief of Mice's videos), so it may also be possible that I'm just a complete idiot and skipped a very important part of setting up a ritual.

Here's the full mod list in case that ends up being important:
![image](https://user-images.githubusercontent.com/86395366/123205458-cc0fa300-d46e-11eb-9e24-248740fe4376.png)
![image](https://user-images.githubusercontent.com/86395366/123205488-da5dbf00-d46e-11eb-87be-b888f411cde4.png)

**Comment by PocketfulOfGeese** [comment]
I'm unable to replicate this. Can you verify the ritual hasn't been disabled in the astralsorcery.toml config for the world?

![image](https://user-images.githubusercontent.com/12677933/123292791-64df0680-d4e1-11eb-8efd-31e15809a3e8.png)

Alternatively, something may be overriding or disabling the creative flight tag for the player (config option, another mod, etc).

In case it matters, I tried this with the same AS, Curios, and ObserverLib versions and Forge 36.1.32 when failing to recreate it.

```		[constellation.effect.vicio]
			#Defines the radius (in blocks) in which the ritual will do its effects.
			#Range: 1.0 ~ 512.0
			range = 24.0
			#Defines the increase in radius the ritual will get per active lens enhancing the ritual.
			#Range: 0.0 ~ 128.0
			rangePerLens = 16.0
			#Set this to false to disable this ritual effect
			enabled = true

**Comment by NotWillFerrell** [comment]
Well, I finally found enough time to go through my mod list again, just to double check it wasn't a conflict, and lo and behold, it was an addon mod for Create of all things.  Sorry about all the hassle.

For anyone in the future with this problem, the addon's name was Create: Stuff Additions, and it seemed to be a problem with the way the jetpack worked that was preventing creative-like flight of any kind while in survival, with or without the jetpack equipped.
