### ISSUE TITLE
Crafting in altars with bucket of liquid starlight doesn't consume the liquid starlight

### ISSUE THREAD

**Issue by FuzzyCrafter** [HellFirePvP/AstralSorcery#1846]
In previous versions, crafting with a bucket of liquid starlight would consume the fluid, leaving an empty bucket. It appears not to do that anymore.
The example screenshot is of upgrading from Luminous to Starlight altars, but the same happens with making a Fosic Resonator, Shifting Star and I assume all other recipes like it.
![After](https://user-images.githubusercontent.com/82778925/123495168-297b2f80-d5e8-11eb-8381-0ec186c31abc.png)
Forge version: 36.1.32
Astral version: 1.16-1.16.5-1.13.12
Other mods: JEI (and Astral's dependencies)
Steps to reproduce: Craft any item in an Astral altar that uses a bucket of Liquid Starlight in the recipe - it is not consumed

**Comment by MuteTiefling** [comment]
To add to this, I'm sure it's no surprise but it's also not working with other fluids in custom recipes. The recipe still uses the `type: 'astralsorcery:fluid'` construct with other fluids, but it's not consuming the fluid.
