### ISSUE TITLE
Attunement Altar works with only the altar itself having sky access

### ISSUE THREAD

**Issue by PocketfulOfGeese** [HellFirePvP/AstralSorcery#1849]
Attunement Altar will build the multiblock and successfully attune when only the Altar itself has sky visibility.

Tested with:
MC 1.16.5
Forge 36.1.32
AS 1.13.12
Curios 4.0.5.2
Observerlib 1.5.3

**Comment by yavincl** [comment]
Is checking if every sooty marble has sky visilibily performance intensive? That said it did matter back in 1.12.2

**Comment by HellFirePvP** [comment]
This was a thing in 1.12, i've changed it for 1.15+ to only check this for the altar itself.
While it's not ideal, it is what it is now. Am gonna leave it like that for now tbh.
