### ISSUE TITLE
Starlight Infuser dont work 1.16

### ISSUE THREAD

**Issue by Haihatsu** [HellFirePvP/AstralSorcery#1850]
Hello

Google Translate:

I play a modpack on Direwolf20 1.10.1 for the minecraft version 1.16,

i play astral sorcery since release and its my favourite mod :)

I built the starlight infuser correctly but if i right click on my resonating wand to the starlight infuser, nothing happens...

does anyone have the same problem?

greetings

**Comment by PocketfulOfGeese** [comment]
That is not a common problem, no. I would recommend coming to the Discord server for assistance.
