### ISSUE TITLE
Russification for astralsorcery-1.16-1.16.5-1.13.12

### ISSUE THREAD

**Issue by FaradeyYF** [HellFirePvP/AstralSorcery#1853]
Hi! I have completely translated the mod into Russian. Perhaps there may be mistakes in some moments, but mostly this will not interfere with the game in any way!
It would be great to insert it into the game waiting for Russian-speaking players!
![2021-07-03_21 14 46](https://user-images.githubusercontent.com/86890588/124363465-084bbc00-dc44-11eb-8004-832b31e9663c.png)
![2021-07-03_21 14 59](https://user-images.githubusercontent.com/86890588/124363467-097ce900-dc44-11eb-903a-7f1d56492240.png)
![2021-07-03_21 15 07](https://user-images.githubusercontent.com/86890588/124363468-0b46ac80-dc44-11eb-806a-1f24bbd9af4d.png)
![2021-07-03_21 15 53](https://user-images.githubusercontent.com/86890588/124363471-0c77d980-dc44-11eb-8593-8e1e64b8795f.png)

And here is the file itself!
[ru_ru.zip](https://github.com/HellFirePvP/AstralSorcery/files/6758860/ru_ru.zip)

**Comment by PocketfulOfGeese** [comment]
Should submit it as a PR in full format.

**Comment by Xomep** [comment]
where should it be placed?

**Comment by xukywka** [comment]
you can read more about the installation?

**Comment by shikhtv** [comment]
omg, another translation :) when will the author pay attention already?

**Comment by JustNikoth** [comment]
Надо открыть astralsorcery-1.16-1.16.5-1.13.12.jar как архив далее assets\astralsorcery\lang и закинуть туда .json

**Comment by HellFirePvP** [comment]
Pardon me, i was very busy with other things and couldn't dedicate time to this. I have merged the PR. :)
