### ISSUE TITLE
Using Quark's Bottled Cloud to place a Collector Crystal renders the crystal non-functional.

### ISSUE THREAD

**Issue by Crioca** [HellFirePvP/AstralSorcery#1854]
Description: When using a Bottled Cloud to place a Collector Crystal, the crystal becomes unmineable and cannot be used as part of a collector enhancer structure. I was able to mine the crystal via the Veinmining enchant but the crystal that I picked up no longer had any attributes or attunement.

To reproduce:
1. Use the Bottled Cloud from Quark to place down a Cloud block.
2. Place a Celestial Collector Crystal by right clicking against the Cloud block with the crystal in hand.
3. Try to mine the crystal or use it as part of an enhanced collector structure
4. Place a second Collector Crystal (the normal way) next to the glitched one, mine the second crystal using a tool with Veinmining, the first crystal should be mined but have no stats.

astralsorcery-1.16-1.16.5-1.13.12
Quark-r2.4-312

**Comment by PocketfulOfGeese** [comment]
What are the stats of the crystal once placed?

**Comment by Crioca** [comment]
No stats as far as I can tell

https://i.imgur.com/aN48IhX.png

**Comment by PocketfulOfGeese** [comment]
Yup, NBT isn't being preserved. Issue on quark's side for that.
