### ISSUE TITLE
Command unlocks for intermediary progress updates do not work.

### ISSUE THREAD

**Issue by half-nothing** [HellFirePvP/AstralSorcery#1855]
I use the command (/astralsorcery progress Half_nothing BASIC_CRAFT) to give me progress.But I see nothing happened.When I try to use the command again,it says that I have already get it.The picture is here.
![NZGMR(LLA4}~0L1MJR5L$FR](https://user-images.githubusercontent.com/50048293/125155286-4d667580-e191-11eb-92a6-c8d7521ecc8e.png)
![LIFJRNV4C$W $AFV5D_X%@T](https://user-images.githubusercontent.com/50048293/125155288-50f9fc80-e191-11eb-9ef6-c67cf60c66b5.png)
By the way,I use the crafttweaker to change the recipe of Luminous crafting table.Maybe this problem is possible caused by it?
My minecraft game version is 1.16.5 with forge 36.1.25.Java 1.8.0.291 64bit with 4GB RAM.

**Comment by HellFirePvP** [comment]
This has to do with you having the progression-stage but not the research-stage required.
Unfortunately the research command didn't make it into 1.16, so i'll sync the progress to automatically grant the required research alongside it.
