### ISSUE TITLE
[1.16.5] Scorching heat is turning stone and cobble to smooth stone

### ISSUE THREAD

**Issue by theboo** [HellFirePvP/AstralSorcery#1856]
in AstralSorcery-1.16.5-1.13.12 scorching heat seems to be turning stone and cobble to smooth stone rather than just stone.

I would think the dropped cobble from mining stone and from mining cobblestone should both result in regular stone.

**Comment by PocketfulOfGeese** [comment]
can you provide an image to explain?

**Comment by theboo** [comment]
ill make a gif one sec

**Comment by theboo** [comment]
turns out im an idiot and i had another mod's autosmelt activated at the same time so it was getting double smelted xD closing now lmao 

scorching heat is working as intended on stone/cobble
