### ISSUE TITLE
Enabling skyRenderingConstellations by itself does not work

### ISSUE THREAD

**Issue by Dejeh** [HellFirePvP/AstralSorcery#1857]
AstralSorcery-1.16.5-1.13.12
Enabling this by itself doesn't show constellations (with or without shaders) and enabling both skyRenderingConstellations and skyRenderingEnabled creates its own skybox (that overlaps shader skybox). I'm sure the second is known already but why can't the first option work by its lonesome?

**Comment by PocketfulOfGeese** [comment]
I don't understand what you're saying. By default the options are:
```
	skyRenderingConstellations = []
	skyRenderingEnabled = ["minecraft:overworld"]
```

Is the question why can't you enable a separate on-top render of constellations when you're not rendering constellations? Without "skyRenderingEnabled" you wouldn't have anything to put into that separate on-top render. It would be an empty render.

**Comment by Dejeh** [comment]
I see, my bad. I was probably thinking too linear here but I assumed when it meant "will only render constellations on top of the existing skybox" that it would be able to render it on top of shaders. From the handful of shaders I've tested, it isn't.. super effective. There always seems to be a line in the lower portion of the sky when sky rendering + constellations is enabled. I'm guessing there's not much that can be done about that though.
