### ISSUE TITLE
Linking Collector Crystal causes server crash

### ISSUE THREAD

**Issue by GloriousMadness** [HellFirePvP/AstralSorcery#1859]
Using astralsorcery-1.16-1.16.5-1.13.12.jar and trying to link the Collector Crystal in the image to the Crystal Lens causes a server crash. Server crash log.txt attached.
(If it matters; Collector crystal is made from Purity II and Shape III Armara Attuned Rock Crystal)
![image](https://user-images.githubusercontent.com/37433284/125652550-f5dbf926-88f4-441e-b3a6-1f882c9e79e0.png)
[crash-2021-07-14_17.34.20-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/6817380/crash-2021-07-14_17.34.20-server.txt)

**Comment by PocketfulOfGeese** [comment]
Your lenses have broken attributes, however you created/duplicated them stripped out parts of the NBT and made them nonfunctional.

Which doesn't matter because starlight through lenses and prisms is broken in your version, gotta direct link only until patched.

**Comment by GloriousMadness** [comment]
*Facepalm* Yeah the moment you mentioned broken attributes I could only think of one thing that broke the lenses. Used Building Gadget's copy thing to copy over a structure with everything placed on it. Seems to have wiped out the attributes of the lenses.
Thanks for the quick response!
