### ISSUE TITLE
{1.16.5} No Crafting Table Conversion

### ISSUE THREAD

**Issue by Hephsmith** [HellFirePvP/AstralSorcery#1860]
I've left my crafting table in the shrine with the crystal shining on it for 3 in-game days, and it didn't change. I even made sure that the crystal had a view of the sky (I broke down the central column and replaced the lantern with glass). Is there something I'm missing?

**Comment by xaelith** [comment]
I usually clear out a 3x3 with the crystal in the center, making sure to get rid of the water that was in the fountain above, and any light globs added by various mods. With this, the crafting table turns to a luminous table in seconds.

If this is how yours is set up and it still doesn't work, my next guess would be some sort of mod interaction and/or change in the configs is preventing the alteration.

**Comment by PocketfulOfGeese** [comment]
Confirmed through discord there was a block obstruction involved.
