### ISSUE TITLE
[1.16.5] Changing the max perk level doesn't affect the advancement

### ISSUE THREAD

**Issue by Weedoof** [HellFirePvP/AstralSorcery#1862]
As the title. If you change your max level in the config, the "It all looks so different on this side" (develop your personal starlight to maximum level) advancement is still unlocked at level 40, as if it hadn't been changed.
XP gain and all other features relating to perks still work as normal. Only the advancement is unaffected.

Minor bug, but still worth mentioning.

Using the latest version of forge & astral sorcery at the time of writing - Forge ver. 36.1.63 and Astral ver. 1.13.12

**Comment by HellFirePvP** [comment]
If you want the advancements to adjust, you can create a datapack changing them. This is out of scope for the mod to dynamically adjust.
