### ISSUE TITLE
Crash with latest forge version?

### ISSUE THREAD

**Issue by shBLOCK** [HellFirePvP/AstralSorcery#1863]
When use this mod with forge version >= 36.1.59, it crash when loading (mixin problem)
It crash when the game is in a very early stage, so there's no proper crash log.

**Comment by PocketfulOfGeese** [comment]
36.1.59 isn't latest forge, and also it's an invalid version:
![image](https://user-images.githubusercontent.com/12677933/126078446-09a56867-1f85-42dd-ba49-e56c9127a4db.png)

Update to an available version of forge, not an AS issue.

**Comment by shBLOCK** [comment]
Oh sorry, I think that was another mod's problem, it just said astral's mixin in the log, when I test it in a single-mod environment, it doesn't cause problem.
