### ISSUE TITLE
Sun following mouse

### ISSUE THREAD

**Issue by SilverInfinite** [HellFirePvP/AstralSorcery#1866]
I dont know why, but when im installing Astral Sorcery(minecraft forge 1.16.5) sun start following my mouse. And when im look down:s tarting night by light(tourches flashing like in night), but not as time, same is sun up

**Comment by PocketfulOfGeese** [comment]
That's not an AS issue, sounds like you've got conflicting shaders, Optifine doing something weird, or something else impacting it that isn't AS.
