### ISSUE TITLE
Enchantment Hooks causing TPS issues - 1.13.12 - All the Mods 6

### ISSUE THREAD

**Issue by Column01** [HellFirePvP/AstralSorcery#1868]
When running the ATM6 modpack (version 1.7.2), astral sorcery seems to be lagging the server with enchantment hooks. This was apparently fixed in version `1.13.11` (see #1751) but ATM6 is currently running version `1.13.12` and this is still present.

You can see the profile [here](https://spark.lucko.me/Xy16zDUYVg) (tombstone also lags with the shadow step enchant, but Astral has been the biggest offender.)

Mod Version: 1.13.12
Forge version: 36.1.65

**Comment by Column01** [comment]
Oh, looking at the profile again, the tombstone lag has the majority of it coming from astral's enchantment lookups

**Comment by PocketfulOfGeese** [comment]
How long was this run for?

Also I don't see Astral anywhere near the top offenders here:
![image](https://user-images.githubusercontent.com/12677933/126883891-b875afb7-203a-4fcd-a7c6-0ef8ffc0c04a.png)

**Comment by Column01** [comment]
15 seconds, and you should click this button to view by the source and astral is number one on that: 
![image](https://user-images.githubusercontent.com/26526649/126883943-d2a7b2df-d978-41ff-b7f7-e83f48d81073.png)

**Comment by Column01** [comment]
1.3 seconds was eaten by astral, and the 1.3 under tombstone was again majority astral sorcery enchantment hooks

**Comment by PocketfulOfGeese** [comment]
How. long. was. the. test. run. for?

Because, again, looking at the entire server thread output I screenshot above, astral, like most of those mods listed during the profile, had a neglible impact on overall server hit. The sources list doesn't even list non-modded code. Listening for event triggers is EXACTLY what event listeners are for.

1.3 seconds is irrelevant unless the entire thing was captured for a matter of seconds. In which case, gather one that runs for several minutes instead and upload it. Every time someone posts one of these since that issue was fixed, it's been shown to be irrelevant.

**Comment by Column01** [comment]
15. Seconds. I. Said. That. Already

**Comment by PocketfulOfGeese** [comment]
Run it for five minutes. Post it again. Get data that's relevant over a timespan that matters, while the server is actually doing something.

And, again, what's the overall server CPU load while this is going on? Is anyone playing? Is it just running blank? Context matters.

**Comment by Column01** [comment]
CPU load is negligible (5%), but TPS is shattered. Memory usage is also low, 33% of allocated and there are 5 playters currently playing. The profiler used is called Spark ([rtfm](https://spark.lucko.me/docs/Using-the-viewer)), and you don't need to run a 5 minute profile to get a good idea of what's causing lag. The MS counters (and the corresponding percent value) next to the sources show how much of the total tick time was eaten by that given source, and out of 15 seconds of tick time, astral ate 1.3 seconds of it doing its enchantment lookups.

I will however oblige you and run a 5 minute profile and post it when it completes

**Comment by PocketfulOfGeese** [comment]
If TPS is low but your CPU load on the core running MC is also low, that's not Astral.

**Comment by Column01** [comment]
It's a combination of things causing the lag, but astral being in the top 3 doing arguably simple tasks is not good. Mekanism (the main source of tech in this pack) is using less of the tick time than astral is. Again, I will update when the profile completes.

![image](https://user-images.githubusercontent.com/26526649/126884212-98906e3e-5e65-484b-84ee-5f1084e9e56d.png)

**Comment by Column01** [comment]
Here's a better view of resource usage:
![image](https://user-images.githubusercontent.com/26526649/126884230-e4fa7014-ef81-4e3e-820f-066c39508b88.png)

**Comment by Column01** [comment]
New 5 minute long profile: https://spark.lucko.me/Vi6268vbm3

**Comment by PocketfulOfGeese** [comment]
Same thing as before: when you look at non-mod entries only (that Source filter) it's not a mod at all causing these issues.

89% of the server thread is occupied with server world tick ops. 63% is entity updates. 28% is mob entity ticking.

9% are zombies alone. Fish are another 6%.

![image](https://user-images.githubusercontent.com/12677933/126884292-c03c6c38-5276-43dd-bd45-c9a5db0c7120.png)

**Comment by Column01** [comment]
Alright, but if that were the case, why does killing all zombies, fish etc. not improve TPS at all? This entire time it's been lagging I've been purging entities and it doesn't improve TPS at all. I assumed the enchants were held by a mob since my players all swear they aren't using any enchants from astral or the tombstone mod (shadowstep)

**Comment by Column01** [comment]
I purged pretty much all mobs within the last 3 mins, this is the result: 
![image](https://user-images.githubusercontent.com/26526649/126884335-3d41681b-b4e9-4ff4-8245-c8f05bc3e915.png)

**Comment by PocketfulOfGeese** [comment]
the event bus being monitored by both mods is irrelevant at the end of the day, honestly. I wouldn't even bother reporting this to Tombstone either.

And I don't know why purging doesn't change things, because it doesn't change that's what's eating server threading.

I suspect that CPU load is aggregate across all cores, and the core running the server instance is probably pegged out.

**Comment by Column01** [comment]
Alright, I'm running a profile for 300 seconds on peaceful so we should only have to deal with a fraction of the mobs. Also, CPU usage is nowhere near being "pegged"
![img](https://i.imgur.com/zVgNl7u.png)

**Comment by PocketfulOfGeese** [comment]
Then that makes it even worse.

Something is limiting the MC server thread. It's not Astral that is causing problems.

**Comment by Column01** [comment]
What could possibly be limiting the MC server thread? We had this issue on Java 8 and recently updated to Java 11 and still have this problem. I can send you the JVM args if you want if you think that would help

**Comment by Column01** [comment]
New 5 minute profile on peaceful: https://spark.lucko.me/x6l65ooep6
We gained ~2 tps from being on peaceful
![image](https://user-images.githubusercontent.com/26526649/126884503-4dba8f51-42c4-4a9f-a5b6-f9316381c99c.png)

**Comment by Jeuvke** [comment]
97.2 MSPT minimum in the last minute but only 5% CPU load? I doubt you're using a 20+ core system, so something must be limiting the server's CPU usage.

**Comment by Column01** [comment]
> 97.2 MSPT minimum in the last minute but only 5% CPU load? I doubt you're using a 20+ core system, so something must be limiting the server's CPU usage.

The server has 24 threads I believe, no idea what would limit the CPU usage, any ideas?

![img](https://i.imgur.com/3qycRIr.png)

**Comment by Column01** [comment]
Astral _is_ contributing to the lag, but after some extensive goofing it seems to be mobs are spawning with enchantments ALOT and causing lag. Does anyone have recommendations for reducing mob spawns (I.E. setting spawn limits?)

**Comment by PocketfulOfGeese** [comment]
InControl would be the mod for that, iirc.
