### ISSUE TITLE
[1.12.2] Can't discover dim constellations

### ISSUE THREAD

**Issue by TwistedGlass2** [HellFirePvP/AstralSorcery#1869]
As the title says I've attuned to the Discidia constellation and I still haven't been able to discover the dim constellations. I'm not sure if it's a bug or some other mod is interfering.
![2021-07-28_00 26 24](https://user-images.githubusercontent.com/88072160/127264110-5d935bb8-8d03-47ee-b768-3491aa14c56e.png)
The dim constellation Octans outlined
![2021-07-28_00 23 06](https://user-images.githubusercontent.com/88072160/127264111-511be6a1-0fe9-4782-817f-5a2f6bd7bb1b.png)
Proof that I've been attuned

**Comment by Jeuvke** [comment]
Do you have the constellation papers for those constellations?

**Comment by PocketfulOfGeese** [comment]
You can't discover constellations you don't have a paper for, even though the telescope and observatory will show them.
