### ISSUE TITLE
Infused Sword activating on right click

### ISSUE THREAD

**Issue by murapix** [HellFirePvP/AstralSorcery#187]
The Infused Crystal Sword is activating whenever I right click things like chests or hoppers, instead of only when I swing with it. This doesn't happen when I right click on normal blocks, only interactable blocks, and has caused the unfortunate deaths of any who have been nearby, including my poor cat.

I haven't tested with the other infused tools, due to a lack of rock crystals to make them with, but I wouldn't be surprised if it happened with them too.

**Comment by HellFirePvP** [comment]
it's been changed in-dev to conform the more-common usecase instead of the previous effect. so that'll change next version.
