### ISSUE TITLE
Cannot progress to attunement.

### ISSUE THREAD

**Issue by ZroNoh** [HellFirePvP/AstralSorcery#1871]
The crafting table transformation just hangs, it doesn't do anything even after waited several in-game days. There are no obstructions what so ever.
![java_Y1MLFeg3QK](https://user-images.githubusercontent.com/32776743/128399085-b26f19d8-67c4-4629-9bb8-b767e85f745e.png)

Trying to manually force a player to progress fails
![java_bOtttoGvYh](https://user-images.githubusercontent.com/32776743/128399193-90e8bc49-b060-44df-8457-4c0eb94724d4.png)

**Comment by PocketfulOfGeese** [comment]
Need to find another shrine, that crystal isn't properly generated. Old known issue that doesn't yet have a fix.

Command issue is known as well: #1855

**Comment by ZroNoh** [comment]
What about the fact that I cannot even use the command to progress
