### ISSUE TITLE
Cannot undergo personal attunement; details in text

### ISSUE THREAD

**Issue by AzazelWormwood** [HellFirePvP/AstralSorcery#1872]
Astral sorcery 1.16.5 personal attunement issue

My attunement altar is set up perfectly well to attune to Discidia, and I’ve already attuned crystals with it so I know it works. But when I try to attune myself it goes into the cinematic but begins glitching between first and third person repeatedly and never completes the attunement. Tried disabling controls so I couldn’t sneak but the issue persisted.

**Comment by PocketfulOfGeese** [comment]
Some other mod is conflicting with camera controls, then. Full mod list? Is there something like sponge involved?

**Comment by AzazelWormwood** [comment]
Agricraft
AstikorCarts
Astral Sorcery
Better Animals Plus
Blood Magic
Chisels and Bits
Citadel
ConnectedTexturesMod
Curios API
Forge
Garden Tools
Ice and Fire
Immersive Engineering
InfinityLib
Iron Age Furniture
Just Enough Items
Macaw’s Furniture
Mantle
Mine Factory
MrCrayfish’s Furniture Mod
Mystical World
ObserverLib
Pam’s HarvestCraft 2 Crops
Pam’s HarvestCraft 2 Food Core
Pam’s HarvestCraft 2 Food Extended
Pam’s HarvestCraft 2 Fruit Trees
Patchouli 
Simple Farming
Simple Tombstone
Sophisticated Backpacks
Statues Mod
The Twilight Forest
The Undergarden
Tinkers Construct

**Comment by AzazelWormwood** [comment]
Mine factory and connected textures have been removed; did not solve the issue

**Comment by AzazelWormwood** [comment]
This is what this looks like on my end
https://user-images.githubusercontent.com/88508861/128571092-b4d0d3d2-9cb0-48c5-82f1-febce95ace25.MOV

**Comment by PocketfulOfGeese** [comment]
What version of Forge?

Is this single-player, or on a server? Any plugins involved?

Does it happen with only AS and its required dependencies? Having trouble recreating this with only AS.

**Comment by AzazelWormwood** [comment]
Forge version: 36.2.2

This is a server; this happens whether or not other people are logged on. Aternos hosting.

Not sure what you mean by plugins, I’m pretty new to modded MC. The mod list is above.

I have no idea if it happens with only AS. It it possible to launch a creative single player with only AS enabled? If so I could test it.

**Comment by PocketfulOfGeese** [comment]
Looks like they allow plugins, need to talk to them about disabling Sponge/whatever their plug-in tool is for the server, or editing the config to not override camera controls, it's conflicting. It's also a super old interaction.

**Comment by AzazelWormwood** [comment]
Problem resolved; agricraft was somehow causing an issue with the cinematic. Removed agricraft and works as intended.
