### ISSUE TITLE
Unable to attune mantle of stars

### ISSUE THREAD

**Issue by AzazelWormwood** [HellFirePvP/AstralSorcery#1873]
I cannot craft the attuned mantle of stars. Recipe is correct; I have tried multiple times. I have all the required starlight and items (pic without enough light is near the end of the night). I tried a fix from some time ago where you could equip and unequip the mantle but it didn’t solve the issue. I have tried it with the mantle enchanted and unenchanted. Full mod list:

Agricraft
AstikorCarts
Astral Sorcery
Better Animals Plus
Blood Magic
Chisels and Bits
Citadel
Curios API
Forge
Garden Tools
Ice and Fire
Immersive Engineering
InfinityLib
Iron Age Furniture
Just Enough Items
Macaw’s Furniture
Mantle
MrCrayfish’s Furniture Mod
Mystical World
ObserverLib
Pam’s HarvestCraft 2 Crops
Pam’s HarvestCraft 2 Food Core
Pam’s HarvestCraft 2 Food Extended
Pam’s HarvestCraft 2 Fruit Trees
Patchouli
Simple Farming
Simple Tombstone
Sophisticated Backpacks
Statues Mod
The Twilight Forest
The Undergarden
Tinkers Construct

![image](https://user-images.githubusercontent.com/88508861/128569660-d0e388ab-fedd-4b51-8b59-a446ed6241f8.jpg)
![image](https://user-images.githubusercontent.com/88508861/128569673-40d4651c-e6d8-4914-9ed9-4dad90cf20e5.jpg)

**Comment by PocketfulOfGeese** [comment]
Does it start the process with making the noise, but never completes? If so, remove the items from the relays until a relay asks for the item by displaying a ghost image of the item.

**Comment by AzazelWormwood** [comment]
It never starts the process. The image of the attuned mantle doesn’t appear in the altar with it without the items in the relays

edit: with *or without

**Comment by PocketfulOfGeese** [comment]
that's...not normal. The relays have no impact on whether it considers the item craftable. Might be best to come to the discord for live troubleshooting on what's wrong.

**Comment by AzazelWormwood** [comment]
A discord would be great. Where can I find the link?

**Comment by PocketfulOfGeese** [comment]
Curse page, or the main code page of this github.

**Comment by AzazelWormwood** [comment]
Issue resolved—the amount of starlight showed as enough but it was not; adding a relay fixed it.
