### ISSUE TITLE
Setting focus on Crystal Prism from Celestial crystal crashes client/server

### ISSUE THREAD

**Issue by ct-klein** [HellFirePvP/AstralSorcery#1874]
Modpack version
Enigmatica6-0.5.9

Mod version: astralsorcery-1.16-1.16.5-1.13.12.jar

Describe the bug
Added a large builders gadgets Astral Sorcery area. Added an attuned celestial crystal (Vicio) to a pillar and used the linking tool to set focus to a crystal prism (that was placed by builders gadget). Client crashed and the server as well.
Rid restarted the server and after some conversation, I broke the crystal and the prism and replaced (thinking building gadgets placed it 'bad'), and the same crash occurred.

I can duplicate the issue locally, placing the same build paste but if I do it 'manually', just put down a celestial crystal and a prism and link the two it works fine. Maybe it is something related to builders gadgets, but thought breaking/replacing the items would resolve.

Logs
https://pastebin.com/zAbE6LR9

Screenshots
https://imgur.com/h1OtAfo

Also reported on Enigmatica site https://github.com/NillerMedDild/Enigmatica6/issues/2912

**Comment by PocketfulOfGeese** [comment]
Builder's Gadgets doesn't maintain the NBT on the prism or lenses, which causes the break. Known and old issue.
