### ISSUE TITLE
Changing horologium ritual config causes crash

### ISSUE THREAD

**Issue by Cratermn** [HellFirePvP/AstralSorcery#1875]
Increasing horologium ritual blocks affected and range causes any clients that go near it to lag freeze and crash and become unable to rejoin. The larger the increase the more severe it becomes. Decreasing the effect did not fix the issue. Attempt to move the ritual caused server hang and crash. Occurs on all the mods 6 pack with various plants and machines nearby. Server rollback or ritual disabling in config was the only solution I found.

**Comment by PocketfulOfGeese** [comment]
Gather a 5 minute Sampler output when the issue is occurring.

**Comment by PocketfulOfGeese** [comment]
@Cratermn any update for the requested sampler? not able to reproduce using latest mc 1.16.5 release, so would need more information as previously requested.
