### ISSUE TITLE
What Does Rampage from Alcara do?

### ISSUE THREAD

**Issue by 2468cool** [HellFirePvP/AstralSorcery#1877]
I'm working with the stellar refraction table and saw that alcara puts rampage on armor. What does rampage do for the player?

**Comment by PocketfulOfGeese** [comment]
Provides speed ,strength, and haste.

**Comment by 2468cool** [comment]
Does rampage happen automatically or is there a way to activate it?

**Comment by PocketfulOfGeese** [comment]
Chance to gain when killing a mob. There's perks that improve duration and chance.
