### ISSUE TITLE
Armor Durability drained extremely fast

### ISSUE THREAD

**Issue by Ultimushadow** [HellFirePvP/AstralSorcery#1878]
While experimenting in a personal modpack, a friend and I were messing around with perk builds. Namely, I was focusing on armor and he on attack, this includes using the Curios mod to affect stats. While my armor was very high, and his attack was also very high, it quickly became apparent that my armor was taking upwards of 15 durability on a hit, this includes both vanilla and modded armor and weapons. Now I'm not entirely convinced this is AS's fault, but, the added armor values though the perk tree seem to increase the amount of durability armor uses, as I also tested getting hit by iron golems and such which also took a lot of durability. Also, I had Unbreaking 6 on my armor during initial tests due to the Resplendent Prism and the AS enchanting system, and it did pretty much nothing from what I could tell. 

Pack here:
[Generic Modpack Name.zip](https://github.com/HellFirePvP/AstralSorcery/files/7004331/Generic.Modpack.Name.zip)
Max Armor build: https://tinyurl.com/yen8wsur
Melee Damage test: https://tinyurl.com/yjpdggbu

**Comment by PocketfulOfGeese** [comment]
Bleed can do that, due to the many constant ticks of small damage, and the way vanilla handles armor durability. If it's happening outside of a bleed proc, it's not AS.

https://minecraft.fandom.com/wiki/Armor#Durability

**Comment by Ultimushadow** [comment]
Looking back through all the perks, it looks like a combination of bleed and the Body Blocking perk is to blame. Although the Body Blocking perk seems useful, it looks like it ultimately diminishes the value of wearing any armor in the first place, might make a suggestion to alter that slightly because taking upwards of 20 durability per hit kinda defeats the purpose of Armara. This isn't just the bleed effect however, iron golems and even just zombies can do multiple durability per hit with this perk. It's basically just shooting yourself in the foot.
