### ISSUE TITLE
Failed to start 1.16.4

### ISSUE THREAD

**Issue by kingOlegos** [HellFirePvP/AstralSorcery#1879]
Received error code "java.lang.noclassdeffounderror". Am I using a wrong version of something or is it a bug in the mod? Thanks for the help!

**Comment by PocketfulOfGeese** [comment]
Likely means you're running an incorrect version of java. It's asking for something in Java that's not present.

**Comment by kingOlegos** [comment]
Just updated Java. Still getting error :0
[crash-2021-08-19_01.17.17-fml.txt](https://github.com/HellFirePvP/AstralSorcery/files/7012857/crash-2021-08-19_01.17.17-fml.txt)

**Comment by PocketfulOfGeese** [comment]
Your launcher is still using java 8 u51. Need to update the config to not use the pre-packaged version it comes with. Please reference your launcher documentation for that.

**Comment by kingOlegos** [comment]
Updated java and used that and got: "java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError:"

**Comment by PocketfulOfGeese** [comment]
Log. Last time you said that the log showed the launcher was still using the old version. Log will confirm the version involved.

**Comment by kingOlegos** [comment]
[crash-2021-08-20_00.07.26-fml.txt](https://github.com/HellFirePvP/AstralSorcery/files/7023360/crash-2021-08-20_00.07.26-fml.txt)

**Comment by kingOlegos** [comment]
Java Version: 1.8.0_301

**Comment by PocketfulOfGeese** [comment]
Different error! Good!

Use a forge version for 1.16.5 please. Preferably latest.

**Comment by kingOlegos** [comment]
IT WORKED! Thanks Doomgull!
