### ISSUE TITLE
Attunement Altar Plz help.

### ISSUE THREAD

**Issue by Jubithaous** [HellFirePvP/AstralSorcery#188]
I have been really enjoying this mod but I dont know if I just didnt make progress or anything but, I have reconstructed the Attunement Altar more times and a day and cant progress further. Is there anyway that i can see a better example of one thats not in the journal? I dont know if I have to place it on flat land, high land or near a stardust field. I tested spots that was clear and still not getting the glowy sparkle effects that its working.

**Comment by HellFirePvP** [comment]
If you've built the structure and placed down the altar in the center and it doesn't show the sparkles around it, you've built it wrong or the altar has no line of sight to the sky.

verify that you've built it correctly.

**Comment by Jubithaous** [comment]
Ok. I rebuilt it again and i finally gotten it to work but now i ran into a new problem. The game keeps crashing and everytime i try to get back into my game im stuck at the altar getting attuned but it keeps crashing the game.

**Comment by Doomgull** [comment]
Crash log on pastebin, copy link here
