### ISSUE TITLE
Minecraft crash ticking entity 1.12.2

### ISSUE THREAD

**Issue by Alexor3** [HellFirePvP/AstralSorcery#1880]
Whenever I try to enter a friend's world in lan, it crashes and says 
"The game crashed whilst ticking entity
Error: java.util.concurrent.RejectedExecutionException: event executor terminated
Código de error: -1"

Here is the crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.151.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  weaponlib (mw_2.0-0.4.6.2_mc1.12.2.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_21.14.1_Forge_1.12.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 8/18/21 10:40 PM
Description: Ticking entity

java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:821)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:327)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:320)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:746)
	at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:236)
	at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java:168)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147297_a(NetHandlerPlayClient.java:805)
	at net.minecraft.client.entity.EntityPlayerSP.func_175161_p(EntityPlayerSP.java:258)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:196)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:821)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:327)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:320)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:746)
	at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:236)
	at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java:168)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147297_a(NetHandlerPlayClient.java:805)
	at net.minecraft.client.entity.EntityPlayerSP.func_175161_p(EntityPlayerSP.java:258)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:196)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 83858
	Entity Name: Alexor2
	Entity's Exact location: 199.83, 11.00, 3274.33
	Entity's Block location: World: (199,11,3274), Chunk: (at 7,0,10 in 12,204; contains blocks 192,0,3264 to 207,255,3279), Region: (0,6; contains chunks 0,192 to 31,223, blocks 0,0,3072 to 511,255,3583)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Alexor2'/83858, l='MpServer', x=199.83, y=11.00, z=3274.33]]
	Chunk stats: MultiplayerChunkCache: 251, 251
	Level seed: 0
	Level generator: ID 07 - climatic_real, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (54,64,259), Chunk: (at 6,4,3 in 3,16; contains blocks 48,0,256 to 63,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1116025 game time, 1308633 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 31 total; [EntityPlayerSP['Alexor2'/83858, l='MpServer', x=199.83, y=11.00, z=3274.33], EntityCreeper['Creeper'/84032, l='MpServer', x=131.50, y=14.00, z=3204.50], DinosaurEntity{ jurassicraft:velociraptor, id=83843, remote=true, isDead=false, isCarcass=false, isSleeping=false, stayAwakeTime=0
    , dinosaurAge=143487, prevAge=143487, maxAge135000, ticksExisted=21, entityAge=0, isMale=true, growthSpeedOffset=0
    , food=84000 / 84000 (73500.0), water=84000 / 84000 (73500.0), digestingFood=0 / 3000, health=33.26859 / 35.0
    , pos=BlockPos{x=120, y=62, z=3245}, eyePos=(120.70177759556246, 64.1497296070681, 3247.259371958608), eyeHeight=1.4199915, lookX=0.0, lookY=0.0, lookZ=0.0
    , width=0.8352891, bb=box[120.03108590841293, 62.458414713541664, 3245.135822236538 -> 120.86637502908707, 63.96193508307139, 3245.971111357212] }, DinosaurEntity{ jurassicraft:triceratops, id=83929, remote=true, isDead=false, isCarcass=false, isSleeping=false, stayAwakeTime=0
    , dinosaurAge=141813, prevAge=141813, maxAge135000, ticksExisted=21, entityAge=0, isMale=true, growthSpeedOffset=0
    , food=168000 / 168000 (147000.0), water=168000 / 168000 (147000.0), digestingFood=0 / 3000, health=75.62541 / 70.0
    , pos=BlockPos{x=210, y=89, z=3209}, eyePos=(212.7938845499345, 91.13463878804734, 3207.9382201317667), eyeHeight=1.7308651, lookX=0.0, lookY=0.0, lookZ=0.0
    , width=2.4039795, bb=box[210.2980102300644, 89.0, 3208.770108764603 -> 211.2980102300644, 90.0, 3209.770108764603] }, EntityWolf['Lobo'/84125, l='MpServer', x=239.50, y=82.00, z=3204.50], EntityWolf['Lobo'/84124, l='MpServer', x=236.50, y=83.00, z=3204.50], DinosaurEntity{ jurassicraft:triceratops, id=84063, remote=true, isDead=false, isCarcass=false, isSleeping=false, stayAwakeTime=0
    , dinosaurAge=143639, prevAge=143639, maxAge135000, ticksExisted=11, entityAge=0, isMale=true, growthSpeedOffset=0
    , food=168000 / 168000 (147000.0), water=168000 / 168000 (147000.0), digestingFood=0 / 3000, health=78.70828 / 78.70828
    , pos=BlockPos{x=126, y=72, z=3349}, eyePos=(126.56889905291017, 74.13463878804734, 3351.4254909152323), eyeHeight=1.5848945, lookX=0.0, lookY=0.0, lookZ=0.0
    , width=2.2012424, bb=box[125.89380292405579, 72.0, 3348.532421134249 -> 128.0950453709552, 74.6414909362793, 3350.7336635811484] }, EntityWolf['Lobo'/84126, l='MpServer', x=240.26, y=82.00, z=3197.51], EntityWolf['Lobo'/84065, l='MpServer', x=143.74, y=76.00, z=3319.45], EntityWolf['Lobo'/84064, l='MpServer', x=120.47, y=74.00, z=3335.44], DinosaurEntity{ jurassicraft:velociraptor, id=84067, remote=true, isDead=false, isCarcass=false, isSleeping=false, stayAwakeTime=0
    , dinosaurAge=143488, prevAge=143488, maxAge135000, ticksExisted=11, entityAge=0, isMale=false, growthSpeedOffset=0
    , food=84000 / 84000 (73500.0), water=84000 / 84000 (73500.0), digestingFood=0 / 3000, health=28.410652 / 28.410654
    , pos=BlockPos{x=116, y=62, z=3248}, eyePos=(118.10292876134332, 64.00357075290144, 3249.3679159748895), eyeHeight=1.5653048, lookX=0.0, lookY=0.0, lookZ=0.0
    , width=0.9207675, bb=box[116.10211625695229, 62.312255859375, 3248.1321455538273 -> 117.02288374304771, 63.96963727474213, 3249.0529130399227] }, DinosaurEntity{ jurassicraft:velociraptor, id=84066, remote=true, isDead=false, isCarcass=false, isSleeping=false, stayAwakeTime=0
    , dinosaurAge=143488, prevAge=143488, maxAge135000, ticksExisted=11, entityAge=0, isMale=true, growthSpeedOffset=0
    , food=84000 / 84000 (73500.0), water=84000 / 84000 (73500.0), digestingFood=0 / 3000, health=35.330246 / 41.330246
    , pos=BlockPos{x=115, y=62, z=3250}, eyePos=(115.84630884556246, 63.98892231540144, 3252.561129771108), eyeHeight=1.6550021, lookX=0.0, lookY=0.0, lookZ=0.0
    , width=0.97353065, bb=box[115.10649639368057, 62.297607421875, 3250.3684592843056 -> 116.08002704381943, 64.04996252059937, 3251.3419899344444] }, EntityZombie['Zombi'/83881, l='MpServer', x=130.50, y=21.00, z=3211.50], EntityWolf['Lobo'/83561, l='MpServer', x=163.51, y=77.00, z=3295.49], EntityWolf['Lobo'/83563, l='MpServer', x=165.33, y=80.00, z=3289.36], EntityWolf['Lobo'/84075, l='MpServer', x=171.52, y=86.00, z=3326.50], EntityWolf['Lobo'/83562, l='MpServer', x=164.38, y=77.00, z=3295.70], DinosaurEntity{ jurassicraft:triceratops, id=84074, remote=true, isDead=false, isCarcass=false, isSleeping=false, stayAwakeTime=0
    , dinosaurAge=143661, prevAge=143661, maxAge135000, ticksExisted=11, entityAge=0, isMale=false, growthSpeedOffset=0
    , food=168000 / 168000 (147000.0), water=168000 / 168000 (147000.0), digestingFood=0 / 3000, health=61.743877 / 61.743877
    , pos=BlockPos{x=133, y=72, z=3346}, eyePos=(136.25636502601853, 74.13463878804734, 3346.7051534827724), eyeHeight=1.6420047, lookX=0.0, lookY=0.0, lookZ=0.0
    , width=2.2805622, bb=box[133.35971891880035, 72.0, 3346.32146800358 -> 135.64028108119965, 74.73667478561401, 3348.602030165979] }, EntityItem['item.item.arrow'/83565, l='MpServer', x=187.13, y=76.00, z=3278.62], EntityWolf['Lobo'/84077, l='MpServer', x=162.47, y=80.00, z=3326.30], EntityWolf['Lobo'/83564, l='MpServer', x=186.78, y=77.00, z=3278.71], EntityWolf['Lobo'/84076, l='MpServer', x=162.64, y=82.00, z=3323.84], EntityFox['Arctic Fox'/83567, l='MpServer', x=234.33, y=64.00, z=3269.46], EntityWolf['Lobo'/84079, l='MpServer', x=154.63, y=84.00, z=3322.50], EntityItem['item.item.bone'/83566, l='MpServer', x=187.99, y=76.00, z=3278.84], EntityWolf['Lobo'/84078, l='MpServer', x=157.47, y=79.00, z=3327.43], EntityFox['Arctic Fox'/83568, l='MpServer', x=235.50, y=65.00, z=3274.50], DinosaurEntity{ jurassicraft:triceratops, id=83451, remote=true, isDead=false, isCarcass=false, isSleeping=false, stayAwakeTime=0
    , dinosaurAge=141959, prevAge=141959, maxAge135000, ticksExisted=21, entityAge=0, isMale=true, growthSpeedOffset=0
    , food=168000 / 168000 (147000.0), water=168000 / 168000 (147000.0), digestingFood=0 / 3000, health=72.47222 / 70.0
    , pos=BlockPos{x=198, y=91, z=3208}, eyePos=(201.34634782883754, 93.13463878804734, 3208.0712053806824), eyeHeight=1.7986412, lookX=0.0, lookY=0.0, lookZ=0.0
    , width=2.4981127, bb=box[198.44688130378967, 91.0, 3207.5697819448887 -> 200.9449939823175, 93.99773526191711, 3210.0678946234166] }, DinosaurEntity{ jurassicraft:triceratops, id=83450, remote=true, isDead=false, isCarcass=false, isSleeping=false, stayAwakeTime=0
    , dinosaurAge=141959, prevAge=141959, maxAge135000, ticksExisted=21, entityAge=0, isMale=true, growthSpeedOffset=0
    , food=168000 / 168000 (147000.0), water=168000 / 168000 (147000.0), digestingFood=0 / 3000, health=70.0 / 70.0
    , pos=BlockPos{x=192, y=87, z=3209}, eyePos=(195.3130036520348, 89.13463878804734, 3209.4004746057376), eyeHeight=1.7146231, lookX=0.0, lookY=0.0, lookZ=0.0
    , width=2.381421, bb=box[192.44861957797264, 87.0, 3209.309289455414 -> 193.44861957797264, 88.0, 3210.309289455414] }, DinosaurEntity{ jurassicraft:triceratops, id=83453, remote=true, isDead=false, isCarcass=false, isSleeping=false, stayAwakeTime=0
    , dinosaurAge=141928, prevAge=141928, maxAge135000, ticksExisted=21, entityAge=0, isMale=true, growthSpeedOffset=0
    , food=168000 / 168000 (147000.0), water=168000 / 168000 (147000.0), digestingFood=0 / 3000, health=78.562035 / 70.0
    , pos=BlockPos{x=195, y=86, z=3208}, eyePos=(197.77362354113194, 88.13463878804734, 3208.556853082775), eyeHeight=1.5388454, lookX=0.0, lookY=0.0, lookZ=0.0
    , width=2.1372852, bb=box[194.90033647951714, 86.0, 3207.7033701918645 -> 195.90033647951714, 87.0, 3208.7033701918645] }, DinosaurEntity{ jurassicraft:triceratops, id=83452, remote=true, isDead=false, isCarcass=false, isSleeping=false, stayAwakeTime=0
    , dinosaurAge=141959, prevAge=141959, maxAge135000, ticksExisted=21, entityAge=0, isMale=false, growthSpeedOffset=0
    , food=168000 / 168000 (147000.0), water=168000 / 168000 (147000.0), digestingFood=0 / 3000, health=70.0 / 70.0
    , pos=BlockPos{x=202, y=91, z=3210}, eyePos=(205.04676673164107, 93.13463878804734, 3210.00669500897), eyeHeight=1.8000605, lookX=0.0, lookY=0.0, lookZ=0.0
    , width=2.500084, bb=box[202.14798794818654, 91.0, 3209.5641578582126 -> 203.14798794818654, 92.0, 3210.5641578582126] }]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 144847008 bytes (138 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_G5 41 mods loaded, 41 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version                            | Source                                      | Signature                                |
	|:------ |:------------------- |:---------------------------------- |:------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2                             | minecraft.jar                               | None                                     |
	| LCHIJA | mcp                 | 9.42                               | minecraft.jar                               | None                                     |
	| LCHIJA | FML                 | 8.0.99.99                          | forge-1.12.2-14.23.5.2854.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2854                       | forge-1.12.2-14.23.5.2854.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | xaerominimap_core   | 1.12.2-1.0                         | minecraft.jar                               | None                                     |
	| LCHIJA | damageindicatorsmod | 1.0                                | [1.12.2]DamageIndicatorsMod-3.5.1.jar       | None                                     |
	| LCHIJA | carrots             | 1.0.0b1                            | carrotslib-mc1.12.2-1.0.0b1.jar             | None                                     |
	| LCHIJA | armorunder          | 1.0.0                              | armorunder-mc1.12.2-1.0.0.jar               | None                                     |
	| LCHIJA | carryon             | 1.12.3                             | carryon-1.12.2-1.12.4.16.jar                | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
	| LCHIJA | chameleon           | 1.12-4.1.3                         | Chameleon-1.12-4.1.3.jar                    | None                                     |
	| LCHIJA | ctm                 | MC1.12.2-1.0.2.31                  | CTM-MC1.12.2-1.0.2.31.jar                   | None                                     |
	| LCHIJA | jei                 | 4.16.1.302                         | jei_1.12.2-4.16.1.302.jar                   | None                                     |
	| LCHIJA | chisel              | MC1.12.2-1.0.2.45                  | Chisel-MC1.12.2-1.0.2.45.jar                | None                                     |
	| LCHIJA | climaticbiomesjbg   | 2.16.4                             | ClimaticBiomes-2.16.4-MC1.12.2.jar          | None                                     |
	| LCHIJA | craftingstation     | @VERSION@                          | craftingstation-0.1.8a.jar                  | None                                     |
	| LCHIJA | falling_tree        | 2.4.0                              | FallingTree-1.12.2-2.4.0.jar                | None                                     |
	| LCHIJA | familiarfauna       | 1.0.11                             | FamiliarFauna-1.12.2-1.0.11.jar             | None                                     |
	| LCHIJA | llibrary            | 1.7.20                             | llibrary-1.7.20-1.12.2.jar                  | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | fossil              | 8.0.5                              | fossilsarcheology-8.0.5.jar                 | None                                     |
	| LCHIJA | waila               | 1.8.26                             | Hwyla-1.8.26-B41_1.12.2.jar                 | None                                     |
	| LCHIJA | inventorytweaks     | 1.64+dev.151.822d839               | InventoryTweaks-1.64+dev.151.jar            | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironchest           | 1.12.2-7.0.67.844                  | ironchest_1.12.2_7.0.72.847.jar             | None                                     |
	| LCHIJA | ironfurnaces        | 1.3.5                              | ironfurnaces-1.3.5.jar                      | None                                     |
	| LCHIJA | mcwdoors            | 1.3                                | mcw-doors-1.0.3-mc1.12.2.jar                | None                                     |
	| LCHIJA | mcwfences           | 1.0.0                              | mcw-fences-1.0.0-mc1.12.2.jar               | None                                     |
	| LCHIJA | mcwwindows          | 1.0                                | mcw-windows-1.0.0-mc1.12.2.jar              | None                                     |
	| LCHIJA | minejurassic        | 1.2.0 - The Secret of InGen Update | MineJurassic-1.2.0-1.12.2.jar               | None                                     |
	| LCHIJA | moreplayermodels    | 1.12.2                             | MorePlayerModels_1.12.2-(05Dec19).jar       | None                                     |
	| LCHIJA | mw                  | 0.4.6.2                            | mw_2.0-0.4.6.2_mc1.12.2.jar                 | None                                     |
	| LCHIJA | neat                | 1.4-17                             | Neat_1.4-17.jar                             | None                                     |
	| LCHIJA | harvestcraft        | 1.12.2zb                           | Pam's+HarvestCraft+1.12.2zg.jar             | None                                     |
	| LCHIJA | corerm              | 1.3.3                              | RikMuldsCore_1.3.3.jar                      | None                                     |
	| LCHIJA | sereneseasons       | 1.2.18                             | SereneSeasons-1.12.2-1.2.18-universal.jar   | None                                     |
	| LCHIJA | storagedrawers      | 5.2.2                              | StorageDrawers-1.12.2-5.4.2.jar             | None                                     |
	| LCHIJA | camping             | 2.4.3                              | TheCampingMod_2.4.3.jar                     | None                                     |
	| LCHIJA | toughasnails        | 3.1.0.141                          | ToughAsNails-1.12.2-3.1.0.141-universal.jar | None                                     |
	| LCHIJA | travelersbackpack   | 1.0.35                             | TravelersBackpack-1.12.2-1.0.35.jar         | None                                     |
	| LCHIJA | wailaharvestability | 1.1.12                             | WailaHarvestability-mc1.12-1.1.12.jar       | None                                     |
	| LCHIJA | walljump            | 1.3.2                              | walljump-1.12.2-1.3.2.jar                   | None                                     |
	| LCHIJA | xaerominimap        | 21.14.1                            | Xaeros_Minimap_21.14.1_Forge_1.12.jar       | None                                     |
	| LCHIJA | jurassicraft        | 2.1.23                             | JurassiCraft-1.12.2-2.1.23.jar              | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.151.jar)
  invtweaks.forge.asm.ContainerTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
weaponlib (mw_2.0-0.4.6.2_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
XaeroMinimapPlugin (Xaeros_Minimap_21.14.1_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
  xaero.common.core.transformer.ModelRendererTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 630 GL version 4.6.0 - Build 27.20.100.8681, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Español (España)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Chocapic13_Better_Default_Beta_4.zip
	OpenGlVersion: 4.6.0 - Build 27.20.100.8681
	OpenGlRenderer: Intel(R) UHD Graphics 630
	OpenGlVendor: Intel
	CpuCount: 12

**Comment by PocketfulOfGeese** [comment]
I don't see Astral Sorcery listed in the mod list there, much less the crash trace.

**Comment by Alexor3** [comment]
Sorry, I don't understand why should be the Astral in the list

**Comment by Alexor3** [comment]
Oh, sorry, now I understand
Sorry for posting in wrong site

**Comment by PocketfulOfGeese** [comment]
This a github for the Astral Sorcery mod. If the mod is not the cause of a crash, this is not the place to report your issue.
