### ISSUE TITLE
[1.16.4] Dupe issue

### ISSUE THREAD

**Issue by SeroMaster** [HellFirePvP/AstralSorcery#1884]
Valhelsia 3.

Perk for transfering items in inventory combined with enchantment which does the same allows duping blocks. (Vicio path perk "Spatial Manipulation" + Charm's "Acquisition" enchantment"

**Comment by SeroMaster** [comment]
Update

Problem weren't in double enchantments, but cause of Scarf of luck item from "Artifacts" modification. There's no dupe when use this scarf with enchanted pickaxe, so I guess issue is in Astral Sorcery.

**Comment by luna6667** [comment]
What version of the mod are you on? This might be a duplicate of #1616

**Comment by PocketfulOfGeese** [comment]
I can't replicate this under the latest version of Valhesia 3. I'm pretty sure this is the same already fixed issue.
