### ISSUE TITLE
Issue when removing the dynamism gems

### ISSUE THREAD

**Issue by Kingcardien** [HellFirePvP/AstralSorcery#1885]
Modpack : Enigmatica 6 0.5.11
Mod version : astralsorcery-1.16-1.16.5-1.13.12

Me and a friend are playing on a server with astral. We wanted to maxed out our health using various mods, including astral sorcery, and attained a certain number (eg. 199 health point in my case). After logging off the server and logging back again two days later, our maximum health decreased by quite a big amount (from 199 to 127.95). When trying to find the cause of this, we found out it was the dynamism gems.

The gems used are these :
- Ourium dynamism gem (blue)
  - 8% maximum life
  - 6% armor
  - 5% melee damage
  - 6% reach
 
 - Fengarum dynamism gem (white)
   - 8% maximum life
   - 7% critical hit chance
   - 7% armor

Here are three screenshots, one with the perks but no gems, I have 9 armor points only with the perks :
![2021-09-01_17 34 39](https://user-images.githubusercontent.com/67120772/131702927-9c240cde-00ff-4f8b-9681-39fdc059e812.png)

Here is a screenshot with the gems, 11 armor points but same maximum health :
![2021-09-01_17 34 56](https://user-images.githubusercontent.com/67120772/131704020-21cfa89c-6e04-4079-a836-0e1f1a933adf.png)

And here is a screenshot after removing the gems, the amount of armor point doesn't change :
![2021-09-01_17 35 07](https://user-images.githubusercontent.com/67120772/131704222-d2c81e6c-b1db-4aa0-ad4b-bed7d5371315.png)

We can see the armor point doesn't decrease as it should. By holding a removed gem and then holding another item, the amount of armor point decrease to the original value (so it needs to be done with both of them). The example with the armor points is for a better understanding of the issue, in the case of the health, adding the gems, removing them and holding them doesn't change the value anymore.

If this can help, my health is increased with :
- Botania: Ring of Odin (+20 max health)
- Spice of life: Carrot Edition (+28 hearts)
- Artifacts: Crystal heart (+5 hearts)

**Comment by dwentz89** [comment]
I can consistently reproduce this without other mods, and I also get the same "Trying to modify PerkConverters while modifiers are applied!" error message that was reported in #1771.

I'm on the following versions:
forge-1.16.5-36.2.20.jar
astralsorcery-1.16-1.16.5-1.13.12.jar
curios-forge-1.16.5-4.0.8.0.jar
observerlib-1.16.5-1.5.3.jar

I'm also on single player.

Steps:
1. Have a perk that increases max hp.
2. Have 3 gems equipped that increase max hp.
3. Load the world again.
4. Unequip the 3 gems.
5. Note that max hp did not go down when unequipping the gems.
6. Save and quit to title.
7. If you did step 6 fast enough after step 4, the game will crash with the "Trying to modify PerkConverters while modifiers are applied!" error.

I have already tried deleting my .astral file and adding the progress back with commands, but it didn't help.

Here's the .astral file I'm using: [4e40c508-e2ec-462e-bf46-a749f6073684.astral.gz](https://github.com/HellFirePvP/AstralSorcery/files/8038443/4e40c508-e2ec-462e-bf46-a749f6073684.astral.gz)
