### ISSUE TITLE
[Suggestion] Decrease Mining Level of Marble by 1

### ISSUE THREAD

**Issue by NielsPilgaard** [HellFirePvP/AstralSorcery#1886]
**Context**
In Enigmatica 6 we have layers of different stones (strata) instead of Stone with blobs of other materials. 
As such, it's random which kind of stone the player will first encounter when digging down.

Marble is one of those stones, and if you have yet to run into any other stone, you will be unable to mine the Marble, rendering you unable to make a Stone Pickaxe from it, effectively blocking progression. *- Stone Pickaxe recipe requires forge:stone*

The player can of course then dig down somewhere else, but it's a kinda feelbad start.

It would be a very nice change for us if Marble was harvestable with a Wooden Pickaxe. I hope you'll consider it :D

**Comment by PocketfulOfGeese** [comment]
This seems more a config issue for the pack's balance choices.
