### ISSUE TITLE
[1.12.2] Issue with Attunement of Players

### ISSUE THREAD

**Issue by nvzeppelin** [HellFirePvP/AstralSorcery#1887]
When you alt+f4 out of the game while you are attuning yourself, you cant see perks and also cant attune you anymore

**Comment by PocketfulOfGeese** [comment]
sounds like there's a desync involved between client and server. Would recommend attempting a relog.  Alt + F4 is never something that should be used to close MC, since there's entirely too many things that it can break.

1.12 is no longer supported, however.
