### ISSUE TITLE
[1.12.2]Star capability interface transparent

### ISSUE THREAD

**Issue by 623667595** [HellFirePvP/AstralSorcery#1888]
![image](https://user-images.githubusercontent.com/88877796/132159081-5301b512-120c-4238-a470-d7ce34c27d85.png)

**Comment by 623667595** [comment]
After testing, it conflicts with RPG HUD mod. As long as the display bar is adjusted, the star capability interface will not be displayed

**Comment by PocketfulOfGeese** [comment]
That is a conflict spawned by that mod's ui code.

It is an old one, too.

Also mc 1.12 is no longer supported for active dev or bug fixes for AS.
