### ISSUE TITLE
Cascading worldgen lag in version 1.12.2-1.10.27

### ISSUE THREAD

**Issue by Zalnor** [HellFirePvP/AstralSorcery#1889]
The version 1.12.2-1.10.27 of Astral Sourcery mod linked bellow causes cascading worldgen lag, by itself it wouldn't be that bad but in any sizeable modpack it adds on quite a bit of cascading worldgen lag. I have also included a link explaing exactly what that is and how to go about fixing it. Example setting an offset or flags when structures are spawned partially in a chunk and when adjesent chunks load it reads it and finishes generating the structure.

https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/

https://www.curseforge.com/minecraft/mc-mods/astral-sorcery/files/3044416

**Comment by PocketfulOfGeese** [comment]
MC 1.12 isn't supported any longer.
