### ISSUE TITLE
[1.12.2] Attempting to Re-Open a still broken issue with Difficulty being set to Normal when set to other modes

### ISSUE THREAD

**Issue by Shibva** [HellFirePvP/AstralSorcery#1890]
I have no idea why this was closed and locked up but the world difficulty issue that happens in the last version of Astral Sorcery for 1.12.2 still pre-exist for still unknown reasons and to be quite honnest, this issue is annoying. I tried to tinker with the worlds NBT data and it seems that even if you change the value, when you load the world in it sets it back to 2 (normal)

mods present: all of these are up to date

Just Enough Items (JEI) (by mezz)
ConnectedTexturesMod (by tterrag1098)
EverlastingAbilities-PotionCore (by kroeser)
Village Spawn Point (by Serilum)
Player Tracking Compass (by Serilum)
Spartan Weaponry (by ObliviousSpartan)
AppleSkin (by squeek502)
Doctor Who - Regeneration (by Suff99)
Mo' Bends (by iwoplaza)
Sit (by bl4ckscor3)
OreLib (by OreCruncher)
Wawla - What Are We Looking At (by DarkhaxDev)
Cyclops Core (by kroeser)
Spartan and Fire (by cbkovak)
LLibrary (by _ForgeUser11902522)
Auto Network Lib (by aurocosh)
Wings (by pau101)
Dragon Mounts 2 (DISCONTINUED) (by TheRPGAdventurer101)
Schematica (by Lunatrius)
LunatriusCore (by Lunatrius)
Patchouli (by Vazkii)
[Backport] 1.13 Water Mechanics [Bubble Columns] (by xFrah)
JourneyMap (by techbrew)
Divine Favor (by aurocosh)
Doggy Talents (by percivalalb)
No Recipe Book (by Seneschal_Luwin)
Fancy Block Particles (by TominoCZ)
EverlastingAbilities (by kroeser)
Spartan Shields (by ObliviousSpartan)
Astral Sorcery (by HellFirePvP)
Dynamic Surroundings: HUDs (by OreCruncher)
Netherite (by ShadowRapZA)
Additional Resources (by Portablejim)
Audio Death (by Portablejim)
CreativeCore (by CreativeMD)
Collective (by Serilum)
Potion Core (by Tmtravlr)
Baubles (by Azanor13)
Extra Arcane Knowledge (Electroblob's Wizardry) (by Ghostrider231_)
Extra Spells (Electroblob's Wizardry) (by meldexun)
Village Names (by AstroTibs)
Ice and Fire: Dragons (by alex_khaan)
Mouse Tweaks (by YaLTeR)
Shadowfacts' Forgelin (by ShadowfactsDev)
Hwyla (by TehNut)
EnhancedVisuals (by CreativeMD)
Electroblob's Wizardry (by Electroblob)

Ik it may be unlikely that this will get fixed, but maybe this can be a fix update or something to try and correct this one issue, please consider in looking into it. it would be appreciated.

**Comment by Shibva** [comment]
same issue as https://github.com/HellFirePvP/AstralSorcery/issues/426 that was closed as far as I know without any fix

**Comment by Jeuvke** [comment]
As far as I can tell from the original issue and linked issue #451, it appears that this is a forge bug related to dimension loading and therefore not AS's fault.

**Comment by PocketfulOfGeese** [comment]
All of which is ultimately irrelevant, because Minecraft 1.12 is no longer supported by this mod.
