### ISSUE TITLE
Wither able to pass through Astral Sorcery Illuminated blocks

### ISSUE THREAD

**Issue by NielsPilgaard** [HellFirePvP/AstralSorcery#1892]
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/3222

### Versions

- astralsorcery-1.16-1.16.5-1.13.12
- Forge-1.16.5-36.2.2

### Description

> **Modpack version**
> Enigmatica6 0.5.11
> 
> **Issue**
> After spawning a Wither will pass through blocks that have been wither-proofed by the Illumination Wand once it has spotted a target. It would float up and through the ceiling as soon as it sees a valid target (within the box). In this case it's a 9x9x5 box made of Astral Sorcery marble that has been proofed. I used a few different colors for the wand but that shouldn't affect the blocks' property, as the tooltip always says it renders blocks immune to the Wither regardless of the wand's color. It's projectiles were also able to pass through the box as well.
> 
> ![2021-09-11_01 31 26](https://user-images.githubusercontent.com/88354170/132938970-70822e48-3b87-4cf7-b8ad-c5895f6d9460.png)

**Comment by PocketfulOfGeese** [comment]
I'm unable to replicate the wither projectile passthrough using only AS and its dependencies.

I can get the wither to passthrough the box only if the box has 3 blocks of interior vertical height (a 9x9x5 structure). 4 blocks of interior vertical height does not display this behavior (a 9x9x6), unless there is also a 1 block hole in the roof by which the wither can fly up and out to seek a valid target. This looks like standard vanilla wither movement issue to me, not something specific to AS.
