### ISSUE TITLE
Link from lens to cristal collector

### ISSUE THREAD

**Issue by NihilSuperbia** [HellFirePvP/AstralSorcery#1897]
Hello! So, i honestly don't know a THING about this mod. And, i love to discover on my own mods and everything else.
So, i tried to link crystal collector and a lens, searching how to make dust from starmetal ingot. But, suddenly, my game crashed and when i try to relog into the world (not the launcher) it crashes again, and again. I can create as many new worlds without any issues.

Here's the crash report: https://pastebin.com/QkZGceHs
i hope that can be useful, have a good day

**Comment by PocketfulOfGeese** [comment]
You had the stats stripped from the lens, so it's throwing an error. I imagine you used Building Gadgets to place the lens? It strips the NBT data, which causes this.

Don't use Building Gadgets to place AS lenses, crystals, etc. Marble only, really.

Also, lenses are non-functional in the current 1.16.5 release: #1835

To fix this, set the server config option "performNetworkIntegrityCheck" located under <pack_save_directory>/saves/<world_name>/serverconfig/astralsorcery.toml to "true" and load the game. It should resolve the issue long enough to break the lens. If not, you'll need to edit that lens out using a third party world editing tool.

Once your fixed, though, the section of the Astral Tome that details how to make stardust is under the "Starmetal Cutting Tool" entry. Looks like a chisel in the book.

If you have additional issues, I'd recommend coming to the discord server linked from the mod's curseforge page.
