### ISSUE TITLE
Text in journal entry goes off the page in "Crystal Tools" entry

### ISSUE THREAD

**Issue by Febilian** [HellFirePvP/AstralSorcery#19]
https://gyazo.com/4861ca3ef0df12e36c0038cf367c5da6

The "Crystal Tools" entry is the one doing it. It doesn't matter what I change my GUI scale to, it's always going off the page of the book like that.

The above picture was with "Large" GUI scale active, this is "Small":

https://gyazo.com/b1c33d44bdcf20b8070666cac54b5359

**Comment by 63502** [comment]
I just rewrote that entry the other day, so it just hasn't been resized yet. It will be fixed by the next update.

**Comment by HellFirePvP** [comment]
I'll just reopen that for now so i don't forget.
