### ISSUE TITLE
Knowledge sharing

### ISSUE THREAD

**Issue by generilisk** [HellFirePvP/AstralSorcery#190]
I'm playing in a 2-player world with a friend, and while we have been able to share the constellation pages we've found thus far, there's no way to open up further sections in his book after I created something to advance my book. We would have to re-craft the structure twice, which seems unnecessary. Thaumcraft had a knowledge sharing journal you could craft; perhaps the same thing could be done here?

**Comment by HellFirePvP** [comment]
I might want to add that it is not thaumcraft that added that. it was an addon for thaumcraft.

**Comment by generilisk** [comment]
That's fair, it's been a while since I played that with friends. As long as you knew what I meant, though.

**Comment by HellFirePvP** [comment]
Added next version.
