### ISSUE TITLE
Create Deployers seem to know how to insert items into the light wells intended or not?

### ISSUE THREAD

**Issue by Algester** [HellFirePvP/AstralSorcery#1900]
I mean I forgot the exact details of my modlist but its been so long since I have updated my modpack

**Comment by PocketfulOfGeese** [comment]
It can be done from the bottom face of the lightwell, just like fluid extraction.

If it works from another side or face, then sidedness isn't being respected in their inventory interaction code.

**Comment by Algester** [comment]
Interesting cause last time I tried to make lightwells be piped in items from any side it didnt to like it....

**Comment by PocketfulOfGeese** [comment]
Any side isn't the bottom. Gotta be in 1.16 for that, though.
