### ISSUE TITLE
Making the Luminous Crafting Table Process?

### ISSUE THREAD

**Issue by SliverMessiah** [HellFirePvP/AstralSorcery#1901]
I am currently playing the Modpack: All the Mods 6 in 1.16.5. 

![2021-10-20_20 23 25](https://user-images.githubusercontent.com/92107357/138190288-cafde47b-abac-4a5b-9b1c-648284af6ea5.png)
From the image above, the Crafting Table has sat there for now 2 night cycles and it hasn't transformed into the Luminous Crafting Table. 

Am i missing a step or is it the modpack that's causing this issue?

**Comment by PocketfulOfGeese** [comment]
Occasionally a world-generated crystal may be a dud. Check with another crystal.

**Comment by SliverMessiah** [comment]
Thanks! yup that was the issue. Found a new crystal and worked right away.
