### ISSUE TITLE
Request: Spinoff Liquid Interaction into separate mod?

### ISSUE THREAD

**Issue by UnseenAcademical** [HellFirePvP/AstralSorcery#1902]
Hi!

I've been working on some modpack design ideas that would benefit from liquid interactions. The whole idea was due to my good interactions with fluids in Astral Sorcery. However, I would like the modpack to have AS as an "optional extra" to increase modularity. Would you consider spinning off the liquid interaction code into a library mod or permitting me to use it in a derivative mod?

Thank you!

**Comment by PocketfulOfGeese** [comment]
Can you clarify the specifics? AS leverages vanilla liquid interaction code for liquid starlight interactions.

If you mean the in-world liquid submersion interactions, ElectroBlob's Wizardry has some of that already, with CTable additions iirc.

**Comment by UnseenAcademical** [comment]
Ah, my apologies. I am unfamiliar with the vanilla liquid interaction code, so I was drawing on the CraftTweaker documentation pointing to the Liquid Interaction code here. Is there a good resource you'd recommend for creating additional liquid interactions, possibly via datapack? I see options for creating a custom fluid, but all I can find for the interaction of liquids so far seems to point here.

**Comment by PocketfulOfGeese** [comment]
Unsure, that would be better directed towards a more generalized minecraft datapack resource for that.
