### ISSUE TITLE
Cannot place liquid starlight buckets on the ground by hand, can only be picked up.

### ISSUE THREAD

**Issue by SelkeGore** [HellFirePvP/AstralSorcery#1904]
Version: 1.16.5
Forge Version: 36.2.4

The mod list is gigantic, also I'm not fully sure how I'm actually supposed to drop it (was gonna make a rar file with all 300 but I doubt you're looking to download something) and I also have a suspicious feeling the issue is the forge version above all else. If you want / need a mod list, lmk as to how I should add it and I'll do so.

**Comment by PocketfulOfGeese** [comment]
That forge version is over a month old, have you tried updating to newest? I don't suspect it will solve the issue, but worth a shot.

I don't believe I've seen this in your used forge version before, but last time I saw this it was a mod interaction issue causing problems for non-vanilla fluids. You will need to perform a binary search of the pack: remove half the mods (mind dependencies), check if issue persists. If it does, remove half of the remaining ones again, if not use the other half you removed, and keeo checking until you have narrowed it down to a single mod. By dividing the list in half each time, you should be able to figure out which mod it is in a failry quick time. Narrowed to under a dozen mods in around 6 attempts, possibly fewer depending on dependency count.

**Comment by SelkeGore** [comment]
Working on it right now, I'll post results once I have them.

**Comment by SelkeGore** [comment]
Done. MerchantPug's TooManyOrigins is the sole cause. It also breaks some other modded liquids such as the underground rifts from BetterPortals. I assume this issue is 100% on their end and not yours, thank you for the help. I've made an issue request over on their end.
