### ISSUE TITLE
[1.16.5][Attunement Altar ]  flash back and crazy rotation of perspective

### ISSUE THREAD

**Issue by NXLcyan** [HellFirePvP/AstralSorcery#1907]
BetterThirdPerson-Forge-1.16.4-1.5.1    When the player stands on the resonance altar, the perspective will rotate wildly
travelers_index-1.16.4-1.0.2      When players stand on the altar of resonance, the game will collapse
This is the first time I use GitHub, I dont know how to upload the crash log. I'm sorry

**Comment by PocketfulOfGeese** [comment]
That's going to be an interaction issue from those mods.

**Comment by HellFirePvP** [comment]
Nothing i can do there.
You may want to ask on their issue tracker to not do camera manipulations in case
`hellfirepvp.astralsorcery.client.util.camera.ClientCameraManager.INSTANCE.hasActiveTransformer()`
returns true.
