### ISSUE TITLE
Resources not loading

### ISSUE THREAD

**Issue by DracoFlame90** [HellFirePvP/AstralSorcery#1908]
Just seeing black/pink blocks for the aquamarine sand and the crystals found in the shrines. Haven't been able to progress yet to check textures on other items, playing on 1.15.2, with the version 1.12.14. Not sure if it's a problem with Astral, or a conflict with another mod.

**Comment by PocketfulOfGeese** [comment]
Should be a mod conflict, or an issue with a texture pack being used in the pack, as that shouldn't be occurring with only AS.

Only 1.16 is being considered for patches/fixes, regardless.
