### ISSUE TITLE
[Minor Bug; 1.16.5] Incorrect handinng of liquid starlight buckets in alters

### ISSUE THREAD

**Issue by Shibva** [HellFirePvP/AstralSorcery#1909]
This is a verry simple issue, it seems that when you craft with a bucket of starlight that it dosent consume the starlight inside of it
(it returns the item or dosent consume it in the crafting process when it should be giving back an empty bucket; currently it just gives back the starlight filled bucket after a crafting opperation)

**Comment by PocketfulOfGeese** [comment]
#1846
