### ISSUE TITLE
Stellar Refraction Table only allows accessing 12 visible constellations

### ISSUE THREAD

**Issue by DerringersMods** [HellFirePvP/AstralSorcery#1910]
Third Quarter has a full complement of 12 visible constellations. If Horologium falls on the same night, one constellation will be inaccessible since there are only 12 positions to pick from.

While it's not required to have another mod installed to surface the issue, if an add-on such as Nature's Starlight adds a constellation, the likelihood of encountering the issue increases significantly.

**Comment by PocketfulOfGeese** [comment]
The night a constellation appears is influenced by world seed. It is not static for all worlds.

**Comment by DerringersMods** [comment]
That doesn't invalidate the underlying issue. If randomization allows 12 regular constellations to fall on one night, a 'lucky' eclipse or add-on constellation can overflow the SRT.

**Comment by PocketfulOfGeese** [comment]
And that is intentional at the moment.

**Comment by DerringersMods** [comment]
Suggestion then: shuffle the SRT constellation list with a seed based on the calendar day before taking the first 12.
