### ISSUE TITLE
Random Crash while doing..well.. nothing

### ISSUE THREAD

**Issue by SheReyy** [HellFirePvP/AstralSorcery#1911]
Mc version: 1.16.5
Mod version: astralsorcery-1.16-1.16.5-1.13.12.jar
Forge Version: 36.2.4
Java version: 1.8.0.311
Mod list: https://paste-bin.xyz/20959

What happened: I was searching for something in the Astral Tome, and then... crash.

Here's my latest log:
[latest.log](https://github.com/HellFirePvP/AstralSorcery/files/7664638/latest.log)

**Comment by Jeuvke** [comment]
Can you give any more detailed steps on how to reproduce this? I think I've narrowed it down to trying to delete a section of text with a negative length, but I have no idea how you managed to do that. Also your Java version is 1.8.0_51, not 1.8.0.311.

Code:
```
         int var2 = Math.min(this.cursorPos, this.selectionPos);
         int var3 = Math.max(this.cursorPos, this.selectionPos);
         String var4 = var1.substring(0, var2) + var1.substring(var3);
```
where `this.cursorPos` or `this.selectionPos` is equal to -3

**Comment by SheReyy** [comment]
Honestly, I have no idea how to reproduce that. I was just looking through the Astral Tome in the "search section" and I was looking for something involving "attunement". That crash happened to me only once and I think it might be that kind of crash which happens once every 342324235252324 centuries, so... And yeah, I know about the java version. Someone on the Astral Discord pointed it out to me. Since I rectified the issue with the Java version, that crash disappeared.

If it helps, I'll leave [here](https://paste-bin.xyz/20959) the mod list I was using.

**Comment by PocketfulOfGeese** [comment]
Has this one repeated since the java update @EuSuntMarian ?

**Comment by SheReyy** [comment]
Nope 👌

**Comment by PocketfulOfGeese** [comment]
Gonna mark this one as a weird java thing, then, unless someone else can replicate.
