### ISSUE TITLE
Bro ?

### ISSUE THREAD

**Issue by Vanilleeeu** [HellFirePvP/AstralSorcery#1919]
Hi, the mod is really cool and I'm having a lot of fun with it. On the other hand if you could avoid making changes every two days it would be nice because no video seems to be up to date even th
![8b6fc76d523a9efaed22e4b650e4f318](https://user-images.githubusercontent.com/97549272/148998506-289b048c-ac95-4512-8217-9bb7a8aadd57.jpg)
ough they are recent. Thank you.

**Comment by PocketfulOfGeese** [comment]
1. Be less of a fuck with your words.
2. What are you even talking about the mod has had no large changes in well over a year.
