### ISSUE TITLE
Linking Collector Crystal Crashes Server.

### ISSUE THREAD

**Issue by MercuryMaiden** [HellFirePvP/AstralSorcery#1920]
I believe this is the server crash log? 
My run down of what is happening is, I grab my linking tool -> link the celestial collector crystal (attuned to Aevitas) -> and link it to a lens -> server crashed on immediate link to lens.

(Edit) - I'm using modpack Valhesia 3 version 3.4.9, with some slight modifications.
(Edit 2) - Also, I tried it with many different crystals, every time I link a collector crystal to a lens, whether its from a shrine or enhanced one, it crashes. However, I can move the lens block with the link tool to make it face blocks and it doesn't crash. 

I'm not sure what mod could be conflicting with this mod, but there are a ton of mods... Please let me know if there is any logs or anything needed for further info!

[crash-2022-01-12_19.04.03-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/7858967/crash-2022-01-12_19.04.03-server.txt)

------------------

Omg, I'm sorry... I read through discord if it was spawned in and doesn't have the correct NBT data it will crash no matter what. I suppose we can close this then! I'll try crafting one instead of spawning it in and see if that makes a difference!  Was building a astral sorcery area and been spawning stuff in.

**Comment by PocketfulOfGeese** [comment]
Ones pulled from the vanilla creative menu will work just fine, as an FYI. JEI should also work since that mimics the vanilla item spawn.
