### ISSUE TITLE
Astral Sorcery/Optifine Shaders conflict

### ISSUE THREAD

**Issue by Andrew-Cole2** [HellFirePvP/AstralSorcery#1921]
I'm aware this is just a mod conflict caused by optifine and the astral sorcery sky shaders, but am posting it here because it was almost impossible to find the issue mentioned with a fix anywhere else:

Some shaderpacks that use `gbuffers_skybasic` (such as BSL, Tea, Complementary, KUDA, Silduers, SEUS, and BeyondBelief) will cause an issue where the sky will either be black, or have flickering lines across it.

To fix this in 1.16.5+ the user has to disable the astral sorcery sky rendering by removing `"minecraft:overworld"` from `skyRenderingEnabled = []` in the `astralsorcery-client.toml` config

I have not gone through the process for versions under 1.16, but I used this video for 1.14; https://www.youtube.com/watch?v=WYI-g4hYhW4; to figure out a solution.

I apologize that this isn't the right place for this but just wanted to share the info

**Comment by PocketfulOfGeese** [comment]
It's on the curseforge main page with the explicit call-out for pre-1.16 versions, and it's in the Discord for 1.16 and later.

There was never a 1.14 release.

**Comment by Andrew-Cole2** [comment]
My bad, I have a bug with the curseforge site where it will only serve me captcha pages so I couldn't check the main page. I thought that video I linked had mentioned it was for 1.14 but that must have been the modpack version. I'm not a part of the discord so I didn't think to check there
