### ISSUE TITLE
[1.16.5 - 1.13.12] Bucket of Liquid Starlight wont pour

### ISSUE THREAD

**Issue by GreyGuy495** [HellFirePvP/AstralSorcery#1923]
I started progressing with this mod and quickly came to realize that buckets of liquid starlight wont pour, what can i do to fix this?

**Comment by PocketfulOfGeese** [comment]
Can't replicate with only AS, it's required dependencies, and latest forge release. Sounds like some other mod in the pack you are playing is causing issues.
