### ISSUE TITLE
constant xp while standing still with Vicio (1.12.2)

### ISSUE THREAD

**Issue by iceyrazor** [HellFirePvP/AstralSorcery#1924]
pretty much what the title says. if you activate your elytra, then land and stand still. you will get constant xp.

relogging seems to stop it but you still retain atleast 98% of what you had.

modver: astralsorcery-1.12.2-1.10.27

<details><summary>Mods</summary>
<p>
AcademyCraft-1.1.3.jar<br>
alchemistry-1.12.2-42.jar<br>
alib-1.0.12.jar<br>
astikorcarts-1.12.2-0.1.2.7.jar<br>
astralsorcery-1.12.2-1.10.27.jar<br>
AutoRegLib-1.3-32.jar<br>
Baubles-1.12-1.5.2.jar<br>
bewitchment-1.12.2-0.0.22.64.jar<br>
BiblioCraft[v2.4.5][MC1.12.2].jar<br>
BloodMagic-1.12.2-2.4.3-105.jar<br>
Bookshelf-1.12.2-2.3.590.jar<br>
cc-tweaked-1.12.2-1.89.2.jar<br>
Chisel-MC1.12.2-1.0.2.45.jar<br>
CodeChickenLib-1.12.2-3.2.3.358-universal.jar<br>
CoFHCore-1.12.2-4.6.6.1-universal.jar<br>
CoFHWorld-1.12.2-1.4.0.1-universal.jar<br>
CosmeticArmorReworked-1.12.2-v5a.jar<br>
Craftable+Saddles[1.12]-1.3.jar<br>
CreativeCore_v1.10.57_mc1.12.2.jar<br>
CTM-MC1.12.2-1.0.2.31.jar<br>
DoggyTalents-1.12.2-1.15.1.6.jar<br>
EnchantingPlus-1.12.2-5.0.176.jar<br>
EnderCore-1.12.2-0.5.73.jar<br>
endercrop-1.12.2-1.6.0.jar<br>
EnderIO-1.12.2-5.1.52.jar<br>
Forgelin-1.8.4.jar<br>
Guide-API-1.12-2.1.8-63.jar<br>
Guidebook-1.12.2-2.9.5.jar<br>
Hwyla-1.8.26-B41_1.12.2.jar<br>
iceandfire-1.9.1-1.12.2.jar<br>
InventoryTweaks-1.63.jar<br>
ironchest-1.12.2-7.0.72.847.jar<br>
ironfurnaces-1.3.5.jar<br>
jei_1.12.2-4.15.0.296.jar<br>
jetif-1.12.2-1.5.1.jar<br>
journeymap-1.12.2-5.7.1.jar<br>
librarianlib-1.12.2-4.22.jar<br>
llibrary-1.7.20-1.12.2.jar<br>
Mantle-1.12-1.3.3.55.jar<br>
MineMenu-1.12.2-1.6.11-universal.jar<br>
moreoverlays-1.15.1-mc1.12.2.jar<br>
movingworld-1.12-6.353-full.jar<br>
mysticallib-1.12.2-1.10.0.jar<br>
OptiFine_1.12.2_HD_U_G5.jar<br>
Patchouli-1.0-23.6.jar<br>
Psi-r1.1-78.2.jar<br>
psipherals-1.1.0.jar<br>
RedstoneFlux-1.12-2.1.1.1-universal.jar<br>
refinedstorage-1.6.16.jar<br>
rpsideas-2.4.4.jar<br>
SGCraft-2.0.5.jar<br>
Tails-1.12-1.10.0.jar<br>
TConstruct-1.12.2-2.13.0.171.jar<br>
themidnight-0.3.5.jar<br>
ThermalDynamics-1.12.2-2.5.6.1-universal.jar<br>
ThermalExpansion-1.12.2-5.5.7.1-universal.jar<br>
ThermalFoundation-1.12.2-2.6.7.1-universal.jar<br>
Vampirism-1.12.2-1.6.2.jar<br>
WailaHarvestability-mc1.12-1.1.12.jar<br>
WarpDrive-1.12.2-1.5.23.jar<br>
Wawla-1.12.2-2.5.273.jar<br>
zerocore-1.12.2-0.1.2.8.jar<br>
[1.12.2]DamageIndicatorsMod-3.5.1.jar<br>
</p>
</details>

**Comment by PocketfulOfGeese** [comment]
1.12 dev is closed, but vicio xp gain is based on vanilla movrment counters going up, so sounds like there is an odd mod interaction there.

**Comment by iceyrazor** [comment]
that was quick for you to goto "eh not my mod not my problem". in this instance. the bug is related to a function you decided to use. regardless of if its a mod conflict, its mainly a function in your mod. 

but you did say you no longer work on 1.12. understandable

either way a bug is a bug and i decided to report it.

if i were to lean java and fix this myself. would you take it?

**Comment by iceyrazor** [comment]
just confirmed. this is NOT a mod conflict, just tested it with just astral. idc if you keep it closed because your not working on it. but remove the "not my mod" tag

both server and solo
