### ISSUE TITLE
buffs/debuffs causing looking glass and telescope to glitch out

### ISSUE THREAD

**Issue by PrimeSins** [HellFirePvP/AstralSorcery#1928]
_**I know that shaders often mess with the built-in shaders for mods, but this is not because of my shaders.**_ 

I also did not change anything in its config.

When I have any buffs/debuffs on my character it won't let me see the stars and the lens would go transparent, as if I were looking out through a window. 

- WITHOUT DEBUFF
![2022-02-11_01 55 20](https://user-images.githubusercontent.com/62324878/153549166-dc92991e-980b-479c-a425-2b51cab4bce7.png)
- WITH DEBUFF
![2022-02-11_01 55 30_LI](https://user-images.githubusercontent.com/62324878/153549204-d2ca9d1a-b51e-4163-95d8-1fe51d0c6eba.jpg)

This is on the sevtech ages modpack version SevTech_Ages_3.2.3.zip 

Version - astralsorcery-1.12.2-1.10.21.jar

**Comment by PocketfulOfGeese** [comment]
It means something isn't cleanly drawing a UI layer, not a shader issue.

1.12 is no longer under active Dev, however, not that there is much that could be done here with another mod's ui.
