### ISSUE TITLE
I'm unable to attune myself?

### ISSUE THREAD

**Issue by DarkyAlan** [HellFirePvP/AstralSorcery#193]
A friend on a server gave me the better telescope making me think that attunement is achievement bound. I've built the muiltiblock structure as instructed and am simply unable to get it to work at all

**Comment by DarkyAlan** [comment]
it occurs to me that if I could get the achievement ids I might be able to bypass the issue. server admin tried resetting my achievements and using the hand telescope to make the telescope or discovering new constellations didn't give me "What a beautiful pattern", I tried doing it legit in singleplayer and didn't have any issues but making the multiblock for attunement just won't work for me on the server

**Comment by HellFirePvP** [comment]
It's not tied to achievements.

You have to discover the constellation and build its relays as the positions are highlighted when holding the corresponding constellation paper in your hand while being near the active attunement altar. Also, you can only attune yourself to 'bright' constellations (you can see that in the book -> constellations when clicking on one of them). Also, be sure the attunement altar has a clear sight to the sky and the multiblock is correctly built.

**Comment by HellFirePvP** [comment]
Information never provided - reopen if you have the proper information.
