### ISSUE TITLE
Crashing with Mine Mine no Mi -  1.15.2

### ISSUE THREAD

**Issue by Himeki** [HellFirePvP/AstralSorcery#1931]
Tested with:
Forge-31.2.57
Mine Mine no Mi-1.15.2-0.7.2
Astral Sorcery-1.15.2-1.12.14
Curios-1.15.2-2.0.2.6
Observerlib-1.15.2-1.3.2

Used MultiMC. Confirmed working with each individually and in modpacks without each other.

With only the mods above, game crashes shortly after launching.

Unsure which mod would need to fix it.

[latest.log](https://github.com/HellFirePvP/AstralSorcery/files/8093030/latest.log)
[crash-2022-02-17_18.25.34-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/8093033/crash-2022-02-17_18.25.34-client.txt)

**Comment by PocketfulOfGeese** [comment]
Astral Sorcery isn't listed in that stack trace, needs to have a ticket opened with Mine Mine no Mi.
