### ISSUE TITLE
Fabric Port?

### ISSUE THREAD

**Issue by cjhickson647** [HellFirePvP/AstralSorcery#1932]
So I did a quick search of this repository. Someone about a year ago asked if you would make a 1.16 update for fabric. A lot can happen in a year. I am wondering if there are any plans since then to make a fabric port, maybe make one in the distant future, or never making a fabric port at all. I know that porting to fabric is not an easy task. But I just want to know the stance on this and if it has or will change in the future.

**Comment by PocketfulOfGeese** [comment]
It has not changed,will not be supported.

The discord server is the better place for these queries in the future.

**Comment by cjhickson647** [comment]
Cool thanks!
