### ISSUE TITLE
[Question] Creative build/structure for worldgen: How to make collector crystal unbreakable like default worldgen?

### ISSUE THREAD

**Issue by Flabort** [HellFirePvP/AstralSorcery#1934]
I am making a (private, for now) modpack with most of the worldgen disabled (read: skyblock). I want the starting area to have a collector crystal, but for it to be unbreakable like the ones in normal worldgen. 

Is there a command or creative way that I can accomplish this?

(Astral sorcery version: astralsorcery-1.16-1.16.5-1.13.12.jar)

**Comment by Flabort** [comment]
Update: I seem to have a partial solution on my own. Hopefully not too hacky:

`/setblock ~ ~-1 ~ astralsorcery:rock_collector_crystal{constellationType: {constellationNam:"astralsorcery:aevitas"},crystalProperties:{attributes:[{property:"astralsorcery:size",pLevel: 1},{property:"astralsorcery:purity",pLevel: 2},]}} destroy`

Although this does accomplish part of my goal, it's unbreakable, it doesn't accomplish the goal of being exactly like a worldgen crystal. I can't create the luminous crafting table.

**Comment by Flabort** [comment]
Oh I get it. Structure blocks in data mode. Just type the word crystal in. So much for something complicated.

**Comment by PocketfulOfGeese** [comment]
There's a flag on the world-gen crystals that sets indestructability and also the auto-link feature for creating the LCT, you'd have to pull the data on a world-gen crystal to see which is was, though, outside of using the structure blocks method.

**Comment by Flabort** [comment]
Well, now I know, thanks. Now I have a different issue - but it's not your mod, it's the Skyblock Builder mod by melanX. The structure saved right, but the data mode structure block didn't do the thing, it's still a structure block not a crystal.

**Comment by Flabort** [comment]
OK, sorry for the re-open, but I'm struggling here. The "data" mode apparently only works for the structure's it's programmed for - aka, "chest" data only works for certain structures. So the crystal data would apparently only work for the astral sorcery structures.

So I'm back to commands. Only, when I grabbed the data from a naturally generated crystal, I didn't see an particular data tags I didn't see on a placed one (thanks for thinking of that @Doomgull ), except for constellationType_present being 1 instead of 0. [Here's an image of the data command results side-by-side](https://imgur.com/uc2FQ11)

**Comment by Flabort** [comment]
OK, closing it again. I misspelled the constellationName tag, and once I fixed that and let it see the sky, everything worked, including auto-linking. :D

Just got to see if this continues to work once I export it. And... not initially. Huh, you have to cover it and uncover it to make it work. I guess that's because it spawns under the ground normally?
