### ISSUE TITLE
Forge send me two erros (observerlib)(curios)

### ISSUE THREAD

**Issue by WalyT248** [HellFirePvP/AstralSorcery#1937]
This is the error that forge sends
![2022-03-12](https://user-images.githubusercontent.com/101472991/158028858-6295e555-a936-4e00-9541-83f4b6333983.png)

**Comment by PocketfulOfGeese** [comment]
Please follow the directions in the error page, it is telling you that required mods are not installed. This is more a thing for the Discord server, not the github bug tracker.
