### ISSUE TITLE
Crash with TNTMinecratEntity on server

### ISSUE THREAD

**Issue by YaBoiChips** [HellFirePvP/AstralSorcery#1938]
[crash-2022-03-14_16.30.53-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/8248884/crash-2022-03-14_16.30.53-server.txt)

we get this when entering random chunks. we have killed all the tnt minecarts around and yet it still crashes

**Comment by PocketfulOfGeese** [comment]
This is not an Astral Sorcery caused issue. Please use vanilla server methods to clear erroring entities on server launch.
