### ISSUE TITLE
/reload crash (1.16)

### ISSUE THREAD

**Issue by blockgoblin31** [HellFirePvP/AstralSorcery#1943]
when I run /reload the game will sometimes crash

crash report:
https://pastebin.com/Q4M9SvTW

**Comment by blockgoblin31** [comment]
[modlist.txt](https://github.com/HellFirePvP/AstralSorcery/files/8467603/modlist.txt)
modlist

**Comment by PocketfulOfGeese** [comment]
That's a CME on a pillager, without enough indication on cause. I don't even know that AS touches those.

**Comment by blockgoblin31** [comment]
I've gotten it multiple times, on pillagers, armor stands, and sheep.

**Comment by PocketfulOfGeese** [comment]
Yup, but as a concurrent modification exception, it means more than one thing is trying to modify the entity. I really don't see how AS is triggering this with the information available, especially with the entities being cycled through when triggering a datapack reload command.

**Comment by blockgoblin31** [comment]
you are correct, it was advanced rocketry
