### ISSUE TITLE
Health Not Saved Between Sessions [1.16.5] [Bug]

### ISSUE THREAD

**Issue by CFlatFlat** [HellFirePvP/AstralSorcery#1944]
After relogging, if you have more than 20 health due to maximum life bonuses, it gets reset back to 20 and you need to regenerate your health again to get back to where you were before. I am also experience issue #1885, which is somewhat related.

Game Version: 1.16.5
Mod Version: 1.13.12

**Comment by PocketfulOfGeese** [comment]
Can you provide a screenshot of your perk tree?

Any other mods involved?

What forge version?

**Comment by CFlatFlat** [comment]
Forge Version: 36.2.22

Here's a list of included mods, though the only one I can see being related is Mantle:
[mod list.txt](https://github.com/HellFirePvP/AstralSorcery/files/8493279/mod.list.txt)

And a screenshot of my perk tree (my maximum health is 23):
![2022-04-14_20 45 43](https://user-images.githubusercontent.com/58796562/163504090-4a3ac332-06c9-4fbf-898e-d61a6e89f32f.png)
