### ISSUE TITLE
start up crash (1.12.2)

### ISSUE THREAD

**Issue by DerpShark** [HellFirePvP/AstralSorcery#1945]
Whenever I start up Minecraft, it crashes

[crash-2022-04-15_15.15.01-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/8497921/crash-2022-04-15_15.15.01-client.txt)

**Comment by PocketfulOfGeese** [comment]
"java.lang.NoClassDefFoundError"

Your java is out of date. Update the version of java your launcher is specifying to a more recent Java8 version, since it's currently using the default 1.8.0u51 shipped with MC.
