### ISSUE TITLE
Can't craft Stellar Refraction Table

### ISSUE THREAD

**Issue by RiQ4** [HellFirePvP/AstralSorcery#1948]
Unable to craft the Stellar Refraction Table. It appears un the altar. Right clicking with the wand only does some VFX and SFX for a fraction of a second. 
![Uploading 20220508_180710.jpg…]()

**Comment by PocketfulOfGeese** [comment]
The discord server is a better place for assistance, not the bug tracker.

Also, your image didn't properly upload.
