### ISSUE TITLE
[1.10.2] Marble stairs don't have a world model

### ISSUE THREAD

**Issue by bl4ckscor3** [HellFirePvP/AstralSorcery#195]
When placing them down, they look like [this](http://i.imgur.com/51Rujhp.png). This happens with upside-down and cornered stairs, too. I am using the mod within the All The Mods modpack, but I have tested it with only the mod and Forge installed, and the issue happens, too

**Comment by HellFirePvP** [comment]
derp. 1.10.2 only.

**Comment by MJRLegends** [comment]
@HellFirePvP This doesnt seem to be fixed AstralSorcery-1.10.2-1.4.4, was it not fixed or did it just get missed out the update
