### ISSUE TITLE
Items drop from your inventory when you click on them due to some condition in the game. [Bugs] [1.12.2]

### ISSUE THREAD

**Issue by GauntBurrito114** [HellFirePvP/AstralSorcery#1950]
I was making an AstralSorcery item. When I tried to put the item in the chest, when I shift+right click on the item, the item dropped out of my inventory. Logging in again does not resolve the issue. I created a new world and tried to find out under what conditions this happens, but couldn't find anything like this.

**Comment by PocketfulOfGeese** [comment]
There is nothing in the AS code that would alter or effect this.

What other mods are in-use?

Also 1.12 isn't supported anymore.
