### ISSUE TITLE
New version of 1.16.5 Crashes on start

### ISSUE THREAD

**Issue by BedrockLegends** [HellFirePvP/AstralSorcery#1952]
I updated this mod in my custom modpack and it crashed due to mixin crash
[crash-2022-05-31_16.00.11-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/8809435/crash-2022-05-31_16.00.11-client.txt)

**Comment by BedrockLegends** [comment]
Another issue I should mention is that we have noticed any mods using forge:workbenches or forge:workbench doesn't seem to work when put said crafting table with those tags under a crystal. I have tested this with Blue Skies crafting Tables and a few other mods as well

**Comment by PocketfulOfGeese** [comment]
The bench thing is not new, and has always been that way.

**Comment by BedrockLegends** [comment]
> The bench thing is not new, and has always been that way.

Anyway to fix that, I try to do it myself through Kubejs and it does not work

**Comment by HellFirePvP** [comment]
Since another mod modifies the default entity reach constant there and is not using mixins to do that, it's not straightforward to find out which one causes this incompatibility.
Please try and binary-search for which mod causes this.

**Comment by BedrockLegends** [comment]
@HellFirePvP The only thing I see before the crash is this [16:00:11] [main/WARN]: @ModifyConstant conflict. Skipping assets/astralsorcery/astralsorcery.mixins.json:client.MixinGameRenderer->@ModifyConstant::getOverriddenCreativeEntityReach(D)D with priority 1000, already redirected by tombstone.mixins.json:GameRendererMixin->@ModifyConstant::pickCreative(D)D with priority 1031 Idk if this is what you mean

**Comment by PocketfulOfGeese** [comment]
A binary search involves taking out half the mods (careful of the dependencies), and validating if it still occurs. If it does not, then the mod causing the issue is in the half that was removed. You then put the "problem" group in, and cut out half of those mods, and keep repeating this until you've narrowed it down to the mod causing the issue. This makes it far faster to check than removing mods one at a time.

**Comment by BedrockLegends** [comment]
@Doomgull That is going to be super hard, for the fact we got 425 mods in our pack

**Comment by PocketfulOfGeese** [comment]
and assuming none of those are library mods, or weird sub-mods, that's still 5 attempts to narrow it down to ~12 mods. It's why a binary search is so much faster than doing it one at a time.

**Comment by HellFirePvP** [comment]
> @HellFirePvP The only thing I see before the crash is this [16:00:11] [main/WARN]: @ModifyConstant conflict. Skipping assets/astralsorcery/astralsorcery.mixins.json:client.MixinGameRenderer->@ModifyConstant::getOverriddenCreativeEntityReach(D)D with priority 1000, already redirected by tombstone.mixins.json:GameRendererMixin->@ModifyConstant::pickCreative(D)D with priority 1031 Idk if this is what you mean

WELL that helps a lot.

**Comment by BedrockLegends** [comment]
> > @HellFirePvP The only thing I see before the crash is this [16:00:11] [main/WARN]: @ModifyConstant conflict. Skipping assets/astralsorcery/astralsorcery.mixins.json:client.MixinGameRenderer->@ModifyConstant::getOverriddenCreativeEntityReach(D)D with priority 1000, already redirected by tombstone.mixins.json:GameRendererMixin->@ModifyConstant::pickCreative(D)D with priority 1031 Idk if this is what you mean
> 
> WELL that helps a lot.

Removed Corail so it's not that, I don't have a lot of time to spend taking 425 mods out to see what's causing it. I guess we will have to wait and see if someone else post the same crash

**Comment by HellFirePvP** [comment]
It is corail's tombstone though.
If the same thing still occurs, then there should be another warning, mentioning a different mod in that case

**Comment by BedrockLegends** [comment]
[crash-2022-05-31_16.33.30-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/8809604/crash-2022-05-31_16.33.30-client.txt)
After removing Corail I got a crash from xReliquary, it seems like its multiply amounts of mods crashing

**Comment by BedrockLegends** [comment]
We will just go back to using the beta version till it gets fixed

**Comment by PocketfulOfGeese** [comment]
It's not an astral sorcery thing to fix, need to go report to those mods for improperly modifying it.

**Comment by Diversion98** [comment]
I have it in my modpack as well

If I disable reliquary, the new update works
but otherwise it crashes on startup

**Comment by Zelceus** [comment]
I found a weird interaction with Reliquary Reincarnations.  After updating some mods, I started getting these crashes myself from these updates. I then I started to disable the mods I updated, which included Astral Sorcery, it worked.  Then I was reading the logs and getting Reliquary compatibility issues with some Void item or something. I then disabled Reliquary, enabled Astral, and it worked like a charm.  So I guess there's a compatibility issue with these mods over an item? I'll attach the log with it.

[crash-2022-06-01_00.05.51-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/8811849/crash-2022-06-01_00.05.51-client.txt)

**Comment by Diversion98** [comment]
> I found a weird interaction with Reliquary Reincarnations. After updating some mods, I started getting these crashes myself from these updates. I then I started to disable the mods I updated, which included Astral Sorcery, it worked. Then I was reading the logs and getting Reliquary compatibility issues with some Void item or something. I then disabled Reliquary, enabled Astral, and it worked like a charm. So I guess there's a compatibility issue with these mods over an item? I'll attach the log with it.
> 
> [crash-2022-06-01_00.05.51-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/8811849/crash-2022-06-01_00.05.51-client.txt)

I reported the issue on the reliquary github as well :)
https://github.com/P3pp3rF1y/Reliquary/issues/574

**Comment by Zelceus** [comment]
> > I found a weird interaction with Reliquary Reincarnations. After updating some mods, I started getting these crashes myself from these updates. I then I started to disable the mods I updated, which included Astral Sorcery, it worked. Then I was reading the logs and getting Reliquary compatibility issues with some Void item or something. I then disabled Reliquary, enabled Astral, and it worked like a charm. So I guess there's a compatibility issue with these mods over an item? I'll attach the log with it.
> > [crash-2022-06-01_00.05.51-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/8811849/crash-2022-06-01_00.05.51-client.txt)
> 
> I reported the issue on the reliquary github as well :) [P3pp3rF1y/Reliquary#574](https://github.com/P3pp3rF1y/Reliquary/issues/574)

Nice, hopefully we can see a hotfix coming soon. If not, I'm fine with waiting and using older versions.
