### ISSUE TITLE
Astral Sorcery 1.12 Aevitas ritual attunement bug.

### ISSUE THREAD

**Issue by ghost** [HellFirePvP/AstralSorcery#1955]
![2022-06-05_16 31 53](https://user-images.githubusercontent.com/98679434/172047754-32fa6327-40bd-49de-a77d-ffe7d6664668.png)
Im trying to attune some crystals to aevitas but the game says i need to place the last relay in the spot where the altar is. Im 100% sure the other relays are in the right place

**Comment by PocketfulOfGeese** [comment]
The altar is a relay itself.
