### ISSUE TITLE
Horologium ritual does nothing and particles persist after ritual taken down.

### ISSUE THREAD

**Issue by snydej** [HellFirePvP/AstralSorcery#1958]
I set up a Horologium ritual with what I believe to be a maxed out configuration (The ritual crystal is Purity 2, Shape 3, Ritual Effect 3, Focus: Horologium 2, Tunned to Horologium, Trait of Ulteria. I linked a collector crystal to it, which had the enhanced celestial crystal multiblock built under it and whose stats are: Size 2, Purity 2, Shape 3, Collection Rate 1, Focus: Horologium 2, Collects starlight from Horologium and I set up the 5 lenses, all max stats themselves, at the ends of the rays of light). I tried to measure its effect with a stopwatch on something I know is affected by Time in a Bottle and I couldn't measure any change.

I tore down everything associated with the ritual but now I'm noticing that the purple particles that the ritual was making are still there and this is after I've closed and relaunched the game

![particles](https://user-images.githubusercontent.com/2817309/174680635-73bff6f5-d47d-48ee-ae36-842b7d0bbfac.png)

I'm playing on the ATM6 mod pack which is using version 1.16.5-1.13.12 of Astral Sorcery.

**Comment by snydej** [comment]
It's so much worse at night...

![2022-06-20_15 12 16](https://user-images.githubusercontent.com/2817309/174683647-bfc3939f-0769-4d25-8edd-8cd0ca4111fa.png)

**Comment by PocketfulOfGeese** [comment]
Update the mod.
