### ISSUE TITLE
Crafttweaker 1.12.2 Question.

### ISSUE THREAD

**Issue by NaveGamer** [HellFirePvP/AstralSorcery#1964]
Well, hello there. I have an little problem with crafting table + starlight recipes. There is an Luminous Altar compability, but no simple crafting tablle + starlight one. Since that variation of crafting is just vanila crafting table, i don't know what kind of thing i should do, for add the need for an starlight in that kind of recipe. For an example, there is a classic crafttweaker recipe for an crafting table:

recipes.addShaped(<astralsorcery:itemwand> [
[null, <ore:gemAquamarine>, <botania:manaresource:1>,
null, <botania:manaresource:13>, <ore:gemAquamarine>,
<botania:manaresource:3>, null, null]]);

And i need, to somehow add there is a need for an starlight. That one, that need for the original craft of the Resonating Wand. Anyone know, how to do it? I'm will be really, really appreciate you, if someone help me with it.

P.S. I'm sorry if my text is a little bit incorrect, english is not my native language

**Comment by DungeonBuffalo** [comment]
Hi, read this carefully, all expained: https://docs.blamejared.com/1.12/en/Mods/Astral_Sorcery/Altar

**Comment by NaveGamer** [comment]
> Hi, read this carefully, all expained: https://docs.blamejared.com/1.12/en/Mods/Astral_Sorcery/Altar

But there is an Altar recipes. I need not that thing. I need workbench recipe that needs a starlight, from the crystal. (That one type of recipes, that needs to create first things, from this mod, like wand or altar itself)

**Comment by PocketfulOfGeese** [comment]
There is no way to create a recipe that needs starlight using a normal crafting table through astral sorcery.

**Comment by NaveGamer** [comment]
> There is no way to create a recipe that needs starlight using a normal crafting table through astral sorcery.

Eh, sad. But thank you for the answer.
