### ISSUE TITLE
Common Config File only has World Gen info in it

### ISSUE THREAD

**Issue by DragonFeyAni** [HellFirePvP/AstralSorcery#1967]
Version 1.16.5 - 1.14.1

I wanted to adjust the config file to increase the level cap to 100 but when I went to look at it the only info the common config file had was about worldgen. There's zero information about levels, perks, or anything else astral sorcery related. Am I missing a file or is my file corrupted? I've looked every where to see if there's a config file elsewhere but nope, this is all I can find.

Below is all that's in my config:

<details><summary>astralsorcery-common</summary>
<p>

[worldgen]

	[worldgen.small_shrine]
		#Sets the categories to generate this feature in. Available categories: none,taiga,extreme_hills,jungle,mesa,plains,savanna,icy,the_end,beach,forest,ocean,desert,river,swamp,mushroom,nether
		biomeCategoryNames = ["forest", "plains"]
		#Sets the worlds to generate this feature in. (Does NOT work for structures!)
		worldNames = ["overworld"]
		#Defines the structure spacing for worldgen
		#Range: 1 ~ 512
		spacing = 18
		#Defines the structure separation for worldgen
		#Range: 1 ~ 512
		separation = 4
		#Set this to true to let this feature generate in any biome.
		everyBiome = false
		#Set this to true to let this feature generate in any world. (Does NOT work for structures!)
		everyWorld = false
		#Set this to false to disable this worldgen feature.
		enabled = true

	[worldgen.marble]
		#Sets the categories to generate this feature in. Available categories: none,taiga,extreme_hills,jungle,mesa,plains,savanna,icy,the_end,beach,forest,ocean,desert,river,swamp,mushroom,nether
		biomeCategoryNames = []
		#Sets the worlds to generate this feature in. (Does NOT work for structures!)
		worldNames = []
		#Set this to true to let this feature generate in any biome.
		everyBiome = true
		#Set this to true to let this feature generate in any world. (Does NOT work for structures!)
		everyWorld = true
		#Set this to false to disable this worldgen feature.
		enabled = true

	[worldgen.glow_flower]
		#Sets the categories to generate this feature in. Available categories: none,taiga,extreme_hills,jungle,mesa,plains,savanna,icy,the_end,beach,forest,ocean,desert,river,swamp,mushroom,nether
		biomeCategoryNames = ["icy", "extreme_hills"]
		#Sets the worlds to generate this feature in. (Does NOT work for structures!)
		worldNames = ["overworld"]
		#Set this to true to let this feature generate in any biome.
		everyBiome = false
		#Set this to true to let this feature generate in any world. (Does NOT work for structures!)
		everyWorld = false
		#Set this to false to disable this worldgen feature.
		enabled = true

	[worldgen.aquamarine]
		#Sets the categories to generate this feature in. Available categories: none,taiga,extreme_hills,jungle,mesa,plains,savanna,icy,the_end,beach,forest,ocean,desert,river,swamp,mushroom,nether
		biomeCategoryNames = []
		#Sets the worlds to generate this feature in. (Does NOT work for structures!)
		worldNames = ["overworld"]
		#Set this to true to let this feature generate in any biome.
		everyBiome = true
		#Set this to true to let this feature generate in any world. (Does NOT work for structures!)
		everyWorld = false
		#Set this to false to disable this worldgen feature.
		enabled = true

	[worldgen.desert_shrine]
		#Sets the categories to generate this feature in. Available categories: none,taiga,extreme_hills,jungle,mesa,plains,savanna,icy,the_end,beach,forest,ocean,desert,river,swamp,mushroom,nether
		biomeCategoryNames = ["mesa", "desert", "savanna"]
		#Sets the worlds to generate this feature in. (Does NOT work for structures!)
		worldNames = ["overworld"]
		#Defines the structure spacing for worldgen
		#Range: 1 ~ 512
		spacing = 18
		#Defines the structure separation for worldgen
		#Range: 1 ~ 512
		separation = 4
		#Set this to true to let this feature generate in any biome.
		everyBiome = false
		#Set this to true to let this feature generate in any world. (Does NOT work for structures!)
		everyWorld = false
		#Set this to false to disable this worldgen feature.
		enabled = true

	[worldgen.ancient_shrine]
		#Sets the categories to generate this feature in. Available categories: none,taiga,extreme_hills,jungle,mesa,plains,savanna,icy,the_end,beach,forest,ocean,desert,river,swamp,mushroom,nether
		biomeCategoryNames = ["icy", "extreme_hills"]
		#Sets the worlds to generate this feature in. (Does NOT work for structures!)
		worldNames = ["overworld"]
		#Defines the structure spacing for worldgen
		#Range: 1 ~ 512
		spacing = 18
		#Defines the structure separation for worldgen
		#Range: 1 ~ 512
		separation = 4
		#Set this to true to let this feature generate in any biome.
		everyBiome = false
		#Set this to true to let this feature generate in any world. (Does NOT work for structures!)
		everyWorld = false
		#Set this to false to disable this worldgen feature.
		enabled = true

	[worldgen.rock_crystal]
		#Sets the categories to generate this feature in. Available categories: none,taiga,extreme_hills,jungle,mesa,plains,savanna,icy,the_end,beach,forest,ocean,desert,river,swamp,mushroom,nether
		biomeCategoryNames = []
		#Sets the worlds to generate this feature in. (Does NOT work for structures!)
		worldNames = ["overworld"]
		#Set this to true to let this feature generate in any biome.
		everyBiome = true
		#Set this to true to let this feature generate in any world. (Does NOT work for structures!)
		everyWorld = false
		#Set this to false to disable this worldgen feature.
		enabled = true

</p>
</details>

**Comment by PocketfulOfGeese** [comment]
Yes, you want astralsorcery.toml. it will be either in the defaultconfigs directory, or the world save configs directory, as it is a server config.

In the future, the discord is a better place for questions like this.
