### ISSUE TITLE
[1.16.5-1.14.2] Attempting to attack an invalid entity

### ISSUE THREAD

**Issue by Rimilik** [HellFirePvP/AstralSorcery#1968]
Hello, 
when processing star metal on the server, the player kicks with the reason:
"Rimil lost connection: Attempting to attack an invalid entity".

I checked in a single game, everything works fine, it doesn't kick.

Also tested on two cores: Mohist and CatServer. 
The outcome is the same, kick from the server.

As an example, I attach a screenshot from the Mohist core:
![image](https://user-images.githubusercontent.com/77163750/187205677-1f7db2d1-24e0-4712-9615-d86801631834.png)

I also want to note that everything works stably on the mod version 1.13.12.

I apologize if there are errors here, I used a translator. <3

**Comment by PocketfulOfGeese** [comment]
Bukkit/Spigot/etc are not supported by this mod, which both those server hosting types include as part of their deployment.
