### ISSUE TITLE
[1.11.2] new frontier modpack, cant use chisel marble as multiblock structure

### ISSUE THREAD

**Issue by Gayanfalor** [HellFirePvP/AstralSorcery#197]
Helo, i was doing some Astral sorcery  things as its a new mod for me but when upgrading my altar to celestial altar and upgrading the multiblock structure i was asking to me why its red and not working.

It was because the multiblock doesnt accept chisel marble as part of the structure, it only accept AS marble that we cant craft , only get from ruins.

I was thinking it could be nice that we could craft it ( but perhaps its from the modpack)

**Comment by HellFirePvP** [comment]
Yea. well. the multiblocks specifically require AS marble. Might change it at some point so it's more lenient with the raw-marble to accept any marble that has an item that also is oredicted to 'blockMarble' or 'stoneMarble' - regardless, this is not really a bug. And if the only way to get the specific marble is by tearing down structures in your pack, then it's the pack author's fault.

**Comment by Gayanfalor** [comment]
ah ok thanks, btw i have another problem with the mod but i think it could be only visual.

its wit the sharpening with the grindstone, i sharpend a sword and now its shows less dmg than before sharpening

**Comment by HellFirePvP** [comment]
? Ok? idk where that'd be coming from though.. even if, i'm certain it's only visual though. Will give it a look
