### ISSUE TITLE
Celestial Gateway not working properly

### ISSUE THREAD

**Issue by TheStarMagus** [HellFirePvP/AstralSorcery#1972]
So when I go onto the platform I made for the gateway, it does the fade and everything to show the stars and what not. The kicker is that it doesn't show any of the colored stars meant for travel. I know there are some when I look through a sextant within the boundaries of the gateway, but without the apparatus I don't see them and I can't crouch to try to travel to it either even though I know the location of one of the colored stars. I'm just a little lost as to what to do.

**Comment by PocketfulOfGeese** [comment]
Have to stand on the gateway block itself, not the platform as a whole.

Discord server is the better place for these types of operational questions.
