### ISSUE TITLE
Disable Iron Ore > Starmetal Ore

### ISSUE THREAD

**Issue by Blueberrypie255** [HellFirePvP/AstralSorcery#1978]
I added a custom recipe for starmetal ore; how do I remove the way iron turns into starmetal?

**Comment by ZZZank** [comment]
try datapack. the origional recipe is in astralsorcery\data\astralsorcery\recipes\block_transmutation\iron_starmetal.json.

**Comment by Blueberrypie255** [comment]
What do you mean datapack? I cannot find the data folder in the config file

**Comment by Blueberrypie255** [comment]
Also I am in V1.12.2

**Comment by ZZZank** [comment]
> Also I am in V1.12.2
> 

Oh, I don't expected that. The datapack was added to vanilla in 1.13, so 1.12 cannot use that. 
How about removing it using CraftTweaker? https://docs.blamejared.com/1.12/en/Mods/Astral_Sorcery/Transmutation

**Comment by Blueberrypie255** [comment]
ty
