### ISSUE TITLE
Attuned myself to constellation and now mobs aren't attacking me (multiplayer)

### ISSUE THREAD

**Issue by Spierex** [HellFirePvP/AstralSorcery#1979]
Hi all. I'm using the modpack Better MC 1.16.5 but I wanted to try astral sorcery so I added it to the modpack and put it on a server. When I came to attune myself to discidia, it kept crashing so I used cheats to attune myself. Then I went to kill some mobs to level up and noticed they weren't attacking me at all

any ideas?

**Comment by PocketfulOfGeese** [comment]
Are...you in creative mode still?

Nothing in AS does that, so need to look elsewhere for the cause.

**Comment by Spierex** [comment]
@Doomgull Nope I'm in survival, I made sure. I'm puzzled tbh. Why would mobs just start ignoring me?

**Comment by Spierex** [comment]
@Doomgull are you completely sure Astral Sorcery has nothing to do with this? this only occurred when I was doing Astral Sorcery stuff. I'm wondering whether it has anything to do with the Attunement animation as it kept crashing every time I attempted it. Do mobs become passive towards you during the Attunement animation?
