### ISSUE TITLE
Could I be so rude as to...

### ISSUE THREAD

**Issue by Dylan4ever** [HellFirePvP/AstralSorcery#2]
... ask when you think there will be a proper release? I have been very hyped for this mod ever since I first saw it on the FTB sub and all. If you have no idea or don't want to give an ETA, no problem, I shall wait in peace then.

**Comment by HellFirePvP** [comment]
Monday 13th

**Comment by Jomik** [comment]
This year? February, March or November then? :p Mod looks amazing.
