### ISSUE TITLE
Uploaded 1.10.2 to 1.11.2 on curse

### ISSUE THREAD

**Issue by Dominance** [HellFirePvP/AstralSorcery#201]
Could just be me but I am pretty sure both the 1.11.2 and 1.10.2 versions are the same and is the 1.10.2 version

**Comment by HellFirePvP** [comment]
They are not the same.

**Comment by Dominance** [comment]
Yeah ether file was giving me the you need minecraft 1.10.2, Found it odd as I did do a MD5 check and they where not the same file that is for sure.
