### ISSUE TITLE
Ritual Anchor Effect, Still Active After Anchor Removed

### ISSUE THREAD

**Issue by Skid-Inc** [HellFirePvP/AstralSorcery#204]
The title says it all, but the video shows it in effect, the regeneration buff from the Aevitas constellation is gone but the Ender Lillys are still getting the green partial effects that are making them grow. This is shown about 6 minutes into the video.

https://www.twitch.tv/videos/153244516

I just tested this with normal crops, and it's doing the same.

Minecraft 1.10.4
Astral Sorcery 1.4.1
Playing on my private server sole, using the All The Mods pack.

**Comment by HellFirePvP** [comment]
Caching mistake, will be fixed.

**Comment by HellFirePvP** [comment]
Adressed with https://github.com/HellFirePvP/AstralSorcery/commit/c97792edf857a8ba3eeded580029fb4dc9d21faa

**Comment by HellFirePvP** [comment]
Adressed with the 1.4.3 update.
