### ISSUE TITLE
1.10.2-1.4.3 Crash on startup

### ISSUE THREAD

**Issue by Kashdeya** [HellFirePvP/AstralSorcery#206]
Just add the mod to my pack and I am getting a ASM crash. 

https://pastebin.com/ik21gmp3

I can repeat the issue over and over and is only fixed if I remove the mod.

**Comment by HellFirePvP** [comment]
This is not an ASM crash.

And idk what registry entry causes this as it doesn't happen for me atm. I'll see to it

**Comment by HellFirePvP** [comment]
Can't reproduce in any way. try with only AS and Forge?

**Comment by HellFirePvP** [comment]
Information never provided.
