### ISSUE TITLE
Compatibility problem with one mods.

### ISSUE THREAD

**Issue by Lagominer** [HellFirePvP/AstralSorcery#207]
Minecraft 1.10.2
Crash when trying to download a ready-made world with mod "CustomMobSpawner".
Can you do something to make the astral support this mod? It is very important for my assembly.
https://pastebin.com/TH0SHAzY

**Comment by HellFirePvP** [comment]
Idk what that mod does or how it works or why it crashes. It's not on my end to do something about this.
