### ISSUE TITLE
Crash with ritual pedestal

### ISSUE THREAD

**Issue by gchpaco** [HellFirePvP/AstralSorcery#208]
I found this with Astral Sorcery 1.4.3, which appears to be current.  Placed down a ritual pedestal and boom, very quickly afterwards.  It did not have a crystal in it at the time, although I had laid out the marble supporting structure.

[crash-2017-06-24_06.22.26-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/1099632/crash-2017-06-24_06.22.26-server.txt)

**Comment by HellFirePvP** [comment]
That's an oversight on my end, which will basically cause any server that loads this to crash immediately... Fixed it and 1.11.2 and 1.10.2 versions that fix this are being uploaded to CF as i write this. Expect a useable release in a few minutes after it's been approved.

**Comment by HellFirePvP** [comment]
1.12 will follow later today or tomorrow. Several changes i made internally are not finished and building it now would do more harm than good.

**Comment by justicesays** [comment]
hey @HellFirePvP , I built a 1.10.2 release from the github branch (I back-ported some features, but wanted to stay on 1.10.2 for now) , but it has this crash (issue #208)  . I don't see any commits to the 1.10.2 branch on of after this date that would fix it. Did you fix it locally and not upload the code fix to the 1.10.2 branch? Could I get the fix please if possible?

**Comment by HellFirePvP** [comment]
AS is licenced as ARR so i will not support an action that i deem illegal, especially without my prior consent.
