### ISSUE TITLE
1.12 Crash on Startup

### ISSUE THREAD

**Issue by Izrith** [HellFirePvP/AstralSorcery#209]
Tried with both normal modlists and with only AS and Forge. Both crash while loading with a -1 error.

https://pastebin.com/Es298Cew This is a pastebin of the crashlog it left behind.

No idea what causes it since it was working fine a few days ago.

**Comment by HellFirePvP** [comment]
Forge has changed its registration system if you didn't notice that being discussed lately.

Issues like this are the result of these changes - and i suspect more mods than just mine experience issues. Use a bit of an older forge version to run it or wait 1-2 days for me to finish what i'm working on and then redo registration.

**Comment by HellFirePvP** [comment]
Updated AS to the new registry system of forge. 1.5.4 is runnable with the newer forge versions for 1.12
