### ISSUE TITLE
[Suggestion] sky block compatibility

### ISSUE THREAD

**Issue by wizard1399** [HellFirePvP/AstralSorcery#211]
Hey,
I am putting together a magic based skyblock modpack. I want to include your mod, but have a few questions first.

1) Do the worldgen structures generate in other dimensions beside the over world?

2) Could you add an item that when right clicked would generate a structure that skyblock players could use to get started with the mod.  Pack makers could either create a recipe for this item or have it drop from some mob in the skyblock.  By defualt this item would not be obtainable unless the packmaker  made a way to give the item to the player.

**Comment by HellFirePvP** [comment]
1. read the config.

2. no, because the structure can be crafttweaker'd around. the recipes that need to be added/changed so you don't need a structure: resonating wand, luminous crafting table - and you need to give the player a way to get starmetal ore.
