### ISSUE TITLE
1.12 Freeze on World Load

### ISSUE THREAD

**Issue by Izrith** [HellFirePvP/AstralSorcery#212]
I was creating the second tier starlight crafting table, which I cannot for the life of me remember the name of. It was the one right after the luminous altar, where it transforms the luminous one into the next tier. IMMEDIATELY upon finishing the 'building' animation it has, the game crashed. After that, any attempts to load the world result in an immediate freeze right after the world loads.

https://pastebin.com/iHE1NYmu

**Comment by HellFirePvP** [comment]
Update to the latest version.
