### ISSUE TITLE
[Suggestion]About Floating Crystal

### ISSUE THREAD

**Issue by YiChenCraft** [HellFirePvP/AstralSorcery#213]
I want to make a sky block modpack,Want to join your mod.But I copied the floating crystal can not activate the crafting table.

1.Can be generated in the air ancient shrines?Preferably through the config control

2.Can let the copy out of the floating crystal can be activated crafting table?

**Comment by wizard1399** [comment]
There is a player craftable version that comes later in the mod. Try replacing this on your starting island. Added bonus, once players get high enough tier pick, they can move it to a more convenient location.

**Comment by Doomgull** [comment]
Archiving. Player craftable floating crystals are a thing, and a linking wand lets you link the creatively placed creative crystals to a crafting table anyhow. Not really anything else here as a suggestion at this point.
