### ISSUE TITLE
Can't re-attune

### ISSUE THREAD

**Issue by SPYROHAWK** [HellFirePvP/AstralSorcery#214]
So this is very likely that this is just a problem with me, but I am testing out the mod in creative mode (but still crafting most of the things for progression) and I got to the attunment phase. I was trying to attune a rock crystal and I accidentally ended up attuning myself to Aevitas.

No big problem, I hung around with it for a while until I found Horologium. So I grabbed a Shiftig Star out of creative to unattune myself, and tried to attune myself to Horologium. Well, I got unattune, but I could not attune myself to the new constellation. I tried with Fornax too, nothing. Long story short, you can't reattune yourself after using the shifting star (or at least I can't).

I tried relogging and whatnot. Is this a bug that needs to be fixed or am I just screwing something up?

(Also I don't know if this is how you are supposed to format a bug report, this is my first time making one of these)

**Comment by HellFirePvP** [comment]
the Shifting star is a thing. and you can only attune yourself to bright/major constellations - i believe that's vaguely mentioned.

**Comment by SPYROHAWK** [comment]
Oh, my mistake. I read through the attunment page several times and I don't remember it mentioning that. That explains the problem
