### ISSUE TITLE
Minecraft 1.10.2 - Version 1.4.4: Entire UI bugs out after reading the "knowledge" section of the journal

### ISSUE THREAD

**Issue by Trawetsmail** [HellFirePvP/AstralSorcery#215]
After reading the "knowledge" part of the journal, and entering one of the galaxies for information, the crosshair, and for that matter, the entire UI becomes white squares. The only thing that I've found can fix this, aside from reloading the game, is to load another texture pack, then load the desired one again. However, as one can imagine, it is very annoying having to reload texture packs every time I have to read the journal.

**Comment by HellFirePvP** [comment]
Most likely #72
