### ISSUE TITLE
[Bug] [Beta 1.10] Iron Ore not Transforming into StarMetal. 

### ISSUE THREAD

**Issue by Ayrrow** [HellFirePvP/AstralSorcery#22]
Had this setup for 22minutes now, not transforming. Iron Ore is giving off particles without issue. 

Both Crystal and Iron have unobstructed view of the sky.

![2017-02-18_20 01 13](https://cloud.githubusercontent.com/assets/7918443/23091951/1494a2fc-f615-11e6-8d11-29a42caab9d6.png)

Updating to latest version on Curse does not fix this issue.

**Comment by HellFirePvP** [comment]
I suspect the crystal is just collecting a super small amount of starlight. The block emitting particles is the proof that it indeed *does* work. _otherwise there wouldn't be particles in the first place._ Try placing the crystal in an area that gets much starlight (sky wave resonator), try use a collector crystal with bigger size and higher purity.

**Comment by Ayrrow** [comment]
This is a crystal from an Ancient Shrine. I can't move it, since I can't get star metal I can't build a collector crystal to place in starlight

**Comment by HellFirePvP** [comment]
Can the crystal in the shrine see the sky?

**Comment by Ayrrow** [comment]
Yes.

**Comment by HellFirePvP** [comment]
Guess i'll flag that as 'design issue' since the collector crystal in the shrine is also affected by randomness in properties. I'll buff its collection rates and try make it a bit of a more stable source in the next update...

**Comment by Ayrrow** [comment]
Thanks

**Comment by HellFirePvP** [comment]
The integrity check is nothing that will resolve missing or misbehaving network nodes. It will clear the ones that lost their corresponding tileentity.

**Comment by Ayrrow** [comment]
Just out of curiosity, how long approx does it take? I cheated in two starmetal ore and have now built a collector crystal of my own, placed in strong starlight... size 308 crystal.

**Comment by HellFirePvP** [comment]
https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/starlight/network/handlers/StarmetalFormHandler.java

13000 'charge' - assuming your 308size crystal would have 100 purity and 100 cutting, it'd generate a bit less than 3 charge a tick. divide/multiply that down with the current day/night cycle percentage and the percentage for your current starlight distribution (the wave resonator thing) you might end up with about less than 1,5/t or so...

**Comment by HellFirePvP** [comment]
Hence the Journal entry says "leave it there for some time" - the 'some time' referencing to, you might want to do something else in the meantime. The mod is, as it was stated somewhere i can't remember where, not rly supposed to be played on its own without any other mods as the day/night cycle and other things require time and stop you from progressing from 0 to everything in less than 1 hour.

**Comment by HellFirePvP** [comment]
_Significantly_ lowered the amount of starlight required for this.
