### ISSUE TITLE
Suggestion - Consume gems/crystals with well only during the night

### ISSUE THREAD

**Issue by rinart73** [HellFirePvP/AstralSorcery#220]
Currently when you place aquamarine/rock crystal on the Well it will consume gem even if it's currently a day. Can it be delayed? So I will place the gem and the well will consume it only at night.

**Comment by HellFirePvP** [comment]
No i will not make up for a user's non-understanding that 1) nighttime is better and 2) that using the starlight network will benefit you greatly day and night.

**Comment by rinart73** [comment]
I know that nighttime is better. I just need to be both at my base filling wells with aquamarine's and far from it, searching for rock crystals.

By the way, it would be great to open a F.A.Q. or something, because no one who did a review/tutorial on your mod can't properly explain certain things. Like a starlight network. Or why it's a good idea to use a bunch of costly lenses to transfer starlight from floating crystal to your base. You need to place a lense every 12-13 blocks. That's just non-profitable.

**Comment by Doomgull** [comment]
Automation.

**Comment by HellFirePvP** [comment]
Well, you don't need to put up a line of lenses between a shrine and where your base is.

And yes, automation is a thing, secondly, the mod generally has a design of 'sacrifice more resources, get more out of it' - now i know this isn't tooooo consistent, however it's certainly true for gem/crystal -> liquid starlight production..

I am very aware that the book is cryptic at parts, but i don't want to just flat out remove all flavour from the book, which i do if i just flat out always write what it does 100%.

**Comment by rinart73** [comment]
So what's the point of lenses then? They only can redirect starlight from a floating gem to a lense and from lense to lense.

That's why I'm suggesting to make some mod community. A channel in the Discord or forum. If people don't understand, they will ask. I don't think that it's useful for you to have a mix of Suggestions, Questions and Issues there.

As of automation I don't get how it can be applied to your mod. I even heard that there is a way to put gems automatically in the well and extract buckets of liquid light, but have no idea. In any cause I don't think it's relevant for me or most of the players until I get 90% of the mod done.

**Comment by HellFirePvP** [comment]
You can direct starlight onto a block, lightwell, ritual pedestal, altar, use the colored lenses, accelerate the tree beacon, ... You're not _forced_ to use them, but you have the very option to do so if you want.

> They only can redirect starlight [...] from lense to lense.

Very much no. They can do the same as if you'd link the collector crystal directly to a receiver. It's basically a way to extend the 'reach' of a collector crystal. ALSO it's not as expensive as you might think.. If you read the book, you might've noticed that you get more lenses the higher the size-stat on the crystal used is/was.

Sure, i'd do so, but my community is negligibly small... So i don't think it'd be worth setting up anything for it anyway.

And i do admit, there are a lot of things that are not obvious to automate, however there are others that are specifically made easy for automation, like the rituals cast by the Ritual Pedestal

**Comment by rinart73** [comment]
Well yeah, you can transmutate some blocks, but I tried to redirect starlight to the altar. It doesn't add anything. As for other options, thanks for explaining.

I get 4 lenses from the crystal with purity 90% and weight 380. I suppose 4 lenses is maximum amount for a simple rock crystal (which has maximum weight of 400, that can be achieved dropping rock crystal in the liquid light).
But its not that easy to find a good Rock Crystal. And finding Rock Crystals in basic is a pain (I know how to find them, but digging a loong tunnels down to the bedrock is kinda time consuming. The only thing that saves me is that my server has "/home" command.
And considering that huge temples are not spawning that often (I'm not going to change this in the configs because I think that it's normal and works as intented) you need a lot of lenses to get small benefit from distant floating crystal. For example the distance to the nearest big temple for me is 300 (according to the marker mod).
You said that it's not necessary to make a chain of lenses from temple to the altar. Then what? Build your base only near the altar? Or run to it every time that you need to transmutate something?

That is sad to hear. Well I suppose all we need is time then. As this mod develops it will attract more and more players, cause it has potential ;)

I'm not ready for the ritual part yet, I'll see what/if I can do with them.

**Comment by Doomgull** [comment]
Building an altar in a more advantageous position until you have lenses, collector crystals to function as a battery, etc.

This is all in the book, it doesn't seem like you've made any effort to read it.

**Comment by rinart73** [comment]
I read it. I just hoped that there is other options available besides running with resonating crystal (which doesn't work for me and I'm still trying to understand why) and building a Relay farm on top of the altar (which I discovered recently during the experiment in the creative mode) because information about the relay is unclear in the book.

**Comment by HellFirePvP** [comment]
> It doesn't add anything. 

i suspect the crystal has a clear view to the sky? If not then i'm not surprised it doesn't add much. Also, again as usual, better during night than day.

> You said that it's not necessary to make a chain of lenses from temple to the altar. 

you said in another post that you cheese'd it with multiplt spectral relays and building it higher up. That's a way to work around it. Or _finding a strong skywave-field with the skywave resonator_, which is usually the easiest way. But since most people are seemingly very resilient against leaving their base searching for one of those skywave fields, i've added those other 'workarounds'.

Also, later on you can craft your own collector crystals from crystals that are attuned to specific constellations. So getting enough starlight in the "current endgame" is not hard.

And yes, the russian translation is incomplete and wrong in places already.... If you want you can translate it :P - mind that this entails keeping it somewhat updated or i'm gonna remove it again, because, well... i don't wanna provide wrong information either.

**Comment by rinart73** [comment]
> better during night than day
I know. As for clear view to the sky.. I actually don't know, but I'll try.

> you cheese'd it with multiplt spectral relays
Well it works in a single player so I hope that it will work in the multiplayer. It actually can give a ton of skylight (I filled empty tier 1 crafting table up to full capacity) as an experiment. It's crazy I know, I will not do this ever again,

If I will have time I will participate in the translation. When I will be fully comfortable with the mod and will understand all mechanics)
