### ISSUE TITLE
(MOD CONFLICT) Dr.Zharks's Mo'Creatures Crashing

### ISSUE THREAD

**Issue by SangurianSoul** [HellFirePvP/AstralSorcery#223]
Im not a programmer by any means, so i know very little of the issue that is presenting itself here.

All i know is that Astral Sorcery and Mo'Creatures arent getting along.

I will include my crash report, in hopes this is an easy issue to fix as Dr.Zhark is no longer modding i do not believe.

Also, if i am doing something really simple and dumb, just tell me. But, it seems to crash any subsequent loads of a world. A new fresh world will load, but upon return it crashes.
[crash-2017-07-03_16.32.15-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/1120523/crash-2017-07-03_16.32.15-server.txt)

**Comment by HellFirePvP** [comment]
#207

Not my mod, not something i can fix.

**Comment by SangurianSoul** [comment]
there is nothing you can do on your end? This has nothing to do with your mod?

Please explain if you dont mind, i just like to better understand these things.

DR.Zharks has worked flawlessly with every mod ive had for months until i tried installing yours today.

**Comment by Doomgull** [comment]
Seeing as zharks mod is causing the crash, why would you assume it's something AS is doing instead of that other mod, and want this mod to fix that other mod's code?

**Comment by HellFirePvP** [comment]
I have no idea where or what crashes, there is nothing about my mod specifically mentioned so idk what i should adjust or what exactly causes the problem. And i'm not going to fix other people's problems.

**Comment by SangurianSoul** [comment]
Ah is it?

Okay, that's fine, im really bad at reading the reports. not a problem.

AS is an awesome mod and i will certainly continue to use it. it has such a fun hands on feeling to it.

Thanks anyways, and good luck on your awesome work!

**Comment by UltraHex** [comment]
Spent most of today researching this. Apparently, this happens because Astral Sorcery is replacing the WorldProvider of the overworld with its own and Mo' Creatures' Custom Spawner doesn't know what mobs to spawn. Luckily, there's an easy fix:
`S:weakSkyRenders <
	0
 >`
in astralsorcery.cfg

You will probably have to add anything else from `skySupportedDimensions` to the list as well.
