### ISSUE TITLE
Suggestion - Starmetal uses

### ISSUE THREAD

**Issue by robertmaxton42** [HellFirePvP/AstralSorcery#224]
So, first of all I just want to say that this is an amazing and beautiful mod, and I love the concept right from the start. The stars are beautiful at night.

-- So's starmetal, too. I really like that texture, and it's kind of a shame you can't do much with the ingots. Perhaps we could get a compressed starmetal block for decoration, for starters? Maybe tools made of starmetal? For bonus points you could implement a TiCon interface or something, Fated homing arrows or piercing swords, but tbh I'd settle for making my own starry sky. 

(While I'm at it, is there any way you could register stardust as dust-of-starmetal for pulverizer/crusher/etc purposes? The grindstone is cool, but it's a little annoying to grind up large quantities of stardust by hand.)

**Comment by HellFirePvP** [comment]
Parts of this is already kinda planned-ish but yes :P i am aware :P

**Comment by robertmaxton42** [comment]
Ooh, excellent. Looking forward to it!

Oh, if you'll allow me to make another suggestion - could you break down the multiblock diagrams into levels like some mods do? It's not too important for most of them, but things like the infuser hide the runes on the marble, so it's hard to tell the difference between runed marble and, I dunno, a pillar top or something.

**Comment by robertmaxton42** [comment]
Also - being roundabout because the logic behind it is kind of cool and I don't want to spoil it - but IRL, there are certain combinations of star sightings and dates that are normally impossible, because at that time the star is directly "behind" the Sun. There is, of course, one major exception: when a total eclipse happens to occur on that date, and the stars are visible even during the daytime.

It seems like a more intuitive way of rewarding an insightful player than the current <spoiler> - while it'd be difficult to make the sky as dark as it should be in Minecraft, I think you're already showing something arbitrarily chosen for the hand telescope, which can also be freely aimed straight up...?
