### ISSUE TITLE
1.12 Ender Dragon broken

### ISSUE THREAD

**Issue by Zygus42** [HellFirePvP/AstralSorcery#225]
astralsorcery-1.5.7
forge-1.12-14.21.1.2395-installer-win

When you go to the End with your mod installed:
1) the bedrock structure that will be the portal to leave the End has no torches on it.
2) the Ender Dragon boss hit point bar does not go down as you do it damage
3) when the Ender Dragon dies, it drops exp, but no dragon egg and no portal to return home.  Game over.

**Comment by Doomgull** [comment]
Are there any other mods at all?

**Comment by HellFirePvP** [comment]
Yea this doesn't sound like being my mod's fault at all. Not doing anything to this.

**Comment by Zygus42** [comment]
Yes i'm afraid it is.  Retested it yet again.  Vanilla = fine.

astralsorcery-1.5.7 & 1.5.8 = broken.  No other mods installed at all.  Only Astral Sorcery.

Forget about point 1 above - didn't realize the dragon breaks them.

When you hit the dragon, the boss hp bar does not go down, and then when you finally kill it, it drops exp but does not create a portal home, a dragon egg or place the 4 torches on the bedrock pillar.

**Comment by Zygus42** [comment]
Guess maybe logs would help:
[logs.zip](https://github.com/HellFirePvP/AstralSorcery/files/1123614/logs.zip)

**Comment by HellFirePvP** [comment]
The logs don't show anything of importance. I'll go double check.
