### ISSUE TITLE
Suggestion(?) - Сonstellation Book entries - moon phases when constellation is visible

### ISSUE THREAD

**Issue by rinart73** [HellFirePvP/AstralSorcery#227]
As I see it may be a planned but not just yet implemented feature, but I just want to be sure.
In the book, every constellation entry shows a set of mini-pictures of moon phases. But it's the same for all constellations. Is it a bug, a design thing or it will be implemented in the future?

**Comment by HellFirePvP** [comment]
It's gonna be changed soon anyway as the constellation-section will be reworked.

**Comment by HellFirePvP** [comment]
The constellation details-section is reworked and it'll be changed in the next update.
