### ISSUE TITLE
[Bug] [Beta 1.12] Emptying a bucket of liquid starlight on a "flowing block" of liquid starlight voids the contents of the bucket

### ISSUE THREAD

**Issue by Ayrrow** [HellFirePvP/AstralSorcery#23]
This has happened to me twice when refilling the altar.

**Comment by HellFirePvP** [comment]
Isn't this vanilla behavior?... If you place a lava bucket "into" a lava source block it gets voided aswell.

**Comment by 63502** [comment]
Yes, a source bucket will void if placed on another source, but what I think Ayrrow  is talking about is the flowing non source part. If placed there, the source takes the place of the non source. This would make this an actual bug and not vanilla behavior.

**Comment by Ayrrow** [comment]
Yeah, what @63502 said, placing a bucket of starlight on a non-source block voids the contents of the bucket, rather than turning it into a source block.

**Comment by HellFirePvP** [comment]
(Since i finally get to it now..) Can't reproduce that..

**Comment by HellFirePvP** [comment]
can't reproduce it and _i_ don't do anything about placement, the bucket is from forge, including the handling. My fluid block also doesn't do anything out of the ordinary. Either mod interaction or something i can't do anything about, so. Not more to say to that.
