### ISSUE TITLE
[1.11.2][1.4.5] Server crash from altar performing collector crystal upgrade recipe

### ISSUE THREAD

**Issue by Rosethorns** [HellFirePvP/AstralSorcery#231]
Collector Crystal attuned to Descidia

https://pastebin.com/zJGhsmn9

**Comment by HellFirePvP** [comment]
#222 Fixed for the upcoming version. Will keep this open to prevent duplicates.

**Comment by trogarus** [comment]
Just of note, this also seems to apply to 1.12 versions as well when a quantum quarry is used, triggering issues with world provider and such as well.

[quantum error.log](https://github.com/HellFirePvP/AstralSorcery/files/1342103/quantum.error.log)
