### ISSUE TITLE
[1.10.2-1.4.5] Solar Eclipse does not respect gamerule doDaylightCycle

### ISSUE THREAD

**Issue by Compegen** [HellFirePvP/AstralSorcery#232]
Solar eclipses can still occur even when the daylight cycle has been disabled.
![2017-07-10_12 21 38](https://user-images.githubusercontent.com/8009507/28030678-60c59860-656a-11e7-91ea-9af5ad40f1e9.png)

**Comment by Doomgull** [comment]
Solar eclipses only happen during the day, so....seems like it's working correctly?

Maybe a separate command to disable that...
