### ISSUE TITLE
Question: I cannot make resonating gems..

### ISSUE THREAD

**Issue by kbcoder** [HellFirePvP/AstralSorcery#234]
I have spent 2 days now trying to figure out why placing an aquamarine on my starlight infuser and then right clicking it with the wand  does nothing and not producing a resonating gem. I have rebuilt the structure like 3 times, all blocks are correct in numbers and placement with 12 starlight liquid in its place, a lapis block in the middle, surrounded by ruined marble. I have had 2 others confirm it the whole build up,remade wands, etc.. and  still nothing. Has something changed? Suggestions?

Here is a pic of it.  https://ibb.co/c5v1aF   also, using the latest version in 1.11.2  I think it is version 1.4.5 of Astral

**Comment by HellFirePvP** [comment]
http://i.imgur.com/B8otLDg.png

Chiseled marble on the corners, not engraved marble.
If you have further questions or uncertainties, you can also join AS' discord server. You might catch me there faster if you need help. https://discord.gg/q37VRcT

**Comment by kbcoder** [comment]
*Bangs forehead on table*

jeesuz.... thanks.
