### ISSUE TITLE
player cannot self attune in  in attunement altar when server is behind BungeeCord proxy

### ISSUE THREAD

**Issue by hunter688** [HellFirePvP/AstralSorcery#237]
When is server behind BungeeCord proxy (Waterfall fork) player cannot self attune in  in attunement altar.

It looks like some kind of nonstandard network packet cannot go through client<->server.

1.11.2 - astral sorcery 1.4.3

proxy: https://github.com/WaterfallMC/Waterfall

**Comment by HellFirePvP** [comment]
Using forge's standard network wrapper. If it doesn't support even that, i won't bother dealing with it anyway as it would require a massive rewrite.
