### ISSUE TITLE
Exu2 + Astral Sorcery on 1.12 crash

### ISSUE THREAD

**Issue by kragnoth** [HellFirePvP/AstralSorcery#238]
https://pastebin.com/RksBEaDK

forge 1.12 
2412

Astral Sorcery: 1.6
exu2: 1.5

Hard crashes when exu2 switched randomly generated biomes.

I also have BoP: 2289 installed.

**Comment by HellFirePvP** [comment]
Same as #240 as far as the stacktrace goes.

**Comment by jc2xs** [comment]
So I have what appears to be the same crash.  I hope this additional log helps.  This was on my server.
https://pastebin.com/d8NMBc5x

**Comment by frenzye** [comment]
same https://gist.github.com/frenzye/35767e5f38448053f402b04f2724c4a4

**Comment by Doomgull** [comment]
Y'all can keep posting these, doesn't change that it's an issue with exu, and with more than a thousand tickets open, doesn't seem like Tema cares..

**Comment by frenzye** [comment]
https://github.com/rwtema/extrautilities/issues/1572

**Comment by HellFirePvP** [comment]
Potentially fixable by adding the ExtraUtilities Quantum-Quarry dimension ID to the 'weak sky renders' whitelist in the config on serverside and clientside. Not a great fix but might be sufficient. ?

**Comment by kragnoth** [comment]
I'll try that HellFirePvP.  From what I can see though, it shouldn't even be trying to run the lighting rendering, as that looks like a whitelist on your end.  So Exu2 ignores that completely somehow.

**Comment by HellFirePvP** [comment]
Just go ahead and try it. It'll most likely work. :P 

I would doubt he'd care either way - he strikes me as a person like BluSunrize or others that don't acknowledge mods' existence if they have less than 2-3 million downloads or something. Neither do they care about their issue trackers and bugs it seems.

**Comment by kragnoth** [comment]
I'll make an array of about 30 of these quantum quarries and see if your suggestion works when I get some free time.  Thanks again for the suggestion.

**Comment by thiakil** [comment]
> Potentially fixable by adding the ExtraUtilities Quantum-Quarry dimension ID to the 'weak sky renders' whitelist in the config on serverside and clientside. 

This config option is actually a *black*list, as adding a dim to the list *prevents* your mod from overriding the `WorldProvider` - you check if the dim is *not* in the list judging by https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/event/listener/EventHandlerIO.java#L49

An actual whitelist would be preferable, as currently this is causing an issue with a mod using dynamic dimensions that is checking for its own provider and getting yours instead.

**Comment by HellFirePvP** [comment]
Somewhat connected to #271 - so since that feature has been removed in the upcoming v1.6.2, this bug will not exist after 1.6.2+
