### ISSUE TITLE
[1.10.2] Astral Sorcery crash on creation of RFtools dimension

### ISSUE THREAD

**Issue by JonoColwell** [HellFirePvP/AstralSorcery#239]
Attempted to create a new RFtools dimension,, astral sorcery is throwing an excepptioon despite only being whitelisted for structure feneration in dimension 0

https://pastebin.com/PYuS623E

**Comment by HellFirePvP** [comment]
@McJty seems to be on your end rather.

**Comment by McJty** [comment]
Actually seems to be a sponge bug. Is sponge recent enough? Otherwise report to sponge

**Comment by HellFirePvP** [comment]
Yes, from looking at the source code of yours Mcjty, it does indeed seem lik Sponge just doesn't support this (yet).

Might be/get resolved in a more recent/future sponge version, however, at the moment it's neither mine nor mcjty's fault.

#Closed

**Comment by JonoColwell** [comment]
Bugger me I'm seriously considering just deleting sponge.

**Comment by Doomgull** [comment]
That's the train I've been on for a long long time.
