### ISSUE TITLE
1.12 Referenced from ExU2 Quantum Quarry Dim Crash

### ISSUE THREAD

**Issue by DingoX3** [HellFirePvP/AstralSorcery#240]
https://github.com/rwtema/extrautilities/issues/1572

**Comment by HellFirePvP** [comment]
On tema's end, not me. - and he seemingly doesn't care about issue reports looking at the more than 1k open reports.

**Comment by DingoX3** [comment]
lol..Looks that way. Well thanks for your quick insight. Glad its not something you have to fix.
