### ISSUE TITLE
Rendering bug when opening the journal

### ISSUE THREAD

**Issue by Maximeus** [HellFirePvP/AstralSorcery#242]
i have an issue when i open the journal, the health, food and experience bar stop rendring correctly and is replaced with white boxes
Here is the phenomenon
![ss 2017-07-15 at 04 34 38](https://user-images.githubusercontent.com/29133136/28240184-aae64f82-697c-11e7-8b84-ba1f9c7f8a02.jpg)

And the list of the other mods i have
![ss 2017-07-15 at 04 42 14](https://user-images.githubusercontent.com/29133136/28240183-aae387d4-697c-11e7-9145-8e9f4d624523.png)

**Comment by Doomgull** [comment]
#72
