### ISSUE TITLE
Add explicit support for Chisel

### ISSUE THREAD

**Issue by tterrag1098** [HellFirePvP/AstralSorcery#244]
In an upcoming release, chisel will be removing the "oredict variants" feature, as it causes too many bugs to be worth while. Everything is much cleaner when the conversion between ItemStack/IBlockState is done by the variation supplier.

The new IMC API is documented here: https://github.com/Chisel-Team/Chisel/blob/1.10/carving_refactor/src/main/java/team/chisel/api/IMC.java#L49-L90 (subject to change)

This new API is still a work in progress, so if something is missing that you need, please let me know.

You can safely add this IMC and release your mod, if a user has an older chisel version it will simply be ignored.

**Comment by HellFirePvP** [comment]
I hope "marble" is the correct group for marble as i saw that being used in the "tests" in the main chisel class :P Support added.

**Comment by DietmarKrause** [comment]
i have to add: chisel of a astral sorcery marble block lead to a crash to desktop in ATM3 modpack. crash report can be provided if needed.

**Comment by HellFirePvP** [comment]
That in the current comment is about as helpful as "crash, plz help"

you have to *at least* provide a crashlog when experiencing a crash. open a new issue for this maybe aswell since it doesn't belong here.
