### ISSUE TITLE
Crash with Stellar Refraction Table [1.12]

### ISSUE THREAD

**Issue by XenoStone1009** [HellFirePvP/AstralSorcery#245]
Pack: [Radon 1.0.4](https://minecraft.curseforge.com/projects/radon/files/2451359)
Minecraft Version: 1.12
Issue: Stellar Refraction Table Enchanting Crash
Steps to Reproduce: 
-Be in creative
-Place the Table and Make an Etched Infused Glass
I removed the glass and replaced it after that, but I'm not sure if needed for crash
-Place a book under the glass
Afterwards, that creative world became unplayable.
Crash log:  [crash-2017-07-16_15.19.47-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/1151348/crash-2017-07-16_15.19.47-server.txt)

**Comment by Doomgull** [comment]
Out of curiosity, what was the enchantment you were trying to apply from the glass?

**Comment by HellFirePvP** [comment]
^

**Comment by XenoStone1009** [comment]
I just dragged 3 random ones, though I am sure was Discidia.

**Comment by Doomgull** [comment]
Update from the Discord during prelim testing for reproduction, seems it was triggering when things caught fire during the writing process, not the combination itself.

**Comment by HellFirePvP** [comment]
@XenoStone1009 was one of them fornax or lucerna?
