### ISSUE TITLE
crash when trying to chisel marble blocks from astral sorcery

### ISSUE THREAD

**Issue by DietmarKrause** [HellFirePvP/AstralSorcery#246]
here is the crash report: https://pastebin.com/wY2j0yx6
reportet to chisel too and the ATM3 github.

**Comment by DietmarKrause** [comment]
https://github.com/Chisel-Team/Chisel/issues/496

**Comment by DietmarKrause** [comment]
https://github.com/AllTheMods/ATM-3/issues/57

**Comment by HellFirePvP** [comment]
Uncertain if this is necessarily my fault.

**Comment by HellFirePvP** [comment]
You are using an outdated chisel version.
