### ISSUE TITLE
Crash with Mystcraft 1.11.2

### ISSUE THREAD

**Issue by WolfieWaffle** [HellFirePvP/AstralSorcery#247]
I got this crash report when playing with Astral Sorcery and Mystcraft, I don't know which side the problem is on but tell me if it's not fixable from this end.

https://pastebin.com/SENHUwBd

**Comment by HellFirePvP** [comment]
Yes that's on mystcraft's end - the bug that i've fixed there today. :P 

A new mystcraft build will be released tomorrow which will also fix this.
https://twitter.com/XCompWiz/status/889228904539586560

**Comment by WolfieWaffle** [comment]
Looks like you are on of both errors I posted today, sorry about that XP
Thanks for being on top of it though, keep up the good work.
