### ISSUE TITLE
OptiFine Incompatible

### ISSUE THREAD

**Issue by sawthewhat** [HellFirePvP/AstralSorcery#248]
(OK...My English is poor. Sorry)
When AS (AstralSorcery) and OptiFine are installed the same time.
then I tried to open the book and zoomed in. when I close the book.
It showed like this.

![2017-07-25_14 53 07](https://user-images.githubusercontent.com/13689994/28559763-889eb1e6-714a-11e7-867e-398065956e64.png)

Even the words.
![2017-07-25_14 53 11](https://user-images.githubusercontent.com/13689994/28559799-a0b9ca72-714a-11e7-9110-9b04736fd1dc.png)

I'm sure it's true.I removed OptiFine. then it ran well.

Plantform: Ubuntu 14.04
MC ver: 1.12.
AS ver: 1.6.1

**Comment by Doomgull** [comment]
Disable OptiFine's "Fast Render" option.
