### ISSUE TITLE
Just wondering...

### ISSUE THREAD

**Issue by MasterFee** [HellFirePvP/AstralSorcery#25]
JEI says that some recipes can use any kind of Rock Crystal where in game you can only use the normal Rock Crystal, not the attuned ones. Is JEI showing something it should or are the recipes in game broken?

![bildschirmfoto 2017-02-18 um 17 26 47](https://cloud.githubusercontent.com/assets/8414127/23094878/0b66604e-f601-11e6-84f4-b9db900d3ed1.png)
![bildschirmfoto 2017-02-18 um 17 26 53](https://cloud.githubusercontent.com/assets/8414127/23094880/0b8f044a-f601-11e6-98fe-f7e53e941e25.png)
![bildschirmfoto 2017-02-18 um 17 22 38](https://cloud.githubusercontent.com/assets/8414127/23094879/0b8c9f70-f601-11e6-9b4c-e4f193171811.png)

**Comment by HellFirePvP** [comment]
That would be a derp where my recipe handling broke
