### ISSUE TITLE
Walia not reading blocks right. Screenshot showing issue.

### ISSUE THREAD

**Issue by jwebba** [HellFirePvP/AstralSorcery#252]
![image](https://user-images.githubusercontent.com/23028228/28687016-12cbbdbc-7305-11e7-9574-dc225b8b1827.png)

Walia seems to think the grindstone is the Telescope block? Maybe down to them being the same ID's #4477/0 etc etc

Forge: 12.18.3.2316
Astral Sorcery: 1.10.2 - 1.4.5
Walia: 1.7.0-B3.1.9.4

**Comment by HellFirePvP** [comment]
Yes they are using the same block and no this is Waila's fault for not using the proper blockstate when querying for .getPickBlock - stopped overwriting it in favor of TOP compatibility - if i did it'd occasionally cuase crashes with TOP - TOP seems to be the more used mod atm, so i won't support this at the moment.
