### ISSUE TITLE
Perks and Attunement can not be used on bungeecord

### ISSUE THREAD

**Issue by luenlin** [HellFirePvP/AstralSorcery#256]
Dear author, hello
Astral Sorcery has a problem with my server
My server is bungeecord and Minecraft 1.10.2
Perks and Attunement can not be used on bungeecord
Single trigger mechanism can not be used on bungeecord server

This is a very good mod, very popular in China
Thank you very much for bringing us so good mod

**Comment by HellFirePvP** [comment]
Forge's packet-wrapper system has issues with Bungeecord packet-system. There is nothing i can do about it and this has been reported some time ago aswell.

So. Nothing i can fix in reasonable amount of time. Sorry.
