### ISSUE TITLE
Lightwell (liquid starlight) + TD Fluiduct crash

### ISSUE THREAD

**Issue by MigukNamja** [HellFirePvP/AstralSorcery#261]
`java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:47) at hellfirepvp.astralsorcery.common.util.block.PrecisionSingleFluidCapabilityTank.drain(PrecisionSingleFluidCapabilityTank.java:174) at cofh.thermaldynamics.duct.attachments.servo.ServoFluid.tick(ServoFluid.java:91)
`
[Full crash report](https://pastebin.com/X8dGK1ji)

I cross-posted this same crash in CoFH against ThermalDynamics:
https://github.com/CoFH/Feedback/issues/469

**Comment by MigukNamja** [comment]
Thanks, HellFirePvP !

**Comment by HellFirePvP** [comment]
Via https://github.com/HellFirePvP/AstralSorcery/commit/140e31a9ba0e88649a73856aeef38c2d17a081a5
