### ISSUE TITLE
ritual altar

### ISSUE THREAD

**Issue by chronocrest** [HellFirePvP/AstralSorcery#263]
I've been unable to get the attuned crystals effects to work when placed in an ritual altar. I'm currently using the 1.12 version.

**Comment by Doomgull** [comment]
Would be better to come to the Discord for AS with screenshots for this kind of thing.

**Comment by Doomgull** [comment]
@chronocrest this still an issue for you? Need some more information, like version you're on, screenshots, that sort of thing.

**Comment by chronocrest** [comment]
No I managed to solve it, just a little while age.the problem was mostly
because I wasn't paying enough attention to the blocks I was using
