### ISSUE TITLE
Unable to Navigate Knowledge in Journal

### ISSUE THREAD

**Issue by Aestolia** [HellFirePvP/AstralSorcery#265]
Hi, First just want to say loving the mod so far.

I'm having an issue with navigating the journal knowledge tab. I'm unable to click and drag the galaxy map around, so if I've zoomed into Discovery, when zooming back out i'm unable to move over to Exploration and zoom in. Currently I can work around this by switching to Constellations tab, then back to Knowledge to reset the position of the knowledge tab and then I can zoom into Exploration.

At first i thought it might be a mod interaction (as I understand there have been some issues with OptiFine) I have tired this with AS being the only installed mod and the issue persists.

Minecraft - 1.12
Astral Sorcery - 1.6.1
Forge - 14.21.1.2443

Not sure if you need any other information. I could provide screenshots, however it wouldn't show my inability to move the knowledge map around.

**Comment by Doomgull** [comment]
What OS and version? Same with mouse and mouse fw/drivers.

**Comment by Aestolia** [comment]
Hi Doomgull, Thanks for the quick response!

Win10 Pro (1703 build 15063.483)
Erebos mouse FW 103, Drivers and software is HERA 2.7.3

**Comment by Aestolia** [comment]
Just an update: I'm unsure what happened, but the issue resolved itself today. Perhaps I had a windows update of some kind overnight.
