### ISSUE TITLE
Unable to craft any Attunement Items

### ISSUE THREAD

**Issue by etherealyandere** [HellFirePvP/AstralSorcery#266]
So I've unlocked the Attunement section of the journal but I seem to be unable to craft anything from it. Theres the likely chance I'm just being an idiot and doing something wrong that can easily fixed, but I'm a bit of an idiot so I can't figure out what, 

For example, I tried crafting the first item (The big lens used for turning iron ore into the blue, space-y iron but even though I definitely have the correct items, layout and enough power, its just not working. I then tried making a standing Telescope, but that didn't work either.

https://i.imgur.com/OgCHMWM.png
This is the altar and the layout for the len item (the first item in the attunement section) and for whatever reason, its not working. The layouts right, I have full power, but its just....not happening

https://i.imgur.com/W7RH9DG.png
This is the altar and its placements layout. It looks correct according to the journal, so I don't think it's an issue with that

https://i.imgur.com/1iyXttk.png
https://i.imgur.com/XmElU1P.png
As both these photos show, its not an issue with power cause my altar is literally in the perfect location for Astral Sorcery (it was completely sheer luck that it happened. I built my base here before even installing AS) so I don't really know whats occurring.

I'm using Minecraft 1.11.2 and version 1.4.5 of Astral Sorcery. Am I just being a bit of a moron or is this a bug I've stumbled across?

**Comment by Deiwos** [comment]
Make sure you have Chiseled Marble under the columns, not Marble Brick or Marble Arches. Red on the power indicator means your altar structure isn't correctly formed. Note, you can move the 3D representation of the structures around in the manual to see what is underneath.

**Comment by etherealyandere** [comment]
Thank you so much! Glad it was just me being an idiot aha.
