### ISSUE TITLE
This is just very minor

### ISSUE THREAD

**Issue by archmage94** [HellFirePvP/AstralSorcery#267]
As much as I like this mod and would be a great addition to mods such as Thaumcraft (When the author has the time to update it) And Chromaticraft (If Reika ever actually updated ANY of his mods past 1.7.10)

This mod actually doesn't play well with shader packs, especially at night. Just letting you know

**Comment by Doomgull** [comment]
Yes. It's known. There's also a configuration option for weakening the sky render needed for the mod to even function so it plays a litter nicer with shader packs, thoug it makes certain parts of the mod more difficult as a result.
