### ISSUE TITLE
[Suggestion] A Block that Detects Constellations and Emits Redstone/BlockUpdate

### ISSUE THREAD

**Issue by Vyraal1** [HellFirePvP/AstralSorcery#268]
Been a while since I tried Astral Sorcery out in depth but if this functionality is already implemented then you can get rid of this.

Any chance there can be a block that changes blockstate (to be detected by BUD's) or emits redstone when a certain constellation is present at night? Let's say you can configure the block by right clicking it with constellation paper, and when that constellation appears at night it will emit a redstone signal. In my developing modpack I'm thinking of using Horologium Attuned Crystal as a part of progression (since to my understanding its the least frequent appearing constellation) but I don't want to make it frustratingly difficult for players on multiplayer servers. As far as I know I don't know of any detection system present in Astral to help with this.

I'm hoping this will make it quite a challenge if a player wanted to automate getting crystals of certain attunements while not really changing a lot of the aesthetics of the mod.

**Comment by Doomgull** [comment]
Horologium only appears after an eclipse, so that one isn't particularly difficult to find.

Might be neat for automation, though.

**Comment by HellFirePvP** [comment]
Yea, you can. Build the relays in the specific positions around the attunement altar and if the constellation is active, you get a visual indicator that you should already be familiar with. :P
