### ISSUE TITLE
Infused crystal sword does not credit the player for celestial damage

### ISSUE THREAD

**Issue by unascribed** [HellFirePvP/AstralSorcery#269]
https://github.com/HellFirePvP/AstralSorcery/blob/145a54a058555462e284e8d5c87a4864d65fe832/src/main/java/hellfirepvp/astralsorcery/common/util/effect/CelestialStrike.java#L65

This was reported to me as a GlassHearts bug, wherein Sapping does not proc when a mob is killed by the secondary damage from the infused crystal sword.

The linked code uses a static shared DamageSource for all celestial damage, instead of creating EntityDamageSources that credit the player. (I don't have a workspace open right now and don't have the exact class name.)

I would guess the player not being credited is unintentional, but I could be wrong.

**Comment by HellFirePvP** [comment]
This is a rather tricky problem since from my design point it would not be the player as direct source of the damage. So.. yea. It's not the player doing the damage by design, however i can see this being potentially problematic for certain features. i'll see to it...

**Comment by HellFirePvP** [comment]
Changed. does player damage now >_>
