### ISSUE TITLE
[Client Crash] Crash when infusing rock crystal with Mineralis. 

### ISSUE THREAD

**Issue by Ayrrow** [HellFirePvP/AstralSorcery#27]
Crash when infusing with mineralis, didn't crash infusing either player or crystal with avertias. 

> **Forge Version:** 2219

> **Mods:**
>   ActuallyAdditions-1.10.2-r88
>   AppleSkin-mc1.10.2-1.0.4
>   astralsorcery-1.1.2-beta
>   BloodMagic-1.10.2-2.1.2-71
>   compatlayer-1.10-0.2.2
>   EnderCore-1.10.2-0.4.1.61-beta
>   EnderIO-1.10.2-3.1.156
>   EnderZoo-1.10-1.2.3.43
>   extrautils2-1.10.2-1.3.0
>   FastLeafDecay-v11
>   foamfix-0.3.2a-law
>   GiacomosCompass1.10.2-1.0.1
>   Guide-API-1.10.2-2.0.3-46
>   inventorysorter-1.10.2-0.10.5+46
>   ironchest-1.10.2-7.0.11.797
>   jei_1.10.2-3.13.6.387
>   Mantle-1.10.2-1.1.5
>   mcjtylib-1.1x-2.3.8
>   MCMultiPart-1.3.0-universal
>   MouseTweaks-2.6.4-mc1.10.2
>   QuantumStorage-1.10.2-3.2.19
>   RebornCore-1.10.2-2.13.4.128-universal
>   refinedstorage-1.2.21
>   rftools-1.1x-5.83
>   rftoolsctrl-1.1x-1.6.6
>   TConstruct-1.10.2-2.6.3
>   theoneprobe-1.1x-1.4.2
>   TombManyGraves-1.10.2-2.1.13
>   xnet-0.0.1alpha

> [14:11:13] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ClientTickEvent@4cdde80e:
> java.lang.NullPointerException
> 	at java.util.LinkedList$ListItr.next(Unknown Source) ~[?:1.8.0_121]
> 	at hellfirepvp.astralsorcery.client.effect.EffectHandler.tick(EffectHandler.java:243) ~[EffectHandler.class:?]
> 	at hellfirepvp.astralsorcery.client.effect.EffectHandler.onClTick(EffectHandler.java:132) ~[EffectHandler.class:?]
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_284_EffectHandler_onClTick_ClientTickEvent.invoke(.dynamic) ~[?:?]
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
> 	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:344) [FMLCommonHandler.class:?]
> 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1851) [bcx.class:?]
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055) [bcx.class:?]
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
> 

full log - https://paste.ee/p/k70jG

**Comment by HellFirePvP** [comment]
Because this is not connected to infusing the rock crystal, but something going wrong in the particle renderer for w/e reason...

**Comment by Ayrrow** [comment]
It happens just at the end of the infusion, when that sphere appears. I've replicated this twice.
