### ISSUE TITLE
Please use a whitelist for WorldProvider hijacking

### ISSUE THREAD

**Issue by thiakil** [HellFirePvP/AstralSorcery#271]
https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/event/listener/EventHandlerIO.java#L49

You appear to be hijacking the provider unless something is listed in `weakSkyRenders`, but without a check for whether that dimension is even in the whitelist of `skySupportedDimensions`

This is creating issues with any mod using dynamic dimensions that checks for its own world provider; one would have to add *every* dimension number (existing or not) to that list to get around it.

**Comment by HellFirePvP** [comment]
The next update removes solar eclipses darkening the world anyway, so this is from that point onwards kinda redundant anyway.

**Comment by thiakil** [comment]
fair enough

**Comment by HellFirePvP** [comment]
https://github.com/HellFirePvP/AstralSorcery/commit/815ab70d1793491da23c6daeaa1e35c22c6cefa0 closed this - idk why github didn't insert the commit link here.
