### ISSUE TITLE
Suggestion: add a ritual to increase the purity of rock crystals

### ISSUE THREAD

**Issue by sanguis3k** [HellFirePvP/AstralSorcery#272]
I have been playing about with this mod since it came in a 1.12 pack and I have enjoyed it quite a lot, I have noticed though there is absolutely nothing you can do to get around the RNG for getting crystal purity. I know it isn't vital for most things and you can get by just fine with 60-80% purity gems but I would love to see a ritual or recipe that increases the purity of gems at a rate of 1/4 to 1/2 of the gems going into another one or configurable so you can choose

**Comment by HellFirePvP** [comment]
A way to increase crystal purity already exists, however not documented at all - it'll get proper documentation in the next update.
