### ISSUE TITLE
Shader Incompatible

### ISSUE THREAD

**Issue by nikissXI** [HellFirePvP/AstralSorcery#274]
![2017-08-27_11 13 48](https://user-images.githubusercontent.com/31379266/29746837-7ac7756a-8b19-11e7-8aee-6abec892497a.png)

what's wrong with the sky and the sun?please help me ,I can't use shader..
If I delete AstralSorcery ,it can back to normal

**Comment by Doomgull** [comment]
The mod has to alter the game shaders in order to display constellations and such. This means the other shader have a conflict.

Enable the "weak skill render" configuration option for AS. This is a well documented issue in the tracker, here.

**Comment by nikissXI** [comment]
I don't know how to enable the weak skill render...
![1](https://user-images.githubusercontent.com/31379266/29747096-c5170912-8b20-11e7-85a2-8edd25262c7e.jpg)

**Comment by Doomgull** [comment]
By reading the instructions and putting the dimension ID you want that option enabled for, which also needs to be in the above option (hint, it's the one with the zero)

**Comment by nikissXI** [comment]
I can't understand how to set the config,I don't have programming basics,and I am a Chinese player,so I can't understand the instructions clearly.

**Comment by nikissXI** [comment]
I find someone else to help，thank you。

**Comment by nikissXI** [comment]
I find someone else to get help ，thank you
