### ISSUE TITLE
Celestial Gateway UI Crash

### ISSUE THREAD

**Issue by Vyraal1** [HellFirePvP/AstralSorcery#275]
https://pastebin.com/Rf9CE2Y3

Crashed upon landing at a Celestial Gateway, and kept crashing upon logging in. Uninstalled optifine, crashed once, but successfully stayed in for the 2nd time.

**Comment by kingofcannons** [comment]
I've had a very similar issue with, and without optifine. Removing optifine fixed the issue the first time, but the crash came back and didn't stop until the gateway was broken. I'm on the same multiplayer server as Vyraal1, if that helps.

Crash with optifine:
https://pastebin.com/W3cgVey2
Crash w/o optifine:
https://pastebin.com/6rKpxJTS

**Comment by HellFirePvP** [comment]
via https://github.com/HellFirePvP/AstralSorcery/commit/52b9bcf3918ede3f479784dc04f7104b0501542b
