### ISSUE TITLE
[Suggestion] Grow crystal size in a Starlight Infuser

### ISSUE THREAD

**Issue by Vyraal1** [HellFirePvP/AstralSorcery#277]
Similar to bathing a crystal in liquid starlight to increase it's size, can you also add that functionality to a Starlight Infuser? It can still be at 100% use of liquid starlight, but at the same time you can make it so that once provided starlight from a collector crystal, it'll be much faster than just waiting for a bunch of crystals to finish bathing.

**Comment by Saereth** [comment]
I like this idea, seems like a natural progression of the mod, plus no in world to despawn and more uses for the starlight infuser, win all around

**Comment by Tim2162286** [comment]
If this was added it would probably be at the cost of spliting the crystal, since i believe the infuser only has room for one item in it. Also, i thought there was code to prevent the crystals from despawning. i know i have acidently left crystals lying around for over a minecraft day with no problems.

**Comment by Doomgull** [comment]
Dunno, might be good to have it increase size and just never split the crystal at max size, so ignoring it eats up starlight for no gain.

**Comment by uecasm** [comment]
There shouldn't be any issue with splitting the crystal if they drop out of the infuser after each size growth/split -- the items that have completed infusing no longer count as "inside" the infuser, they're just sitting in-world.  (This can be seen when you can put a new aquamarine into the infuser without taking the previously infused one.)

**Comment by Doomgull** [comment]
It was more a "cost for the convenience" thing.
