### ISSUE TITLE
[1.12][Bug]Crystal tools not breaking blocks

### ISSUE THREAD

**Issue by AssasinAsha** [HellFirePvP/AstralSorcery#278]
Specifically, crystal pickaxe and axe act as if I was trying to break certain blocks with my hand, even though the tool I used is correct.
For testing purposes I added Silktouch enchant to the pick, although the bug happens without any enchants as well. 

Interestingly, if I hover over these blocks with the tools in hand, Waila Harvestibility shows an error, which does not happen if I don't have the tool in my hand (I can see the harvest level with an empty hand or a vanilla tool). However, the error also applied for glass (all varieties), glass panes (same) and monster egg blocks, despite the fact that they _were_ collected with silktouch just fine, so it might not be connected that much (It also happens with vanilla tools).
All the other blocks (those on the list) just break into nothing/get harvested as with an empty hand, with no silktouch applied (although I think it's simply not applicable to them) and with the same speed as if I broke them by hand.

While the list only has vanilla blocks, that's because I only had AS, HWYLA, Waila harvestibility and JEI for testing purposes. Other mods blocks, such as coloured slate from Earthworks also trigger this behaviour. AS blocks themselves work just fine.

[List of blocks](https://gist.github.com/AssasinAsha/11d572427614721407aaac42ef4a1ec9#file-blocks). I think this is most of them. Might have missed one or two.

Infused crystal tools exhibit the same behaviour.

Also, obsidian is breakable but takes absolute forever (about a minute per block). I think it's peculiar, since I already need a diamond pick to break the crystal ore and the crystal pick breaks said ore just fine. No point in using crystal pick for obsidian if diamond one is so much faster.

Versions:
Astralsorcery 1.12-1.6.1
Forge 14.22.0.2464
JEI 1.12-4.7.5.85
HWYLA 1.8.20-B35_1.12
WailaHarvestability mc1.12-1.1.11

How to reproduce:
1. Spawn/craft yourself a crystal tool of choice,
2. Spawn/make yourself a block from the list (that should be broken with the tool),
3. Place the block in the world,
4. Try breaking the block with the tool.

**Comment by Doomgull** [comment]
Full mod list? Something else is modifying that.

**Comment by AssasinAsha** [comment]
Just what was in my first post.

**Comment by AssasinAsha** [comment]
Just checked and without any other mod but AS, the problem persists.
I'll try different forge versions now.

**Comment by Doomgull** [comment]
The mention of Earthworks blocks is what made me think there were other mods present. Let me know if this persists in a later forge version.

**Comment by AssasinAsha** [comment]
Yeah, I mentioned that to show it's not only vanilla blocks.
I'm trying every version of Forge now, but quick check showed that both the oldest and newest versions available for MultiMC still had the bug.
Right now I'm checking if there's a specific one without it. Not too many versions, so it should be quick.

**Comment by Doomgull** [comment]
Does it happen without harvestability present?

**Comment by AssasinAsha** [comment]
It happens with only AS as an active mod besides forge.

**Comment by Doomgull** [comment]
Hmm, seems a couple people using the Radon pack have seen a similar issue. Interesting. Time to go digging, unless hellfire beats me to it.

**Comment by AssasinAsha** [comment]
Yeah, I've been playing that pack when I first noticed and then I started testing.
Also, tested different Forge versions to no avail, so I went all the way to the earliest version for MC 1.10.2 available on Curse (AstralSorcery-1.10.2-1.1.0-Beta from February 12th) and the bug is still there.
I'll be really surprised if this managed to avoid attention for that long.
Unless nobody bothered to report it, in which case shame on them all!

**Comment by HellFirePvP** [comment]
This seems rather odd. I've not encountered this yet and it seems odd that it happens with only AS and forge. i didn't encounter this issue yet nor have i ever heard anyone having it..

I'll tend to it and see if i can find out something about it once i have some time leftover..

**Comment by vdrake77** [comment]
Found the same issue here.  I've currently got an infused pickaxe of size 560, purity 46, and 94 cutting that doesn't seem able to work correctly.  The right click function is neat, but I can't mine things I logically should be able to.  Standard minecraft mossy stone bricks, for example.  It mines them slowly and destroys them when done.  Copper ore from mods can't be mined, but breaks in the same way.  Minecraft stone and iron mine extremely fast, though.

**Comment by vdrake77** [comment]
Doing some various testing, I can't mine furnaces with the infused pickaxe either.  It seems like it's strictly vanilla stone and ore that it's fine with?

**Comment by hollowstrawberry** [comment]
Sad that the fix isn't backwards-compatible, the tools are very annoying to work with in 1.12 due to them only breaking a few blocks
