### ISSUE TITLE
[Suggestion] Add a method to get a very rough idea of the % completed of starmetal infusion. 

### ISSUE THREAD

**Issue by Ayrrow** [HellFirePvP/AstralSorcery#28]
Currently its a bit annoying going off and doing something, coming back and still not having metal infused, it would be a nice addition to have a rough idea of how long left in the infusion.

**Comment by HellFirePvP** [comment]
Upon (now actually being able to) testing myself, i got results of like 0,14 charge per tick during *night* times from collector crystals in shrines. Adjusted the required charge to be _much_ lower, so that this becomes actually feasible...
