### ISSUE TITLE
[1.12] [Bug] Player attunement isn't working

### ISSUE THREAD

**Issue by Bertel401** [HellFirePvP/AstralSorcery#280]
I'm playing on the 1.6.1 version of Astral Sorcery.
When I try to attune myself to the Aevitas constellation, i get sucked into the altar and the animation starts playing. Once the animation is done and i can move again, when opening my journal i do not see the "perks" tab anywhere.
I can go to the altar again and repeat this but nothing ever changes.
I have found all four of the basic constellations in the sky.

**Comment by HellFirePvP** [comment]
Any information in the console? Dedicated server or singleplayer? If dedicated, any more information about the connection? (aka is there a bungeecord or similiar proxy server inbetween?) Does the UI/HUD settings and things reset properly to how it was before or is the UI/HUD still hidden after you finish the attunement? (the F1-UI hiding thing)

**Comment by Bertel401** [comment]
It happened on the Modern Skyblock 2 modpack. As I am playing on a server i do not have any console information. While I am getting attuned the HUD is not visible but when i finished it became visible again.

I tried the attunement again yesterday and then it worked without any problems so I am not quite sure what might have caused the problem.

**Comment by HellFirePvP** [comment]
Well.. not sure what to say then.

**Comment by Doomgull** [comment]
@Bertel401 any update or repeat of this issue? Without logs or outputs or ability to recreate to gather those, this is going to be hard to pinpoint what's going on.
