### ISSUE TITLE
creative generated luminos crafting table  not working as intended

### ISSUE THREAD

**Issue by dhudd3** [HellFirePvP/AstralSorcery#281]
it seems if you use creative to get a luminos crafting table  then you cannot craft anything with it tested in latest version (nothing shows up) if i make one using a floating crystal it works fine am happy to post any other information needed

**Comment by HellFirePvP** [comment]
This is roughly as much information as "doesn't work". Please provide additional information regarding this. Do you provide enough starlight/Are you aware how to use it? What's the NBT-tag on the table if you pull it from the creative menu? Have you tried this with only forge and AS? forge versions & AS version?

**Comment by dhudd3** [comment]
haven't tried it with only those 2 mods no i am currently using the latest version of modern skyblock https://minecraft.curseforge.com/projects/modern-skyblock-2
and the latest forge  I am aware of how to use it and was able to get it working with one i created by linking the floating crystal to the crafting table and crafting it that way i am aware of how to use it and have used it to craft many things in order to get the lens for converting iron 
![image](https://user-images.githubusercontent.com/7098329/30525494-ece04ca2-9c4a-11e7-8f4c-8a9b2b79c423.png)

that is the NBT tags for the table exp is at 0 not sure if maybe that's the issue with it other then that the NBT values match the recipe has not been changed in that mod pack 
 forge version 1.12.1 14.22.1.2484
AS version 1.12 1.61

i will test the mods by themselves to see if this still occurs

**Comment by HellFirePvP** [comment]
Try again with version 1.7 - should work now,

**Comment by HellFirePvP** [comment]
I'll take this as either "works now" or lost interest. either way, #closed.
