### ISSUE TITLE
Liquid Starlight is really ugly

### ISSUE THREAD

**Issue by chadmcn** [HellFirePvP/AstralSorcery#282]
It could be really cool and the particles look great but it doesn't tile correctly and also looks kinda like milk.

**Comment by HellFirePvP** [comment]
Resource Packs are a thing if you don't like the texture. i'm not too fond of its tiling when it's flowing diagonally or w/e but well. if you want to make a prettier one, go ahead and PR it. Other than that, use a resourcepack that changes it or leave it as it is.
