### ISSUE TITLE
[1.12.1] class Cast Exception with ExtraUtil2

### ISSUE THREAD

**Issue by KajesLorian** [HellFirePvP/AstralSorcery#283]
Has something to do with your mod doing something to XU2's "Workhouse" dimension (I was using the Quantum Quarry, so I'm assuming that's the "dummy dimension" we pull ores and blocks out of now). I will be posting on their site as well, just in case this is on their side.

https://pastebin.com/EhJg2NaJ

Thank you.

**Comment by Doomgull** [comment]
See solution to #238
