### ISSUE TITLE
Feature request: lightwell dump command

### ISSUE THREAD

**Issue by wizard1399** [HellFirePvP/AstralSorcery#285]
Hey, 
I know you have craft tweaker support built in to the 1.10.2 version of the mod. Could you add an ingame command to dump the lightwell registery to the mt log?

Example of how this will be useful. I am wirking on a pack where there are several mods that add aquamarine. I want to add each of these, but I want to match what you have already set up with the item from your mod. This command would be useful in this situation.

**Comment by HellFirePvP** [comment]
One way to get those variables would be looking it up in the code:

https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/base/WellLiquefaction.java#L41

I don't expect people to sift through my mod either to just find a few lines they need with "magic numbers" they need, so yea, i can see the gain in this. Will add it to the todo list, however, i'm not gonna make promises when i'm gonna get around to add it. Until then, the values in the code should aid you enough ;)
