### ISSUE TITLE
Crafting Sound gets stuck and persists even after leaving game and rejoining

### ISSUE THREAD

**Issue by Winrylive** [HellFirePvP/AstralSorcery#286]
I'm not sure really how to describe what happens so how about a video? This happened during my stream this morning. Please skip to about 1:31:30. https://www.twitch.tv/videos/175189390 I don't know if this is Astral Sorcery or some other thing happening but I thought I should let you know about it.

This is The Simple Life 2 Modpack v1.3.2 which has Astral Sorcery v1.4.5 in it.

**Comment by HellFirePvP** [comment]
Seems Odd, will look into that and make the checks for the sound-loop more precise. Thank you.
