### ISSUE TITLE
Glitch maybe? 

### ISSUE THREAD

**Issue by GalenDudek** [HellFirePvP/AstralSorcery#287]
So I have been playing  a crap ton of the mod-pack Sprout, and jumped right into Astral Sorcery. I just LOVE the concept! 

I have gotten to the point where I need to start making Star Metal ore etc... I have created the crystal wand, and lenses, but when I go to place down the iron ore in front of the lenses, oddly I cant.  I have tried  exiting and re-entering the world, reloading the game, even a complete restart of my pc and still cannot place iron ore blocks.  

Tried creating a new world, and same issue, cant place the blocks.  

Any suggestions would be greatly appreciated! 

Thank you!

**Comment by Darkere** [comment]
What version are you on? at least in 1.12 you dont need any lenses to make starmetal. Simply placing it near a Collector Crystal ( the floating crystal in the big structure) and linking it with the linking tool worked for me.

**Comment by dhudd3** [comment]
I dont think that this is widely known i was under the impression the lens was needed also as it is what is listed under JEI with no other information available maybe something in JEI that linked to the page in the book relating to that information would help (AA has this) not trying to hijack the thread tho so i wont talk about that here anymore as for the Iron try placing it 2 block in front of the lens and using the linking tool and link them this worked for me

**Comment by GalenDudek** [comment]
I am using the 1.10 version in the Sprout Modpack. 

The big problem for me is that I cant even place the iron ore.  I have gone all over the world I am playing in, trying to place it, and just discovered that I cant even place gold ore.... So maybe I should check with the modpack creator(s), since I can place the blocks in a world with only the Astral Sorcery mod... I dunno.

**Comment by Doomgull** [comment]
Yeah, if you can't place any ores anywhere in that pack, doesn't sound like AS.

**Comment by Doomgull** [comment]
@GalenDudek did you ever figure out the issue with the modpack preventing you from placing down ores?

**Comment by GalenDudek** [comment]
@Doomgull Yeah, thanx man.  I put the ores in a mechanical user and it works like a charm.  Thanx mate!

**Comment by Doomgull** [comment]
Apparently the "Dungeon Tactics" mod prevents ore blocks that were doubled from being placed back down normally, so that's the root cause mod.
