### ISSUE TITLE
[1.12.1] When I open the guidebook, all of the text in my entire game glitches out.

### ISSUE THREAD

**Issue by yamiaainferno** [HellFirePvP/AstralSorcery#288]
![screenshot_3](https://user-images.githubusercontent.com/30121755/30575541-2bcf1778-9cc7-11e7-827b-2fff19eff6a6.png)
![screenshot_1](https://user-images.githubusercontent.com/30121755/30575563-4fe06310-9cc7-11e7-9743-3fa62d629a37.png)
![screenshot_2](https://user-images.githubusercontent.com/30121755/30575571-60df54be-9cc7-11e7-8327-35959a61eb39.png)

Restarting Minecraft will fix it until I try and open the book again. What's going on?

**Comment by Doomgull** [comment]
Modpack/list? Version of AS? Optifine?

**Comment by yamiaainferno** [comment]
God, sorry. I've been sick this week and totally loopy. Barely remembered to add the MC ver. I do have Optifine-- I looked up other issues here on the wiki regarding it, since your specific mention made me think it was a likely culprit. Turning off fast render fixed the issue.
