### ISSUE TITLE
PaintedBiomes BiomeProvider overridden by AS

### ISSUE THREAD

**Issue by Sukasa** [HellFirePvP/AstralSorcery#289]
I have a world with PaintedBiomes providing the biome map.  Normally it works fine, however if Astral Sorcery is present in the world, then the biomes used are regular ones, and PB's wrapped BiomeProvider has no effect.  There are no crashes and no apparent errors or warnings in the log.

This is Dimension 0 only, which is in the supportedSkyRenders list and NOT the weakSkyRenders list.

**Comment by Doomgull** [comment]
Version of mods and forge installed?

**Comment by Doomgull** [comment]
@Sukasa any update for this? Don't see any movement on the paintedbiomes issue tracker for this particular issue, just checking if this still needs to be open.

**Comment by HellFirePvP** [comment]
Most likely connected to  #271 - If that's the case, it's resolved with the next update
