### ISSUE TITLE
cant craft luminous in 1.12.1

### ISSUE THREAD

**Issue by falizure** [HellFirePvP/AstralSorcery#293]
as stated when placing a crafting table beneath the crystal the light never binds and you cant craft astral recipes in it, i assume this is due to the version difference as you only as of yet support 1.12, assuming that is the issue will we see a 1.12.1 version soon? I'm usually the last person to push for new versions but it would be extremely helpful.

**Comment by HellFirePvP** [comment]
most likely a modpack issue as one of the mods in your pack is conflicting with the logic of AS.
Try removing mods that are affecting the crafting table in some way. Also refer to the other (tons) of issue-reports on here regarding the same problem which almost always resulted in it being another mod interfering.

**Comment by Doomgull** [comment]
@falizure Any update on this? I've yet to find an instance you described that wasn't resolved by improper use of mechanics or something with the pack doing something odd. Mostly skyblock packs, actually.

**Comment by falizure** [comment]
im sorry, between my poor pc and heat and personal issues i have not been able to properly test lately, and no its not a skyblock pack, someone testing it for me said they were able to make them once and then when i asked them to detail how they did it they weren't able to repeat it.
