### ISSUE TITLE
Journal not functioning

### ISSUE THREAD

**Issue by zetosuru** [HellFirePvP/AstralSorcery#294]
For the last two days, I've been trying to use the in game guide for the mod, but after crafting the starlight infuser I was and still am unable to zoom into a section.

**Comment by zetosuru** [comment]
For the record, this is on the latest version of modern sky block, and the server is running sponge

**Comment by Doomgull** [comment]
Is it only mouse scrolling, or also keyboard scroll with W\S?

What hardware platform (pc, mac, linux)?

**Comment by Doomgull** [comment]
@zetosuru Any update for the above information?
