### ISSUE TITLE
Sky Render issues

### ISSUE THREAD

**Issue by TheFoxOfShadows** [HellFirePvP/AstralSorcery#295]
The custom sky is conflicting heavily with shaders. I turned off the custom sky in the config and that resolved the issue only on a local game. The server overrides the config setting of the client. A suggestion for resolving the conflict would be to allow the clients to ignore server settings dealing with the custom sky. I am using the current version of Kuda Shaders (v65.56). I am also using v1.4.5 of Astral Sorcery

Relevant screenshot below.

You will notice the discoloration of the sky at the cross hair. The horizon and celestial bodies follow the cross hair. I can confirm that it is not a hardware issue, both of my friends can confirm same issue and our rigs are vastly different.

![2017-09-25_01 26 34](https://user-images.githubusercontent.com/13582374/30801409-0ca92048-a198-11e7-8cd7-6e85e33b2858.png)

**Comment by Doomgull** [comment]
The server config doesn't override client config for that option by default unless something else is forcing it to do so.

**Comment by TheFoxOfShadows** [comment]
I have some more info after some testing. I made a world with the default config in a local world. I closed the client and changed the white list in the config to have the overworld blacklisted.

I the restarted my client and entered the local world again. The sky glitch still persisted. I then removed the mod, and unsurprisingly, the sky glitch disappeared.

The surprising thing happened after closing my client and re-added the mod with the config change. The sky glitch then reappeared.

**Comment by TheFoxOfShadows** [comment]
I looked through the closed issues. (Which were hidden be default.) I am attempting one of the fixes mentioned in the report. I am curious how the above post's result happened though....

**Comment by Doomgull** [comment]
The answer to this may be "Doomgull, consume more caffeine, its too early", but I don't follow. You changed the config and the glitch happened, removed the mod an the glitch disappeared, then readded the mod with the same config where it glitched and are surprised the glitch is still around?

**Comment by TheFoxOfShadows** [comment]
Here is a step by step with numbers:
1) New install with default config.
2) I changed the white list in the config to black list the overworld. This resulted in no change in the render glitch.
3) I removed the mod completely, including config. This fixed the rendering.
4) In the same world, I re-added the mod and the modified config. The glitch returned.

The expectation is that once removed, all data from the removed mod is removed. Then the clean re-installation of the mod "should" be loaded with the config changes. However that isn't what happened.

Also, using the weak render option fixed the issue. I suggest putting a note in the config notating the shader conflict and the fix.

**Comment by Doomgull** [comment]
If you didnt remove the config file when you pulled the mod, it wont regen it. Thats default mc behavior.

And thats what the weakrender option is for.

**Comment by TheFoxOfShadows** [comment]
The config was removed btw.

**Comment by Flinkymeat** [comment]
Doomgull, this aint shader's fault, fix it yourself
