### ISSUE TITLE
Can't craft Celestial Crafting Table

### ISSUE THREAD

**Issue by 0Chris0** [HellFirePvP/AstralSorcery#296]
![2017-09-25_11 30 45](https://user-images.githubusercontent.com/30864381/30802075-a37e5842-a1e5-11e7-9b9d-55163fe0b2d0.png)

**Comment by 0Chris0** [comment]
And yes the Crystal was Attuned

**Comment by Doomgull** [comment]
Red bar means yout altar isn't formed correctly. Use the star in the corner of the journal page to make sure you have the correct number of each block, and double check the layout. You can rotate the image to view the bottom, as well.

That also doesn't look like the correct marble pieces in the recipe.

**Comment by 0Chris0** [comment]
thanks

**Comment by Doomgull** [comment]
Going to go ahead and close this one out, come by the discord server if theres any other questions/issues.
