### ISSUE TITLE
Suggestion : crystal lamp and armor

### ISSUE THREAD

**Issue by fflortix** [HellFirePvP/AstralSorcery#297]
Hi,
You can add a marble lamp (it can be craft with 8 marble and 1 crystal or aquamarine).
And an armor in cristal ?

**Comment by Winrylive** [comment]
I think using illumination powder in the recipe would be a good choice and I'd 2nd a lamp/lantern recipe.

**Comment by Doomgull** [comment]
@fflortix @Winrylive The 1.7 and later versions have an armor included in them now, at the farthest progression point. It's not made of crystal, however.
