### ISSUE TITLE
[SUGGESTION] Aquamarine block, for decoration

### ISSUE THREAD

**Issue by Sunconure11** [HellFirePvP/AstralSorcery#298]
I like the color of aquamarine, would it be possible to have it in block form for decoration?

**Comment by Hypsellis** [comment]
I add to the list the reasonating gem block, crystal block, and celestial crystal block.

**Comment by HellFirePvP** [comment]
aquamarine: maybe yea.
resonating gem: NO
any crystal: HELL NO - have you actually played with the mod?!
starmetal block: likely.

**Comment by Hypsellis** [comment]
Yes I did, a really nice mod. I just give suggestions, you're free to do whatever you want, no need to be so agressive.

**Comment by Machadeon** [comment]
Also add chisel support for multiple textures for these blocks! Not sure who owns that, you or the chisel developers, but these would make for fantastic design opportunities. Also a great place to use those not-good-enough-for-the-main-texture texture ideas.

**Comment by Sunconure11** [comment]
Unlimited Chisel Works might be best suited for such a thing IMO, Machadeon (addon by Asie that adds support for various mods into chisel.)
