### ISSUE TITLE
Player unable to log in to server - FMLIndexedMessageCodec exception caught

### ISSUE THREAD

**Issue by ProsperCraft** [HellFirePvP/AstralSorcery#299]
https://gist.github.com/ProsperCraft/746a1043480f682ae99b0502be24d695

astralsorcery-1.12-1.6.1.jar
forge-1.12.2-14.23.0.2497

**Comment by HellFirePvP** [comment]
Any update on this? Does it still happen?
Networking issues like this are not exactly great to debug as the setup on forge's networking internals are not something i can directly influence...

**Comment by Doomgull** [comment]
ATM closed this saying no longer an issue in latest ATM version. Closing this as well.
