### ISSUE TITLE
Add a configuration option to turn off modifications to the sky

### ISSUE THREAD

**Issue by Sunconure11** [HellFirePvP/AstralSorcery#3]
Due to multiple mods existing to change the skybox (Garden of Glass and Stellar Sky come to mind; and lets not forget shaders), there are players that might want to use the skyboxes from those mods as opposed to this one. A config option to turn it off might be okay for such players.

**Comment by HellFirePvP** [comment]
I do recognize you by your avatar :P As discussed, this will be in the next update~

**Comment by HellFirePvP** [comment]
Well, it's not 100% only visual though... (Things i remember before going to sleep)

When you disable it you cannot see Solar & Lunar eclipses... :| And you kinda need the Solar eclipse for *something*

**Comment by Sunconure11** [comment]
What about an item that can detect eclipses, regardless of the skybox? Maybe tweak the telescopes some more to allow some usage during an eclipse?

**Comment by p455w0rd** [comment]
I would advise against this option @HellFirePvP ..This is an immersive mod...A huge part of the immersion is the sky you provide...As you said, it provides more than just visuals...Trust me when I say this mod is going to be big enough that people will no doubt choose to use this mod over a mod like GoG. Other mods exist to create the skyblock experience without the sky rendering being altered. If it wasn't pivotal to the core theme and functionality of this mod, I would agree with @Sunconure11 ..

**Comment by Sunconure11** [comment]
The telescope provides most of the functions already (constellations can be viewed using the telescope), the skybox is only required for eclipses, according to @HellFirePvP. An item or something that allows for detection of eclipses under differing skyboxes could resolve this. Also I'd be one of those players that would favor a different skybox over this one.

**Comment by Saereth** [comment]
Options are always great, and I do agree with p455w0rd here for the most part. My only concern is with conflicting sky renders like stellar sky and mods like it (potentially coro's weather mod). It's pretty great in it's own right. Would it be good if both could work together? Sure, but if not... Look up in the night sky and seeing a sky filled with the constellations you discovered is a very rewarding and important part of this mod's immersion from my experience.

**Comment by Sunconure11** [comment]
Stellar Sky does have an API to go along with it (Stellar API), but something tells me it wouldn't look right if we just plopped the constellations from this mod onto Stellar Sky's skybox. However this option is coming in the future, I talked with the dev of this mod on Discord.

**Comment by HellFirePvP** [comment]
That then raises the question if i should do integrated skyrenders at all where i only render the constellations. If Stellar Sky will change the moon cycles completely, a co-existance of StellarSky & AstralSorcery might not be feasible anymore, since, well, the mod is _dependent_ on the moon phases to cycle once every 8 days. If that's not true anymore from a visual point of view, i'm uncertain how i should fare with Stellar Sky since it'd be completely incompatible.

**Comment by Sunconure11** [comment]
I'd say the config option might still be a better option, but you could ask Abastro for configs to allow one to change the lunar cycle:

https://github.com/Abastro/StellarSky

You could also extend your mentioned... feature to allow for lunar observation, too.

**Comment by Winddbourne** [comment]
The skybox isn't the core of GOG and the botania config already has an option to turn it off; or to force it to be active in regular Botania worlds.

**Comment by Sunconure11** [comment]
So I guess its shaders plus Stellar Sky and other mod with a differing skybox then.

**Comment by Winddbourne** [comment]
I'm thinking the visual moon cycle issue is something @HellFirePvP is going to want to deal with somehow anyway as texture packs exist to change the image of the sun and moon. A lazy or romantic sun and moon pack creator might have it set to the full moon every night or something weird. 

For that matter if you are using a graphic overlay for the constellations over the GOG skybox you have a bunch of other planets and things in the sky that can really obscure the sun and moon. I actually put out a texture pack for minecraft 1.7.10 called "clear sky block" which adds in a custom sun and moon while also making the rainbows and extra planets invisible when using the GOG skybox. 

I do like the idea of an overlay for the constellations that could be used with different skyboxes as a player option too. It may not be necessary for GOG, but what if you want to use the skybox from void world control? 

In 1.7.10 I only had one skybox option to use. Now I technically have three with this mod. More may come out. :)

**Comment by HellFirePvP** [comment]
_Maybe as a heads-up_

This is partially adressed now.. kinda. I included a config option-list which allows for specification of dimension id's in which (if the dimension is supposed to have sky-rendering and constellation cycles enabled with 'skySupportedDimensions) a dimension can be marked to have a "weak" sky renderer. Which means AS will try and preserve the previous sky-renderer and only render constellations on top of the current one.

Is that sufficient for now? (Granted if it actually works with all kinds of skyboxes)

**Comment by Sunconure11** [comment]
I'll test it on top of Stellar Sky's skybox, to see what happens. Unlikely to work, but I'm willing to test anyways.

Also, what software did you use for the crystals in this mod?

**Comment by ruyanve** [comment]
Weak sky render is working with custom texture pack skyboxes! Cheers for that!
http://i.imgur.com/BDBiTv8.png

Now off to make moon phases...

**Comment by HellFirePvP** [comment]
The weak skyrenders should work with most skyboxes out there and not cause issues with rendering-bugs anymore.. As far as stellar sky goes, it seems they're using 'uncommon' methods to do their skyrendering and as a result, the constellations rendered either don't render at all due to missing calls as a result of stellar sky's rendering OR they get rendered too early and stellar sky renders on top of the constellations, again due to unexpected rendering behavior of stellar sky. I will not start writing custom integrations for all kinds of skyboxes, so integration for that won't happen.

As the rest of this, 'adding' the constellations onto the existing skybox doesn't 'hurt' your experience.
