### ISSUE TITLE
Crash when using Extra Utilities 2's quantum quarry

### ISSUE THREAD

**Issue by ZeWolfTah** [HellFirePvP/AstralSorcery#301]
Minecraft Version: 1.12.2
AstralSorcery Version: astralsorcery-1.12-1.6.1
Forge Version: forge-1.12.2-14.23.0.2503
Extra Utilities 2 Version: extrautils2-1.12-1.6.3

Crash Report:
https://pastebin.com/AyEbHF8C

Crash Description:
When using the quantum quarry from extra utilities 2, it was working fine for about 5 minutes until the game suddenly crashed to the launcher. The game instantly crashes again when trying to open the world.

Thankfully this happened on a test world where I was viewing what the quarry could collect on my modpack.

When looking up the crash, the only related report I was able to quickly gather was this:
https://gist.github.com/Phizzhead/b63d142adf22b3787cf29e035ecf1a75

The crash still occurs both with and without optifine or betterfps (wanted to test if either of those was causing the crash but neither was)

Edit:
Found other threads now referencing this issue
https://github.com/rwtema/extrautilities/issues/1572

**Comment by Doomgull** [comment]
#240 #238 #271  not new, please search next time. Fixed in upcoming release. Workaround is to add mining dim to weakrender list.

**Comment by ZeWolfTah** [comment]
Apologies for not searching enough, was in a bit of a rush and I mostly spent my time checking if I was using the most recent versions of the mods.
