### ISSUE TITLE
bug of journal

### ISSUE THREAD

**Issue by kohtahirano** [HellFirePvP/AstralSorcery#305]
when using the mod journal all that is text in the game suffers a bug
by pressing the f3 key the info of the world is unreadable and happens with everything ... I can not know how many items I have, or as the items are called etc.
to solve it I have to close the minecraft and open it again but if I open the newspaper again the bug returns .... I changed the verions of the mod but it still appears and I do not know what else to do ....
PLEASE HELP!!!!!!

**Comment by Doomgull** [comment]
Disable OptiFine's "Fast Render" option.
