### ISSUE TITLE
Lightwell still seeing a crash with TE Ducts, possibly servo-related

### ISSUE THREAD

**Issue by Doomgull** [HellFirePvP/AstralSorcery#309]
[ATM 3 #231](https://github.com/AllTheMods/ATM-3/issues/231)

Duct attached to lightwell didn't crash, but adding a servo to the duct resulted in a crash everytime the chunk loaded.

https://gist.github.com/dmodoomsirius/994e59451304e78be35e6c045fdabc22

ATM 4.2
AS 1.6.1

**Comment by HellFirePvP** [comment]
Bug got fixed for version 1.7

**Comment by HellFirePvP** [comment]
Closed on ATM's end, closing here.
