### ISSUE TITLE
[Question] Where is the Rock Crystal Ore?

### ISSUE THREAD

**Issue by DestinyPlayer** [HellFirePvP/AstralSorcery#31]
I'm sorry that I have to ask this, but I'm seriously worried that my game is bugged. The journal says that Rock Crystal Ore is found really really deep down. But I even blew up several Nova Cataclysms at various levels of depths near the bedrock, yet I've found zilch in terms of Rock Crystals. Aquamarine I've managed to find, but only a single ore deposit, everything else I've found within altars. 
I live at the Extreme Hills biome, and nearby is the Alps biome from Biomes O' Plenty.
So... Are they intended to be this rare? Or is there a miscompatibility between BOP and AS?

**Comment by Elvarion** [comment]
Not using BOP on our server but they seem really rare. Maybe 1-3 ores in every other chunk.
If you run around at Night on the surface with the Resonating Wand in your Main Hand (Offhand does NOT work)
You will see "smoke" rise from the ground, Dig down there and look at bedrock level. I found them there. They also spawn under the first bedrock layer so you may need to dig around.
Not sure how this works if you have something like "FlatBedRock Mod" installed.

**Comment by DestinyPlayer** [comment]
Ooh. I didn't know that thing with the Resonating Wand. Thank you. Is this not written down in the journal, or have I just missed it?

**Comment by Elvarion** [comment]
It is written down under the Resonating Wand entry, Second page. It's not word for word, little cryptic that engages you to go around and explore some.

Hope you find them :)

**Comment by HellFirePvP** [comment]
Rock crystal ores are designed to be rare and without using the mod, you won't find them reliably or mine them automatically. The Resonating wand is the tool that'll help you find them yea.
