### ISSUE TITLE
Evorsio bugs

### ISSUE THREAD

**Issue by Taintacle** [HellFirePvP/AstralSorcery#310]
1. Stacking destruction doesn’t seem to work properly. Hitting something at a sword’s attack speed doesn’t accumulate more than one stack. When spam clicking hard (like 7 times a second) the stacks apply, but only inconsistently.

2. Static Charge isn’t dealing extra damage to the entity the player is striking, only to the one being chained toward. Not sure if bug or not, but judging by the config description it is a bug. Also a suggestion, this perk should be able to be triggered even if no other mobs are nearby so you aren’t at a disadvantage in a 1v1 or bossfight.

**Comment by HellFirePvP** [comment]
For the next update:

1. The per-stack duration got increased
2. This is indeed a mistake, i forgot to call it for the originating entity...

**Comment by Taintacle** [comment]
Found another bug with Static Charge, it targets players and damages them even when pvp is off.
