### ISSUE TITLE
Iridescant Altar crash

### ISSUE THREAD

**Issue by FractalPhoenix** [HellFirePvP/AstralSorcery#311]
On the ATM3 modpack, and while using the iridescant altar, whenever anyone interacts with the constellation/attunement area of it, then they crash to desktop. It does it whether it's the starfield, or the slot.

[crash-2017-10-19_00.19.01-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/1405893/crash-2017-10-19_00.19.01-client.txt)

**Comment by HellFirePvP** [comment]
Outdated issue of Version 1.6.1 - you might want to consider updating to 1.7

**Comment by HellFirePvP** [comment]
Uh. well. Not much more to say here - *closing issue*
