### ISSUE TITLE
[1.12.2 AS version 1.7] Grindstone no render on re-log

### ISSUE THREAD

**Issue by VallenFrostweaver** [HellFirePvP/AstralSorcery#313]
On logging into a single player world the grindstone(s) I placed are not visible but for the bounding box until right clicked (or left clicked with a weapon).

**Comment by PG-Fuury** [comment]
Similar issue, but already resolves on approaching

**Comment by Doomgull** [comment]
Yes, its cause is known, just not an easy fix.
