### ISSUE TITLE
[1.12.2 Astral v 1.7] Armara powered Ritual Pedestal reflects Vortex wand projectile

### ISSUE THREAD

**Issue by VallenFrostweaver** [HellFirePvP/AstralSorcery#314]
If you use a Vortex wand within range of an Armara crystal powered Ritual Pedestal the projectile is pushed outside the protection range as if it were a hostile mob.

**Comment by Doomgull** [comment]
This sounds like an awesome feature for longer reach, to me, lol.

**Comment by HellFirePvP** [comment]
Fixed with v1.7.2

**Comment by VallenFrostweaver** [comment]
No it wasn't. :/   I see no change.


Also, the resulting byproducts from the Chalice get pushed away as well. Here's a screen shot of the items getting pushed away from an Armara altar set up.
![as](https://user-images.githubusercontent.com/13642054/32220995-ae79cdb4-be2b-11e7-9b56-6fbbfcf751e4.png)
