### ISSUE TITLE
Constelacion Horologium Error

### ISSUE THREAD

**Issue by mediumdamphir** [HellFirePvP/AstralSorcery#316]
La constelacion nunca ha aparecido ademas he intentado con todas las faces de la luna y no aparece luego cuando la busco en el telescopio parpadean unas estrellas que no cuadran con la constelación y mi juego se cierra

**Comment by murapix** [comment]
Solo aparece en la noche despues de una eclipse solar.

No se espanol tan bien, y el autor no lo sabe nada de espanol, asi que si pudiera usar ingles, seria apreciado.

**Comment by Doomgull** [comment]
In addition to murapix's information, the eclipse only happens once every 36 days.
