### ISSUE TITLE
Problem with Static Charge perk

### ISSUE THREAD

**Issue by Taintacle** [HellFirePvP/AstralSorcery#319]
Evorsio’s Static Charge perk ignores PvP being turned off and shocks nearby players when I’m trying to kill mobs. This has caused me to kill my friends many times by accident. It also doesn’t credit the player for the damage, meaning that mobs killed by it don’t drop specific items, and mobs don’t aggro toward the player when shocked by it, etc.

**Comment by HellFirePvP** [comment]
#310

**Comment by Taintacle** [comment]
Sorry, thought you didn’t see the comment I put on my earlier post

**Comment by Doomgull** [comment]
We get emails for all of them.
