### ISSUE TITLE
Lesser Constellations not showing in Telescope UI.

### ISSUE THREAD

**Issue by muffinkiller1** [HellFirePvP/AstralSorcery#321]
Despite having all the necessary papers, and having a mounted telescope, it's not showing me any of the lesser constellations when I look for them in the night sky, despite saying that I've at least seen them on their respective papers (they show what moon phases they're most visible on.)

I'm playing with the Horizons 3 modpack on FTB, so I'm not sure if this is mod interaction or what.

**Comment by Doomgull** [comment]
Attune yourself, it's basic progression lock.

**Comment by VallenFrostweaver** [comment]
Is your telescope open to the sky above it?
Are there no blocks nearby (blocks adjacent to the telescope or too close can cause no stars to show at all)?
Are you seeing any stars at all or a blank screen?
Are you able to find any constellations (like the bright ones)?

**Comment by HellFirePvP** [comment]
> they show what moon phases they're most visible on

despite you having discovered them? Well, that's something i gotta fix...
