### ISSUE TITLE
Game breaking bug with Evorsio in new update

### ISSUE THREAD

**Issue by Taintacle** [HellFirePvP/AstralSorcery#322]
The static charge perk now triggers itself, causing massive loops that end up dealing a thousand damage or even more. It also still ignores pvp being turned off. The massive damage has only happened on my server against a player so far, but in a singleplayer test the perk was still triggering itself, as I hit one mob, it chained toward another, but it didn’t stop and chained toward another mob.

**Comment by Taintacle** [comment]
Oh, and if it’s relevant, pvp is turned off on my server

**Comment by HellFirePvP** [comment]
Fixed with v1.7.2
