### ISSUE TITLE
JEI handling of blocks from this mods seems to be a bit... off

### ISSUE THREAD

**Issue by Sunconure11** [HellFirePvP/AstralSorcery#324]
![screenshot 2017-10-28 23 40 48](https://user-images.githubusercontent.com/5614902/32140513-85c3c67a-bc39-11e7-84a2-2bdda8a97ca3.png)

They seem to clip a bit out of their tabs, as seen in the top.

**Comment by HellFirePvP** [comment]
Happens with GUI scale AUTO - auto is known to mess up a lot of GUIs across mods that are not 100% standard. In this case, the space needed to display the recipe for the gui scale is just not big enough. Thus it's centered as well as possible given the circumstances.

tl;dr: change your GUI scale or be fine with it *shrugs*
