### ISSUE TITLE
[1.7.1] Book Crashing on Zoom In

### ISSUE THREAD

**Issue by Goatasus** [HellFirePvP/AstralSorcery#326]
The mod's book/manual has been crashing consistently when I try to zoom up to the discovery tech tree. This has happened on a brand new world, so not much has gone on in it so far. This doesn't happen with version 1.7 (the version just before the one I'm reporting about).

[Crash Report](https://pastebin.com/cBdh0Drg)

As a note I have the following mods running with it:
ActuallyAdditions-1.12.1-r121
astralsorcery-1.12.2-1.7
AutoRegLib-1.3-14
Baubles-1.12-1.5.1
BetterThanBunnies-1.12.1-1.1.0
BiomesOPlenty-1.12.2-7.0.1.2297-universal
Bookshelf-1.12.2-2.2.468
Botania r1.10-349
BrandonsCore-1.12-2.3.3.132-universal
Chameleon-1.12-4.1.3
ChestTransporter-1.12-2.8.7
chiselsandbits-14.9
Clef-1.12.2-7.0.0
CodeChickenLib-1.12-3.1.3.313-universal
CoFHCore-1.12-4.3.6.14-universal
CoFHWorld-1.12-1.0.1.8-universal
DarkUtils-1.12.2-1.7.176
Decocraft-2.5.2_1.12.2
deepresonance-1.12-1.4.9
Draconic-Evolution-1.12-2.3.4.265-universal
DrZharks MoCreatures Mod-12.0.3
ElecCore-1.12-1.8.430
embers-0.221
fairylights-2.1.1-1.12
FastLeafDecay-v14
flatcoloredblocks-mc1.12-6.6
GooglyEyes-1.12.2-7.0.2
GravityGun-1.12.2-7.0.1
Hats-1.12.2-7.0.2
HatStand-1.12.2-7.0.1
iChunUtil-1.12.2-7.0.2
ImmersiveEngineering-0.12-74
ImmersiveEngineering-0.12-74-core
jei_1.12.2-4.8.0.105
journeymap-1.12.2-5.5.1
malisiscore-1.12.2-6.1.7
malisisdoors-1.12.2-7.1.1
Mantle-1.12-1.3.1.21
mcjtylib-1.12-2.4.4
Pam's HarvestCraft 1.12.2a
PartyParrots-1.12.1-1.0.0
PortalGun-1.12.2-7.0.1
Psi-r1.1-58
Quark-r1.3-114
RebornCore-1.12.2-3.4.8.138-universal
RedstoneFlux-1.12-2.0.1.2-universal
rftools-1.12-7.12
rftoolsctrl-1.12-1.6.8
rftoolsdim-1.12-5.05
RoguelikeDungeons-1.12.2-1.8.0
StevesCarts-1.12.2-2.4.10.49
StorageDrawers-1.12.1-5.3.3
Streak-1.12.2-7.0.0
TConstruct-1.12-2.7.4.34
ThermalExpansion-1.12-5.3.6.20-universal
ThermalFoundation-1.12-2.3.6.16-universal
TrailMix-1.12.2-7.0.0
twilightforest-1.12.2-3.3.202-universal
WailaHarvestability-mc1.12-1.1.12
Wawla-1.12.2-2.5.246

**Comment by HellFirePvP** [comment]
Fixed with v1.7.2
