### ISSUE TITLE
[1.7.1] Game freezes when using standing telescope the night after a solar eclipse

### ISSUE THREAD

**Issue by Scironex** [HellFirePvP/AstralSorcery#328]
When using the standing telescope block the night after a Solar Eclipse, the game freezes. The game doesn't crash - there's no corresponding crash log - it just hangs up until as such a time that I close it manually. The same freeze does not occur when using a hand telescope.

Other mods:
JEI 4.8.0.105
ProjectE PE1.10

**Comment by HellFirePvP** [comment]
Uh... i got a suspicion what's going on..
It *only* happens at that time? Have you tried a different SP world with a different seed and set the time to the night after a solar eclipse? That would be useful to know.

**Comment by Scironex** [comment]
Different SP world, different seed, post-eclipse night: No issue. I could use the telescope without a problem.

**Comment by HellFirePvP** [comment]
Ugh. just as i expected.. >_> Welp, that's gonna be ugly to fix. Thanks for the report.

**Comment by HellFirePvP** [comment]
1.7.3 will potentially have a somewhat-fix for that. So if you still have that world + know the date/timestamp for that, you could then try again once i release that new version and tell me if that works then...

**Comment by HellFirePvP** [comment]
Has been adressed seemingly as no more information is being added to this...

**Comment by belathus** [comment]
This might be related: we're using the telescope to trace constellations on a server. After we traced 3 of them, the server's TPS dropped to 0.08. We're using Astral Sorcery on 1.10.2 version 1.4.5.

**Comment by Doomgull** [comment]
Unsupported version, and no, not related. Not enough constellations to have caused this in the 1.10 versions.
