### ISSUE TITLE
[1.12 ver. 1.61] Collector crystal beam locations copied while copying worlds

### ISSUE THREAD

**Issue by wilfurdmcwargnash** [HellFirePvP/AstralSorcery#329]
Copying a world copies light beams from crystals as well.

Other Mods:
Mercurius
Actually Additions
Extra Utilities 2

**Comment by HellFirePvP** [comment]
What else would you expect? Copying a world would entail copying all data that's relevant to that world doesn't it?

**Comment by Doomgull** [comment]
@wilfurdmcwargnash anything else for this, or am I going to archive this issue?
