### ISSUE TITLE
Rock crystals generated by treasure shrines don't drop anything

### ISSUE THREAD

**Issue by superfluke** [HellFirePvP/AstralSorcery#331]
Rock crystal ores generated by the treasure shrine do not drop any rock crystals when broken:
![2017-11-01_21 11 57](https://user-images.githubusercontent.com/20022336/32305174-489ef314-bf4a-11e7-839d-46df0679bad5.png)
![2017-11-01_21 12 04](https://user-images.githubusercontent.com/20022336/32305176-4a40ebbe-bf4a-11e7-92cf-3e3c6d8e90f1.png)

However, if you use a piston to move the rock crystal ore out of the ore generating TE, then the rock crystals drop normally:
![2017-11-01_21 14 54](https://user-images.githubusercontent.com/20022336/32305193-67735744-bf4a-11e7-9a43-0c54acc2d8ad.png)

AS: astralsorcery-1.12.2-1.7.2
Forge: Forge Mod Loader version 14.23.0.2522

**Comment by HellFirePvP** [comment]
Ah, yea, i forgot to label that. it's fixed in dev.
