### ISSUE TITLE
Craft tweaker recipes for AS tables not working

### ISSUE THREAD

**Issue by superfluke** [HellFirePvP/AstralSorcery#334]
While using crafttweaker to add recipes to the discovery and attunment tables registers them in jei, the actual items do not output. Tried 2 recipes on 2 different AS tables with different starlight values but neither would output.
![image](https://user-images.githubusercontent.com/20022336/32411555-4620ef18-c1b4-11e7-99fc-8bb783b8414b.png)
![image](https://user-images.githubusercontent.com/20022336/32411556-4a4bf0a6-c1b4-11e7-9cd0-a86b032ce174.png)
Here's an example of the script used, starlight needed is set to 100, half the value of the sample recipe:
`mods.astralsorcery.Altar.addDiscoveryAltarRecipe(<extrautils2:endershard>*8, 100, 60, [
    <evilcraft:dark_spike>, <evilcraft:dark_spike>, <evilcraft:dark_spike>, 
    <evilcraft:dark_spike>, <minecraft:ender_pearl>, <evilcraft:dark_spike>,  
    <evilcraft:dark_spike>, <evilcraft:dark_spike>, <evilcraft:dark_spike>
    ]);
`
AS: astralsorcery-1.12.2-1.7.2
Forge: Forge Mod Loader version 14.23.0.2522

**Comment by HellFirePvP** [comment]
Future reference: Player trying to craft the recipe was missing progression.
