### ISSUE TITLE
Floating crystals are treated as full blocks

### ISSUE THREAD

**Issue by SnowShock35** [HellFirePvP/AstralSorcery#335]
Hi,

I believe to have found an issue with Astral Sorcery. Here are the details.

#### Issue details

- Minecraft 1.12.2
- Minecraft Forge 14.23.0.2529
- Astral Sorcery 1.7.2

#### Issue description

You have the ability to place blocks like torches on the sides of Floating crystals which doesn't make sense when it's bounding box is less than a block and neither is it a full block. 

#### Issue solution

Make it so that it's not seen as a full block and that other blocks cannot be placed on it's faces.

#### Issue media

![Issue media #1](https://ss.blamesnow.co.uk/2017/11/1509905361-28b77f63.png)
![Issue media #2](https://ss.blamesnow.co.uk/2017/11/1509905704-24831a69.png)

**Comment by HellFirePvP** [comment]
That's.... quite amusing actually

**Comment by SnowShock35** [comment]
@HellFirePvP Indeed. The odd thing is doors don't work. If you try to place a door on the crystal it will just break and drop the door. o_O
