### ISSUE TITLE
Feature Request: Way to toggle "Increased Fertility" and "Mineral Enrichment"

### ISSUE THREAD

**Issue by LazerusKI** [HellFirePvP/AstralSorcery#336]
While those two perks are very powerful, it can be very annoying when you build with Stone, or when your animal farm constantly grows.

So a way to toggle them on and off would be great, either with a hotkey or by clicking the perk-node again

**Comment by LazerusKI** [comment]
Also to add to the list:
Mantle of the Stars with Aevitas effect.
Just destroyed my farm by replacing a plant with a tree...

**Comment by Doomgull** [comment]
Review of all suggestion issues for compiling an updated ticket master list shows duplicate to #428 , previously rejected.
