### ISSUE TITLE
[1.12.2 v1.7.2] Evorsio eventual game crash. (Small Albedo interaction) Ritual Anchor bug.

### ISSUE THREAD

**Issue by VallenFrostweaver** [HellFirePvP/AstralSorcery#338]
I took an enhanced Evorsio crystal and focused it on a Ritual Pedestal with an Evorsio infused crystal. The Ritual Pedestal was already set up with a Ritual Anchor above it that was linked to another Anchor down underground. I added lenses to focus the Pedestal and have Evorsio show on the ground around it. All stats were max (creative). I went to the area that the quarrying was happening and it was working. As time went on the lag started from all the items being created. I used "/kill @e[type=item]" to destroy the blocks that were there and proceeded to wait and repeat the command every now and then. Eventually the blocks stopped being broken and the game slowed down as if massive items were lagging me out. I used the command again and no items were removed. Lag got worse. I tried to get to the Anchor to break it but lag was so bag I was getting 1 frame every 20 seconds. I tried to log out. It took me 5 minutes. I tried to log back in and it sits there at 0% loading dirt screen.

Disabled Albedo and it all started working again and my frame rate came back up.

Second thing of note and **the main issue** here is that the Anchor was quarried in the process. I tried to get back to the original Pedestal to shut it off but instead I ran into a similar lag issue as before but it was actually due to the liquids (lava, starlight, water) all flowing together nearby and all the blocks being effected by the quarrying at the base Ritual Pedestal (which also would be someone's base in most scenarios).

Last thing of note is that this has potential to cause massive amounts of blocks to be in the world potentially causing a game crash. Perhaps a block replacement mechanic or each block broken is placed in an inventory specified. Just some prelim ideas.

Forge 14.23.0.2515
JEI, Journeymap, The One Probe

![07-11-17 4-30-52 pm](https://user-images.githubusercontent.com/13642054/32505057-2524ef36-c3d9-11e7-928b-c14498e37422.png)
![07-11-17 4-30-15 pm](https://user-images.githubusercontent.com/13642054/32505058-2541a0f4-c3d9-11e7-833d-4bfe9747fbd2.png)

**Comment by HellFirePvP** [comment]
The ritual anchor will now at least no longer break itself.
As for the mass amount of dropped items, any specific solution you had in mind?... imean.. i still have to drop the results... "linking" it to a inventory to dump the results into is not really a great option.. :|

**Comment by Doomgull** [comment]
Perhaps setting it to an internal inventory that itcan be piped out of when finished boring? It has theoretical maximums for the number of blocks that can it can bore, correct?

**Comment by VallenFrostweaver** [comment]
How about teleporting the dropped items in the same area that are effected back to the ritual platform (even if it's linked via ritual anchor) should help. Maybe even adding a anti-starlight item that vacuums things in might be in order but I would think a push lens or two could get the items off the platform and into an inventory (probably via hoppers or the like).

Another idea might be to have it actually dig in a line straight down instead of randomly patterned around it. This would allow items to stack better at the very least. Though I will admit it's not as cool that way. 

One last suggestion idea.. it could effect things slowly over time and take a chunk like the infused axe/pick does and draw them in toward the center, It slowly moves out farther and farther taking a chunk at a time. This would give a themed effect that matches the mod and also would allow items to stack.

**Comment by HellFirePvP** [comment]
Alright, it now "teleports" the result back onto the pedestal/anchor. Now while that doesn't solve that whole thing, it at least solves the issue of hundreds of items lying around somewhere random...

The other part is that the chunk is constantly redrawn due to blocks being removed somewhere... which kinda is due to how this thing works :| Not sure what else to do regarding this..
