### ISSUE TITLE
Cave illuminator questions

### ISSUE THREAD

**Issue by Feltdisc** [HellFirePvP/AstralSorcery#339]
I placed the cave illuminator and it worked great the only problem is it worked too great I had found a mob spawner that I was using for evilcraft blood farming. Now with the lights the spawners wont spawn. Is there a way to remove lights or prevent certain areas from being lit up?

**Comment by Doomgull** [comment]
Lights persist after illuminator is removed. Remove illuminator, place blocks where lights spawned to remove them.
