### ISSUE TITLE
Craft Tweak integration doesn't handle item transformers

### ISSUE THREAD

**Issue by Mewr11** [HellFirePvP/AstralSorcery#341]
Item transformers, such as .giveBack() and .transformDamage() are completely broken in Altar/Starlight crafting recipes. Transformed items are simply ignored for such crafting recipes. No errors are thrown by either AstralSorcery or CraftTweaker; as such, no error logs can be reported.

Relevant snippet of ZenScript:
[https://pastebin.com/N3AAV60W](https://pastebin.com/N3AAV60W)

If you need anything else regarding the issue, contact me at mewr.11.coding@gmail.com

**Comment by HellFirePvP** [comment]
Whoops wrong issue to label.

Regarding this, it would require a massive rewrite internally to support this... I'll have a chat with Jared to get the .giveBack() to work, but i'll not support anything other than that as it requires - as said - a huge rewrite to accomodate for CraftTweaker's special "itemstacks" or oredict or whatever. Sorry, but that's as much as i can reasonably say.

**Comment by jaredlll08** [comment]
Transformers are only for VANILLA crafting tables (and similar, so like the tinkers crafting station). So neither Astral or Crafttweaker is doing anything wrong, it is just not possible for them to be supported in every single thing.

**Comment by HellFirePvP** [comment]
On that note: Closing the issue/suggestion/bug report
