### ISSUE TITLE
[1.12.2] Containment Chalice delete buckets

### ISSUE THREAD

**Issue by Kuraen** [HellFirePvP/AstralSorcery#342]
If you right click with just one bucket in hand to a chalice it works fine but if you more than one in hand and right click it only give you one bucket of liquid and the rest of buckets are deleted.
![2017-11-08_19 22 23](https://user-images.githubusercontent.com/33462308/32567246-ff13e634-c4ba-11e7-92b3-758705e1987e.png)

**Comment by VallenFrostweaver** [comment]
Can confirm, clicking on a chalice (with fluid in it) with any number of a empty buckets stacked results in a single filled bucket and the rest of the empty stacked buckets are destroyed.
