### ISSUE TITLE
[SMP] Server DCs

### ISSUE THREAD

**Issue by Lukas45** [HellFirePvP/AstralSorcery#343]
We recently updated to Astral Sorcery 1.7.2, and been having some DCs related to it.
We told the server not to play with AS for the time being due to this.
The first case that happened, everybody DCd, and were instantly kicked out again upon joining. Error message in console being: [FML]: There was a critical exception handling a packet on channel Astral Sorcery.
Restarting the server resolved the issue, for now.

I wasn't personally there, so I don't know exactly what happened, but it happened again today with one of our server members, although it didn't affect the entire server this time.
He was looking through the Telescope Stand, when he DCd. He was able to log back in without issues, and I didn't experience it.
This is what the console printed:
https://pastebin.com/5GCRkYkx
The "SimpleChannelHandlerWrapper exception" was there 10 times, identical to the one in the paste.
These error messages doesn't get put into the log files, so they only show up in the Server Console.

I will try to duplicate the "perma-DC" once the server is empty, and play around to see what could cause this.

And also, Vicio is broken in the night sky (first time looking up at it, it gave a huge FPS lagspike) - looks fine in a telescope
![2017-11-08_18 06 59](https://user-images.githubusercontent.com/4707702/32573273-b41a0402-c4cd-11e7-8fef-27026aeecbb2.png)

**Comment by Doomgull** [comment]
Is this only happening when people look through the telescope? There's an indev fix if so. If it also happens without using telescopes, going to need server logs for that because its a separate issue.

**Comment by Lukas45** [comment]
The first time happened without telescope and affected the entire server (even people with no/little AS progress).
I've been waiting for the server to be empty during my available hours, which hasn't happened yet,
but will do further testing when that happens (as I don't want to interrupt their gameplay)

**Comment by Lukas45** [comment]
So we've been trying pretty hard to replicate this, with no luck.
So for now, I'm going to close this issue, and open a new one if it happens and I manage to get server logs.
