### ISSUE TITLE
Crystal Sword loses all enchantments when infused at the Starlight Infuser

### ISSUE THREAD

**Issue by RobotLobster** [HellFirePvP/AstralSorcery#344]
Issue as stated in title. An infused crystal sword returning to a normal crystal sword after depleting its energy will retain its enchantments. Re-infusing this crystal sword will wipe all enchantments from it.

**Comment by VallenFrostweaver** [comment]
Not that me understanding the issue matters but energy? Infused crystal swords will recharge after each use (1-2 seconds) and should never lose their infusion. To increase cutting use a grindstone (also reduces size based on purity). To increase Size, submerge it in a source block of liquid starlight (which will also reduce the cutting). What method are you using to lose the infusion?

**Comment by Doomgull** [comment]
Losing enchantments when infusef is intentional, its a new item at that point.

Otherwise, need the info Vallen pointed out.

**Comment by RobotLobster** [comment]
Update: I just had it happen again. I was fighting a group of zombies and the sword had just cooled down. I swung at a zombie and it performed the "item switch" animation and became a normal crystal sword (and did not trigger the AoE burst effect of the Infused Sword). This did not coincide with a loss of cutting from use. If it helps at all, this is on a SMP server running the same version of Forge, Minecraft, and AS.

**Comment by HellFirePvP** [comment]
As hinted at in the journal, it'll revert. That can be configured however, so it's up to the pack maker.

Regardless, the problem that it loses its enchantments and other nbt data while being "upgraded" is not intentional and i thought i've fixed this once before...
