### ISSUE TITLE
Suggestion: crystal shield and upgraded bow/arrows

### ISSUE THREAD

**Issue by tyrianblade** [HellFirePvP/AstralSorcery#345]
Title says it all. I love the mod and these two feel like the only things missing.

**Comment by VallenFrostweaver** [comment]
There already is a "crystal shield" equivalent with the Armara attuned Resonating wand (and it also can do more than a plain shield and has infinite durability). You can also attune yourself to Discidia and unlock perks to do more damage with all arrows.

**Comment by tyrianblade** [comment]
Oh haven't tried the armara wand yet. The discidia perk is cool, and I like the damage I guess I just wanted a shiny bow 😀. Something that looked fancy.

**Comment by HellFirePvP** [comment]
Yea, normal shield & bow/arrows will not happen.

If anything, there might be a somewhat non-obvious equivalent (as vallen said, the armara resonating wand is basically a stronger "shield").
