### ISSUE TITLE
[Suggestion] Advanced Starlight Infuser

### ISSUE THREAD

**Issue by DishonoredRaven** [HellFirePvP/AstralSorcery#346]
An upgraded multi-block structure that acts as a better version of the starlight infuser. The main perk of this would be acting much like a furnace where you can put in multiple of the same item, and then it will continually produce the product. Crafting Resonating Gems and Starmetal Ore one at a time is very tedious and time consuming, even though they are increasingly used as the mod goes on. For the most part, this is a time-sink. Aquamarines, like clay in other mods, limit the speed of progression by forcing you to look in very specific locations and continually travel out further and further to find more. However, if you have stacks of these already like me, converting these to resonating gems can take a painfully long time. Other benefits from the upgraded structure, such as lower chance of using liquid starlight, could also be implemented, but the main addition I would like to see is the ability to craft multiple Resonating Gems and Starmetal Ore at once, rather than having to sit here and babysit them, which can especially be infuriating when Horologium is on its way and you need more of these materials. Just creating them can waste half the night, and then you have to wait for the next eclipse.

**Comment by Doomgull** [comment]
Chalices can accelerate infusion speed, and mechanical users can automate the rod use.

Additionally, you dont need to use an infuser for starmetal: just placing iron ore where starlight has already been linked from a crystal lets you automate that very easily.

**Comment by DishonoredRaven** [comment]
Ah, I haven't delved much into chalices yet. The page is rather confusing and vague, so I'm doing testing to see what they actually do. As for the starmetal, I've been using one of the permanent crystals from the temples, but I still find myself having to constantly place them and mine them. A mechanical user would work, but I was thinking more along the lines of making something that would aid this process as if it were a standalone mod, not combined in a modpack. As a standalone mod, there doesn't seem to be a way, at least currently, to truly automate this process. Of course, it's just a suggestion, and I'll probably go ahead and use the mechanical user and chalices, just seemed like something I thought would be useful for the mod as its own entity.
