### ISSUE TITLE
found a bug

### ISSUE THREAD

**Issue by HopeGamer** [HellFirePvP/AstralSorcery#348]
so i have the latest astral sorcery and when i open the book and zoom in after a while the hearth/hunger/oxygen/crosshair/attack indicator/armor all glitch and adapt the texture of starlight

**Comment by Doomgull** [comment]
Turn off FastRender in Optifine. Known issue for a very long time, thank optifine for it.

**Comment by HopeGamer** [comment]
i dont use optifine


2017-11-11 14:42 GMT+02:00 Doomgull <notifications@github.com>:

**Comment by Doomgull** [comment]
Then there's something else modifying gui rendering similar to Optifine. This is not a normal bug, but a rendering conflict from another mod.
