### ISSUE TITLE
[1.10.2 - 1.1.3-beta] Increased Fertility perk from Aevitas not functioning?

### ISSUE THREAD

**Issue by VallenFrostweaver** [HellFirePvP/AstralSorcery#35]
Tested with 2 chickens and 2 cows. In 1 square shared with me and 2x2 shared with me and no breeding happened.

**Comment by Febilian** [comment]
If this is the perk where animals randomly breed or grow up near you, I've definitely had it doing stuff when I'm wandering about,  so I'm pretty sure it's functional. It just seems to be a fairly low chance at first and is kind of spontaneous.

**Comment by HellFirePvP** [comment]
I suspect it's the same as the other perks: They just have a small chance of doing something due to them being more or less for free.
