### ISSUE TITLE
[1.12.2]Ore/Structure gen

### ISSUE THREAD

**Issue by Kasparsunekaer** [HellFirePvP/AstralSorcery#350]
Minecraft version: 1.12.2
AS version: 1.7.2
Forge version: 1.12.2-14.23.0.2528

Other mods: 
Aroma1997Core-1.12.2-1.3.0.2.b128
Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37

Mining dim id: 6
Mining dim Biome: Mining Biome

    # the Astral Sorcery-specific worldgen will only run in Dimension ID's listed here. [default: [0]]
    S:worldGenWhitelist <
        6
     >
    # Set the BiomeTypes (according to the BiomeDicitionary) this structure will spawn in. [default: ]
     S:BiomeTypes <
       Mining Biome
    >

So in the mining dim, none AS Ores spawns, and only smallShrine structures and there still spawns Marble in overworld

**Comment by Doomgull** [comment]
Biome name is wrong.

**Comment by Kasparsunekaer** [comment]
Its the name that ModTweaker gives me when running /mt biomes

**Comment by HellFirePvP** [comment]
biome name != biome type. that might be your problem. there is no type called "mining biome"

**Comment by Kasparsunekaer** [comment]
Okay, but the 
# the Astral Sorcery-specific worldgen will only run in Dimension ID's listed here. [default: [0]]
S:worldGenWhitelist <
    6
 >
still doesnt work

**Comment by Doomgull** [comment]
How are you determining it is not working? It works for me. Pull out the wand at night time, you'll see the plumes unless it wasn't generated with the config set.
