### ISSUE TITLE
Multiple issues on latest Forge version

### ISSUE THREAD

**Issue by Alchimous** [HellFirePvP/AstralSorcery#353]
When running AS on the latest version of Forge(14.23.0.2541 as of time of submitting) the vortex wand will not send the grapple forward, while still depleting the charge of the wand. The issue disappears when rolling Forge back to an earlier version(14.23.0.2534). As well, the Lucerna ritual will not prevent mob spawns. Rolling back also fixes this issue.

**Comment by Alchimous** [comment]
Actually it seems I jumped the gun on the Lucerna ritual. While the vortex wand absolutely fixed itself, the Lucerna ritual still isn't working.

**Comment by Doomgull** [comment]
Try going back to 2531.

**Comment by Doomgull** [comment]
Move up to latest forge and 1.8.1 and see if still issue.

**Comment by Alchimous** [comment]
All of my versions have been above 2501, I have updated to 1.8.2 and will test again shortly.

**Comment by Alchimous** [comment]
Both issues seem to be fixed with 1.8.2 and 2544.
