### ISSUE TITLE
[1.12.2 v1.7.2] Mantle of Bootes flares get in the way and can kill you

### ISSUE THREAD

**Issue by VallenFrostweaver** [HellFirePvP/AstralSorcery#354]
While having these little guys around you is excellent they get pushy and will push you off cliffs or certain distances. It can be especially frustrating when trying to escape via jumping a gap and they bump you off to your demise. They also get in the way any time I try to walk around bumping into me and I often will swing my weapon and kill one or many with an infused crystal sword.

Suggestions for solution:
1. Make them not be able to move you (they pass through blocks/entities).
2. More distance when following you and a minimum distance so they are pushed away from you (like an invisible bubble) when you move.

**Comment by Lukas45** [comment]
+1 at suggestion 1, for Spectral Tools. Got pushed in Lava earlier.
