### ISSUE TITLE
Fosic Resonator causing internal server error (Ver: 1.8.1)

### ISSUE THREAD

**Issue by Skalfred** [HellFirePvP/AstralSorcery#356]
Creating a Fosic Resonator causes the server to kick me and refuse to let me rejoin until the item is removed from my inventory. This is happening on a server that has updated from 1.7.2.]

[https://pastebin.com/0g9aMEeA](https://pastebin.com/0g9aMEeA)

**Comment by Doomgull** [comment]
Forge version, and other mods on the server and their versions?

**Comment by Skalfred** [comment]
[https://pastebin.com/jQpMzBVt](https://pastebin.com/jQpMzBVt)

**Comment by Skalfred** [comment]
[https://pastebin.com/T56Dm0ee](https://pastebin.com/T56Dm0ee)

**Comment by HellFirePvP** [comment]
Derp. My stupidity strikes once more.
