### ISSUE TITLE
[1.12] Crash when generating the world with no Strongholds

### ISSUE THREAD

**Issue by Dilnu** [HellFirePvP/AstralSorcery#358]
Hi, there I'm using Astral Sorcery version 1.7.2 on Forge version 14.23.0.2529

I'm using No Woldgen Gen 5 You version 1.0.6 https://minecraft.curseforge.com/projects/no-worldgen-5-you to disable Stronghold generation.

This resulted in a crash within base Minecraft code called by your Treasure Shrine worldgen code. Crashlog here: https://pastebin.com/8uyZY2s8.

I think this could be fixed by using a try catch block in your code.

**Comment by xannor** [comment]
This is labeled as fixed next update, is that 1.8.4? If it is I can report that the #361 still occurs with that version, it the fixed version has not been released yet I will check again at the next release.

**Comment by Doomgull** [comment]
New logs from 1.8.4, forge version, etc.

**Comment by xannor** [comment]
Here is the Crash log:
https://gist.github.com/xannor/e3485046f2ffd0f455b576fe3c5a1ac5

Forge is 2757 .
