### ISSUE TITLE
[Suggestion] Mantle ability toggle

### ISSUE THREAD

**Issue by Lukas45** [HellFirePvP/AstralSorcery#359]
The ability to toggle the Mantles attunement ability on/off

I attuned my Mantle to the Pelotrio constellation, because it sounded pretty cool.
So I went to dig out a small area in my base that would lead to my AS area with a Tinkers hammer.
First 18 blocks I broke (which is 2 swings), it summoned like 9 spectral tools (which may be a bug? That many tools for that few blocks), which began mining everything in reach.
While pretty funny, they didn't quite mine where they were supposed to, like my glass dome :D

**Comment by HellFirePvP** [comment]
The ability toggle is called wear the mantle or don't wear it. :P
