### ISSUE TITLE
[1.10.2 - 1.1.3-beta] Extended Reach perk from Discidia not functioning?

### ISSUE THREAD

**Issue by VallenFrostweaver** [HellFirePvP/AstralSorcery#36]
NOTE: This may be as intended behavior. If so, please close the issue.
The reach ability is not allowing the extra reach with melee weapons but it does work with tools (ie. hoe, pick, etc).

**Comment by HellFirePvP** [comment]
1) it's from Aevitas :P
2) It is intended. It should only extend the player's interaction range, not attack range.
