### ISSUE TITLE
Crash when using Tree Beacon with Integrated Dynamics' Menril Saplings

### ISSUE THREAD

**Issue by Darksilver78** [HellFirePvP/AstralSorcery#364]
Server / Client will crash when using Menril Saplings in the Tree Beacon. 

Modpack: Horizons III v1.2.0

How to replicate: Place Tree Beacon and 1 Menril Sapling. Bone meal the sapling until it's grown and becomes the 'ghost' Menril Tree. Place second Menril Sapling, when it grows (bonemeal or not) server/client will crash.

**Comment by Darksilver78** [comment]
[crash-2017-11-17_21.40.38-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/1484323/crash-2017-11-17_21.40.38-server.txt)

**Comment by Doomgull** [comment]
Considering the weirdness I've seen out of those trees with other harvesting methods, somewhat shocked the tree beacon processed it into a ghost tree at all.

**Comment by Dinerell** [comment]
Just nothing gets mixed up: Menril Spalings are from Integrated Dynamics and not Industrial Foregoing

**Comment by HellFirePvP** [comment]
That is indeed correct ^

**Comment by Darksilver78** [comment]
My bad, good catch!

**Comment by HellFirePvP** [comment]
Not on my end. Handing it over.

**Comment by josephcsible** [comment]
https://github.com/HellFirePvP/AstralSorcery/blob/a58d238dad64c9ed26d673a05fa13317eb186545/src/main/java/hellfirepvp/astralsorcery/common/tile/TileTreeBeacon.java#L149

https://github.com/HellFirePvP/AstralSorcery/blob/a58d238dad64c9ed26d673a05fa13317eb186545/src/main/java/hellfirepvp/astralsorcery/common/tile/TileTreeBeacon.java#L163

Are those `||`s supposed to be `&&`s? I get stuck in an infinite loop on the first one.

**Comment by josephcsible** [comment]
I found no less than 3 bugs that all conspire to cause this. They should all be fixed, but fixing any one of them will resolve the issue.
