### ISSUE TITLE
CraftTweaker Integration Error

### ISSUE THREAD

**Issue by Andvee** [HellFirePvP/AstralSorcery#365]
caught a typo in the code...

`mods.astralsorcery.Altar.addAttunmentAltarRecipe`

Works as intended. Correct spelling of attunement `.addAttunementAltarRecipe` will throw no such static member error.

Error found in 1.10.2-1.4.5

**Comment by HellFirePvP** [comment]
Not providing support for 1.10.2 and 1.11.2 versions.

Regardless, as it persists into newer versions, i'll roll out the possibility to make it work with both "Attunement" and "Attunment"

**Comment by HellFirePvP** [comment]
Both methods are added for the next version so either will work as of 1.8.3 then
