### ISSUE TITLE
[1.12.2] Lightwell compatability with pipes from other mods

### ISSUE THREAD

**Issue by Dragnier** [HellFirePvP/AstralSorcery#368]
I've been trying to get your Lightwells to work with a couple of modded pipes. However, they seem to be incompatible. I'm trying to put together a modpack for myself, family, and friends and while there are certain mods that _do_ have pipes that work with lightwells, those mods don't fit the theme for the pack. The two mods I've tried that would work thematically do not work with your lightwells.

Those two mods are Embers and Immersive Engineering. I have posted issues with both mods. Embers has not yet responded and I don't know why their Fluid Extractor will not connect to the bottom of a lightwell even though their regular pipes do. Immersive Engineering refuses to adjust their pipes/pump to work, which I completely understand is their prerogative. IE's pump cannot connect to the bottom of a block and their pipes don't work with tanks that do not auto-output.

I'm wondering if you could find a way to help support compatibility with more pipes by making the lightwells auto-output or some other method.

I am unsure, but this may also affect the Chalice, since I am guessing it interacts with pipes the same way as the lightwell.

**Comment by VallenFrostweaver** [comment]
It does interact with the chalice on the bottom as well. You should note that the latest version of AS will auto output starlight being made in a lightwell to a nearby chalice. No pipes needed.

**Comment by Dragnier** [comment]
I get that, but before you reach that point in the mod, tanks are useful and being unable to move liquid starlight to tanks without manually using buckets is a bit harsh considering the pack I'm designing is already intended to slow down progression.

**Comment by Doomgull** [comment]
Maybe you should use one of the many other mods out there that don't intentionally mess with pulling fluid from below a container? IE pumps not pulling from above because LOOK at them. They clearly aren't intended to pull through the pump motor head.

Embers pipes...dunno. Talk to Elucent and see if he has any idea. This is not a new issue, though, and it works for every other pipe that handles liquids I've seen so far.

**Comment by Dragnier** [comment]
As stated, I have put in an issue with Embers, but I don't have much hope of a fix there since the latest commit was back in June and the most recent label/response to an issue was in September. This was a simple request as a last ditch effort and I understand it isn't a bug. I just wanted to see if there could be some compatibility adjustments or not. Never hurts to ask, as they say.

This is really more of a thematic issue. It just so happened that Embers and IE were the most thematically suited to what I was trying to make and neither worked with the lightwells.

**Comment by HellFirePvP** [comment]
Uh. Yea. Everything has been said here.

**Comment by Normal69** [comment]
Tried out 2 configurations:
1) iron barrel with input on top + fluid pipe + lightwell on top of eachother, pipe connects
2) lightwell on top of liquid pipe, beside it a rightly configured pump with power and redstone signal, pipe beside it, under it an iron barrel, all pipes connecting input/output configured well

None of them work. Tested liquid starlight between 2 iron barrels connected by a pipe, liquid starlight flows.
Embers fluid extractor with a redstone connets to the bottom of the lightwell, with a redstone signal and a fluid gauge it seems to extract the liquid, gauge shows 240.

**Comment by Doomgull** [comment]
Pump has to actively draw from the bottom of the lightwell. Everything there is working as intended. Address this with iron barrels if you think it should be working.
