### ISSUE TITLE
CraftTweaker intergration for removing Starlight Infusion recipes does not work.

### ISSUE THREAD

**Issue by The-Arcanian** [HellFirePvP/AstralSorcery#369]
Tying to use this script: https://gist.github.com/The-Arcanian/4497ca4b092358562410eaa4445711b4

But the recipes are not removed.

Tested with:
Crafttweaker 4.0.10
AstralSorcery 1.8.2
Forge 14.23.0.2529

**Comment by Doomgull** [comment]
Have you reloaded the pack/server after making the changes? Does it report any errors into the log when loading up with that script in place?

**Comment by HellFirePvP** [comment]
Your fault for not reading the documentation of it properly:

> // Parameters:
> // OutputStack

I don't know of any recipe to remove that outputs 3 iron ore or 3 gold ore.

**Comment by The-Arcanian** [comment]
Ok, throwing blame around does not help anything, and comes across as uppity.

But I did make an oversight, so thank you.
