### ISSUE TITLE
Crash at random points

### ISSUE THREAD

**Issue by gchpaco** [HellFirePvP/AstralSorcery#37]
I'm infusing starmetal, and the game is flatlining every now and again.  Crash log attached.

[crash-2017-02-20_18.39.22-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/788952/crash-2017-02-20_18.39.22-client.txt)

**Comment by HellFirePvP** [comment]
Ugh, i thought this was fixxed >_> well, time to have another look..

**Comment by HellFirePvP** [comment]
*hopefully* adressed next update
