### ISSUE TITLE
Perk Issues - Insane Reach / Phantom Blocks

### ISSUE THREAD

**Issue by LazerusKI** [HellFirePvP/AstralSorcery#370]
MC version: 1.12.2
AS version: 1.8.2 (got the perks in i think v1.7)
Forge version: 2531
Modpack: ATM3

With Insane Reach i mean that i noticed a weird behaviour after having the far reach perk for a while.
For some reason i started with just a few blocks more range, but after a few days i suddenly had like 32 blocks placement range.
Resetting the perks and picking another one didnt solve it, i still had that range even without having perks at all.
Maybe an issue with the additional reach from creative? like toggeling creative on and off pushes the perk-range up over and over again?
Resetting my Playerdata solved it (only playerdata, not the AS data)
Would it be possible to add a code that "resets" the range value to vanilla when you remove the perks?

Another issue i noticed was also with the reach perk but also with stacking miningspeed perk from the destruction tree.
Soft blocks that you can onehit tend to become "phantoms" that you cant see but that are still there until you have a block update or reload the chunk and so on. With the reach perk it only happened beyond "normal" reach and only on blocks like sand. The stacking mining speed on the other hand happened only with stone-types that i mined with a pick. So far im not sure if thats an issue with the perk or with something else since i couldnt find a reliable way to replicate it.

**Comment by HellFirePvP** [comment]
Same as #404 

>I am uncertain (so i leave this issue open for now) however i included a potential fix for this in 1.8.3 - uncertain if it will work as expected as i am unable to reproduce this issue however i do have an idea about where it might originate from. So once 1.8.3 is released, i'd like to ask you to try and reproduce the issue and then tell me if it got fixed with that or not.... :|
