### ISSUE TITLE
GUI messed up

### ISSUE THREAD

**Issue by TrialDragon** [HellFirePvP/AstralSorcery#371]
My GUI got messed up as soon as I opened the astral tome I am on the latest 1.12.2 version of the mod.
![2017-11-20_13 58 38](https://user-images.githubusercontent.com/31419708/33043779-6a63b092-cdfb-11e7-8b84-7d231cbc0112.png)

**Comment by Doomgull** [comment]
There is a reason optifines page' says to disable fastrender if you get any gfx weirdness.

**Comment by TrialDragon** [comment]
Disabling Fast render does nothing at all to fix my issue.
![2017-11-20_14 16 15](https://user-images.githubusercontent.com/31419708/33044402-abfd87e2-cdfd-11e7-9b5b-ce15ec6be274.png)
![2017-11-20_14 16 26](https://user-images.githubusercontent.com/31419708/33044403-acb1b334-cdfd-11e7-9d72-498258dd0fb7.png)
