### ISSUE TITLE
Perk issues - Hiking boots

### ISSUE THREAD

**Issue by derpingdolly** [HellFirePvP/AstralSorcery#373]
MC version: 1.12.2
AS version: 1.8.2
Forge version: 2531
Modpack: DW20 1.1.0

After death Hiking boots wont work. It is still activated in Astral Tome. 
Who needs fins is still working fine.

**Comment by Doomgull** [comment]
Did you change dimensions on death? If so, known issue triggered by dimension changing.

**Comment by derpingdolly** [comment]
No, I died during daytime in the same chunk my spawn is (by falling from a high place).

**Comment by HellFirePvP** [comment]
Same as #404 

>I am uncertain (so i leave this issue open for now) however i included a potential fix for this in 1.8.3 - uncertain if it will work as expected as i am unable to reproduce this issue however i do have an idea about where it might originate from. So once 1.8.3 is released, i'd like to ask you to try and reproduce the issue and then tell me if it got fixed with that or not.... :|
