### ISSUE TITLE
Items disappear instantly after crafting on the altar or infusing

### ISSUE THREAD

**Issue by MariaTargaryen** [HellFirePvP/AstralSorcery#376]
While crafting anything on iridescent altar(not sure about previous ones), the result disappears instantly after crafting without dropping out of the altar itself. Same happens with the infuser. Items go in, but the result is gone into thin air. 
Before this bug I placed a second enhanced collector crystal and connected it to the altar. Removing it didn't solve the problem.
It might be the server's issue, but if its not, it's a terrifying bug
MC: 1.12.2, AS: 1.8.2, direwolf20 pack 1.1.0

**Comment by Tuvermage** [comment]
We had a similar issue happen on our server. it wouldn't let us throw items and items thrown form inv got deleted. The resolution was to unload the chuck, wait about 5 minutes and return to the chunk, that fixed the issue on our servers. Same direworf20 1.1.10

**Comment by Doomgull** [comment]
@MariaTargaryen Can you see if Tuvermage's suggestion resolves it on your end? I know ATM3 had issues with dormant chunk caching on an earlier version of forge previously, I'm mildly interested if it's the same issue here.

**Comment by MariaTargaryen** [comment]
Nope, the issue remains

**Comment by HellFirePvP** [comment]
Does the issue still remain actually? I heard rumors about FTBUtil's chunk loading being derp and causing issues related to chunk loading & unloading logic.
