### ISSUE TITLE
No luminous crafting table recipe in Just Enough Items

### ISSUE THREAD

**Issue by ghost** [HellFirePvP/AstralSorcery#377]
The luminous crafting table doesn’t show its recipe in JEI, and the journal doesn’t even appear in JEI.

**Minecraft version**: 1.12.2
**Forge version**: 14.23.0.2531
**Modpack**: [All the Mods 3](https://minecraft.curseforge.com/projects/all-the-mods-3), version 5.1
**Astral Sorcery version**: 1.8.2
**Just Enough Items version**: 4.8.1.120

**Comment by Doomgull** [comment]
Yup. Where's the one you spawn in with?

**Comment by PapiDimmi** [comment]
I’m playing [All the Mods 3](https://minecraft.curseforge.com/projects/all-the-mods-3), and I didn’t get a journal when I first spawned.

**Comment by Doomgull** [comment]
That's because all books in ATM3 are in the akashic tome, crafted with a piece of dirt. Open an issue on their end about that not being clear. I'm tired of telling them that.

**Comment by PapiDimmi** [comment]
Oh, I forgot about that.

Also, it seems as though the journal’s name was changed to “astral tome,” too.

Anyway, shouldn’t the luminous crafting table have a recipe in JEI? I’m new to Astral Sorcery, so maybe I’m missing something again.

**Comment by PapiDimmi** [comment]
Oh, I forgot about that.

Also, it seems as though the journal’s name was changed to “astral tome,” too.

Anyway, shouldn’t the luminous crafting table still have a recipe in JEI?

**Comment by Doomgull** [comment]
No, because then people open tickets for "why won't this work?" because not using a crystal-linked table.

**Comment by PapiDimmi** [comment]
Couldn’t you just make that clear by putting some sort of disclaimer in JEI?

**Comment by HellFirePvP** [comment]
This once used to work when JEI's recipe pickup was more lenient and it picked up general shaped recipes from the registry. This is now connected to specific (can't remember if they're abstract or not, doesn't matter here, but they're not interfaces.) classes and thus it'll not pick up AS' shaped & shapeless recipes. I looked into that once and it took me the better part of the day to conclude that this would require a rewrite of the entire internal recipe handling of mine. Which i would rather try to avoid. So... This will require more research into the issue and finding potential workarounds. Atm, i can't do much about it so.... RTFM
