### ISSUE TITLE
[1.10.2] Server Crash on Client Login

### ISSUE THREAD

**Issue by chezpaul** [HellFirePvP/AstralSorcery#378]
Hey there, This mod looks really nice but I can't seem to be able to launch it.
When I launch the server, (Forge 2511 on 1.10.2), it launches fine but when I login with client, I crash after about 5 seconds with [this error message](https://pastebin.com/4QmrRMT3).

If I take out Astral Sorcery, server works fine, put it back in, get the same exact crash every time.

Mods used: [Here](https://pastebin.com/99HiTBJ6)

Thanks

**Comment by Doomgull** [comment]
Galacticraft is causing that, per the logs.

Also, unsupported version of AS.

**Comment by MJRLegends** [comment]
No this is a astral sorcery issue https://github.com/micdoodle8/Galacticraft/issues/2891

**Comment by Doomgull** [comment]
Still unsupported version.

**Comment by MJRLegends** [comment]
Yeah but theres a simple fix the config that can be done
