### ISSUE TITLE
Suggestion from Curseforge

### ISSUE THREAD

**Issue by 63502** [HellFirePvP/AstralSorcery#38]
> Start the Journal in zoomed in mode and have an entry explaining how to use the Journal. 
-Zygus42

This would be a good way to prevent more confusion as to how to use the journal since its unique navigation method has not been used in other major mods to the best of my knowledge. At very least there needs to be a short Journal How-to on the Curseforge page. Other people may have this same bit of trouble.

**Comment by HellFirePvP** [comment]
Added a info-star to the journal that'll be there until you've attuned yourself at least once - i guess at that point you either are familiar with the mod or you've used it already.
