### ISSUE TITLE
Containment chalice bug

### ISSUE THREAD

**Issue by Coolcabbage** [HellFirePvP/AstralSorcery#382]
Placing the containment chalice underneath another block will delete the other block
It probably need some check for clear area before placing,
deletes blocks with nbt and also bedrock
Modpack : A Grim Life 2 1.1.2
astralsorcery-1.12.2-1.7.2
forge-14.23.0.2528

**Comment by Hubry** [comment]
This was fixed already in 1e11df64026d5812810ed911a6d044623e3d4a4f, update to 1.8.1 or higher.
