### ISSUE TITLE
Shift-clicking paper to book leaves ghost in inventory (minor)

### ISSUE THREAD

**Issue by TheQuadShot** [HellFirePvP/AstralSorcery#383]
MC 1.10.2
Forge 12.18.3.2511
AstralSorcery 1.10.2-1.4.5

Sorry if this isn't your bug.
If I shift-click a Constellation Paper into the Book it leaves a ghost image behind and it counts as inventory space. It will "clear" if I click on them. It does not occur if I drag/drop them.

Image
https://imgur.com/ffb5Zsm

ModList
https://pastebin.com/T2ENwqHZ

**Comment by Doomgull** [comment]
That's going to be whatever mod grants the shift-click not properly handling inventory code.

Don't shift click blank papers into your inventory, if its doing that shift-clicking out.

**Comment by TheQuadShot** [comment]
That's what I originally thought(mouse/inventory tweeks), However I can shift-click them into chests/crates/other mod containers, and I don't have the issue. It only occurs when I shift-click them into the book. btw the pages aren't blank and the shift-click option/function is a vanilla mechanic in 1.10.2 anyway.

**Comment by TheQuadShot** [comment]
I've just re-confirmed this with just your mod installed. So there can't be a conflict, unless the problem is in Forge?

**Comment by Doomgull** [comment]
There's been a lot of forge bugs recently due to changes, wouldn't shock me. 

Regardless: AS doesn't handle any inventory movement. AS just provides an inventory object. If there's a problem moving things and the client getting desynced from the server (which is what causes those ghost items), that cannot possibly be an AS issue.

**Comment by TheQuadShot** [comment]
Please don't misunderstand me, I'm just not sure what to file with Forge. I can't tell them to load a mod to "see" the issue. I hope that makes sense. I just want to make sure I file bugs in the proper place and with enough information to be helpful. I can't file a bug with them that says: shift-clicking some TileEntity's from inventory to container leaves cloned ghost in some cases... I guess I'm asking what is the difference between the book and a chest/crate?
