### ISSUE TITLE
Crash when activating step assist perk.

### ISSUE THREAD

**Issue by Lanternglow** [HellFirePvP/AstralSorcery#388]
When doing personal attunement, I chose the travel constellation. I wanted to see how it compared to the Botania sojourner's sash and whether the overlapping effects would stack. After wandering around for a bit, I noticed that I had gained level 5. So I activated the swim speed perk and then the step assist perk. At that point the game crashed.

I was wearing the Botania sash at the point that I activated the perks. Not sure if that is important, but I think it is significant enough to mention.

I was able to restart the game and load the world again. The step assist perk was still marked as active, but was not functioning (once I took off the Botania sash). I think I saw a similar issue for this part already logged on the issue tracker.

Output messages and stack trace attached:
[AstralSorceryCrash.log](https://github.com/HellFirePvP/AstralSorcery/files/1503669/AstralSorceryCrash.log)

**Comment by uecasm** [comment]
Fairly sure this crash log is related.  In my case I'd been using the perk and the sash for quite a while without issues, but then one time seemingly out of the blue while using the telescope the game kicked me back to the main menu, and I was unable to re-enter that world until completely shutting down and restarting MC.

MC 1.12.2
Forge 14.23.1.2555
Astral Sorcery 1.8.3

https://pastebin.com/R0Kg3jjW

**Comment by Doomgull** [comment]
Dfferent issue, but still already being tracked. 

Also, restarting to reenter is a forge issue

**Comment by HellFirePvP** [comment]
Might be fixed with 1.8.4 - report back please in case it's still happening.

**Comment by Lanternglow** [comment]
Indeed. I just ran through the same scenario and didn't have any problems with crashing.
