### ISSUE TITLE
[Suggestion] change astral sorcery bore size

### ISSUE THREAD

**Issue by Qohelethh** [HellFirePvP/AstralSorcery#389]
When you make the neromantic focus (or whatever it's called), the hole it makes beneath the ring structure you have to build is so large that it removes all blocks from underneath the supporting pillars. If you changed the diameter of the hole to be smaller by one block on all sides, there would still be dirt underneath the pillars and it wouldn't look like it's floating in midair.

**Comment by ouroborus** [comment]
I kinda like that it does that, appearing to floating in midair. Given how it's laid out, I would've though that was normal.
