### ISSUE TITLE
AstralSocery + OptiFine = bad skies

### ISSUE THREAD

**Issue by wadiv76** [HellFirePvP/AstralSorcery#391]
I narrowed down the following sky problem to astral sorcery + optifine + forge with shaders.  I loaded just the two mods and recreated the issue in the image below.  When I removed astral sorcery the sky returned to normal.  To be completely fair to Astral Sorcery, when I removed Optifine, the sky looked fine as well just without all the pretty.  This is with Minecraft 1.12.2 using astralsorcery-1.12.2-1.8.2, Optfine preview_OptiFine_1.12.2_HD_U_C7_pre.jar(It did the same thing on previous stable versions of Optifine), and Forge 1.12.2-forge1.12.2-14.23.0.2549 using just about any shader pack, but I was using SEUS-v11.0.zip for the image. 

<a href="https://imgur.com/vZQvO2d"><img src="https://i.imgur.com/vZQvO2d.png" title="source: imgur.com" /></a>

**Comment by HellFirePvP** [comment]
I don't support shaders. There's a config option 'weakSkyRenders' where you can add the dimension ID's AS should not do its skyrender in. Add whatever dimension you need it for there and it'll - well - disable AS' skyrender there.

**Comment by AlbertoJVD** [comment]
How do you enter configurations? I am having this same issue.

**Comment by Doomgull** [comment]
It's in the config file. Try reading it. Plug in the dimension id, which is what is said in the config, and by Hellfire up above.
