### ISSUE TITLE
Starlight infuser just doesn't work anymore.

### ISSUE THREAD

**Issue by ArtOfCombat** [HellFirePvP/AstralSorcery#393]
I have a starlight infuser. I know it's set up correctly as I've checked all the liquid starlight and used it before. But it just won't work anymore! Not at night, not by day, and I'm just infusing aquamarines, which worked before. I've tried breaking the multiblock, and replacing the infuser itself.

**Comment by Doomgull** [comment]
You're missing liquid starlight somewhere, or you weren't right clicking with the resonating wand.

Assuming you didn't rebuild the multiblock incorrectly, now.

**Comment by bluev1121** [comment]
I am having this issue aswell in the newest build. I have checked and rechecked the multiblock multiple times.
![2017-11-28_18 13 49](https://user-images.githubusercontent.com/2925704/33349418-f210b2b6-d467-11e7-9e2e-ecc7fab2ea3c.png)

**Comment by Doomgull** [comment]
Version of mod, version of forge, full modlist involved in the MC instance.

I have so far been unable to replicate this behavior on my own, so I need more info for later on when I have time to dig through it more and try to get it to fail. Because employment and family takes time out of day, and HellFire's been working on code stuff.

**Comment by bluev1121** [comment]
[Ancientcraft-1.4.zip](https://github.com/HellFirePvP/AstralSorcery/files/1512393/Ancientcraft-1.4.zip)
This is the mod profile exported from twitch launcher if you want to go that route. 
Forge 14.23.0.2550 Astralsorcery-1.12.2-1.8.2 If you don't want to use the twitch profile, I will send you the modlist. Quark is installed, but no quark marble is used. All blocks used in the multi block are Astral Sorcery.

**Comment by Doomgull** [comment]
What's the block under your infuser itself? The one surrounded by the 8 runed marble.

**Comment by HellFirePvP** [comment]
Also check the liquids around the infuser if it did consume any and you have to refill.

**Comment by forry** [comment]
Hi, I'm having same problem for FTB Direwolf20 1.12.2  v1.30 and v1.40 mod pack. Also one question, we have 8 runed marbles surrounding the lapis block and also 4 runed marbles  in the corners (diagonally) touching the inner 3x3)? If thats the case I have no other idea why it shouldn't work (short of a bug).

**Comment by Doomgull** [comment]
@forry This is better suited for the Discord channel, with screenshots.

9/10 times, you're missing one of the 12 starlight buckets

**Comment by myrriad** [comment]
I seemingly had this problem. 

What I did was that I first placed the starlight infuser, then built the surrounding multiblock. Apparently you have to place the starlight infuser last? Breaking and replacing the starlight infuser fixed it.
