### ISSUE TITLE
[Suggestion] Error indicator for multiblocks

### ISSUE THREAD

**Issue by Lilylicious** [HellFirePvP/AstralSorcery#394]
Currently, when a mistake has been made in the building of a multiblock, it can be quite the hassle tracking down the error. Perhaps some sort of particle effect could be implemented to indicate the error? I'm thinking that it could trigger when using the resonating wand on the functional block, or something similar. Right now, the multiblocks mostly just let you know if it's complete or not, without any indication of what's wrong.

**Comment by uecasm** [comment]
It would also be nice if there was a tooltip on hovering over the individual blocks in the manual.  In some of the structures it's not obvious which type of marble is used in certain places.  (Mostly looking at you, starlight infuser.)
