### ISSUE TITLE
Starlight infuser not working

### ISSUE THREAD

**Issue by bluev1121** [HellFirePvP/AstralSorcery#395]
I'm resubmitting this because the other topic is flagged as user error. I have rebuilt the multi block multiple times, I have had a friend walk around it to see what the problem is. Placed and replaced every block within the multi block, and I am sure that it isn't a problem with the building. The other user that you marked as a user error even stated that his infuser worked before, but has stopped working. I am just asking to please look into it.
![2017-11-28_18 13 49](https://user-images.githubusercontent.com/2925704/33350203-9fda59a8-d46b-11e7-8d9b-69b447b452ef.png)

**Comment by Doomgull** [comment]
#393 

Other issue isn't closed. Don't open duplicates. I've been unable to replicate the problem yet on my end. Until the ticket is closed, it's not closed, and is still being looked into.
