### ISSUE TITLE
Celestial Gateway Problem

### ISSUE THREAD

**Issue by Kamisama1337** [HellFirePvP/AstralSorcery#397]
MC Version: 1.12.2
I'm playing the Direwolf20 Pack on a Server. When i use the gateway to the end and take the gateway again to get back, i'm invisible to all players on the server. I can interact with most items and players ( hiting mobs and players or using maschines ), but i can't activate pressure plates or use the bed. When i try to use the bed i get stuck on it. I can use the chat to write but it's not recognizing that im on the bed, so i'm lying there all night. Even when it gets to daytime i can't get out of the bed, even when other players break the bed.

**Comment by Doomgull** [comment]
Version of AS and Forge?

**Comment by Kamisama1337** [comment]
Ah sorry.
AS: 1.8.2
Forge: 14.23.0.2531

**Comment by Doomgull** [comment]
Looks like a desync issue, does it resolve if you relog? Is this single-player, or on a hosted multiplayer server?

**Comment by Kamisama1337** [comment]
If I relogg the Problem is gone, also if I go to the end in any way und jump through the end portel to get back, the problem is also gone. It's on a hostet multiplayer server. Like I said other players can't see me, but i can interact with them.
