### ISSUE TITLE
Crash when loading a world: FluidRarityRegistry

### ISSUE THREAD

**Issue by Krhymez** [HellFirePvP/AstralSorcery#399]
I am having an issue when creating a world, i am getting this as the crash reason
https://pastebin.com/N9GQgAyW

Any ideas on how i can fix this?

**Comment by Doomgull** [comment]
Modlist, AS version, Forge version.

And what is this from? Probably the culprit: thut.api.terrain.CapabilityTerrain$DefaultProvider

**Comment by Krhymez** [comment]
@Doomgull  I found the issue. It is "ThutCore".  One of its recent updates changed something with chunks. I will be removing it from my pack.

More Info: it is this mod causing it. https://minecraft.curseforge.com/projects/thutcore/files/2504834

You can close this if you want. i sorted the issue out by removing it.
