### ISSUE TITLE
[Question] How does the Sky Wave Resonator work?

### ISSUE THREAD

**Issue by DestinyPlayer** [HellFirePvP/AstralSorcery#40]
Apologies, but I straight up can't figure it out. For all I know, it's an item that does nothing. I just can't figure anything about it out. I've traveled straight up kilometers with it in my arm at night. Nothing, don't notice any change at all. I just can't figure it out.

As a result I ended up with a bigass tower of a base that's built in a place where there is barely any starlight, to the point that I can't even get enough to upgrade the table at the literal top of the world, but that's my fault for not checking whether I can beforehand...

**Comment by 63502** [comment]
Hold the Skywave resonator in your hand (main and offhand slots work), and run around the world at night. Spots with more intense starlight will appear to have a kind of blue fog gather around them.

Like so:
![2017-02-23_09 59 13](https://cloud.githubusercontent.com/assets/15267053/23264463/5eecf636-f9af-11e6-8489-76e6b0fa3906.png)

They are a bit hard to spot if you don't know what to look for but they are common enough. I might even be willing to bet you may have run past one or two without even noticing.

Hope this helps! 😄

**Comment by DestinyPlayer** [comment]
Huh. I've seriously not noticed even one of those. That's funny. Now I have to either abandon the idea of having a huge tower with Astral Sorcery stuff on top, or get some stuff for easier building and relocate. Thanks a lot.

**Comment by 63502** [comment]
Sure thing.

Actually, only devices that collect starlight are affected by these spots as far as I know (I'm sure HellFirePvP will jump in and correct me if I'm wrong). Anything else can be build outside and linked up with lenses n' prisms n' thing, so a giant tower with Astral Sorcery stuff on top may actually still be plausible. You just have to build it on top of one of the spots.

**Comment by DestinyPlayer** [comment]
Well, yeah, I just already built it in the wrong place. That's what I meant.
