### ISSUE TITLE
spectral blocks not rendering in a dw20 1.12 FTB server

### ISSUE THREAD

**Issue by Aillk** [HellFirePvP/AstralSorcery#402]
After making a sky platform out of spectral menril wood and relaunching the next day they will not render. I have tried redoing, placing new blocks, going to new areas. Nothing works. my wand i s colored, but a new uncolored one gives the same results.

unsprectral-ized
![2017-11-30_16 57 39](https://user-images.githubusercontent.com/34144412/33459743-d2d308ec-d5f0-11e7-8216-9fad1dd51c3f.png)

respectral-ized
![2017-11-30_16 57 43](https://user-images.githubusercontent.com/34144412/33459762-e72d2cd2-d5f0-11e7-8b0e-a9fcc63b1139.png)

same deal on newly placed astral sorcery marble
before:
![2017-11-30_17 00 45](https://user-images.githubusercontent.com/34144412/33459803-fdf2fe4c-d5f0-11e7-9f66-ee2f8e5261a5.png)
after:
![2017-11-30_17 00 48](https://user-images.githubusercontent.com/34144412/33459806-011aafc0-d5f1-11e7-85ed-c832d8e04d17.png)

**Comment by HellFirePvP** [comment]
Did a relog change anything regarding this?
So "shifting" a block into its "spectral" form just didn't do anything to its rendering more or less is what you're saying? Or are "spectral" blocks outright invisible? Did you try to reproduce this with a smaller selection of mods?

**Comment by Aillk** [comment]
my 4th relaunch of the server fixed it guess. And i have not tried to reproduce it.
