### ISSUE TITLE
[1.12.2] Crash When Picking Up Item

### ISSUE THREAD

**Issue by TreguardV** [HellFirePvP/AstralSorcery#403]
I harvested a potato, and the game crashed when I picked the potato up.

I'm using Astral Sorcery version 1.8.2 on Forge version 14.23.1.2557. I suspect this might be some kind of weird interaction with one of the other mods I have installed.

Crash log: https://pastebin.com/i21njVaV

**Comment by ashly138** [comment]
Getting this error too with forge 14.23.1.2557 going back to 14.23.1.2556 and its working just fine.

**Comment by TimGoll** [comment]
it's a forge bug as faar as I know

**Comment by HellFirePvP** [comment]
As far as i've looked into it, it seems other mods experience the same issue with picking up items. Moreover, i saw discussions that this is a forge bug. So. Yea. marking it as such.

Older versions of forge, like ashly said, might work.
