### ISSUE TITLE
[1.12.2] 1.8.2 Cave illuminator illuminating above it

### ISSUE THREAD

**Issue by BanzaiRun** [HellFirePvP/AstralSorcery#405]
The tome implies illumination occurs beneath, but my mob spawner is being lit up from above.

Or am I being a derp?

![2017-12-01_16 12 24](https://user-images.githubusercontent.com/8942699/33491562-90d90780-d6b2-11e7-9320-4f90232429b1.png)

**Comment by HellFirePvP** [comment]
Not a bug. Its logic picks up on the same y-layer the illuminator is on and adds a random y-offset to it that ranges in +/-7 iirc. So yea.. this is possible to happen with it. However, you don't need to have the illuminator around at all times either so you can just break it after you've left it there for a while as the lights are persistent until you place another block in their space.

**Comment by BanzaiRun** [comment]
So will place it at least -7 below top layer and try to resolve, thanks.

Great mod, keep it up.
