### ISSUE TITLE
[Suggestion] CraftTweaker recipes should accept IIngredients as inputs where possible

### ISSUE THREAD

**Issue by belathus** [HellFirePvP/AstralSorcery#406]
Specifically referring to the Starlight Infusion.
```//mods.astralsorcery.StarlightInfusion.addInfusion(IItemStack input, IItemStack output, boolean consumeMultiple, float consumptionChance, int craftingTickTime);```

I want to write a recipe that allows the starlight infusion to process modded ores, but there are about 10 different types of copper ore. I'd have to write a recipe for each one without using the oredictionary. Something like below:
```mods.astralsorcery.StarlightInfusion.addInfusion(<ore:oreCopper>,     <immersiveengineering:metal> * 3,    false, 0.05, 200);   # Copper```

**Comment by HellFirePvP** [comment]
Derp. This is 2 lines to fix. Doom would you put that on the todo list? thanks in advance.
