### ISSUE TITLE
Opening Astral Tome

### ISSUE THREAD

**Issue by DarkHook23** [HellFirePvP/AstralSorcery#409]
The issue occurs upon opening the Astral Tome when it is opening to the general start page (the galaxy navigation) where the icons displaying my hunger, hearts, armor, and the crosshair turn to white, glimmering boxes. This only occurs when opening the original start page. If I were to open any other page (i.e. the constellation page or the recipe pages from closing the book on a recipe) the displaying bar is completely fine. When I go to the Navigation page, the boxes take over as a display.

**Comment by HellFirePvP** [comment]
Optifine. Disable fast render.
