### ISSUE TITLE
[Bug?] Grievous Wounds

### ISSUE THREAD

**Issue by Elvarion** [HellFirePvP/AstralSorcery#41]
Unlocking the Grievous Wounds Perk allows you to inflict a bleed on your enemies.
This bleed will do around 80 points of damage / 4 full Health bars in a matter of just a second or two.

Not sure if this is intentional or not, but it seems to be quite alot of damage.

**Comment by 63502** [comment]
OKAAAAAY.  O_O

That is DEFINITELY not intentional.

**Comment by HellFirePvP** [comment]
drep.. >_>

**Comment by Elvarion** [comment]
It was quite Hilarious. I Imagined myself as Chuck Norris. Punching everyone just once and exploding all their internal organs as they bled to death from internal trauma.
Did not work on the Wither.. He is one tough bastard..

Good to see it getting fixed non the less ^^
