### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by R4ss1n** [HellFirePvP/AstralSorcery#410]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.2.6-27.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.1.7.jar)
  BCModPlugin (backpacks 1.12.2 - 3.4.2.jar)
  FMLPlugin (elulib-0.1.9.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-75-core.jar)
  AstralCore (astralsorcery-1.12.2-1.8.2.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 12/2/17 7:50 PM
Description: Exception in server tick loop

java.lang.ClassCastException: thut.api.terrain.CapabilityTerrain$DefaultProvider cannot be cast to hellfirepvp.astralsorcery.common.base.FluidRarityRegistry$ChunkFluidEntry
	at hellfirepvp.astralsorcery.common.base.FluidRarityRegistry.onChLoad(FluidRarityRegistry.java:122)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_693_FluidRarityRegistry_onChLoad_Load.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:99)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 2.6.32-642.6.2.el6.x86_64
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 962546640 bytes (917 MB) / 2023751680 bytes (1930 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -XX:MaxPermSize=128m -Xmx4096M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2555 85 mods loaded, 85 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID                        | Version          | Source                                            | Signature                                |
	|:------- |:------------------------- |:---------------- |:------------------------------------------------- |:---------------------------------------- |
	| UCHIJAA | minecraft                 | 1.12.2           | minecraft.jar                                     | None                                     |
	| UCHIJAA | mcp                       | 9.42             | minecraft.jar                                     | None                                     |
	| UCHIJAA | FML                       | 8.0.99.99        | ForgeMod.jar                                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAA | forge                     | 14.23.1.2555     | ForgeMod.jar                                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAA | advancedrocketrycore      | 1                | minecraft.jar                                     | None                                     |
	| UCHIJAA | elucore                   | 1.0              | minecraft.jar                                     | None                                     |
	| UCHIJAA | uncraftingtable           | 1.8-beta6        | [1.12]UncraftingTable-1.8-beta6.jar               | None                                     |
	| UCHIJAA | actuallyadditions         | 1.12.2-r124      | ActuallyAdditions-1.12.2-r124.jar                 | None                                     |
	| UCHIJAA | redstoneflux              | 2.0.1            | RedstoneFlux-1.12-2.0.1.2-universal.jar           | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAA | cofhcore                  | 4.3.7            | CoFHCore-1.12.2-4.3.7.24-universal.jar            | None                                     |
	| UCHIJAA | libvulpes                 | 0.2.6.-16        | LibVulpes-1.12.2-0.2.6-16-universal.jar           | None                                     |
	| UCHIJAA | advancedrocketry          | 1.2.6.-27        | AdvancedRocketry-1.12.2-1.2.6-27.jar              | None                                     |
	| UCHIJAA | akashictome               | 1.2-10           | AkashicTome-1.2-10.jar                            | None                                     |
	| UCHIJAA | baubles                   | 1.5.1            | Baubles-1.12-1.5.1.jar                            | None                                     |
	| UCHIJAA | botania                   | r1.10-350        | Botania r1.10-350.jar                             | None                                     |
	| UCHIJAA | craftstudioapi            | 1.0.0            | CraftStudio-1.0.0.93-mc1.12-alpha.jar             | None                                     |
	| UCHIJAA | animania                  | 1.4.2            | animania-1.12.2-1.4.2.jar                         | None                                     |
	| UCHIJAA | tammodized                | 0.15.3           | TamModized-1.12.1-0.15.3.jar                      | None                                     |
	| UCHIJAA | aov                       | 0.8.1            | AoV-1.12-0.8.1.jar                                | None                                     |
	| UCHIJAA | jei                       | 4.8.0.114        | jei_1.12.2-4.8.0.114.jar                          | None                                     |
	| UCHIJAA | appleskin                 | 1.0.9            | AppleSkin-mc1.12-1.0.9.jar                        | None                                     |
	| UCHIJAA | aroma1997core             | 1.3.0.2          | Aroma1997Core-1.12.2-1.3.0.2.jar                  | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHIJAA | aroma1997sdimension       | 1.3.0.0.b37      | Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar | None                                     |
	| UCHIJAA | crafttweaker              | 4.0.10           | CraftTweaker2-1.12-4.0.10.jar                     | None                                     |
	| UCHIJAA | astralsorcery             | 1.8.2            | astralsorcery-1.12.2-1.8.2.jar                    | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| UCHIJAA | autoreglib                | 1.3-15           | AutoRegLib-1.3-15.jar                             | None                                     |
	| UCHIJAA | backpacks16840            | 3.4.2            | backpacks 1.12.2 - 3.4.2.jar                      | None                                     |
	| UCHIJAA | badwithernocookiereloaded | 1.12.2-2.12      | badwithernocookiereloaded-1.12.2-2.12.jar         | None                                     |
	| UCHIJAA | betteradvancements        | 0.0.5.17         | BetterAdvancements-1.12.2-0.0.5.17.jar            | None                                     |
	| UCHIJAA | betterbedrockgen          | 6.0.2            | BetterBedrockGenerator-1.12-6.1.1.jar             | None                                     |
	| UCHIJAA | bibliocraft               | 2.4.3            | BiblioCraft[v2.4.3][MC1.12.0].jar                 | None                                     |
	| UCHIJAA | biomesoplenty             | 7.0.1.2302       | BiomesOPlenty-1.12.2-7.0.1.2302-universal.jar     | None                                     |
	| UCHIJAA | bookshelf                 | 2.2.500          | Bookshelf-1.12.2-2.2.500.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAA | codechickenlib            | 3.1.3.313        | CodeChickenLib-1.12-3.1.3.313-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAA | brandonscore              | 2.3.4            | BrandonsCore-1.12-2.3.4.134-universal.jar         | None                                     |
	| UCHIJAA | chameleon                 | 1.12-4.1.3       | Chameleon-1.12-4.1.3.jar                          | None                                     |
	| UCHIJAA | chesttransporter          | 2.8.7            | ChestTransporter-1.12-2.8.7.jar                   | None                                     |
	| UCHIJAA | chisel                    | MC1.12-0.0.14.18 | Chisel-MC1.12-0.0.14.18.jar                       | None                                     |
	| UCHIJAA | cofhworld                 | 1.0.2            | CoFHWorld-1.12.2-1.0.2.10-universal.jar           | None                                     |
	| UCHIJAA | crafttweakerjei           | 2.0.0            | CraftTweaker2-1.12-4.0.10.jar                     | None                                     |
	| UCHIJAA | thermalfoundation         | 2.3.7            | ThermalFoundation-1.12.2-2.3.7.18-universal.jar   | None                                     |
	| UCHIJAA | draconicevolution         | 2.3.5            | Draconic-Evolution-1.12-2.3.5.269-universal.jar   | None                                     |
	| UCHIJAA | enderstorage              | 2.4.0.122        | EnderStorage-1.12-2.4.0.122-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAA | valkyrielib               | 1.12.2-2.0.5a    | valkyrielib-1.12.2-2.0.5a.jar                     | None                                     |
	| UCHIJAA | environmentalmaterials    | @EM_VERSION@     | environmentalmaterials-1.12.X-1.0.4a.jar          | None                                     |
	| UCHIJAA | environmentaltech         | 1.12.2-2.0.5a    | environmentaltech-1.12.2-2.0.5a.jar               | None                                     |
	| UCHIJAA | etlunar                   | 1.12.2-2.0.5a    | etlunar-1.12.2-2.0.5a.jar                         | None                                     |
	| UCHIJAA | mantle                    | 1.12-1.3.1.21    | Mantle-1.12-1.3.1.21.jar                          | None                                     |
	| UCHIJAA | tconstruct                | 1.12-2.7.4.34    | TConstruct-1.12-2.7.4.34.jar                      | None                                     |
	| UCHIJAA | theoneprobe               | 1.4.19           | theoneprobe-1.12-1.4.19.jar                       | None                                     |
	| UCHIJAA | immersiveengineering      | 0.12-75          | ImmersiveEngineering-0.12-75.jar                  | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAA | thermalexpansion          | 5.3.7            | ThermalExpansion-1.12.2-5.3.7.27-universal.jar    | None                                     |
	| UCHIJAA | exchangers                | 1.12-2.5.2       | Exchangers-1.12-2.5.2.jar                         | None                                     |
	| UCHIJAA | extrautils2               | 1.0              | extrautils2-1.12-1.6.8.jar                        | None                                     |
	| UCHIJAA | fastleafdecay             | v14              | FastLeafDecay-v14.jar                             | None                                     |
	| UCHIJAA | sonarcore                 | 5.0.2            | sonarcore-1.12.2-5.0.2.jar                        | None                                     |
	| UCHIJAA | fluxnetworks              | 3.0.1            | fluxnetworks-1.12.2-3.0.1.jar                     | None                                     |
	| UCHIJAA | forestry                  | 5.7.0.214        | forestry_1.12.2-5.7.0.214.jar                     | None                                     |
	| UCHIJAA | ftbl                      | 4.2.4            | FTBLib-4.2.4.jar                                  | None                                     |
	| UCHIJAA | ftbu                      | 4.2.3            | FTBUtilities-4.2.3.jar                            | None                                     |
	| UCHIJAA | ftbg                      | 1.12.1-1.0.06    | ftbg-1.12.1-1.0.6.jar                             | None                                     |
	| UCHIJAA | gravestone                | 1.10.0           | gravestone-1.10.0.jar                             | None                                     |
	| UCHIJAA | journeymap                | 1.12.2-5.5.2     | journeymap-1.12.2-5.5.2.jar                       | None                                     |
	| UCHIJAA | lunatriuscore             | 1.2.0.42         | LunatriusCore-1.12.2-1.2.0.42-universal.jar       | None                                     |
	| UCHIJAA | malisiscore               | 1.12.2-6.1.7     | malisiscore-1.12.2-6.1.7.jar                      | None                                     |
	| UCHIJAA | malisisdoors              | 1.12.2-7.1.1     | malisisdoors-1.12.2-7.1.1.jar                     | None                                     |
	| UCHIJAA | radixcore                 | 1.12.x-2.2.1     | RadixCore-1.12.x-2.2.1-universal.jar              | None                                     |
	| UCHIJAA | mca                       | 1.12.2-5.3.1     | MCA-1.12.x-5.3.1-universal.jar                    | None                                     |
	| UCHIJAA | minemenu                  | 1.6.3            | MineMenu-1.12.2-1.6.3-universal.jar               | None                                     |
	| UCHIJAA | morpheus                  | 1.12-3.3.2       | Morpheus-1.12-3.3.2.jar                           | None                                     |
	| UCHIJAA | reborncore                | 3.5.0.162        | RebornCore-1.12.2-3.5.0.162-universal.jar         | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHIJAA | storagedrawers            | 1.12-5.2.5       | StorageDrawers-1.12.1-5.3.3.jar                   | None                                     |
	| UCHIJAA | refinedstorage            | 1.5.25           | refinedstorage-1.5.25.jar                         | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| UCHIJAA | rftools                   | 7.14             | rftools-1.12-7.14.jar                             | None                                     |
	| UCHIJAA | rftoolsdim                | 5.05             | rftoolsdim-1.12-5.05.jar                          | None                                     |
	| UCHIJAA | schematica                | 1.8.0.167        | Schematica-1.12.2-1.8.0.167-universal.jar         | None                                     |
	| UCHIJAA | spartanshields            | 1.3a             | SpartanShields-1.12-1.3a.jar                      | None                                     |
	| UCHIJAA | thermaldynamics           | 2.3.7            | ThermalDynamics-1.12.2-2.3.7.14-universal.jar     | None                                     |
	| UCHIJAA | thutcore                  | 5.12.1           | thutcore-5.12.1.jar                               | None                                     |
	| UCHIJAA | thutcore_compat           | 1.0              | thutcore-5.12.1.jar                               | None                                     |
	| UCHIJAA | thuttech                  | 6.0.8            | thuttech-6.0.8.3.jar                              | None                                     |
	| UCHIJAA | torchmaster               | 1.6.1.53         | torchmaster_1.12.2-1.6.1.53.jar                   | 5e9a436b366831c8f54a7e80b015784da69278c6 |
	| UCHIJAA | twilightforest            | 3.4.239          | twilightforest-1.12.2-3.4.239-universal.jar       | None                                     |
	| UCHIJAA | waystones                 | 4.0.17           | Waystones_1.12.1-4.0.17.jar                       | None                                     |
	| UCHIJAA | elulib                    | 0.1.9            | elulib-0.1.9.jar                                  | None                                     |

	Loaded coremods (and transformers): 
CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.2.6-27.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.1.7.jar)
  
BCModPlugin (backpacks 1.12.2 - 3.4.2.jar)
  brad16840.core.ClassTransformer
FMLPlugin (elulib-0.1.9.jar)
  elucent.elulib.asm.ASMTransformer
IELoadingPlugin (ImmersiveEngineering-0.12-75-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
AstralCore (astralsorcery-1.12.2-1.8.2.jar)
  
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.5.0.162
		Runtime Debofucsation 1
	Profiler Position: N/A (disabled)
	Player Count: 0 / 24; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

not sure what is going on I'm using forge V 14.23.1.2555 and still get a crash.  and my players keep asking me whin the server is going to be back up.  need help soon. thank you

**Comment by HellFirePvP** [comment]
#400 duplicate
