### ISSUE TITLE
[SUGGESTION] WAWLA Enchantment Descriptions

### ISSUE THREAD

**Issue by Sunconure11** [HellFirePvP/AstralSorcery#411]
WAWLA adds support for one to add descriptions to enchantments. Would it be possible to pull this off on your end?

![ass](https://user-images.githubusercontent.com/5614902/33523719-6b95d104-d7db-11e7-8a6d-ca3b1945d942.png)

**Comment by HellFirePvP** [comment]
duplicate #385
