### ISSUE TITLE
Pillars hide water

### ISSUE THREAD

**Issue by darkhax** [HellFirePvP/AstralSorcery#412]
![image](https://user-images.githubusercontent.com/2250798/33529178-2eda089e-d82a-11e7-97c2-96b5c3184b9e.png)

**Comment by majijn** [comment]
![2018-07-25_04 05 08](https://user-images.githubusercontent.com/18368034/43366566-32feb588-9340-11e8-8a38-66e4b03c7ba4.png)
black pillars seem to do the same
