### ISSUE TITLE
MeeCreeps can break the crystals in temples (1.12 Direwolf20)

### ISSUE THREAD

**Issue by Ozzymud** [HellFirePvP/AstralSorcery#416]
Had a MeeCreep level the terrain at a temple so I could build my own outpost there. He did such a good job that he also destroyed the crystal. I mentioned this to McJty on reddit:

https://www.reddit.com/r/feedthebeast/comments/7ha0es/tips_for_ftb_dw20_1122/dqqomig/ 

He seems to think it is badly implimented as he does all he can think of to prevent the MeeCreeps from doing bad things.

They check for:
    Hardness of the block (for bedrock etc)
    If the block allows destruction by a player (canEntityDestroy())
    They call the BreakEvent and see if the event was canceled
    And finally they call canHarvestBlock()

Direwolf20 pack: 1.2.0
Astral Sorcery: 1.12.2-1.8.2
MeeCreeps: 1.12-0.1.6beta
Forge: 14.23.1.2555

**Comment by HellFirePvP** [comment]
After discussing this with McJty, this is not reproducable. Neither indev aswell as in the latest direwolf20 pack version. The sourcecode on both sides looks fine and it working correctly in our testcases supports that as it doesn't happen to us.
An idea was that it was broken by a player in creative and placed again aftwards making it essentially breakable... Try on other shrines.

**Comment by Ozzymud** [comment]
This was in my single player world and none else has messed with the world.

**Comment by HellFirePvP** [comment]
Yea. literally did the same thing.

**Comment by Ozzymud** [comment]
Since that happened I updated the pack and cannot reproduce it.
