### ISSUE TITLE
Crash while trying to break Torch

### ISSUE THREAD

**Issue by CastielAngelow** [HellFirePvP/AstralSorcery#419]
[crash-2017-12-04_13.26.05-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/1527691/crash-2017-12-04_13.26.05-server.txt)

Title says it all. Wasnt able to repeat issue without AS installed in my pack. Also posted this on Discord., sorry for that.

**Comment by Doomgull** [comment]
Duplicate #403 .
