### ISSUE TITLE
[Suggestion] Unlink all links to a crytal/lens/prism

### ISSUE THREAD

**Issue by VallenFrostweaver** [HellFirePvP/AstralSorcery#423]
**Problem:**
Often I will have a single crystal to get starlight from for the first part of my playthrough and I may need things like a bunch of starmetal and I will end up linking to a lot of places. Then when I need that starlight to be focused on something later that night I forget to unlink all the places where the starmetal was and I have to run around placing blocks so that I can unlink them. 

**Solution idea:**
Perhaps making it so that if a crystal/lens/prism that is first clicked to start linking then shift + clicked to unlink will unlink all things that it is focused on would help. I dislike break & replace as it is often hovering in mid air and the idea of unlinking all items when there isn't anything where it was shining and needing to replace an item to unlink it gets a bit tedious.

Just a thought. :)

Linked:
![linked](https://user-images.githubusercontent.com/13642054/33711663-af132940-db3c-11e7-9f1b-6e13a4408d3e.png)
After harvesting:
![missing](https://user-images.githubusercontent.com/13642054/33711686-b82c4048-db3c-11e7-9ce5-fbb045d78f0f.png)
Replacing to unlink:
![placed unlinked](https://user-images.githubusercontent.com/13642054/33711696-c266afc6-db3c-11e7-8a30-ba0f8ff6f648.png)

**Comment by SirMoogle** [comment]
I second this suggestion. After harvesting the blocks dummy ones have to be added to properly unlink the Crystal to those block positions.
