### ISSUE TITLE
[1.12.2 v1.8.2 and v1.8.3] Crash when right-clicking Containment Chalice

### ISSUE THREAD

**Issue by ranma862** [HellFirePvP/AstralSorcery#425]
Crash reports in the pastebins below. Built the chalice just fine, placed it in the world, right-clicked it with an aquamarine the first time, and a bucket of starlight the second. Both times it just crashed the client.

https://pastebin.com/bxsUrFw6
https://pastebin.com/8gvXS6gi

While reporting this I realized there's a version 1.8.3, updated to that version and it worked twice - right-clicked with a starlight bucket and it started hovering around the chalice, right-clicked again with the empty bucket and it came back. The third time I right-clicked with the full starlight bucket again, it crashed again:

https://pastebin.com/Kv1FmBGb

Mod list here:
https://pastebin.com/WbDfrp31

**Comment by HellFirePvP** [comment]
try removing whatever that mod is:

sorazodia.survival.mechanics.PlayerActionEvent.blockRightClick(PlayerActionEvent.java:130)

made my sorazodia it seems. Survival-Tweaks is its name. I couldn't find it in the modlist you supplied so i guess you added it without updating the mod list.

**Comment by HellFirePvP** [comment]
looking through his code:

> boolean blockActivated = !player.isSneaking() && block.onBlockActivated(world, new BlockPos(0, -1, 0), blockState, player, hand, offset, 0, 0, 0);

what the fcking shit.

**Comment by HellFirePvP** [comment]
*sighs* https://github.com/SoraZodia/Survival-Tweaks/issues/14
filed issue report, it's a 1 line change on his end. Did my part.

**Comment by ranma862** [comment]
Thank you! Appreciate the submission to SurvivalTweaks as well, we may well take it out.
