### ISSUE TITLE
Celestial collector crystal

### ISSUE THREAD

**Issue by hypernova132** [HellFirePvP/AstralSorcery#427]
I really have no clue what's going on. I built the structure for the celestial collector crystal yet I'm not seeing particle effects and it's not gaining effects from it. ![2017-12-09_21 19 56](https://user-images.githubusercontent.com/25520679/33801640-f2312308-dd26-11e7-99f0-0f80e896b321.png)

**Comment by HellFirePvP** [comment]
The Size of your collector crystal is probably too small, also the 1.10.2 and 1.11.2 versions are no longer supported.
