### ISSUE TITLE
Gateway not working

### ISSUE THREAD

**Issue by xventure1** [HellFirePvP/AstralSorcery#429]
on a server. have it set up correctly... I used shit tier crystals, would that effect anything at all?

Thanks in advance. I did triple check the block syntax, I got it set up correctly.

**Comment by Doomgull** [comment]
Version of AS, Forge, MC, Pack (or modlist) and screenshots because you built something wrong. Crystal stats are wholly irrelevant. There is no ownership, all gateways are global.

What are you doing to move between them?

**Comment by xventure1** [comment]
I solved it. I couldn't decipher what was causing the issue but restarting the server fixed it.
