### ISSUE TITLE
Crystal Breaking crash

### ISSUE THREAD

**Issue by CanadianBash** [HellFirePvP/AstralSorcery#43]
The game crashed and when I would reload it the crystal would still be there. 

[crash-2017-02-24_23.20.03-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/801308/crash-2017-02-24_23.20.03-client.txt)

**Comment by 63502** [comment]
[Gist Version of Crash Log](https://gist.github.com/63502/cee7469d15c4b397f64122b95eba7b04)
