### ISSUE TITLE
Weird Bug. After like 2-5 mins Minecraft crashes

### ISSUE THREAD

**Issue by VoidedDarkness24** [HellFirePvP/AstralSorcery#430]
Ok like I said in the title it crashes and I opened the log up cause I want to play in 1.12.1 to see the problem think this is an issue, 

17:43:41] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in astralsorcery-1.12.2-1.8.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
--
17:43:41 | game | [17:43:41] [main/WARN] [FML]: The coremod hellfirepvp.astralsorcery.core.AstralCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft

Can you get anything outta that? Forge Version: 14.22.1.2485 AS: 1.8.1

**Comment by HellFirePvP** [comment]
These warnings are not the source of your problem, it's just that AS 1.8.1+ is no longer compatible with minecraft 1.12.1 - only 1.12.2. it's wrongly tagged on CF sorry~

**Comment by VoidedDarkness24** [comment]
ok then well, I moved version and it fixed it. Thanks
