### ISSUE TITLE
Issue with Rock Crystal Ore not Dropping

### ISSUE THREAD

**Issue by rongineering** [HellFirePvP/AstralSorcery#432]
This is on Astral Sorcery 1.8.2 so if it was fixed in the newest versions, my apologies. I just wanted to document it in case it is a different than what you have seen to date.  

The issue occurred when mining rock crystal ore. The ore would break and then nothing would drop and the attached error would populate the server log. The ore was specifically being generated by one of the underground ore rooms if that changes anything. 

![minecraft error]: (https://user-images.githubusercontent.com/32487842/33894613-5f52c688-df2c-11e7-8eb5-73f54d7194d6.png)

Disregard if no longer relevant, can provide more information if necessary. Custom 1.12.2 modpack with about 74 mods

**Comment by HellFirePvP** [comment]
Found that issue by accident yesterday. yes it changes something and yes it's fixed for 1.8.4

**Comment by rongineering** [comment]
Cool! Great Mod btw!

For curiosity's sake, what was the issue that caused it?
