### ISSUE TITLE
Server crash while exploring 

### ISSUE THREAD

**Issue by OldManCraft** [HellFirePvP/AstralSorcery#433]
Forge: 2562
AS 1.12.2-1.8.4
[crash.txt](https://github.com/HellFirePvP/AstralSorcery/files/1553613/crash.txt)

**Comment by OldManCraft** [comment]
Any update on the next version release ?

**Comment by Doomgull** [comment]
If you dont see it out yet, its not.

Don't expect it until after first of year.

**Comment by OldManCraft** [comment]
Sounds good, Thanks for the update.
