### ISSUE TITLE
Rock Crystal Ore NOT Dropping Rock Crystals

### ISSUE THREAD

**Issue by jusjudge** [HellFirePvP/AstralSorcery#437]
Minecraft Ver: 1.12.2
Astral Sorcery Ver: 1.8.4
Forge Ver: 14.23.1.2566

To my understanding a part of the update to 1.8.4 was to fix the rock crystal ore not dropping rock crystals but although I am currently on 1.8.4, it still isn't dropping anything whether I create the rock crystal from rock crystal essence from Mystical Agriculture or I find an ore within the world. I've tried using a vanilla diamond pickaxe, a tinker's construct hammer, and even a tinker's construct pickaxe and nothing worked.

**Comment by Doomgull** [comment]
The fix was for them not dropping crystals from the Treasure Shrines, not them not dropping in general.

Need the pack you're using/full mod list.

**Comment by jusjudge** [comment]
@Doomgull https://pastebin.com/naxsMJTU

**Comment by Doomgull** [comment]
Addtional Information:
Another confirmation for this issue in Discord for DW20 1.12.2 pack, also AS 1.8.4, Forge 14.23.1.2559.

**Comment by Doomgull** [comment]
Test environment running 1.8.4 on MC 1.12.2 on Forge 2566 worked.

**Comment by jusjudge** [comment]
@Doomgull being that it worked for you, what should I do to try to get it to work for me?

**Comment by Doomgull** [comment]
Check if it still happens in a single player version of the same pack and then maybe try removing some mods that the pack shares with direwolf20. This sounds like some sort of weird interaction but considering this isn't happening to everybody it makes me wonder what the commonality is. If this was something specific to the direwolf20 pack I'm pretty sure we would have heard from direwolf himself that hey this whole thing is broken.

**Comment by jusjudge** [comment]
@Doomgull So I tried mimicking DireWolf's pack, and the new FTB Revelations pack. I updated my forge to 2575 and even tried taking mods out and nothing works still. I also attempted taking Astral Sorcery out of the pack and deleting the config and nothing changed either. I would try to find a treasure shrine to see if that works but I have no idea on how to find one.

**Comment by Doomgull** [comment]
Mystic ag has nothin to do with oresoawn. Something is brooen in your pack. Please start a freah instance of it and see if it replicates.

**Comment by MyDaysBoy** [comment]
I have verified that MoreCommands 6.0 causes this problem (maybe other mods too, but at least THIS one does). I downloaded a fresh copy of the Direwolf20 1.12 modpack, I was able to break rock ore and get shards. I exited, added MoreCommands and restarted the game - now when I broke the rock ore I did not get shards.

**Comment by HellFirePvP** [comment]
"Conflict" with universial remote fixed in 1.8.5
