### ISSUE TITLE
random crashes after adding astral sorcery to server

### ISSUE THREAD

**Issue by redgoblin88** [HellFirePvP/AstralSorcery#438]
i have been playing on my friends server for at least a month with no issue, after we added astral sorcery a few of us began randomly crashing at random intervals depending on what we were doing.

luckily i have access to the server, so i have tried deleting my playerdata but that did not fix anything, but oddly enough whenever i crash the console log gets spammed with this:

https://pastebin.com/bVAnSPXJ

this occurs whenever i'm at my well explored (500 block radius+) base, exploring new chunks or more specifically, mining and i happen to pick up ic2 copper ore.

strangely not everybody is having this issue

astral: 1.8.3 and 1.8.4
forge: 14.23.1.2566

**Comment by HellFirePvP** [comment]
literally. the first line tells you which mod it is.
> at cofh.thermalfoundation.proxy.EventHandler.handleEntityItemPickupEvent(EventHandler.java:64)
