### ISSUE TITLE
Protected (ghost) AE2 Stuff Inscribers

### ISSUE THREAD

**Issue by Fey142** [HellFirePvP/AstralSorcery#439]
Not sure how it happened but somehow those advanced inscribers got indestructible (like the illumination wand effect). Also got some console errors - https://pastebin.com/EdSTHRsb
Tried to smack it with the illumination wand to remove it - like ordianary - but didn't do anything.
Fixed it by going into creative and destroying them.

Sorry for not providing more info.

MC 1.12.2 DW20 pack v1.4.0 (added AE2Stuff manually) Forge 14.23.1.2566
![unknown 1](https://user-images.githubusercontent.com/16908410/34071096-53368234-e271-11e7-9c26-125b67e831b5.png)
![unknown](https://user-images.githubusercontent.com/16908410/34071097-535108d4-e271-11e7-900e-76b69d91f416.png)

**Comment by Doomgull** [comment]
Are you sure you didn't get trolled by someone else on the server?

**Comment by Fey142** [comment]
It's a singleplayer instance

**Comment by Fey142** [comment]
As far as I know, you can't "illuminate" tile entities anyway so how it came to this beats me.

**Comment by Fey142** [comment]
It happened again a few minutes after restart of the server. After that I removed the AS tree beacon(s) I had next to my house. Another thing is they were acting strangely - found random redstone clocks, machine frames and droppers in the tree canopy?

**Comment by HellFirePvP** [comment]
Huh. strange. might be that the treebeacon picked up on wrong places for whatever reason... will investigate this further then..

**Comment by Fey142** [comment]
It's not super close - should definitely not be in it's range.
![image](https://user-images.githubusercontent.com/16908410/34079880-135b8a72-e336-11e7-97ae-29c60ad9e74d.png)

**Comment by Fey142** [comment]
I don't really know anything about code and such, but 

> [14:33:23] [Server thread/WARN] [bdlib]: Error retrieving TE of type net.bdew.ae2stuff.machines.inscriber.BlockInscriber$ at BlockPos{x=613, y=66, z=216} (world is net.minecraft.world.WorldServer)
java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=active, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=astralsorcery:blockfaketree, properties=[]}

**Comment by Doomgull** [comment]
Are there any AE cables that run closer to where the beacon is/was?

**Comment by Fey142** [comment]
![image](https://user-images.githubusercontent.com/16908410/34081042-b551e9f0-e347-11e7-973e-8353f99cfa52.png)

![image](https://user-images.githubusercontent.com/16908410/34081057-efb19db6-e347-11e7-8a1e-780deca3f5ea.png)


Those are the cables - the tree beacons are in every corner of the stone brick fence. As far as I remember, at the time the bug happened, even the one cable that is there now, wasn't present.

**Comment by Fey142** [comment]
Doing further testing at the moment but I am now able to reproduce it every time. It happens when I use the exchanger on the blocks under the tree beacon - more info later (and a video so you can see this black magics first hand LOL)

**Comment by Fey142** [comment]
More info: - Only happens on dedicated server, when I try to exchange blocks under the beacon and the exchanger runs out of blocks that you are trying to replace. That is when the replaced blocks become seethrough aka Astral sorcery illuminated blocks. Then the console throws out errors that I posted before - AE2 insciber corrupt, block/blockfaketree etc. Also the "ghostly" trees (the actual area it should affect) start throwing out inscribers, redstone clocks and droppers - It creates a few copies of said items every time I click with the exchanger under it.

**Comment by Fey142** [comment]
Ok, so I managed to reproduce it in a fresh superflat world. Adding video link as soon as it uploads.

**Comment by Fey142** [comment]
https://youtu.be/1ABevWd7VU8 
(actual thing is at the end) 9:00 - 10:20

**Comment by Fey142** [comment]
Same thing is happening (AE2 Blocks getting corrupt) when I use the formation wand (was using it to flatten the lake in front of the house - not in range of the tree beacon at all.

**Comment by HellFirePvP** [comment]
I did put some extra prevention mechanisms in place and hopefully that'll work out better then - will be included in the next release.
