### ISSUE TITLE
[1.12.2 v1.8.4] Infused Crystal Axe does not harvest leaves from Traverse mod when chopping tree trunk

### ISSUE THREAD

**Issue by VallenFrostweaver** [HellFirePvP/AstralSorcery#442]
When I use the axe on the trunk of an "Autumnal" tree the trunk is taken. If I wait for the recharge and use it on the leaves the leaves are taken. I can't take both with one use. Normal vanilla trees are fine.

**Comment by Doomgull** [comment]
Mildly curious what Traverse does to those trees.

**Comment by HellFirePvP** [comment]
@TheCodedOne pls overwrite isLeaf & isLog for both leaves and logs respectively on the block.

**Comment by TheCodedOne** [comment]
will be in next update for traverse

**Comment by HellFirePvP** [comment]
Tree-checking is less agressive next version. that should fix this.
