### ISSUE TITLE
[Non-Crash] Potential conflict between Astral Sorcery and Recurrent Complex

### ISSUE THREAD

**Issue by Voleur** [HellFirePvP/AstralSorcery#443]
Hi, just wanting to report this issue: If both Astral Sorcery and Recurrent Complex are running, the log file gets filled with these errors while exploring.

While it does NOT cause a crash, it does cause severe lag spikes. This occurs with or without 'lightweightMode' enabled for Recurrent Complex, and occurs both on SSP and SMP. It also occurs with fresh configs generated for both mods, or with configs tweaked for both mods, and occurs without any other mods running (besides Forge and required libs). It also occurs with 'treeLeavesDecay: false' set - I assumed that might be what was causing the error. It isn't.

In this instance, I'd re-enabled all of my mods to see if the error occurs more often - it doesn't, its pretty consistent. It only seems to occur when an Astral Sorcery shrine and a Recurrent Complex Structure are near each other - within 3-4 chunks, and only occurs on chunk generation (ie, not when a chunk already exists). I have not tested it with retrogen enabled for Astral Sorcery.

Each individual occurrence is 850+ lines long, so I've put the relevant error on PasteBin: https://pastebin.com/gDypXTH6

Minecraft Version: 1.12.2
Forge Version: 14.23.1.2555
Astral Sorcery Version: AstralSorcery-1.12.2-1.8.4
Recurrent Complex Version: RecurrentComplex-1.4.6

Also posted to Recurrent Complex: https://github.com/Ivorforce/RecurrentComplex/issues/293

**Comment by HellFirePvP** [comment]
Now that's a very elaborate stacktrace with a ton of mods involved. i'm gonna somewhat fix my end... soo. yea. :P Not sure if everything is going great in there though.

**Comment by Voleur** [comment]
Yeah, I gave the most recent error after attempting some config/mod removals/etc to eliminate issues. I'm relatively sure Actually Additions was un-involved and just generated ore in the chunks(s) that time, as it happens with just Forge/Astral Sorcery/Rec. Complex+Lib enabled.

I probably should have dug through my error logs for a cleaner one, lol, but they're all about this long.
