### ISSUE TITLE
Not really sure what this is

### ISSUE THREAD

**Issue by Zsashas** [HellFirePvP/AstralSorcery#444]
It caused a pretty big frame drop for a few seconds while just exploring.

https://hastebin.com/otihezetib.md

**Comment by Doomgull** [comment]
... version of AS. version of forge. version of mc. pack version/mod list.

**Comment by Zsashas** [comment]
Right, sorry.

Mod list: https://hastebin.com/ixavageneb.css
Forge: 2565
AS: 1.8.4
