### ISSUE TITLE
Kicked from singleplayer when entering the Aether

### ISSUE THREAD

**Issue by Zsashas** [HellFirePvP/AstralSorcery#447]
https://hastebin.com/jeketasuli.vbs

Happens every time when entering the portal, but reloading the save puts me in the Aether just fine.

Also it sent me to the multiplayer menu for some reason, even though I was in a singleplayer world.

Mod: 1.8.4
MC: 1.12.2
Forge: 2565

**Comment by longtomjr** [comment]
Got similar error when exiting deep dark #465

**Comment by longtomjr** [comment]
@Zsashas Does it happen every time you enter the Aether? @HellFirePvP is looking for a way to reproduce it, so if you have the save, care to share?

**Comment by Zsashas** [comment]
It stopped happening, so I have no idea. :I
