### ISSUE TITLE
Get fluid name RE:fountain

### ISSUE THREAD

**Issue by ouroborus** [HellFirePvP/AstralSorcery#448]
Any chance of adding something that gives the name of the fluid currently associated with a chunk?

It turns out that similarly colored fluids look very nearly the same as each other when AS applies its texture adjustments (transparency, etc., especially considering changing lighting and terrain color) for the "springs" shown when using the ichosic resonator. Blues are especially problematic given how common water is.

I'm thinking, at minimum, for admins, add a sub-command to `/astralsorcery` to show the current fluid and amount remaining for the current chunk.

For general play, maybe add the ability to click with the ichosic resonator to get a fluid name in chat for the current chunk.

Astral Sorcery 1.8.2

**Comment by HellFirePvP** [comment]
I am very opposed to adding a command that literally tells you the name as it's against the design of the fountain + ichosic resonator.
Admin command? maybe. not likely since i'd really hate to disclose the information to the end user without having to actually do the "drilling"

**Comment by ouroborus** [comment]
@HellFirePvP I don't see the problem with an admin command. The mod already has commands for just handing out all the progressions and such. What's the difference between that and having a command for seeing the fluid names?

As for your specific concern of not revealing actual names: Then don't show names, do something else. Just whatever is done, make it easier to differentiate between similarly colored fluids. As it stands, the whole drilling system is just a way to blow off part of an hour the first time you come across it before deciding there are easier, more predictable ways of getting those materials and never using that part of AS again.

How about some kind of memory system? Add an item (I'll call it a Recorder, the name doesn't matter) for the purpose of recording "flavors" of fluids. Once the player sets up the mining rig and it has gathered a certain amount of the material, the player can click the recorder on the evershifting fountain. This causes the particular material to get registered in the recorder along with whatever else had been registered. Later, the player can use the ichosic resonator (or some other hand-held, purpose-built device) to "taste" a chunk. If the "taste" matches one of the "flavors" stored in a recorder (held in the player's inventory), more information is given towards the purpose of enabling the player to better determine what is available here. (Maybe cause the cause the "fountains" from the ichosic resonator to be shown as though they're actually made of their representative fluid, no texture/transparency modifications, rather than the washed out version normally shown. Or maybe have the click produce a "splash" of cubes using the unaltered fluid texture. The idea is that the original fluid textures are a lot easier to differentiate than the AS versions.)
