### ISSUE TITLE
Containment Chalice looses Starlight in Tank 1.12.2-1.8.2

### ISSUE THREAD

**Issue by pddm** [HellFirePvP/AstralSorcery#449]
Beautiful Mod, I love it
When you fill a Containment Chalice and pick it up to place it again, it looses all the Starlight.
It is assumed if it shows up like a tank, it behaves like one.
Thank you for this mod.

**Comment by HellFirePvP** [comment]
Also as description it's mentioned to hold the liquid in a very volatile, unstable state. And it doesn't even look like a tank as in the fluid is actually stored in some container of some form. it's literally floating in the air. Thinking it'll keep it upon mining is... no.
