### ISSUE TITLE
Dupe Bug when Faint Amaranth is Sheared

### ISSUE THREAD

**Issue by 666lumberjack** [HellFirePvP/AstralSorcery#450]
Shearing Faint Amaranth drops glowstone in addition to the plant itself, so it's possible to infinitely create glowstone at a cost of nothing but the durability of the shears you use. 

Using astralsorcery-1.12.2-1.8.4 for MC 1.12.2 and forge 2566

**Comment by Doomgull** [comment]
What other mods?

**Comment by Doomgull** [comment]
@666lumberjack update please.
