### ISSUE TITLE
Ritual Altar not creating beams with Collector Crystal and Ritual Anchor

### ISSUE THREAD

**Issue by phood0588** [HellFirePvP/AstralSorcery#452]
With Ritual Altar with white attuned crystal on it and Ritual Anchor placed correctly there is a particle effect with the anchor and the altar, and the second anchor also does the particle effect. Although placing collector crystal and linking it to the altar does not produce the beams to place lenses on to redirect back to the altar. What am I doing wrong?

**Comment by Doomgull** [comment]
Is the crystal attuned to the same constellation as the ritual?

**Comment by phood0588** [comment]
I have the attuned crystal on the altar attuned to Bootes. I have read somewhere that the collector crystal must also be attuned to Bootes but when I drop the crystal on the attunement altar nothing happens.

**Comment by phood0588** [comment]
![2017-12-21_01 47 04](https://user-images.githubusercontent.com/34734216/34272940-5853272a-e660-11e7-8e5c-537b2e269da9.png)

**Comment by phood0588** [comment]
I have figured it out the collector crystal must be made with a rock crystal attuned to the same as the rock crystal on the pedestal.
