### ISSUE TITLE
Possible to turn off cave illuminator in certain areas?

### ISSUE THREAD

**Issue by creamedpossum** [HellFirePvP/AstralSorcery#453]
Was trying out the cave illuminator in a base i made underground.  Didn't realize how far the effect would spread, and It is also hitting some dark rooms that were created for mob spawners.  Is there a way to have it not light up particular areas, or is it just a more or less a certain radius?

**Comment by Doomgull** [comment]
No, though when you pick it up it stops placing lights, so once everything is illuminated, just pick it up, the lights will stay, then overwrite the lights you don't want by placing a block in their space.
