### ISSUE TITLE
Shaders compatibility (Crystal Glow Glitching)

### ISSUE THREAD

**Issue by TimeConqueror** [HellFirePvP/AstralSorcery#454]
Hey there,

1.12.2
Optifine HD_U_C8
Tested with Sildurs Vibrant Shaders v1 166 Extreme

Using shaders, Crystal starts to emit black rays. http://prntscr.com/hqlxxt (Astral Sorcery 1.8.2)

**Comment by Doomgull** [comment]
And shaders aren't supported because conflicts with skyrendering.
