### ISSUE TITLE
Weird crash between this mod and dynamic surroundings

### ISSUE THREAD

**Issue by Sunconure11** [HellFirePvP/AstralSorcery#455]
https://pastebin.com/raw/gPvZ8vt1

A user of my pack encountered this. I am not sure what happened. It happened on a server I'm hosting though, and its using spongeforge.

**Comment by Doomgull** [comment]
Reproduce without sponge involved., reopen if it triggers afterward.

**Comment by Sunconure11** [comment]
I believe it was a one off crash. I'll see if it triggers again in the future.

**Comment by HellFirePvP** [comment]
It's not directly a sponge-related issue. this just happens cause the aurora "sky-renderer" also calls my skyrenderer again and i cache whatever skyrenderer was there before and try to render "on top of that" when doing "weak" skyrendering: https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/client/sky/RenderSkybox.java#L51

just happens that it ends up calling me yet again. i'll tape-fix arond it.
