### ISSUE TITLE
HUD Glitch when opening Astral Tome

### ISSUE THREAD

**Issue by Oceanus5000** [HellFirePvP/AstralSorcery#458]
I'm using a server modpack called Alteria and whenever I open the Astral Tome my HUD glitches and turns the crosshair, EXP bar, hunger meter, and health bar into white bars. The only way I have found to resolve this is by completely restarting my game.
![2017-12-22_14 09 34](https://user-images.githubusercontent.com/27291276/34309775-d09397da-e721-11e7-895f-b98382e7abec.png)

**Comment by HellFirePvP** [comment]
Disable optifine fast render
