### ISSUE TITLE
Crash due to crafting crystal pickaxe

### ISSUE THREAD

**Issue by chunkedelement** [HellFirePvP/AstralSorcery#459]
[crash-2017-12-22_22.23.32-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/1584398/crash-2017-12-22_22.23.32-server.txt)
Crash when crafting crystal pickaxe. Running MC 1.10.2, The simple life 2 modpack 1.4 toast version.
This crash couldnt recover, server would not start, didnt have mc edit to fix at the time so had to restore a backup world. Any ideas what caused this or what to do to fix? Thanks for your help
David

**Comment by Doomgull** [comment]
Don't use crystals without stats. That pack is bad about that.

Also, unsupported version.
