### ISSUE TITLE
i Craft a Crystal sword. My world is dead

### ISSUE THREAD

**Issue by SuperFurias** [HellFirePvP/AstralSorcery#460]
(sorry my english i'm italian)

Crafting minecraft crystal sword my world crashing. I think it's a momentary problem to restart mc in the world and re-crashing. I'm going to crash-report and I find this:

https://mega.nz/#!tJ0CWQAa!93VhfigPPzgxcFqlrOoFO21w8Q1DRt21_ySzc0iX6QI

Please help!!! :c

**Comment by HellFirePvP** [comment]
Please upload your crashlog to hastebin, pastebin or gist.github.com - i will not download any arbitrary file due to security reasons.

**Comment by SuperFurias** [comment]
Sorry I did not know, here is hastebin
https://hastebin.com/akefizarim.scala

**Comment by HellFirePvP** [comment]
1.10.2 and 1.11.2 versions of the mod are no longer supported. The issue got fixed for the 1.12.2 versions.
