### ISSUE TITLE
Extreme lag curse from liquid miner thing

### ISSUE THREAD

**Issue by Rebelord01** [HellFirePvP/AstralSorcery#461]
Okay so I placed down the liquid miner thing and it lag every 5 seconds lag spike so I'm like I gotta destroy this thing which I did but know my world is cursed with lag plz help

**Comment by HellFirePvP** [comment]
lag is not a "curse"

Profiling data please. You can profile your current JVM instance with Java VisualVM - there are plenty of tutorials that guide you through it.

**Comment by Doomgull** [comment]
@Rebelord01 please provide some updated info, or I'll close this at the end of the week.
