### ISSUE TITLE
[Non-Crash] Starlight fields disappearing?

### ISSUE THREAD

**Issue by zrieprakis** [HellFirePvP/AstralSorcery#462]
Been playing in a DW20 1.12 server world for a little while now.  I did update from 1.3 to 1.4 at one point.  Managed to find a decent starlight field and build my table a a decent Y-level.  Good power in the table.  Noticed recently that the table barely fills halfway.  Just happened to check through the Fosic resonator and noticed that the field under my table had vanished.  Even stranger, a weak field popped up where I know there wasn't one earlier.  Took me a while to find this, so I doubt any logs would help.  Is this normal behavior, or did something glitch?

If I can give more info, let me know.  Thanks.

**Comment by Doomgull** [comment]
Worldseed change?

**Comment by zrieprakis** [comment]
World didn't change, that's what's disturbing.  It was a flat copy of the world folder to the new server instance.  Very strange.

**Comment by Doomgull** [comment]
With recent code changes, that's enough to count despite the seed itself not changing, apparently.

I'll let Hellfire address the rest.

**Comment by HellFirePvP** [comment]
Yea. the seed that generates the skywave fields (more or less) changed from direct world seed to (now) a seed-dependent number. Thus the skywave fields are now on different locations. not a bug really, just a change that happened due to me being hated against.

**Comment by zrieprakis** [comment]
Good to know.  Thanks for the feedback, and Merry Christmas!  Will go try to find another field.  :-)
