### ISSUE TITLE
our dw20 server is having issues thats directed towards your mod

### ISSUE THREAD

**Issue by TGSRagnarok** [HellFirePvP/AstralSorcery#463]
https://pastebin.com/PJJTBs1Q

**Comment by Doomgull** [comment]
*sigh*.

Pack version.
Forge version.
Any changes to the pack.

Come on people!

**Comment by ShamanDarrow** [comment]
Pack version is 1.4.0
Forge Version is 14.23.1.2566
I believe some config changes were made... I have a message to TGSRagnarok to see if any mods were added for the server.

**Comment by TGSRagnarok** [comment]
no mods were changed
forge version is14.23.1.2566 only config changes was to the chunk loading from ftbu

**Comment by Doomgull** [comment]
Seeing as how the error points to a chunk data error...what did you change on the ftbu chunk loading config?

**Comment by HellFirePvP** [comment]
On that note: i might be in the stacktrace, however what fails is loading the chunk. That's nothing i influence on my end.

**Comment by TGSRagnarok** [comment]
we just set it so people can't chunkload

**Comment by HellFirePvP** [comment]
That has nothing to do with what i just said.

**Comment by TGSRagnarok** [comment]
ok doing a server roll back to see if its a corrupted chunk
