### ISSUE TITLE
Bootes ritual - no wool

### ISSUE THREAD

**Issue by n0yes** [HellFirePvP/AstralSorcery#464]
I made bootes ritual to get animal drops. I get leather and beef from cows, but sheep give only meet and no wool. They get sheared though, so I was thinking it's a bug.

**Comment by Doomgull** [comment]
It's just insanely slow for wool, because it pulls from the drop table, not the shearing table.

**Comment by n0yes** [comment]
I'm not sure that is the case. I was standing near the sheep while they are being sheared. No wool dropped. My vacuum hopper doesn't pick it up either.

**Comment by n0yes** [comment]
Lol. I stand corrected. My hopper picked up one wool in 2 days :) Though me standing by the sheared sheep and not getting wool is true.

**Comment by HellFirePvP** [comment]
https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/base/HerdableAnimal.java#L242
