### ISSUE TITLE
[Suggestion/Compatibility] Add a list for ores to be checked by the ore discovery feature of the infused pickaxe

### ISSUE THREAD

**Issue by Lathanael** [HellFirePvP/AstralSorcery#467]
I am currently working on a 1.12 mod pack with a heavily altered ore generation due to CustomOreGeneration and Harder Ores. Thus every normal ore block gets replaced/is not generated and only the Harder Ores ones can be found underground. This however results in a problem as these ores do not extend **_BlockOre_** but rather the normal Minecraft **_Block_** class ([Harder Ores source for ore blocks](https://github.com/Draco18s/ReasonableRealism/blob/1.12.1/src/main/java/com/draco18s/ores/block/ore/BlockLimonite.java)). Your **_OreDiscoverer_** ([AS source - OreDiscoverer.java - line 64](https://github.com/HellFirePvP/AstralSorcery/blob/6ba10e1edc5e1e5a2829e90f7e3e1f57f35991aa/src/main/java/hellfirepvp/astralsorcery/common/util/struct/OreDiscoverer.java#L64)) relies solely on identifying ores by their extension of the BlockOre class.

This could be "fixed" by adding another list like the ones for the mineralis ritual or ritual shrine  (This one [here](https://github.com/HellFirePvP/AstralSorcery/blob/86f9d9e82f78ea2709bcf15b6ed80ee0704bfdd7/src/main/java/hellfirepvp/astralsorcery/common/base/OreTypes.java) if i am not mistaken). This list would get checked in addition to the BlockOre check in the OreDiscoverer class. Thus a user can add other blocks or ores which would be picked up by the infused pickaxe without the need for hard coding any compat for other mods on your end. Of course this is only a suggestion and a hint on how such a thing could be implemented (or rather how i would implement it :-)). By no means do i want to tell you how it should be done if you decide to implement this feature.

**Comment by Lathanael** [comment]
Aehm excuse me?! If you close an issue please also include an explanation why! Either referencing a commit or a simple "won't fix/implement" is enough imo. But closing with no feedback is not ok in my book!

**Comment by Doomgull** [comment]
There's a fucking master ticket all these were compiled under to make navigating the actual issues easier, I just didnt want to link 28 other tickets to it.

Fix your tone for next time.
