### ISSUE TITLE
Thermal Expansion Satchel voids excess items in Starlight Crafting Altar

### ISSUE THREAD

**Issue by loudwhitenoise** [HellFirePvP/AstralSorcery#468]
I have a Hardened Satchel that I've been using to collect my rock crystals, it had about 8 or 9 items in it. When I rightclicked on my starlight crafting altar, the satchel attempted to deposit its contents into the altar. I had already filled some of the altar slots with random stuff. The satchel deposited the first few of its items in the altar and caused the rest to just... vanish. I sent bug report to Thermal team and they say it's on your end, so, good luck.

Update: while breaking the altar can return one's items, if you complete a craft before doing so they go all over the place. I thought my stuff was gone for good.

**Comment by HellFirePvP** [comment]
Break the altar and you get your items back. they're not gone.

What actually happens: The altar has no check when pumping items in via conduit/duct or w/e that it checks the tier of the altar. Thus it may also insert items into higher altar-tier-slots that you just don't have access to. The items went into those slots, so they're not gone, you can't access them atm though unless you progress or simply just break the altar.
