### ISSUE TITLE
High density starfield regions disappeared/moved

### ISSUE THREAD

**Issue by weedenbc** [HellFirePvP/AstralSorcery#469]
Playing direwolf20 1.12, and I had previously mapped out a few different areas where there was a really high density starfield (as measured by the fosic). I built my altar on top of one of them, with a base nearby.

Just updated to the version of the pack that has Astral Sorcery 1.8.4 and it seems all those high density locations are gone. I've managed to find a few more, but the original ones I'd mapped out are gone.

Was this intended?

**Comment by Doomgull** [comment]
#462

**Comment by Doomgull** [comment]
Blame bigger names in the community yelling about seed usage for the change.
