### ISSUE TITLE
[Suggestion]: Add setting for illumination wand's "indestructible" block hardness

### ISSUE THREAD

**Issue by ChronosWS** [HellFirePvP/AstralSorcery#470]
Allowing unrestricted player-creation of indestructible blocks in multiplayer is potentially game-breaking and can only be solved by OP intervention.  A config  option should be added to allow the hardness of the block to be set instead (if possible), or to disable the indestructibility feature entirely (leaving the block merely translucent.)

**Comment by HellFirePvP** [comment]
Just remove the recipe if you don't like the item.
