### ISSUE TITLE
Is the Discidia ritual supposed to damage villagers?

### ISSUE THREAD

**Issue by JiaYow** [HellFirePvP/AstralSorcery#474]
The Discidia ritual apparently damages nearby villagers.

Is this working as intended? The journal states that it is supposed to be "lashing out at all **enemies** nearby", which shouldn't include villagers, should it?

If this is the intended behavior, is there any way to prevent villagers from being affected (e.g. mark them as friendly)?

**Comment by Doomgull** [comment]
Keep the ritual further away from them.

**Comment by JiaYow** [comment]
Hm, I was actually planning to use the ritual to protect the village, but I can find a workaround by placing the ritual anchors on the edges of the area.

I would then propose that you change the description text of the journal, as I assume that most people don't classify villagers as "enemies".

Thank you!

**Comment by Doomgull** [comment]
Use lucerna instead for that purpose.

**Comment by JiaYow** [comment]
I could do that of course, but I was going for bloody murder on those mobs *g*. Anyway, please keep the suggestion about the ritual's description text in your pipeline. Thanks! :-)
