### ISSUE TITLE
Weird glitch when opening Astral Tome

### ISSUE THREAD

**Issue by Hypatech** [HellFirePvP/AstralSorcery#476]
As soon as I open the astral tome, my GUI changes to this:
![image](https://user-images.githubusercontent.com/27899907/34463687-e97950c8-ee5b-11e7-883c-12915824d3b8.png)

My Modlist:
Adventure Bags
Akashic Tome & Morph-O-Tool (I've tested using this and not using it, neither fix it)
Astral Sorcery
Psi
Quark
Botania
ChickenChunks
Embers
Tomb Many Graves
Mouse Tweaks
Inventory Tweaks
JEI
Vanilla Magic

**Comment by Hypatech** [comment]
This is fixed by re-loading resource packs

**Comment by Doomgull** [comment]
Disable optifine's fastrender.

Or they're is something else fiddling with shaders/gui.

**Comment by Hypatech** [comment]
Ah, okay. That fixed it, thanks :P 
Forgot to list optifine in my list of mods, too
