### ISSUE TITLE
Cannot Craft Crystal Lens

### ISSUE THREAD

**Issue by Kattaleya** [HellFirePvP/AstralSorcery#477]
I'm unsure what the problem is, but I cannot craft a crystal lens in the starlight crafting altar. The bar is always red, whereas the previous crafting table (Luminous crafting table) would fill up with a white-blue bar to indicate how much starlight I was getting. I'm using it in the exact same area and in this tier it's simply red. I can craft a looking glass just fine, which requires the same amount of starlight(Average). When I place all the items required in the table it doesn't even show me a preview, as if the recipe is incorrect. Checked the book and I'm pretty sure I've copied it slot for slot. I'm using standard vanilla items and astral sorcery items. The center rock I have is a regular rock crystal, not attuned. I'm using the aquamarine from astral sorcery. There's one regular vanilla gold ingot and two vanilla spruce wood. The three glass lens are not glass panes xD And finally there are two Runed Marble in the bottom slots. 

![crystallensrecipe](https://user-images.githubusercontent.com/34989370/34464037-e11b5fd4-ee24-11e7-8b74-0e82959416e9.png)

![starlightcraftingaltar](https://user-images.githubusercontent.com/34989370/34464038-e745a996-ee24-11e7-92e1-b3f52fd60824.png)

Additional info:
    And yes, I'm crafting at night time as you can see from the moon. The bar is red regardless of day or night. I also have a spectral relay placed with the structure around it, and it's producing blue and white shimmering orbs that float towards my altar. So I assume the relay is working. And yes, I built the massive structure around my altar, including the one sooty marble that sits underneath the altar.

    My server is running version 1.8.4 from FTB Horizons III (v1.5.0) Minecraft Version 1.12.2
By The FTB Team

**Comment by HellFirePvP** [comment]
The altar structure is wrong. Check on the journal entry for information on how it's built. You've built it wrong. The red bar is proof for that.

**Comment by Kattaleya** [comment]
Lol sorry, my stupid one line of scrolling was annoying me, I will check!

**Comment by Kattaleya** [comment]
Found it!!! The bottom of the pillars I placed bricks, but it's chiseled >.<

**Comment by Kattaleya** [comment]
![2017-12-31_12 42 37](https://user-images.githubusercontent.com/34989370/34464132-1ad6fa82-ee28-11e7-903b-933bbd934f67.png)

**Comment by Kattaleya** [comment]
Also, thank you so much for the quick response! :) Really appreciate it.
