### ISSUE TITLE
MC1.12 AS1.8.5 Evorsio Ritual breaks Ritual Anchor/no filter option

### ISSUE THREAD

**Issue by KITbutler** [HellFirePvP/AstralSorcery#480]
How to reproduce: 

- Set up a ritual multiblock (less powerful computer: UP IN THE AIR WITH NO OTHER BLOCKS NEARBY!)
- Place a Ritual Anchor some distance away and link it to the ritual, ideally close to some normal blocks to confirm the ritual is working
- Place an Evorsio-attuned crystal in the ritual and link a corresponding collector crystal
- Wait and observe the ritual anchor that is channeling the ritual.

Key Issue:

- The channeling Ritual Anchor is broken by the destruction ritual, sometimes even before all other eligible blocks are gone.
- The ritual reverts its focus to the multiblock structure. This will obliterate any nearby base and a fully powered ritual can easily cause catastrophic lag due to the dropped items if the multiblock was placed on solid ground.

Secondary Issue:

- The ritual also appears to break many other blocks I personally would rather see remain intact such as modded item pickup systems. 

Simple Solution:

- Add a blacklist for the ritual to prevent anchors from breaking, ideally with a config option to add other modded blocks

Complex Solution:

- Add a mechanic to allow in-game filtering of eligible blocks, for example an inventory (chest) placed on white marble and linked to the Ritual Pedestal to whitelist items inside; placing the chest on sooty marble to blacklist instead.

**Comment by Doomgull** [comment]
Reference: Previously fixed under #338, possible recursion.

**Comment by kmork1** [comment]
I just had this happen to me and when I asked on the discord I was directed here. 
I’m minecraft 1.12.2
As is 1.8.4 
I’m on direwolf20 1.12 pack v 1.5

**Comment by Doomgull** [comment]
@kmork1 this was fixed in 1.8.5, you were told that in discord.

@KITbutler is this actually 1.8.4? It was mentioned 1.8.5 in discord.

**Comment by KITbutler** [comment]
@Doomgull Originally observed in 1.8.4, just reproduced it in 1.8.5 (same modpack+test world, couple updates to unrelated mods). For some reason linking a collector crystal fails to produce the secondary beams of light right now but even the unboosted ritual still breaks ritual anchors including the one above the pedestal and the remote linked one, as well as diamond chests from Iron Chest (which poses a severe lag/crash hazard as many super-large modded inventories will spill their contents when broken...)

Restarting Minecraft fixed the boosting issue but **not** the problem at hand, ritual anchor broke again.

**Comment by Doomgull** [comment]
Screenshots for replication, by chance?

**Comment by KITbutler** [comment]
In the first screenshot you can see the ritual setup, expertly deactivated by a temporary anchor. The Diamond Chest to the left \*ahem\* _used to_ house another Ender Hopper for drop collection. 

![as-ev1](https://user-images.githubusercontent.com/22204328/35755794-fb0299d6-0868-11e8-8042-6f9f4ebbff5c.png)

Linking the anchor to a "remote" destination to the left. The pillar of anchors is purely for scaffolding.

![as-ev2](https://user-images.githubusercontent.com/22204328/35755875-51add854-0869-11e8-929d-210e0de0033b.png)

Fired up! I am using a Botania magnet ring in conjunction with the Ender Hopper to monitor incoming drops.

![as-ev3](https://user-images.githubusercontent.com/22204328/35755903-71b8d6ee-0869-11e8-871f-2f410c464398.png)

Ritual at work during daytime, the anchor scaffolding is already gone and the sinkhole is growing.

![as-ev4](https://user-images.githubusercontent.com/22204328/35755949-9cb0ca78-0869-11e8-8520-29f766195c51.png)

Here I unfortunately got annoyed at the rain and daylight and the anchor broke just as I remedied this.

![as-ev5](https://user-images.githubusercontent.com/22204328/35755976-ba50364a-0869-11e8-9640-ffa0053e71bc.png)

Second time's a charm, no more op commands from now. There _was_ an Angel Block from XU2 beneath that anchor.

![as-ev6](https://user-images.githubusercontent.com/22204328/35756002-d6b5df06-0869-11e8-9005-5d3ccdf8641e.png)

And poof! Still the same night, no admin commands, no other blocks broken by the ritual in the meantime.

![as-ev7](https://user-images.githubusercontent.com/22204328/35756045-fb0cf8e4-0869-11e8-9194-1ffee5a93ec9.png)

The time until failure appears to be semi-random but it breaks the anchor fairly reliably. I have not had the "remote" ritual effect break the "source" anchor so far but that might be luck.

**Comment by HellFirePvP** [comment]
I get the feeling you're not understanding this ritual effect as it is now properly. It does not care about much. If the ritual origin is the ritual pedestal, it'll exclude its structure + 3 blocks height around the outer ring - for lenses - and a central column up to where the anchor is - if there is one or not doesn't matter for this - and that's what got fixed with 1.8.5: It won't break the anchor atop the ritual pedestal anymore.
If you link the effect to a 2nd anchor the effect originates from that anchor. It'll break everything except itself. So if you place it too close to the actual ritual pedestal setup, of course it'll eat that up. And again for good measure: If you link the ritual to a 2nd anchor with the ritual anchor linking, the effect then counts as originating from that anchor. And it will not care about anything except "don't break offset position 0, 0, 0" - cause that's the anchor itself. Besides that, it doesn't give a shit about what to break and what not to break. This isn't a bug, it's the way the ritual works.

**Comment by KITbutler** [comment]
@HellFirePvP sorry, but my observations as outlined in the screenshots (check the last one!) clearly show the ritual breaking the anchor it is linked to, i.e. the "remote" one acting as the focus/origin point of the active ritual. When not linked to a remote anchor I have also observed the now-inactive ritual anchor above the pedestal being broken. The exclusion of the ritual structure itself including lenses appears to be working fine.

And while probably a separate issue, what you outline as the "intended" design frankly does not make much sense. The point of rituals is that they function (semi-)autonomously, but this one poses a severe crash risk if left unattended due to the number of item entities created. And unlike others such as Bootes or Octans it actively works to sabotage any and all means to alleviate this risk except for turning off block drops entirely. What is your intended in-game use case where one would deploy this ritual?

**Comment by HellFirePvP** [comment]
1. i just read through the code again - yeeeeeea..... i've forgot to include smth so it wouldn't break the anchor it's linked *to*. If you only place a non-linked anchor on top of the ritual, it doesn't break that one anymore. that i got fixed at least :P 

2. It doesn't have a good use. Hence why i'm planning to rework it for 1.9

**Comment by KITbutler** [comment]
@HellFirePvP sorry to disappoint you but it broke the anchor above the pedestal in 1.8.5 too. Or is that an upcoming fix?

And if you're reworking things, what are your thoughts on multi-anchor AoE controls (like a Buildcraft quarry, or centre+radius)? Even with just the bugs fixed and a way of collecting drops it would be fine as a quarry/terrain clearing tool.

**Comment by HellFirePvP** [comment]
Alright, so that's fixed now for 1.9 idk if i get to include the rework into that release yet, but at least the ritual will work then. :P 

I'll see how i rework it. i have some rough plans already, soo... *shrugs*
