### ISSUE TITLE
[1.12.2 / Suggestion] Attunement Perks Toggle

### ISSUE THREAD

**Issue by DShou** [HellFirePvP/AstralSorcery#482]
Automated lights is great (Vicio/Miner's Delight), but if anything it'd be nice to be able to disable it such as for when in areas you purposefully want to be dark (such as farming a spawner) for example.

Certain other perks may not be as immediately disruptive but giving the player a choice without repeatedly resetting or just foregoing the perk completely would be nice.

If the feature already exists, I haven't figured it out yet. The most streamlined suggestion imo would be to make clicking on the perks page toggle the perk.

**Comment by Tim2162286** [comment]
hellfire has stated multiple times he will not be adding this feature.

**Comment by CTH999** [comment]
Would be nice, but if you have to, have lights in the spawner. That way, when you go in, the mod says, oh, it's light. Better not place a light source there! and, it prevents mobs from spawning and killing you as well!
