### ISSUE TITLE
playerdata files in excess

### ISSUE THREAD

**Issue by 0m3ns** [HellFirePvP/AstralSorcery#484]
I am running a server, FTB Revelation pack. We have only 4 constant players, on a white list. I am noticing that the player save files and backup files for Astral Sorcery are constantly increment through the day. In the course of 3 days my server has accrued several thousand files, despite inactivity from over half the player base. Is this intended? At 146k and 4k per file pair, adding almost 170mb of information in a short time for 4 players.

**Comment by Doomgull** [comment]
Can you zip and upload some of them? That's not normal unless they're corrupted every time they're accessed or something equally odd.

**Comment by 0m3ns** [comment]
Hi, yes here is a link to the files created on the server. Also, in looking I fluffed the file size, it was bytes not kilobytes, so not quite the file size thing I made it sound like. Sorry for that part. However the number of files still seems high, and over the period of a week or so it does seem to slow down player logins. Thank you for responding to this so quickly.

https://we.tl/58qNvtT8jP

**Comment by Doomgull** [comment]
What are the perms on the directory, and the files themselves? Ownership?

**Comment by 0m3ns** [comment]
I've attached screenshots of the directory and the files with the permissions listed. The server is run by a service, I connect and manage it with a combination of Multicraft and FileZilla. I always test and spin up the server on my local machine before uploading and going live.

No one has progressed in AS as of yet, which is what caught my attention when I was fixing a player's dat file a while back.

![directory perm](https://user-images.githubusercontent.com/16026516/34735357-07121f2e-f524-11e7-8992-8441a7e5939a.png)
![file perm](https://user-images.githubusercontent.com/16026516/34735358-07285078-f524-11e7-811b-ead058d23793.png)

**Comment by Phishinabowl** [comment]
Can also confirm this as well for my server. Been backing up the world folder for the last 51 mins and the majority of whats taking forever is the .astral files. I already have over 20 THOUSAND .astral files in the playerdata folder. This cannot be right...wtf is going on...
![image](https://user-images.githubusercontent.com/18666621/34742613-c032e80a-f554-11e7-9724-b2299f800f84.png)

**Comment by Doomgull** [comment]
Should only be doing that if its failing to read or update the existing file due to corruption or the like. What's server logs contain? 

Also what are you using to back up if it takes 50 minutes for under 50 mb of files?

**Comment by Phishinabowl** [comment]
Using WinSCP but everything up until the astral files was going much faster. The world save is only 1.88 Gigs and it got all the way up to 93% and then just sat chugging on the astral files. I'll have to look into pulling the logs

**Comment by 0m3ns** [comment]
> Using WinSCP but everything up until the astral files was going much faster. The world save is only 1.88 Gigs and it got all the way up to 93% and then just sat chugging on the astral files. I'll have to look into pulling the logs

I know for me when I was using Open Terrain Generator and a mod for world gen in the past, it was the number of files. FileZilla negotiates a transfer request for each individual file from my server host, so even though they were tiny and went quick, the couple seconds to start and finish the transfer added up real fast with several thousand custom world gen files. Could be similar?

**Comment by Doomgull** [comment]
Offline backup, got it. Make a tar copy, then ftp that off instead, guys.

Still going to need a server log to look through, preferably with a server.conf. you can dm that to me on Discord if you don't want to link it here.

**Comment by 0m3ns** [comment]
So I'm not super Discord savvy, how do I find you to DM you? Looks like I need a discord tag or something, was surprised there was no search function. Or is there a channel I can hop into and find you that way?

**Comment by Doomgull** [comment]
AS curse page has a link to the server, I should be easily found from there.

**Comment by Doomgull** [comment]
UUIDs aren't staying static (which they should be since those are set by Mojang per account). No errors on AS side in the logs. AS created a log file per UUID, since that's how it tracks each player's progress, and UUIDs don't change when account names do (Mojang instituted this for exactly that reason).

UUIDs not staying consistent with Sponge running is not a new issue, or uncommon. Please open a ticket with them.

**Comment by ryantheleach** [comment]
@Doomgull On the Sponge side of things "UUID's not staying consistent with Sponge running is not a new issue, or uncommon." Is news to us. To my knowledge we don't mess with the UUID's at all. If you have any more information about it, we would love to hear it.

**Comment by Doomgull** [comment]
Let me see if I've still got the stuff on it in my archives from before.
