### ISSUE TITLE
Rituals spawn monsters insted of doing actual buff

### ISSUE THREAD

**Issue by henkaa** [HellFirePvP/AstralSorcery#485]
I have tried the Aevitas and Armara riutals on our server.
None of them is doing their actual boost effect. All they do is spawn a large amount of mobs.

They have the correct visual effect tho (according to videos I have seen on Youtube)

We are running EOD Synthesis 1.3-RELEASE, which is a 1.12.2 Minecraft with 1.8.4 Astral Sorcery.

**Comment by henkaa** [comment]
Correction.. The reclection bonus on Armara seemed to work. On MY arrows.

**Comment by Doomgull** [comment]
Any changes/edits/updates to the pack?

**Comment by henkaa** [comment]
The modpack is unchanged at the moment according to the server admins.

**Comment by Doomgull** [comment]
I'm having issues replicating the mob spawn stuff. Are you sure you've got aevitas and not pelotrio linked?

Armara deflecting ALL projectiles in intended. It used to do it to grappling wands, too.

**Comment by Doomgull** [comment]
Screenshots or videos, perhaps? not able to replicate on my side.

**Comment by HellFirePvP** [comment]
This was reworked for the next version so those things now 'work' instead of being reliant on the intensity of starlight incoming. specifically refering to the lucerna ritual here. :P
