### ISSUE TITLE
Player progress not loading

### ISSUE THREAD

**Issue by Lazruse** [HellFirePvP/AstralSorcery#486]
I have a semi consistent problem, wherein, my player data will not load when i first load up my game for the day. Where is the Astral Sorcery Progression file located ? And for a noob... can you tell me how to access the files that would show the possible issue. I have to review server logs?

**Comment by Lazruse** [comment]
Incredible work on this Mod BTW!

**Comment by Doomgull** [comment]
Server and Client logs would contain the information. The player file is located in the same directory as the installation for the pack would be.

**Comment by Doomgull** [comment]
@Lazruse an follow up?
