### ISSUE TITLE
[1.12.2-1.8.4] Crafting table recipes don't display in JEI

### ISSUE THREAD

**Issue by Lykrast** [HellFirePvP/AstralSorcery#487]
For some weird reason JEI (1.12.2-4.8.5.143) doesn't see any of the standard crafting table recipes added by this mod. I have tested it for Parchments, Sooty Marble and Marble Arches : all of those can be made in the standard crafting table with no starlight without problem even in survival, but they don't display in JEI.

This also means there's no way to see how to craft Marble Slabs or the Luminous Crafting Table through JEI alone, which is an issue.

**Comment by Doomgull** [comment]
Luminous Table without book is intentional. Rest sounds like a jei issue.

**Comment by Hubry** [comment]
Seems like by default JEI only handles the vanilla/Forge implementations of `IRecipe` ([see here](https://github.com/mezz/JustEnoughItems/blob/e859c33404aed65bff04ce70ab07f0d897773d76/src/main/java/mezz/jei/plugins/vanilla/VanillaPlugin.java#L125-L128) I guess?), while AS has its own implementation of those (`BasePlainRecipe`), meaning a JEI plugin is necessary to handle those.

**Comment by Doomgull** [comment]
Moved to master suggestion list.
