### ISSUE TITLE
[1.12.2] Direwolf20 pack, possible mod conflict dealing with crafting

### ISSUE THREAD

**Issue by SuprTofourK** [HellFirePvP/AstralSorcery#489]
My issue is that the luminous crafting table craft anything. I have checked multiple times, tried with several different recipes (resonating wand and grindstone), and nothing. I even had full star light and nothing happens like help pls.

**Comment by Doomgull** [comment]
Go to the discord with screenshots, better place for help with this than the bug tracker.
