### ISSUE TITLE
[Mod Incompatibility?] Server Crash

### ISSUE THREAD

**Issue by Elvarion** [HellFirePvP/AstralSorcery#49]
Updated AstralSorcery to the new version and this is making ZombieAwareness to start crashing the Server
Pastebin of the Error
http://pastebin.com/SU0Q4AeM

Using 1.1.3 of Astral works just fine

Not sure if its Astral or Zombie thats the root problem, But ive told Coro about this also, so hopefully we can sort this out :)

- AstralSorcery-1.10.2-1.1.4-Beta.jar
- coroutil-1.10.2-1.1.13
- zombieawareness-1.10.2-1.11.3

**Comment by HellFirePvP** [comment]
Same as #47 but just that another mod has a wrapper somewhere. The issue itself is most likely the same.
