### ISSUE TITLE
(1.12.2) Problem With hunger and health bar

### ISSUE THREAD

**Issue by GhostBlade43** [HellFirePvP/AstralSorcery#491]
When I use the Journal after the hunger,health and experience bar become white similar to the texture of starlight liquid. What can i do?

**Comment by Doomgull** [comment]
Search before opening a new ticket to see that this is caused by optifine's fast render setting.

**Comment by GhostBlade43** [comment]
Thanks

Il 7 gen 2018 15:49, "Doomgull" <notifications@github.com> ha scritto:
