### ISSUE TITLE
[1.12.2] Cannot Remove Transmutation Recipes

### ISSUE THREAD

**Issue by EmosewaGamer** [HellFirePvP/AstralSorcery#492]
Starlight Transmutation recipes cannot be removed via CraftTweaker. There are no errors, it simply doesn't work.

**Comment by Doomgull** [comment]
How about uploading your scripts?

**Comment by EmosewaGamer** [comment]
Fair point.
https://pastebin.com/d6j5syzf

**Comment by Doomgull** [comment]
There anything in the server logs during launch when it parses the CT scripts?

**Comment by EmosewaGamer** [comment]
Nope, nothing in the craftweaker nor the regular log.
