### ISSUE TITLE
1.12.2-v1.8.2 - Sword and Axe loose special ability permanently at random.

### ISSUE THREAD

**Issue by Exanadu** [HellFirePvP/AstralSorcery#497]
Sword lost its dmg proc while fighting blazes in the nether. No longer procs. This is on a 1800/100/61 Sword. Sharpened it to 100 didn't help
Axe no longer chops whole trees down just 1 log at a time.  2700/100/31, Sharpening did not help. 

I am assuming this will happen to my shovel at some point. 

This is multiplayer Direwolf 20 pack v1.3.0

**Comment by Doomgull** [comment]
Tome mentions the infusions don't last forever. You need to re-infuse the tool. This behavior has a config option to disable the behavior.

You also should update, you're several versions behind both in AS, and in the pack.

**Comment by Exanadu** [comment]
Thank you for clearing that up. I did not notice the do not last forever part.
