### ISSUE TITLE
Mac cursor disappear after attuning self

### ISSUE THREAD

**Issue by kmork1** [HellFirePvP/AstralSorcery#499]
After I use the atunement altar the cursor on my minecraft client disappears. Can’t makenit comeback in any way other than restarting my minecraft client

**Comment by Doomgull** [comment]
Versions (as/mc/forge/pack), and is this gone after completing the attunement completely and returning back to normal?

And it is limited to the MC cursor, or the cursor regardless of application?

**Comment by Doomgull** [comment]
Duplicate to #12 . Can you update that ticket with your information? Would be nice to finally get some more info to try to track it down.

**Comment by kmork1** [comment]
My email is Kim.mork001@gmail.com

**Comment by desagas** [comment]
Is there an updated for this issue yet?

**Comment by Doomgull** [comment]
No.
