### ISSUE TITLE
Console spam when automating starlight infuser

### ISSUE THREAD

**Issue by mrmorder** [HellFirePvP/AstralSorcery#500]
Setting up a starlight infuser with two mechanical users (from Extra Utilities) (one to place the aquamarine and another to click the block with a wand) causes the console to be spammed with 

`11.01 23:41:18 [Server] Server thread/WARN [Astral Sorcery]: [AstralSorcery] Infusion finished, player that initialized crafting could not be found!`
`11.01 23:41:18 [Server] Server thread/WARN [Astral Sorcery]: [AstralSorcery] Affected tile: BlockPos{x=-3532, y=139, z=1699} in dim 0`

Worse when using a chalice to supplement as it happens about twice a second.

**Comment by Doomgull** [comment]
Well, when something without progression attempts to craft something that requires progression and has no player identity... that sounds about right.

**Comment by mrmorder** [comment]
I'm not concerned about the warning that no user exists but more about the spam when trying to see other issues in the console and someone has automated this.

**Comment by Doomgull** [comment]
What would you propose then, for when an error occurs and a message needs to be created when the logic is attempted and sees an error?

**Comment by mrmorder** [comment]
Only thing that comes to mind is a verbosity config as it's just a warning and not an error specifically.

**Comment by Doomgull** [comment]
That already exists, though: Debug vs Info vs Warn. It's built in.

The easy fix would be to just disable allowing fakeplayers to use it, since apparently the exu users does weird things with its fakeplayer trigger.

**Comment by mrmorder** [comment]
I'm an idiot. Thanks for the help. I'll look for the config setting.
