### ISSUE TITLE
[1.12.2] Things Placed After Iron Ore Turn Into Starmetal Ore

### ISSUE THREAD

**Issue by EmosewaGamer** [HellFirePvP/AstralSorcery#502]
So I have it so Light Gray Terracotta turns into Iron Ore and that turns into Starmetal Ore. The issue is that when that Iron Ore is removed, whatever transmutable block is placed after it will turn into Starmetal Ore.

**Comment by Doomgull** [comment]
Versions?

**Comment by EmosewaGamer** [comment]
The latest - 1.8.4.
