### ISSUE TITLE
[1.12.2-sponge] Tree beacon not turning trees into fake tree with sponge installed

### ISSUE THREAD

**Issue by anthonysan95** [HellFirePvP/AstralSorcery#504]
The tree beacon doesn't turn the tree into the fake tree when it grows with sponge installed.. couldn't tell if the problem was on sponge part or not.. so i wrote here.. tell me if it's not on astral sorcery part.
No errors appears in the console, the tree just grows normally without changing.

---
* Astral Sorcery version: 1.12.2-1.8.4
* SpongeForge version: 1.12.2-2555-7.1.0-BETA-2834
* Forge version: 1.12.2-14.23.1.2566-universal
* Plugins/Mods: Astral Sorcery and Sponge forge
---

Zip containing the server used for testing [here](https://drive.google.com/file/d/11E6P-Gvdi0zhsB5sInb4sU6GzmJL18qs/view?usp=sharing).

**Comment by Doomgull** [comment]
Tree beacon works normally, so if its not working, look to sponge.

Sponge is also not supported with AS, so don't expect a compat fix regardless on this side.

**Comment by anthonysan95** [comment]
Ok thank you.
