### ISSUE TITLE
Optifine + Shaders visual glitch

### ISSUE THREAD

**Issue by Xogue** [HellFirePvP/AstralSorcery#505]
Including Optifine and a shader together with Astral Sorcery causes the shaderpack to react and render (if that is the right word) badly.  The sun follows the cursor, shadows appear "off" (cant really explain that any better) and at certain angles and directions there are glitches with sky textures.

To reproduce:
Minecraft 1.12.2
Optifine 1.12.2_HD_U_C8
Astral Sorcery 1.8.4
Shaders: (I attempted plenty because I thought it was optifine or the shaderpack until I started strategically removing mods)
    Sildur's Vibrant
    Super Shaders
    MrMeepz Shaders
    SEUS
    KUDA
    more....

that should be all that is required but in case you need it my computer specs:
Intel Core i7-7700k CPU
16GB RAM (Over 6GB given to the MC instance)
NVIDIA GeForce GTX 1070 w/8GB VRAM

Ill check back periodically in case you need more info

**Comment by Doomgull** [comment]
AS uses it's own Shader to handle the sky stuff. Known and documented issue. Engage the "weakSkyRender" config option to shut down the AS one. There's not really a way to run "compatibility" without a complete recode.
