### ISSUE TITLE
[1.8.4] Rituals stop working when player switches dimentions

### ISSUE THREAD

**Issue by raellol** [HellFirePvP/AstralSorcery#506]
I've experienced this bug with the following rituals: Lucerna,Vicio and Aevitas on a single player map.
After comming back from a different dimentions my rituals don't work anymore. the bug occurs both wit anchored rituals and non- anchored rituals. I keep the chuncks loaded. The bug doesn't occur when traveling in the same dimention (teleporing or other) but everythime I leave the overworld, (nether, end, compact machine, ....)  to fix this i need to quit and rejoin.
Teleporting far away and then switching dimensions doesn't fix the issue.

I'm playing the direwolf20 modpack (v1.5 and v1.6) wich uses Astral sorcery V1.8.4 for minecraft 1.12.2

**Comment by Fey142** [comment]
#413

**Comment by Doomgull** [comment]
As mentioned above, known issue. Please search the existing open tickets before opening new ones.
