### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by JedTheSeeker** [HellFirePvP/AstralSorcery#508]
The server crashes everytime I right click a wolf to sit it down while I have the Astral Tome book in my hand. this is the crash report
[crash-2018-01-16_00.42.12-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/1633250/crash-2018-01-16_00.42.12-server.txt)

**Comment by JedTheSeeker** [comment]
Also, the dog may be corrupted. Maybe it's the way I sat the dog down but I dunno. the FTB Revelation version is 1.2.0

**Comment by Doomgull** [comment]
That crash log is an NPE for the AI. I really don't think AS has anything to do with that, especially since it's not even in the stack trace.

What happens if there's no Tome in your hand?

**Comment by HellFirePvP** [comment]
I doubt this is on AS' end

**Comment by Yusixs** [comment]
Works fine for me, 
Direwolf 1.12 modpack 
Astral Sorcery 1.8.4

**Comment by Doomgull** [comment]
@JedTheSeeker any other information to indicate this is an AS issue at all?

**Comment by Doomgull** [comment]
@JedTheSeeker poke poke
