### ISSUE TITLE
Self inflicted Bleeding effect with Discidia attunement.

### ISSUE THREAD

**Issue by Jeffnukem** [HellFirePvP/AstralSorcery#509]
Version 1.12.2-1.8.4 
Direwolf20 pack Ver.  1.12-1.12.2-1.7.1 

Attuned with Discidia, Discida wand, and Mantle of the Stars with Discida upgrade.   I end up with Bleeding II and it breaks my armor and kills me  when attacking mobs.  The effect amplifies when attacking multiple mobs in sequence.

**Comment by Doomgull** [comment]
From Discord testing: Only replicated with both Discidia Mantle and Discidia Rod equipped.
