### ISSUE TITLE
[Typo?] SkyCollectionHelper.linearInterpolate(float, float, float)

### ISSUE THREAD

**Issue by StanleyMines** [HellFirePvP/AstralSorcery#511]
https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/util/SkyCollectionHelper.java

Line 78-81 in SkyCollectionHelper has method "linearInterpolate", but the code is cosine interpolation.

Fixes:
1) Rename to cosineInterpolate
2) Change body to: "return (h-l)*partial+l;"

PS:
Thanks for making such an amazing mod! Keep up the good work! :D

**Comment by HellFirePvP** [comment]
eh.... wth. lol.
it is not supposed to do linear interpolation. i was mainly just too lazy to change names after changing the interpolation method. not that it matters too much anyway as i probably won't tough the noise generation any time soon again and it's private so not like anyone calls that on accident :P 
gonna fire a rename through it anyway *shrugs*
