### ISSUE TITLE
Not able to view glass lens recipe from looking glass recipe

### ISSUE THREAD

**Issue by JayaramV-Hexaware** [HellFirePvP/AstralSorcery#512]
Version:  astralsorcery-1.12.2-1.8.4

Clicking on glass lens to view its recipe from crystal lens recipe works fine.
Clicking on glass lens to view its recipe from looking glass recipe doesn't work.

Expected:  Clicking on glass lens to view its recipe from looking glass recipe should work fine.

**Comment by HellFirePvP** [comment]
Problematic. The glass lens recipe is on the same research-pages as the looking glass. So doing a lookup you can go down indefinitely by just constantly looking up the same recipe over and over again.

Idk. probably not too problematic though... will re-enable this as it was once disabled for that exact reason.

**Comment by JayaramV-Hexaware** [comment]
I'd agree that it's not that problematic.  Given that it's a manual action that lets them drill infinitely down, one could argue that you get what you go looking for.

Appreciate the prompt response.  It's a trivial thing, but for a first time player of this mod (like yours truly), it felt like a broken functionality at that time.
