### ISSUE TITLE
Master Network Disconnection/Weirdness Ticket

### ISSUE THREAD

**Issue by Doomgull** [HellFirePvP/AstralSorcery#513]
This is the ticket for referencing the other miscellaneous network disconnection/weirdness tickets, since as far as even CPW can tell, the network packet code is implemented per Forge standards.

#360
#374 - Involves multiple chalices interacting.
#447 - Involves dimension crossing into Aether.
#457 - Involves Telescope.
#479 - Involves crossing dimensions.
#515 and #669 - NPEs on player login.
#528 - NPE on transitioning into nether.
#603

**Comment by HellFirePvP** [comment]
AS version 1.9 will include a potential fix for this. I can't say much for sure since i can't reproduce this issue, however from a logical point of view, it should work? We'll see when 1.9 comes out.

**Comment by Xules01** [comment]
I'm seeing this with my players as well. It seems to happen during the time AstralSorcery is trying to synchronize configuration files with the player. Is there a way you could try putting a delay on this so it's not happening while the player is trying to login?

**Comment by Doomgull** [comment]
That's really not how config syncing works. It's also not an AS specific thing, just happens to be occurring when AS is in the stack to sync the configs. 

Have you already added "-Dfml.readTimeout=90" to the server java args, and had your clients who are having connection issues do the same to theirs?

**Comment by Alaberti** [comment]
Is this related to this issue? https://paste.dimdev.org/bohibumece.txt This crash occurred as I was standing in the Galacticraft Mars dimension.

**Comment by Doomgull** [comment]
No, different issue already fixed for next version.

**Comment by HellFirePvP** [comment]
This thread has been silent for a while.. Has anyone had this specific issue pop up again?

**Comment by RickBlaine** [comment]
I believe I am running into this issue on kingdomscity.com using sevtech.  When I place a chalice near a lightwell then put a rock crystal above the lightwell, the server kicks me off.  I don't have access to the server logs.  Nothing in the client side logs looks unusual.

So long as the chalice is taking liquid star light from the light well, I get kicked off the server when I log on near the chalice.

**Comment by Doomgull** [comment]
Unfortunately, I believe sevtech is about 5 versions out of date, still, so its not necessarily helpful.

**Comment by Hazmatik** [comment]
I just had similar issue happen on FTB Revelation which is using Astral Sorcery version 1.9.4, as soon as I placed a chalice next to a lightwell that had some liquid starlight and an aquamarine in it I was kicked from the server and everytime I try to log in I get kicked again instantly.

**Comment by HellFirePvP** [comment]
This sounds similiar to another issue that was pointed out with liquid sparks crashing the client. This doesn't sound at all what this issue is about though.

**Comment by Hubry** [comment]
Seeing a variation of this on a server I play on. Trying to join the game results in getting disconnected more quickly than the usual timeout. A server reboot seems to fix this.

[Log snippet](https://gist.github.com/retep998/5fe6d715fe437b656071fbe218696575) provided by server admin, [modpack](https://minecraft.curseforge.com/projects/wikipack-3-2). Client log shows nothing unusual, just the standard "an existing connection was forcibly closed by the remote host" netty stacktrace.

**Comment by PocketfulOfGeese** [comment]
Closing this since 1.12 is no longer being actively updated, and appears to no longer be an issue post 1.12.
