### ISSUE TITLE
Picking up 2 constellation papers while 11 are discovered, leads to a duplicate

### ISSUE THREAD

**Issue by JayaramV-Hexaware** [HellFirePvP/AstralSorcery#514]
I had discovered 10 and saw 3 new constellation papers in a chest.  When I picked up all 3, the first one got discovered into a new constellation (Fornax, I think).  The second correctly discovered the last remaining constellation Mineralis.  The third should have said nothing's found, but it ALSO resolved as Mineralis.  I tried dropping it and picking it up again, but it still said Mineralis.

It's a minor bug or even a feature ;), if if it resolves properly for a new player who may subsequently discovers it after the bugged player leaves the duplicate in the chest.  If it doesn't, it'd need looking into, I guess.

**Comment by Doomgull** [comment]
Discovery triggers on the paper entering a player's inventory, so don't fire it so fast the server can't keep up?

/shrug

**Comment by HellFirePvP** [comment]
Not much i can do about that.. seems like me changing the 1st item doesn't get recognized/applied to the inventory before the 2nd one updates & checks the playerdata for what constellations the player has 'seen'...

Oh wait. could you send me a copy of your log of when that happened? The whole log file please.
