### ISSUE TITLE
NPE's on player login(?)

### ISSUE THREAD

**Issue by i9hdkill** [HellFirePvP/AstralSorcery#515]
Forge: 2587
Client Forge: 2587
AS: 1.8.4
Pack: Direwolf20
Recently one player reported that he gets a ping of 900+ and a timeout after some sceonds if he enters his claim. (Other players have the same issue on his claim).
As his claim is kinda big, it's hard to debug. But it seems like a mod is spamming packets like hell, resulting in a high ping + timeout.
I am not telling AS is doing that, but got this errors and thought thats a good way to start debugging this issue.

He isn't able to join if he logged out on his claim. From time to time, his login attempts gives this NPE's:
https://pastebin.com/YZcYu6AZ

**Comment by HellFirePvP** [comment]
you can line yourself in at #513 since it's the same issue... - once i know more about the source of this issue, you'll be able to see it on there. But thanks a lot for reporting it!

**Comment by HellFirePvP** [comment]
Can you send me his AS player data? it's in the overworld world directory in a folder called "playerdata". lookup his UUID. his playerfile there will be UUID.astral & UUID.astralback

**Comment by i9hdkill** [comment]
Sure:
https://www.dropbox.com/s/9gd97yks5vfb59s/f81224bc-0a74-472e-8c8b-e66428f9cf5e.zip?dl=0
I asked the player what he did place last before this timeout issue arrised. He said he placed a "Containment Chalice". But he isn't 100% sure if thats the last thing he did.

**Comment by HellFirePvP** [comment]
Thank you, will dig through it tomorrow. As for the issue itself, yea... it is weird and appears with random things... >_> as stated above, we created a issue that collects all the other issues that basically have the same type of issue appearing as this one. So. as far as future information on a fix goes, you might find/hear-about more there in the comments if i post about it.

**Comment by Hazmatik** [comment]
I had a similar thing just occur with me after placing 2 containment chalices and putting lava in one and as soon as i added liquid starlight to the other now I can't go near it or I get disconnected with a message about the server going down, yet the server is still online. This happened on FTB Revelation version 1.3.0 using Astral Sorcery version 1.8.4 with Forge 2587

**Comment by Doomgull** [comment]
Archiving as being tracked in master ticket for this issue (513), please see that ticket for all future updates on resolution. Additional logging not required at this time unless requested.

Also, Hazmatik, yours sounds more like 374, not this ticket.
