### ISSUE TITLE
I think astral sorcery is crashing my server..

### ISSUE THREAD

**Issue by BrockDierksen** [HellFirePvP/AstralSorcery#516]
Think its something to do with this line `at hellfirepvp.astralsorcery.common.entities.EntityLiquidSpark.func_70071_h_(EntityLiquidSpark.java:138)` but im not sure. Every time i log onto the server it crashes it. The server was fine until i used the astral transport thing and traveled to where my astral temple was.

[crash-2018-01-21_20.10.52-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/1650167/crash-2018-01-21_20.10.52-server.txt)

Managed to log in and while it was constantly freezing teleport myself out of the chunk. Which did not crash the server. So something about that chunk which is pretty much entirely astral sorcery being loaded is doing something.

**Comment by Doomgull** [comment]
At a quick glance, looks like it's the chunk firing an update that is hanging the network stack.

**Comment by BrockDierksen** [comment]
Is there a way to fix it? Been staying out of the area but i have a lot of resources at it.

**Comment by Doomgull** [comment]
Could try restarting the server and see if it replicates afterward, perhaps.

**Comment by BrockDierksen** [comment]
Yeah it does. If im in the area its super choppy and minecraft stops responding then the server crashes. When it was first being choppy and freezing i could leave then rejoin and it fixed itself, but that doesnt work anymore it just crashes the server.

**Comment by Doomgull** [comment]
Take a backup of the world, pull AS, then launch, what happens?

**Comment by BrockDierksen** [comment]
I'll try it when i get off work.

**Comment by BrockDierksen** [comment]
So after updating forge to 2602 I think the problem was fixed. Maybe using the latest forge isn't such a good idea. Should i use the recommended or stick with latest?. Hopefully the error doesn't occur again. Thank you two for helping me.

**Comment by Doomgull** [comment]
I'd recommend using the minimum version required for the mods in the pack, or latest "stable" marked version, whichever is later, tbh
