### ISSUE TITLE
Starlight infuser mot working

### ISSUE THREAD

**Issue by Zilvynrae** [HellFirePvP/AstralSorcery#518]
Ok, i have built a starlight infuser, I rebuilt it, I double checked everything is in the correct spots, i even double checked to make sure i'm using astral sorcery marble and not chisel marble but the stucture just isn't working.

![2018-01-21_23 41 12](https://user-images.githubusercontent.com/19956327/35209995-af749cb2-ff0d-11e7-921c-a8423a55ab24.png)
![2018-01-21_23 41 20](https://user-images.githubusercontent.com/19956327/35209997-b06ffb7a-ff0d-11e7-8f2b-6d88768158ac.png)
![2018-01-21_23 41 40](https://user-images.githubusercontent.com/19956327/35210000-b16e350a-ff0d-11e7-99d1-9a8470ef1833.png)
![2018-01-21_23 41 45](https://user-images.githubusercontent.com/19956327/35210003-b2d67790-ff0d-11e7-955b-5dcbdc6eef20.png)
![2018-01-21_23 41 57](https://user-images.githubusercontent.com/19956327/35210005-b40691c2-ff0d-11e7-91ee-b790617b8642.png)

Astral sorcery is updated to 1.12.2-1.8.9

full list of mods
![mod list](https://user-images.githubusercontent.com/19956327/35210110-1e88c790-ff0e-11e7-9b63-c6db5f116478.PNG)

forge version is 1.12.2 forge-14.23.1.2601

**Comment by Doomgull** [comment]
What is the process you are attempting to infuse, and where is it failing? Not accepting the item when right clicking the infuser? Infusion notbstaring when right clicking the altar with the resonating wand after placing an item in it?

**Comment by Zilvynrae** [comment]
Sorry, should have been more specific about not working. It would accept the item which was an aquamarine. But the process would not start after right clicking with the resonating wand. I assumed at first that I had missed a star liquid spot, but I double checked and had all 12, then rechecked the multi block and as far as I can tell everything there is correct as well. Tried during the day and night, relogged a few times, tore down and rebuilt the structure, but did not seem to fix the issue.

On Jan 22, 2018, at 4:22 AM, Doomgull <notifications@github.com<mailto:notifications@github.com>> wrote:


What is the process you are attempting to infuse, and where is it failing? Not accepting the item when right clicking the infuser? Infusion notbstaring when right clicking the altar with the resonating wand after placing an item in it?

**Comment by Doomgull** [comment]
Its an AS aquamarine, correct?

Also, you have Tome progression for the infuser, correct? The infusions are gated.

If the answer to both of those is yes, I would highly recommend going to the Discord server because there are a lot more people there who can assist troubleshoot the issue who are not on a mobile device. This is not a bug, it's just something that is wrong.

**Comment by Zilvynrae** [comment]
It is as aquamarine and ya I'm past that in the tome, I was going to hop on and record a quick vid for you to show you that my multiblock is right and that it wasn't working and then it decided to work...
So my apologies, I don't know why it wasn't working yesterday, If i somehow recreate the bug i will let you know what caused it
