### ISSUE TITLE
Chalice doesn't work with Mekanism pipes

### ISSUE THREAD

**Issue by JayaramV-Hexaware** [HellFirePvP/AstralSorcery#519]
As indicated in the subject, the chalice doesn't support piping in or out using Mekanism pipes.  It does however work with fluiducts from Thermal.

**Comment by Doomgull** [comment]
Someone in the discord used mek pipes the other day successfully, so this is incorrect. They only work from the bottom, like all pipes. Please check configuration.

**Comment by JayaramV-Hexaware** [comment]
![2018-01-22_19 46 49](https://user-images.githubusercontent.com/31346880/35252194-41f986d4-ffad-11e7-8a04-f8156e5358a3.png)
It's definitely not working properly.  On connecting for the first time, it fills like 80% of the chalice (not 100%) with the liquid.  Once the liquid is used, it does NOT replenish the liquid through the pipe though the source still has liquids to provide.  It is consistent with lava, liquid starlight & water.  I've attached a screenshot showing the filled up capacity of the chalice with mekanism pipes versus fluiducts even after 10 minutes of letting them stay.  The tanks below them each have well over 6,000 buckets of water at this point.  Please also note that for the animations to start in both chalices, I have to right click on each of them with a bucket filled with water.  They don't start automatically as the chalices are filled with the fluid.
![2018-01-22_19 46 46](https://user-images.githubusercontent.com/31346880/35252191-3e11722a-ffad-11e7-88f4-3939ec424837.png)
I've noticed another oddity.  Piping fluids using fluiducts or mekanism pipes may fill the chalice partly or fully, but it doesn't engage the chalice animation or start the chalice interaction.  We need to take a bucket of the fluid and right click the chalice with the fluid (though the chalice may already be full of that fluid) to start the animation and interaction with other chalices, etc.

**Comment by Doomgull** [comment]
It's a tank. It just sits there and waits for pipes to work on it. The tanks also only ever hold 24 buckets of fluid. If anything is wrong, it's your tooltip display, or the mek pipes.
