### ISSUE TITLE
About Armara perks

### ISSUE THREAD

**Issue by Waisse** [HellFirePvP/AstralSorcery#52]
Armara is about protection, armors and shields. Yet some perks would make more sense in other constellations  : 

- Additional feathers : take less damage from falling.
Belong more to Vicio that is about travel. Should be replaced with something about shields or movement impairing resistance.

- No armor is more armor : resistances and heal when wearing less than 2 armor pieces.
Again belong more to Vicio. This perk should indeed grant a bonus for wearing full armor sets, with said bonus scaling based on armor points.

Not related to the issue, but I have to say it : your mod is amazing ! Been playing it since the release and I love it. 👍

**Comment by Elvarion** [comment]
Was kinda hoping that Armara had some kind of protection against fatal damage with a longer cooldown as final perk
.
Armara could be improved I think (Not bashing! since I also really like this mod ^^)

**Comment by HellFirePvP** [comment]
Armara and all other major-constellations got new perks.. Problem still is that there's only so much that vanilla mechanics offer in terms of defensives. I will change things around with perks more as time moves on..
So i'm gonna close this for now~

**Comment by Waisse** [comment]
My original post is still relevant. I really want another bonus from those 2 perks. 

What about an armor toughness bonus to replace No armor is more armor ? I mean the point of Armara is to wear armor.
