### ISSUE TITLE
Horrible HUD problem once I open the journal (1.12.2

### ISSUE THREAD

**Issue by YellowSnowmann** [HellFirePvP/AstralSorcery#521]
As the title states, once I open up the journal this happens.
![2018-01-23_15 48 31](https://user-images.githubusercontent.com/35748754/35306996-82a779fe-0055-11e8-9b81-432a955981d5.png)
Maybe it's something with my PC.

**Comment by Doomgull** [comment]
#72 

Checking closed issues for any number of words in your title would have shown there were 13 previous tickets.
