### ISSUE TITLE
[Re-Open] Conflict with Universal Remote

### ISSUE THREAD

**Issue by orbwoi** [HellFirePvP/AstralSorcery#522]
Reposting this appears to not have been seen in #475 since it was closed.

This is being caused by the MiscUtils.isPlayerFakeMP() method in Astral Sorcery. See this line of code.

Universal Remote currently extends the player class of actual real players in order to avoid being a complicated core mod.

Unfortunately, the cannonical way developers have been checking for fake players precludes extending the base minecraft player class. See orbwoi/UniversalRemote#21 for a discussion I had with darkhax about the fake player check and object oriented programming principles.

I'm honestly curious why lines 308-317 are even needed. If they have a null connection or are not in the player list, isn't that good enough? Why care about the class being used? I've confirmed universal remote works properly with astral sorcery with those lines commented out.

**Comment by HellFirePvP** [comment]
> Universal Remote currently extends the player class of actual real players in order to avoid being a complicated core mod.

Yea. sure. let's just all overwrite each other's EntityPlayerMP classes cause that's better than adding 2 lines of code to it. Any tests with GC or other mods that do the same?
This whole discussion about coremods is just a shitshow.

Regardless. Player-class check added.
