### ISSUE TITLE
Bootes ritual doesn't drop wool

### ISSUE THREAD

**Issue by JayaramV-Hexaware** [HellFirePvP/AstralSorcery#526]
Bootes ritual is dropping mutton, but not dropping wool (of any color).  Wool being a natural drop on killing sheep, it's reasonable to expect they'd drop wool (of the appropriate color).

**Comment by Doomgull** [comment]
Its insanely rare because of how wool drops are handled off vanilla sheep. Might be time for even more special casing of wool.
