### ISSUE TITLE
Suggestion CraftTweaker/Config - Grindstone double chance support

### ISSUE THREAD

**Issue by GlacieredPyro** [HellFirePvP/AstralSorcery#527]
It would great if it were possible to change the double chance of ores via the config file or the craftweaker Grindstone Recipes.

Looking at the source the config file would likely be the simpler option.

I would like to gate progression behind the grindstone, ideally without the chance for extra dust.

**Comment by Doomgull** [comment]
Pulled under existing CT suggestions in master sugg thread.
