### ISSUE TITLE
[1.12.2 1.8.5] Crash upon entering the Nether

### ISSUE THREAD

**Issue by NotAVerb** [HellFirePvP/AstralSorcery#528]
Only the integrated server crashed. I am unsure if this has anything to do with NetherEX, which is also installed but was unmentioned by the log.
https://gist.github.com/NotAVerb/fd7b8440c1f4a6aaab1904d4f83c188b
Some sort of nullpointer exception.

**Comment by HellFirePvP** [comment]
another occurence of #513

**Comment by Doomgull** [comment]
Archiving, please see ticket 513 for resolution information once available.
