### ISSUE TITLE
World goes transparent when looking at things. 

### ISSUE THREAD

**Issue by pixzi** [HellFirePvP/AstralSorcery#53]
I've been playing with a few mods on 1.10.2 for a bit. I decided to add AS to the pack as it looks amazing, so i loaded a new world to test it and behold leaves on the trees went transparent so did the ground, i could see through the world to lava pools below. 
 The picture below shows what happens when i install and run the mod, the orange in the first picture is the lava below. 
  I have checked all my other mods and i can not replicate it without AS, there is no crash report so i can't determined what is causing it. Anyone able to give any insight?
  Just to note as well, if im in f1 mode it doesn't do it either. Just when i tried to play normal

I don't have optifine installed at the moment, i did but it still caused the issue with or without. 
EDIT: Also don't have any waila of any kind either. (Noticed the closed post about this).

With AS installed.
![2017-03-05_10 05 51](https://cloud.githubusercontent.com/assets/26198439/23586376/7281b5f4-018b-11e7-942c-53ad5ae07f28.png)
![2017-03-05_10 04 47](https://cloud.githubusercontent.com/assets/26198439/23586404/f1650b8c-018b-11e7-9ffd-f141f73b36a4.png)

Without AS installed and in F1.
![2017-03-05_10 05 54](https://cloud.githubusercontent.com/assets/26198439/23586377/757b0120-018b-11e7-9483-053d8f753dd4.png)

**Comment by pixzi** [comment]
Mod List:

 AdvancedRocketry-1.10.2-1.0.12
  animania-1.10-1.0.1a
  Aroma1997Core-1.9.4-1.1.1.1
  AromaBackup-1.9.4-1.0.1.1
  ArsMagica2-1.10.2-1.5.0-17b
  astralsorcery-1.1.4-beta
  AutoRegLib-1.0-2
  backpack-3.0.1-1.10.2
  Baubles-1.10.2-1.3.9
  betterbeginnings-MC1.10.2-b0.9.8-R4c
  BetterFps-1.3.2
  Botania r1.9-340
  Chisel-MC1.10.2-0.0.8.12
  CodeChickenLib-1.10.2-2.5.6.233-universal
  CoFHCore-1.10.2-4.0.0.127-universal
  concreteMod-v1.0
  CreativeCore v1.6.25 mc1.10.2
  Customized Dungeon Loot 1.10.2 (v.1.0.0)
  Cyclic-1.10.2-1.10.13
  DoomlikeDungeons-1.9.0-MC1.10
  DungeonTactics-1.10.2-0.11.3
  EnderCore-1.10.2-0.4.1.65-beta
  EnderIO-1.10.2-3.1.156
  foamfix-0.6.1-anarchy
  GraveStone Mod 1.4.9
  GrimoireOfGaia3-1.10.2-1.5.3
  jei_1.10.2-3.14.5.406
  LibVulpes-1.10.2-0.1.16-universal
  liteloader-1.10.2-release
  LittleTiles v1.3.10 mc1.10.2
  LootBags-1.10.2-2.3.2
  Mantle-1.10.2-1.1.5
  mod_voxelMap_1.6.21_for_1.10.2
  MooFluids-1.10.2-1.7.02.12b
  MouseTweaks-2.7.3-mc1.10.2
  multistorage-1.10.0-1.2.15
  natura-1.10.2-4.1.0.24
  NoMoreRecipeConflict-0.6(1.10.2)
  OptiFine_1.10.2_HD_U_D6_MOD
  OreExcavation-1.2.84
  ProgressiveAutomation-1.10.2-1.7.0
  Quark-r1.1-70
  shetiphiancore-1.10.0-3.3.7
  TConstruct-1.10.2-2.6.3
  ThermalExpansion-1.10.2-2.0.0.64-universal
  ThermalFoundation-1.10.2-2.0.0.64-universal
  TinkerToolLeveling-1.10.2-1.0.1

**Comment by HellFirePvP** [comment]
Any idea which one of those?... I would rather not try rebuild the pack, try replicate the issue and then search through all the mods myself... >_>

**Comment by pixzi** [comment]
I have gone through all the mods adding one by one with AS and AS on its own but i can't replicate it. I'll try a clean instance and will let you know.

**Comment by pixzi** [comment]
Okay so i went through them again on a clean install, i removed NoMoreRecipeConflict and set default world gen rather then quarks realistic one. 
  I must have glanced over that mod not realising or the clean install and normal gen did something. Either way one of those thing's fixed it!

Thank you for your time.

**Comment by HellFirePvP** [comment]
If you come across it again or pinpoint the mod, please let me know ;)
