### ISSUE TITLE
Celestial gateway bug, cannot place/interact after teleportation

### ISSUE THREAD

**Issue by helldragger** [HellFirePvP/AstralSorcery#530]
My friends and I are playing with the FTB revelation mod pack (unmodified 1.4.0 version) and the bug arises when we use a celestial gate to another world. When we do so we can still destroy blocks but cannot interact or craft anything anymore until we disconnect and reconnect

Forge version: 14.23.1.2601 
minecraft version: 1.12.2
mod version included in the modpack: astralsorcery-1.12.2-1.8.4

No log or errors thrown I can remember of.

To add more details, the first gate is in the overworld and the second one is in the simple void world dimension.

**Comment by helldragger** [comment]
To add more details, the first gate is in the overworld and the second one is in the simple void world dimension

**Comment by Doomgull** [comment]
1.8.5 had a large number of bugfixes covering instances similar to this. Please update and verify if still an issue.

**Comment by helldragger** [comment]
Done, updated manually and the bug is still there, still cannot interact with crafting tables or blocks after a teleportation via celestial gate..

**Comment by helldragger** [comment]
Found a fix when trying to open the astral book, the client seems to remember the shift key of the sneaking needed to teleport even after the teleportation if you release it during the loading screen.

It causes you to have to re press shift to re-trigger the key release event correctly, even though the game considers you are not sneaking as the key is not really pressed, so you walk at normal speed. But can't interact with blocks.

The problem seems to be located around the teleportation initiation event.

**Comment by Doomgull** [comment]
It just moves you.

And vanilla has that issue on its own with how the game recognizes key inputs.

At least thrres another piece figured out.

**Comment by Doomgull** [comment]
No, my point is: MC, even with no mods, has a history of not recognizing key inputs during a world transition. Happens a lot with alt+tab and throwing items from inventories because of it.

**Comment by helldragger** [comment]
Yup, I do understand your point, that's why I suggested to see with aroma how he did his work around for his portal, because you can only trigger the TP by sneaking in them, and it does not have this key ghosting problem. As far as I know it's the only other teleportation related mod using sneaking as a trigger input, and he might have found a useful workaround you could use. 

Otherwise as I said, the only way to avoid it would be to avoid using sneak as a trigger input

**Comment by HellFirePvP** [comment]
Fixed the desync of the sneaking flag as it - until 1.8.5 - gets easily desynced between server and client. In specifics: the client's sneak-flag gets cleared after teleportation, the server's flag persists, so the player is sneaking as far as the server's view is concerned and is not sneaking as the client's view is concerned.
From what i heard, bugs like key-input not fully processing has been a issue for a while in mc.

>seems to always be true when sneaking, potentially making it redundant with player.isSneaking(), but I may have misunderstood the condition ^^' potential bug over here

No, that is not a bug. You can either use the teleport with shift or by holding rightclick. It's made to have both.

**Comment by helldragger** [comment]
I see. Seems like you found a fix though, that was hella quick! I didn't know that you could just use right click, thanks for the clarification!

**Comment by Doomgull** [comment]
It was the original method to use the gateway. Sneaking was added due to excessive complaints it wasn't working/tickets being opened for it.
