### ISSUE TITLE
Marble Slab Blocking Light 

### ISSUE THREAD

**Issue by InsomniaKitten** [HellFirePvP/AstralSorcery#532]
The marble slab blocks light when it is not a double slab, causing weird lighting issues, which can be seen on the surface of a lower slab and the block faces adjacent to the upper slab in the screenshot below.

**Mod version:** [1.12.2-1.8.5](https://minecraft.curseforge.com/projects/astral-sorcery/files/2523583)

![screenshot](https://i.imgur.com/EZK3pAm.png)

**Comment by InsomniaKitten** [comment]
I don't mean to be rude, but this is far from a complex issue
You need to remove your call to `Block#setLightOpacity` at [BlockMarbleSlab.java#L57](https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/block/BlockMarbleSlab.java#L57)
Lighting opacity and AO is already handled by `BlockSlab#isOpaqueCube`

**Comment by Doomgull** [comment]
Should have dropped that into the Discord when discussing it several days ago, I just tag things as discussed.
