### ISSUE TITLE
CTD Possibly AS related  revelation 1.2

### ISSUE THREAD

**Issue by kazaryu** [HellFirePvP/AstralSorcery#533]
So full scenario, i loaded the game gathered teh materials and began teh process of creating a mantle of the stars. Then while that was happening decided to go check my telescope for horo. as soon as i opened the telescope GUI the game crashed. 

[crash-2018-01-18_11.13.24-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/1670555/crash-2018-01-18_11.13.24-server.txt)

**Comment by Doomgull** [comment]
Astral sorcery isn't anywhere in that stack Trace, is it something you can repeat via testing? It calls out the thermal expansion Satchel in there.

If it's something you can repeat, can you manually update astral sorcery to the 1.8.5 version and test again?

**Comment by HellFirePvP** [comment]
https://github.com/CoFH/ThermalExpansion/blob/1.12/src/main/java/cofh/thermalexpansion/item/ItemSatchel.java#L127-L133

Nothing really stands out to be an AS issue tbh.

**Comment by HellFirePvP** [comment]
Was seemingly fixed on KL's side from what i can see on his commit. closing this.
