### ISSUE TITLE
[Visual] Stellar Refraction Table + Sunrise = Visual Glitch

### ISSUE THREAD

**Issue by StanleyMines** [HellFirePvP/AstralSorcery#538]
Minecraft: 1.12.2
Forge: 14.23.1.2584
AstralSorcery: 1.8.5
Optifine: 1.12.2 HD_U_C8

Hovering over constellation in Stellar Refraction Table at sunrise made stuff not look right. 
Table did not have any items in it.
Maybe caused by optifine? idk.

![2018-01-28_21 53 41](https://user-images.githubusercontent.com/4878558/35495518-112f6924-0476-11e8-98d6-80ebc85e847f.png)
![2018-01-28_21 53 42](https://user-images.githubusercontent.com/4878558/35495520-1562d2e2-0476-11e8-90d2-b58433df1a99.png)

**Comment by StanleyMines** [comment]
First is normal
Second is hovering over a constellation.

lol screenshot got my fraps fps in it. xD

**Comment by HellFirePvP** [comment]
The book refers to this process only be doable at nighttime iirc?
Regardless, you can only engrave constellations and enchant things with it at nighttime.
