### ISSUE TITLE
Desert Shrine spawn in wrong biomes

### ISSUE THREAD

**Issue by Lorexe** [HellFirePvP/AstralSorcery#54]
Hello,
I find a desert shrine in a mesa biome : http://i.imgur.com/MkZierJ.png
In the config, desertStructureIgnoreBiomes is set to false (default)

I don't know if "desert shrine" are supposed to spawn only in desert or "hot biomes"
but if they can spawn in mesa, maybe you can try to used red sand ?

Version : 
forge-12.18.3.2239
AstralSorcery-1.10.2-1.1.4-Beta

Thanks for your work :)

**Comment by HellFirePvP** [comment]
_uhhhhh_ well mesa is a hot and dry biome >_>

I'm gonna make it use the topblock instead _shrug_
