### ISSUE TITLE
Add a Preferred Mod ID to Aevitas Ore Perk Config

### ISSUE THREAD

**Issue by justastranger** [HellFirePvP/AstralSorcery#541]
I'm currently using a modpack that is configured to only have Thermal Foundation ores generated in the world, but as I walk around with the perk, the world gets peppered with ores from Forestry and Immersive Engineering. It would be nice if I could specify in the config that Thermal Expansion ores should be preferred over other varieties of ores, since it clogs up inventory space to mine these other forms of ore.

**Comment by Doomgull** [comment]
There's already a config file for what's allowed to generate, located under /config/astralsorcery.

**Comment by justastranger** [comment]
There's a config for which entries from the Ore Dictionary are allowed to generate, but no way to specify that you want a particular mod's version of those ores generated.

**Comment by HellFirePvP** [comment]
There is a astralsorcery subfolder in your config directory. You might want to look at that.

And in regards to adding a preferred ore, there are solutions to just write up CT scripts that remove all other ores from a specific oredict entry except the one you want and hide the others from JEI and the like. Then only have those ores generate with the correct mods as worldgen, and boom. it's like the other ores don't exist.

**Comment by Doomgull** [comment]
Collapsed into master suggestion thread.

**Comment by HellFirePvP** [comment]
Since i just stumbled across this yesterday actually: there is a config option in the general astralsorcery.cfg which allows you to blacklist certain mods (by adding their modid there) from being used for ore-picking from the oredict and stuff. iirc it's called smth like "oreGenBlacklist" ? You might wanna look into that.
