### ISSUE TITLE
Rock Crystal Disappearing  with Greater Ring of Magnetization 

### ISSUE THREAD

**Issue by bthrom** [HellFirePvP/AstralSorcery#543]
I go to throw a rock crystal in a pool of starlight when wearing the greater ring of Magnetization the rock crystal just vanishes nothing hits the ground nothing goes in the pool nothing back into my inventory tried to disable ring with Solegnolia and same things happen. I take the ring off and it works like it should into the pool no issue. There is no crash log but running most updated version 1.12.1-1.8.5

**Comment by Doomgull** [comment]
That's a baubles version issue with botania.

**Comment by bthrom** [comment]
Ok wasnt sure one what side so cross-posted it

**Comment by HellFirePvP** [comment]
supposedly a botania issue which is or will be fixed.
