### ISSUE TITLE
Enabling AstralSorcery lets my sun disappear.

### ISSUE THREAD

**Issue by dornenfeld** [HellFirePvP/AstralSorcery#544]
Issue as quoted above. Any excuse? :P
Minecraft Version:
-1.12.2
Forge Version:
-newest
AstralSorcery 1.8.4
Optifine + Sildur Shader (also tested on Chocapic13)

**Comment by Doomgull** [comment]
Yes, you're running a shader, which is stated to not work because AS has to run its own, so its conflicting.

Check the config file, there's a weakSkyRender option explicitly for that scenario.
