### ISSUE TITLE
[Netty Epoll Server IO #1/ERROR] [FML] on Containment chalice

### ISSUE THREAD

**Issue by ilFau** [HellFirePvP/AstralSorcery#547]
First of all... sorry for my English.

I have some trouble with containment chalice on server. When they interact with each other or lightwell the client crash.
I try to figure out why... and i discover that it happend when i connect to world throught BUNGEECORD.
Because in the same instace of server if i connect directly on his port, the client doesn't crash.

I try with a different version of Forge and Atral sourcery:
Forge 14.23.2.2611
Forge 14.23.2.2586
Forge 14.23.2.2575

Astral 1.8.5 and 1.8.4

this is the modlist of pack on server:

- AdFinders-1.12.1-2.1.1.0-build.0056.jar            
- gravestone-1.10.0.jar                       
- AppleSkin-mc1.12-1.0.9.jar                        
- ImmersiveEngineering-0.12-76-core.jar       
- natura-1.12-4.3.1.35.jar
- Aroma1997Core-1.12.2-2.0.0.0.b135.jar              
- ImmersiveEngineering-0.12-76.jar            
- refinedstorage-1.5.31.jar
- Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar  
- immersivepetroleum-1.12.2-1.1.6.jar         
- refinedstorageaddons-0.2.jar
- astralsorcery-1.12.2-1.8.4.jar                     
- immersivetech-1.12-1.3.4.jar                
- RoguelikeDungeons-1.12.2-1.8.0.jar
- base-1.12.2-3.5.0.jar                             
- InventoryTweaks-1.63.jar                    
- SimpleDimensions-MC1.12-1.3.1.jar
- BetterFps-1.4.8.jar                                
- IronBackpacks-1.12.2-3.0.2-3.jar            
- StorageDrawers-1.12.1-5.3.3.jar
- BiblioCraft[v2.4.3][MC1.12.0].jar                  
- ironchest-1.12.2-7.0.34.820.jar             
- TConstruct-1.12-2.8.1.49.jar
- Chameleon-1.12-4.1.3.jar                           
- jei_1.12.2-4.8.5.138.jar                    
- theoneprobe-1.12-1.4.19.jar
- ChestTransporter-1.12-2.8.7.jar                    
- jeibees-0.9.0.5-mc1.12.2.jar                
- TinkerToolLeveling-1.12-1.0.3.jar
- Clumps-3.0.0.jar                                   
- jeiintegration_1.12.2-1.5.1.36.jar          
- topaddons-1.12.2-1.2.1.jar
- CodeChickenLib-1.12.2-3.1.5.331-universal.jar      
- journeymap-1.12.2-5.5.2.jar                 
- torchmaster_1.12.2-1.6.1.53.jar
- ComputerCraft1.80pr1.jar                           
- JustEnoughResources-1.12.2-0.8.5.27.jar     
- Traverse-1.12.1-1.3.1.jar
- ElevatorMod-1.12.2-1.3.5.jar                       
- KleeSlabs_1.12-5.3.2.jar                    
- UniDict-1.12.2-2.0.jar
- EnderStorage-1.12.2-2.4.2.126-universal.jar        
- LootBags-1.12.2-2.5.3b.jar                  
- ViesCraft-1.12.2-5.6.1.jar
- FastLeafDecay-v14.jar                             
- Mantle-1.12-1.3.1.21.jar                    
- WanionLib-1.12.2-1.4.jar
- FoamFix-1.12.2-0.8.4-Anarchy.jar                  
- mcjtylib-1.12-2.6.2.jar                     
- Waystones_1.12.2-4.0.20.jar
- forestry_1.12.2-5.7.0.219.jar                      
- minecolonies-universal-1.12.2-0.8.6471.jar  
- worldedit-forge-mc1.12-6.1.8-dist.jar
- ForgeEndertech-1.12.1-4.3.0.0-build.0056.jar       
- MobGrindingUtils-0.3.4.jar                  
- xnet-1.12-1.6.7.jar
- FTBLib-4.2.5.jar                                   
- moreoverlays-1.13-mc1.12.1.jar
- FTBUtilities-4.2.4.jar                             
- Morpheus-1.12-3.3.2.jar

Log from server:
```
[18:05:16] [Server thread/INFO]: ilFau[/127.0.0.1:39891] logged in with entity id 12234 at (27692.61220500026, 96.0, 27518.20102013725)
[18:05:16] [Server thread/INFO]: ilFau joined the game
[18:05:17] [Server thread/INFO]: ilFau lost connection: Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connessione interrotta dal corrispondente
[18:05:17] [Server thread/INFO]: ilFau left the game
```

no crash report from client

I hope you find a fix for this problem, beacuse we like so much this mod, if you need other information i'll glad to help!

i forgot the bungeecord report:

> 18:05:16 [BUONO] [DONE Server <- Bungee][RECEIVED: HandshakeAck]
> 18:05:16 [INFORMAZIONI] §filFau §bchanged server to flavourland§b.
> 18:05:17 [GRAVE] [ilFau] <-> DownstreamBridge <-> [flavourland] - encountered exception
> java.lang.IllegalArgumentException: Unknown meta type 15
>         at net.md_5.bungee.entitymap.EntityMap.rewriteMetaVarInt(EntityMap.java:200)
>         at net.md_5.bungee.entitymap.EntityMap_1_12_1.rewriteClientbound(EntityMap_1_12_1.java:152)
>         at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:102)
>         at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>         at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>         at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>         at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
>         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
>         at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
>         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>         at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
>         at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
>         at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
>         at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
>         at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
>         at java.lang.Thread.run(Thread.java:748)
> 18:05:17 [INFORMAZIONI] [ilFau] <-> DownstreamBridge <-> [flavourland] has disconnected
> 18:05:17 [INFORMAZIONI] [ilFau] <-> DownstreamBridge <-> [lobby] has disconnected
> 18:05:17 [INFORMAZIONI] [ilFau] <-> ServerConnector [lobby] has connected
>

**Comment by Doomgull** [comment]
Use of Sponge isnt supported, but looks like it's a network stream issue, which there should be some improvements coming in the next release or two due to some other issues that have been popping up. So while this may not have a direct fix one of the other fixes may see improvements for this particular issue with sponge.

**Comment by ilFau** [comment]
but i'm not using sponge

**Comment by HellFirePvP** [comment]
You're using bungeecord for - i presume - a server network and thus modifying the packets as they get sent. Apparently some packet is running into issues being processed. As i have no clear way of ever tracking why and what goes wrong, i'm not tackling these issues.
On that note: Similiar as to the sponge-related server environments: Not supported.

**Comment by ilFau** [comment]
ok, I try to contact the bungeecord author.

thank you anyway!
I really appreciate your work, for one of the best mods ever!
I hope I can fix this issue soon, because the chalice it so awesome.

**Comment by ilFau** [comment]
I'm still investigating how to solve this problem.
The chalice, when interact with other entities (like lightwell or chalice), refers to an invalid meta type of vanilla minecraft metadata (meta type 15). Is this possible?
