### ISSUE TITLE
[feature request] Celelstial Gateway tweaks

### ISSUE THREAD

**Issue by Zygus42** [HellFirePvP/AstralSorcery#548]
(1) if the gate you want to go to is in line with any of the blocks making up the Gateway platform (including the corner pillars) you're standing on you can't see it.  Would be very useful if you could see the starfield through the gateway platform blocks.

(2) Hard to line up your feet with the middle block of the platform exactly.  I have worked around this with some fences, but is ugly.  Would be great if maybe you could target the other gateways in the starfield while within 1.5 or 2 blocks of the center.

(3) If there was an alternative non-free or limiting method(s) of using the gates that you could activate in the config.  It might cost buckets of liquid starshine, or the main piece of the gate might need to be attuned to the travel/movement constellation, so it would only work at the times that was in the sky.  Or even that the gateways only worked at night.  This would be more suitable for world builds where constant free teleporting was a game breaker.

**Comment by Doomgull** [comment]
Collapsed into master suggestion thread.
