### ISSUE TITLE
Rendering Issues

### ISSUE THREAD

**Issue by McGaughy** [HellFirePvP/AstralSorcery#55]
For MC version 1.10.2

I'm encountering an issue in which the sky is not rendering any of the stars. This does not appear to be a constant issue across all my maps using the exact same mod pack.
![2017-03-05_15 32 06](https://cloud.githubusercontent.com/assets/3643143/23592715/11ee5d30-01ba-11e7-86be-1c0cbd4a160a.png)

I have also encountered an issue where the lightwell appears to reflect certain surfaces:
![2017-03-05_15 47 34](https://cloud.githubusercontent.com/assets/3643143/23592825/4d1bedea-01bb-11e7-8968-530f31125cb5.png)
This one does appear to be fairly constant across my maps.

The mods I'm currently using are :
AppleSkin
astralsorcery-1.1.4-beta
AutoRegLib
Baubles
BloodMagic
Botania
Chameleon
CookingForBlockheads
CyclopsCore
EvilCraft
Guide-API
jei
journeymap
Pam's HarvestCraft
Psi
roots
StorageDrawers

This is an amazing mod, thanks for making it!

**Comment by HellFirePvP** [comment]
1st issue _might_ be adressed with the changes i've done in preparation of 1.1.5

2nd, uhm.. well.. do you have the option of dumping the texture atlas? Try https://github.com/mezz/TextureDump for that. DL links and descriptions what it does & how it works are on the project page there.

**Comment by McGaughy** [comment]
[texture_dump.zip](https://github.com/HellFirePvP/AstralSorcery/files/823977/texture_dump.zip)
Here are the results of the dump (please let me know if you would like it in a different format)
