### ISSUE TITLE
Custom Sky render and WeakSkyRender config isn't working

### ISSUE THREAD

**Issue by Darsenia** [HellFirePvP/AstralSorcery#550]
Hello.Every resoursepack with custom sky isn't working - only sun/moon changes,there are no sky textures and sky looks pretty bad.
I'm using the latest 1.10.2 Astral Sorcery 1.4.5 version.I tried to change the config file, eaclude 0 dimension from the supported list-nothing changes.When I'm trying to modify WeakSkyRender, the mod just generates new,clean file and saves modified as "errored" tagged config.I tried to put 0  there,other numbers just to be sure-nothing."True" argument doesn't work,but it would be strange,if it does.
Any chance to solve this?

**Comment by HellFirePvP** [comment]
As it says in its description. it's a comma-separated list of dimension id's. It does work if actually done correctly. Besides that, this is 1.10.2 and thus unsupported.
