### ISSUE TITLE
[feature request] Different rotation options for lenses

### ISSUE THREAD

**Issue by xy795** [HellFirePvP/AstralSorcery#551]
By now it is not possible to place a lens anywhere than on top of another block. If its not too complicated, it would be awesome if you could implement options to place them on the sides/bottom of a block so the lenses would not look like they are floating if there is no block below it.

**Comment by Doomgull** [comment]
Would require a re-write at present, but it's on the list of possible improvements down the line.

**Comment by Doomgull** [comment]
collaped into master suggestion thread.
