### ISSUE TITLE
[1.12.2] Luminous Crafting Table shows no output/not craftable

### ISSUE THREAD

**Issue by Paril** [HellFirePvP/AstralSorcery#553]
So, this is an odd thing I've been fighting all day. On the latest Modern Skyblock 2 pack, Astral Sorcery never shows an available output to the Luminous Crafting Table.

![](https://i.imgur.com/ILcDC6g.png)
![](https://i.imgur.com/6rEyEve.png)

I've watched some videos (direwolf20's showcase) on the mod, and in his video he had a similar issue for a little bit where the recipe output didn't show up, but his popped in randomly whereas mine is just stuck here. I've waited all day/night, smacked the thing with my resonating wand multiple times, but it just doesn't want to register the recipe as being valid. I tried other Marbles as well, but the Astral Sorcery one is obviously the one that the recipe wants me to use.

**Comment by Paril** [comment]
As a last resort, I crafted the Luminous Crafting Table myself (I was picking up where another player left off, so I never had the Exploration part of my book) and that seems to have unlocked the recipes for me. Might be nice to note that this unlocks recipes or something :)

**Comment by vinikum** [comment]
Had the same problem, issue was probably not progressing step-by-step through the questbook:
Did **not** check the box in the "Welcome to Astral Sorcery"-Quest **before** i crafted the Luminous crafting table, wich caused my progression not to register. Checked the box, claimed the reward, then crafted another one, then it worked :)
