### ISSUE TITLE
Poor Interactions With Dimensions That Have no Day/Night Cycle

### ISSUE THREAD

**Issue by notWaterGuy12** [HellFirePvP/AstralSorcery#554]
Within the configs there is an option to give other dimensions the Astral Sorcery sky. Only problem is that the mod regards dimensions with no day/night cycle as perpetually noon. Possibly making so that dimensions that have no day/night cycle just randomly cycle through constellation would be a helpful fix.

**Comment by Doomgull** [comment]
This has been repeatedly denied.
