### ISSUE TITLE
Custom Fluid Rarities crashes on world load

### ISSUE THREAD

**Issue by davqvist** [HellFirePvP/AstralSorcery#555]
Config: https://pastebin.com/Wp5DNFxj
Error Log: https://pastebin.com/05CiMETb

AS 1.8.5
Forge 2599
MC 1.12.2

**Comment by Doomgull** [comment]
Whqt mod is adding hydrogen and oxygen as liquids?

**Comment by davqvist** [comment]
I talked to Hellfire on Discord already. It is Advanced Rocketry. Hellfire changed the registration of the liquids to init. Maybe that will fix it.
