### ISSUE TITLE
Telescope issues

### ISSUE THREAD

**Issue by headwyvern** [HellFirePvP/AstralSorcery#556]
Sorry I don't know if youve had this issue before but my telescope stopped working.  i'm almost done researching all the constellations but for some reason on direwolf20's modpack through twitch on their server it stopped working.  all I get is a black screen at night with the telescope.  everything else works fine.  Ive even passed on the knowledge on to some of them and given them perks its fun!  But I'd like to continue stargazing, hopeful I didn't burn my eyes out or something and there is an actual fix here.  we tried resetting the time per a search that said time modifications (which were not made) might alter it.  manual reset didnt fix it.  we have a mining dimension teleporters and twilight forest all pretty active with some serious tech gadgets.  maybe there is some other issue.  Please I'd appreciate any help, although I know you have a life and are busy.  It's a wonderful toy you've created, I love it and want to continue exploring what it has to offer regardless.

**Comment by Doomgull** [comment]
Move the telescope away from whatever wall or whatever it's near.
