### ISSUE TITLE
Containment Chalice disappearing when block/liquid placed next to it 

### ISSUE THREAD

**Issue by fufu87** [HellFirePvP/AstralSorcery#558]
Forge version: 14.23.1.2601
Minecraft version: 1.12.2
Modpack : FTB presents Direwolf20 1.12 version 1.80
Mod version astralsorcery-1.12.2-1.8.5 

I lost 3 chalices when blocks/items are placed close  #to the chalice  
I made a chalice intended to help in the starlight infusion process; upon placing the lightwell close/next to the chalice, it disappeared . Same issue happened when accidentally pouring liquid next to it.  Third occurrence happened when my friend was trying to toggle the chalice to stop taking starlight and upon placing the lever, it disappeared.

**Comment by Doomgull** [comment]
So, they've a range of 16 blocks, would recommend not placing them adjacent to things while this is looked into.

**Comment by HellFirePvP** [comment]
This seems more like a mod interaction or some weirdness with claims/protection things. I can't reproduce this even in the pack in question.

**Comment by fufu87** [comment]
Nothing regarding this appear on my server's log.

I will to try reproduce it again on the server and record it or as @HellFirePvP mentioned.

**Comment by HellFirePvP** [comment]
Yea. That's the problem with moving tileentities without running them through proper code and just forcibly ripping them out of the world without further notice.

Closed.
