### ISSUE TITLE
Fortune+Scorching Heat double-stack

### ISSUE THREAD

**Issue by KITbutler** [HellFirePvP/AstralSorcery#559]
- DW20 MC 1.12.2 pack 1.8.0
- Astral Sorcery 1.8.5

When a tool is enchanted with both Fortune and Scorching Heat the effects not only stack (which is fine) but Fortune appears to be applied twice if the non-smelted drop is also affected by fortune. I cannot think of any vanilla cases at the moment but in the DW20 pack coal smelts into graphite and nether quartz into silicon for example. Interestingly lapis lazuli shows absolutely no difference in results whether Scorching Heat is used or not, I presume that enchantment only checks the _drop_ of the block for smelting?

**Comment by HellFirePvP** [comment]
Fortune should only be applied to the result of the block broken after being smelted not twice before AND after. will write a workaround for this, thanks for the report.
