### ISSUE TITLE
[Request] Mod integration

### ISSUE THREAD

**Issue by mankra** [HellFirePvP/AstralSorcery#56]
The [Chisel](https://minecraft.curseforge.com/projects/chisel) mod already provides marble which can be chiseled. It would be cool if Astral Sorcery could recognize the Chisel mod and use the marble of that mod instead of it's own, so the player don't has to mess with two marble variants when using both mods.

Another mod providing marble is [UBC](https://minecraft.curseforge.com/projects/undergroundbiomesconstructs), but there it's a stone type which is broken to marble cobblestone. Don't know wether integration is possible. I disabled UBC marble to give preference to Chisel marble.

**Comment by Saereth** [comment]
AS does support ore dictionary in the recipes, the issue I've found is that the oredicts for marble are all over the place. AS oredicts as blockMarble. Makes sense, quark is stoneMarble, which also kinda makes sense. Chisel literally has no oredict for their marble at all and not sure about UBC's oredict. There doesnt seem to be consensus in the modding community on which oredict to use. 

You can fix this with minetweaker howeve by adding all the mod marbles into a single oredict for recipes or just adding a shapeless recipe to convert between the types.

**Comment by mankra** [comment]
The [CraftTweaker](https://minecraft.curseforge.com/projects/crafttweaker) + shapeless recipe idea sounds good, I'll try that. Thank you. :-)

**Comment by WesCook** [comment]
Here's the CraftTweaker solution I went with for UBC compatibility.  It adds oredict for the recipes, and allows direct crafting for the multiblock structures.  Tooltips are added to help distinguish the two.

```
// Marble Oredict for most Astral Sorcery recipes
<ore:stoneMarble>.add(<undergroundbiomes:metamorphic_stone:2>);
<ore:blockMarble>.add(<undergroundbiomes:metamorphic_stone:2>);

// Marble Tooltips for clarity
<astralsorcery:BlockMarble:0>.addTooltip("Able to channel starlight");
<undergroundbiomes:metamorphic_stone:2>.addTooltip("Can be crafted into another type of marble");

// Direct Marble conversion for any edge cases
recipes.addShapeless(<astralsorcery:BlockMarble:0>, [<undergroundbiomes:metamorphic_stone:2>]);
```
