### ISSUE TITLE
Starlight power system failing on dimension change and relog

### ISSUE THREAD

**Issue by KITbutler** [HellFirePvP/AstralSorcery#560]
- Direwolf20 MC 1.12.2 pack 1.8.0 with manual additions and mod updates
- Forge 14.23.1.2601
- Astral Sorcery 1.8.5

I am not entirely sure whether this is just one issue or multiple separate ones. Lucerna, Horologium and Bootes rituals seem to stop working fairly consistently after entering a Compact Machine even once or upon exiting to the main menu and re-entering. All three are powered by an enhanced collector crystal and should be within range of a ChickenChunks chunkloader which also covers the compact machines usually triggering the failure.

A separate enhanced collector crystal powering green lenses also fails upon dimension change or relog but seemingly not all the time.

Yet another enhanced collector crystal outputs enough starlight to keep lightwells producing during the day, but once failed to provide meaningful power to my crafting altar. This one is particularly strange as it did output some power during the night, as if the multiblock were invalid rather than the crystal entirely nonfunctional. Only it wasn't and resumed working without any changes after a hard restart of the game. Such a behaviour would imply the Lucerna ritual should keep mobs at bay during the night if this were the only issue though.

**Comment by Doomgull** [comment]
#539
