### ISSUE TITLE
Suggestion- More!

### ISSUE THREAD

**Issue by CTH999** [HellFirePvP/AstralSorcery#562]
Suggestion 1- So, star-metal is magic-infused iron right?

So, maybe you could make it into tools that are stronger than iron but weaker than diamond, and armor that is more protective than diamond, but weaker. Faster than gold tools, attack on-par with diamond, highly enchant able, and strong! Sounds good to me!

Also, it's good for bulk changing! (That way you can change your 1000K iron to star-metal, and still have tools!)

Suggestion 2- Lucerna ritual should give night vision!

Suggestion 3- More consolations- (You have time, what about space and the concept of space-time) Also, rituals and more!

Suggestion 4- I don't know if this is against your mod or not, but It would be neat if you could attune yourself with Non-major constellations!

Suggestion 5- Rock and Celestial Tools and armors. Because why not!

Suggestion 6- Compatibility with more mods! Because that's always nice! (Especially compatibility with botania and similar mods)

However these are just suggestions!

**Comment by HellFirePvP** [comment]
1) repeditively denied over and over. no.

2) its effects are designed to be world-based not entity based.

3) "gimme more" is not a suggestion.

4) comes with the problem of trying to find 6 perks that are somewhat unique and are in line with each constellation's theme and concept. However, i'm unable to come up with 42 different and unique perks at this point and other things have priority. so... no.

5) same as 1)

6) I have enough work on my own mod before i care about specific interactions with other mods. Interactions exist, so for example you can "feed" a formation or conversion wand with botania's cobble or dirt wands and other small things. For the moment? Not really. got enough stuff i want to include into the mod itself before i want to work for the gain of other mods.

**Comment by CTH999** [comment]
Ok...

- [ ]

**Comment by HellFirePvP** [comment]
to reply:

1. It can be somewhat found in the suggestion masterlist. i may quote:

> -"Normal" bows/arrows/shields, but "starlight flavored".
-Metal/traditional armor. Mantles fill the armor role. There won't be any Starmetal armors.

this includes "hey, make <generic tool name> out of <generic metal name> pls it would be so cool"

2. i have design concepts in mind for each constellation, if that comes across well or not is not really the question, however the suggestion originally made doesn't fall into it.

3) Yes. The mod still gets added upon continuously so asking for more is like "keep doing what you're already doing" which is not a suggestion. And "pls more" is not a pinpoint suggestion, nor are any points made towards what exactly it is you want to have and how it should work for each respectively. This includes the total amount of features tied to it. So adding a constellation comes along with: non-duplicating theme, ritual, enchantments and potions fitting, mantle effect - and if it's a major constellation: perks and wand attunement. So there's more to it than "just add a new one"

6) i have plans for content for almost 2 years now. I've got plenty of things to do thank you.

**Comment by CTH999** [comment]
1. I used the search and couldn't find it. I'm sorry.

2. Okay, I was just giving ideas, not saying you have to, If you don't want to, pleas don't. To quote what I normally put in, (I forget _this time_ Is something along the lines of "This is just a suggestion. It's your mod, do what you want."

3. Still Ok, (With the constellation thing, I like space-time and relativity, hence the space-time one.

4. Fine, If you don't want to add it in, then pleas don't. Whenever a mod author adds something they don't want to, it turns out word.

5.

6. Ok, I like compatability, but If you have more content planned, please add that next! I like a constantly updated mod more!

7. Thank you, and I'm sorry if I sounded mean.
