### ISSUE TITLE
Bug(?) With GoG Skybox

### ISSUE THREAD

**Issue by DaggerTM** [HellFirePvP/AstralSorcery#563]
With GoG Skybox installed it makes the sky look different.... But upon installing AS it reverts to the original look. I know how the mods works that it uses the moon and stuff, but have you though of incorporating GoG Skybox to use the mod? If this bug can't be fixed then i'm fine with it.

### Forge:  1.12.2-14.23.2.2618

**Comment by Doomgull** [comment]
Check the "weakSkyRender" option in the configs. That's the limit of supportability that will be provided.
