### ISSUE TITLE
[Question] Default Recipe Source

### ISSUE THREAD

**Issue by ElvenChaos** [HellFirePvP/AstralSorcery#564]
Is there a spot in the source where I can view the default recipe allocations for the mod, namely for the starlight infuser? I've been digging around and can't quite find the recipes themselves, just the methods to make them. I'm attempting to extend the current recipes to include more inputs from other mods via CT, but I can only see inputs and outputs in JEI -- not other information like the chance to consume liquid starlight or the tick time for crafting.

**Comment by HellFirePvP** [comment]
https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/registry/RegistryRecipes.java#L137
