### ISSUE TITLE
Astral Sorcery ore room/shrine not working

### ISSUE THREAD

**Issue by BleesTFE** [HellFirePvP/AstralSorcery#565]
I've been looking for the shrines and finally found one, broke the stone and that's it. What a huge disappointment. Found two more, broke the stone, nothing else.
It should be noted that the shrines were completely new and that I'm playing on a server. It should also be noted that it used to work.
I am using the latest version for 1.12.2

**Comment by BleesTFE** [comment]
It should be noted that the shrines were completely new and that I'm playing on a server.

**Comment by Doomgull** [comment]
What'd you break it with, and were you nearby when doing so, or did you use a machine to do it?

**Comment by BleesTFE** [comment]
The first shrine, I used a builder from RFTools, the next i used regular pickaxes, iron and a third shrine i used a vanilla diamond pickaxes. I flew over to the shrines in spectator mode. But they were newly loaded.

**Comment by Doomgull** [comment]
What mods are in-use/modpack? Sponge? Did you claim the chunk? That's not normal behaviour.

**Comment by BleesTFE** [comment]
I don't have those kinds of mods. There is no claiming mods or anything.
List of mod:
10/02/2018  14:02        55,893,034 AmbientSounds+v2.2.2+mc1.12.2.jar
10/02/2018  13:51            32,317 AppleSkin-mc1.12-1.0.9.jar
10/02/2018  13:45        16,332,798 astralsorcery-1.12.2-1.8.5.jar
10/02/2018  13:55           506,667 base-1.12.2-3.6.1.jar
10/02/2018  13:56         1,962,731 bdlib-1.14.3.12-mc1.12.2.jar
10/02/2018  13:53            75,709 BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar
10/02/2018  13:47           155,196 BetterFps-1.4.8.jar
10/02/2018  14:04         5,148,425 BiblioCraft[v2.4.3][MC1.12.0].jar
10/02/2018  13:49         4,868,866 BiomesOPlenty-1.12.2-7.0.1.2313-universal.jar
10/02/2018  13:50           244,613 Bookshelf-1.12.2-2.3.523.jar
10/02/2018  13:45           472,782 BrandonsCore-1.12-2.3.7.140-universal.jar
10/02/2018  13:57         4,284,190 buildcraft-7.99.14.jar
10/02/2018  13:43            96,859 Chameleon-1.12-4.1.3.jar
10/02/2018  13:47           314,060 ChestTransporter-1.12.2-2.8.8.jar
10/02/2018  13:54           132,232 ChickenChunks-1.12.2-2.4.1.71-universal.jar
10/02/2018  14:46        17,346,525 Chisel-MC1.12-0.1.1.24.jar
10/02/2018  13:51           695,675 chiselsandbits-14.13.jar
10/02/2018  13:55            13,778 Clumps-3.0.0.jar
10/02/2018  13:45           650,693 CodeChickenLib-1.12.2-3.1.5.331-universal.jar
10/02/2018  13:57           764,904 CoFHCore-1.12.2-4.3.10.5-universal.jar
11/02/2018  20:05           399,333 CoFHWorld-1.12.2-1.1.1.12-universal.jar
10/02/2018  13:42           181,856 CTM-MC1.12-0.2.3.12.jar
10/02/2018  14:08           722,552 CustomMobSpawner-3.11.3.jar
10/02/2018  14:35            65,319 cxlibrary-1.12.1-1.6.1.jar
10/02/2018  13:49           448,983 DarkUtils-1.12.2-1.8.193.jar
10/02/2018  13:54           863,205 deepresonance-1.12-1.6.0.jar
10/02/2018  13:45         5,552,107 Draconic-Evolution-1.12-2.3.8.279-universal.jar
10/02/2018  14:18        22,443,630 DrZharks MoCreatures Mod-12.0.3 (1).jar
10/02/2018  13:54           845,761 ElecCore-1.12.2-1.8.434.jar
10/02/2018  13:51           221,404 EnderStorage-1.12.2-2.4.2.126-universal.jar
10/02/2018  13:59           244,973 endertanks-1.12.0-1.6.3.jar
10/02/2018  13:53         3,779,552 ExtraBitManipulation-1.12-3.2.1.jar
10/02/2018  14:02         9,099,190 ExtraPlanets-1.12.2-0.2.1.jar
10/02/2018  13:42         2,885,143 extrautils2-1.12-1.7.3.jar
21/02/2018  20:19                 0 filename.txt
10/02/2018  13:55           421,631 fluxnetworks-1.12.2-3.0.3.jar
10/02/2018  13:41         3,820,398 Galacticraft-Planets-1.12.2-4.0.1.132.jar
10/02/2018  13:39        10,302,770 GalacticraftCore-1.12.2-4.0.1.132.jar
10/02/2018  13:56         1,674,251 generators-0.9.20.12-mc1.12.2.jar
10/02/2018  13:50            76,022 gravestone-1.10.1.jar
10/02/2018  14:37           164,579 Guide-API-1.12-2.1.4-57.jar
10/02/2018  13:46           446,657 Hwyla-1.8.23-B38_1.12.jar
10/02/2018  13:57           550,812 iChunUtil-1.12.2-7.1.4.jar
10/02/2018  14:32             7,235 ImmersiveEngineering-0.12-76-core.jar
10/02/2018  13:42         5,937,804 ImmersiveEngineering-0.12-76.jar
10/02/2018  13:42           262,219 InventoryTweaks-1.64-dev.jar
10/02/2018  13:42         1,097,937 ironchest-1.12.2-7.0.34.820.jar
10/02/2018  13:50           545,366 jei_1.12.2-4.8.5.151.jar
10/02/2018  15:26         1,822,850 journeymap-1.12.2-5.5.2.jar
10/02/2018  13:50           215,140 JustEnoughResources-1.12.2-0.8.7.41.jar
10/02/2018  14:01           181,970 Level+Up!+2-1.1.15-1.12.jar
10/02/2018  14:00           773,275 lostcities-1.12-2.0.1.jar
10/02/2018  13:43           865,513 Mantle-1.12-1.3.1.21.jar
10/02/2018  13:47           366,615 mcjtylib-1.12-2.6.3.jar
10/02/2018  13:52           163,254 MCMultiPart-2.4.1.jar
11/02/2018  19:44        15,993,190 Mekanism-1.12.2-9.4.3.330.jar
11/02/2018  19:49           338,420 MekanismGenerators-1.12.2-9.4.3.330.jar
11/02/2018  19:49           161,111 MekanismTools-1.12.2-9.4.3.330.jar
10/02/2018  13:39            50,849 MicdoodleCore-1.12.2-4.0.1.132.jar
10/02/2018  13:59        27,940,497 minecolonies-universal-1.12.2-0.8.7494.jar
10/02/2018  14:35            80,014 MJRLegendsLib-1.12.2-1.0.6.jar
10/02/2018  13:48           870,528 MobGrindingUtils-0.3.4.jar
10/02/2018  15:13               162 mod_list.json
10/02/2018  14:01           121,463 MoreFurnaces-1.12.2-1.10.5.jar
10/02/2018  14:01            10,710 moreloottables-1.12.0-0.1.0.jar
10/02/2018  13:57         1,018,651 Morph-1.12.2-7.1.2.jar
10/02/2018  13:42            20,837 Morpheus-1.12-3.3.2.jar
10/02/2018  13:53         3,148,569 OpenBlocks-1.12.2-1.7.5.jar
10/02/2018  13:53         2,609,119 OpenModsLib-1.12.2-0.11.5.jar
10/02/2018  13:46         2,219,800 RandomThings-MC1.12.2-4.1.2.jar
10/02/2018  13:45            33,436 RedstoneFlux-1.12-2.0.1.2-universal.jar
10/02/2018  13:49         1,750,553 refinedstorage-1.5.31.jar
10/02/2018  14:00            53,918 refinedstorageaddons-0.2.jar
10/02/2018  13:56         1,206,299 Reliquary-1.12.2-1.3.4.733.jar
10/02/2018  13:51         2,878,703 rftools-1.12-7.27.jar
10/02/2018  13:49           573,359 rftoolsctrl-1.12-1.8.0.jar
10/02/2018  13:46         1,671,994 rftoolsdim-1.12-5.51.jar
10/02/2018  13:59           395,298 shetiphiancore-1.12.0-3.5.6.jar
10/02/2018  14:00            87,465 simplegenerators-1.12.2-2.0.7a.jar
10/02/2018  13:55         1,161,406 sonarcore-1.12.2-5.0.5.jar
10/02/2018  14:00           264,741 SoulShards-TOW-1.12-2.7.4-53.jar
10/02/2018  13:43           590,377 StorageDrawers-1.12.2-5.3.4.jar
10/02/2018  13:54           402,870 StorageDrawersExtras-1.12-3.1.0.jar
10/02/2018  14:01         1,520,219 taiga-1.12.2-1.3.0.jar
10/02/2018  13:43         3,747,716 TConstruct-1.12.2-2.9.0.55.jar
10/02/2018  13:55            30,925 Tesla-1.12.2-1.0.63.jar
11/02/2018  19:43           716,384 ThermalDynamics-1.12.2-2.3.10.4-universal.jar
11/02/2018  20:02         2,022,699 ThermalFoundation-1.12.2-2.3.10.6-universal.jar
10/02/2018  13:57           159,350 TinkersComplement-1.12.1-0.2.2b.jar
10/02/2018  13:48            91,796 TinkerToolLeveling-1.12-1.0.3.jar
10/02/2018  14:01           644,751 tinyprogressions-1.12-3.2.10+-+Beta.jar
10/02/2018  14:01         6,899,106 twilightforest-1.12.2-3.6.345-universal.jar
10/02/2018  14:00           275,550 valkyrielib-1.12.2-2.0.7a.jar
10/02/2018  13:59           128,682 VeinMiner-1.12-0.38.2.647+b31535a.jar
10/02/2018  13:45            31,462 WailaHarvestability-mc1.12-1.1.12.jar
10/02/2018  13:48            81,117 Wawla-1.12.2-2.5.251.jar
10/02/2018  13:59           526,210 woot-1.12.2-0.0.8.jar
11/02/2018  19:43           418,122 xnet-1.12-1.6.7.jar

**Comment by HellFirePvP** [comment]
In order:

- Check /config/astralsorcery/treasure_shrine.cfg and make sure at least a few different ores are listed there.
- Try in a new world.
- Try with just AS alone
- Try adding more and more mods and try reproduce with a new world in each until you can reproduce the behavior.

I here can't reproduce the issue nor has anyone else ever reported this.

**Comment by BleesTFE** [comment]
The thing is, there are ores listed, the shrines worked earlier, and now they don't. My server is up 24/7

**Comment by Doomgull** [comment]
Maybe try restarting the server, then.

**Comment by Doomgull** [comment]
@BleesTFE any update?

**Comment by randomlypickedname** [comment]
A player on my server has encountered the same bug on the Enigmatica 2: Expert modpack, ver. 1.26c, and I confirmed ores show up, but blocks don't drop in multiple treasure shrines. Tested with Tinker's, vanilla, BM, Mekanism's Atomic Disassembler, as well as a Cardboard Box (item disappeared, no box showed up, block changed from an ore to stone).

**Comment by Doomgull** [comment]
Can you narrow it down? Again, never reproduced and I know of several servers running that pack and version that didn't have this issue.

**Comment by randomlypickedname** [comment]
I'm working on narrowing it down, I'll let you know if I come up with anything.

**Comment by randomlypickedname** [comment]
So it seems Tool Progression is the cause of this bug, at least for me (I know I'm in creative, but you can see the difference):
Without: https://imgur.com/a/vDKf4fc 
With: https://imgur.com/a/MVeWDN2

**Comment by NillerMedDild** [comment]
I suspect the Treasure Ore/Stone is a special block that contains other blocks, so I need add a harvest level to the "container" - Is that the case, and if yes, by which name do I reference it?

**Comment by NillerMedDild** [comment]
Yeah you're probably right, I'll take it up with the Tool Progression dev.
