### ISSUE TITLE
Mod crashed

### ISSUE THREAD

**Issue by HarryTsui313** [HellFirePvP/AstralSorcery#57]
[crash-2017-03-08_16.15.29-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/827043/crash-2017-03-08_16.15.29-client.txt)

**Comment by HellFirePvP** [comment]
> Caused by: java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.

You added too much and exceeded the id limit. Remove mods/make your pack smaller
