### ISSUE TITLE
Telescope GUI Closes immediately on opening

### ISSUE THREAD

**Issue by ghosthog** [HellFirePvP/AstralSorcery#571]
As the title says, the telescope GUI shows for a split second and then closes. Sometimes if click a lot it might stay open for a full 2 seconds but that's it.

I saw there's issue #531 which talks about the gui not opening when clicking top half. It says this is being fixed for 1.9 but its not clear if that fix will fix this bug as well. A few people mention it in that ticket's comments and also on Discord (seems to be mainly multiplayer servers) but wasn't sure it was being looked into/addressed. Thanks. Love the mod!

**Comment by Doomgull** [comment]
It's the same.
