### ISSUE TITLE
Armara ritual pedestal pushes away villagers (AS 1.2.12-1.8.5)

### ISSUE THREAD

**Issue by ogradyjd** [HellFirePvP/AstralSorcery#573]
Unless the ritual is trying to protect me from the plague, lycanthropism, or having to interact with "peasents", I'm pretty sure the ritual pedestal with an Armara-tuned stone shouldn't be pushing villagers away.   I'm trying to protect a village I'm living next to from zombie attrition, and the modpack I'm using (All The Mods 3) doesn't have things like Magnum Torches or such.   When I started playing with AS, I fully expected the Armara to push away only hostile mobs.   Maybe the villagers secretly hate me and have been planing my demise behind my back?

If this is by design, then no worries, and maybe you can come up with a mechanic that will only affect mobs in some way?  If it isn't by design, then maybe it's time I teach those villagers a lesson.  ;)

**Comment by Doomgull** [comment]
By Design at present, though there has been discussions about possibly adding a whitelist to prevent certain mobs from being impacted. 

If you want to prevent hostile mob spawns, use the lucerna ritual instead
