### ISSUE TITLE
Crash after trying to play previous save, possible incompatibility?

### ISSUE THREAD

**Issue by TERRAkat** [HellFirePvP/AstralSorcery#574]
So I created a new world with astral sorcery and other mods, then trying to get back into the save world causes my game to crash. I'm wondering if there are a list of incompatible mods out there or not. I'm not certain but I think there's an incompatibility that's causing the crash.

*Note: I am playing v1.10.2 with the most up to date forge for that version

Mod list:
Actually additions
AppleSkin
AE2 (applied energistics)
bad wither no cookie
baubles
Bdlib
biomes o plenty
chicken chunks
chisel
chicken core/lib
CoFH core
Connected textures
Cooking for blockheads
Custom mob spawner
ender storage
energy converters
Extra Utilities
Extreme reactors
Fairy lights
forestry
gravestone
industrialcraft
inventory sorter
iron chests
journeymap
JEI
Light level overlay
mantle
Mo' Creatures
Morpheus
Mystical agriculture
Nature's compass
Netherportalfix
NEI
Obsidian plates
ore dictionary converter
pams harvestcraft
quick leaf decay
ranged pumps
simple teleporters
smoothwater
tesla
thaumcraft (and thaumcraft JEI)
Thermal Dynamics/expansion/foundation
tinkers construct
torchmaster
WIT
Zerocore

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.12.17-universal.jar)
  SmoothWaterCore (SmoothWater-0.1.3-1.10.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.320-universal.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  AppEngLoadingPlugin (appliedenergistics2-rv4-stable-1.jar)
  IC2core (industrialcraft-2-2.6.252-ex110.jar)
  CTMCorePlugin (CTM-MC1.10.2-0.2.3.26.jar)
  AstralCore (astralsorcery-1.4.5.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 2/25/18 2:23 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at drzhark.customspawner.handlers.SpawnTickHandler.worldTick(SpawnTickHandler.java:17)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_504_SpawnTickHandler_worldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:282)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:694)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 944605920 bytes (900 MB) / 2971664384 bytes (2834 MB) up to 5760352256 bytes (5493 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6180m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 106
	FML: MCP 9.32 Powered by Forge 12.18.3.2511 59 mods loaded, 59 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJAAAA	Forge{12.18.3.2511} [Minecraft Forge] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv4-stable-1} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{2.1.3.220} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.3.220-universal.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.320-universal.jar) 
	UCHIJAAAA	cofhcore{4.1.12} [CoFH Core] (CoFHCore-1.10.2-4.1.12.17-universal.jar) 
	UCHIJAAAA	actuallyadditions{1.10.2-r105} [Actually Additions] (ActuallyAdditions-1.10.2-r105.jar) 
	UCHIJAAAA	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UCHIJAAAA	appleskin{1.0.9} [AppleSkin] (AppleSkin-mc1.10.2-1.0.9.jar) 
	UCHIJAAAA	appliedenergistics2{rv4-stable-1} [Applied Energistics 2] (appliedenergistics2-rv4-stable-1.jar) 
	UCHIJAAAA	astralsorcery{1.4.5} [Astral Sorcery] (astralsorcery-1.4.5.jar) 
	UCHIJAAAA	badwithernocookie{1.10.2-0.0.1-5418dde} [Bad Wither No Cookie!] (BadWitherNoCookie-1.10.2-0.0.1-5418dde.jar) 
	UCHIJAAAA	Baubles{1.3.13} [Baubles] (Baubles-1.10.2-1.3.13.jar) 
	UCHIJAAAA	bdlib{1.12.4.25} [BD Lib] (bdlib-1.12.4.25-mc1.10.2.jar) 
	UCHIJAAAA	BiomesOPlenty{5.0.0.2236} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2236-universal.jar) 
	UCHIJAAAA	CodeChickenLib{2.5.9.320} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.320-universal.jar) 
	UCHIJAAAA	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.102-universal.jar) 
	UCHIJAAAA	ChickenChunks{2.2.0.52} [ChickenChunks] (ChickenChunks-1.10.2-2.2.0.52-universal.jar) 
	UCHIJAAAA	ctm{MC1.10.2-0.2.3.26} [CTM] (CTM-MC1.10.2-0.2.3.26.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.1.1.39} [Chisel] (Chisel-MC1.10.2-0.1.1.39.jar) 
	UCHIJAAAA	cookingforblockheads{4.2.45} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.45.jar) 
	UCHIJAAAA	customspawner{3.10.1} [DrZhark's CustomSpawner] (CustomMobSpawner 3.10.1.jar) 
	UCHIJAAAA	mocreatures{10.0.6} [DrZhark's Mo'Creatures Mod] (DrZhark's Mo'Creatures Mod-10.0.6.jar) 
	UCHIJAAAA	EnderStorage{2.2.1.106} [EnderStorage] (EnderStorage-1.10.2-2.2.1.106-universal.jar) 
	UCHIJAAAA	energyconverters{1.0.0.26} [Energy Converters] (energyconverters_1.10.2-1.0.0.26.jar) 
	UCHIJAAAA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.7.4.jar) 
	UCHIJAAAA	thermalfoundation{2.1.5} [Thermal Foundation] (ThermalFoundation-1.10.2-2.1.5.12-universal.jar) 
	UCHIJAAAA	thermalexpansion{5.1.10} [Thermal Expansion] (ThermalExpansion-1.10.2-5.1.10.28-universal.jar) 
	UCHIJAAAA	zerocore{1.10.2-0.1.1.1} [Zero CORE] (zerocore-1.10.2-0.1.1.1.jar) 
	UCHIJAAAA	bigreactors{1.10.2-0.4.5.46} [Extreme Reactors] (ExtremeReactors-1.10.2-0.4.5.46.jar) 
	UCHIJAAAA	fairylights{2.1.3} [Fairy Lights] (fairylights-2.1.3-1.10.2.jar) 
	UCHIJAAAA	FastLeaveDecay{1.2.3} [Fast Leave Decay] (FastLeaveDecay-MC1.10.2-1.2.3.jar) 
	UCHIJAAAA	IC2{2.6.252-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.252-ex110.jar) 
	UCHIJAAAA	forestry{5.2.17.388} [Forestry] (forestry_1.10.2-5.2.17.388.jar) 
	UCHIJAAAA	gravestone{1.5.13} [Gravestone Mod] (gravestone-1.5.13.jar) 
	UCHIJAAAA	inventorysorter{0.11.0+47} [Simple Inventory sorting] (inventorysorter-1.10.2-0.11.0+47.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.15.804} [Iron Chest] (ironchest-1.10.2-7.0.15.804.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.5.2} [JourneyMap] (journeymap-1.10.2-5.5.2.jar) 
	UCHIJAAAA	llor{1.1.1-mc[1.9-1.11]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.1-mc[1.9-1.11].jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCHIJAAAA	Morpheus{1.10.2-3.1.13} [Morpheus] (Morpheus-1.10.2-3.1.13.jar) 
	UCHIJAAAA	mysticalagriculture{1.5.10} [Mystical Agriculture] (mysticalagriculture-1.10.2-1.5.10.jar) 
	UCHIJAAAA	naturescompass{1.3.1} [Nature's Compass] (NaturesCompass-1.10.2-1.3.1.jar) 
	UCHIJAAAA	netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.10.2-3.3.7.jar) 
	UCHIJAAAA	ObsidianPlates{1.1.1} [Obsidian Plates] (ObsidianPlates-1.1.1_1.9.4.jar) 
	UCHIJAAAA	fodc{1.9.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.9.1.jar) 
	UCHIJAAAA	harvestcraft{1.10.2j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.10.2j.jar) 
	UCHIJAAAA	rangedpumps{0.3} [Ranged Pumps] (rangedpumps-0.3.jar) 
	UCHIJAAAA	smoothwater{0.1.3-1.10} [SmoothWater] (SmoothWater-0.1.3-1.10.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.6.5.10} [Tinkers' Construct] (TConstruct-1.10.2-2.6.5.jar) 
	UCHIJAAAA	lteleporters{1.1.3} [Lemon's Simple Teleporters] (teleporters-1.1.3.jar) 
	UCHIJAAAA	tesla{1.2.1.49} [TESLA] (Tesla-1.10.2-1.2.1.49.jar) 
	UCHIJAAAA	thaumcraft{6.0.BETA6} [Thaumcraft] (Thaumcraft-1.10.2-6.0.BETA6.jar) 
	UCHIJAAAA	ThaumicJEI{1.1.1} [ThaumicJEI] (ThaumicJEI-1.1.1.jar) 
	UCHIJAAAA	thermaldynamics{2.0.11} [Thermal Dynamics] (ThermalDynamics-1.10.2-2.0.11.19-universal.jar) 
	UCHIJAAAA	torchmaster{1.4.1.34} [TorchMaster] (torchmaster_1.10.2-1.4.1.34.jar) 
	UCHIJAAAA	WIT{1.0.23} [WIT] (WIT-1.9.4-1.0.23-44.jar) 
	Loaded coremods (and transformers): 
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.12.17-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
SmoothWaterCore (SmoothWater-0.1.3-1.10.jar)
  pl.asie.smoothwater.SmoothWaterTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.320-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  codechicken.nei.asm.NEITransformer
AppEngLoadingPlugin (appliedenergistics2-rv4-stable-1.jar)
  appeng.coremod.transformer.IntegrationTransformer
IC2core (industrialcraft-2-2.6.252-ex110.jar)
  
CTMCorePlugin (CTM-MC1.10.2-0.2.3.26.jar)
  team.chisel.ctm.client.asm.CTMTransformer
AstralCore (astralsorcery-1.4.5.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: stable rv4-stable-1 for Forge 12.18.3.2185
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	NotEnoughItems Invalid Fingerprint Reports: 
	List of loaded APIs: 
		* actuallyadditionsapi (29) from ActuallyAdditions-1.10.2-r105.jar
		* appliedenergistics2|API (rv4) from appliedenergistics2-rv4-stable-1.jar
		* Baubles|API (1.3.1.3) from Baubles-1.10.2-1.3.13.jar
		* bigreactors|API (4.0.1) from ExtremeReactors-1.10.2-0.4.5.46.jar
		* Chisel-API (0.0.1) from Chisel-MC1.10.2-0.1.1.39.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.10.2-0.1.1.39.jar
		* CoFHAPI (1.8.9R1.2.0B1) from rangedpumps-0.3.jar
		* cofhapi (1.5.0) from ActuallyAdditions-1.10.2-r105.jar
		* cofhapi|block (1.7.0) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhapi|core (1.7.0) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from energyconverters_1.10.2-1.0.0.26.jar
		* cofhapi|energy (1.7.0) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhapi|item (1.6.0) from zerocore-1.10.2-0.1.1.1.jar
		* cofhapi|tileentity (1.6.0) from zerocore-1.10.2-0.1.1.1.jar
		* cofhapi|util (1.7.0) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhlib (1.7.6) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhlib|audio (1.7.6) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhlib|gui (1.7.6) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhlib|gui|container (1.7.6) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhlib|gui|element (1.7.6) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhlib|gui|element|listbox (1.7.6) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhlib|gui|slot (1.7.6) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhlib|inventory (1.7.6) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhlib|util (1.7.6) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhlib|util|helpers (1.7.6) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhlib|world (1.7.6) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* cofhlib|world|feature (1.7.6) from CoFHCore-1.10.2-4.1.12.17-universal.jar
		* ComputerCraft|API (1.80pr0) from zerocore-1.10.2-0.1.1.1.jar
		* ComputerCraft|API|FileSystem (1.80pr0) from zerocore-1.10.2-0.1.1.1.jar
		* ComputerCraft|API|Lua (1.80pr0) from zerocore-1.10.2-0.1.1.1.jar
		* ComputerCraft|API|Media (1.80pr0) from zerocore-1.10.2-0.1.1.1.jar
		* ComputerCraft|API|Peripheral (1.80pr0) from zerocore-1.10.2-0.1.1.1.jar
		* ComputerCraft|API|Permissions (1.80pr0) from zerocore-1.10.2-0.1.1.1.jar
		* ComputerCraft|API|Redstone (1.80pr0) from zerocore-1.10.2-0.1.1.1.jar
		* ComputerCraft|API|Turtle (1.80pr0) from zerocore-1.10.2-0.1.1.1.jar
		* ctm-api (0.1.0) from CTM-MC1.10.2-0.2.3.26.jar
		* ctm-api-models (0.1.0) from CTM-MC1.10.2-0.2.3.26.jar
		* ctm-api-textures (0.1.0) from CTM-MC1.10.2-0.2.3.26.jar
		* ctm-api-utils (0.1.0) from CTM-MC1.10.2-0.2.3.26.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.10.2-5.2.17.388.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.10.2-5.2.17.388.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.10.2-5.2.17.388.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.10.2-5.2.17.388.jar
		* ForestryAPI|core (5.1.0) from forestry_1.10.2-5.2.17.388.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.10.2-5.2.17.388.jar
		* ForestryAPI|food (1.1.0) from forestry_1.10.2-5.2.17.388.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.10.2-5.2.17.388.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.10.2-5.2.17.388.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.10.2-5.2.17.388.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.10.2-5.2.17.388.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.10.2-5.2.17.388.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.10.2-5.2.17.388.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.10.2-5.2.17.388.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.10.2-5.2.17.388.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.10.2-5.2.17.388.jar
		* ForestryAPI|world (2.1.0) from forestry_1.10.2-5.2.17.388.jar
		* journeymap|client-api (1.4) from journeymap-1.10.2-5.5.2.jar
		* journeymap|client-api-display (1.4) from journeymap-1.10.2-5.5.2.jar
		* journeymap|client-api-event (1.4) from journeymap-1.10.2-5.5.2.jar
		* journeymap|client-api-model (1.4) from journeymap-1.10.2-5.5.2.jar
		* journeymap|client-api-util (1.4) from journeymap-1.10.2-5.5.2.jar
		* JustEnoughItemsAPI (4.10.1) from jei_1.10.2-3.14.7.420.jar
		* Thaumcraft|API (6.0.2) from Thaumcraft-1.10.2-6.0.BETA6.jar
		* WIT-API (1) from WIT-1.9.4-1.0.23-44.jar
		* zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.10.2-0.1.1.1.jar
		* zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.10.2-0.1.1.1.jar
		* zerocore|API|multiblock|tier (1.10.2-0.0.2) from zerocore-1.10.2-0.1.1.1.jar
		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.10.2-0.1.1.1.jar
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	ChickenChunks Invalid Fingerprint Reports: 
	EnderStorage Invalid Fingerprint Reports: 
	AE2 Integration: IC2:ON, RF:ON, RFItem:ON, Waila:OFF, JEI:ON, THE_ONE_PROBE:OFF
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Doomgull** [comment]
That crashlog points to mocreatures (drzhark reference at the top of the null pointer exception).

AS isn't even in the stack.
