### ISSUE TITLE
Cannot set property PropertyBool{name=active, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=astralsorcery:blockmachine, properties=[machine]}

### ISSUE THREAD

**Issue by jusjudge** [HellFirePvP/AstralSorcery#576]
When I launch up the client, it loads properly and gets to the in-game screen where I can choose single player, multiplayer and so forth. When I try to go into my single player world, I get this [error](https://hastebin.com/kipohigoxi.erl).

**Comment by Doomgull** [comment]
Looks like an issue with a grindstone or telescope at those coordinates. Curious why soul stones is attempting to interact with it, though, since that looks like the crash source.

Try deleting the block listed at those coordinates.

**Comment by jusjudge** [comment]
I probably wasn't so clear but I can't get into the world. It crashes after it says loading world so I'm not exactly sure how I could delete the block. Also, this is probably another bug on its own but the grindstones texture stutters sometimes or causes other blocks to stutter. For example, I have one near an iron door but there are marble blocks in between the two, yet when I place a crystal on the grindstone, the door becomes lighter.

**Comment by Doomgull** [comment]
MCedit.

**Comment by jusjudge** [comment]
I am currently trying to delete it but I either don't know how to or I am doing it correctly (according to the edit tab, SHIFT+DEL is used to delete blocks. I even tried to use DEL on its own. For some reason, MCEdit shows all the blocks in pink with a question mark as well.
https://imgur.com/a/oTtG3

**Comment by Doomgull** [comment]
Might need to check with the MCedit people, then, unsure.

**Comment by Doomgull** [comment]
Crash log from ticket #582, added here for reference: https://pastebin.com/Hk7J4z7R

**Comment by Doomgull** [comment]
https://github.com/TehNut/Soul-Shards-The-Old-Ways/issues/58

**Comment by Rixxaw** [comment]
Okay its definitely the Grinder causing it in my Issue.  I have had it happen repeatedly.  If I leave a Grinder on the ground and close the game it won't re-load.  I have to break the grinder put it into my inventory before i close out.

As for it being Foamfix.  I've already tried disabling Foamfix and its still occurs.  Only solution is breaking the grinder using MCEdit for me.

**Comment by Doomgull** [comment]
Grinder and telescope are same block.

Also, please read the linked soul shards ticket, and downgrade version as mentioned there. Not a foamfix issue.

**Comment by Rixxaw** [comment]
Can confirm downgraded SS TOW allows the world to load.

**Comment by jusjudge** [comment]
I can confirm as well that downgrading Soul Shards allowed my world to load properly.
