### ISSUE TITLE
Lens Recipe Crashing Simple Life 2

### ISSUE THREAD

**Issue by Newman2393** [HellFirePvP/AstralSorcery#578]
My wife is currently playing The Simple Life 2, and is trying to craft a Lens from Astral Sorcery. As soon as she puts in all the items she needs the game crashes. This also prevents her from reloading the world, but has no problem opening other worlds. We were able to temporarily workaround the issue by taking it into mcedit, and removing the altar. That allows her to load the world again, and do other things, but wondering if there is a permanent fix so she can craft it, and continue on.

Pastebin of crash report: https://pastebin.com/TEH1T9ar
Let me know if any additional information is needed to figure this out. Thank you.

**Comment by Doomgull** [comment]
Known issue, delete any crystals the pack hands out that dont have stats (purity, size, cutting) when you hover over them with shift held, and replace them with crystals from the creative menu instead.

Pack author messed up and provided crystals as quest rewards and recipes that are broken by missing important nbt data to set their parameters.
