### ISSUE TITLE
ChiselsAndBits conflict

### ISSUE THREAD

**Issue by ggblbl** [HellFirePvP/AstralSorcery#579]
In my serverlog it says "[chiselsandbits]: Unable to determine blocks eligibility for chiseling" for some of the blocks in the mod.
I read up on the error (https://github.com/AlgorithmX2/Chisels-and-Bits/issues/49) and it seems it can't be fixed by @AlgorithmX2.
These are the blocks:
hellfirepvp.astralsorcery.common.block.network.BlockAttunementAltar attempted to load net/minecraft/client/particle/ParticleManager

**Comment by Doomgull** [comment]
Is this preventing server start? Or just that you can't chisel the attunement altar?

**Comment by ggblbl** [comment]
I think ChiselsAndBits parses every block in the game to see if it can be used for chiselling, but wth some blocks it throws an exception.
Those exceptions log about 20 times and thus drastically slow down startup times to the point where it sometimes can't startup, because the ping took too long (or something like that, anyway).

**Comment by Doomgull** [comment]
Is there no blacklist that can be set to prevent it scanning those blocks?

**Comment by ggblbl** [comment]
I tried looking for one, but it turns out it doesn't exist.
