### ISSUE TITLE
While opening the guide book bug with fonts 

### ISSUE THREAD

**Issue by PaulWeider** [HellFirePvP/AstralSorcery#580]
When I open the guide book in game my font transforms to "squares"!! 
<img src="https://i.imgur.com/yTQ9gX8.png">
<img src="https://i.imgur.com/N4Sq6B4.png">
I reinstalled the mod and tried to create another world for testing it! THE same Result!
Please help!

**Comment by Doomgull** [comment]
Some other mod is messing with things. That's not AS.

Versions of as, mc, forge, pack/mods. Might see something obvious.

**Comment by PaulWeider** [comment]
Thanks! I've worked with it and noticed it's a bug with Optifine interaction!

**Comment by Doomgull** [comment]
Disabling Fast Render in optifine may resolve.
