### ISSUE TITLE
Unable to use the telescope

### ISSUE THREAD

**Issue by Mistercl0ud** [HellFirePvP/AstralSorcery#584]
Hello,
I'm using your mod with the modpack FTB Revelation on 1.12.2. 
I'm having an issue using the telescope :
Each time I'm trying to use it the square map briefly appears and closes.I did try differents places in the world but I'm still experiencing the same problem. 
The hand telescope doesn't have the same issue and the GUI window appears normally.

**Comment by Doomgull** [comment]
#531
