### ISSUE TITLE
Constellations disappearing after I reload a world

### ISSUE THREAD

**Issue by Ormega** [HellFirePvP/AstralSorcery#585]
I created a world and had started on Astral Sorcery, and had all the constellations learned in about 5 hours. I saved and quit the world, but when I came back, the constellations weren't visible. I checked my tome and it said I had learned those constellations, despite them not showing up.
I made a new world to test this out, and once I restarted the world, the constellations disappeared.
Versions:
Astral Sorcery: 1.8.5
Minecraft: 1.12.2
Forge: 14.23.2.2618
Please let me know if you need more information do diagnose the problem or perscribe a solution, I'll try to reply as soon as possible.

**Comment by Doomgull** [comment]
Have you tried logging back into that same world after restarting MC itself, not just saving and quitting the world?

**Comment by Ormega** [comment]
Just did, the constellations are still gone. Could it be a mod conflict? I have about 50 mods installed.
Would a list of the mods help?

**Comment by Doomgull** [comment]
Might help see if there's anything that stands out.

What about shaders or optifine?

**Comment by Ormega** [comment]
Yes, I have optifine. Does the twinkling stars effect it adds affect the constellations from AS?
I turned the sky effects off, and now I can see the major constellations (Discidia, Armara, etc.) but not the minor ones.

**Comment by Ormega** [comment]
Heck, i'm a fool. Just realized that the clouds from my shader pack were covering up the minor constellations. That was likely the root of the problem. Thanks for your time, Doomgull.
