### ISSUE TITLE
Iron won't turn into StarMetal

### ISSUE THREAD

**Issue by PessimisticBastard** [HellFirePvP/AstralSorcery#587]
Forge Version: 14.23.2.2624
Astral Sorcery Version: 1.12.2-1.8.5 

https://imgur.com/a/eLj0K

The collector crystal has an open view of the sky, and yet will not turn iron into starmetal.  I've even tried going to blocks with high starlight concentrations, cheating in the best crystal and the best lens. However, no particles even appear on the iron ore block. I've waited for half an hour, and nothing.

**Comment by Doomgull** [comment]
#535

Welcome to weird SSP bugs. Restart MC itself.
