### ISSUE TITLE
Can't craft resonating wand (table is crystal linked).

### ISSUE THREAD

**Issue by bonnedav** [HellFirePvP/AstralSorcery#588]
I went to a shrine, and placed down a table and light shown on it. But when I try to craft a resonating wand it does not work. 
![2018-03-05_13 42 08](https://user-images.githubusercontent.com/14209707/36998707-18df8bc4-207b-11e8-8768-1a81814751d9.png)

**Comment by Doomgull** [comment]
Assuming you're using the correct mod's marble, and you have no mods editing crafting tables, try exiting MC and relaunching. Could be same issue as #535, if that solves it.

**Comment by bonnedav** [comment]
Restarting MC worked.
