### ISSUE TITLE
Astral Sorcery progress resetting

### ISSUE THREAD

**Issue by bl4ckscor3** [HellFirePvP/AstralSorcery#589]
I'm on a private server with the Direwolf20 1.12.2 pack (1.9.0) installed and my AS progress resets every time I rejoin the server. We only have updated Portal Gun to 7.0.2, else the pack is the default one.
Please let me know if you need further information.

**Comment by Doomgull** [comment]
Multicraft, Bungeecord, Sponge, anything that would modify your player UUID on the server host?

Otherwise, need to take a look at the <uuid>.astral files in the world save to see if the directory is write-protected.

**Comment by bl4ckscor3** [comment]
Sorry to have bothered you, it was indeed a permissions issue. The server owner fixed it and everything is fine now.
