### ISSUE TITLE
[bug] Can't craft item/block contain "Glass lens" 

### ISSUE THREAD

**Issue by titantwoshot** [HellFirePvP/AstralSorcery#59]
It like the title, can't craft anything have Glass Lens in there
http://imgur.com/a/sH5iC
The pack i'm playing is All The Mods v2.5b

**Comment by BloodWorkXGaming** [comment]
Mod-Version: 1.1.5 - beta
Forge 12.18.3.2254

**Comment by Saereth** [comment]
The crafting table glowy bar at the bottom it showing it dosn't have enough starlight to craft. Once you have the items and the right amount of starlight then the item to craft will show up and you can make it.
