### ISSUE TITLE
Mineralis ritual not operating?

### ISSUE THREAD

**Issue by YogsMcree** [HellFirePvP/AstralSorcery#590]
So I have a mineralis ritual, all my lenses set up, mineralis collection crystal, and a ritual stone with reflectors set up and two ritual anchors, one in the center of that lovely giant block of stone. No ores are being made, they were working earlier, but have since stopped. What gives?
https://gyazo.com/3b84853d35d389acc98db9640e711d5a

**Comment by YogsMcree** [comment]
Upon further inspection into the GIT issues, i entered my compact machine several times. Is this the same as #539

**Comment by Doomgull** [comment]
Likely
