### ISSUE TITLE
Crashed when I broke the Telescope after accidentally picking it up with mod "Carry On"

### ISSUE THREAD

**Issue by greenking13** [HellFirePvP/AstralSorcery#591]
https://gist.github.com/greenking13/d8a235347915202558f89cf89b96d727

Yeah, I accidentally picked up the telescope and placed it back down and attempted to break it.

**Comment by Doomgull** [comment]
Yeah, don't do that.

**Comment by Doomgull** [comment]
In general, picking up a tile entity and moving it is not a good idea, unless the mod intends it to be picked up and moved.
