### ISSUE TITLE
Telescope closes instantly when opened (Non-Sponge)

### ISSUE THREAD

**Issue by TechDweebGaming** [HellFirePvP/AstralSorcery#593]
When using the telescope, the gui instantly closes. The handheld telescope seems to work. I have tested both on a sponge server and on a non-sponge server running the exact same modpack, and the issue has happened on two separate modpacks.

**Comment by Doomgull** [comment]
#531

Please search issues next time. There's no reason for there to be half a dozen duplicate entries for a fairly recent ticket, especially when the last duplicate was closed half an hour ago.

**Comment by TechDweebGaming** [comment]
The last duplicate was with sponge and you closed it blaming it on sponge, which is why I opened this...

**Comment by TechDweebGaming** [comment]
Also, this has nothing to do with the "halves" of the telescope. It's not a duplicate. No matter where you click, the gui instantly closes.

**Comment by Doomgull** [comment]
It's part of the same issue, had you read the ticket. Also the last closure was not blamed on Sponge it was pointed to that ticket. I simply mentioned that sponge is not supported.
