### ISSUE TITLE
Game crash with BlockMachine error in Forever Straded Lost Souls modpack

### ISSUE THREAD

**Issue by Eskordok** [HellFirePvP/AstralSorcery#595]
After recording an episode of Astral Sorcery and logging off. I can't log back in.
The error mension something about:
Block type: ID #3280 (tile.blockmachine // hellfirepvp.astralsorcery.common.block.BlockMachine)

Full log attached.

Any idea what block is that and what am I doing? I can link the youtube episode tomorrow if necessary.
But on the recording everything went well.
[crash-2018-03-11_06.22.27-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/1800212/crash-2018-03-11_06.22.27-server.txt)

btw Thanks for the help HellFirePVP.   What an amazing mod it is. :)

**Comment by Doomgull** [comment]
Same crash as seen in #576, use MCedit to delete the block, or yank soul shards, launch, and re-add it.

Supposedly downgrading Soul Shards versions fixes it? There's an issue open on their git I'm linking to ticket 576 for it.

**Comment by Eskordok** [comment]
What block I need to delete?

**Comment by Eskordok** [comment]
Downgrading soul shard to previews version did it. Not sure why. so thanks a lot.
Still would like to know what seems to be the problem and what block was causing the issue.

**Comment by Doomgull** [comment]
TehNut committed some code to fix it 9 hours ago (as of this comment) under Soul Shard's ticket 58.
