### ISSUE TITLE
Marble Slab recipe missing from JEI

### ISSUE THREAD

**Issue by armuell** [HellFirePvP/AstralSorcery#597]
You can currently craft marble slabs by placing 3 marble brick in a vanilla crafting table like any other slab but the recipe does not show up in jei.

Also I find it weird that you need a luminous crafting table and regular marble to make marble stairs but a vanilla crafting table and marble brick to make slabs. Seems inconsistent to me.

**Comment by Doomgull** [comment]
AS has no slab recipe, its why the slabs behave oddly, they are creative only.

Some other mod has added those recipes.
