### ISSUE TITLE
Imbued Blocks become transparent

### ISSUE THREAD

**Issue by TLomon** [HellFirePvP/AstralSorcery#598]
Made a base where all visible blocks are imbued with starlight (Illumination Wand). Upon world load after taking a break, and during smeltery work via Tinkers' Construct, the blocks all become transparent. This is impacting all players on server. 

Work around: Smelt an item, and watch it cool, gives a flash of transparency then clears the issue. Very odd interaction. 

Using vanilla resource packs. Let me know if you need any additional information.

**Comment by Doomgull** [comment]
Modlist/packlist.

Sponge? Optifine?

Are you near a celestial gateway?

**Comment by TLomon** [comment]
Custom pack. List is:

ActuallyAdditions-1.12.2-r130.jar
ae2stuff-0.7.0.4-mc1.12.2.jar
AkashicTome-1.2-10.jar
ancientwarfare-1.12.2-2.4.37.jar
angelRingToBauble-1.12-0.3.1.50+d4e654e.jar
AppleSkin-mc1.12-1.0.9.jar
appliedenergistics2-rv5-stable-8.jar
Aroma1997Core-1.12.2-2.0.0.0.b129.jar
Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar
astralsorcery-1.12.2-1.8.5.jar
AutoRegLib-1.3-15.jar
badwithernocookiereloaded-1.12.2-2.12.jar
Baubles-1.12-1.5.2.jar
bdlib-1.14.3.10-mc1.12.2.jar
BetterAdvancements-1.12.2-0.0.5.17.jar
BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar
biomediversity-1.0.5.jar
BiomesOPlenty-1.12.2-7.0.1.2312-universal.jar
blockcraftery-0.1.3.jar
Bookshelf-1.12.2-2.3.527.jar
Botania+r1.10-353.jar
BrandonsCore-1.12-2.4.0.152-universal.jar
Chameleon-1.12-4.1.3.jar
Chisel-MC1.12.2-0.2.0.31.jar
chiselsandbits-14.14.jar
CodeChickenLib-1.12.2-3.1.5.331-universal.jar
CoFHCore-1.12.2-4.3.10.5-universal.jar
CoFHWorld-1.12.2-1.1.0.11-universal.jar
CommonCapabilities-1.12-1.4.0.jar
compactmachines3-1.12.2-3.0.3-b169.jar
Controlling-3.0.4.jar
CookingForBlockheads_1.12.1-6.3.17.jar
CraftTweaker2-1.12-4.0.10.jar
CTM-MC1.12-0.2.3.12.jar
Cyclic-1.12.2-1.11.1.jar
CyclopsCore-1.12.2-0.11.4.jar
DankNull-1.12-1.4.33.jar
DarkUtils-1.12.2-1.8.194.jar
deepresonance-1.12-1.6.0.jar
DefaultOptions_1.12.1-9.2.4.jar
diethopper-1.1.jar
Draconic-Evolution-1.12-2.3.10.284-universal.jar
DummyCoreUnofficial-2.4.112.1.jar.moo
ElecCore-1.12.2-1.8.434.jar
ElevatorMod-1.12.2-1.3.5.jar
elulib-0.1.10.jar
endertanks-1.12.0-1.6.4.jar
environmentaltech-1.12.2-2.0.7b.jar
EssentialCraftUnofficial-4.8.112.4.jar.moo
Exchangers-1.12.2-2.6.2.jar
ExtraCells-1.12.2-2.5.9a45.jar
extrautils2-1.12-1.7.4.jar
ExtremeReactors-1.12.2-0.4.5.45.jar
fairylights-2.1.2-1.12.x.jar
flatcoloredblocks-mc1.12-6.6.jar
fluxnetworks-1.12.2-3.0.3.jar
FoamFix-1.12.2-0.9.2-Anarchy.jar
forestry_1.12.2-5.8.0.250.jar
Forgelin-1.6.0.jar
FTBLib-4.2.5.jar
FTBUtilities-4.2.4.jar
funky-locomotion-1.12.2-1.1.0.jar
gendustry-1.6.5.6-mc1.12.2.jar
generators-0.9.20.9-mc1.12.2.jar
gravestone-1.10.0.jar
Guide-API-1.12-2.1.4-57.jar
IGW-Mod-1.12.2-1.4.3-14-universal.jar
ImmersiveEngineering-0.12-78-core.jar
ImmersiveEngineering-0.12-78.jar
immersivepetroleum-1.12.2-1.1.5.jar
ImmersiveRailroading-0.5.1_1.12.jar
industrialforegoing-1.12.2-1.6.5-112.jar
IndustrialWires-1.6-23.jar
IntegratedDynamics-1.12.2-0.11.4.jar
IntegratedTunnels-1.12.2-1.5.2.jar
intwheel-1.12-1.2.7.jar
inventorysorter-1.12.2-1.12.4+52.jar
IronBackpacks-1.12.2-3.0.2-3.jar
ironchest-1.12.2-7.0.34.820.jar
jeibees-0.9.0.5-mc1.12.2.jar
jeiintegration_1.12.2-1.5.1.36.jar
jei_1.12.2-4.8.5.157.jar
journeymap-1.12.2-5.5.2.jar
JustEnoughResources-1.12.2-0.8.6.28.jar
LLOverlayReloaded-1.1.4-mc1.12.jar
malisisblocks-1.12.2-6.1.0.jar
malisiscore-1.12.2-6.4.0.jar
malisisdoors-1.12.2-7.3.0.jar
malisisswitches-1.12.2-5.1.0.jar
Mantle-1.12-1.3.1.21.jar
mcjtylib-1.12-2.6.5.jar
MCMultiPart-2.4.1.jar
meecreeps-1.12-0.1.7beta.jar
MobGrindingUtils-0.3.4.jar
modnametooltip_1.12.2-1.10.0.jar
modtweaker-4.0.5.jar
modular-routers-1.12.2-3.1.2.jar
Morpheus-1.12-3.3.2.jar
MouseTweaks-2.8-mc1.12.1.jar
MTLib-3.0.1.jar
multistorage-1.12.0-1.4.8.jar
NetherPortalFix_1.12.1-5.3.13.jar
notenoughwands-1.12-1.6.1.jar
p455w0rdslib-1.12-2.0.24.jar
Pam's+HarvestCraft+1.12.2q.jar
platforms-1.12.0-1.4.4.jar
QuantumStorage-1.12-4.4.8.jar
QuickLeafDecay-MC1.12.1-1.2.4.jar
rangedpumps-0.5.jar
RebornCore-1.12.2-3.6.8.214-universal.jar
RebornStorage-1.12.2-3.0.1.26.jar
RedstoneArsenal-1.12.2-2.3.7.18-universal.jar
RedstoneFlux-1.12-2.0.1.2-universal.jar
refinedstorage-1.5.25.jar
refinedstorageaddons-0.2.jar
ResourceLoader-MC1.12.1-1.5.3.jar
rftools-1.12-7.30.jar
rftoolsctrl-1.12-1.8.0.jar
rftoolsdim-1.12-5.52.jar
shetiphiancore-1.12.0-3.5.5.jar
Signals-1.12.2-1.2.2-5-universal.jar
sonarcore-1.12.2-5.0.5.jar
StevesCarts-1.12.2-2.4.17.88.jar
StorageDrawers-1.12.2-5.3.4.jar
StorageDrawersExtras-1.12-3.1.0.jar
swivelseating-1.0.0.jar
TConstruct-1.12.2-2.9.1.65.jar
tesla-core-lib-1.12-1.0.12.jar
theoneprobe-1.12-1.4.19.jar
ThermalCultivation-1.12.2-0.1.3.11-universal.jar
ThermalDynamics-1.12.2-2.3.10.4-universal.jar
ThermalExpansion-1.12.2-5.3.10.14-universal.jar
ThermalFoundation-1.12.2-2.3.10.6-universal.jar
TickProfiler-1.12-0.0.2.jar
TinkerToolLeveling-1.12-1.0.3.jar
Toast Control-1.12-1.2.0.jar
topaddons-1.12.2-1.2.1.jar
TrackAPI-1.1_1.12.jar
UniDict-1.12.2-1.5.jar
valkyrielib-1.12.2-2.0.7a.jar
WanionLib-1.12.2-1.3.jar
Waystones_1.12.2-4.0.20.jar
WirelessCraftingTerminal-1.12.2-3.8.55.jar
woot-1.12.2-0.0.10.jar
xnet-1.12-1.6.5.jar
Xtones-1.12-1.0.8-11.jar
zerocore-1.12-0.1.1.0.jar


No on both. Yes, right below it actually.

**Comment by Doomgull** [comment]
Probably #542. let me know if you can replicate/looks like that ticket video.

**Comment by TLomon** [comment]
Looks pretty darn similar. I'd be comfortable with you combining it.
