### ISSUE TITLE
1.12.2 Grindstone crashes server when reloading 

### ISSUE THREAD

**Issue by Ranger360O** [HellFirePvP/AstralSorcery#599]
On my server, I am running the latest (or at least what the Twitch launcher downloaded as the latest) version and run into this issue when I reload the chunk with a grindstone in it.

https://pastebin.com/yN2JVvXv

AS: 1.12.2-1.8.5

**Comment by Doomgull** [comment]
#576 

Not an Astral Sorcery issue, but a Soul Shards issue. See related ticket in linked issue, and downgrade version to resolve.
