### ISSUE TITLE
[Suggestion] List all constellations by default

### ISSUE THREAD

**Issue by Saereth** [HellFirePvP/AstralSorcery#60]
I've run into several people asking how many constellations there are, what they are etc. Now this information will eventually be on a webpage or youtube video right now but it got me thinking. In the book under constellations you could have all of them listed, and just have garbled text for their entry until you find the page and/or unlock them.

this would serve a couple purposes. 
1. you'd know the constellations that are out there, but maintain the exploration/discovery aspect because you'd still not know anything about them/be able to use them. 

2. You'd know which constellations you still need to explore and collect

Maybe some indication of which are Major and Minors would be good as well.

**Comment by Tarod7** [comment]
Only having one paper in the world that's "your" constellation paper for the attunement blue lights is weird too, unless I'm confused on that part.
