### ISSUE TITLE
Horolgium constellation overlays Pelotrio

### ISSUE THREAD

**Issue by BanzaiRun** [HellFirePvP/AstralSorcery#600]
![2018-03-17_17 54 40](https://user-images.githubusercontent.com/8942699/37558497-025f92fe-2a0d-11e8-843b-aa58d0cfdcfc.png)

Playing Modern Skyblock 3:-

Not sure if relevant but all the constellations were learnt via creation in an iridescent altar.

**Comment by Doomgull** [comment]
Not a bug, intentional. Means you have more than 8 constellations in the sky at once. Used to just deadlock the server.
