### ISSUE TITLE
Allow Enchanted Books from Stellar Refraction Table to be applied at Anvil

### ISSUE THREAD

**Issue by Saklad5** [HellFirePvP/AstralSorcery#602]
As it stands, books like Sharpness Ⅶ cannot be applied on other items using an Anvil. Unless I am missing something, this makes it impossible to use such Enchanted Books from a Stellar Refraction Table without additional mods. I am fairly certain that is not your intention, so please use the addToBookList method (if that is possible for vanilla enchantments) to fix it.

More urgently, this also makes those enchantments incompatible with multiple mods that check that list, such as Just Enough Resources. Judging by [the relevant code](https://github.com/way2muchnoise/JustEnoughResources/blob/8c836f02a408de304720b2e3b69480f82acec5c5/src/main/java/jeresources/registry/EnchantmentRegistry.java#L33), making those books applicable at an Anvil will also make Just Enough Resources acknowledge them so they can be shown in JEI.

**Comment by Doomgull** [comment]
There are sufficient methods to bypass vanilla anvil enchanting limits within modded, this is unlikely to be changed within AS by design.
