### ISSUE TITLE
[1.12.2] critical exception handling a packet on channel Astral Sorcery

### ISSUE THREAD

**Issue by Morpheus1101** [HellFirePvP/AstralSorcery#603]
The above was part of a larger message that was continually being displayed on server console, un-sure if its a bug or just some random anomaly.

Full display of the msg can be seen over on https://github.com/MinecraftModDevelopment/New-MMD-Public-Pack/issues/44

**Comment by Doomgull** [comment]
What was being done when it started?

Stringing this into the master network list at #513

**Comment by Morpheus1101** [comment]
At this stage i was trying to join the server, with no luck at all at that time

**Comment by Doomgull** [comment]
Yup, follow 513 then, possible fix included for the 1.9 release.
