### ISSUE TITLE
[Suggestion] Add Whitelist/Blacklist for Aevitas Attunement Growth Perk

### ISSUE THREAD

**Issue by Saklad5** [HellFirePvP/AstralSorcery#607]
The Aevitas perk effect that makes nearby plants grow can be extremely irritating in unexpected ways. In my case, I kept breaking my Mana Enchanter by turning Mystical Flowers into their two-block variants.

I understand if you intended it to work this way, and I can always just not attune myself with Aevitas, but unless this is changed, Aevitas is pretty much unusable with multiblocks like that. I also recognize that there is already a near-identical suggestion for the Aevitas Mantle, but this is an important addition to that.

**Comment by Doomgull** [comment]
Collapsed into master list.
