### ISSUE TITLE
it looks like you running an unsupported version of minecraft crash

### ISSUE THREAD

**Issue by creepermygamer** [HellFirePvP/AstralSorcery#608]
I am trying to run Astral Sorcery mod but when i try to run a world it crashes and says this "it looks like you running an unsupported version of minecraft crash." Please tell me what to do 
(i am running 1.11.2)

**Comment by Doomgull** [comment]
Run a version that is supported for the MC version you are using. The discord channel linked on the Curse page for AS is a better source to assist with that if youre having issues matching them.
