### ISSUE TITLE
Server crash when placing a lense in world

### ISSUE THREAD

**Issue by Saereth** [HellFirePvP/AstralSorcery#609]
Sevtech 3.0.3 pack

crashlog:
https://hastebin.com/ojomujamek.sql

astralsorcery-1.12.2-1.8.5

conditions: placed an aevitas collector, unenhanced on the ground and then broke it (survival mode) moved it a few blocks away about 30s later placed a lense down about 6 blocks away and the server crashed with this message.

**Comment by Saereth** [comment]
Also unable to log back in after the server restarted, immediately get disconnected with internal server error

https://imgur.com/a/HCa70

**Comment by Doomgull** [comment]
Issue determined to be a lens without proper full NBT data for stats. Unable to replicate in the pack, closing for now unless it resurfaces and source for NBT error can be determined.
