### ISSUE TITLE
Grindstone Interaction and Inventory

### ISSUE THREAD

**Issue by Saklad5** [HellFirePvP/AstralSorcery#612]
The Player Simulator in Integrated Tunnels is [unable to interact](https://github.com/CyclopsMC/IntegratedTunnels/issues/116) with the Grindstone, and only the Grindstone. What makes it different from the Spectral Relay, which works as expected, with regard to listening for input?

On a related note, while I understand that you [do not want pipes and such to interact with the Grindstone](https://github.com/HellFirePvP/AstralSorcery/issues/570), I think it would be improved by having an inventory that is visible to logic mods such as Integrated Dynamics and OpenComputers for the purpose of automation. At the very least, it’d be nice to emit a Comparator signal when something is in the Grindstone, possibly with the strength dependent on the attributes of the item.

**Comment by HellFirePvP** [comment]
The entire purpose of the grindstone comes along with the concept of it not being automateable and i will do whatever i can do prevent users from doing that. I do want to create an incentive to use the grindstone to either produce a certain result or gain potential benefits from it, which you can't get from another machine potentially, to reward a player for not standing in front of a terminal and playing GUI-simulator-9000.
So, no, i will not make it automateable and/or make it give out any information about itself.

**Comment by Saklad5** [comment]
Could you eventually add a less optimal but more automatic way to increase cutting? It could be slower, or more likely to reduce size, or powered by liquid starlight, or otherwise inferior to manually using the Grindstone.

It’s your mod, in the end, but it is somewhat annoying to have no choice but staring at the screen and waiting. I’m fine with manually doing things a few times, like with the Crafting Altars, but Celestial Crystals need to be produced over and over again to power various things in the mod.

I noticed that one of the planned features is a way to grow crystals in the Starlight Infuser. That’s the kind of thing I’m thinking of, though you can already automate that part. If anything, that’s too easy.

**Comment by HellFirePvP** [comment]
> Could you eventually add a less optimal but more automatic way to increase cutting? It could be slower, or more likely to reduce size, or powered by liquid starlight, or otherwise inferior to manually using the Grindstone.

No. cause nothing that is automated is inferior in any way. Cause where you spend 20 seconds before doing something, you completely stop spending time doing something. So it doesn't matter how much inferior i make it besides "you can sacrifice 899 size to get a chance to gain 1 cutting". That would be a compensation.
You see, automation in that regard just completely ruins gameplay. Where you had to first invest some time and effort into doing something, you know just watch numbers in your GUI increase.

**Comment by Doomgull** [comment]
Minor correction, but visible Source, not open source.

Also, anything that simulates a right click action can utilize a grindstone. But, the issue you run into is that fake players don't gain astral sorcery progression, and so you can't do things like automate infusions or other crafting involving right-clicking that's not a grindstone, which is progression Limited. You can manually set astral sorcery progression using op commands for those fake players if you have the right id, but it occasionally has some weird bugs still.

There's a guy on the astral sorcery Discord who has automated manufacturing more than 67,000 perfect collector crystals, after all.

**Comment by Saklad5** [comment]
@Doomgull Wait, are you saying that brand-new players cannot use a grindstone either?

**Comment by Doomgull** [comment]
I believe the grindstone is the only operation that is not progression gated. Almost everything else requires progression, but IT / ID can automate the grindstone. Just not the extraction of crystals, without doing some weird block breaking shenanigans

**Comment by Saklad5** [comment]
It can’t. That’s the point of this issue.

**Comment by Doomgull** [comment]
You're amusingly wrong. Come onto the AS discord, talk to the guy named TPS Killer about his 67000+ automated perfect collectors, and see how he did it, then. 

There's been posts on the Feed the Beast subreddit detailing it, as well, using IT / ID, mechanical users, and other things that simulate player right clicks.

Automating the inventory is the thing that's not being added, automating right clicks is not that big a deal because that's stupidly easy.
