### ISSUE TITLE
Rituals Stop working after a time.

### ISSUE THREAD

**Issue by Sarnow** [HellFirePvP/AstralSorcery#613]
I have several rituals (Discidia and Lucerna) and they will stop working after a time and I have to break the pedestal and replace it before it starts working again. I haven't figured out what triggers it at this time though.

**Comment by Doomgull** [comment]
Changes in the starlight network and chunk load/unload. Possible fix in 1.9 already with other network issues.

Remove sponge if its there, some have reported it helps. Otherwise, watch ticket #539

**Comment by Sarnow** [comment]
Thanks, didn't see the other one or I wouldn't have posted this one.
