### ISSUE TITLE
Conflict with shader!

### ISSUE THREAD

**Issue by oOMrFarrellOo** [HellFirePvP/AstralSorcery#614]
I test it out on **forge** 1.12.2 - 14.23.2.2611 and 1.12.2 - 14.23.2.2641 & **optfine** 1.12.2 HD U C9 and 1.12.2 HD U D1. Nothing fixed. Would you able to fix the conflict with shader? I cannot play MC without shaders, so PLEASE.

**Comment by Doomgull** [comment]
No.

Use the "weakSkyRender" config option in AS to attempt compatibility.  AS utilizes shaders to function, and that is the furthest support will ever go for that.
