### ISSUE TITLE
Collector crystal with proper setup does nothing.  Altar never has enough starlight.

### ISSUE THREAD

**Issue by ebnoid** [HellFirePvP/AstralSorcery#616]
The setup is good on both.  Collector crystal structure emits proper particles+lightning.  Altar is in _dense_ starlight.  No amount of crystals helps.

https://i.imgur.com/YjaWdeb.png
https://i.imgur.com/tnuszKc.png
https://i.imgur.com/0tJ4HAN.png

Edit: Also, everything was fine when using 1.12.1 version.  We updated to 1.12.2 and now no altars get enough light.

**Comment by Doomgull** [comment]
It's not proper. The amount of cannibalism there is painful. Move the crystals away from each other, if within 16 blocks of another starlight collecting block, they "steal" from each other. Check out the Discord linked on the curse page for more assistance.
