### ISSUE TITLE
The Betweenlands dimension incompatibility.

### ISSUE THREAD

**Issue by Titus-Armillius** [HellFirePvP/AstralSorcery#62]
I changed the dimension ID for the rendering of the sky to be 20, which is the Betweenlands dimension and got this crash when trying to enter: http://pastebin.com/i088fyay

My guess is that something in your renderer is clashing with the custom shaders The Betweenlands uses.

**Comment by HellFirePvP** [comment]
The 2 world providers are incompatible. i guess only doing 'weak' sky rendering (aka only constellations and no solar & lunar eclipses aswell as not the full sky rendering) is applicable here. Add the dimension id of the betweenlands to 'weakSkyRenders' and it should work.

As for the incompatibility in general: well, not much i can do.
