### ISSUE TITLE
Telescope won’t stay on star map

### ISSUE THREAD

**Issue by kmork1** [HellFirePvP/AstralSorcery#621]
Astral sorcery 1.8.5 
Direwolf20 v1.9 pack

Whenever I right click a telescope it brings up the start map and then instantly closes it

**Comment by kmork1** [comment]
I’m playing on a public server called wyvernrealms

**Comment by Doomgull** [comment]
#531 

Remove Sponge if present on the server, as a work-around, as it's been pointed to by many users as the culprit (though not all)

**Comment by mjra007** [comment]
@kmork1 wait for a sponge release they fixed this recently SpongePowered/SpongeForge#2118
