### ISSUE TITLE
Repeat Discidia self harm on attack

### ISSUE THREAD

**Issue by djnifos** [HellFirePvP/AstralSorcery#623]
Same issue as  https://github.com/HellFirePvP/AstralSorcery/issues/509, I read that issue like it had been fixed, but I'm taking damage wearing the Discidia robe with the perk

Sevtech 3.0.6, AS 1.8.5

**Comment by Doomgull** [comment]
Because it may be relevant, what weapon are you using to attack with, what monster or other creature are you attacking? And does it replicate without wearing the mantle but while attuned to that perk, and vice versa?

Also, because it is the sevtec pack, what is your current age progression?

**Comment by djnifos** [comment]
I'm age 3.  I was using a TF Knightly Sword with Light Pierce, Venom, and Unbreaking.  Doesn't happen just with the perk.  Haven't tried just the mantle yet.  I was fighting vanilla zombies, skeletons, trumpet skeletons, and a creeper.
