### ISSUE TITLE
Shader Compatibility

### ISSUE THREAD

**Issue by SpacePirate2016** [HellFirePvP/AstralSorcery#624]
I'm new to the mod but came across this fairly quickly. Looking into the sky at certain angles while using shaders produces a static effect usually yellow in color. In the image below I'm running Chocapic13 V6, but all other shaders I've used have the same effect. I'm guessing this is due to conflicts with some sort of skybox overlay.

![2018-04-11_19 05 46](https://user-images.githubusercontent.com/38304713/38652574-6a6bcefa-3dbb-11e8-9043-c86b15693e7f.png)

**Comment by Doomgull** [comment]
Correct, AS uses it's own shader to display the constellations. You can attempt to enable the compatibility option to see if it fixes it under the AstralSorcery config file, the option you want is "weakSkyRender".
