### ISSUE TITLE
Crashed twice in 24 hours

### ISSUE THREAD

**Issue by TWJedi** [HellFirePvP/AstralSorcery#625]
First crash was last night:

https://pastebin.com/NsxJUUf1

I was standing on my Attunement Altar, it had not yet correctly formed. It crashed when I looked at one of the marble pillars.

Second crash just now:

https://pastebin.com/1538nQKr

I was simply standing near the Starlight Infuser, not doing anything. My view direction was towards the attunement altar.

**Update:** Crashed two more times today, same crash.

Modpack: Sevtech Ages 3.0.6
Java 8.161
Forge 14.23.2.2654

**Comment by ZombieHDGaming** [comment]
There's a config option, if I remember correctly, that causes AS to override the sky handling. If it is enabled, try disabling it if it is enabled and see if it crashes again @TWJedi.

**Comment by ZombieHDGaming** [comment]
Hmm, after a look into the code, both of your crashes are pointing to a for loop on the first line which is kinda weird. Quick question, for the second crash, was the Attunement Altar formed at that point? Or was it still not fully formed?

**Comment by TWJedi** [comment]
The attunement altar was formed after the first crash. It was a good distance away though, so I'm not sure if it had anything to do with the second crash.

The third and fourth crashes today were at random times, I was not near the attunement altar.

**Comment by Doomgull** [comment]
Attunement altar shouldn't have wnything to do with this.

**Comment by SeanLatimer** [comment]
Any updates on this?

Keeps crashing our server

**Comment by Doomgull** [comment]
1.9 is still being worked on, it comes out when it comes out.
