### ISSUE TITLE
Game Crash on World Load

### ISSUE THREAD

**Issue by mastershivam** [HellFirePvP/AstralSorcery#626]
Repeated crash on trying to load into my world:
https://pastebin.com/u2rLcx5F

Using a modified Foolcraft 2 modpack (1.10.2)

Forge 12.18.3.2511
Astral Sorcery 1.4.5
Java 8.161

**Comment by Doomgull** [comment]
Delete player files to reset perk data.

Also, 1.10 has been unsupported by AS for a while now.
