### ISSUE TITLE
[Crafttweaker] Cannot use OR IIngredients in tables

### ISSUE THREAD

**Issue by justinrusso** [HellFirePvP/AstralSorcery#627]
It appears like the crafting tables do not support ORed IIngredients correctly. Support for this would be appreciated 👍 

Reference:

I use an OR IIngredient to add support for any bucket to be used in recipes. Once in game, the item seems to be resulting in it being translated to a `null` for the recipe, and just excludes the ingredient from the recipe.

**Comment by HellFirePvP** [comment]
'OR'-ingredients and other ingredient types are supported as of v1.9 - Any other functionality IIngredients imply (such as transformers, matchers, ...) are **NOT** supported.
