### ISSUE TITLE
Illumination and Nocturnal Powder missing particle effects when Valkyrien Warfare is installed

### ISSUE THREAD

**Issue by grouNDfx** [HellFirePvP/AstralSorcery#629]
The lighting in the nocturnal powder and the yellow orb from the illumination powder are missing when Valkyrien Warfare and Valkyrie Lib are installed.

Mod Versions:
- Valkyrien Warfare 0.9_alpha
- Valkyrie Lib 1.12.2-2.0.8a
- Astral Sorcery 1.12.2-1.8.5

[debug.log](paste.ee/p/XhD9R)
[latest.log](paste.ee/p/N4E9Z)

**Comment by Doomgull** [comment]
Would recommend also opening a ticket on their GitHub as well, due to the interaction.

**Comment by grouNDfx** [comment]
@Doomgull will do

**Comment by HellFirePvP** [comment]
*links to the VW issue*

https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/issues/147
