### ISSUE TITLE
Floating crystal in different chunk thank Iridescent Altar provides very little boost.

### ISSUE THREAD

**Issue by Rixxaw** [HellFirePvP/AstralSorcery#630]
I had 2 attuned Celestial 90+ purity crystals pointed at my Iridescent Altar at Y Level 82.  The Altar was in a star field blue with white sparkles.  Every previous table had been max star light.  I had 4 Relay's setup around the altar and higher up as per the instructions.  And yet I was getting about 50% strength on my table in the middle of the night.  After about 48 hours of troubleshooting and frustration, I decided to move my floating crystals to make room for me to add more relays.  I tore down the 2 crystal structures and put up just 1, checked the table and boom max star light.  The difference?  The table is centered on the starfield which seems to generate at the chunk intersection of 4 chunks.  The table was in 1 chunk and the two previous crystals were in different chunks.  The new crystal was in the same chunk as the table.

Is it possible that being in a different chunk would cause this?

**Comment by Rixxaw** [comment]
In this screenshot you can see where my previous  floating crystals were located in other chunks and the new crystal moved to where i had a Stairwell is boosting the altar to max in Daytime... Which blows my mind currently.

![image](https://user-images.githubusercontent.com/17864718/38841781-b8eabb9c-41ab-11e8-9a7f-e20bd99bc201.png)

**Comment by Doomgull** [comment]
Literally nothing to do with it.

But having relays or collectors within 16 blocks of each other results in cannibalism of the light provided, disregarding if the collectors had enhancement structures so they provided starlight when their constellation was not in the sky.

In that screenshot, the relays are all cannibalizing each other, and that crystal is being heavily cannibalized by the two relays on its side.

See the Discord channel for further discussion.

**Comment by Rixxaw** [comment]
Nah its not cannibalization... They might be cannibalizing each other, but this is how I always build my altar, and it always provides more light for each relay.  Maybe not the MOST light possible now that I know there is a within 16 block limitation.  However I had that same crystal on the other side of the altar and zero benefit to the table.  Moved it to the side in the picture and the table is full.   Maybe it was just a fluke.

**Comment by XavierNero** [comment]
Does this mean that enhanced structure celestial collector crystals are not affected by cannibalism?

**Comment by Doomgull** [comment]
As I said when closing this ticket 2 months ago, the Discord server will provide much more assistance for this, including pinned example images.
