### ISSUE TITLE
Tile entities are registered under "minecraft" namespace

### ISSUE THREAD

**Issue by Hubry** [HellFirePvP/AstralSorcery#631]
All Astral Sorcery tile entities are registered with the default namespace, which could cause problems if another mod registers its tile entities on the same namespace. I'll note that this is pretty unlikely (especially that all AS tile entities have their names prefixed with `tile`).

![Example](https://user-images.githubusercontent.com/26120076/38869246-4dc0a1d4-424a-11e8-9fa6-47c45f7aec00.png)

(Used versions: Forge 14.23.2.2624, AS 1.8.5)

**Comment by HellFirePvP** [comment]
Will be adressed for 1.13 as it'll break a lot of worlds and cause incompatibility across AS versions.
