### ISSUE TITLE
missing texture on TCon fluid in containment chalice/ichosic resonator

### ISSUE THREAD

**Issue by syrun97** [HellFirePvP/AstralSorcery#637]
![2018-04-20_14 27 05](https://user-images.githubusercontent.com/19798397/39033078-4668462c-44ab-11e8-8b21-91e8768d7698.png)
![2018-04-20_14 37 09](https://user-images.githubusercontent.com/19798397/39033091-57bff00a-44ab-11e8-8c94-51fee7468b58.png)
How to reproduce: put Tcon fluid on chalice
![2018-04-20_15 08 54](https://user-images.githubusercontent.com/19798397/39033390-bff52b58-44ac-11e8-8c07-c94af0f93949.png)
Texturepack: vanila texturepack
Modpack:SevTech Ages 3.0.6 w/o fancy block particles, better foilage, betterfps and smooth font
Astral Sorcery version:1.8.5
TCon Version:2.9-1.65

**Comment by HellFirePvP** [comment]
Issue for that is that the color multiplier of said textures isn't applied correctly. Already found internally and fixed for next version.
