### ISSUE TITLE
[Client Crash] Involving Illumination wand and translucent blocks

### ISSUE THREAD

**Issue by bafomdad** [HellFirePvP/AstralSorcery#64]
Mod version: beta 1.1.5
Crash report: http://pastebin.com/1WsyEtJ9

Steps to reproduce:
1. Get illumination wand
2. Right click with it on a limestone block (or perhaps any decoration blocks from Quark) to make it translucent
3. crash from the property exception on the client side. Does not affect servers.

**Comment by HellFirePvP** [comment]
Happens because vazkii queries the blockstate again feom the world instead of using the one that is passed in... uhh.

**Comment by HellFirePvP** [comment]
'Adressed' in the next version. will no longer crash, but won't display anything either in case the underlying blockstate crashes on .getPickBlock due to unsafe querying of world blockstates.
