### ISSUE TITLE
Allow class transformers to be run multiple times

### ISSUE THREAD

**Issue by Aaron1011** [HellFirePvP/AstralSorcery#644]
The [Mixin](https://github.com/SpongePowered/Mixin) project, which is used by Sponge and other coremods, causes class transformers to be run twice. The first time occurs during startup, when Mixin sets up its internal state, and checks for problems with loaded Mixin classes. The second time occurs when the class is actually loaded.

Currently, AstralSorcery only allows each transformation [to run once](https://github.com/HellFirePvP/AstralSorcery/blob/4da5db76d80b8c73c3987ccc29fb6ac16468a3ce/src/main/java/hellfirepvp/astralsorcery/core/transform/AstralPatchTransformer.java#L101). To ensure that AstralSorcery is compatible with Mixin projects, this check should be removed (or changed to allow each transformer to run at most twice).

**Comment by Doomgull** [comment]
![image](https://user-images.githubusercontent.com/12677933/39097434-2dc27d7e-462a-11e8-82b5-971bffda2ab5.png)

From the Curse page. No.
