### ISSUE TITLE
Stationary Telescope GUI not working

### ISSUE THREAD

**Issue by amateurvspixels** [HellFirePvP/AstralSorcery#646]
I'm not necessarily calling this a bug, I'd be 100% ready to accept it as user error, but I can't figure out why my stationary telescope won't load the GUI. I tried it in a fairly open area near my base, I tried it out in an empty desert, I tried breaking it and replacing it (sometimes the grindstone will bug and this fixes that for me), but no changes have brought up a GUI.

**Comment by Doomgull** [comment]
#531, remove Sponge from the server if present.

**Comment by mjra007** [comment]
@amateurvspixels wait for a sponge release they fixed this recently https://github.com/SpongePowered/SpongeForge/issues/2118
