### ISSUE TITLE
Game-breaking speeds achieved using perks and a TCon slimesling

### ISSUE THREAD

**Issue by amateurvspixels** [HellFirePvP/AstralSorcery#647]
Basically what the title says. When you use a slimesling to throw yourself out across the ocean with the "Who Needs Fins?" perk active, you can sometimes get kicked from the server because your speed exceeds acceptable bounds. To highlight just how fast I've been able to reproduce on my friendly local whitelisted server, I've included a video [here](https://youtu.be/I3_Tk36pMLw).

**Comment by Jemsuper** [comment]
I also get this when flying into the water while wearing mantle of stars vicio adjusted. No slime sling

**Comment by xenxero1** [comment]
While this isn't a fix since it isn't a bug, you should ask your server owners to change the server configs.

/gamerule disableElytraMovementCheck true

That should make the server stop kicking people for moving in unexpected ways or for exceeding certain speed limitations.
