### ISSUE TITLE
Slabs are always placed "lower" slabs with Formation Wand

### ISSUE THREAD

**Issue by Sorbe** [HellFirePvP/AstralSorcery#649]
I tried to use the _Formation Wand_ from Astral Sorcerery 1.8.5 in **SevTech 3.0.6** with slabs.

At least for Birch Slabs, and seemingly all slabs I tried, the slab is always a "lower slab" even if placed under blocks.

The scenario was putting wooden slabs on the ceiling.  I expected to either automatically get upper slabs when placed from below -OR- be able to shift click a target upper slab in the world and place them the same way.

In all cases, the slabs were only being placed as lower slabs - making this great tool far less useful.

**Comment by Sorbe** [comment]
![2018-04-24_23 21 31](https://user-images.githubusercontent.com/7958470/39229226-b21034f2-4816-11e8-983f-18936bd0e9af.png)

**Comment by HellFirePvP** [comment]
Duplicates #650
