### ISSUE TITLE
Vicio Mantle of the Stars rapid toggle on/off

### ISSUE THREAD

**Issue by randomlypickedname** [HellFirePvP/AstralSorcery#651]
Same as #312, AS version 1.8.5 in SevTech 3.0.6. 

This GIF may not be the best quality but maybe it'll help? https://imgur.com/CnB69vw

**Comment by Doomgull** [comment]
You running Sponge on the server, by chance? Chasing something down.

**Comment by randomlypickedname** [comment]
Nope, just that default modpack with a couple mods for utility.

**Comment by aMannus** [comment]
We have the exact same issue on the server I play on. No sponge, default modpack. Single player works fine, the gamerule for the disableElytraMovement doesn't change anything. Might still be related to the vanilla minecraft anti-cheat, not sure.

**Comment by LightsDawn** [comment]
im admin on the server aMannus is on, there is no output at all about any errors from AS. the pack is running sevtech 3.0.6 with only a couple utility mods

**Comment by Doomgull** [comment]
If so, it's able to be turned off once you've advanced far enough in pack progression, iirc.

**Comment by MattmonGaming** [comment]
I am having an identical issue in the Magitech Soldiers pack since updating from 1.8.5 to ANY newer version of Astral Sorcery. Happens in both SSP and SMP. Here's a link to the pack for recreation: https://minecraft.curseforge.com/projects/magitech-soldiers/files/2555537

**Comment by aMannus** [comment]
Sooooo, I don't know how, or why, or if you people changed anything in later AS versions... But we updated to SevTech 3.0.7 on the server I play on, which updates AS to 1.8.10, and it's completely fixed for us. 

So I don't know if this'll be the case for everyone, but do try updating either SevTech or just AS itself and see if it does fix it for everyone.

Also, bit late, but thank you all very much for Astral Sorcery. This is becoming one of my favorite magic mods, and I'm seriously loving it so far!

**Comment by Doomgull** [comment]
@MattmonGaming @Ryan-Cross @randomlypickedname Can y'all update to AS 1.8.10 and confirm if you're seeing improvements like aMannus?

**Comment by randomlypickedname** [comment]
I'll push out the update to our server in a few hours and see how it goes.

**Comment by Doomgull** [comment]
I've also had confirmations in Discord that 1.8.10 has solved the issue for them, as well, so I'm going to mark this one resolved until we see a recursion.
