### ISSUE TITLE
Suggestion: Consider a "fill" wand that places blocks in a plane

### ISSUE THREAD

**Issue by Sorbe** [HellFirePvP/AstralSorcery#652]
It would be very helpful for building structures to place a plane of selected blocks (say 16x16 maximum) or place them within a frame of blocks or against other existing blocks.  This would complement the formation wand and even one up a "builders wand".  In vertical mode, it would make walls and in horizontal mode, floors and ceilings from blocks already in your inventory.

**Comment by Doomgull** [comment]
Collapsed into master list.
