### ISSUE TITLE
Suggestion: Astronomy is a great theme, how about lunar stuff later?

### ISSUE THREAD

**Issue by Sorbe** [HellFirePvP/AstralSorcery#653]
I love your Astral Sorcery mod, the very best thing about playing Sevtech these days.  It pushes all of my buttons (astronomy, magic, cool multi-blocks, awesome effect, etc.).  I was wondering what would be cool to add next... and I had a suggestion for you.

You could add more lunar stuff to the mod -- the game already has solar and lunar eclipses.  These should be very special events overworld events IMO.  Further options might include "Moondust", more lycanthropy mischief, something like tides, lunar rituals, neolithic rituals at converted druid circles, moonbeam effects for new magic spells (I would suggest wide area lighting, charms and love effects).  Perhaps ways to control the phase of the moon to light up the night and spawn special Fey beings.

You could even integrate with the planetary stuff and add special lunar mobs for the moon -- including perhaps underground cities and materials...

**Comment by Doomgull** [comment]
Collapsed into master list.
