### ISSUE TITLE
Crash report for the 1.8.7

### ISSUE THREAD

**Issue by JoeSGT** [HellFirePvP/AstralSorcery#654]
https://pastebin.com/M5mw9VxQ
i crash i even reseted the config but still crash 

EDIT: i even tried with a clean minecraft instance with just bauble with this mod and crash with clean configs also

**Comment by Doomgull** [comment]
Can you upload your config file, please?

**Comment by JoeSGT** [comment]
[config.zip](https://github.com/HellFirePvP/AstralSorcery/files/1948163/config.zip)

**Comment by Doomgull** [comment]
Roll back to 1.8.5 for now while it's investigated.

**Comment by boosterdev** [comment]
[additional crashlog](https://gist.githubusercontent.com/boosterdev/c644ed388da69b744dd91a24ecd41515/raw/)

**Comment by Doomgull** [comment]
Fixed version is now available on Curse
