### ISSUE TITLE
Collector Crystals in SevTech

### ISSUE THREAD

**Issue by Tapeman83** [HellFirePvP/AstralSorcery#657]
Hello,

I have been doing a bunch of work with Astral Sorcery in SevTech: Ages, and have been running into some serious issues with the Celestial Collector Crystals. Specifically, even with a 900/100/100 crystal attuned to Vicio, it does not charge up the altar at all. 

Not even a single drop of starlight is added to the altar, despite having the structure built properly (generating the particle effects for the crystal) and a clear line of sight to the sky, and from the crystal to the altar. Linking the crystal to the altar does absolutely nothing, and I have no idea what is causing it.

Here are a few screenshots to visualize the situation:

![2018-04-26_17 44 16](https://user-images.githubusercontent.com/38392493/39338219-269041f2-4987-11e8-8be1-c792feba5855.png)

![2018-04-26_17 44 20](https://user-images.githubusercontent.com/38392493/39338224-32d8f36e-4987-11e8-80c2-54177009ee7d.png)

This setup produces exactly zero starlight for my altar:

![2018-04-26_19 25 01](https://user-images.githubusercontent.com/38392493/39338289-8dd1c32c-4987-11e8-89ef-88a14feb94f9.png)

Please note that I have no spectral relays currently set up, so it's definitely not suffering from cannibalism. Any help would be greatly appreciated. Thanks.

**Comment by Doomgull** [comment]
Restart MC, #535

**Comment by Degonsky** [comment]
Same issue, sevtech ages

Restart didn't helped, re-install too,

**Comment by Doomgull** [comment]
If you are single player, it's 535.

**Comment by Degonsky** [comment]
Collector crystal begun to work after I changed minecraft launcher, but after restart issue occured again and remains the same.
