### ISSUE TITLE
[STDERR] on Pack Load 

### ISSUE THREAD

**Issue by Tanto17** [HellFirePvP/AstralSorcery#658]
Hello, 
I'm encountering an error when I load my own custom pack. The pack loads and plays fine but the console spam has me concerned. This is probably an issue on my end since I am fairly new to packmaking. 

Error Spam lines 257 - 400. 

https://pastebin.com/dNpbRwUQ

Sorry if this not helpful for you at all. 
Thanks for an awesome mod!

**Comment by Tanto17** [comment]
Thanks! Good luck with 1.9

**Comment by HellFirePvP** [comment]
Does this happen with AS alone aswell? Does it happen only on a dedicated server or singleplayer? Have you tested either? Does it happen in a sponge environment? You might wanna test 'remove & retry' with some mods and see if this issue disappears *in case it doesn't happen with AS alone*

**Comment by Tanto17** [comment]
Thanks for looking into it. Sorry I am not the best tester. I only have one computer and am only running single player.
Just tested with only Astral Sorcery and Baubles it still occurs (new log): 

https://pastebin.com/9Hi14fuC

LWJGL 2 version: 2.9.4-nightly2015209
Minecraft version: 1.12.2
Forge version: 14.23.3.2662

Again thanks for all the work going into this mod.

**Comment by Tanto17** [comment]
Oh I see a new version is out. I'll test it out again and get back to you.

**Comment by Tanto17** [comment]
Unfortunately it still occurs in my single player world with the new version of Astral Sorcery (1.12.2-1.8.9)
https://pastebin.com/GN1ZqpaW

**Comment by HellFirePvP** [comment]
oups. i derped >_>

**Comment by Tanto17** [comment]
Awesome thanks for the work! 
Loving the mod!
