### ISSUE TITLE
Crash while doing starlight infusion

### ISSUE THREAD

**Issue by RayCore** [HellFirePvP/AstralSorcery#662]
I crashed while doing infusion, i placed a bucked of liquid starlight, and (it seems) as soon as i looked at the infuser i crushed, it might be helpful to know that i had a blood magic tank inside the structure.

Here is the log: https://pastebin.com/HnMzv62d
The first lines are from when i filled lightwells with crystals a couple minutes before so it should have everything needed

Modpack: SevTech 3.0.6
Java: 1.8.0.171
Forge 14.23.2.2651
Optifine: No

**Comment by HellFirePvP** [comment]
Fixed with AS 1.8.8 - wait until the pack has updated, darko is already working on the update 3.0.7

**Comment by RayCore** [comment]
woah, that was quick. Thanks!
