### ISSUE TITLE
[1.12.2] Crystal shines on Crafting Table, can't craft anything

### ISSUE THREAD

**Issue by Corsaka** [HellFirePvP/AstralSorcery#664]
I have no idea what's going on. This works fine in multiplayer but not in this specific singleplayer world - maybe because I have creative mode on, maybe not.

**Comment by Corsaka** [comment]
![image](https://user-images.githubusercontent.com/23699128/39397878-2eab4756-4afe-11e8-9b01-fda05e26e777.png)
![image](https://user-images.githubusercontent.com/23699128/39397885-39c42e32-4afe-11e8-9152-3c51a2909d4a.png)
Neither of the starter recipes work. I'm incredibly confused.

**Comment by Doomgull** [comment]
#535 , restart MC in SSP.

**Comment by Corsaka** [comment]
And so I'm not allowed to be in creative mode and it'll suddenly work

Ok
