### ISSUE TITLE
Ritual Pedestal place/break crash

### ISSUE THREAD

**Issue by Machadeon** [HellFirePvP/AstralSorcery#665]
This may or may not be related to #539.

Context: Astral Sorcery v.1.8.8, custom modpack, single player world, full mod list below. Chunkloading from Weirding Gadget and Mekanism (anchor upgrades) only.

Upon traveling to the nether and back then immediately breaking an active ritual pedestal with an unlinked ritual anchor, the pedestal broke, the crystal did not drop, I picked up the pedestal, then the game crashed and produced the first crash report included in this report.

After restarting the game the ritual pedestal was in my inventory but the crystal was gone. Upon placing the ritual pedestal back in its original position the game crashed again and produced the second crash report included in this report.

It should be noted that the ritual is in the spawn chunks, but there is also chunkloading in nearby chunks, but NOT covering the chunk with the ritual pedestal.

[crash-2018-04-28_17.41.38-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/1958325/crash-2018-04-28_17.41.38-server.txt)
[crash-2018-04-28_18.14.46-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/1958326/crash-2018-04-28_18.14.46-server.txt)

Mod list:
Astral Sorcery 1.8.8
Avaritia 3.2.0.13
Baubles 1.5.2
Block Drops (JEI Addon) 1.4.0
Brandon's Core 2.4.2.157
CodeChicken Lib 3.1.7.340
Common Capabilities 1.4.0
Cooking for Blockheads 6.3.26
Cyclops Core 0.11.5
Draconic Evolution 2.3.11.290
Ender Storage 2.4.2.126
Integrated Dynamics 0.11.10
Integrated Tunnels 1.5.5
JEI Villagers 1.0.2
Just Enough Items (JEI) 4.9.1.168
Mekanism 9.4.5.340
Mekanism Generators 9.4.5.340
Mekanism Tools 9.4.5.340
Mouse Tweaks 2.8-mc1.12.1
Pam's Harvestcraft 1.12.2t
Reborn Core 3.8.0.264
Reborn Storage 3.0.6.43
Redstone Flux 2.0.1.2
Refined Storage 1.5.33
The Weirding Gadget 2.0.5

**Comment by HellFirePvP** [comment]
Already fixed with 1.8.9
