### ISSUE TITLE
AstralSorcery: Data not loading...

### ISSUE THREAD

**Issue by xPROALPACKAx** [HellFirePvP/AstralSorcery#666]
I'm new to this pack and this is the second time I'm loading onto my world and this error message came up and when I relog in I still get the message.

AstralSorcery: Your progress could not be loaded and can't be recovered from backup. Please contact an administrator to lookup what went wrong and/or potentially recover data from a backup.
Don't know what to do need help

**Comment by Doomgull** [comment]
looks like your playerdata.astral file was corrupt. How did you exit the world previously? Was it via the normal exit and save button from the Escape menu, or did you just click the red X?

Verify as well, that the <UUID>.astral files inside the world save folder for the player data aren't write protected, or otherwise prevented from writing.

**Comment by xPROALPACKAx** [comment]
I left by saving and exiting through the escape menu.

**Comment by Doomgull** [comment]
"Verify as well, that the .astral files inside the world save folder for the player data aren't write protected, or otherwise prevented from writing."

**Comment by xPROALPACKAx** [comment]
I can write in the .astral files

**Comment by Doomgull** [comment]
You're an admin, of course you can. Doesn't mean windows lets mc write them. Double check read-only or file security settings on files and folder. 

Otherwise, something broke in your progress file. What's in the .astral? If you rempve it and rename the .astral.back to match it, what happens?

**Comment by xPROALPACKAx** [comment]
When I renamed the.astral.back file to astral and removed the original one the world file seems fine and I didn’t get the message.

Thank you for the help and seems like a great mod
