### ISSUE TITLE
Bug in AstralSorcery

### ISSUE THREAD

**Issue by pingvikin** [HellFirePvP/AstralSorcery#669]
Hello, when connecting a player on my server, it is disconnected from the server.

Forge version: 2655
AstralSorcery version: 1.12.2-1.8.9

latest server log: https://gist.github.com/pingvikin/ccbd456eb948e7a67391c7c1c3756eda

**Comment by Doomgull** [comment]
#513

**Comment by Xules01** [comment]
I'm seeing this with my players as well.  It seems to happen during the time AstralSorcery is trying to synchronize configuration files with the player.  Is there a way you could try putting a delay on this so it's not happening while the player is trying to login?
