### ISSUE TITLE
Rock Crystals in CraftTweaker scripts match too strictly

### ISSUE THREAD

**Issue by codewarrior0** [HellFirePvP/AstralSorcery#670]
CraftTweaker scripts that specify `<astralsorcery:itemrockcrystalsimple>` as an ingredient will only match the plain rock crystal, and reject crystals that are celestial, attuned, or both. In contrast, stock AS recipes such as the Lightwell and Linking Tool accept any such crystal.

One solution would be to create an oredict key that matches any rock or celestial crystal and another key that just matches celestial crystals. Another solution (that would retroactively fix any existing scripts) would be to special-case the CT handling of the rock crystal and celestial crystal items to automatically generify them as is done in `ItemHandle.getCrystalVariant`.

**Comment by codewarrior0** [comment]
I've been told that using an oredict key for crystals in CT scripts fails due to the NBT data on the crystals. The special-case handling might be the best solution.

**Comment by codewarrior0** [comment]
It works if the items are added to the oredict like so:

```
# Astral Sorcery Rock Crystals

    <ore:crystalAstralRockAny>.add(<astralsorcery:itemrockcrystalsimple>.withEmptyTag());
    <ore:crystalAstralRockAny>.add(<astralsorcery:itemtunedrockcrystal>.withEmptyTag());
    <ore:crystalAstralRockAny>.add(<astralsorcery:itemcelestialcrystal>.withEmptyTag());
    <ore:crystalAstralRockAny>.add(<astralsorcery:itemtunedcelestialcrystal>.withEmptyTag());
```

**Comment by justinrusso** [comment]
Indeed, oredict does not care about nbt tags. You can also omit the .withEmptyTag() part and it should still work.

**Comment by codewarrior0** [comment]
`withEmptyTag()` was needed. Without it, recipes using the tag did not work in the Vanilla crafting table.

**Comment by HellFirePvP** [comment]
Next update adds a utility class which includes a ZenMethod which does the same as ItemHandle.getCrystalVariant:

`mods.astralsorcery.Utils.getCrystalORIngredient(boolean hasToBeCelestial, boolean hasToBeAttuned)`

Does exactly was ItemHandle.getCrystalVariant does and returns an IIngredientOR which matches against any crystal that fits according to the 2 boolean parameters.
