### ISSUE TITLE
Missing smelting recipe for Starmetal ingot - AS 1.8.9

### ISSUE THREAD

**Issue by count-chaos** [HellFirePvP/AstralSorcery#671]
The title basically explains my issue.

Unless I'm missing something (or missed some update related to this issue), the only thing I can do with Starmetal Ore is to grind it to dust. I've tried searching myself for that problem, if there's a conflict between Primal_Core/Primal_Tech and AS but alas...

So as long, as I can't smelt Starmetal into Ingots I'm unable to progress with the Mod.

**Comment by Doomgull** [comment]
What pack? What does JEI say if check the sourcing methods for starmetal ingots? This sounds like a conflict with another mod or pack config.

**Comment by count-chaos** [comment]
It's a Custom Privat Pack of about 60 Mods including the mentioned Primals, Thaumcraft 6, Botania, Embers,... (heavily Magic-focused). I've been waiting for the Thaumcraft 6-update for 1.12 before playing the pack, so it's though to narrow down the conflict to any specific mod.

JEI doesn't show any usage for the Ore, besides the Dust-Recipes.

But since it seems, as I'm the only one with this issue so far, I'll start loading single mods together with AS... I'll give you an update as soon as possible, and thx for the response.

**Comment by count-chaos** [comment]
There's nothing happening at all, like I said: the recipe for the ingot seems to be missing entirely. There's no gui whatsoever. Neither the Vanilla Furnace, nor EnderIO's smelter, nor Primal's stonegrill is shown.

**Comment by count-chaos** [comment]
Alright I've found the issue: the mod Charcoal_Pit does have the config "DisableFurnaceOre" - I didn't think this would apply to Starmetal as well.
