### ISSUE TITLE
[Suggestion] Add Starlight Field Item

### ISSUE THREAD

**Issue by thelapisfox** [HellFirePvP/AstralSorcery#673]
I checked the current suggestions list and didn't see this one suggested yet, so thought I would give it a try. Anyways, I am currently playing the Modern Skyblock 3 mod pack and made a fosic resonator. Unfortunately, I had to build platforms for almost an hour before I found a starlight field. I am thinking a creative mode item could be added that could be used to force place a starfield in a specified area (kind of like how other mods with special stuff adds items (i.e. Silent's Gems chaos nodes etc)). This would allow those whom play with this mod in skyblocks the ability to 'place' a starlight field in times of extreme unluckiness.

**Comment by HellFirePvP** [comment]
Due to the way the Skywave fields are generated, this is not possible. For further information, join our discord and lookup the pins in the starry-sky channel.
