### ISSUE TITLE
[Bug] Treasure Shrine is giving non smelted ores (was previously labled infinite?)

### ISSUE THREAD

**Issue by DarcClan** [HellFirePvP/AstralSorcery#674]
So I've been mining a treasure shrine under my house and it doesn't seem to match up with what I've found while googling it, (which is that it only spawns 200 blocks and only gives smelted results for ores if they have any)

Mine seems to be infinite and also giving me ore blocks for smeltable ores., This is with version 1.8.8

**Comment by Doomgull** [comment]
Not a bug. There's config options for both the minimum number of blocks it spawns before starting the RNG check to kill the shrine off, as well as the chance each mine after that point for RNG death.

There's also a config file (treasure_shrine.cfg) in the /astralsorcery subdirectory of the configs that lists what spawns, and it's weighting. This is generated on initial world start based on what is registered. This can be edited or replaced with another version of the configuration. If you pack contains ortes that are unsmeltable, that's not an AS issue if it shows up in the shrine, just remove the entry from the config.
