### ISSUE TITLE
Unable to finish crafting item required Iridescent Altar

### ISSUE THREAD

**Issue by useenzhekoay** [HellFirePvP/AstralSorcery#676]
As title said the items i tried such as Resonating Wand (Vicio) and Mantle of Stars (vanilla) when i try to craft them i been inform by altar that able to craft and R-Click with resonating wand. It start crafting (listen to the sound effect only) but it does not show any visual effect. But craft for other that does not require Iridescent Altar's level it able to show the effect. Is there any way to solve or other issues.

1st try, installed Optifine [OptiFine_1.12.2_HD_U_D1.jar]: Failed.
2nd try, remove Opticfine: Failed.

Pack Info: SevTech Ages v3.0.6 From Curse Forge
Launcher Used: MultiMC v0.6.2-1222
MC Forge v14.23.2.2651
AstralSorcery v1.8.5

Screenshot of Altar recipe (ForResonating Wand (Vicio))
![image](https://user-images.githubusercontent.com/5300396/39501182-ee725634-4deb-11e8-8539-62218e349363.png)

Screenshot of Astral Setup
![image](https://user-images.githubusercontent.com/5300396/39501238-4c93aac4-4dec-11e8-82a9-bd5851fbd99b.png)

Extra notes: The collector/enhanced collector seem do nothing as the altar starlight buffer is the same whether have or not having them.

Edit: The altar is built at the starlight source field that show by Fosic Resonator.

**Comment by Doomgull** [comment]
You're missing the relays for the extra items involved in tier 4 altar recipes (orbiting items). The Tome explains this requirement in the altar section.

If you need additional troubleshooting assistance, please come to the Discord server.

**Comment by useenzhekoay** [comment]
After try few possibles, found out that it just required more than just enough starlight for crafting. I added 2 more small setup of spectral relay to boost it in order to able see the light beam.
Yes, thank for reminding me. I know for the extra 4 items (orbiting) but i just could not see the light beam (other visual effect from altar after R-Click with wand) showing which item goes into which relay at first.
