### ISSUE TITLE
Step assist broken?

### ISSUE THREAD

**Issue by aridhol** [HellFirePvP/AstralSorcery#679]
I've been wracking my brain trying to figure out why the step assist perk from Vicio is not working for me - and as far as I can tell its just a bug? Maybe something recent, I don't know, but it just will not work. I've tested with and without tons of mods and the only thing I can come to is that Astral Sorcery may be the root itself

Is there any known issues with this with another mod or something by chance, maybe it is an interaction issue? Thaumcraft 6's step assist still works, but it seems like Quark's step assist is no good when Astral Sorcery step assist is supposed to be active

**Comment by aridhol** [comment]
Well, I look the time to figure out the commands and attune myself to vicio and level up to max and get my step assist with no other mods - works fine. There must be an interaction issue - but I can't seem to narrow it down. Anyone have any ideas?

Could it be a problem with Quark + Astral Sorcery together specifically? I'll do some more testing, hopefully I can narrow it down!

**Comment by Doomgull** [comment]
Knowing what versions of Minecraft, Forge, the other mods in the pack you're playing, would help. There haven't been any issues where there are conflicts reported with the step assists being disabled from other mods just because astral sorcery is in the back would it be possible to take a backup of the world, remove astral sorcery from the pack, and attempt to replicate?

**Comment by aridhol** [comment]
I think I've got it figured out - will report back after I've tested a bit more just so we have references if the issue pops up again. I am adding one mod at a time (tedious, let me tell you!!) so I can directly narrow down the conflict. I'm confirming it now..

**Comment by aridhol** [comment]
Culprit: Ice and Fire (dragons mod) - definitely is the cause of the problem. Why? Idk just yet, I'll be talking to the mod author in his discord from here on - sorry for thinking it was Astral Sorcery at first :P but if anyone else runs into this issue, this might help
