### ISSUE TITLE
Astral Sorcery Rock Crystal Configs

### ISSUE THREAD

**Issue by Vyraal1** [HellFirePvP/AstralSorcery#680]
Whoops sorry pressed "enter" too early.

On a fresh install of 1.8.9 -
```
        # Chance to generate the structure in a chunk. The higher, the lower the chance. [range: 1 ~ 2147483647, default: 0]
        I:Chance=0
```
is in the rock crystal worldgen section of configs, but looking at the source it seems like this config doesn't do anything?

https://github.com/HellFirePvP/AstralSorcery/blob/8611d9558db776cf74d96b0b9be3b1377a471ea0/src/main/java/hellfirepvp/astralsorcery/common/world/attributes/GenAttributeRockCrystals.java#L39

Maybe a typo?

**Comment by HellFirePvP** [comment]
derp
