### ISSUE TITLE
[Question] AS world retrogen

### ISSUE THREAD

**Issue by randomlypickedname** [HellFirePvP/AstralSorcery#681]
I recently pregenned a world, wasn't happy, and pregenned it again. What I didn't realize is if I didn't delete the AS data, it won't populate more structures. Is there a way to retrogen these structures or will I have to pregen again?

**Comment by Doomgull** [comment]
There's a retrogen option in the configs that may resolve this if you delete the AS data, but you may need a clean pregen, depending on results.

**Comment by randomlypickedname** [comment]
Thanks, skimmed right over this option when I scanned your config. I renamed the data folder and enabled the retrogen option, I'm using WorldBorder's fill option to force load chunks, and I see structures and ores forming as they should. Thanks for your help!
