### ISSUE TITLE
Formation wand with sooty marble shows hardly perceivable building guides

### ISSUE THREAD

**Issue by ZZaphodd** [HellFirePvP/AstralSorcery#687]
astral sorcery 1.8.9

most of building guides(phantom blocks?) with formation wand are easy to see.
but with sooty marble, very hard to recognize building range.

**Comment by Doomgull** [comment]
It's a low reflectivity black block that's see-through. There's...limits to that.

**Comment by Doomgull** [comment]
Not an issue anymore in 1.15+ changes.
