### ISSUE TITLE
[1.12.2] Conflict with Ender IO & Tinker's Construct: Unable to use Tinkers Arrows & Bolts/ Ender IO's Powered Dark Bow unless you have Vanilla Arrows in Inventory if using Astral Sorcery 1.8.9.

### ISSUE THREAD

**Issue by Z-Tunic** [HellFirePvP/AstralSorcery#688]
Minecraft: 1.12.2
Forge: 14.23.3.2673

Mods:
astralsorcery-1.12.2-1.8.9
Baubles-1.12-1.5.2
EnderCore-1.12.2-0.5.22
EnderIO-1.12.2-5.0.24
Mantle-1.12-1.3.2.24
TConstruct-1.12.2-2.10.0.75

-----
Steps:
1. Get a Tinkers Shortbow/Longbow/Crossbow
2. Get a Tinkers Arrow for the Shortbow/LongBow or Bolt for the Crossbow.
3. Hold Right-Click to pull the string back... only... you will begin pulling it back rapidly as if you were mashing the Right-Click instead of holding it down.
4. Get a Regular Vanilla Arrow and put it in your inventory. Make sure that your Tinker's Arrow/Bolt is in 'front' of the Regular Vanilla Arrow so it uses those instead of the Regular Vanilla Arrows. The Crossbow will skip the Regular Vanilla Arrow since it's not a Bolt.
5. Hold Right-Click to pull back the string... only this time... you actually pull the string back. Release to fire an arrow. If using a Crossbow you'll load it and have to Right-Click again to fire, which is intended.

This also effects Ender IO's Powered Dark Bow, where it won't be able to fire any arrows unless it's a Regular Vanilla Arrow. Spectral Arrows & Tipped Arrows will not work with either Bow/Crossbow. It might also possibility affect bows & such from other mods. Oddly enough... the unpowered Dark Bow doesn't have this issue nor does the Vanilla Bow.

-----
Note:
Now I dunno if it's Ender IO or Astral Sorcery causing this as removing either of the two mods allows Tinker's Construct Arrows & Bolts to function properly without needing to have at least 1 Regular Vanilla Arrow. Removing Astral Sorcery 1.8.9 allows Ender IO's Powered Dark Bow to work correctly with other arrows without needing to have a Regular Vanilla Arrow in your inventory.

However... if I downgrade Astral Sorcery to 1.8.8... this issue doesn't happen so I figure reporting it here might be the right place...?

**Comment by Doomgull** [comment]
#686
