### ISSUE TITLE
Let player link a lightwell and a containment chalice

### ISSUE THREAD

**Issue by ZZaphodd** [HellFirePvP/AstralSorcery#691]
I have a simple setup include two containment chalices.
One is dedicated to provide liquid starlight to starlight infuser, and another is consume liquid from lightwells.
But some of lightwells are bind to further chalice.(both cartesian, manhattan distance)

3 lightwells are working as I intended, but 2 lightwell are not.
![image](https://user-images.githubusercontent.com/8099421/39689006-f48fb5ac-520f-11e8-81b9-261920ded12b.png)

I read the page in astral, tome but there're no rule for connection between a chalice and a lighwell.

**Comment by Doomgull** [comment]
Collapsed into master list.
