### ISSUE TITLE
Bug report : Formation wand treats all variants of AS marble as base marble

### ISSUE THREAD

**Issue by Doomgull** [HellFirePvP/AstralSorcery#692]
Version astralsorcery-1.12.2-1.8.10

When using the formation wand to select blocks it works normally, but when selecting an AS marble variant other than the "base" uncrafted marble it acts as if the base marbl had been selected instead, placing it if you have it in your inventory and placing nothing if you do not, regardless if you have stock of the intended block.

Crossposting from mispost into MM git: https://github.com/HellFirePvP/ModularMachinery/issues/89

**Comment by Jandakast** [comment]
This also occurs with the Conversion wand. :)

**Comment by nitrous24** [comment]
I came here to create an issue similar to this but with the variants of stone/slabs and such. I assume this fix would fix that as well?  For instance, if i shift right-click andesite i would expect it would try to place andesite, but instead it tries to place normal stone.  If i shift right-click cobblestone stairs it tries to place normal stone slabs.  I don't wanna open an issue that already has a potential fix, so i figured i would ask here first.

**Comment by Doomgull** [comment]
Correct, all part of the same thing that has a fix in-dev.
