### ISSUE TITLE
"/as progress (playername) all" does not unlock sections of the astral tome

### ISSUE THREAD

**Issue by lag42** [HellFirePvP/AstralSorcery#693]

**Comment by Doomgull** [comment]
Can you provide the output of displaying their progress via command, or their <player>. astral file?

Are you certain you've spelled their name correctly, with proper case sensitivity? I routinely use this command for testing and have never seen this issue before.

**Comment by lag42** [comment]
It just outputted the success message and I am certain I used the proper case sensitivity, and where would I find this .astral file

**Comment by Doomgull** [comment]
In the playerdata folder for the world.

**Comment by lag42** [comment]
I checked there, so it didn't even appear for some reason which makes me wonder if progressing normally works now

**Comment by HellFirePvP** [comment]
progress levels != research levels. hence maximize exists. Progress only unlocks progress, not research

**Comment by lag42** [comment]
This issue is invalid then, I thought progress levels = research levels thanks for correcting me
