### ISSUE TITLE
Suggestion: Starlight Illuminator

### ISSUE THREAD

**Issue by Sorbe** [HellFirePvP/AstralSorcery#694]
The _Cave Illuminator_ is great!  How about a _Starlight Illuminator_ for the surface?
It would only need to provide enough light to get rid of the red/yellow X's from F7.
I would expect that the range could be boosted with a linked collector crystal.
I think that's the same level as a _Redstone Torch_, but that is conjecture.

Further, you could provide further upgraded illuminators at higher levels... 
say _Lunar Illuminator_ and _Solar Illuminator_ later, with more light levels/range later.

**Comment by HellFirePvP** [comment]
Seems overly unnecessary. If you want to light up large areas, there are other, existing solutions. On top of that, it would just add more clutter and being non-trivial.
