### ISSUE TITLE
Suggestion: More optical elements (not just mirrors)

### ISSUE THREAD

**Issue by Sorbe** [HellFirePvP/AstralSorcery#696]
Many of the colored mirror effects would be useful in more shapes than just rays.  How about some other optical elements such as spheres, square prisms, beam spreaders, collimators, etc.  that would make other AoE shapes like circles, squares, arcs, etc.

**Comment by HellFirePvP** [comment]
I can't see how this would add anything to the currently existing mechanical elements; Seems unnecessary.
