### ISSUE TITLE
Suggestion: Ritual effect area indicator

### ISSUE THREAD

**Issue by Sorbe** [HellFirePvP/AstralSorcery#697]
AS has a lot of very pretty graphical effects, but here is a pragmatic one.  It is difficult to guess where the precise area of effect is of a Ritual Altar or Ritual Anchor.  Perhaps if the altar had a Redstone signal, it could show the area of effect?

**Comment by Sorbe** [comment]
I'm done anyway.   Since the others were all rejected.

**Comment by Doomgull** [comment]
It's been considered previously, but won't be included at this time.
