### ISSUE TITLE
Ritual Altar and Lens in the Hunting Dimension

### ISSUE THREAD

**Issue by Sorbe** [HellFirePvP/AstralSorcery#698]
The _Ritual Altar_ works well in the Hunting Dimension, right up to the point where first _Lens_ are added.  In the overworld, the initial secondary beam appears from the _Ritual Altar_ right away.  In the Hunting Dimension, it sometimes only appears after I leave/re-enter the dimension.  And while I can put a _Lens_ at the correct spot and link it back to the _Ritual Altar_, no more secondary beams appear and no rainbow effect beams show up at all.

SevTech 3.0.6
Astral Sorcery 1.8.5
Java 8u172 x64
Window 10 Home
Client/Server SMP

It's worth noting that I have a similar setup working (with _Ritual Anchors_) in the Overworld.

**Comment by Sorbe** [comment]
![2018-05-07_18 17 09](https://user-images.githubusercontent.com/7958470/39732759-f225c752-5223-11e8-86b3-d5607004d85b.png)

**Comment by Sorbe** [comment]
Here is a screenshot of the working Ritual Altar in the overworld, with a Ritual Anchor.
![2018-05-07_18 26 54](https://user-images.githubusercontent.com/7958470/39732830-53361c90-5224-11e8-8de8-9fce9b62329f.png)

**Comment by Doomgull** [comment]
Is this in Single Player, or on a server?

**Comment by Sorbe** [comment]
Server

**Comment by Sorbe** [comment]
In both of the above cases, the Collector Crystal was visibly connected and supplying "extra starlight" if that is what you mean.  The images above confirm the visible connection to the collector crystals in both dimensions.  Or are you asking something else? 

This bug was solely intended for problems with even getting the Ritual Pedestal working in the Hunting Dimension.  I've broken, torn down, and reset all of the elements, and it never does anything further when the Lens is placed at the indicated spot and linked back to the ritual pedestal, even with a maxed out matching attunement collector crystal connected to the ritual altar.  I can provide screenshots of the ritual pedestal attuned crystal and the matching collector crystal if you like.

**Comment by Sorbe** [comment]
As a test... I unlinked the Collector Crystal from the Ritual Altar _and_ removed the Ritual Alter crystal as well.... here is what I see.
![2018-05-08_14 02 36](https://user-images.githubusercontent.com/7958470/39783025-ad37ab42-52c8-11e8-81d5-41bcb02f90ae.png)

**Comment by Sorbe** [comment]
The Dicidia effect is no longer functioning even though the altar is still showing graphics.

**Comment by Sorbe** [comment]
If I now break the Ritual Altar, put back the gem and relink, I get this.

![2018-05-08_14 09 36](https://user-images.githubusercontent.com/7958470/39783335-878da03a-52c9-11e8-9969-611f9819b76b.png)

Notice that the graphic for the secondary ray and the animated circle are missing.  This does give a Dicidia effect strictly within a 1 chunk radius (this base).  I have a LOT more dead bats to prove that :)

**Comment by Sorbe** [comment]
If I leave the dimension for a couple of minute, long enough for it to unload on the server, nothing seems to have changed visually.   Except Discidia Ritual Altar effect has stopped working... you can tell because the bat is flying around inside here freely without taking damage.

![2018-05-08_14 23 06](https://user-images.githubusercontent.com/7958470/39783946-97dd7a8a-52cb-11e8-8788-8563a66c85c6.png)

**Comment by Sorbe** [comment]
If I once again, leave the dimension, wait a few minutes to let it fully unload and then come back, I see this...

![2018-05-08_14 33 28](https://user-images.githubusercontent.com/7958470/39784341-e5ac55e6-52cc-11e8-96e7-1beafb4191f7.png)

The Ritual Altar is once again showing the ring graph and the white secondary ray, but Discidia is still not actually functioning, as proven by the bat flying near the altar.

**Comment by Sorbe** [comment]
Just to be very clear, this base in the Hunting Dimension has no chunk loaders or anything else like that.

**Comment by Doomgull** [comment]
Despite the difference in chunkloading, I'm going to mainline this one in with #413 since it is so similar.
