### ISSUE TITLE
Can't attune myself

### ISSUE THREAD

**Issue by Adamantion** [HellFirePvP/AstralSorcery#699]
I'm playing Crimson Skies pack. I was able to attune myself 4 times to: Evorsio, Discidia, Vicio and again Evorsio. After the last one, i can't do that anymore. I tried different constellations, tried breaking/replacing altar and structure, and even unlocked modpack to update to the latest version. When I place relays, I just get them connected and glowing, but when I step in, nothing happens

**Comment by Doomgull** [comment]
Assuming you can attune a crystal, and it's only player attunement that's in error, either remove Sponge from the server, or use the "/as help" command to see how to manually attune. Additional assistance can be provided on the Discord server for troubleshooting this, if needed.
