### ISSUE TITLE
[Config Request] Toggle for Worldgen Blacklist vs Whitelist

### ISSUE THREAD

**Issue by InjuredWolf** [HellFirePvP/AstralSorcery#700]
Currently, you can set a whitelist for dimensions for worldgen. A way to change this to a blacklist (for mods like RFTools Dimensions, etc.) while blocking specific dimensions would be really useful, as a pack maker.

**Comment by Doomgull** [comment]
I'm assuming the intent is to make it so all dimensions except a few will have worldgen without babysitting them.

**Comment by Doomgull** [comment]
Collapsed into master list.
