### ISSUE TITLE
doConstellationIteration crash loop

### ISSUE THREAD

**Issue by justinrusso** [HellFirePvP/AstralSorcery#702]
Reference: https://github.com/DarkPacks/SevTech-Ages/issues/2356

**Comment by Giovanni-NL** [comment]
Same thing happens on our server.  Modpack SevTech Ages version 3.0.7

Complete server crash log: https://pastebin.com/bDsaJX9p 

Crashes happen at irregular intervals. Sometimes you can play for hours before a crash happens. Other times there's several crashes in one hour. Always the same stacktrace. Crashes started to happen after we placed Celestial Gateways in the overworld and on the moon.
