### ISSUE TITLE
Mantle of the Stars - Vicio

### ISSUE THREAD

**Issue by Lunarclipse** [HellFirePvP/AstralSorcery#704]
Hello, I was playing FTB Revelations v 1.8.0 with a friend and we finally made the Mantle today and attuned it to Vicio. We were unable to fly and it seemed to have no effect. I downloaded the latest version of astral sorcery 1.12.2-1.8.10 and loaded it up and attuned the other mantel with Vicio, no flight still. Spawned one in creative and went back to survival and no flight. I saw a post back from I think November 2017 saying this was fixed in the next version but there is like 7 versions after November. Haaalp plz.

**Comment by Doomgull** [comment]
@Lunarclipse any followup to my above post? Need information or I'm closing this one this weekend.
