### ISSUE TITLE
Astral Sorcery and KUDA shader complications

### ISSUE THREAD

**Issue by MrKekster** [HellFirePvP/AstralSorcery#705]
(Re-copied from another forum)
Hi!

Im having issues with KUDA shaders and the astral sorcery mod specifically on a SevTech modded server. 

In the attached picture i am wearing mantle of stars which has particles flying around it. It can be seen that "shadowy squares" will occur for the particles as if it renders it badly. This happens for all astral sorcery related particles.

![2018-05-13_17 39 04](https://user-images.githubusercontent.com/39242033/39970714-89dcae14-56f0-11e8-846c-37efc09f0ab0.png)

I've seen streamers without this issue, dont know if they've already fixed it or if its a unique issue for me. Video settings for minecraft is set to "Fast" and shaders is set to "High". Everything else is default.

**Comment by Doomgull** [comment]
We don't support shaders. Try enabling the "weakSkyRender" config option in AS, that's as far as it goes (or will ever go) for compat.
