### ISSUE TITLE
Compact with The Betweenlands

### ISSUE THREAD

**Issue by Kiyaku** [HellFirePvP/AstralSorcery#706]
Heya,

i'm currently working on a modpack where the player spawns and stays in the betweenlands the entire time. I'd love to add some other mods, Astral Sorcery being one of them. Unfortunately no matter what time of day it is, the telescope display as if it was daytime. 

I was wondering if there would be a way to always allow the telescope (no matter of daytime), or allow it to work specifically in the betweenlands (i have the dimension on the whitelist in the config too). 

Wasn't sure if this would be something Astral Sorcery can add, or if The Betweelands would have to change how their day/night time works. 

-SC

**Comment by Doomgull** [comment]
The dimension has to have flowing time for any constellation stuff to work, and I believe the Betweenlands non-standard day/night time flow bypasses this portion of MC code.

It's unlikely to be resolvable without a major rework.
