### ISSUE TITLE
Ritual Pedestal multi block Extent?

### ISSUE THREAD

**Issue by ghost** [HellFirePvP/AstralSorcery#709]
The _Ritual Pedestal_ says it has a 9x9x2 multiblock, **but** it seems to quit working if **any** block impinges on a different and larger sized space.  

![2018-05-14_23 02 59](https://user-images.githubusercontent.com/7958470/40039521-8832afce-57cb-11e8-8490-a0b06d88930b.png)

The space that the _Ritual Pedestal_ actual monitors appears to be 7x7x4 -- any blocks placed within that extent prevent the _Ritual Pedestal_ from functioning.

![2018-05-14_22 58 32](https://user-images.githubusercontent.com/7958470/40039531-9150f0b6-57cb-11e8-9a2c-c4dd00f94ccc.png)
![2018-05-14_22 58 47](https://user-images.githubusercontent.com/7958470/40039532-91696218-57cb-11e8-84a6-99fe31e7d843.png)
![2018-05-14_23 13 31](https://user-images.githubusercontent.com/7958470/40039764-8d9e6614-57cc-11e8-9e82-68943be36236.png)

Please review this inconsistency and update the _Ritual Pedestal_ multiblock extent or the _Astral Tome_ multiblock description to show the actual extent.

Secondarily, please consider ignoring any blocks that don't actually block light, such as transparent blocks(_glass_) and even perhaps half-slabs, etc.

**Comment by Sorbe** [comment]
Did you notice the last screenshot, with the dirt arch directly over the width of the _Ritual Altar_, including directly over the center, yet the _Ritual Altar_ functions?  How does that jibe with your AS structures require "sky sight" requirement?

**Comment by Doomgull** [comment]
There's no light ring at the altar base, and no rays from the anchor. Doesnt look active to me.

**Comment by Sorbe** [comment]
The visual effects seem weird and misleading.   Here are the _Ritual Altar_ and the two linked _Ritual Anchors_ (with the blocking _Dirt_ arch) ... notice the green animations implying growth at both ends.  But there is no "Regen Buff" in effect, so the _Ritual Altar_ is not actually not working.

![2018-05-15_14 22 07](https://user-images.githubusercontent.com/7958470/40084579-679807f6-584c-11e8-9e23-2a45bde77207.png)
![2018-05-15_14 23 25](https://user-images.githubusercontent.com/7958470/40084580-67b5bad0-584c-11e8-9f1b-d8a363f78ede.png)

Now, if I take away the _Dirt_ arch, nothing changes on either end (still no light ring effect or rays either) but now the Regen buff appears at the linked destination _Ritual Anchor_.

![2018-05-15_14 24 40](https://user-images.githubusercontent.com/7958470/40084673-ca598590-584c-11e8-8e5e-6ffa7c071197.png)
![2018-05-15_14 25 34](https://user-images.githubusercontent.com/7958470/40084675-ca78493a-584c-11e8-9688-a87118a55156.png)

I think the _Ritual Altar_ & _Ritual Anchor_ are in need of a Test Suite World all by itself.  Not to even mention the other broken dimension use issues I already ran into.
