### ISSUE TITLE
Client crash unknown source

### ISSUE THREAD

**Issue by Saereth** [HellFirePvP/AstralSorcery#71]
FTB beyond modpack, As 1.1.5
https://hastebin.com/sudoboyoce.sql

Was just standing around mostly afk and this crash happened. Had an aevitas ritual running as well as tree beacon and cave illuminator all within render range

This happened at the same time that the server crashed from an unrelated issue (enderio/TE)

**Comment by HellFirePvP** [comment]
Believe it or not; same bigger issue as #37
