### ISSUE TITLE
pelotrio ritual working differently when anchored (SevTech 3.0.7/ Astral 1.18.10)

### ISSUE THREAD

**Issue by LordHellscream** [HellFirePvP/AstralSorcery#710]
Attempting to setup up a mob farm using Pelotrio ritual.
When using it without anchor, it works properly.
When it's anchored, it only spawn a specific type of mob (in the case of sevtech world -- fallen heroes).

Also, the ritual doesn't work when Armara ritual is activated nearby, suspect a buggy behavior.

Side question: is there anyway to reduce the ritual radius? (should i cut down size or purity?)

**Comment by Doomgull** [comment]
What is the biome that the original ritual is located within, and the biome the anchor is located within? Pelotrio is supposed to pull from biome info to set spawns.

Can you provide a screenshot of the Armara/Pelotrio interaction for placement/review?

The only way to modify the radius is to edit the config file and reduce it. Very few rituals have a radius that is effected by starlight, and those that do will provide a config option for how much starlight effects the radius. The rest just have a hard radius set in the configs.

**Comment by LordHellscream** [comment]
Both the dark room and the ritual pedestals are on the beach biome. the ritual pedestal for pelotrio are right next to the dark room structure, so it seems to spawn mobs inside the dark room even without anchoring. However, once I starting to anchor it (receiving end is on the ground level in the dark room), all it spawns are fallen heroes.

(will add screenshot when i get back home).

BTW, do you still need to keep 24 blocks away for things to spawn with Pelotrio ritual?

(As on title) SevTech version 3.0.7, Astral Sorcery version 1.12.2 - 1.18.10, (will add forge version when i get home),thanks

**Comment by LordHellscream** [comment]
Can you please tell me if the Pelotrio Ritual (for spawning hostile mobs) requires player to stay away from the immediate vicinity (like vanilla mob farm)?

**Comment by Doomgull** [comment]
It spawns from its own code set, with a frequency based on the amount of Starlight provided to it.

As a test, could you disable the ritual and use a piece of Nocturnal Powder in your darkroom and let me know what spawns out of it?

**Comment by LordHellscream** [comment]
https://imgur.com/a/N0ygsUJ
- first image is inside the dark room (i have nightvision on), the anchor is disabled
- 2nd and 3rd are the setup, the ritual pedestal on the right are for pelotrio, and the one on the right is for armara. the anchor toward the upper left corner of the 2nd image (near the horse) is the receiving anchor for armara (i moved it away so it won't push around animals in my base). All rituals are disabled.

I tried using a nocturnal powder in the dark room and it spawns 2 endermans, 1 zombie, 1 lava monster, and a skeleton.

**Comment by LordHellscream** [comment]
FYI, i did more testing, the ritual anchor actually worked for a short moment there, i thought it was fixed, but when i went on a trip and came back and started the anchor again it became bugged again (only spawn fallen heroes).

**Comment by Doomgull** [comment]
Looks like it's an issue with biome mob spawning lists because of the sevtech mob spawn gating with stages. Nothing we can really do on this end, unfortunately.

**Comment by LordHellscream** [comment]
how come it works different when it's anchored? if it's a problem with how mobs are spawned in the mobpack, wouldn't it work regardless of anchor or not?

**Comment by Doomgull** [comment]
The anchor replaces the ritual altar in the code when it gets linked, so a considerable potential number of things change that way. It's a proxy for all the ritual effects, maybe that matters for the way biome gating is handled for Mob spawns, the code literally just pulls from the existing biome list and repoint it to the new anchor though. Maybe it's an instance of when it updates biome list, maybe the way biome mob spawns are gated, maybe it's how the biome is getting called with the update for what's considered a valid spawn for the area. The method for how valid spawns are being determined based on the Modpack is what is at fault here.
