### ISSUE TITLE
Baubles Dependency not installing via Twitch Launcher with Astral Sorcery

### ISSUE THREAD

**Issue by Dragnier** [HellFirePvP/AstralSorcery#712]
As stated, I downloaded Astral Sorcery into a new mod setup and upon starting the game it warned me that I did not have the dependency Baubles required by Astral Sorcery. Probably a setting or something on Curse; but I figured I'd mention it.

Astral Sorcery Version - 1.12.2-1.8.10

**Comment by HellFirePvP** [comment]
1.8.10 and newer versions now will do that. It's something i forgot on the CF file. Should do it from now on.
