### ISSUE TITLE
GUI rendering bug apon opening Astral Tome

### ISSUE THREAD

**Issue by Katapow99** [HellFirePvP/AstralSorcery#713]
Everytime I open the guide book, my GUI gets this strange rendering bug that seems to be turning it into the liquid starlight texture, I tried removing all mods except Astral Sorcery yet it still persists, I've heard this is a known bug, just wanting to bring it up since it's still present as of 1.8.10
![2018-05-15_22 22 37](https://user-images.githubusercontent.com/23222326/40098121-b07cab06-588e-11e8-9a57-318f6e1335fc.png)

**Comment by Katapow99** [comment]
and I should mention that I am not using Optifine

**Comment by Doomgull** [comment]
When it happens with only Astral Sorcery installed, what else is running? QoL mods? Shaders? Forge version? Can I get a screenshot of your mods directory?

**Comment by Katapow99** [comment]
![screenshot from 2018-05-16 18-50-31](https://user-images.githubusercontent.com/23222326/40152443-10042abc-593a-11e8-83b2-7acb8cc73ea9.png)

It's minimalistic at best, mostly focused on mods about night which is why it bums me that AS isn't working properly, if required I can get a log, no shaders or resource packs, Forge version is 14.23.3.2680

**Comment by Katapow99** [comment]
Here is a simple log of me loading into a test world, opening the guide to cause the bug, then closing:
[latest.log](https://github.com/HellFirePvP/AstralSorcery/files/2011368/latest.log)

**Comment by Katapow99** [comment]
It may also be chalked up to my hardware, that's what I might settle on if there is no software-based fix.

**Comment by Doomgull** [comment]
Vampirism has a shader with a known conflict: #689

**Comment by Doomgull** [comment]
Try enabling the 'weakSkyRender' config option in the AS config, that's about as far as supportability can go for that one on our end.

**Comment by Katapow99** [comment]
Unfortunately this did not work, oh well, I can remember how to do Astral Sorcery decently without a guide, I can live without opening it, thank you for helping, Doomgull.
