### ISSUE TITLE
Horologium constellation with ritual pedestal does not get empowered

### ISSUE THREAD

**Issue by Twister1002** [HellFirePvP/AstralSorcery#716]
I'm trying to use a celestial crystal attuned to the constellation of Horologium inside my ritual pedestal. However when I shine a collector crystal on the pedestal, I do not get the same effects as from another constellation such as Discisia or Vicio. Meaning I do not get 5 extra lights to point at the pedestal to empower the effects.

I am running FTB Revelation V 1.8.0 with Astral Sorcery V 1.8.5

**Comment by Doomgull** [comment]
This would be better to troubleshoot the placement of everything in the Discord server with screenshots.

If this is single player, restart mc first to see if it resolves, because of issue 535.

**Comment by Twister1002** [comment]
Previously asked,  by "Doomgull": "What's the crystal in the entancement structure's attunement and stats? And what version of AS?" 

The crystal is a Celestial Collector Crystal, but I don't remember the attunement. The size was 900, cutting 100% and purity 100%

**Comment by Doomgull** [comment]
Attunements have to match, so that's really super important.

Again, Discord, not GitHub.
