### ISSUE TITLE
[1.12.2] Formation and conversion wands don't handle stairs and slabs correctly

### ISSUE THREAD

**Issue by gchpaco** [HellFirePvP/AstralSorcery#717]
When placing blocks with formation wands, they get placed in some weird orientation instead of what was specified.  This is in both 1.8.0 and the unreleased 1.9.0 with Baubles 1.5.2 and Forge 14.23.3.2655.

Reproduction steps: place stairs down in some orientation.  Shift + right click on stairs with formation wand.  Attempt to use them.

Preview: 
![2018-05-16_20 03 11](https://user-images.githubusercontent.com/17789/40151261-7256fd52-5944-11e8-8bf6-30535839845e.png)

Result:
![2018-05-16_20 03 16](https://user-images.githubusercontent.com/17789/40151265-774b7a68-5944-11e8-98d0-36cbd9f1062f.png)

Oddly, #703 fixes the *preview* but not the actual placement.  With that patch applied, the preview becomes:

![2018-05-16_19 59 04](https://user-images.githubusercontent.com/17789/40151273-823e3168-5944-11e8-9dbd-16a5d58cdda5.png)

But the result is the same:

![2018-05-16_19 59 08](https://user-images.githubusercontent.com/17789/40151279-898bcd9a-5944-11e8-9fa6-a876e27f58c8.png)

In neither case does the conversion wand permit changing stairs of one orientation into stairs of another orientation.

**Comment by gchpaco** [comment]
I'm not 100% sure about logs, but slabs will also pick a default orientation that is different from the one in the model block.  It's easiest to display with stairs.

**Comment by Ceifeire** [comment]
I'd like to tack on this if possible. The formation wand would not place logs outside of oak for me. I was using spruce and when i shift-right click it oak appears in the box and then tells me i have zero of the item i clicked even if im holding a few stacks of spruce.

**Comment by Doomgull** [comment]
Completely different issue, but also already fixed for next release.
