### ISSUE TITLE
[Suggestion] tinker's hammer and mantle

### ISSUE THREAD

**Issue by Ceifeire** [HellFirePvP/AstralSorcery#718]
Would it be possible to have the tinker's hammer be acknowledged by the evorsio attunement? At least for the speed boost. I enjoy my pickaxe mining faster than I can run and I was hoping to get a similar experience with my hammer but it doesnt seem to have gotten faster at all.

The mantle of the stars, was wondering if it would be possible to integrate it with baubles as accessory and not the chest slot. If its for balance purposes I am fine with it as is. But was hoping to wear it over my living armor.

**Comment by Doomgull** [comment]
Tinker's tools don't call normal tool code, so it would have to be a special edge-case support addition if that were to happen (unlikely). More likely for support if TiCon were to treat it like a pickax tool.

And no, the Mantle is a chest armor piece, like wearing a breastplate. It's not a cape.

**Comment by Ceifeire** [comment]
ok. I thought the mantle was a cape because when i was looking through the code at the effects of the attunements the code called it a cape. thanks for the answer.
