### ISSUE TITLE
Weird HUD Texture Glitch

### ISSUE THREAD

**Issue by FuriousXtremes** [HellFirePvP/AstralSorcery#72]
When I open the journal, the textures for my health, hunger, xp bar and crosshair get liquid starlight textures.
![image](https://cloud.githubusercontent.com/assets/22120759/24071461/56ed90da-0be3-11e7-87bb-2b77c431442e.png)

**Comment by FuriousXtremes** [comment]
HellFire, should I provide my computer specs if it is helpful?

**Comment by HellFirePvP** [comment]
i need to run some additional tests and stuffs (for which i didn't have time yet), but i don't think this is OS dependent. Modlist or pack name would be helpful i guess.

**Comment by FuriousXtremes** [comment]
Well, there is one issue, I tried this mod solo with only optifine and latest forge, the bug still happened. I kind of have that feeling it has to do with the mod itself probably conflicting with optifine somehow.

**Comment by WesCook** [comment]
I'd suggest toggling off some of Optifine's features to see if you can narrow it down further.  For instance I know the "Performance > Fast Render" option can cause some mod conflicts.

**Comment by ADBard** [comment]
I can confirm that turning off Performance > Fast Render fixed the issue for me. Optifine's own tool tip warns it sometimes causes graphics glitches

**Comment by RajehTXD** [comment]
i think it is fast render
