### ISSUE TITLE
Collector Crystal does not work in Hunting Dimension

### ISSUE THREAD

**Issue by justinrusso** [HellFirePvP/AstralSorcery#722]
I'd assume this is one mod conflicting with the other. Seems to be the only dimension so far that has been brought up as being an issue.

When a player tries to use the collector crystal to transmute iron ore into starmetal ore, it seems to just not work. Moving to the overworld instantly works.

**Comment by Doomgull** [comment]
You need flowing world time for anything involving starlight to work. Hunting dim doesn't have that. This is no different than trying to do Starlight transmutation in a dimension that's permanent night or permanent day with no world tick time passage.

Working as intended, really.
