### ISSUE TITLE
i am crashing using the lens

### ISSUE THREAD

**Issue by quindao** [HellFirePvP/AstralSorcery#724]
heres the crash report
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 5/24/18 3:36 AM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at hellfirepvp.astralsorcery.common.tile.network.TileCrystalLens.writeCustomNBT(TileCrystalLens.java:218)
	at hellfirepvp.astralsorcery.common.tile.base.TileEntitySynchronized.func_189518_D_(TileEntitySynchronized.java:65)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:288)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:273)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:182)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at hellfirepvp.astralsorcery.common.tile.network.TileCrystalLens.writeCustomNBT(TileCrystalLens.java:218)
	at hellfirepvp.astralsorcery.common.tile.base.TileEntitySynchronized.func_189518_D_(TileEntitySynchronized.java:65)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:288)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:273)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:182)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)

-- Affected level --
Details:
	Level name: astral aether
	All players: 1 total; [EntityPlayerMP['Quindao'/399, l='astral aether', x=1361.96, y=65.00, z=1319.62]]
	Chunk stats: ServerChunkCache: 678 Drop: 0
	Level seed: -1050248148
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-204,64,248), Chunk: (at 4,4,8 in -13,15; contains blocks -208,0,240 to -193,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 285733 game time, 19188 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 87410 (now: false), thunder time: 47031 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1264520616 bytes (1205 MB) / 2184708096 bytes (2083 MB) up to 3113877504 bytes (2969 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.3.2702 Optifine OptiFine_1.12.2_HD_U_D3 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                  | Version                 | Source                                          | Signature                                |
	|:--------- |:------------------- |:----------------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft           | 1.12.2                  | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | mcp                 | 9.42                    | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | FML                 | 8.0.99.99               | forge-1.12.2-14.23.3.2702.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge               | 14.23.3.2702            | forge-1.12.2-14.23.3.2702.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | actuallyadditions   | 1.12.2-r135             | ActuallyAdditions-1.12.2-r135.jar               | None                                     |
	| UCHIJAAAA | orbis_api           | 1.12.2-1.1.2            | orbis_api-1.12.2-1.1.2.jar                      | None                                     |
	| UCHIJAAAA | aether              | 1.12.2-1.0.5            | aether_ii-1.12.2-1.0.5.jar                      | None                                     |
	| UCHIJAAAA | astralsorcery       | 1.8.5                   | astralsorcery-1.12.2-1.8.5.jar                  | None                                     |
	| UCHIJAAAA | quark               | r1.4-123                | Quark-r1.4-123.jar                              | None                                     |
	| UCHIJAAAA | autoreglib          | 1.3-17                  | AutoRegLib-1.3-17 (1).jar                       | None                                     |
	| UCHIJAAAA | babyanimals         | 1.11-2                  | BabyAnimals-1.11-2.jar                          | None                                     |
	| UCHIJAAAA | baubles             | 1.5.2                   | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UCHIJAAAA | mantle              | 1.12-1.3.2.24           | Mantle-1.12-1.3.2.24.jar                        | None                                     |
	| UCHIJAAAA | jei                 | 4.9.1.190               | jei_1.12.2-4.9.1.190.jar                        | None                                     |
	| UCHIJAAAA | tconstruct          | 1.12.2-2.10.0.81        | TConstruct-1.12.2-2.10.0.81.jar                 | None                                     |
	| UCHIJAAAA | bhc                 | 1.1.1                   | baubley-heart-canisters-1.12.2-1.1.1.jar        | 7b14aaee2dd17b12a140baecab28948fff3a263f |
	| UCHIJAAAA | betterbuilderswands | 0.11.1                  | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| UCHIJAAAA | chameleon           | 1.12-4.1.3              | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCHIJAAAA | codechickenlib      | 3.1.3.313               | CodeChickenLib-1.12-3.1.3.313-universal (2).jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | doggytalents        | 1.14.2.314              | DoggyTalents-1.12-1.14.2.314-universal.jar      | None                                     |
	| UCHIJAAAA | ironbackpacks       | 1.12.2-3.0.8-12         | IronBackpacks-1.12.2-3.0.8-12.jar               | None                                     |
	| UCHIJAAAA | metamorph           | 1.1.5                   | metamorph-1.1.5-1.12.2.jar                      | None                                     |
	| UCHIJAAAA | oreexcavation       | 1.4.105                 | OreExcavation-1.4.105.jar                       | None                                     |
	| UCHIJAAAA | projecte            | 1.12-PE1.3.0            | ProjectE-1.12-PE1.3.0.jar                       | None                                     |
	| UCHIJAAAA | tinkertoolleveling  | 1.12-1.0.2b.DEV.1a79301 | TinkerToolLeveling-1.12-1.0.2b.jar              | None                                     |
	| UCHIJAAAA | xaerominimap        | 1.15.1                  | Xaeros_Minimap_1.15.1_Forge_1.12.jar            | None                                     |
	| UCHIJAAAA | xray                | 1.4.0                   | xray-1.12.2-1.4.2.jar                           | None                                     |

	Loaded coremods (and transformers): 
AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  
LoadingPlugin (Quark-r1.4-123.jar)
  vazkii.quark.base.asm.ClassTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Quindao'/399, l='astral aether', x=1361.96, y=65.00, z=1319.62]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_D3
	OptiFine Build: 20180515-125031
	Render Distance Chunks: 2
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1.0 - Build 8.15.10.2993
	OpenGlRenderer: Intel(R) HD Graphics
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by quindao** [comment]
plz help

**Comment by Doomgull** [comment]
Wha modpak, and how did you get that lens? It has malformed nbt. Trash it and replace it.

**Comment by Jo-Mamma75** [comment]
Having a similar issue on a FoolCraft 3 server with a player.  This player has had his entire playerdata reset and still get the following crash.
[https://pastebin.com/5tMUTnQv](url)

**Comment by Doomgull** [comment]
Again: the lens at that location has malformed nbt. How was it crafted, what stats does it have?

**Comment by Jo-Mamma75** [comment]
Just found out that it may have been pulled from a ProjectE Transmutation Tablet so that might be part of the reason since it technically wasn't "crafted".  The player did say that he could pull the same item from the creative menu and it was fine.

**Comment by Doomgull** [comment]
That's because the creative menu has proper nbt data. Any thing in AS that touches rock crystals, or anything eventually made from them, should be black listed from ProjE, tbqfh, because of nb isses.

**Comment by Jo-Mamma75** [comment]
Sounds about right.  Don't know if my issue is the same as @quindao 's issue though @Doomgull

**Comment by Doomgull** [comment]
Lenses don't error like this without something messing them up. Either a custom recipe in the pack, or another mod generating them does it. ProjE is in both packs, so sufficient for me.

**Comment by quindao** [comment]
useed commands to spwan it for testing

**Comment by quindao** [comment]
so don't get them with commands use jei cheat mode good to know

**Comment by quindao** [comment]
and thanks doomgull this was my first git hub post and you guys are cool

**Comment by quindao** [comment]
and Jo-Mamma75 it is probly not my pc cant run foolcraft any of them :(
