### ISSUE TITLE
Data storage slightly breaks behavior of `/whitelist list`

### ISSUE THREAD

**Issue by digitallyApocalyptic** [HellFirePvP/AstralSorcery#726]
Because Astral Sorcery stores its data files (an additional two per player that it's seen) in the `playerdata` directory of the world folder, and because Minecraft itself uses the number of files in that folder as a way of checking how many users have been seen on the server, using `/whitelist list` on a server with Astral Sorcery installed will yield incorrect results. For example, on my server:

![powershell_2018-05-24_22-00-52](https://user-images.githubusercontent.com/21273522/40525639-7fc48ad0-5f9e-11e8-8308-304a2d6a7aa1.png)

May also break other commands that display the number of seen players. Figured that it's unlikely for this to be fixed, since that would involve greatly changing the paradigm of stored data in a backwards-incompatible way, but I at least wanted to flag it.

**Comment by HellFirePvP** [comment]
Requires some delicate rewrite of the data handling where research data is read & saved. The actual impact of it seems rather small as testing shows. Would rather not touch it while we're still in the same mc version between updates. Will be fixed/tended to for the mc 1.13 update when/if that hits.

**Comment by HellFirePvP** [comment]
Adressed this for AS 2.0 - Will be fixed whenever that comes out....

**Comment by HellFirePvP** [comment]
That being said, the data storage has been rewritten for the 1.14 version of the mod, so. this issue will cease to be a problem from thereon.

**Comment by HellFirePvP** [comment]
Fixed in 1.14, will not be addressed in 1.12
