### ISSUE TITLE
Pelotrio doesn't add Infinity to bows; Infinity and Lure to books at Stellar Refraction Table

### ISSUE THREAD

**Issue by PhoReaper** [HellFirePvP/AstralSorcery#727]
I'm playing SevTech Ages 3.0.7 which is running Astral Sorcery-1.12.2-1.8.10.

**Comment by Doomgull** [comment]
What bow, what does it actually add, and were they didabled for the pack/gated?

Also, vanilla mc makes certain enchants naturally incompatible, so knowing what was already on the bow/what was added is important here.

**Comment by PhoReaper** [comment]
An unenchanted Vanilla bow received Mending III only, an unenchanted vanilla fishing rod received Mending III and Lure VI (my memory might be off on this power of this enchantment?), and a book received Mending III only. I'm in age 5 so past any relevant gates. I had a look at https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/registry/RegistryConstellations.java and noticed that some constellations further down have .setIgnoreCompatibility() , so maybe that's missing for Pelotrio?

**Comment by HellFirePvP** [comment]
Indeed, Infinity can't be applied together with mending. Mending will be removed from pelotrio in the next update.
