### ISSUE TITLE
Resonating wand (Aevitas) stuck in air blocks

### ISSUE THREAD

**Issue by miofferg** [HellFirePvP/AstralSorcery#728]
I'm currently playing sevtech ages and i noticed that when im running around with the aevitas wand and a mob hits me i sometimes get stuck in those helper blocks which then makes me unable to move until i unequip the wand.

**Comment by HellFirePvP** [comment]
Uh. yea. happens. Not tooo terribly much i can do and/or am willing to do against it as it's only some occasional problems.
