### ISSUE TITLE
[Suggestion] WeakSkyRenders Syntax

### ISSUE THREAD

**Issue by MokahTGS** [HellFirePvP/AstralSorcery#73]
Can you please give examples in the config of what syntax is used with the weak sky renders config to get the mod to work with Botania's GoG skybox?

**Comment by HellFirePvP** [comment]
same as 'skySupportedDimensions'. The comment on the config option also tells you that it's a list of dimension ID's

**Comment by MokahTGS** [comment]
Simply putting 0 in the weak sky renders config area does nothing.

**Comment by Saereth** [comment]
Can you provide a copy of your config and a screenshot of it not working please.

**Comment by MokahTGS** [comment]
Config setup:

# Whitelist of dimension ID's that will have special sky rendering + constellation handling (and thus starlight collection, ...) [default: [0]]
    S:skySupportedDimensions <
        0
     >

    # Defines how much the 'sharpened' modifier increases the damage of the sword if applied. Config value is in percent. [range: 0.0 ~ 10000.0, default: 0.1]
    S:swordSharpenedMultiplier=0.1

    # IF a dimensionId is listed in 'skySupportedDimensions' you can addAmount it here to keep its sky render, but AS will try to render only constellations on top of its existing sky render. [default: ]
    S:weakSkyRenders <
        0
     >
}

If the syntax is wrong, please inform me of how it should be setup.

**Comment by MokahTGS** [comment]
Alright, with the latest version (1.2.3 beta) and the above config setup, I have confirmed that the mod does work with Botania's Fancy Skybox.

Screenshot: https://www.dropbox.com/s/x8ciom1dk5zkx31/2017-03-20_09.39.56.png?dl=0
