### ISSUE TITLE
Conversion Wand does not work with chiseled blocks

### ISSUE THREAD

**Issue by natanfudge** [HellFirePvP/AstralSorcery#730]
If you try to use the conversion wand with chiseled blocks (i.e. you try to replace blocks with chiseled oak wood planks) it will always appear at the top left as if you just copied the original block (oak wood planks in this case) and that you have none of it. This means you can never use the conversion wand with chiseled blocks.

**Comment by Doomgull** [comment]
#692 will be fixed next version
