### ISSUE TITLE
Bug/Issue with Hiking Boots and Dimensions

### ISSUE THREAD

**Issue by superbrotherx4** [HellFirePvP/AstralSorcery#733]
Dearest readers,

I have seen other threads on issues with changing dimensions, and I have only seen one with hiking boots.

I am currently playing ATM Expert Remastered, and am attuned to Vicio.

I have all of the perks, and I love them all. However, the hiking boots stop working when I enter the Nether.

I had, at first, assumed this was intended because you can't see the stars in there, but the other perks worked still.

Going back to the overworld doesn't help. The other perks work great and hiking boots don't work.

I have seen something like this with xp, but that can be fixed by simply gaining some extra xp.

I know backing out of the world and entering back in fixes the issue, but my computer is rather slow and I try to avoid that as much as possible. Is there any other method to possibly fix this issue?

I love this mod, and can't wait to see where it ends up. Thank you for your time.

    Superbrotherx4

**Comment by Doomgull** [comment]
Unfortunately because its the 1.10 version of the mod, no. Other fixes have been applied in 1.12.2 versions, to varying degrees of success, but the 1.10 and 1.11 versions of AS are no longer supported.

**Comment by superbrotherx4** [comment]
I am thankful for your reply. I am very interested in the mechanics of mods and was wondering, what causes these issues after changing dimensions? What causes them to break?

**Comment by Doomgull** [comment]
Ultimately, it has to do with how Minecraft itself handles transitioning between Dimensions. Players have some special code involved that make things work a little bit better, but it's still kind of weird. A lot of mods' step assist stops working when transiting between dimensions for the same reason.
