### ISSUE TITLE
Celestial Gateway not showing all locations

### ISSUE THREAD

**Issue by IainVM** [HellFirePvP/AstralSorcery#734]
In the overworld of my SevTech 3.0.7 pack we have 4 Celestial Gateways. 
```
A
 \
  B - C
   \
    D
```

When I'm at A I can see B and C but there's no star for D.
When I'm at D I can see A and C but there's no star for B.

So it's not dependant on distance (which would make sense in my opinion), since the further gateway is visible at D. Neither is it which gateway is placed last, since I replaced B and it made no difference.

**Comment by Doomgull** [comment]
It not showing overlapping gateways is intended. The order of display may be a bug, will check.

**Comment by HellFirePvP** [comment]
Will now always pick the closest.
In your example: at D you'd see B and no A, at A you'd see B but no D.

**Comment by IainVM** [comment]
The fact that these teleporters are at players bases and 1000 blocks away makes it difficult to offset them, though the always picking closest means consistent and predictable behaviour.
