### ISSUE TITLE
Amara infusion perk phoenix blessing causes dupe

### ISSUE THREAD

**Issue by apricot2** [HellFirePvP/AstralSorcery#736]
On sevtech version 3.0.7 i was killed by a anti-creeper while holding a parrot and it activated phoenix blessing which duped my items into a grave

**Comment by Doomgull** [comment]
What does the parrot have to do with it?

And that sounds more like the grave mod not handling a death event cancel properly.

**Comment by Doomgull** [comment]
Also, Phoenix just prevents you from dying. It doesn't cause graves to spawn or the like.
