### ISSUE TITLE
Crash when placing Tree Beacon

### ISSUE THREAD

**Issue by BluMasc** [HellFirePvP/AstralSorcery#737]
I'm Playing a selfmade modpack and after Placing a Tree Beacon, the game crashed.
Every time i tiry to reopen it it crashes again.
Here is the crashlog:
[https://pastebin.com/FD0D1EeW](url)

I Played with this mods:
https://pastebin.com/GrKAhvLk

**Comment by Doomgull** [comment]
Going to need a little bit more information, if possible. If you make a backup of your world, and remove roughly half of the mods, and attempt to launch again and see if it still crashes the same way, this can be useful in narrowing down which mod is causing the issue with the list. If it doesn't crash, add in some of the other mods until you can figure out which one causes the tree vegan list to crash on world start. If it does crash, remove 50% of the remaining mods, until you can start the pack with astral sorcery, and whichever other mod is resulting in this problem together.

**Comment by BluMasc** [comment]
ill do that and tell you my results

**Comment by BluMasc** [comment]
i tried to remove half and add mods back in till the crash hapens again, but even after adding every mod back in i did not get the crash anymore.
I gues the mod, that was causing it had an update that fixed it on their side.

**Comment by Doomgull** [comment]
Okay. Update the ticket again if it triggers, but otherwise I'll keep the ticket open until the weekend before closing it in case it repeats.
