### ISSUE TITLE
Making a Telescope

### ISSUE THREAD

**Issue by AlphonseVaher** [HellFirePvP/AstralSorcery#738]
Shrine: https://gyazo.com/8279c362cb85214dae17b096307918d7

Table: https://gyazo.com/f494493067feae7ba353a3b6faf0244a

So I am working on Sevtech ages with my brother, lots of fun, However, I am running into an issue with making a Telescope. You can see the Setup above, and the Recipe in the table, Amount of starlight within ect. 

(Made the whole thing survival, Used an existing crater, Bucketed up TONS of the Star liquid, Lovely)

The table is working, No red bar, I have seven spectral relays pushing light into the table in the center (All partical effects flowing towards the table), The Recipe is EXACTLY right, No odd wooden planks or sticks here. 

But it won't produce a telescope.

It CAN produce other things, But I am able to make other things on it. What am I doing wrong here?

Edit: And it is in a high-intensity star field. https://gyazo.com/aa0f3b65285358c0522a0b1ba90b5935

**Comment by Doomgull** [comment]
yup, or have a Scroll of Written Expertise shared from him to you so you've got parity in progression.
