### ISSUE TITLE
Crash while being pretty lazy, sorry Hellfish (Knowledge Sharing Paper in XU2 Mech User)

### ISSUE THREAD

**Issue by Vyraal1** [HellFirePvP/AstralSorcery#740]
Context: I was trying to unlock the required research so the mechanical user could autocraft using the Iridescent Altar, so I gave it a Knowledge Sharing Paper and ended up crashing the server.

https://hastebin.com/unotumaqij.pl

Link to XU2 issue thread.
https://github.com/rwtema/Extra-Utilities-2-Source/issues/109

**Comment by Doomgull** [comment]
Flagging as uncertain because may or may not be fixed as intentional to prevent non-real player usage...

**Comment by ruifung** [comment]
But at the very least, should at least stop it from crashing the game. Because this could be done, on a server to crash it until the forge option to remove erroring tile entities is enabled.

**Comment by Doomgull** [comment]
That would be on exu's side, it's the source of the ticking entity.

**Comment by HellFirePvP** [comment]
Knowledge will not be given to fakeplayers anymore.
