### ISSUE TITLE
Destroying Celestial Gateway while still standing on it leaves everything dark

### ISSUE THREAD

**Issue by Mijago** [HellFirePvP/AstralSorcery#742]
When I step on the Celestial Gateway, everything works as expected.
I just broke it (using a Tinker's Hammer) while standing on it. The sphere disappeared, but the dark effect is still here, so I can not see anything.

Mod Version "1.12.2-1.8.10"

I can not give any more information, I guess, but I hope this still helps.

**Comment by Doomgull** [comment]
Why did you do that?

**Comment by Mijago** [comment]
Because I wanted to move it.

**Comment by Doomgull** [comment]
Was it broken using the center of the Hammer's area, or the edge?

**Comment by Mijago** [comment]
So, I was standing on the center, moved about a block (I still saw the sphere).
Then I used the Hammer to remove one corner of the ground. 
The center of the Hammer was here:

```
XXXXXXX
XOXXXXX
XXXXXXX
XXXXXXX
XXXXXXX
XXXXXXX
XXXXXXX
```

After the 9 blocks were mined, the sphere disappeared but the world still stood dark.
(I checked twice, it was in the middle of the day)

**Comment by HellFirePvP** [comment]
It disappears when moving away from it. If not, then the hammer doesn't cause tileentities to disappear on clientside which is a big problem and should be reported to the respective mod doing the blockbreaking.
