### ISSUE TITLE
[Suggestion] Celestial Gateway effects

### ISSUE THREAD

**Issue by Iorce** [HellFirePvP/AstralSorcery#743]
## Context
First off: I LOVE the way the Celestial Gateway interacts.
However, the black starfield sphere feels a bit choppy when it intersects blocks or hits the ground.

## Suggestion
Would it be possible to maybe add a blindness effect that fades blocks out the further they're away from the player or make blocks gradually appear transparent (like Illumination Wand but less glowing)?

Maybe a gradual fade-out of the sphere when it's about to hit the ground/the level the player is standing on?

It would make the Celestial Gateway feel even more immersive.

Also, big thumbs up for all the effects (I felt especially amazed when I saw the Iridescent Altar appear)

**Comment by Doomgull** [comment]
Collapsed into master list.
