### ISSUE TITLE
Celestial Crystal disappears from Ritual after relog in single player

### ISSUE THREAD

**Issue by Yadokingu** [HellFirePvP/AstralSorcery#745]
astralsorcery-1.12.2-1.8.10
forge-14.23.4.2707

When I relog in my world the celestial crystal from rituals disappears. When I shift-rightclick the ritual pedestal I get the crystal back and can replace it.

Edit: After replacing the crystal it also disappears when I go out of render distance of the chunk where the ritual is in, despite the chunk being loaded with a weirding gadget.
Only breaking and replacing the ritual pedestal fixes this, but that also means that all the leneses have to be replaced.

before relog:
![2018-06-11_22 23 54](https://user-images.githubusercontent.com/11133215/41255565-3bc02d30-6dc7-11e8-9366-68797d81ce3d.png)

after relog:
![2018-06-11_22 25 23](https://user-images.githubusercontent.com/11133215/41255566-3be806f2-6dc7-11e8-9022-aa55c0ba1cd0.png)

crystal shifted out:
![2018-06-11_22 25 36](https://user-images.githubusercontent.com/11133215/41255568-3c09f26c-6dc7-11e8-937f-d8a08157c2cb.png)

crystal replaced:
![2018-06-11_22 25 47](https://user-images.githubusercontent.com/11133215/41255569-3c32b5f8-6dc7-11e8-8626-85027fcec750.png)

**Comment by Yadokingu** [comment]
It's not just a rendering bug. The ritual also doesn't work when it's in that state. Maybe I should have been more clear about that.

**Comment by Doomgull** [comment]
Unrelated issue, and already has a ticket open for that. Not displaying the crystal is the bug for this ticket.
