### ISSUE TITLE
[1.12.2][1.9.0] Startup crash with Astral Sorcery, Erebus and NEI

### ISSUE THREAD

**Issue by SassyCultist** [HellFirePvP/AstralSorcery#747]
This crash occured on startup and I'm not sure which mod is the exact issue. However, I think it started with the new Astral update.

https://pastebin.com/8VWwX2hf

[Erebus Issue](https://github.com/ganymedes01/TheErebus/issues/624)
[NEI Issue](https://github.com/TheCBProject/NotEnoughItems/issues/161)

Minecraft Forge: 14.23.4.2705
Astral Sorcery: 1.9.0
Erebus: 1.0.2332
NEI: 2.4.1.233

**Comment by Doomgull** [comment]
Received same error once, but was unable to reproduce any time after initial launch.

**Comment by zEpiixz** [comment]
getting the same error

**Comment by Doomgull** [comment]
Issue is on Erebus side, it appears.

**Comment by Rongmario** [comment]
Happens here but don't crash: https://pastebin.com/8VWwX2hf

**Comment by Doomgull** [comment]
That still lists erebus.

**Comment by Rongmario** [comment]
Sorry, wrong link; updated with correct ones.

**Comment by Doomgull** [comment]
Should open a ticket on VFP's github, then. AS is just triggering it, it's not the source. VFP's having unhappy times.

**Comment by Doomgull** [comment]
Collapsing to new master tracking ticket for the incompatibilities: #762 

Please watch that thread for more updates/known issues.
