### ISSUE TITLE
Startup crash with Mekanism

### ISSUE THREAD

**Issue by lebanni** [HellFirePvP/AstralSorcery#748]
MC 1.12.2
Forge 14.23.4.2707
Astral Sorcery 1.9.0
Mekanism 9.4.11.346

[crash-2018-06-13_02.17.36-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/2096199/crash-2018-06-13_02.17.36-client.txt)

**Comment by Doomgull** [comment]
Possibly related to 161.

**Comment by Doomgull** [comment]
Can't reproduce on my system:
AS 1.9.0
Mek 9.4.11.346
Forge 14.23.4.2707
Baubles 1.5.2
JEI 4.10.0.198
The One Probe 1.4.23

**Comment by Doomgull** [comment]
Duping to #749, same source mod issue: Mek.
