### ISSUE TITLE
Central attunement relay for Aevitas attunement conflicts with altar position

### ISSUE THREAD

**Issue by gchpaco** [HellFirePvP/AstralSorcery#75]
When attempting to attune to Aevitas, one of the relays wants to be placed on the central altar, which obviously won't work.  I think this is probably the problem:

`sl1 = aevitas.addStar(15, 14); `

15 and 14, rounded down, are both 7, which means they get assigned coordinate 0,0.

**Comment by HellFirePvP** [comment]
How about actually trying it before filing a bug report?

**Comment by gchpaco** [comment]
Proof that this will work with some array (Holorogium, as it happened)
![2017-03-21_22 33 50](https://cloud.githubusercontent.com/assets/17789/24183681/196ae982-0e87-11e7-8767-1310912b6a8a.png)
Same array with Aevitas
![2017-03-21_22 37 10](https://cloud.githubusercontent.com/assets/17789/24183680/19695702-0e87-11e7-9d25-c986afc97733.png)
From above, demonstrating that I filled everything.  ![2017-03-21_22 39 06](https://cloud.githubusercontent.com/assets/17789/24183707/3c033c9c-0e87-11e7-8694-9b2f4a75edd0.png)

**Comment by gchpaco** [comment]
The version is 1.2.3-beta, I had discovered Aevitas in the sky, and I verified with a telescope that it was visible that night.

**Comment by PG-Fuury** [comment]
I have a repeat of this problem in current FTB:Revelations

**Comment by Doomgull** [comment]
No, you don't. The altar is a relay.

**Comment by PG-Fuury** [comment]
I have placed eight of the relays at the positions indicated by the constellation paper in my offhand, with the ninthbeing the Altar

**Comment by Doomgull** [comment]
doesn't change that it's not related to this ticket. Go to the discord server, to the appropriate channel, someone there can assist if you can provide screenshots.

**Comment by PG-Fuury** [comment]
I haz teh dumbz, aevitas was not in the sky
