### ISSUE TITLE
Crash report from updating the mod

### ISSUE THREAD

**Issue by JoeSGT** [HellFirePvP/AstralSorcery#750]
https://pastebin.com/raw/0nYqdzEb
so today i just update the mod to `1.12.2-1.9.0`
and when i took out this mod i don't get any crash i am unsure very odd bug

**Comment by Doomgull** [comment]
Need more of the error, what was above that point? This looks like something else is casting to the amulet, not that the amulet is the source.

**Comment by JoeSGT** [comment]
https://pastebin.com/raw/YnP3Yqmb
It seem with this mod install and lucraftcore mod together cause the crash. Here a link to the mod https://minecraft.curseforge.com/projects/lucraft-core

**Comment by Sacrificialgaming** [comment]
https://gist.github.com/Sacrificialgaming/29c296450413a64d59855bc814c59785

According to this crash log, it's now crashing with cyberware aka Robotic parts

**Comment by Doomgull** [comment]
#749, then.

**Comment by JoeSGT** [comment]
@Doomgull  what made you think it's the other mod fault when in the crash report it does not mention any lucraftcore mods in addition it seem that it's having issues with other mods. Just make things look odd

**Comment by Doomgull** [comment]
1. It doesn't occur without lucraft in.
2. Lucraft has some weird failures to properly set it's domain in the logs.
3. AS doesn't attempt to append energystorage onto the amulet capability, but lucraft attempts to add quite a few things via it's modules.
4. I would have said remove sponge to make sure it wasn't an ASM conflict, but it's not present in your second crashlog so there should be no problems there, either.
