### ISSUE TITLE
Crash after updating 

### ISSUE THREAD

**Issue by kave777** [HellFirePvP/AstralSorcery#751]
I have updated AstralSorcery and there is crash while loading 
logs - https://paste.ee/p/2pMHH
crash - https://paste.ee/p/EGgYN

**Comment by Darkmega18** [comment]
got this one too.

**Comment by HellFirePvP** [comment]
Duplicates #746

**Comment by Darkmega18** [comment]
it's not from ancient warfare tho? I don't have that mod.

**Comment by Darkmega18** [comment]
[crash-2018-06-13_22.22.40-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/2098703/crash-2018-06-13_22.22.40-client.txt)
and then I realized that it keeps going, unlike kaves which stops after it nulls. mine seems to go on about some other stuff. Here. Sorry if you don't like direct upload. :V
