### ISSUE TITLE
[1.9.0] Startup crash with NEI

### ISSUE THREAD

**Issue by wormzjl** [HellFirePvP/AstralSorcery#754]
Happens after update
Crash log: https://gist.github.com/wormzjl/3b381e92f7e373f90be35dfde0b99358
Which didn't tell much, so here is the full log: https://gist.github.com/wormzjl/99a766bb6a92279e0e18a6b9dfd215e9

**Comment by Doomgull** [comment]
#746, and eventually #749 based on mod list.

**Comment by wormzjl** [comment]
I don't have both mod through

**Comment by Doomgull** [comment]
Too many crash logs opens at once >.<

Going to need to try a binary test method to see when it doesn't trigger.

**Comment by wormzjl** [comment]
After disabling NEI it no longer crashes

**Comment by Doomgull** [comment]
NEI is just exposing it, it seems. Someting else in there is triggering it fro another mod involved, as NEI and AS alone doesn't cause it. Check the ticket ligands linked above for ther possible mods involved so far that have been found to need to address.

**Comment by Doomgull** [comment]
Collapsing this to new master ticket for tracking the incompatibilities until resolved: #762 

Please check the listed mods there and confirm if still present after testing with that information.

**Comment by wormzjl** [comment]
Confirmed to be an ic2 issue
