### ISSUE TITLE
Aquamarine shale is no where 

### ISSUE THREAD

**Issue by kmork1** [HellFirePvP/AstralSorcery#756]
Aquamarine shale isn’t naturally occurring in my world. Playing the direwolf20 1.12 pack v 1.11 and updated astral only

**Comment by Doomgull** [comment]
Astral didn't change the aquamarine shale or world placement code with the version change, so...

**Comment by kmork1** [comment]
Also rocky crystal ore

**Comment by Doomgull** [comment]
Check your configs, they shipped a version where rock crystal spawning was disabled.
