### ISSUE TITLE
Conflict between Ancient warfare and Astral Sorcery version 1.9.0

### ISSUE THREAD

**Issue by Winddbourne** [HellFirePvP/AstralSorcery#757]
This crash only happens with the newest version of astral sorcery released yesterday (6/12/18), moving back a version lets my pack load properly again.

[crash-2018-06-13_13.28.41-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/2099228/crash-2018-06-13_13.28.41-client.txt)

**Comment by Doomgull** [comment]
#746 

It was even left open so duplicates wouldn't be created!
