### ISSUE TITLE
[1.12.2] [1.8.10 + 1.9.0] Ritual Pedestal causes extreme amounts of chunk updates

### ISSUE THREAD

**Issue by Spikeddragon** [HellFirePvP/AstralSorcery#759]
I originally noticed this in the Sevtech Ages modpack (As of update 3.0.8 it uses Astral Sorcery 1.8.10) where my base would get up to 100+ chunk updates causing my memory to be eaten up quite quickly. After removing most machines, I found out that the Ritual Pedestals (even when not active) can cause plenty chunk updates. One pedestal causing 20, a second causing 50, and a third bumping it up to 90-100 (For note, the pedestals weren't too far away from one another ~15 block distance max). I made a modpack with only Astral Sorcery 1.9.0 (and baubles as it was installed along side it). Going into a fresh save (waiting for the world to load around me of course) caused the same effect to happen.

I am aware that the Ritual Pedestal works in a large AOE effect but I don't know if all the chunk updates are intended or not.

**Comment by Doomgull** [comment]
Can you run some JVM profiling on it and upload the results for additional review?

Were these empty ritual pedestals, or did they have an attuned crystal inside them?

**Comment by Spikeddragon** [comment]
I'm not familiar with JVM profiling so some instructions would be nice. I tested with empty ritual pedestals, empty ritual pedestals on the marble structure under it, and active ritual pedestals. The chunk updates were consistent throughout them all.

**Comment by Doomgull** [comment]
Would recommend using visualvm for it, there's several good tutorials with video out there, but also the docs for it: https://docs.oracle.com/javase/8/docs/technotes/guides/visualvm/profiler.html

**Comment by Spikeddragon** [comment]
I've been able to begin profiling the client but the game crashes at about 50%. Do you know anything that could be causing it?

**Comment by Doomgull** [comment]
Wait to start the profiling until it's running. Likely a resource availability issue.

**Comment by Spikeddragon** [comment]
I started profiling when I was in the world. Should I start before I enter the save?

**Comment by Doomgull** [comment]
Hmm, no once you're in the world should be enough. I'll see if I can replicate on my end.

**Comment by HellFirePvP** [comment]
Not sure what's happening for you, i can't see this happening both in dev, in dev with dedicated server, in a forge environment out of dev with just AS and forge. https://i.imgur.com/6UigWLb.png

**Comment by Spikeddragon** [comment]
This is what happens on my end. The world is completely empty and the only mods are Astral Sorcery 
(1.9.0) and Baubles. https://i.imgur.com/KW372RK.gifv

**Comment by MrNinja93** [comment]
So I tested this and also got the chunk update spam but I noticed Hellfire's screenshot was an older Forge version so tested with a bunch of different forge versions and lo and behold it looks to be something caused by a forge/Astral interaction.

Narrowed it down to being caused by Forge 2684-2686 (bugged commit in the same versions that insta crashes so can't narrow it down further... ) Hopefully this helps track down the cause and get it fixed.

**Comment by HellFirePvP** [comment]
Yes it seems to be something happening on a newer forge version. Trying to find out where/why it happens.

**Comment by HellFirePvP** [comment]
Actual critical information: Does this only happen in Singleplayer by any chance?

**Comment by Spikeddragon** [comment]
Using forge 2708 and astral sorcery 1.9.1 the chunk updates only went up to ~20 in a multiplayer world.

**Comment by MrNinja93** [comment]
Yeah confirmed affects servers too, tested on an Exoria server which was running Astral 1.8.10 and forge 2705

**Comment by HellFirePvP** [comment]
I asked if this affects multiplayer the same way - so also spikes up to 150 instead of 20. 20 confirms my suspicion.

**Comment by HellFirePvP** [comment]
Will be adressed in 1.9.2, however this change might expose more desync as i can remember the weaker version i'm using now has resulted into something not getting synchronized in the past.... Oh, well.. the ritual pedestal might need a rewrite at some point...
