### ISSUE TITLE
[1.11.2] Using a bucket on a light well will not fill it with liquid starlight

### ISSUE THREAD

**Issue by Rosethorns** [HellFirePvP/AstralSorcery#76]
Description:
It appears that several mods have missed a change in forge regarding buckets and liquids. When using a a empty bucket on a lightwell full of starlight, the starlight will be removed from the well but the bucket will remain empty.  making it impossible to pull starlight from the well for crafting purposes.

Starlight will however be placed and picked up properly from the world by a bucket.

Repeat:
1. have a light well full of liquid startlight
2. use a empty bucket on the on light well.
3. bucket should not fill with liquid starlight.

Versions:
Minecraft: 1.11.2
Forge: 13.20.0.2252
Astral Sorcery: 1.2.3-Beta

**Comment by HellFirePvP** [comment]
Side note: mods like EnderIO or others that can conduit/pipe out of it should theoretically work.

**Comment by MrNinja93** [comment]
Relevant changes to the fluid handler in 1.11+ discussed here.

https://www.reddit.com/r/feedthebeast/comments/60lrxp/psa_for_modders_a_common_bug_interacting_with/

**Comment by HellFirePvP** [comment]
Yea, i missed that part during the kinda rushed port. I'm unfortunately not able to adress this today or tomorrow.. So, either you pump it out via some sort of pipes/conduits or... well.. wait until i'm properly able to adress this and release the fix.
