### ISSUE TITLE
Master AS 1.9.x incompatibility crash ticket

### ISSUE THREAD

**Issue by Doomgull** [HellFirePvP/AstralSorcery#762]
This will be used as the Master tracking ticket for issues reported involving the update to 1.9.0 causing other mods to throw exceptions because they don't like the Resplendent Prism's code requesting the max stack size of their items to build its blacklist.

This may or may not occur with NEI installed. As neither AS nor AS+NEI crashes on their own, and NEI has confirmed this has no involvement on them (https://github.com/TheCBProject/NotEnoughItems/issues/162), if you have none of the below mods installed in your pack you will need to investigate to determine based on installation or stack trace what mod is throwing an exception when queried, and open a ticket once that is done. Please update this thread by posting into it when you do so, and I'll attempt to track it for ease of reference, along with updates pushed to resolve the ticket when yours closes.

If it's referencing NEI in the crashlog, attempt to start it without NEI and see if that functions as a work-around. You will still need to open a ticket on the other mod's bug tracker (Not AS, not NEI, the OTHER mod).

Issue resolved in:
Ancient Warfare - Fixed in 1.12.2-2.6.1.251
Mekanism/Mek Generators - Fixed in 9.4.12.348
IC2 - Fixed in IC2 2.8.85
VanillaFoodPantry - Should be fixed in 4.2.1.  https://github.com/Wabbit0101/mods_hoardercraft/issues/47
Custom NPCS - Fixed in  (07jul18) release.
Erebus - https://github.com/ganymedes01/TheErebus/issues/624  FIXED IN NEXT RELEASE AS OF JULY 25TH NOTIFICATION.
Unique Crops archived their ticket, claiming no longer an issue with newest versions of both.
YABBA issue closed.

Issue still present in:
Lucraft Core
Advanced Rocketry versions prior to 1.4.0-84-universal.
Ender IO - Conflicting reports. Some users are launching with EIO without issues, likely an undetermined interaction trigger.

ALSO REMOVE SPONGE AND TEST THAT WAY. Not supported by AS to begin with as it breaks a considerable number of things in the mod because of how things are modified by Sponge.

Last Updated: August 10th 1833 UTC

**Comment by Deloyar81** [comment]
Is the Custom NPCs issue not related to this one too?

#755 
Custom NPCs - [Curse Issue Tracker](https://minecraft.curseforge.com/projects/custom-npcs/issues/2082)

**Comment by Doomgull** [comment]
I just forgot it because made this without enough caffeine in my system yet.

**Comment by MrFastZombie** [comment]
I looked through my mods folder and did not see sponge's .jar at all, but looking in my log I saw that Malisis core mentions org.spongepowered. So I removed Malisiscore and Malisisdoors, and the issue persisted.

I also tried removing IC2 at the same time, with no luck.

[Here is my latest log file](https://gist.github.com/MrFastZombie/4f6e7ce2be1a3745e8586f16538fc7e9), in case anything is different, but I see the same error just before the crash.

```
[20:50:30] [main/ERROR] [FML]: Exception caught during firing event hellfirepvp.astralsorcery.common.event.ItemEnchantmentTooltipEvent@4d1c2012:
java.lang.ClassCastException: null
```

**Comment by Doomgull** [comment]
@MrFastZombie That log is a disaster of errors, and even forge is having problems in it. Pull forge up to at least 2707 and try again. If it still fails, you're going to have to use a binary method of determining what's causing it to narrow it down.

**Comment by MrFastZombie** [comment]
It seems in my case, Advanced Rocketry 1.4.0-67 was causing the crash. I updated it to 1.4.0-85-universal, and it works fine now.

**Comment by Deloyar81** [comment]
I have Erebus 1.0.22 and it works fine with AS 1.9.0 - my hidden culprit is Custom NPCs which leads to the crash log refering to different other mods like Tinker and IC2.

**Comment by Morpheus1101** [comment]
With the crashes i have received 2 times, EnderIO and CyberWare have both been mentioned

**Comment by kotoroshinoto** [comment]
"Advanced Rocketry versions prior to 1.4.0-85-universal"

i'm on 1.12.2, and 1.4.0-84 is the newest version available.

**Comment by kotoroshinoto** [comment]
removing erebus stopped the issue for me, for now

**Comment by Morpheus1101** [comment]
This is the crash i got that pointed to EIO 
 & only occured with AS 1.9 https://gist.github.com/Morpheus1101/230f3911e36bceb5b51c2ad623c13242

**Comment by Doomgull** [comment]
Please report on the EIO tracker.

**Comment by Deloyar81** [comment]
@kotoroshinoto Which Version of erebus do you use?
I load up a modlist of my pack soon that don't crash. I removed NPC-Integration and Custom NPCs and can confirm that 'Integration isn't the culprit because the Issue persist with the same crash log when I only remove NPC-Integration.

**Comment by Deloyar81** [comment]
My actual mod List with versions that loads correctly:
https://gist.github.com/Deloyar81/9a2849310d510c246ec05b9974bf060f

**Comment by kotoroshinoto** [comment]
this currently doesn't show the version of erebus as I removed it, but it SHOULD show everything else i am using. (erebus was the only thing I've removed.)

**Comment by Darkmega18** [comment]
Ah, alrighty dokey. good luck with them all.

**Comment by Ligands** [comment]
So, it seems the startup crash with Unique Crops was _partially_ fixed with 1.9.2.

It no longer occurs if just Astral Sorcery & Unique Crops are installed together, however I am still experiencing the crash when NEI is installed also:
https://paste.dimdev.org/uvazurizic.mccrash

I removed NEI, and experienced the crash with AS 1.9.2 + UC + Cyberware as well:
https://paste.dimdev.org/cevezineri.mccrash

**Comment by generrosity** [comment]
I'm very sorry to ask, is there an option or ability to disable the 'Resplendent Prism' (and thud the check) in the configs or via a customisation mod? 

Not an ideal request, but i realize some mod authors are singular people who don't release often, and can't downgrade.

**Comment by Doomgull** [comment]
No, would need to either remove the mod throwing the exception when asked for stack size, or revert to a Pre-1.9.x version of AS. Please test with 1.9.2 installed if you've not yet, to see if there are improvements.

**Comment by thundR** [comment]
Moving above to here from #780

**Comment by AdaraChristine** [comment]
Im having the same error with Giacomo's Foundry but i can't seem to find an issue page for the mod.
https://pastebin.com/ZBHHeXqV

**Comment by Doomgull** [comment]
@AdaraChristine that looks like the issue Hubry just referenced from YABBA, actually. Rolling back to YABBA version 1.1.2.10 should resolve it.

**Comment by AdaraChristine** [comment]
Thank you, it worked and i can run the latest version. :)

**Comment by Deloyar81** [comment]
Custom NPC's update (07jul18) solves the issue (for me).

**Comment by Doomgull** [comment]
@generrosity check new CustomNPCs release mentioned in Deloyar's comment

**Comment by generrosity** [comment]
Working indeed - cheers @Deloyar81 and for your patience with conflicts Doomgull etc. Noppes put a few quick versions through via his Discord (latest 09jul18 looks to be final upload for a while).

**Comment by Sunconure11** [comment]
I feel like Howling Moon may have some issues with Astral Sorcery. You might want to check to be certain.

https://gist.github.com/Sunconure11/05e2b636e39ab79658fd7cf7dc001620

https://github.com/Razmen/HowlingMoon/issues/12

**Comment by Doomgull** [comment]
Erebus in that stack with issues still from above. If MoreCommands is in there (on mobile) try cutting it to see if it repeats the HowlingMoon issue.

**Comment by Sunconure11** [comment]
MoreCommands is not in that pack. I'm trying to deduce the Howling Moon issue via the additive approach, add until it errors

**Comment by Doomgull** [comment]
I'm archiving this now. Major offenders have tracked resolutions. Anything else comes up or there's a Lucraft response, it'll need a fresh ticket anyhow.
