### ISSUE TITLE
"C:\ASTestClasses" - AS 1.9.0

### ISSUE THREAD

**Issue by zISKo666** [HellFirePvP/AstralSorcery#764]
Hello,

I found the folder "`C:\ASTestClasses`" on my drive.
It contains the files:
- net.minecraft.enchantment.EnchantmentHelper.class
- net.minecraft.entity.EntityLivingBase.class
- net.minecraft.item.ItemStack.class
- net.minecraft.world.chunk.Chunk.class
- net.minecraft.world.World.class

I guess this should never happen!?
Do not write any stuff outside the Minecraft folders, please!

Thanx

**Comment by HellFirePvP** [comment]
These are internal class files written to see if the ASM patches apply correctly. Fixed for next update.
