### ISSUE TITLE
Client boot crash - 1.9.0; crashlog

### ISSUE THREAD

**Issue by AnsuzThurisaz** [HellFirePvP/AstralSorcery#765]
Client booted on fresh build of the modpack using 1.8.10 of Astral

https://gist.github.com/AnsuzThurisaz/086b6f591231cec67d6fbe36c3fcbc2a

**Comment by Doomgull** [comment]
#762 known issue, no fix from Erebus yet for this issue. Please also update AS to 1.9.0

**Comment by AnsuzThurisaz** [comment]
This crash was reported with 1.9.0, so what is there to update?

**Comment by Doomgull** [comment]
" known issue, no fix from Erebus yet for this issue."

The "update to 1.9.0" is because it's considered poor practice to report bugs with prior versions.
