### ISSUE TITLE
Astral Sorcery ores not generating

### ISSUE THREAD

**Issue by DuckyMoMo000** [HellFirePvP/AstralSorcery#766]
After creating a single-player world in the Direwolf20 1.12 pack I went searching for Aquamarine Shales to harvest, after hours of looking and flying in creative I came to the hypothesis that they didn't spawn. I put the theory to the test and went looking for rock crystals while holding the resonating wand, I could not find anything at all. No light beams from the surface and I mined for ages at y-level 4 and under, but nothing. That's when I came to the conclusion that no ore had been spawned in my world. I understand that they are not the most common thing to find, but they're not rare.

**Comment by Doomgull** [comment]
That's because the DW20 pack has a config where it's turned off. Go into the Astral Sorcery config, turn back on rock crystal generation, and enable retrogen in the AS config or generate new chunks.

**Comment by kmork1** [comment]
Thank you

**Comment by MrMSmith** [comment]
Hi @Doomgull 

Can you please provide some information on where the Astral Sorcery and AS configs are located?

Cheers,

**Comment by Doomgull** [comment]
Inside the pack instance's /config fitectory for thr main config file (astralsorcery.cfg), and the lists are inside tge /config/astralsorcery directory.

Or, upgrade to 1.9.2 since they were all just added to the in-game config system.

**Comment by Redeye123** [comment]
Srry for Bumping this tread again Do you know any reason why it was disabled ?

**Comment by Doomgull** [comment]
Oversight by pack devs.
