### ISSUE TITLE
The Increased Fertility perk doesn't breed animals

### ISSUE THREAD

**Issue by Mike-RaWare** [HellFirePvP/AstralSorcery#767]
This seems to be because `getGrowingAge()`, used in the following line, never returns an integer more than 0.

https://github.com/HellFirePvP/AstralSorcery/blob/b065398dded2de66a57b65fb464016b20229b42f/src/main/java/hellfirepvp/astralsorcery/common/constellation/perk/impl/PerkCreationBreedables.java#L50

**Comment by HellFirePvP** [comment]
my bad, should be >=

fixed next version
