### ISSUE TITLE
Astral Tome completely blank.

### ISSUE THREAD

**Issue by Hyperion505** [HellFirePvP/AstralSorcery#771]
Just installed Astral Sorcery and upon opening the Astral Tome, theres nothing, i can zoom in and out and move around (noted by the "stars" moving) but no galaxy/chapters to select. Changing my gui size around didn't help, nor uninstalling and reinstalling said mod.

Cant find anyone else with this issue, and im at a loss.

**Comment by Doomgull** [comment]
Which version of AS? Does the client log report anything about loading issues?

**Comment by Hyperion505** [comment]
AstralSorcery-1.12.2-1.9.1, the latest release. Nothing out of the ordinary from the latest log. shows me spawning it in, nothing about when i opened it, then closed it, saved and quit.

**Comment by Doomgull** [comment]
Need the full client log from launch.

**Comment by Hyperion505** [comment]
Id love to grab it for you but now all my Minecraft does is sit on "Waiting for server" indefinitely, freezes up on exiting and produces no crash logs. While a new world save has no issues. All on single player.

**Comment by Hyperion505** [comment]
Here is a crash log

[crash-2018-06-17_10.58.37-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/2109523/crash-2018-06-17_10.58.37-client.txt)


And client Log

[latest.log](https://github.com/HellFirePvP/AstralSorcery/files/2109522/latest.log)

**Comment by Doomgull** [comment]
Can you revert to forge 2707, or even the recommended 2705? 2708 is flagged as bugged, and according to the logs you're using it. There's a WHOLE bunch of problems in that log for many mods.

**Comment by Hyperion505** [comment]
I can try that, ill update you with the results.

**Comment by Hyperion505** [comment]
Sadly did not fix my major issue of that save being stuck on waiting for server/ crashing after trying to save and exit.

**Comment by Doomgull** [comment]
That particular server has some massive issues with multiple mods, I have no idea what's going on with it, but it looks pretty terrible in the log.

**Comment by Hyperion505** [comment]
Even after uninstalling and deleting anything minecraft, i started a new world and the astral tome worked! Then a crash when i shift clicked a blank constellation paper which would crash to desktop, and then i couldnt even load into my world. so i uninstalled Astral Sorcery then reinstalled it, now my tome is blank yet again.

**Comment by Doomgull** [comment]
Is your world folder properly writable and not protected? What mod are you using to add the shift-click move, and where is it being shift-clicked from? It's reporting an issue trying to update your player progression and sync it to the client in the log, from the network thread.

Does it happen if you DON'T shift-click?

**Comment by HellFirePvP** [comment]
Try without sponge

**Comment by Doomgull** [comment]
@Hyperion505  What does your <world_data>/playerdata/ directory path look like? How many <uuid>.astral files are present, and how many people play in this particular world?

**Comment by Doomgull** [comment]
@Hyperion505 remove MoreCommands, test if it works properly. Had a couple other tickets where MoreCommands was messing with it somehow. Need to open a ticket with them, if so.

**Comment by HellFirePvP** [comment]
Any additional information regarding this?
