### ISSUE TITLE
[Suggestion] Allow a config option for Bootes ritual

### ISSUE THREAD

**Issue by XavierNero** [HellFirePvP/AstralSorcery#772]
On our server we use animania and while we like the vanilla mob drops, it'd be nice if we could add additional mobs to get drops for, like the Dutch buck rabbit from animania don't drop rabbits feet and vanilla rabbits no longer exist in world.

**Comment by Barhandar** [comment]
Being able to get Animania's own drops would be nice, too (at quarter of the vanilla rate for cows and pigs since Animania's meat can be sliced into four items oredicted to vanilla's with Pam)

**Comment by HellFirePvP** [comment]
The ritual now has a much larger & generic capture/detection method for animals and will capture stuff like animania. Additionally, a blacklist has been added to specifically blacklist unwanted or too-strong animals from being interacted with.
