### ISSUE TITLE
I can't read.

### ISSUE THREAD

**Issue by PixelMusical** [HellFirePvP/AstralSorcery#773]
*I've found an annoying bug that when I opened the Tome all texts(including oher mods) have been glitched. When I reload my texture packs(F3+T) the bug is no more. But it will come back when I opened the tome again. Please fix this.

**Comment by Doomgull** [comment]
Optifine? Disable fastrender.

Going to need some image examples or something, otherwise, along with a full modlist, and the scale value in your options (auto, normal, small, large, etc)
