### ISSUE TITLE
[Suggestion]Mod optimization.

### ISSUE THREAD

**Issue by Minecraftbegin2snow** [HellFirePvP/AstralSorcery#774]
mc:1.12.2  mod:1.9.1
I played Astral Sorcery for one month,it is very good in general.So I want to propose some suggestions for the mod.
1.Add "+"(Move items) button on JEI for altars,just like vanilla crafting table and furnace.Most players think it's too hard to remember all altars' crafting recipes.
2.Add some vanilla items' recipes by altars,such as Nether Star,Elytra,Totem of Undying,Notch Apple and more.The mod added some altars,they're stronger than vanilla crafting table,so why not try to add them?

**Comment by Doomgull** [comment]
There's already a ticket for JEI enhancement stuff, and crafttweaker support already allows packmakers to do the second suggestion.
