### ISSUE TITLE
Suggestion: Renewable Marble / Oddities in Starlight Transmutation

### ISSUE THREAD

**Issue by CJL48** [HellFirePvP/AstralSorcery#775]
I'm suggesting this mainly because almost everything else from this mod or vanilla is renewable, with only this mod's features. Rock/celestial crystals can be duplicated via liquid starlight, aquamarine shale can spawn from interaction between liquid starlight and lava, and liquid starlight itself is produced from the former two in a lightwell. As far as I'm aware, that leaves marble as the only resource needed for this mod which isn't renewable (Including vanilla resources, since starlight transmutation, infusion, and mineralis/evorsio ritual/cloak make all of those renewable).

The other issue is actually more of a question: Is the starlight transmutation recipe for lapis blocks messed up? Transmuting prismarine lamps into lapis blocks seems backwards, given their relative rarity. Every other block shown in the icon of the transmutation entry is the block that gets transformed, not the result of the transmutation, and every other transmutation recipe is from a more common block to a rarer one (lapis ore can be gotten from mineralis ritual or mantle, infused to get lapis block: prismarine lanterns aren't renewable). I'm not certain that this one is a bug, since the entry does say that not all transmutations are favorable, but I'd like to be sure. In addition, blocks of coal are shown as part of the icon for transmutation, but there is no recipe that uses or produces coal.

**Comment by HellFirePvP** [comment]
To now get back to this suggestion:
Renewable marble: No. This is intentionally not renewable from within the mod itself.
"Oddities" in starlight transmutation: prismarine -> lapis is intentional yes. The block of coal transmutation got removed at some point yes. I forgot to remove it from that list, thanks for mentioning that.
