### ISSUE TITLE
Crash while loading with 1.9.1

### ISSUE THREAD

**Issue by Darkmega18** [HellFirePvP/AstralSorcery#776]
Heres a crash report: 
[crash-2018-06-21_02.36.55-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/2120373/crash-2018-06-21_02.36.55-client.txt)

says something about noppes custom npcs scripted item and an amulet blacklist. I'm supposing the custom npc item is just incompatible with it. Since I know JEI goes nuts at it as well, but thankfully it can be blacklisted off of jei so it doesn't keep blowing up.

**Comment by Doomgull** [comment]
#762
