### ISSUE TITLE
Shaders issue plus Mystcraft

### ISSUE THREAD

**Issue by Jkosio23** [HellFirePvP/AstralSorcery#778]
Basically, relatively the same shaders issue with the weak sky render fix as the others, but how do you do that with every new dimension that you make with mystcraft? it would really be a welcome option to have forced weak sky renders for all dimensions instead of just a list of which that you need to update manually

**Comment by Doomgull** [comment]
...could also not add those other dims to the constellation display config option.

**Comment by Jkosio23** [comment]
it doesn't help, even when they're not added they still get the overworld's bug with the shader thats solved when they're put in both the whitelists

**Comment by Jkosio23** [comment]
i have no experience programming so i don't know how difficult it would be to add this config option

**Comment by Doomgull** [comment]
Enough that its worth making players just add other dims to the config for unsupported feature conflicts instead.
