### ISSUE TITLE
Astral Sorcery 1.9 update breaks RFTools Storage Scanner

### ISSUE THREAD

**Issue by Routhinator** [HellFirePvP/AstralSorcery#780]
Not sure what is happening here, however updating to Astral Sorcery 1.9+ breaks the storage scanner rendering certain items unextractable. Some examples are:

- carrots
- wheat
- Black concrete powder
- chicken manure

Issue was tracked and reported against RFTools, but it has been determined that this mod and this update specifically cause it. Rolling back to Astral Sorcery 1.8.10 fixes the break.

https://github.com/McJtyMods/RFTools/issues/1793

**Comment by Doomgull** [comment]
Got a client log from load up?

**Comment by Routhinator** [comment]
Here you are:

[2018-06-25-1.log](https://github.com/HellFirePvP/AstralSorcery/files/2135432/2018-06-25-1.log)

**Comment by Doomgull** [comment]
No, the launch log for the client, not the log-in. I want to look at how your system is loading up the pack.

**Comment by Routhinator** [comment]
Sorry:

[debug-2.zip](https://github.com/HellFirePvP/AstralSorcery/files/2137153/debug-2.zip)

**Comment by Doomgull** [comment]
Crossposting from the RFtools ticket: 

So, some other things learned: vanilla double chest with a single stack of carrots within scanner range causes the same issue, as it reports as 128 carrots vs the 64 it actually is. It's crossing the 127 item threshold. Vanilla cobble stairs, same deal.

**Comment by Doomgull** [comment]
Fixed in 1.9.2 for me in testing, please confirm on your side @Routhinator

**Comment by Routhinator** [comment]
@Doomgull Will test and confirm this week. Patience please, will get back to you ASAP. Just very busy with little one these days. :)

**Comment by Doomgull** [comment]
Np, I just don't want to close this on AS's end if it's still happening for you in a pack or the like.

**Comment by thundR** [comment]
Can anyone confirm if the linked AE2 issue is the same one, or should I open a new issue?

**Comment by Doomgull** [comment]
Did you test using 1.9.3?

**Comment by fscan** [comment]
I'm not sure if its the same issue, but i think i know why it happens (see the linked AE2 issue). And yes, this is with 1.9.3. Personally i think this has to be fixed on the Mekanism side, but i'm not sure.

**Comment by Doomgull** [comment]
If it happened post 1.9.2, it is not the same issue as this ticket, and instead should go under # 762, and would indeed be something to address with mekanism.

**Comment by Doomgull** [comment]
Others have confirmed this specific issue no longer occurring. Archiving now.

**Comment by Routhinator** [comment]
Sorry for delays @Doomgull - confirmed fixed.

One question related to this. When we rolled back, the rollback caused all the crystals to be removed from the world. We've tried respawning them manually as admin, however they are still breakable by players and don't autolink to crafting tables. Is there some way as admin we can spawn in the worldspawn ones to fix this?

**Comment by Doomgull** [comment]
Could try using the "/as build" commands to place one (supports tab completion), but I d6ont recall if that imparts unharvestability. If that does not, there is no other method I am aware of.

**Comment by Routhinator** [comment]
Works! Cheers!
