### ISSUE TITLE
Crash when linking lens to ritual pedestal

### ISSUE THREAD

**Issue by Bobertie** [HellFirePvP/AstralSorcery#781]
Crash first occurred in version 1.8.9, so I updated to 1.9.1 and broke and replaced the lens, and it still crashes. 
1.8.9 crash report:
[crash-2018-06-26_17.36.18-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/2138199/crash-2018-06-26_17.36.18-server.txt)
1.9.1 crash report:
[crash-2018-06-26_18.02.40-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/2138204/crash-2018-06-26_18.02.40-server.txt)
Video of crash in 1.9.1:
https://youtu.be/bQdfuo4T3p8

I can paste launcher logs too if required :)

**Comment by Doomgull** [comment]
Whatever lens you're trying to use had corrupted NBT data, and therefor bad stats. How did you craft it/where did you get it? If you crafted it, how did you get the crystal used/where did it come from?

**Comment by Bobertie** [comment]
I used 2 different lenses (both crafted a while ago) as it never dropped when breaking the lens when i changed versions.  The crystals I used were unprocessed rock crystals. I made some new lenses using a random celestial crystal and crashed again

**Comment by Doomgull** [comment]
What are the stats on the lenses you cheat in?
Is this occurring only when placing it, or are you linking something to it?

**Comment by Bobertie** [comment]
The cheated in ones were size 900, purity and cutting 100%. Crash occurs a few seconds after inking the lens to the ritual pedestal.

I also noticed that the lens appears to place, but doesn't leave my inventory. The JEI cheated lens stays with my mouse cursor, while the crafted ones reappear when i reload minecraft. 

When i found the lenses reappearing, i tried to break the one that was there, and it wouldn't break, so i went into creative mode to break it. I placed a new lens and linking it didnt crash.

Looks like eventually it was a weird de-sync thing, but there wasn't the de-sync issue when the crashes first started happening last night.

Either way, it looks like its working now, but I'm still clueless as to what caused the issue in the first place.

**Comment by Doomgull** [comment]
We've had this reported twice over the last year, but have never been able to reproduce, and it wasn't consistent for initial trigger. It's always been unfortunately transient when attempting to update the NBT tag on a lens, and didn't repeat once the problem lens was completely broken >.<
