### ISSUE TITLE
Crash with LucraftCore installed

### ISSUE THREAD

**Issue by reddler97** [HellFirePvP/AstralSorcery#782]
when loading the game the game crashes with this crash:

[crash-2018-06-26_16.22.10-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/2139007/crash-2018-06-26_16.22.10-client.txt)

Or Pastebin:

https://pastebin.com/HWE2mVuU

**Comment by Doomgull** [comment]
Congrats, this is a duplicate ticket to #762

**Comment by reddler97** [comment]
my bad I thought I had looked thoroughly enough through the issues
