### ISSUE TITLE
Errores de particulas

### ISSUE THREAD

**Issue by lmentrix2** [HellFirePvP/AstralSorcery#783]
miren tengo un problema de particulas cuando destruyo el crytal clouster o al aquamarine shale y el starmetal sus texturas bugeados o el cuando un aquamarine u otro objeto es destruido por el ligtwell o o cuando los perks las estrallas salen cuadros blancos ,salen esto
 
![2018-06-28_11 49 12](https://user-images.githubusercontent.com/40603610/42046011-ea46bc88-7aca-11e8-8b0f-c2cee50613ba.png)

![2018-06-28_11 49 12_2](https://user-images.githubusercontent.com/40603610/42046038-faa94a50-7aca-11e8-8e4e-ec2090110994.png)

![2018-06-28_11 49 57](https://user-images.githubusercontent.com/40603610/42046052-03233402-7acb-11e8-986a-0f9dd4ed917c.png)

![2018-06-28_11 54 10](https://user-images.githubusercontent.com/40603610/42046078-0f5c1ee6-7acb-11e8-8278-b9e38d810726.png)

![2018-06-28_11 49 43](https://user-images.githubusercontent.com/40603610/42046229-69db1e1c-7acb-11e8-907d-2f5207ad1b17.png)

**Comment by Doomgull** [comment]
por favor use español, el traductor que utilizó lo hace difícil de entender.

**Comment by lmentrix2** [comment]
perdon es que no se utilizar el ingles pero bueno

**Comment by Doomgull** [comment]
Optifine?

**Comment by lmentrix2** [comment]
lo intente con optifine y sin optifine y no se arreglan

**Comment by lmentrix2** [comment]
primero intente al optifine poner todo alto no se arregla y despues todo bajo peor pero sin optifine solo arregal el aquamrine shale y starmetal

**Comment by Doomgull** [comment]
lista de mods?

**Comment by lmentrix2** [comment]
astral sorcery 
hwyla
jei
baubles

**Comment by Doomgull** [comment]
cualquier otro mods? Shaders? paquete de texturas?

**Comment by lmentrix2** [comment]
mi pc no aguanta shaders y no tengo ningun pavk de texturas instalados

**Comment by Doomgull** [comment]
No he podido reproducir este problema. ¿Qué tarjeta gráfica y sistema operativo tienes? ¿Los controladores están actualizados?

**Comment by lmentrix2** [comment]
Mi sistema operativo es de 32 bit windows y que son los controladores

**Comment by lmentrix2** [comment]
y targeta grafica ni idea

**Comment by Doomgull** [comment]
Ese puede ser el problema. No tengo un sistema de 32 bits para probar esto.

**Comment by lmentrix2** [comment]
bueno intentalo

**Comment by lmentrix2** [comment]
alguien sabe como arreglarlo

**Comment by Doomgull** [comment]
Creo que está relacionado con el hardware, en función de la apariencia, ya sea por versiones de 32 bit vs 64 bit o driver.

**Comment by lmentrix2** [comment]
o puede que puede arreglarse o con una libreria

**Comment by lmentrix2** [comment]
o drivers el antivirus  360 total segurity que actualiza un driver  hay

**Comment by lmentrix2** [comment]
alguien ayudaaa

**Comment by Doomgull** [comment]
No sé si esto puede solucionarse debido a las versiones de hardware. Lo siento. :(

**Comment by lmentrix2** [comment]
;( ;( ;( ;( ;( ;( ;( ;(
