### ISSUE TITLE
server crash on chunkload

### ISSUE THREAD

**Issue by Y0ungSandwich** [HellFirePvP/AstralSorcery#784]
A player is crashing my server when loading his chunk. 
The modpack is Mech & Magic https://www.atlauncher.com/pack/MechMagic
Astral Sorcery version is 1.9.1

Crash Report: http://mechandmagic.com/crashreports/crash-2018-06-28_15.28.38-server.txt

User says it is a fresh area he just moved to and he broke a Celestial Gate that was in his way.

**Comment by Doomgull** [comment]
Server failed an NBT write to a block, you'll need to delete the block manually or regen that chunk.

Also, just as an aside, this is going to be problematic:
spongeforge-1.12.2-2705-7.1.0-BETA-3206.jar

Please be aware several features of the mod cannot be performed due to things Sponge blocks, and you'll need to use the "/as" command groups to bypass them in some cases.

**Comment by Y0ungSandwich** [comment]
I figured as much. Time to blockzap around until I can find the block in console as the report didnt leave any coords. 

Sponge is usually problematic but Its not worth losing for a public server lol.

**Comment by Y0ungSandwich** [comment]
Looks like breaking the block is the actually mechanic crashing sadly. Not even world edit was powerful enough lol.

**Comment by Doomgull** [comment]
Regenerate that chunk, then. That you can't simply delete the block makes me wonder whats going on there with the world.

**Comment by Y0ungSandwich** [comment]
The portal was there, the guy broke it, crash. Nothing out of the ordinary. A pretty dry server in terms of plugins and features. We play very survival like. The server itself is only a few weeks old we just did a reset.

**Comment by Doomgull** [comment]
And sponge is explicitly not supported by AS, because of numerous issues involved. Whether that's relevant her or not may not matter, but writing NBT to a block shouldn't be difficult for any server to perform, and yet...the world ticks out attempting to do so.

**Comment by Y0ungSandwich** [comment]
Happens without sponge in as well. I think the initially block was broken during some lag, as I said the server is new and people are exploring. We chose not to pregen for some other mod issues we encountered in the past. Minecraft will be minecraft. We're rerolling the chunk we were just trying all possible paths first. Thanks.
