### ISSUE TITLE
Oredict block selection for mineralis ritual

### ISSUE THREAD

**Issue by ruifung** [HellFirePvP/AstralSorcery#787]
One possibility is to randomize the selection of blocks with a given oredict name. This would be useful for example, oreCertusQuartz is present on both certus quartz ore and charged certus quartz ore, however the mineralis ritual consistently produces charged certus quartz ore.

**Comment by ruifung** [comment]
you can set specific ores in config? okay then. that works.

**Comment by Doomgull** [comment]
Yes, it autopopulates from the registry, but you could specify a specific mod's ore type instead, or remove entries, or add non-oredicted ores if you wanted.

**Comment by ruifung** [comment]
@Doomgull  how *do* you specify specific ore type? The config file mineralis_ritual.cfg doesn't seem to accept block ID's i.e. (appliedenergistics2:ore_quartz) in place of an oredict name.

**Comment by HellFirePvP** [comment]
Use crafttweaker to define a new oredict and add just that one ore to it.
