### ISSUE TITLE
PlayerAmulet Capability attaches to empty ItemStacks

### ISSUE THREAD

**Issue by tommyTT** [HellFirePvP/AstralSorcery#788]
While hunting down a bug in Charset that occured with Astral Sorcery installed (see CharsetMC/Charset#244), I discovered that the capability for the player amulet is attached to item stacks a lot. I wanted to report this, so you could please check, if [this](https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/enchantment/amulet/PlayerAmuletHandler.java#L38) is intended behaviour, since all ItemStacks with isEmpty=true get PlayerAmuletCapability [attached](https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/enchantment/amulet/EnchantmentUpgradeHelper.java#L189) to them.

Thank you for your time!

## Version
Minecraft: 1.12.2
Forge: 1.12.2-14.23.4.2703
Astral Sorcery: 1.12.2-1.9.1

**Comment by HellFirePvP** [comment]
Derp. supposed to return true in case it's an empty item.
