### ISSUE TITLE
Is ritual acceleration only available in the overworld ?

### ISSUE THREAD

**Issue by Yarillo4** [HellFirePvP/AstralSorcery#793]
I just can't seem to make it work.

AS: astralsorcery-1.12.2-1.8.10
Forge: 14.23.4.2705
MC: 1.12.2

* Maxed out crystals
* Both crystals are indeed of the same type
* Particles effects indicating that both the ritual and the collector crystal are working
* No ray is parting from the ritual
* Lightwells work
* Collector crystal can't turn iron into starlight in here
* I have an identical one in the overworld that works
![img](https://i.imgur.com/ywjwvdU.png)

Something is apparently missing in that "Hunting dimension". How does astral sorcery figure out the starlight level of a dimension for the collector crystal ?

Do some dimensions actually work properly with astral sorcery ?

**Comment by Doomgull** [comment]
Yes, the Hunting Dimension has not moving time. If there's no ticking world time, there's no AS constellation operations that function.

**Comment by Yarillo4** [comment]
Hey @Doomgull, you seem knowledgeable.

So, what you said seemed very interesting.

I set up a test chamber on Jupiter (faster day/night cycle) and one in the overworld. 

![img](https://i.imgur.com/QlyexA2.png)

It's a starlight ore farm. I was expecting it to run faster on Jupiter, but, turns out, it still takes ~0.88 seconds per ore.

Shouldn't it be affected though ?

**Comment by Doomgull** [comment]
Unless it's actually ticking twice as fast, no. Changing length of day/night cycle doesn't change AS's code, which goes by MC day length in ticks. If it just transitions day to night and back twice as fast as normal, you'll get some desync as "day" time progresses differently from world tick time.

Then again, GC also does some weirdness where some dimensions have negative world time and I have no clue why it was set that way, but it's not a good practice.
