### ISSUE TITLE
Observatory has a graphical bug 1.9.3

### ISSUE THREAD

**Issue by Convergence2738** [HellFirePvP/AstralSorcery#799]
I was working around 1.9.3 (gateway is working great again btw) and I found two possible bugs regarding the observatory. The first one is a little strange and inconsistent. It is an item client desync bug that looks to happen after interacting with the observatory. Items that you pick up or (or blocks you place) don't want to leave or enter your inventory. Note: I am playing in SP so I am noting this with a grain of salt. 

The second bug I have is a graphical and interaction bug. The starfield within the observatory doesn't appear and you cannot draw lines in the interface. Already known constellations appear however. 

![20180706091930_1](https://user-images.githubusercontent.com/36319508/42393195-1eb73594-8145-11e8-8fe5-ee6282acc7f0.jpg)
![20180706091925_1](https://user-images.githubusercontent.com/36319508/42393197-2151118a-8145-11e8-8706-91bdb2e2b3b5.jpg)

Quitting and re-entering the work fixes the desync bug until you use the observatory again, then the bug starts triggering again. The observatory graphics bug is more inconsistent with the reload fix, but it also works. Rain seems to be the primary trigger for the graphics bug (unless that is a feature, that the observatory doesn't work during rainy nights).

**Comment by Doomgull** [comment]
Telescope and the handscope also do not work when raining, by design.

**Comment by HellFirePvP** [comment]
Yea, happens when it's raining. Forgot to add that in the constellation render on the gui there.

**Comment by lmentrix2** [comment]
es como que paso ami ese error de graficos pero eso se debe no se para mi es el optifine hace una opcion y me buegea el cielo nocturno
