### ISSUE TITLE
Dedicated server restarting gives players an extra journal on login even if they had one already

### ISSUE THREAD

**Issue by Febilian** [HellFirePvP/AstralSorcery#8]
I wasn't sure what triggered it the first time it happened, but I'm definitely getting another new journal every time the server routinely restarts and I log back in - even if I've already got my original in my inventory. I do have my first marked by Quark's "favorite" function if it makes a difference somehow, that's how I can tell that I'm getting new multiples in my inventory rather than just a copy of the first.

**Comment by HellFirePvP** [comment]
Will look into this, thanks for reporting

**Comment by Febilian** [comment]
No prob. Let me know if there's something else I can do to help figure this out.

**Comment by HellFirePvP** [comment]
Ugh. i'm afraid i can't reproduce that...
I save the state if the player has received a book already or not in a flag in the player's persistent NBT tag. So unless another mod is messing with it and deleting data out of it, it shouldn't be removed... Kinda at a loss here; Mind trying to reproduce it only with AS and see if it still happens on your end?

**Comment by Shadows-of-Fire** [comment]
That raises the question if anything related to player nbt works in that instance

**Comment by HellFirePvP** [comment]
Moved the check to another logic now, which is not overseen by forge's logic. I suspect that might be more reliable. At least it works just as before from _my perspective_ but will most likely fix it.

**Comment by Febilian** [comment]
Sorry for the several-hour-late response, I can try it with just AS installed to see if it still happens? Just to be sure.
