### ISSUE TITLE
AS 1.12.2-forge1.12.2-14.23.4.2705 (1.12.2 FML) Crystal not shining on crafting table and missing output results

### ISSUE THREAD

**Issue by Dajuki** [HellFirePvP/AstralSorcery#801]
I have put the crafting table near the crystal and there wasn't any shining on the craft table (Did it for day and night) . I also have restarted minecraft completely, it still doesn't work. I have made new world with AS and baubles being the only mods. It requires Baubles to run AS. Still couldn't get the crystal shining on the crafting table. Researched for as much solutions as possible and tried all but none would work (5 hours). Tried different versions of Forge and the mods and it did not work. I don't have VM or any vanilla related mods. Also even using the wand on the first tier crafting table for AS and it doesn't show any output on the right side and crystal wasn't shining on it when place below it with a directly contact to the sky (opened). The only thing that seemed fine was the constellations had all unlocked (Don't know if it involves with recipes). 

Mods I am currently used it with/tried.
-RFTools
-RFToolsDim
-JEI
-Xeno's minimap mod
-Tree Capitator
-Mcjtylib
-Damage Indicators
-Applied Energistics 2
-Baubles
-Craft Tweaker2

**Comment by Doomgull** [comment]
What is the version of Astral Sorcery in-use?

Do you have any mods that are modifying the crafting table?

Is this a world-gen crystal, or one you are placing yourself? Only the world-gen crystals will auto-link to a crafting table. Ones placed (even in creative mode) need to be manually linked.

The ones that are not auto-linking, can you link them via spawned-in linking wand to a table?
