### ISSUE TITLE
Armara ritual affects Botania mana bursts

### ISSUE THREAD

**Issue by tsurezuregusa** [HellFirePvP/AstralSorcery#802]
This is presumably intended but annoying. The Armara ritual makes Botania mana bursts go off target.

![2018-07-07_19 23 51](https://user-images.githubusercontent.com/589440/42409905-b87fad9c-821b-11e8-8084-9bd5ecd3d9c0.png)

**Comment by Doomgull** [comment]
They're entities, yes, so they'll be pushed away.

**Comment by HellFirePvP** [comment]
Yes they're entities, so.... (repeats what doom said) they'll be pushed away if they get too close. That's how it works. :P
