### ISSUE TITLE
Tough as Nails' brewing recipes don't work when Astral Sorcery is installed

### ISSUE THREAD

**Issue by atakle** [HellFirePvP/AstralSorcery#803]
Tough as Nails adds two brewing recipes using ice cubes and magma shards with an awkward potion. When Astral Sorcery is installed, nothing happens when the ingredients are placed in the brewing stand. The recipes work normally when Astral Sorcery is removed.

Forge version: forge-1.12.2-14.23.4.2730

Complete mod list:
- astralsorcery-1.12.2-1.9.3.jar
- Baubles-1.12-1.5.2.jar
- ToughAsNails-1.12.2-3.1.0.125-universal.jar

**Comment by Doomgull** [comment]
Can you provide a server launch log (if multiplayer) or client startup log (if single player)?

**Comment by atakle** [comment]
https://pastebin.com/CnpuPMVD
