### ISSUE TITLE
multiple issues with AS

### ISSUE THREAD

**Issue by diablo184** [HellFirePvP/AstralSorcery#806]
so i have been trying for a while to get this to work and can not seem to figure anything out, my game crashes whenever i pick up a constellation page, every time i log into the game i get a ancestral journal, and trying to use commands gives me and encountering unknown error message
server debug 
[debug.zip](https://github.com/HellFirePvP/AstralSorcery/files/2178796/debug.zip)

[latest.log](https://github.com/HellFirePvP/AstralSorcery/files/2178798/latest.log)
client debug
[debug.log](https://github.com/HellFirePvP/AstralSorcery/files/2178802/debug.log)
[latest.log](https://github.com/HellFirePvP/AstralSorcery/files/2178803/latest.log)
 any help would be appreciated

**Comment by Doomgull** [comment]
Screenshot of the directory where your <uuid>.astral files are located, please. All of those issues combined have been shown in the past to be triggered by file permissions issues.

**Comment by diablo184** [comment]
![screenshot 154](https://user-images.githubusercontent.com/40878736/42524582-9267221c-8436-11e8-96b8-faea0d49499b.png)
![screenshot 157](https://user-images.githubusercontent.com/40878736/42524587-9545711e-8436-11e8-89bf-9711eeb6b7ed.png)
are these what you are needing or are you need different files?

**Comment by Doomgull** [comment]
Inside that first screenshot, go into the "saves"  -> <gameworld name> -> "playerdata" directories, and I need a screenshot of that playerdata directory. Also need to check the "Read Only" status of the files ending in ".astral" and ".astralback".

**Comment by diablo184** [comment]
![screenshot 164](https://user-images.githubusercontent.com/40878736/42549999-b15f0e92-8494-11e8-89ea-53d4bf9fc987.png)
 this is all i could find in the playerdata folder.

**Comment by Doomgull** [comment]
No, but you have no astral progression file. What's the read/write permissions on the playerdata directory? If it has "Read Only" checked, uncheck it and launch again, then try to use a command to advance knowledge somehow.

You should get something that looks like this, at that point, except using your UUID from that last screenshot above, not mine:
![image](https://user-images.githubusercontent.com/12677933/42566487-c3778a4c-84d4-11e8-887d-21b7872d0664.png)

**Comment by diablo184** [comment]
so i deleted all my mods and did as by itself and it works fine

**Comment by diablo184** [comment]
gana go through and see if i can find the issue

**Comment by diablo184** [comment]
so the issue i was having was a mod conflict with the More Commands Mod after deleting it everything works fine
