### ISSUE TITLE
Astral Sorcery No Eclipses Ocurring

### ISSUE THREAD

**Issue by NOTMASTER09** [HellFirePvP/AstralSorcery#807]
I have been playing in creative world and I wanted to see the horologium constellation.

FTB Wiki says, that the horologium comes after solar eclipse that happens every 36 days.
It says that the day can be tracked with /time query day, with /time add 24000 I maked the 36th day
and when the mid day was the solar eclipse won't accured.

Log
[latest.log](https://github.com/HellFirePvP/AstralSorcery/files/2181372/latest.log)

**Comment by Doomgull** [comment]
From  AS 1.9.0 version patch notes:

Changes:
...
- Horologium will be... harder to find - Flares are no longer push-able; they also cannot push the player anymore
...


First appearance is between days 15 and 51 now, and occurring every 36 days after first appearance. It's impossible to miss the solar eclipse if you're on the surface when it occurs.
