### ISSUE TITLE
Crash With JEI & Yabba

### ISSUE THREAD

**Issue by DaggerTM** [HellFirePvP/AstralSorcery#808]
There is a crash involving AS with Yabba & JEI:
https://github.com/mezz/JustEnoughItems/issues/1290
https://gist.github.com/DaggerTM/5a418719ad367fe26101694b6ea80d77

**Comment by Doomgull** [comment]
#762  Almost like that wasn't already known, and caused by 1.1.2.11 version of YABBA's update. Downgrade back to 1.1.2.10, there's a fix being worked on with YABBA to resolve that. Not an NEI issue.
