### ISSUE TITLE
No constellation visible in multiplayer server

### ISSUE THREAD

**Issue by PhannyAmethyst** [HellFirePvP/AstralSorcery#809]
so far only had one constellation visible but a after one cycle it disappeared and never came back 
created a new testing world and discovered every constellation  by command but still non showed up while searching for them or even in the sky.

![2018-07-10_20 56 17](https://user-images.githubusercontent.com/41083651/42531499-6cff7670-8484-11e8-8a73-25c169763b75.png)
![2018-07-10_20 56 45](https://user-images.githubusercontent.com/41083651/42531500-6d26e660-8484-11e8-9f36-1e3fbb9568a3.png)
![2018-07-10_20 56 48](https://user-images.githubusercontent.com/41083651/42531501-6d55ad24-8484-11e8-959e-55d0ae5bef1e.png)
![2018-07-10_20 56 49](https://user-images.githubusercontent.com/41083651/42531502-6d764e94-8484-11e8-8da7-78473b662a05.png)
![2018-07-10_20 56 51](https://user-images.githubusercontent.com/41083651/42531503-6d942996-8484-11e8-8522-cf5841a5421a.png)
![2018-07-10_20 56 52](https://user-images.githubusercontent.com/41083651/42531504-6db404c8-8484-11e8-873e-036a0d4df484.png)

**Comment by Doomgull** [comment]
Upload your astralsorcery.cfg file, please. Also, what pack?

**Comment by PhannyAmethyst** [comment]
custom private pack i run for friend that i manually distribute
mod list:
astralsorcery-
AutoRegLib-
Baubles-
Botania
Chameleon-
CoFHCore-
CoFHWorld-
coroutil-
cucumber-
CyclopsCore-
EvilCraft-
FluidConverters-
Hwyla-
iceandfire-
industrialcraft-
ironchest-
Jei-
JurassiCraft-
JustEnoughResources-
llibrary-
MagicArsenal-
Mantle
MorePlayerModels_1.12.2
mysticalagriculture-
NetherEx-
plustic-
ProjectE-
Quark-
RedstoneFlux-
Reliquary-
Ruins-
TConstruct-
Thaumcraft
ThaumicInventoryScanning_1.12.2-
thaumicperiphery-0.2.3
ThermalFoundation-
torohealth-
Totemic-
UniDict-
VeinMiner-
WanionLib-
Wawla-
Waystones_1.12.2
zombieawareness-


[astralsorcery.zip](https://github.com/HellFirePvP/AstralSorcery/files/2181952/astralsorcery.zip)

**Comment by Doomgull** [comment]
What's the constellation tab of your Tome look like inside? Specifically the constellations? Just one or two is fine, don't need all 16.

**Comment by PhannyAmethyst** [comment]
![2018-07-11_03 05 22](https://user-images.githubusercontent.com/41083651/42545342-a4d3bba0-84b7-11e8-93e2-4e58bf0a93c3.png)
![2018-07-11_03 06 34](https://user-images.githubusercontent.com/41083651/42545344-a55f5dcc-84b7-11e8-8112-5447fa24dd9d.png)
 this is what they used to look like
don't know what happened but after 4 RL (as seen in the earlier screenshots) days it somehow fixed it self and seem to be working normally right now

**Comment by Doomgull** [comment]
¯\_(ツ)_/¯
