### ISSUE TITLE
[1.11.2] Using a shifting star while on a server kicks the player and breaks their sign.

### ISSUE THREAD

**Issue by Rosethorns** [HellFirePvP/AstralSorcery#81]
http://pastebin.com/kJUi0Gdi
The above is the "interal server error" as reported by the server

When a player uses the shifting star on a server it kicks the player and does not seem to completely remove the players sign.

In this example I had the Aevitas attunment which I attempted to clear. I was then booted from the server (above pastebin) and upon logging in the book showed that I did not have any sign on me and no perks page. However I still continued to have extended reach, turn stone to ore and grow plants around me.

Reproduce:
1. On a server attune to a sign
2. use the shifting star to remove the sign.

Versions:
Minecraft: 1.11.2
Forge: 13.20.0.2252
Astral Sorcery: 1.2.3-beta

**Comment by HellFirePvP** [comment]
Derp. My bad..
