### ISSUE TITLE
Not All Bright Constellations On Sky

### ISSUE THREAD

**Issue by NOTMASTER09** [HellFirePvP/AstralSorcery#811]
I created new world, and I wanted to unlock the bright constellations. I gived to me constellation papers,
and then with the /as constellations command i unlocked all bright constellations, but when i looked on sky there was only three of five

### Log
[latest.log](https://github.com/HellFirePvP/AstralSorcery/files/2185066/latest.log)
### Debug
[debug.log](https://github.com/HellFirePvP/AstralSorcery/files/2185067/debug.log)

**Comment by Doomgull** [comment]
Not all constellations are visible on every night. It's randomly distributed based on world seed. Did you actually check every night, or just one night?

Also, really should have been a Discord thing, not a Github thing.

**Comment by NOTMASTER09** [comment]
Every night.

**Comment by Doomgull** [comment]
What's the server day/time to a "/time query day"?

**Comment by NOTMASTER09** [comment]
It's a new world, it's cretive i'm skipping day with /time add 2400 on the /time query day i have the 3th day.

**Comment by Doomgull** [comment]
How many times have you skipped forward? It was was more than twice, should have a date much older than 3.

**Comment by NOTMASTER09** [comment]
I'm not sure, i'm not in the game now. But i think it should be like 4th or 5th day.

**Comment by NOTMASTER09** [comment]
It's 4th day.

**Comment by NOTMASTER09** [comment]
And when i reentered the world all the constellations disappeared

**Comment by Doomgull** [comment]
Log shows you disabled daylight cycle. That's your problem.

https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/constellation/distribution/WorldSkyHandler.java#L69

**Comment by Doomgull** [comment]
Daylight cycle controls pretty much everything. Can't do that. Just like dimensions that are perma-day or perma-night. It doesn't go well.

**Comment by NOTMASTER09** [comment]
I maked a new world then gived the constellation papers to me and then i tried to discover it with telescope but not all the bright constellations showed. I do not set daylight cycle to false

**Comment by Doomgull** [comment]
With this newest test? Because the previous one you uploaded had it in the log pretty clearly. Again, constellations don't show every night, usually at most 5 out of every 8. The contellation entry in the book will show which phases it should be in the sky for.

**Comment by NOTMASTER09** [comment]
Test is newest. I don't know if this is important but when I played before posting the issue I was searching horologium but when I opened the chat after opening the telescope i crashed.

**Comment by Doomgull** [comment]
Horologium only shows up once every 36 night ( with a 0-18 day offset for first appearance). Do you have a crash log from that time?

**Comment by NOTMASTER09** [comment]
Yes. I do
[crash-2018-07-11_15.49.14-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/2187578/crash-2018-07-11_15.49.14-server.txt)
