### ISSUE TITLE
Containment Chalice/Evershifting fountain not working as expected.

### ISSUE THREAD

**Issue by Turmfalke2** [HellFirePvP/AstralSorcery#813]
hi,
I thought I could make a well in my base by placing down an evershifting fountain over a water source and then supplying it with liquid starlight. After bucketing more than 20 buckets worth of liquid starlight into the chalice I have yet to gain a single bucket of water.
My observations:

-  it instantly created the wellhole
- the evershifting fountain consumes liquid starlight even when it is deactivated by placing a block in the circle.
- Water particles are flying from the evershifting fountain to the output chalice.
- The output chalice contains a tiny cube of water
- rightlicking the output chalice with a bucket does nothing
- occasionally ice blocks are created halfway between the output chalice and the evershifting fountain, dropping down into the hole.

So am I missing something? Shouldn't the output chalice fill up with water?

**Comment by Doomgull** [comment]
Water + liquid starlight creates ice with in contact in-world. Chalices perform this interaction wirelessly. The fountain has an internal reservoir, so you don't have to keep it filled, if you don't want that interaction.

What bucket are you using? What version of AS? Forge? Modpack? Going to try to replicate, but need that info to do so.

May also want to try rebooting, if in singleplayet.

**Comment by Turmfalke2** [comment]
Was singleplayer. What do you mean with if I don't want that interaction? I can pump directly from the fountain? How?

bucket iron
AS 1.12.2-1.8.10
Forge 14.23.4.2707
modpack sevtech 3.0.8

So is the issue that the moment output chalice reaches 1bucket worth of water it creates an icecube? I thought it should primarily pump water and create some icecubes as a by product. Also what is the ratio for starlight to water?

**Comment by Doomgull** [comment]
Place a bucket of liquid Starlight, and a bucket of water, like you were making a cobble gen. It'll make sense.

Normally, it doesn't use the entire bucket for the interaction. Normally it has a chance to use a tiny portion. Sevtech has changed a lot of things with the configs and the recipes, however. This is normal behavior for the pack, as far as I am aware. Feed a single bucket of liquid Starlight into the Chalice on top of the fountain, at a time, so that there's not any fluid to perform an interaction with because it all gets stored internally to the Fountain, and not in the Chalice on top.

**Comment by Turmfalke2** [comment]
er.. that is making things far more difficult.
Also I can see to many scenarios in which the liquids interacting with each other is useful with the evershifting fountain.

**Comment by Doomgull** [comment]
I'm not saying you have to, I'm saying there's the risk you may need to with the Sevtech pack, because of changes made, to use it as an effectively infinite water source.

That said, could always have a vacuum hopper grabbing the ice and then melt it like normal.
