### ISSUE TITLE
Wonky Aevitas Fertility Bug/Feature Suggestion

### ISSUE THREAD

**Issue by Convergence2738** [HellFirePvP/AstralSorcery#814]
Quick Question: is the Aevitas perk tree suppose to 'de-age' animals that multiply by the fertility perk? Because it causes problems with mountable animals as they 'de-age' when they 'breed' and undergo mob mitosis. I'd just throw the idea out there if possible, to have the perk not make mountable mobs 'de-age' or breed by the perk as it is rather problematic when your mount de-ages into a baby while you are riding it. You can't remount until it grows up again. I know, I *could* tweak the configs to effectively neuter the problem, but it would be rather bothersome to have to play in the menus every time I go to use a Horse or Donkey. This is just a small quality of life thing I noticed.

![20180716221914_1](https://user-images.githubusercontent.com/36319508/42798317-d2a37f8c-8982-11e8-8af5-22b60a2703b8.jpg)

**Comment by HellFirePvP** [comment]
Next update will prevent ridden entities from being affected.
