### ISSUE TITLE
Strange Interaction betweeen Pam's Harvestcraft and Immersive Engineering with Astral Sorcery

### ISSUE THREAD

**Issue by Eresorm** [HellFirePvP/AstralSorcery#816]
When Pam's, Immersive Engineering and Astral Sorcery are installed, Pams recipes that use things like the Bakeware or the Pot dont work inside the IE Assembler Mutiblock. They show up in JeI and can be crafted normally, but the Assembler doesn't output or consume anything.

The recipes work if Astral Sorcery is not installed.

![2018-07-19_22 32 16](https://user-images.githubusercontent.com/36823423/42968591-08dc2e14-8ba4-11e8-8d09-b81fea5ed7b7.png)

Edit: after some testing it seems, that only recipes that also result in a pams item are affected. I installed Mekanism and now the salt recipe works, but it outputs mekanism salt.
I don't know if this is a AS issue, but it goes away without Astral Sorcery...

**Comment by Doomgull** [comment]
What version of AS, what version of Forge, and what are the versions of the other two mods?

**Comment by Doomgull** [comment]
Should probably report to IE so they can take a look at what's going on. AS doesn't alter the crafting stuff there. Might be related to non-stackable items and the amulet capability.

**Comment by rinart73** [comment]
Please reopen this. Because this mod adds an NBT record that messes up Pam's cooking utensils.
It adds following NBT record (serialized NBT for Mortar and Pestle):
`{ForgeCaps:{"astralsorcery:cap_item_amulet_holder":{}},id:"harvestcraft:mortarandpestleitem",Count:1b,Damage:0s}`

**Comment by Doomgull** [comment]
No, I pointed this out more than five months ago in the other ticket. This is entirely the result of NBT not being properly checked. #762
