### ISSUE TITLE
More Commands compatibility issue. 

### ISSUE THREAD

**Issue by Trawetsmail** [HellFirePvP/AstralSorcery#818]
So technically, yes. This isn't a bug with the mod itself, but rather its inability to run alongside another one. As stated in the title, using More Commands in tandem with Astral Sorcery causes AS to break. A new journal spawns in my inventory every time I load up a world, as opposed to just the first time. On top of that, the journal is completely blank and does not function properly. Picking up constellation maps crashes the game, and attempting to execute commands will turn up the message "an unknown error occurred while attempting to perform this command".

I can officially confirm that this is a compatibility issue with more commands as another person using it reported the exact same issues on here and revealed that uninstalling More Commands fixes the issue, which I can also confirm to be true. I would refrain from using it other than the fact that More Commands is an extremely useful utility for Minecraft that for me is pretty much on par with Optifine and Worldedit as mods I have to have installed, so unfortunately, I uninstalled AS as there was no use having it take up more RAM. These two mods used to be fully compatible in their 1.10.2 counterparts, so I'm not sure what happened or what changed.

**Comment by Doomgull** [comment]
Yes, we know. Considering this only happens when the mod that modifies commands is installed, this should really be opened on the MoreCommands side. None of the command stuff changed in AS between the two outside of adding additional commands, so when the exact same command code from 1.10 triggers it, per another player, it's highly unlikely to be AS.

**Comment by Doomgull** [comment]
![image](https://user-images.githubusercontent.com/12677933/42995325-8f2518b6-8bde-11e8-95fb-6e520a7521eb.png)
