### ISSUE TITLE
Crash with Ore Stages 2.0 +

### ISSUE THREAD

**Issue by artdude543** [HellFirePvP/AstralSorcery#820]
_As a reminder for yourself HellFire from the chats in DM's and so I can use this for tracking_

As noted in the title and previous talks. Due to the refactor of GameStages all the deps mods changed to use the new API. As such the current implementations in AS is out of date for OreStages which causes worlds to be un-playable is one of the samples is in the chunk render view/distance.

Report: https://gist.github.com/artdude543/add834495047ca7ade875179528d8de2

**Comment by HellFirePvP** [comment]
I didn't forget :V i just didn't push an AS update in a while :P
