### ISSUE TITLE
Enchantment bonus from resplendent prism persisting after item is dropped on the the ground from held slot

### ISSUE THREAD

**Issue by SerotoninJC** [HellFirePvP/AstralSorcery#822]
When I drop an item from my main hand with its enchantment boosted by the resplendent prism, the enchantment bonus remains on the item (When i drop a sword of sharpness I boosted to sharpness II by the prism, i pick up the sword as a sword with sharpness II boosted to sharpness III by prism). This resulted in infinite stacking of enchantment levels.
![image](https://user-images.githubusercontent.com/41575405/43073606-d2e40e56-8eac-11e8-839e-20daa7f5230c.png)

**Comment by HellFirePvP** [comment]
This is a mod interaction. Please try binary-searching through your pack and see which interaction causes that.

**Comment by Doomgull** [comment]
AS version, forge version, modpack?

**Comment by SerotoninJC** [comment]
Running the latest version of AS and forge, playing on a custom self-made modpack with some rather old mods, the bug didn't occur with some mods removed. But i don't have the time to find out which specific interaction it is so i will have to deal with it for now

**Comment by SerotoninJC** [comment]
I suppose it is caused by some no longer updated mods since this bug didn't happen when i was playing another modpack with all constantly updated mods
