### ISSUE TITLE
Evilcraft compat crashing 

### ISSUE THREAD

**Issue by vdrake77** [HellFirePvP/AstralSorcery#826]
In Astral 1.9.4, seems to have some sort of issue with Evilcraft's built in compatibility with thaumcraft specifically.

Minecraft 1.12.2
Astral 1.9.4 (1.9.3 works)
Evilcraft 10.60

https://pastebin.com/FHcpeVeP

**Comment by bartimaeusnek** [comment]
https://github.com/HellFirePvP/AstralSorcery/blob/48270b71199034af6066ff737b7040612a9f4fb8/src/main/java/hellfirepvp/astralsorcery/common/enchantment/amulet/EnchantmentUpgradeHelper.java#L178

getItemDamage() causes the StackOverflow.

**Comment by Doomgull** [comment]
This is the evilcraft bug tracker: https://github.com/CyclopsMC/EvilCraft/issues/712

**Comment by HellFirePvP** [comment]
Evilcraft fixed this. See the issue doomgull linked.
