### ISSUE TITLE
AmuletHolderCapability breaks other mods when applied to a bucket

### ISSUE THREAD

**Issue by MatthewSmit** [HellFirePvP/AstralSorcery#828]
In other mods, in my experience it's AbyssalCraft, they don't expect this nbt tag, causing them to not recognise the buckets as valid in recipes.

Here are two issue reports in AbyssalCraft showcasing the issue.
Shinoow/AbyssalCraft#302
Shinoow/AbyssalCraft#301

It's possible it's affecting other mods, and possibly non bucket items too. It might be related to #816?

**Comment by Doomgull** [comment]
This is an issue with how the NBT is being matched on Abyssalcraft's side. Not us. Anything that does ANYTHING with NBT is going to cause this issue, and it's something he needs to fix.

Even ignoring what people are going to start transitioning to in prep for 1.13.

**Comment by HellFirePvP** [comment]
Judging by Shinoow's closing comment on https://github.com/Shinoow/AbyssalCraft/issues/301 it is fixed now, which also goes along with what he's told me some days ago. Could you try and test with a newer version of Abyssalcraft?
