### ISSUE TITLE
Crashes on creating a new World

### ISSUE THREAD

**Issue by panslothda** [HellFirePvP/AstralSorcery#83]
As in titel
[crash-2017-03-24_16.35.29-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/869162/crash-2017-03-24_16.35.29-server.txt)

**Comment by HellFirePvP** [comment]
That'd imply that no AT configuration files ran since the access change defined in the AccessTransformer configuration did not get applied correctly, resulting into the crash you have there.

I am puzzled why an AT configuration would not be read and applied correctly. Try re-downloading first of all.

**Comment by rinesi** [comment]
(This is my crashlog, I had him post it as I was away from my computer) Just redownloaded and trying again. 

Works for one launch, but not the next. I'm pretty sure it has to do with ClassCacheTweaker. Will check.

**Comment by HellFirePvP** [comment]
From what i've been told, CCT holds a cache in some folder somewhere or w/e. When you add or remove a mod, you should delete the cache so it can properly rebuild it with the changes the new mod introduces/the old mod left behind.

**Comment by rinesi** [comment]
Yeah, but even removing the cache will only work for one launch. I just uninstalled ClassCache and everything is great.

**Comment by ryanstott** [comment]
> Yes, this is a horrible, horrible hack. However, it generally works. Do not ever try to report issues with this mod installed without reproducing it without them. Ever.

;)

**Source: ** https://asie.pl/Projects/Minecraft/Mods/ClassCacheTweaker****
