### ISSUE TITLE
Celestial Gateways not working (minecraft 1.12 - mod version 1.9.2)

### ISSUE THREAD

**Issue by saint-waiden** [HellFirePvP/AstralSorcery#835]
after building the structure and placing the gateway block, the black star-field appears with the little white stars, but the yellow stars that should link to other gateways are not appearing. I certified that I built the right structure 5 times, have an open sky, and that I  do have other gateways, and did everything I could to make it work:

I used a chunk loader on the gateways, re-build the gateway structure, and even moved them to be just 25 blocks apart and still nothing works

curiously, sometimes the camera freezes and a snapshot is taken, as it should be, but that rarely happens and still didn't change anything 

I am using a sorta homebrewed modpack

**Comment by HellFirePvP** [comment]
Update AS
