### ISSUE TITLE
Constellations in the sky aren't showing after using scroll of written expertise 

### ISSUE THREAD

**Issue by Eziss** [HellFirePvP/AstralSorcery#836]
So basically I used the scroll of expertise that makes me know everything in astral but now when I use the telescope the constellations are already traced out but don't show up in the sky and now I think its messing with my attunement alter it won't work and I know I have it correct but it won't activate

**Comment by Doomgull** [comment]
Can you use the /as commands to print your unlocks out?

**Comment by Doomgull** [comment]
@Eziss any update on my above request?
