### ISSUE TITLE
Can't distinguish sooty marble types

### ISSUE THREAD

**Issue by scribbler957** [HellFirePvP/AstralSorcery#838]
I don't know how clear it is on other screens, but I've got my monitor calibrated so the blacks are true black and the marble all looks the same (except for the pillars). I'd like to suggest that maybe the lines on the different types of sooty marble could be lighter, like the sooty layer was scratched away while carving them, exposing the lighter marble underneath.
![2018-08-02_08 14 13](https://user-images.githubusercontent.com/15851438/43593445-43cff8f2-9667-11e8-9ba9-87d968246c5b.png)
This might look fine on other monitors, but on mine they're a series of black cubes with subtle shading variations in the texture.

**Comment by Doomgull** [comment]
Would probably recommend using a texture replacer, then, since most don't run that kind of calibration and it becomes out-of-place looking otherwise.
