### ISSUE TITLE
ContentTweaker Fluid Tinting in Lightwell

### ISSUE THREAD

**Issue by xt9** [HellFirePvP/AstralSorcery#840]
When adding **lightwell** recipes for ContentTweaker fluids the tinting/color code is not applied when rendering the liquid that's inside the Lightwell.

I compared a few tanks to see if they had similiar issues but it seems most of them render fluids from ContentTweaker with the specified color.
https://i.imgur.com/VhmJ1u2.png

The only other outlier I've seen is OpenBlocks tanks but they've already fixed it for an upcoming build https://github.com/OpenMods/OpenBlocks/issues/894

Would be super cool if this was fixed.
Thanks in advance.

**Comment by Doomgull** [comment]
Would be good to have a list of the fluids you're sering this with, AS version, and Forge version.

**Comment by xt9** [comment]
Yes, Tinkers' Construct fluids also render without their tint.
https://i.imgur.com/fDgfZRC.png

I also found that molten uranium from IE renders without a color.
https://i.imgur.com/GD2Hl6J.png
