### ISSUE TITLE
Resplendent Prism +X Levels to all Existing Enchantments not being applied

### ISSUE THREAD

**Issue by Perdemot** [HellFirePvP/AstralSorcery#841]
AS Version: 1.9.4. 
All the prisms, only affecting specified enchantments, work. 
The ones affecting all existing enchantments aren't applied.
Not certain why this is, or if this is a modpack issue and not a mod issue.

**Comment by Doomgull** [comment]
What are you expecting it to apply to? Definitely a Modpack or mod interaction issue

**Comment by Perdemot** [comment]
I am using the Enigmatica 2 Modpack. And basically, this is what the Issue looks like: https://imgur.com/a/RnjnpU0
Doesn't matter which Item or what enchantment.
Also tried this in SP with a +1 and +2 on all enchantments. The issue remains.

I guess I'll talk to the modpack people.

**Comment by Doomgull** [comment]
Do you have a log from client startup, and perhaps a server log from when you equip the amulet?

Is sponge involved?

**Comment by Perdemot** [comment]
Sponge is not involved. 
I checked the server log and the client log. Couldn't find anything, so I reproduced the issue on a local server. The issue remains and nothing is logged.

**Comment by HellFirePvP** [comment]
Is this JUST happening with +X to ALL existing enchantments? Does it work fine with the other 2 types?

**Comment by Perdemot** [comment]
Yes only the +1 +2 +3 on ALL enchantments is affected
