### ISSUE TITLE
Observatory desync between client and server thread

### ISSUE THREAD

**Issue by Dayyer1** [HellFirePvP/AstralSorcery#842]
I am getting an issue where I can't move items in my inventory if I am close to an Observatory.
I can pick up items and move them around my inventory, but after I close my inventory, strange things happen where items or blocks will disappear or duplicate.

An example would be;
I have marble in hotbar slot 1. I open my inventory and move oak wood to slot 1 and the marble somewhere else in the inventory. If I exit the inventory and try to place that oak wood in the world, the oak wood would be replaced with marble (which was previously in slot 1) and marble would be placed instead. If I open my inventory, the oak wood is gone, and there is another stack of marble in my inventory where I moved it.
All this happens after being close to an Observatory. If I break the Observatory and don't place it again, the bug still happens.

I can move items in my inventory properly only when I'm interacting with other inventories, like a chest. Reloading the level also works.

Hopefully this makes sense.

AS version 1.9.4
Forge version 14.23.4.2747

**Comment by Doomgull** [comment]
Sounds like client/server thread desync. Are you using the observatory, or just walking near it? What pack?

**Comment by Dayyer1** [comment]
The issue happens after I’ve used the Observatory.
If I reload a world, inventories and things all work fine until after I use it. Walking around the Observatory before I use it doesn’t seem to be a problem.
I don’t know if it would make a difference, but maybe I could try reloading the chunk it’s in after I use it and see what happens.

**Comment by Dayyer1** [comment]
And about packs, I made my own. Do you want the mod list?

**Comment by Doomgull** [comment]
Please. Might help run down if its an interaction issue causing the desync, or if something else is going on wholly within AS.

**Comment by Seitz1** [comment]
I'm having this exact issue as well.
Astral Sorcery v1.9.4, Forge v14.23.4.2739
Mod list (custom pack): https://pastebin.com/mC63jfpg

**Comment by Dayyer1** [comment]
@Seitz1 is there a way to list all my mods like that?
I have about 150 mods to list.

**Comment by Seitz1** [comment]
@Dayyer1 I typed that out manually. You can try intentionally crashing the game, since there will be a mod list in the crash report. That might be more trouble than it's worth, though.

**Comment by Doomgull** [comment]
Theres a mod that will generate a textfile with them all in it.

Or you could use the command line to print it out by running something like "dir >> C:\Temp\modlist.txt" on windows from inside the mod folder directory, and it'll dump the output into your C drive's temp folder.

I would expect a Linux user to know how to work an ls command, so won't include it here.

**Comment by Engreyight** [comment]
I have the same issue. It happens after using an observatory, only in survival and adventure mode (creative seems fine). World reload fixes it. The only mods I have are AS and Baubles. What happens is the inventory you had when you clicked on the observatory gets "saved" and you can't make changes from the inventory screen (E), or at least the changes are only visual (that's why @Dayyer1 saw planks and placed marble). If you, however, open something with an inventory (chest, machine from other mod) you can make changes to your inventory that DO stick. You don't need to change the contents of said tile entity, you just need to see your inventory through some way other than the E-screen.

**Comment by Zarvera** [comment]
Currently expiriencing exactly this bug on the latest AS available on CF.

**Comment by Doomgull** [comment]
@Zarvera if you open another inventory, like a chest, does it start working as expected again?

**Comment by Zarvera** [comment]
Yes. Exactly as described above pretty much - can work with my inventory only when i open chest or something with a GUI, and only there, opening inventory with E or trying to place a block or throw with a Q results in said action not happening\items diesappearing from inventory until i open chest again, at which point everything reverts back.

**Comment by Doomgull** [comment]
Is this on a server, on single player? Can I get a log uploaded to pastebin or the like from your client demonstrating the occurrence, from launch to demo?

And just to confirm, this is a 1.10.3 or later AS version, right?

**Comment by Zarvera** [comment]
>And just to confirm, this is a 1.10.3 or later AS version, right?
Now this left me utterly confused. I'm on 1.9.4 version, which was the last one available when i downloaded it, but judging by by file creation date and what i'm seeing on CF now, there were THREE more recent versions available when i downloaded. 
Does CF has some filehosting hickups or something? I couldn't have downloaded earlier Release if later available, i simply don't do that. This would also explain my confusion with a whole bunch of other mods discrepancy in dates between mine file and the ones available on CF
Anyway, i'm awfully sorry for bothering you, did checked the actual latest version and it works fine.
Bummer
