### ISSUE TITLE
Possible missing visuals

### ISSUE THREAD

**Issue by Dayyer1** [HellFirePvP/AstralSorcery#843]
I watched this video:

https://www.youtube.com/watch?v=uZ1UTh14QMY

The visuals around his rituals have effects that I don't see around my rituals;

![2018-08-08_23 36 41](https://user-images.githubusercontent.com/9260182/43878866-fd0c8f70-9b66-11e8-9af1-00600841ca25.png)

I'm not sure if it's a bug, or setting, or it was changed since this update, or what. I am using Optifine, though, so maybe that could be the problem.

What should an active ritual look like?

It's attuned to Vicio. I can fly, but there are no effects like in the video.

So, what's up with that?

**Comment by Doomgull** [comment]
What version of Astral Sorcery are you using? There were visual changes to the particle effects of rituals during the MC 1.12 development cycle for AS. If they're still not present in the most recent version of the mod, it's likely something conflicting with the display.

**Comment by HellFirePvP** [comment]
Progress further and read through texts and descriptions in the book.

**Comment by Dayyer1** [comment]
Ok.
Also, I’m using 1.9.4.

**Comment by Doomgull** [comment]
Then you need to empower the ritual to get the effects. Check the Tome, or the video again, as it's covered.
