### ISSUE TITLE
What's the meaning of Inner Wealth effect?

### ISSUE THREAD

**Issue by mcBegins2Snow** [HellFirePvP/AstralSorcery#844]
mod:1.9.4 for mc 1.12.2
The mod added Inner Wealth effect,but I don't know this effect is positive or negative for mobs.

**Comment by Doomgull** [comment]
Its a positive for the player that kills them.

**Comment by mcBegins2Snow** [comment]
What about the details?

**Comment by Doomgull** [comment]
Check the discord, or read the code. Not the place for something not spelled out in the tome.
