### ISSUE TITLE
Lag with Discidia

### ISSUE THREAD

**Issue by Dayyer1** [HellFirePvP/AstralSorcery#846]
Hitting mobs while fully attuned to Discidia causes a tiny bit of lag. (Not fps lag.)
(To be fair, my computer isn't the *best* for running modded Minecraft, but with multiple mods.)

How I tested it;

Superflat world, only AS (& Baubles) installed.
Spawn some cows (or any mob), and hit them. They should instantly be damaged and knocked back.
Now, attune yourself to Discidia. Every time you unlock a perk for Discidia, the knock back from hitting a cow will take more time. After unlocking all the perks for Discidia, there should be a noticeable difference in the time it takes for the cow to be knocked back. (Albeit small.)
The difference is more noticeable if you use an Attuned Sword, since the sword also lags a bit.
Wearing the Discidia Mantle of Stars makes the lag even worse.

The differences in timing are not a big deal with just AS, but I found that the more mods used along with AS would increase the lag. With my 130 mods, the delay was about 2 seconds. (In my defense, most of those mods are small.)

**Comment by Doomgull** [comment]
May not be relevant with 1.10's new perk system, but will check.

**Comment by LemADEC** [comment]
What version are you using?

**Comment by Dayyer1** [comment]
Doomgull— in case you haven’t already checked, I’ll check myself now.

**Comment by Doomgull** [comment]
@Dayyer1 this still happening with the 1.10 perk rework now?
