### ISSUE TITLE
Lag in checking mod presence

### ISSUE THREAD

**Issue by LemADEC** [HellFirePvP/AstralSorcery#847]
As of astralsorcery-1.12.2-1.9.4, lag is observed from checking mod presence.
Consider cashing mod presence instead of doing constant lookups, or even cache the fakeplayer ids in https://github.com/HellFirePvP/AstralSorcery/blob/76518f2025ec78f9a1fd0210000d895f628860b3/src/main/java/hellfirepvp/astralsorcery/common/util/MiscUtils.java#L423

![image](https://user-images.githubusercontent.com/4776032/44208162-ec1ba580-a15f-11e8-89a4-7d5d8c954236.png)

**Comment by HellFirePvP** [comment]
0.14% of whatever you recorded there? doubtful. and no.

**Comment by LemADEC** [comment]
That's 0.41% CPU consumed by your mod for just 5 players. That event is called for each player, real or fake.
Imagine what happens with 50 players online.

**Comment by Doomgull** [comment]
The fake player stuff is only 0.14%, not 0.41%. There's a lot more going on with that 0.41% than fake player checks.

**Comment by HellFirePvP** [comment]
> Imagine what happens with 50 players online.

Imagine the amount of OTHER STUFF that's going on when 50 players are online. This is the least of your problems by then. Either you are knowledgeable enough to see that or you are free to reduce those 0.41% to 0.38%. great job. you saved about 200 nano seconds then. Now go calculate how much 200 nano seconds are in relation to 1 millisecond. If something's lagging your server from whatever snapshot you've shown a piece of above, it's *not* this section you've shown. That's all there is to say. Have a nice day.
