### ISSUE TITLE
[Request] Stairs/Slabs for Infused/Enriched Wood

### ISSUE THREAD

**Issue by scribbler957** [HellFirePvP/AstralSorcery#848]
Please add stair/slab versions of the infused/enriched wood. (I wouldn't be adverse to chisel support but I won't push it.)
Thank you.

**Comment by HellFirePvP** [comment]
I will not do chisel-exchangability between them as specific types of infused wood are by intent gated "later" into the mod whereas the "raw"/basic variant is available very early.

As for stairs and slabs, i'm not really a fan...

**Comment by scribbler957** [comment]
I didn't mean interchangeably. I was going to mark the infused/enriched wood so it could make Davinci's vessels fly. I thought a flying AS powered ship would be fun.

**Comment by Doomgull** [comment]
Updated into master suggestion list.
