### ISSUE TITLE
Prevent exponential blowup of animal populations in the presence of a player with the Animal Breeding perk.

### ISSUE THREAD

**Issue by Lymia** [HellFirePvP/AstralSorcery#850]
This perk results in exponentially exploding animal populations in the proximity of a player with it. This eventually leads to TPS or framerate loss.

It should probably be placed in a more easily skipped location in the perk tree, or capped somehow.

**Comment by Doomgull** [comment]
Doesn't matter with next update

**Comment by Lymia** [comment]
Can you elaborate on how it fixes the issue?

**Comment by Doomgull** [comment]
Existing perk system is gone. Check twitter or discord for updates on the replacement system.
