### ISSUE TITLE
Yet another enchantment necklace related crash (I think)

### ISSUE THREAD

**Issue by Darkmega18** [HellFirePvP/AstralSorcery#855]
[crash-2018-08-26_17.30.36-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/2321330/crash-2018-08-26_17.30.36-client.txt)

I got hit with this crash just now. I just updated random things and as far as the crash is concerned there seems to be a new item from it that possibly doesn't like the amulet again, Some kind of ender bucket? or atleast thats what the report said. 

Anyways, I temporarily turned off astral sorcery so to see if it would continue to load and it did. so although it errored on clay soldiers I think it's yours. :V so I'll just pop back a random things version.

Has:
Forge 1.12.2 ending in 2705
RandomThings-MC1.12.2-4.2.1
astralsorcery-1.12.2-1.9.4

**Comment by HellFirePvP** [comment]
#854 literally the one issue right before this one.
