### ISSUE TITLE
[1.12.2]Crash Caught exception from Forge 

### ISSUE THREAD

**Issue by FhtagnHlatk** [HellFirePvP/AstralSorcery#859]
When it gets to stage 6 at startup it stops on Minecraft forge and crashes
Deleting Astral sorcery solves the issue but I like this mod so much and I really hope there is a way to solve this.
Here's the [crash](https://pastebin.com/AgJTK9GL)

**Comment by Doomgull** [comment]
Your forge version is busted:
![image](https://user-images.githubusercontent.com/12677933/44945496-d2fa3200-adb8-11e8-86fa-f3dd07b0ad87.png)

Roll back to 2755.
