### ISSUE TITLE
Sextrant not working

### ISSUE THREAD

**Issue by SteamDoge9000** [HellFirePvP/AstralSorcery#862]
The problem is that i can see the gui But when i select the star i cant see it in the sky

here is the list of mods i have present

ConnectedTexturesMod (by tterrag1098)
Chisel (by tterrag1098)
Mantle (by mDiyo)
Tinkers Construct (by mDiyo)
Baubles (by azanor)
Chisels & Bits (by AlgorithmX2)
Extra Utilities (by RWTema)
Pam's HarvestCraft (by MatrexsVigil)
Botania (by Vazkii)
CodeChicken Lib 1.8.+ (by covers1624)
CoFH Core (by TeamCoFH)
CoFH World (by TeamCoFH)
Thermal Foundation (by TeamCoFH)
Thermal Dynamics (by TeamCoFH)
Thermal Expansion (by TeamCoFH)
Brandon's Core (by brandon3055)
Draconic Evolution (by brandon3055)
Astral Sorcery (by HellFirePvP)
Reliquary v1.3 (by P3pp3rF1y)
AutoRegLib (by Vazkii)
Psi (by Vazkii)
Random Things (by lumien231)
Chest Transporter (by CubeX2)
NotEnoughIDs (by fewizz)
Cyclops Core (by kroeser)
Colossal Chests (by kroeser)
Forge MultiPart CBE (by covers1624)
Translocators 1.8.+ (by covers1624)
Tinkers' Tool Leveling (by bonusboni)
Tinkers' Complement (by KnightMiner)
Tinker I/O (by gkbm2011)
PlusTiC (by Landmaster_phuong0429)
Yoyos (by Raven2396)
Moar Tinkers (by Bartz24)
Tinkers' Addons (by oitsjustjose)
Just Enough Items (JEI) (by mezz)
Tinker's JEI (by Possible_Triangle)
Mekanism (by aidancbrady)
LibVulpes (by zmaster587)
Advanced Rocketry (by zmaster587)
Immersive Tech (by ferroo2000)
NuclearCraft (by TLJGames)
iChunUtil (by iChun)
Gravity Gun (by iChun)
Titanium (by Dr_Codex)
Matter Overdrive (by simeonradivoev)
LightningCraft (by sblectric)
MalisisCore (by Ordinastie)
MalisisSwitches (by Ordinastie)
Refined Storage (by raoulvdberge)
Refined Avaritia (by ExpensiveKoala)
ICBM - Classic (by darkguardsman)
Avaritia 1.1x (by brandon3055)
Avaritia Tweaks (by Jacky1356400)
Booster Rockets (by marwat208)
Immersive Engineering (by BluSunrize)
Guide-API (by TehNut)
Blood Magic (by WayofTime)
The Twilight Forest (by Benimatic)
Bookshelf (by Darkhax)
Simply Arrows (by Darkhax)
stimmedcow : NoMoreRecipeConflict (by Oliv1er)
Unlimited Chisel Works (by asiekierka)
DimensionalDoors (by DimensionalDevelopment)
General Layman's Aesthetic Spying Screen (GLASS) (by iChun)
Globe (by iChun)
MageCrafter (by sealandmapper)
Disharmony mod (by ricometzn12)
Roots (by epicsquid319)
EvilCraft (by kroeser)
Morph (by iChun)
Shadowfacts' Forgelin (by shadowfactsmc)
Doggy Talents (by Percivalalb)
Totem Essentials (by IceMetalPunk)
Infinity Stones Mod (by Jdroppert)
PotionCraft (by White_Draco)
Mekanism Tools (by aidancbrady)
Spartan Shields (by ObliviousSpartan)
OpenModularTurrets (by Poenjabiesous)
Ancient Warfare 2 (by shadowmage45)
SlashBlade (by scharfer)
Spartan Weaponry (by ObliviousSpartan)
Reforged (by ThexXTURBOXx)
SubLib (by senpaisubaraki)
Class Armor : Berserker, Mage and Archer (by senpaisubaraki)
Class Armor : Necromancer and Paladin (by senpaisubaraki)
Craftable Elytra (by mariofishy)
Grim Pack (by grim3212)
MMD OreSpawn (by jriwanek)
Potion of Aiming (by jglrxavpok)
OMLib (by Keridos)
Not Enough Items 1.8.+ (by covers1624)
Nyan Cow (by TheRandomLabs)
Long Fall Boots (by NanoHeart)
Trail Mix (by iChun)
MalisisBlocks (by Ordinastie)
Extra Alchemy (by zabi94)
Tiny Reactors (by arclight_tw49670)
ForgeEndertech (by EnderLanky)
Advanced Finders (by EnderLanky)
Portal Gun (by iChun)
Immersive Cables (by SanAndreasP)
Ruins (Structure Spawning System) (by AtomicStryker)
Techguns (by pWn3d_1337)
Meme In A Bottle (by mrbysco)
Thaumcraft (by azanor)
Planar Artifice (by Leppaisawesome)
Cube Art Online (by Forbidden_Gamer1)
LLibrary (by iLexiconn)
Statue (by gegy)
Just Enough HarvestCraft (JEHC) (by mrAppleXZ)
Piston Expansion (by UpcraftLP)
Minecraft Discs (by kento2300)
PistonCompression (by josephcsible)
AppleCore (by squeek502)
The Spice of Life (by squeek502)
McJtyLib (by McJty)
RFTools (by McJty)
RFTools Dimensions (by McJty)
Just Enough Resources (JER) (by Way2muchnoise)
MalisisDoors (by Ordinastie)
AbyssalCraft (by Shinoow)
AbyssalCraft Integration (by Shinoow)
Shear Madness (by AtomicBlom)
Torched (by iChun)
Avaritia (by Assassinfox)
WanionLib (by WanionCane)
Eternal Singularity (by KingWealthyturtle)
CreativeCore (by CreativeMD)
OnlinePictureFrame (by CreativeMD)
CraftTweaker (by jaredlll08)
EnderCore (by tterrag1098)
Karat Garden (by MrAmericanMike)
Sync (by iChun)
Roguelike Dungeons (by Greymerk)
Orbis API (by GildedGames)
The Aether II (by GildedGames)
Redstone Flux (by TeamCoFH)
Cooking for Blockheads (by BlayTheNinth)
Buildcraft (by CovertJaguar)
ArmoreableMobs (by Buuz135)
Super Ores (by abused_master)
Bullseye (by Glitchfiend)
CraftingNetherStar (by ZeckG)
Doomlike Dungeons (by BlackJar72)
Dynamic Lights (by AtomicStryker)
Rikmulds Core Mod (by rikmuld)
Placeable Items (by Ferdz)
ZeroCore (by ZeroNoRyouki)
Extreme Reactors (by ZeroNoRyouki)
MCMultiPart (by amadornes)
Farming for Blockheads (by BlayTheNinth)
IncreaseMobs (by _kegare)
Ender Storage 1.8.+ (by covers1624)
OpenModsLib (by OpenMods)
OpenBlocks (by OpenMods)
CasinoCraft (by Epidra2077)
Redstone Arsenal (by TeamCoFH)
ExpandedBonemeal (by josephcsible)
Slurpie's Dongles (by Redbullslurpie)
Dark Utilities (by Darkhax)
Thaumic JEI (by Buuz135)
Advanced Combat (by sblectric)
Thaumic Periphery (by mangoose3039)
Thaumic Inventory Scanning (Thaumcraft Addon) (by BlayTheNinth)
Forestry (by SirSengir)
Magic Bees (by MysteriousAges)
Thaumic Katana (by sz0999312)
Thaumic Potatoes 2 (by zxc74171)
Wawla - What Are We Looking At (by Darkhax)
No Recipe Book (by Seneschal_Luwin)
Flat Colored Blocks (by AlgorithmX2)
Bloodmoon (by lumien231)
The Rpg Inventory and ClassArmor Mod (by senpaisubaraki)
Class Armor : Beast Master (by senpaisubaraki)
Hwyla (by TehNut)
Waila Harvestability (by squeek502)
UniDict (by WanionCane)
Just Enough Pattern Banners (by Lorexe)
TAIGA (Tinkers alloying addon) (by Zkaface)
Iron Chests (by progwml6)
Inventory Sorter (by cpw11)
Villager Inventory Viewer (by csb987)
Extra Bit Manipulation (by MolecularPhylo)
MmmMmmMmmMmm (by bonusboni)
Thaumic Equivalence (by Lilylicious)
Lilliputian (by mangoose3039)
Elemental Creepers Redux (by MegaT145)
Hats (by iChun)
Hat Stand (by iChun)
Tinkers' Compendium (Tinkers' Defense) (by Lance5057)
SanLib (by SanAndreasP)
Turret Mod Rebirth (by SanAndreasP)
Iron Backpacks (by gr8pefish)
Chance Cubes (by turkey2349)
Mob Battle Mod (by Flemmli97)
Thaumic Tinkerer (by nekosune)
Thaumic Bases Unofficial (by Rumaruka)
DummyCore Unofficial (by TheLMiffy1111)
Hammer Core (by Zeitheron)
Expanded Equivalence (by Zeitheron)
Baublelicious (by DenBukki)
KJLib (by kjmaster2)
MagicBooks2 (by kjmaster2)
ProjectE (by sinkillerj)
More Wool Mod (by Michael18751)
Thaumic Additions: Reconstructed (by Zeitheron)
OpenComputers (by SangarWasTaken)
OpenComputers Drivers for Tinkers Construct (by BrisingrAerowing)
Industrial Craft (by Player)
Industrial Magic - Crossover (by Rumaruka)
Thaumic Computers (by jco2641)
Ender IO (by CrazyPants_MC)
Construct's Armory (by theillusivec4)
Ender Portal Decoration (by Thiakil)
Engineer's Doors (by Nihiltres)
Alternating Flux (by AntiBlueQuirk)
Robotic Parts (by An_Sar)
ReWIRED (by marwat208)

**Comment by SteamDoge9000** [comment]
just for the record i can see the constellations in the sky

**Comment by SteamDoge9000** [comment]
how do  i do i disable it and were is it located

**Comment by SteamDoge9000** [comment]
and yes i dragged shift and i put it in and its not showing at night

**Comment by SteamDoge9000** [comment]
its not on

**Comment by SteamDoge9000** [comment]
will forcing a crash report with task manager in sed test word be enough info?

**Comment by SteamDoge9000** [comment]
ok its working but get this i can oNLY see the star when im not looking directly at it
(the corners of my screen)

**Comment by SteamDoge9000** [comment]
Also  please note that i was only able to see it if my render distance was greater than 10
just for the record

**Comment by Doomgull** [comment]
We don't need a crash report, that won't help. Just need to see which mod specifically is causing the interaction, so we can try to isolate the source, and which side of the code it's on. Still need the AS and Forge versions.

**Comment by SteamDoge9000** [comment]
the problems fixed
it only fuly appears when the render chunk distance is equal to or greater that 10
