### ISSUE TITLE
Spectral relay cannibalization incorrect collection multiplier? 

### ISSUE THREAD

**Issue by Vritra22189** [HellFirePvP/AstralSorcery#866]
currently playing with the FTB revelation pack, 
which have AstralSorcery 1.12.2-1.9.3

as i want to plan ahead the relay's placement around the Luminous Crafting Table
i looked into the Spectral Relay's max range, and the cannibalization mentioned in the in-game guide
and proceed to test in creative.

but i found that even if i place the relays very close,
they still seems to produce the full amount of starlight
so i looked further into the NBT tags
and noticed the colMultiplier is 1, 
which means no cannibalization if i understand correctly?

![2018-09-09_14 07 21](https://user-images.githubusercontent.com/9210589/45261654-485da680-b43a-11e8-99b6-8592b3f30976.png)
![nbt](https://user-images.githubusercontent.com/9210589/45261659-557a9580-b43a-11e8-8b1b-e225fb3e28a4.png)

and a suggestion about the max range.
it seems the altar max range and the cannibalization range is both 16 blocks, 
so if i want to put 8 relays in the 8 cardinal direction
there is no way to avoid cannibalization even at max range?

i think having altar max range slightly larger than cannibalization range is more flexible to placements.

**Comment by Doomgull** [comment]
You're looking at the wrong part of the code, trust me, there's cannibalization.

And that's intentional on the cannibalization. Use lenses to move the starlight instead.
