### ISSUE TITLE
Goofy worldgen with between lands

### ISSUE THREAD

**Issue by Saereth** [HellFirePvP/AstralSorcery#867]
Added AS worldgen to betweenlands, when you zone in it immediately attempts to spawn in multiple AS structures which generate right next to each other (as issues?)

then betweenlands loads next and plops a big tree down right on top where you spawned in which looks well....
![image](https://user-images.githubusercontent.com/9200909/45447534-d9808780-b69d-11e8-8ac9-66e6436941a6.png)

I'm not sure how this could be fixed or if there is a work around,
As 1.10 betweenlands v3.3.11

**Comment by Doomgull** [comment]
Can you upload the worldgen configs?

**Comment by Saereth** [comment]
yep, here ya go:
https://gist.github.com/Saereth/91c5250751e5a24199768f10b0aef5c2

Also opened an issue with betweenlands 
https://github.com/Angry-Pixel/The-Betweenlands/issues/705

**Comment by HellFirePvP** [comment]
Looking into it that the 3 AS structures there literally spawned right next to each other.
The tree is Betweenlands' worldgen responsibility though... :P
