### ISSUE TITLE
[1.12] Resplendent Prism applying infinite amount of efficiency

### ISSUE THREAD

**Issue by MasterEnderman** [HellFirePvP/AstralSorcery#868]
Forge: 2757
Astral Sorcery: 1.9.4

I have a Resplendent Prism with +2 levels to efficiency.
If i hold a Tool in my hand, which already is enchanted with efficiency, it wil get boosted more and more while holding it in your hand. So the tool starts looking like that:
![image](https://user-images.githubusercontent.com/24524662/45480612-ac89ae80-b749-11e8-9632-276822dff326.png)

**Comment by Doomgull** [comment]
What other mods are in the instance?

**Comment by MasterEnderman** [comment]
Current Modlist: https://pastebin.com/7LW36PE8

**Comment by Doomgull** [comment]
Not going to lie, considerable number of mods in that list (which is huge), I am not familiar with. You'll need to do a binary check to see which mod is causing the interaction.

**Comment by Doomgull** [comment]
@MasterEnderman it's caused by electroblob's wizardry, specifically imbuement code. PR was submitted and bug filed with it.
