### ISSUE TITLE
[Suggestion] Config to allow blacklisting of specific tile entity types for the Horologium ritual

### ISSUE THREAD

**Issue by AranaiRa** [HellFirePvP/AstralSorcery#869]
Certain tile entities (such as Embers pipes) can eat up all of your entities for a ritual. It would be appreciated to be able to blacklist entities in config to prevent this problem.

**Comment by AranaiRa** [comment]
It is? I'm not seeing it anywhere in the main astralsorcery.cfg file, nor am I seeing it in the subfolder.

**Comment by Doomgull** [comment]
...huh. There were discussions about it. Going to have to go digging and see what happened.
