### ISSUE TITLE
Avietas perk turning adults into babies

### ISSUE THREAD

**Issue by mostwanted12354** [HellFirePvP/AstralSorcery#872]
When attuned to Avietas the "Increased fertility" is turning all the adult animals into two babies instead of them just mating and spawning a baby

When i get near the adults and then look at them, poof adult animal disappears then 2 babies appear. 

Started with passive mating, then minerall enrichment, and then increased fertility. 

FTB revelations
Minecraft 1.12.2
Astral sorcery v1.9.4

**Comment by Doomgull** [comment]
Yes, that's normal. There's not an easy way to delay breeding in existing code without a lot of ASM hackery, so it instead causes the animal to split like an amoeba.

Perk rework coming with AS 1.10 (presently in testing) will make it easier to not take the perk effect if not desired.
