### ISSUE TITLE
Stars not showing up in night sky after other mods (or vanilla) time manipulation

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [HellFirePvP/AstralSorcery#875]
After sleeping or otherwise manipulating time with mods (such as with blood magic), the stars seem to disappear from the night sky. Discovered constellations still show up blue but the sky is otherwise black. [There was a post on /r/feedthebeast with some pictures and futher information](https://www.reddit.com/r/feedthebeast/comments/7lebcv/dw20_112_no_stars_in_the_night_sky_astral_sorcery/), and I will copy links to the pictures here

![](https://i.imgur.com/NJZlL64.png)

![](https://i.imgur.com/60Qx8LY.png)

![](https://i.imgur.com/x0TaUH3.png)

Using the latest version of the Direwolf20 1.12.2 modpack, which uses AS version 1.9.4

**Comment by HellFirePvP** [comment]
Might be that you're in a desert biome and it's raining. Otherwise, i'm not calculating the brightness of them in any "weird" way, so if this breaks, normal skyrendering breaks aswell.

Reference:
https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/client/sky/RenderAstralSkybox.java#L520

Might also be that a tile renderer is applying a color through native GL11 instead of the wrapped GLStateManager and its color values are leaking into this state, however that is hard to trace.

**Comment by A-UNDERSCORE-D** [comment]
In a magical forest, but the effect is visible to every user on the server, and we are split across various biomes.

The suggested fix in the linked reddit thread (/time set night) does work, but is not permanent and has the effect of moving time backwards, which breaks some things like opencomputers computers.

[clear sky screenshots](https://imgur.com/a/cJrnwCM)

Fix wise I am unsure, rendering or java in general is not my strong suit.

**Comment by A-UNDERSCORE-D** [comment]
Additional info, setting the time to a specific number (Ive tried that day at 13000 equiv and 10000 equiv) does not work to fix it in the same way /time set day does, either thats something backend that changes (I havent checked) or this bug is related to gametime in a different manner, *or* its a coincidence.

**Comment by Doomgull** [comment]
"/time set night" shouldn't be reverting the day or moving it backwards, it should be advancing to the next night. Something is messing with things in a "not good" manner there. It doesn't look like there's a ticket open on the DW20 pack bug tracker, but there should be one opened there so they can troubleshoot from a pack perspective.

**Comment by A-UNDERSCORE-D** [comment]
@Doomgull As far as I know /time set night sets the time directly to 18000, rather than `(floorDiv($currentTime, 24000) * 24000) + 18000`, [even in vanilla](https://minecraft.gamepedia.com/Commands/time).

By "Move backwards" I mean that the current world time is a lower number than it was before.

Otherwise yeah, I will open an issue on DW20's side and see if they can figure something out their side

**Comment by CovertJaguar** [comment]
I too am curious how Root's Divine Protection Ritual, which changes day/night ratios affects things.
