### ISSUE TITLE
Crystal Duplication bug with Ritual Pedestal

### ISSUE THREAD

**Issue by Minamikaze392** [HellFirePvP/AstralSorcery#877]
Steps to reproduce:
1. Place the ritual pedestal and put an attuned rock/celestial crystal into it.
2. Use shift+right click to place a block above the ritual pedestal. The crystal will pop out.
3. Shift+right click the ritual pedestal, and you can get another identical crystal.

**Comment by Doomgull** [comment]
Pretty sure this was previously fixed. What version of AS?

**Comment by Minamikaze392** [comment]
I'm using AstralSorcery-1.12.2-1.9.4.
