### ISSUE TITLE
Cave Illumination - and light updates?

### ISSUE THREAD

**Issue by generrosity** [HellFirePvP/AstralSorcery#879]
Have been using Cave Illuminator for a while with FoolCraft3 modpack. Recently noticed I'm sometimes getting clumps of light sources together. While we have been using a series of versions along the way, it was noticed after upgrading to a faint starlight update.

https://imgur.com/a/1jGvXJ2

A couple of instances of this near the floor show that they are not lighting the floor as such (using More Llight Overlays to get light numbers drawn on the ground). Placing and removing a torch fixes the levels.

I'm not sure if that is somehow related to it, and will try replicating it by removing sources with the wand.

I can only imagine that it _might_ have to do with chunk borders or chunkloading the single chunk the illuminator is in, but there are too many in the same squares and chunks further away for me to explain it quite that easily. [EDIT] Yea nah - found a chunk with a 1x1 vertical hole filled with lights near chunk center, and the cave below full around that center too.

Thanks for checking this out, and thanks again for the mod. 💚

**Comment by HellFirePvP** [comment]
Hmm.. seems rather odd. Have you been able to reproduce this at all in a different pack? It seems like something's not doing the light update and then it'll just stay dark so other positions which are close by still seem "ok" to spawn a light at eventhough it shouldn't.

I can't see too many other reasons as to why this could happen...? Maybe some 'optimization' mod?

**Comment by generrosity** [comment]
I am slowly working through mods through a busy week - obviously just Astral on its own doesn't do it 😜 

Is it based on Random Tick? I could ramp up the speed of that to test faster 🤔

**Comment by Doomgull** [comment]
Nightime and sky access. You can right click the illuminator with an illumination wand to power it when not in those conditions for a bit of time each click.

**Comment by generrosity** [comment]
Closing this tickets as I am struggling to replicate the issue in other situations. I'll blame a 'optimization' mod at this stage - thanks for the tips and ideas
