### ISSUE TITLE
Crashes on startup in big modpack

### ISSUE THREAD

**Issue by Normina** [HellFirePvP/AstralSorcery#88]
Crashes quickly on startup. Added this and a few other mods to FTB Beyond 1.10.2.
[modlist](https://i.imgur.com/cmpH1SQ.png)
[crash log](https://pastebin.com/24DvSjFz)

**Comment by HellFirePvP** [comment]
Some mod loads all core mods and access transformers twice. try removing mods until this line

'[main/INFO]: [AstralCore] Initialized.'

only appears *once* and not twice as shown in the crashlog. (It can be found pretty close at the beginning of the log)

**Comment by Normina** [comment]
I had a duplicate mod installed. Thanks for the help! Great mod
