### ISSUE TITLE
Option to require vanilla materials for making/using certain items

### ISSUE THREAD

**Issue by xAlicatt** [HellFirePvP/AstralSorcery#882]
I will admit before I get into this that my understanding of how this mod works is limited to having mod spotlights playing in the background while I work on other things. I do not have any first-hand knowledge of it's intricacies, so this may be ignorant of me...

But I would like to request an option added to the configs that includes a requirement for vanilla materials for infusions/items that make vanilla features useless. 

I read a post on one of the modded minecraft reddit posts that the Vicio infused mantle replicates and surpasses the Vanilla Elytra and does not require obtaining an elytra to use. Imo, there should at least be the option to require that an elytra is used either in the mantle or in the infusion or in some other way that makes sense. 

Additionally if there are similar features that overshadow vanilla features, they also have at least the option to require the vanilla-rare item in their making/use in some way. An example: I don't add any mods that give normal creative flight to the modpack I'm working on because it makes the Elytra pointless and makes exploration trivial. So I'm using the "Magic Feather" mod because it allows me to add creative flight in a fairly small radius around a beacon if you have the magic feather item in your inventory....which requires an elytra to make and obviously beacons require netherstars. I'm adding creative flight this way because it still allows it to be used around your base for building and such, but doesn't make travel trivial

I want to include AS in my pack that I'm working on, but not if it trivializes obtaining features that are hard to get in normal vanilla progression.

Is this ever something you would consider?

**Comment by xAlicatt** [comment]
@Doomgull 

mods.astralsorcery.Altar.removeAltarRecipe(<astralsorcery:itemcape:*>.withTag({astralsorcery: {constellationName: "astralsorcery.constellation.vicio"}}), 3);

isn't removing the recipe? I've tried 0,1,2, and 3 for the alter # and it's still not removing the recipe. What am I missing?

**Comment by Doomgull** [comment]
This is really something that the Discord would be better for, where someone with some free time could walk you through that one.
