### ISSUE TITLE
Thaumcraft Golems affected by Armara Ritual Pedestal

### ISSUE THREAD

**Issue by Aldurnamiyanrandvora** [HellFirePvP/AstralSorcery#888]
As the title reads, Golems from Thaumcraft are pushed away from the ritual pedestal, leaving the owner to have to choose between setting up a Ritual for protection or using Golems for automation. 

Also, butterflies from Familiar Fauna had the 'bubbles' the Ritual applies to mobs, but they were frozen, not pushed away.

**Comment by MartyGentillon** [comment]
I don't see how this change changes anything.  In the current dev build golems still go flying within the Armara effect, meaning that, at current, it is still Golems or Armara.  After all, you didn't exempt them from the knockback effect, you just changed the potion effects on them.

Also, Discidia would suffer similar issues...
