### ISSUE TITLE
Quantum Quarry? Ticking block entity

### ISSUE THREAD

**Issue by 34486** [HellFirePvP/AstralSorcery#889]
No idea what to say, Just updated to latest rec forge build 1.12.2. Just updated to 1.9.7 of EU2.

I get this crash on start... I read other people have similar problems, but its not the same. I deleted the quarry dimension. No idea what to do after this....
Log:

[crash-2018-10-21_15.09.41-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/2499518/crash-2018-10-21_15.09.41-server.txt)

**Comment by 34486** [comment]
What do you mean there is no AS? I don't see exu2 depending on any coremod? Its in a private custom pack.

**Comment by HellFirePvP** [comment]
Not AS' fault.

**Comment by Doomgull** [comment]
@34486 There is nothing related to AS in that failure. The exception triggers from vanilla code, which is being modified by EX2 chunk provider code. There is not even an AS modification in that (Lines 23 through 50).

Additionally, the stack trace is explicitly calling out an EXU2 block being ticked in a chunk without an AS listed code reference, and the chunk is being generated by exu2 explicitly (lines 62 through 76), in an exu2 dim (line 60).

In fact, Astral Sorcery isn't even in the fucking pack list. Or the Core Mod list. It's not remotely possibly involved. How can AS code cause a crash when it isn't even involved?
