### ISSUE TITLE
Wand Not Crafting

### ISSUE THREAD

**Issue by TobiDoesMC** [HellFirePvP/AstralSorcery#89]
I don't know what is going on I have my table in place but it wont craft my wand

**Comment by HellFirePvP** [comment]
"doesn't work" is not enough information for an issue report.

**Comment by TobiDoesMC** [comment]
![2017-03-28_15 55 58](https://cloud.githubusercontent.com/assets/26752168/24458668/d3329ae8-1456-11e7-899f-b0fefebf2e69.png)
as i said the fast that i have the right items in the table with it next to a shrine i dont understand iwhy i cant get the wand

**Comment by HellFirePvP** [comment]
This has also been reported in the past - #14 

Try removing mods and create new worlds with the potential offenders removed.

**Comment by Saereth** [comment]
What is that mod that adds the armor display on the left there? Actually can you give a complete modlist, also important to know if you're using sponge or not.  I can help test once I have that

**Comment by TobiDoesMC** [comment]
i have over 122 mods installed
![2017-03-29](https://cloud.githubusercontent.com/assets/26752168/24471104/4d6322ca-147e-11e7-80a9-defba81af5c9.png)
![2017-03-29 1](https://cloud.githubusercontent.com/assets/26752168/24471108/500f05b6-147e-11e7-8731-6e66a42e8c66.png)
![2017-03-29 2](https://cloud.githubusercontent.com/assets/26752168/24471111/526ecdc8-147e-11e7-9c85-0d39339a57dc.png)
![2017-03-29 3](https://cloud.githubusercontent.com/assets/26752168/24471113/54b91ac0-147e-11e7-922b-f0ef02189f27.png)
![2017-03-29 4](https://cloud.githubusercontent.com/assets/26752168/24471116/5604ce38-147e-11e7-8a4a-9f327adf62db.png)
![2017-03-29 5](https://cloud.githubusercontent.com/assets/26752168/24471119/57db52d6-147e-11e7-91bd-82faf62127f8.png)
![2017-03-29 6](https://cloud.githubusercontent.com/assets/26752168/24471121/59916b2e-147e-11e7-8ab4-59cde88e09ee.png)

**Comment by TobiDoesMC** [comment]
this is the easiest way to give the full mod list

**Comment by HellFirePvP** [comment]
i'm almost certain there is a cleaner way of giving me the modlist. Regardless, i didn't see one of the "usual" mods that cause this in there, so i'd - again - suggest to try binary-split search through your modlist and try find the mod that's causing this.

Also, as i saw OfflineSkins in your modlist: AstralSorcery will most likely run into issues on offline servers and i will *not* give support for such servers/players, no matter the issue.

**Comment by TobiDoesMC** [comment]
i usedd that to test i can take it off

**Comment by VallenFrostweaver** [comment]
I'm having a similar issue but you can pull an "invisible" wand out of the result space and it's then crafted. Same with some other items too. Looking into what mod interaction is causing it. I'll let you know tomorrow tho as it's late.

**Comment by HellFirePvP** [comment]
This is often caused by another mod overriding the way the crafting table works or overriding the crafting table itself completely. This results in the problem that the client doesn't know where the crafting table is in-world, but the server knows. So the crafting recipe is invalid for the client, but valid for the server; That way you can pull it out of the result slot eventhough you cannot see the item...

**Comment by VallenFrostweaver** [comment]
Excellent. That narrows it down to very few mods. Thanks

**Comment by VallenFrostweaver** [comment]
I've tested this with only Astral Sorcery, install of any level of Forge, and vanilla 1.11.2 and I still get the same results. I fly to a Shrine, hop under it, place the crafting table (and the light connects to it), try crafting the wand and it's invisible but I can pull it out of the table crafted and then it's visible again.

**Comment by HellFirePvP** [comment]
'[main/ERROR] [FML]: The coremod hellfirepvp.astralsorcery.core.AstralCore is requesting minecraft version 1.10.2 and minecraft is 1.11.2. It will be ignored.'

i am retarded. nvm.
