### ISSUE TITLE
Miner's delight perk not going away

### ISSUE THREAD

**Issue by Jacencaedus** [HellFirePvP/AstralSorcery#890]
I needed to make a mob spawner, so I needed to get rid of miner's delight as it kept lighting up the room, however when I un-attuned from Vicio, the perk stayed active.  I even attuned to a different constellation and it remained. The modpack I use is Enigmatica 2 Expert version 1.39a, forge version 14.23.4.2751, and after I asked on the discord, I was told you would need the .astral file, so I have attached that

[e199c488-cb9f-48a5-8055-2b3ad9f26c1f.zip](https://github.com/HellFirePvP/AstralSorcery/files/2507806/e199c488-cb9f-48a5-8055-2b3ad9f26c1f.zip)

**Comment by HellFirePvP** [comment]
Seems rather odd. You do not have the perk in your list of gained perks anymore either.
Might be that a server restart is enough to fix it? Idk. I mean, for all intents and purposes, it should be gone after a restart. Regardless, AS 1.10.X will change the perk system entirely, so this isn't relevant anymore then...
