### ISSUE TITLE
Attunement Perk Glitch

### ISSUE THREAD

**Issue by Logantastic** [HellFirePvP/AstralSorcery#893]
Currently running Astral Sorcery 1.10.1.
As soon as I reached Level 20 in my Attunement Perk Tree, my game had [this](https://paste.dimdev.org/eboyajohig.mccrash) crash. (Which was caused by an outdated version of NotEnoughIDs, I believe). However, upon updating NotEnoughIDs and restarting Minecraft, I continued to try to level up my attunement, but subsequent level ups did not give points to spend on the tree. Using an Irradiant Star gives you all the points that you would have had, but does not fix the problem.

**Comment by HellFirePvP** [comment]
Did you allocate any of the Epiphany nodes or the Singularity node by any chance?

**Comment by HellFirePvP** [comment]
Try again with AS 1.10.2 since i suspect perks granting free perk-points being at fault for this misbehavior.
