### ISSUE TITLE
CRASH when placing Tree Beacon

### ISSUE THREAD

**Issue by Akaruz64** [HellFirePvP/AstralSorcery#894]
Don't know if this issue has been reported, or if anyone else is having it, but i get a crash when placing a Tree Beacon, didn't happen in the previous version.

MC 1.12.2
Forge 2772
AS 1.10.2

https://pastebin.com/fdfuYsQ0

**Comment by Doomgull** [comment]
Cme's are unfortunate to try to diagnose. Does it happen when you try to place the tree Beacon more than once? Where are you trying to place it, and in what dimension? Were there any tree saplings that could have grown at the same time? When you say previous version, do you mean 1.9.4? I don't recall the tree Beacon having any code change, so...

**Comment by Akaruz64** [comment]
Yeah, i had this crash when placing the Beacon over a marble block (the "clean" one), in the over-world without any saplings in range of it, I had no problem in 1.9.4, only tried once, i will make a new world to test this

**Comment by Doomgull** [comment]
I'm not seeing this with only AS.
