### ISSUE TITLE
CraftTweaker integration: Unable to remove altar upgrade recipe

### ISSUE THREAD

**Issue by thehobojoe** [HellFirePvP/AstralSorcery#896]
Adding an altar upgrade recipe works correctly with:
```
mods.astralsorcery.Altar.addDiscoveryAltarRecipe(
	"astralsorcery:shaped/internal/altar/upgrade_tier_2", 
	<astralsorcery:blockaltar:1>, 700, 100, [
            null, null, null,
            null, <minecraft:grass>, null,
            null, null, null]);
```

Removing an altar upgrade recipe with the same registry key does not work:

```
mods.astralsorcery.Altar.removeAltarRecipe("astralsorcery:shaped/internal/altar/upgrade_tier_2");
```

With the error: 
```
[AstralSorcery Altar Crafting] Could not find recipe to remove with name astralsorcery:shaped/internal/altar/upgrade_tier_2
```

The same thing happens with further upgrade tiers.

CraftTweaker: 4.1.11
Astral Sorcery: 1.10.3

**Comment by wamc2017** [comment]
Hmm, Crafttweaker removes all recipes first, then adds new ones, so it can't remove anything which is added by itself...
The original recipe name is "astralsorcery:shaped/internal/altar/upgrade_tier2" so no "_" between "tier" and "2" which works fine on my side.

**Comment by Doomgull** [comment]
You need to use a different name for the second recipe you want added.

**Comment by thehobojoe** [comment]
Thank you both, issue resolved.
