### ISSUE TITLE
Anvil will not apply Enchantments higher than vanilla levels

### ISSUE THREAD

**Issue by NimonoSolenze** [HellFirePvP/AstralSorcery#897]
I know this issue isn't inherent in Astral Sorcery, but I felt I should let you know about it anyway- If you use the Stellar Refraction Table to apply an enchantment directly to a tool, the enchantment applies properly, even if the level is above the vanilla limit. However, if you instead put it on a Book, or use a machine from another mod that pulls the enchantments off the tool and puts them in a Book, an Anvil will allow you to use the enchantment, BUT it lowers the level down to the vanilla cap. This makes enchanting Books using Horologium absolutely pointless, and hinders other Constellations that apply enchantments above the vanilla max that will have an effect. I'm not sure what could be done about this, personally, unless it's a conflict with another mod, but I still felt I should notify you about this.

EDIT: Did forget one thing- Modded machines that apply Enchantments directly, such as Industrial Foregoing's Enchantment Applicator, DO work as intended with higher-than-max enchantments, but I do still feel this was worth reporting since the typical idea would be to use an Anvil...

Version: AS 1.10.3
Tested in both Singleplayer and Multiplayer

Other mods installed:
Uncrafting Table
Actually Additions
AgriCraft
Akashic Tome
AppleSkin
Baubles
Better Builder's Wands
Biomes O' Plenty
Blood Magic
Botania
Chisel
Chisel & Bits
CoFH Core
CoFH World
CraftTweaker
Creeper Confetti
Ender Storage
Extra Utils 2
Extreme Reactors
Flux Networks
Forestry
Gendustry
HammerCore
Immersive Engineering
Industrial Foregoing
Instant Unify
Iron Chest
Magic Bees
Mantle
Mekanism (+Generators, Tools)
MineTweaker Recipe Maker 
Netherending Ores
OpenBlocks
OpenModsLib
Oreberries
PlusTiC
Psi
RebornCore
Reborn Storage
Recurrent Complex
Redstone Flux
Refined Storage
ResourceLoader
RFTools
RFTools Control
Silent Boss
Simply Jetpacks 2
Solar Flux Reborn
SonarCore
Steve's Carts
TConstruct
Telsa Core
Thaumcraft
Thermal Dynamics
Thermal Expansion
Thermal Foundation
Tinkers' Addons
Tinkers Tool Leveling
Veinminer
Waystones
ZeroCore

**Comment by Doomgull** [comment]
It's an issue with vanilla code, you would need to use a mod that expands out the vanilla enchanting mechanics so that doesn't happen. This is not a bug within the mod, this is a limitation of vanilla Minecraft being imposed.
