### ISSUE TITLE
Tree Beacon is ticking while unloaded in spawn chunks

### ISSUE THREAD

**Issue by terrapin47** [HellFirePvP/AstralSorcery#900]
The Tree Beacon, when placed within spawn chunks and unloaded, still ticks.  This can cause a server to lock up if the beacon is unloaded for a long period of time and then loaded.  

Checking the `/blockdata` of a tree beacon within spawn chunks shows this to be true, as it will increase regardless of being loaded or not.

**Comment by Doomgull** [comment]
The pseudo-load around spawn chunks where tiles are ticked but not entities.
