### ISSUE TITLE
[Suggestion] Ritual anchor stays linked after being broken

### ISSUE THREAD

**Issue by Dalois** [HellFirePvP/AstralSorcery#902]
When trying to use the Bootes ritual in a compact machine I realized I had no way to link it as the ritual was in the Overworld. Various cross dimensional teleporting I tried prevented linking as well. (RFtools, FTBUtil, vanilla nether portal just because.) I figured you had probably already considered it, but I didn't see it suggested anywhere.

Sorry if this wasn't a proper place to suggest something.

**Comment by HellFirePvP** [comment]
inter-dimensional linking will not be supported, no.
The title of this is also misleading :P
