### ISSUE TITLE
Fatal error when discovering a new constellation

### ISSUE THREAD

**Issue by Philosyang** [HellFirePvP/AstralSorcery#904]
#### Issue Description:
Multiplayer connection terminates when discovering a new constellation with a telescope based on a constellation paper.

#### What happens:
Player's connection got terminated and did not discover the constellation.

#### What you expected to happen:
Player discovers the constellation.

#### Steps to reproduce:

1. Wait till night.
2. Open a telescope.
3. Try linking the stars to discover a new constellation.
4. When finishing the final stroke, the connection terminated.

[video demo](https://mega.nz/#!cT4HkAZC!dHtDuDSIis_QG5Au_GMk0n4ifzQM8N5gF8G2ACnCRmU)

[server-side log](https://github.com/HellFirePvP/AstralSorcery/files/2569018/AS_crash.log)

____
#### Affected Versions:

- AS: 1.10.3
- Minecraft: 1.12.2
- Forge: 14.23.5.2768

**Comment by Doomgull** [comment]
Replicate without sponge.

**Comment by jinkhya** [comment]
Is there anything that can be done to work around it? Also experiencing this on our Revelation Server. 
Is there a command or a file to edit for example?

**Comment by Doomgull** [comment]
Yes, there is an astral sorcery / command that is got its own help file that you can access, or used tab complete to manually set constellation discovery.

Start with "/astralsorcery help"
