### ISSUE TITLE
The Knowledge from the shooting star disappears

### ISSUE THREAD

**Issue by VictorScrooge** [HellFirePvP/AstralSorcery#905]
After i collected one of the containers and get the knowledge scroll from it, it is disappeared after i restart the game. No error, crash, what so ever. Just vanished.

**Comment by Doomgull** [comment]
@VictorScrooge @wamc2017 please confirm that the directory being written to has write permissions the whole way down, please.

**Comment by wamc2017** [comment]
Yeah, there's definitely write access to the file. I checked with NBTExplorer:
![1](https://user-images.githubusercontent.com/33242447/48640089-e68b6100-e9d5-11e8-85e5-fe10c6e223ae.png)

Seems to be an issue with loading the file, when I restart the instance...

**Comment by HellFirePvP** [comment]
THAT could be it
