### ISSUE TITLE
Request: Gamestage integration for perks

### ISSUE THREAD

**Issue by Saereth** [HellFirePvP/AstralSorcery#907]
It would be very nice if instead of disabling the perks entirely we could have the option to stage them. A prime example would be turning stone to ore perk, if there was gamestage integration we could make it so people could not unlock that perk until they have found the aevitas paper, same of the other perks. With this integration we could create an even more interactive play experience with the pack by requiring the players to fight certain bosses and do certain progression steps to unlock access to those perks. Would be really sweet :P

**Comment by HellFirePvP** [comment]
Implemented feature: Level Cap can now be defined through gamestages.
