### ISSUE TITLE
Formation Wand mixes up Stone and Cobblestone

### ISSUE THREAD

**Issue by Svish** [HellFirePvP/AstralSorcery#909]
Using the Formation Wand, after having right-clicked plain regular stone, if I have both stone and cobblestone in my inventory, it will place stone and cobblestone kind of randomly...  rather annoying 🤔

Seems to happen when I select cobblestone too, i.e. when I have both stone and cobblestone in my inventory it will place both...

![2018-11-17_17 39 11](https://user-images.githubusercontent.com/142162/48663388-bc967500-ea8f-11e8-9ad8-544567e16c90.png)

**Comment by Svish** [comment]
Hm... just noticed the two types being shown in the top left corner... seems I can right-click more than one thing... what is this feature? How does it work? Is this documented somewhere? Can't remember having read about it in the book... 🤔

**Comment by Doomgull** [comment]
Its in the patch notes for the 1.10 release.

**Comment by Svish** [comment]
@Doomgull Where are those?

**Comment by Doomgull** [comment]
Up on curse, or in the Discord release section.
