### ISSUE TITLE
Is this right, 1.11.2

### ISSUE THREAD

**Issue by darkshadow543** [HellFirePvP/AstralSorcery#91]
Used the resonator to find the best spot, however, the table does not gather enough starlinght
![2017-03-29_21 20 29](https://cloud.githubusercontent.com/assets/14943673/24483388/cde1c8f6-14c5-11e7-9d89-c49f810d446f.png)
![2017-03-29_21 20 33](https://cloud.githubusercontent.com/assets/14943673/24483390/d04fc958-14c5-11e7-84ec-394599bb4c87.png)
![2017-03-29_21 20 38](https://cloud.githubusercontent.com/assets/14943673/24483392/d258261e-14c5-11e7-9ca4-190849128e40.png)

**Comment by darkshadow543** [comment]
![2017-03-29_21 24 08](https://cloud.githubusercontent.com/assets/14943673/24483427/0ebea628-14c6-11e7-9898-793abe6b91fd.png)
From a better perspective

**Comment by HellFirePvP** [comment]
Seems like you forgot that the height/y-position of the altar matters aswell. ;)

**Comment by DietmarKrause** [comment]
I personally think this is a problem. You will hardly find a "blue" position in the right y-level (what will that be ? y=100? y=150?), especially in older bioms o plenty worlds. That means you will have to build ridiculously high towers from 60 to 150 (?) only to get enough light for the highest tier of the altar. Suggestion: playable enhancement of the Star-light, perhaps the floating crystals to add them somehow to the Altar to let it i a slightly lower y level. The crystals themself should be buildable in lower levels. Or anything similar.

**Comment by HellFirePvP** [comment]
An option to "avoid" having to find spots with the resonator was/is added next version.
Also, "good spots" are based on x/z coordinates. The y-level doesn't matter for the resonator-spots themselves.
Additionally, if you're to progress into the currently last stage in progression, you can just link a crystal to the altar via the 'starlight network' - so linking tool & optionally lenses and stuff. There will be an additional clarification research-node in the next version mentioning the general philosophy behind the starlight network.

**Comment by DietmarKrause** [comment]
good to know. But doesnt help if the crystal itself seeds "too much" starlight (as in my case). My tower is already 40 blocks high... and i have to add at least 20 (?) or so levels. I had to re-buold it already 2 times, for there is now war to tell, if the spot is "good " in terms of y -level for future progression and until now no way to enhance it without building the whole thing higher than before. Suggestion: make the crystal "cheaper" in terms of light (for getting it) and then 2 or more of them with lenses to enhance the altar without re-build the thing every two days.
