### ISSUE TITLE
Celestial Collector Crystal appeared out of nowhere and somehow won't allow my setup to work

### ISSUE THREAD

**Issue by halpishooes** [HellFirePvP/AstralSorcery#913]
*Minecraft: 1.12.2
*Forge: 14.23.5.2768
*AS: 1.10.3

I broke a Collector Crystal that I kept on top of my altar for aesthetic reasons and there's a Celestial Collector Crystal there instead. It's graphical, so I can't remove it. What should I do?

![5yzsal2](https://user-images.githubusercontent.com/44909912/48733900-06679280-ec2b-11e8-92aa-274619f1ff6b.png)

**Comment by Doomgull** [comment]
Thats part of the altar.

**Comment by HellFirePvP** [comment]
> and somehow won't allow my setup to work

And it's not that visual that makes your altar not work.
