### ISSUE TITLE
Crash Creando un mundo nuevo

### ISSUE THREAD

**Issue by lmentrix2** [HellFirePvP/AstralSorcery#916]

**Comment by lmentrix2** [comment]
[crash-2018-11-21_19.12.21-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/2606080/crash-2018-11-21_19.12.21-client.txt)

**Comment by lmentrix2** [comment]
Ayudaaa con la version actual de astral sorcery 1.10.3 uso launcher Fenix mi version de open Gl 2.1

**Comment by Doomgull** [comment]
That error is vanilla only, it appears. There is no astral sorcery in the trace.

The version of Forge is at fault. Revert to the recommended version, the latest is broken: 
![image](https://user-images.githubusercontent.com/12677933/48873941-9d188880-edbe-11e8-8f2a-a0d1dcd4bec2.png)
