### ISSUE TITLE
Drawing Constellations Crash/Kick (SpongeForge)

### ISSUE THREAD

**Issue by krisjenner** [HellFirePvP/AstralSorcery#917]
AS v1.12.2-1.10.2
Sponge v7.1.0

player gets kicked from server on attempting to draw constellations [[log](https://pastebin.com/Y5ppvw9B)]
This doesn't happen for him in singleplayer

**Comment by Doomgull** [comment]
Replicate without sponge, please.

**Comment by Doomgull** [comment]
#904

**Comment by krisjenner** [comment]
It does not happen without Sponge. I reported on Sponge discord and was told “**<electroniccat>** astral sorcery is playing with advancements async which isn't safe” // “**<electroniccat>** The exception is caused through sponges code, but that's because sponge is applying that limitation properly as opposed to allowing stuff to mess with it from another thread and cause issues elsewhere”

I hope this helps

**Comment by Doomgull** [comment]
This was closed as a duplicate to an issue marked fixed for next release because it is
 already fixed for the next release.
