### ISSUE TITLE
Sextant Not Showing Navigational Stars

### ISSUE THREAD

**Issue by AwesomeAlec1** [HellFirePvP/AstralSorcery#918]
Hi, I'm playing a modified version of the Direwolf20 1.12.2 pack, with astral sorcery v1.9.4 included.

When I use the sextant (augmented or not, makes no difference), the stars that represent structures appear in the viewport just fine, and even lets me drag the structure images over them to "activate" them. However, when I exit the viewport and look for the star in the night sky, it's nowhere to be found. 

I've tried messing with my graphics settings to no avail, and seeing there haven't been any instances of this issue (as far as I can tell), I'm guessing it isn't an issue with this mod, but I figured I'd post the question here just to be sure.

**Comment by Doomgull** [comment]
What is your render distance?

**Comment by AwesomeAlec1** [comment]
I messed around with my chunk render distance, with it usually sitting around the 6-10 chunk mark, but to test if that was an issue, I set it to the maximum (~32 chunks), and the navigational star still failed to show.

**Comment by Doomgull** [comment]
If it doesn't show at 10, you are either using it incorrectly, or there is a shader or something conflicting.

I would recommend watching Vallen's video on the sextant.
