### ISSUE TITLE
StackOverflow crash when using CraftTweaker util method getCrystalORIngredient

### ISSUE THREAD

**Issue by thehobojoe** [HellFirePvP/AstralSorcery#921]
Putting all the ingredients in the crafting grid with a recipe using a rough match crystal causes a StackOverflow.

Example recipe:

```
var livingrock = <botania:livingrock>;
var crystalAny = mods.astralsorcery.Utils.getCrystalORIngredient(false, false);
recipes.addShaped(<botania:pool>,
	[[null, null, null],
	[livingrock, crystalAny, livingrock],
	[livingrock, livingrock, livingrock]]);
```

Issue can be replicated in a vanilla workbench (using fastworkbench, unknown if this error occurs without) and a Tinker Construct workbench.

Crash:
https://pastebin.com/75nLnqQD

Versions:
AS: 1.10.3
CraftTweaker: 4.1.11
Forge: 14.23.5.2768

**Comment by Doomgull** [comment]
Can you try without FastBench? Need to narrow this one down.

`Details:
    Screen name: shadows.fastbench.gui.GuiFastBench
    Mouse location: Scaled: (283, 83). Absolute: (1132, 685)
    Screen size: Scaled: (480, 255). Absolute: (1920, 1017). Scale factor of 4`

**Comment by vanityset** [comment]
I was able to re-produce this crash today using the same recipe as above and a Tinker's Construct crafting table.

Crash log:
https://pastebin.com/Ru03hrhF
