### ISSUE TITLE
Crash on changing dimensions via Advanced rocketry rocket

### ISSUE THREAD

**Issue by Saereth** [HellFirePvP/AstralSorcery#925]
not sure what all's to blame here, this is for interactions so large list
https://hastebin.com/jetocobiyo.rb

this is the dev version 1.10.4

**Comment by Doomgull** [comment]
Same issue as #762, gotta be fixed on plustic side.

**Comment by Saereth** [comment]
fixed via
https://github.com/Landmaster/PlusTiC/commit/df5a8f921f7acc6c8ce6920949c6717eb407c415
