### ISSUE TITLE
Would it be possible to add oredict to the grindstone?

### ISSUE THREAD

**Issue by kragnoth** [HellFirePvP/AstralSorcery#927]
Right now, I am using this abomination to add ore chunks to the grind stone
https://pastebin.com/CapQJMUX

Please, if you value your sanity, don't look too deeply at the evil that is that string hack.

Using that as a base, I can finally use the grindStone.addrecipe(input,output,chance) with just a little more debugging.

**Comment by Doomgull** [comment]
It should support it already.

**Comment by kragnoth** [comment]
public static void addRecipe(IItemStack input, IItemStack output, float doubleChance) 

IItemstack does not support oredict.  I could iterate through all items, but the ores I want to use are added to oredict after CrT runs scripts.

**Comment by kragnoth** [comment]
So, after going through some extra steps, it looks like the oredict is added after crafttweaker runs its scripts on ore stone variants and jaopca ore chunks.  So I'm not sure having oredict support on this recipe would help.
