### ISSUE TITLE
Es raro El crash

### ISSUE THREAD

**Issue by lmentrix2** [HellFirePvP/AstralSorcery#928]

**Comment by lmentrix2** [comment]
Yo abri el minecraft con astral sorcery 8:00am con el forge 1.12.2-14.23.4.2758 entre ejecute un mundo normal plano y por defecto me ando de maravilla haora cuando intento crear o entrar en un mundo me crashea, con la version Astral Sorcery 1.12.2 1.10.2 despues Astral Sorcery 1.12.2 1.10.3, alas 6:30pm ayudaaaaa

**Comment by Doomgull** [comment]
Can you provide a crash log to help troubleshoot?

**Comment by Saereth** [comment]
Necesitamos el informe de bloqueo de su instancia de Minecraft. Puedes encontrarlo en la carpeta "crash-reports".
