### ISSUE TITLE
Crash with Avatar Mod 2: Out of the Iceberg

### ISSUE THREAD

**Issue by FavouriteDragon** [HellFirePvP/AstralSorcery#929]
So, people have reported that using your mod with mine crashes on start up. Their forge version was 2768, and here's the crash report that they provided:
https://pastebin.com/yL52REXw
While I may be able to prevent this crash, it would almost certainly break the mod for the player. Any idea why this is happening?

**Comment by Doomgull** [comment]
AS isn't in the trace, so unsure what it may be.

**Comment by FavouriteDragon** [comment]
Yeah I didn't see it either, but apparently removing AS stopped the crash.
Does AS modify anything huge about the player?
On a side note, we're going to be reworking how player data is saved for 1.13, so that might help.

**Comment by FavouriteDragon** [comment]
Cause that error implies the player doesn't have a UUID on mojang's database.

**Comment by Doomgull** [comment]
Uuid, or mojang provided uuid? Lots of mods provide a fake uuid for their fakeplayer entity.

**Comment by FavouriteDragon** [comment]
Mojang provided. It's why the mod doesn't work with cracked accounts.

**Comment by HellFirePvP** [comment]
Not an AS issue and we don't provide support for cracked.
Buy the game.

**Comment by FavouriteDragon** [comment]
Oh it's a cracked error?
I don't think it is :P
Since it doesn't happen with Astral Sorcery AND Avatar installed.
More information according to the player:
"Hey, instead of deleting the mod, remove dimension 0 from WeakSkyRender in the Astral Sorcery, that fixed the issue for real."

**Comment by Doomgull** [comment]
That has zero influence or even interaction with the crash you provided. That just prevents the sky shader from being populated.

Red herring and unrelated.

**Comment by FavouriteDragon** [comment]
Ok.
Yes, I realize that, I was just wondering if it might've helped you at all.
Yeah I think if AS is creating a fake player, then the mod is probably trying to use that fake player, and straight up crashes. I can fix that, if that's the issue.

**Comment by Doomgull** [comment]
AS doesn't directly but it does interact with players and block certain accesses.

**Comment by FavouriteDragon** [comment]
Ok I'll add a fix for that,- it might break bending, but at least it shouldn't crash.

**Comment by FavouriteDragon** [comment]
Theoretically fixed on my side
