### ISSUE TITLE
Night Vision enchantment causes excess lag

### ISSUE THREAD

**Issue by AKA-Syenite** [HellFirePvP/AstralSorcery#930]
https://github.com/HellFirePvP/AstralSorcery/blob/a2725884952bedcf04bf07d965e97923270f1615/src/main/java/hellfirepvp/astralsorcery/common/enchantment/EnchantmentNightVision.java#L34

When an item with the night vision enchant is worn, it applies the potion effect every tick, which causes comparatively large amounts of lag relative to other types of enchantments.

**Comment by Doomgull** [comment]
Do you have profiling to show this being an issue? "More expensive than other enchantment applications" isn't really a good measuring metric.

**Comment by AKA-Syenite** [comment]
When on a terrasteel helm
https://i.imgur.com/hwgPU6y.png
https://i.imgur.com/iQNshdE.png

A fluxed helmet with the same enchant clocked at 562-660 us/t

Without the enchant, the player clocked at about 38 us/t, depending on what else was equipped. The largest spike was definitively the night vision enchantment.

**Comment by Doomgull** [comment]
So...1/2 of a millisecond. Not a concern.
