### ISSUE TITLE
No stars showing up on the telescope GUI [Enigmatica 2]

### ISSUE THREAD

**Issue by doelling** [HellFirePvP/AstralSorcery#934]
I'm currently playing Enigmatica 2 (MC 1.12.2) through the Twitch app, which has AS (v.1.10.3) installed. When I right click on the telescope, the GUI shows up, but there are never any stars, just black rectangles. Even when rotating the telescope via the arrows, still no stars. I am doing this at night. I have disabled all resource packs and still nothing.

**Comment by Doomgull** [comment]
Screenshots of telescope location with regsrd to nearby terrain?

**Comment by doelling** [comment]
![as1](https://user-images.githubusercontent.com/45838137/49916629-d8602180-fe69-11e8-99db-a218b137c46d.png)
![as2](https://user-images.githubusercontent.com/45838137/49916630-db5b1200-fe69-11e8-8847-51feef0bad09.png)
![as3](https://user-images.githubusercontent.com/45838137/49916635-ddbd6c00-fe69-11e8-96b2-1ed1f894e2e3.png)

**Comment by doelling** [comment]
Ok, so, I just moved the telescope out 1 block (away from the cobblestone and tank with liquid starlight) and now it works perfectly
