### ISSUE TITLE
Metadata not supported by Waterfall / players can't connect to server at all

### ISSUE THREAD

**Issue by krisjenner** [HellFirePvP/AstralSorcery#937]
https://github.com/PaperMC/Waterfall/issues/331

**Comment by krisjenner** [comment]
I know it's astral as it didn't happen until i teleported to the players astral set up

**Comment by krisjenner** [comment]
player had just placed  a "Lightwell" and "containment chalice"

**Comment by Doomgull** [comment]
Replicate without sponge, please. Please also see the linked 136 issue from the above ticket.

Also, AS isn't in that trace.

**Comment by Doomgull** [comment]
@krisjenner any update on my above request?
