### ISSUE TITLE
Game crashes when using Shifting Star

### ISSUE THREAD

**Issue by MobiusFlip** [HellFirePvP/AstralSorcery#94]
As soon as I use the Shifting Star to reset my attunement, my game crashes. If I log back in and restart the game, I'm properly unattuned and can reattune myself to any of the major constellations, but the Shifting Star is not used up. The crash report is [here,](https://pastebin.com/XQs2yQ5p) from a test with only Forge and Astral Sorcery.

**Comment by HellFirePvP** [comment]
#81 duplicate.
