### ISSUE TITLE
Crash with v1.10.5 with JEI recipe transfer

### ISSUE THREAD

**Issue by Saereth** [HellFirePvP/AstralSorcery#944]
crash report: https://gist.github.com/Saereth/f09c9426dc94e9991d1d7866f6847f46

AS version: astralsorcery-1.12.2-1.10.5
JEI Version: jei_1.12.2-4.14.3.238
forge: 14.23.5.2782

steps to reproduce: open iridescent altar, try to view recipe for a vorux constellation paper I have in my inventory (which has a custom recipe that uses the iridescent table) crash occurs.

I can view the custom recipe outside of the altar's UI without crashing and it is correct. Relevant CT scripting if needed:

`	#Vorux
	mods.astralsorcery.Altar.removeAltarRecipe("astralsorcery:shaped/internal/altar/constellationpaper/vorux");
mods.astralsorcery.Altar.addTraitAltarRecipe("interactions:vorux", <astralsorcery:itemconstellationpaper>.withTag({astralsorcery: {constellationName: "astralsorcery.constellation.vorux"}}), 4500, 400, [
	<botania:tinyplanet>, salisMundis, <botania:tinyplanet>,
	aquamarineGem, parchment, aquamarineGem,
	<botania:tinyplanet>, scribingTools, <botania:tinyplanet>,
	illuminationPowder,illuminationPowder,illuminationPowder,illuminationPowder,
	<ore:dustAstralStarmetal>,<ore:dustAstralStarmetal>,<ore:dustAstralStarmetal>,<ore:dustAstralStarmetal>,<ore:dustStellarAlloy>,<ore:dustStellarAlloy>, null, null, null, null, null, null]);	`

**Comment by SiliconEnt** [comment]
I built a stripped down pack specifically to generate a clean crash report, and can confirm that this crash occurs in a newly created world save with no mods beyond Forge, JEI, Baubles and AstralSorcery. It is also not limited to the Iridescent Altar or the Vorux recipe – I haven't done too much testing, but it also affects the Luminous Crafting Table and its recipes.

Crash report is attached.

[crash-2018-12-22_09.30.00-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/2705457/crash-2018-12-22_09.30.00-client.txt)

**Comment by Doomgull** [comment]
Known. It is why jei requirements weren't updated.

**Comment by HellFirePvP** [comment]
Fixed with 1.10.6
