### ISSUE TITLE
CraftTweaker's modifyPerk is bugged

### ISSUE THREAD

**Issue by Grimtrap** [HellFirePvP/AstralSorcery#945]
Doesn't seem to multiply the values on a lot of perks properly
![2018-12-22_13 49 09](https://user-images.githubusercontent.com/30621588/50377722-74b7c000-05f0-11e9-918c-66fd3d94c9d1.png)
![2018-12-22_13 44 59](https://user-images.githubusercontent.com/30621588/50377721-6d90b200-05f0-11e9-87da-dacf3bef4950.png)
The lines of script that I used to modify those perks
![image](https://user-images.githubusercontent.com/30621588/50377728-826d4580-05f0-11e9-98a5-b0b4135bab94.png)
![image](https://user-images.githubusercontent.com/30621588/50377734-91ec8e80-05f0-11e9-8ed3-24b705245489.png)

**Comment by HellFirePvP** [comment]
Fails to apply properly for stacking multipliers. /note-end

**Comment by HellFirePvP** [comment]
Fixed with 1.10.6
