### ISSUE TITLE
AS issue with gamestages

### ISSUE THREAD

**Issue by Yoghurt4C** [HellFirePvP/AstralSorcery#947]
https://pastebin.com/H1dsqETW

mods present: astral sorcery, crafttweaker, gamestages, itemstages, chisel (as example);
one line `mods.ItemStages.stageModItems("chisel", "chisel");` makes AS spew out an NPE and create a crashlog, and somehow breaks progressing through AS;
this behaviour only seems to occur on AS versions after **1.10.4**, where AS' internal gamestage support was added

**Comment by HellFirePvP** [comment]
Not connected to whatever you reported there btw.
