### ISSUE TITLE
Perk Crashes

### ISSUE THREAD

**Issue by Dayyer1** [HellFirePvP/AstralSorcery#949]
[crash-2018-12-24_17.31.16-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/2707825/crash-2018-12-24_17.31.16-client.txt)
[crash-2018-12-24_18.10.26-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/2707826/crash-2018-12-24_18.10.26-client.txt)

In the first crash, I clicked on a "15% perk effect increase" and it crashed.
I restarted the game and the perk was selected. I used an irradiant star, and I selected the same perk, and the game did not crash.
I then used another irradiant star, and the game crashed. (The second crash log.)

This was using AS version 1.10.7 and Forge 2796.

**Comment by Doomgull** [comment]
Do you have a list of all the perks you had assigned prior?

**Comment by Dayyer1** [comment]
I do not.
Here's another one. Forge version 2795.

[crash-2018-12-24_19.46.43-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/2707915/crash-2018-12-24_19.46.43-client.txt)

**Comment by HellFirePvP** [comment]
Supposedly fixed with a test-version?

**Comment by Dayyer1** [comment]
I think so.

**Comment by HellFirePvP** [comment]
Reopen if needed then..
