### ISSUE TITLE
[CTD] Compatibility crash, DRPMedieval

### ISSUE THREAD

**Issue by drakray** [HellFirePvP/AstralSorcery#95]
https://pastebin.com/AakEdWuw
Crash when placing Altar
MC 1.11.2
Forge 2262
AS 1.2.3 beta
[DRPMedieval](https://minecraft.curseforge.com/projects/dark-roleplay-medieval) 0.1.8

**Comment by drakray** [comment]
reported to DRPMedieval as well

**Comment by JTK222** [comment]
Fixed was an Issue on my end!
Thx for the report.

**Comment by drakray** [comment]
Working :D

**Comment by HellFirePvP** [comment]
uhhhh.... ok, thanks :P
