### ISSUE TITLE
Game Crash on Loadup.

### ISSUE THREAD

**Issue by SavageKiller13** [HellFirePvP/AstralSorcery#953]
While loading up a modpack with the latest version of the mod I have a crash saying the liquid starlight texture map is too large. Full crash log 
[crash-2018-12-27_00.28.06-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/2711807/crash-2018-12-27_00.28.06-client.txt)

**Comment by HellFirePvP** [comment]
Looks like minecraft can't create a texturemap large enough to fit all textures of the modpack you're playing.
This is a GL error and directly ties with the memory available on your graphics card. This is not something i can fix.
