### ISSUE TITLE
Client crash on MP server join 1.12.2 / 1.10.8

### ISSUE THREAD

**Issue by AnsuzThurisaz** [HellFirePvP/AstralSorcery#954]
Client loads fine in SP, crashes on server join with this output from server:
https://gist.github.com/AnsuzThurisaz/a051c052dbb46ecdc47715e8805d0a83

Client Crashlog:
https://gist.github.com/AnsuzThurisaz/b58f2a40ee4af8be433f6b430b7b0020

Forge 1.12.2 2796
Astral Sorcery 1.10.8

**Comment by Bluerobin427** [comment]
I have a similar crash. We removed the attunement altar placed in the world and there's still a crash: 
[crash-2018-12-30_21.40.10-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/2717684/crash-2018-12-30_21.40.10-client.txt)

**Comment by Doomgull** [comment]
That client.txt log is not related, @Bluerobin427 . It's for an NPE with perk mapping.

**Comment by zlainsama** [comment]
This happens to me too. I guess i should check issues before updating mods.

**Comment by HellFirePvP** [comment]
Fixed with 1.10.9
