### ISSUE TITLE
Client-side perk regen crash

### ISSUE THREAD

**Issue by Bluerobin427** [HellFirePvP/AstralSorcery#955]
I started with the same (or similar) issue as `[here](https://github.com/HellFirePvP/AstralSorcery/issues/954)` but we removed the attunement altar and now my crash log looks like this:
[crash-2018-12-30_21.40.10-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/2717706/crash-2018-12-30_21.40.10-client.txt)

From a very newbie modmaker perspective, seems related to genning a new perk tree for a client. Let me know if there's anything else I can do to help!

**Comment by HellFirePvP** [comment]
Fixed with 1.10.9
