### ISSUE TITLE
Rendering issues with Storage Drawers after updating Astral Sorcery?

### ISSUE THREAD

**Issue by ate0ate** [HellFirePvP/AstralSorcery#956]
This is kind of a strange one, but after using Astral Sorcery build 107 without issue for some time in a large personal pack, I updated to the recently released build 108 and promptly experienced some odd issues with the rendering of certain blocks, chiefly Storage Drawers' basic drawers. When using the addon Storage Drawers Extras, the basic drawers from that addon's variants fail to render a texture at all and instead display the usual purple missing texture. Oddly, opening a door using a redstone switch or placing a block near to the drawer fixes this until again interacting with the drawer. When using just the default Storage drawers' basic drawer it seems that the texture renders initially, but after placing an item in the drawer the block turns to face north despite its prior positioning and does not display the contents of the drawer at all. It seems as though certain updates in a chunk can trigger the drawers to render appropriately for a bit, but they again break whenever used. Very odd indeed. Downgrading back to Astral Sorcery build 107 does indeed fix the issue as well. This is all using forge 14.23.5.2796. I'm only posting the issue here at all because the issue comes and goes depending on the version of Astral Sorcery I use and the only mod changed at all has been Astral Sorcery. I'm not sure what further info I could provide other than I am using quite a large modpack, but again, It has been working as intended up to this point. Please let me know if I can provide any further information or assistance and please feel free to close the issue if this is the incorrect place to be presenting it. I apologize for bringing this here in that case, I am just at a loss as to the cause or how to proceed. Thank you.

**Comment by HellFirePvP** [comment]
You could start a new SP world and then see if it already happens if you on place a storage drawer down and nothing else in view. Until it happens again try find out which AS "thing" needs to be in view for this to start happening..

**Comment by ate0ate** [comment]
Well, I'm going to go ahead and close this as It seems whatever changes you made in build 109 have fixed the issue. I cannot reproduce it at all using that build. Just to be sure I'm not entirely insane, I again tried build 108 and sure enough the rendering issues happen every time. For me it doesn't matter if it is in a new world or not, the issue is there regardless of the presence of AS items/blocks or a new/old world. I have no idea what is happening, but the latest AS build is working just as well as build 107. I don't know if there is any useful information you can glean from any of this but, yeah, thanks!

I do not have enough knowledge of the game's inner workings to deduce anything myself, but it almost seems as though Storage Drawers was having issues saving or updating the state of its blocks. It was very odd, but while using build 108 I could tell something was initially amiss as the texture for the basic drawer was rendering purple in TOP while looking at it, but appeared fine in-world. There was also a strange "ghosting" that would happen that is normally not present when interacting with the drawers. For instance, whenever I placed a cobblestone into an empty drawer, initially the cobble block would appear briefly in front of the drawer as if I placed the block in the world before quickly vanishing and being accepted by the drawer. This only happened upon placing the first cobble into an empty drawer though. After that, if I added any further cobble, the texture would break and turn purple. If I took cobble out or put it back in or just further messed with it, the drawers would some times appear to vanish entirely resulting in the x-ray effect. This would also propagate to any other drawers visible in-game as well. 

I had the drawer placed six or seven blocks away from a door and pressure plate and every time I would use the door it fixed the texture temporarily, but the drawer was now facing north every time, no matter what direction it was in before. Exiting the world and loading it again would temporarily fix the textures as well. It's all very strange. I suppose the issue is moot at this point anyhow with the changes made in build 109 resolving matters, but hopefully you got something out of it all.
