### ISSUE TITLE
[Bug] Craft in Luminous Crafting Table erroneously awarded challenge completion

### ISSUE THREAD

**Issue by WhatThePuckPT** [HellFirePvP/AstralSorcery#957]
Title. When I crafted a Grindstone in the basic Luminous Crafting Table, it erroneously awarded me the completion of the whole line for the Starlight Crafting Altar.
If you need logs of something to see what the issue might be, say the path and what log - playing self-created modpack on Twitch Launcher.
Astral Sorcery version is 1.10.7.

**Comment by HellFirePvP** [comment]
outdated.
