### ISSUE TITLE
Ore Dict entries might be registered too late

### ISSUE THREAD

**Issue by tommyTT** [HellFirePvP/AstralSorcery#960]
#### Issue Description:
The ore dictionary entries from Astral Sorcery are empty when being accessed by a CraftTweaker script.

#### What happens:
In my CraftTweaker script I need to iterate through the items of certain ore dictionary entries, e.g. "gemAquamarine". This entry however doesn't have any items associated with it.

#### What you expected to happen:
When CraftTweaker runs the scripts the ore dictionary entries should be fully initialized from the Astral Sorcery mod itself.

#### Steps to reproduce:
1. Make a new CraftTweaker script that contains the following code:
```
print("OreDict entries for gemAquamarine:");
for item in <ore:gemAquamarine>.items {
  print(item.name);
}
```
2. Start Minecraft with Astral Sorcery and CraftTweaker installed.
3. Look into the crafttweaker.log file for the output.

This should print the name of the aquamarine item to the log file, but no iteration happens since the items from the mod are not yet registered.

#### Analysis
Looking at the Astral Sorcery code, I found that the ore dictionary items are registered during the [Init](https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/CommonProxy.java#L229) phase of Forge. The [Forge Docs](https://mcforge.readthedocs.io/en/latest/utilities/oredictionary/#registering-items-to-the-oredictionary) however suggest, this should happen during the PreInit phase after initializing the blocks and items. Please check to see, if the registration can/should be moved according to the documentation or if this needs to stay this way.

#### Affected Versions:
Minecraft: 1.12.2
Forge: 14.23.5.2780
Astral Sorcery: 1.10.3
CraftTweaker: 4.1.13

**Comment by Doomgull** [comment]
There's been a lot of changes with CT stuff. Please update to AS 1.10.9 or later and reproduce.

**Comment by tommyTT** [comment]
Same result with the latest versions of everything (as available on CurseForge):

Minecraft: 1.12.2
Forge: 14.23.5.2796
Astral Sorcery: 1.10.9
CraftTweaker: 4.1.13

**Comment by HellFirePvP** [comment]
Moved oredict registration directly after item registration now during registry-init
