### ISSUE TITLE
Called getProgress on neither server or client - what are you? (ic2 mining laser usage on smooth stone -> crash)

### ISSUE THREAD

**Issue by NoLoginFound** [HellFirePvP/AstralSorcery#963]
Crash log:
https://pastebin.com/T52fwuMh

What happens:
When a vanilla stone block (smooth stone?) is hit by ic2 mining laser in 'super-heat' mode, 'server' crashes ('server' since it's a singleplayer).
My guess that it happens because ic2 fake player extends EntityPlayer, not EntityPlayerMP (but I doubt this guess is helpful. Maybe fake player should have been filtered from any magics processing earlier in the code?).

What should happen:
(from ic2 wiki):When a super-heat laser is fired at a block such as smoothstone, where the 'normal' drop can be smelted into the block itself, the block will be dropped as if mined with a silk touch-enchanted tool

Mods involved (from modpack Enigmatica 2:Expert 1.48a):
industrialcraft-2-2.8.105-ex112
astralsorcery-1.12.2-1.10.9
(Thaumcraft-1.12.2-6.1.BETA26 ? or some of its addons?)

**Comment by HellFirePvP** [comment]
Any fakeplayer is a EntityPlayerMP - should it not be, then Ic2 breaks Forge behavior and thus detecting a fakeplayer could turn out weird..

**Comment by HellFirePvP** [comment]
On that note, such a system to catch fakeplayer-access to progression data is being caught and handled properly already. https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/data/research/ResearchManager.java#L91

**Comment by HellFirePvP** [comment]
Looking at their codebase and talking it through with one of IC2's developers, the irregularity lies on IC2's side. However, as they're not gonna adjust their code to newer standards, i'll go about to add _yet another_ specialcase to this...

**Comment by HellFirePvP** [comment]
Fixed on IC2's side with version 2.8.106-ex112 on curseforge.

**Comment by Shybella** [comment]
Is there anything to maybe hotfix this as modpacks don't update very often?

**Comment by Doomgull** [comment]
Yes. Update to the fixed-in ic2 release.
