### ISSUE TITLE
[BUG] Astral Tome rendering weird 

### ISSUE THREAD

**Issue by NightmareTwilight** [HellFirePvP/AstralSorcery#966]
![2019-01-06_08 56 26](https://user-images.githubusercontent.com/29397235/50733645-67bed300-1191-11e9-8bfb-56b7c3c16a3f.png)

It's only a problem in the RESEARCH tab, though Briliance area doesn't show _anything_.

![2019-01-06_09 01 02](https://user-images.githubusercontent.com/29397235/50733662-d69c2c00-1191-11e9-9bdb-88c9189109f9.png)

It get's even worse when only using Astral Sorcery 1.12.2-1.10.10, Baubles 1.12-1.5.2 and VanillaFix 1.1.1-132 with Forge 1.12.2-14.23.5.2796.

![2019-01-06_09 08 50](https://user-images.githubusercontent.com/29397235/50733732-4b239a80-1193-11e9-91a7-45aaf5992e7f.png)
![2019-01-06_09 13 51](https://user-images.githubusercontent.com/29397235/50733735-6d1d1d00-1193-11e9-9409-b85c5219c3a9.png)

**Comment by Doomgull** [comment]
Turn off AUTO scale, as specified on the curse page:
![image](https://user-images.githubusercontent.com/12677933/50736616-84590c00-118d-11e9-8c71-d955726b628f.png)

**Comment by NightmareTwilight** [comment]
My GUI setting is set to medium in all those pictures, though setting it to small, or large for that matter doesn't work.

![2019-01-06_09 06 58](https://user-images.githubusercontent.com/29397235/50738923-0884b100-11d9-11e9-95ed-f0568422371b.png)

**Comment by HellFirePvP** [comment]
Ever thought of. You know. Removing VanillaFix? It does a ton of hacky shit to manipulate render states.

**Comment by NightmareTwilight** [comment]
Hmm, that seems to have fixed it.
