### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by KamiSami** [HellFirePvP/AstralSorcery#968]
https://pastebin.com/NcJXCV71 This started to happen out of sudden, i suspect it's this mod since it mentions it in crash report?

**Comment by KamiSami** [comment]
Almost forgot to mention that im using astralsorcery-1.12.2-1.10.10  and forge-14.23.5.2797

**Comment by Doomgull** [comment]
No, you aren't. Log reports 1.10.9.

"astralsorcery-1.12.2-1.10.9.jar "

Update, this was already resolved.

**Comment by KamiSami** [comment]
Ah damnit! I just realized my server had outdated mod while my client had newest one, im sorry!
