### ISSUE TITLE
[Request] Prevent AS structures from spawning on transparent blocks

### ISSUE THREAD

**Issue by Kataiser9** [HellFirePvP/AstralSorcery#971]
I'm requesting this because the current interaction with Lost Cities spheres is [a little wonky](https://i.imgur.com/9ZExku5.png), as shown. 

Kind of a niche issue, I know, but there are other worldgen mods this could cause issues with, and I imagine it'd be straightforward to fix.

**Comment by Doomgull** [comment]
May be able to work around that using the existing configuration options to restrict spawning, for now.
