### ISSUE TITLE
Conversion wand TPS Tank

### ISSUE THREAD

**Issue by Chocopuffs** [HellFirePvP/AstralSorcery#972]
Conversion wand works fine on my server, but as soon as i use Infused wood as the replaceing or replaced block it lags the server to 2tps and takes a good 30 seconds to convert... it is strange how it works better with other modded blocks then it's own mod.

**Comment by HellFirePvP** [comment]
Lacks information. How is it used? Keep circumstances such as lighting updates when building "flooring" in a skyblock map or related in mind.

**Comment by Doomgull** [comment]
Looks like lighting updates based on that.

**Comment by Chocopuffs** [comment]
So is that on our server's end or mod side?

**Comment by Doomgull** [comment]
Should be serverside, but if you could run a visualvm profile while replicating, would help verify there's nothing being exacerbated by the mod.

**Comment by Doomgull** [comment]
@Chocopuffs just wanted to check in on this again, see if there was any profiling that had been done. I'm not seeing anything like this in my testing that's not related to lighting updates.
