### ISSUE TITLE
FTBQuests / Proper Tag Encapsulation

### ISSUE THREAD

**Issue by Vyraal1** [HellFirePvP/AstralSorcery#974]
Lat says it's not his mod - wat do?

https://github.com/FTBTeam/FTB-Quests/issues/144

**Comment by Doomgull** [comment]
Adding the tag is correct. If ftbq is doing something like blanket checking all nbt without regard for compound tags...dunno what to say. Perhaps try checking for including that? All instances of that item should contain the tag.
