### ISSUE TITLE
EnchantmentUpgradeHelper performance issue

### ISSUE THREAD

**Issue by Sir-Will** [HellFirePvP/AstralSorcery#975]
There are more enchantments where this looks the same.
![](https://i.imgur.com/vnxeOVi.jpg)
![](https://i.imgur.com/WGjXizX.jpg)

**Comment by Doomgull** [comment]
Need some context for what this actually represents for overall load.

**Comment by Sir-Will** [comment]
What do you mean?

**Comment by HellFirePvP** [comment]
You are pointing at something that's using so little of the time the snapshot prints that even the jvmprofiler rounds it to 0. Whatever you're trying to resolve as performance impact, something that gets rounded to 0% of time used is hardly what you're looking for.

**Comment by Sir-Will** [comment]
Where do you read 0%? It's 1.6% for isPlayerFakeMP which shows up for multiple other enchantments so it's more then 1.6%

**Comment by HellFirePvP** [comment]
Learn how to interpret jvm snapshots or take what you hear from experienced people. Don't make up stuff that suits your case.

Percentages of time used are shown behind the time the call used up.
In that case above for example, EnchantMagnet.onEntityUpdate uses up 2.1% of the time snapshotted. That's it. 2.1% total. Anything shown in the hierarchy below is just that 2.1% split up into the following calls to further look down into the stack for specific calls.

**Comment by HellFirePvP** [comment]
For the specific call isPlayerFakeMP you mentioned, it took up 9ms from all the time you've ran the snapshot _in total_.
_All calls in all instances_ during your time recorded took up that amount of time; 1.6% of that time, relatively speaking. Hardly a noteworthly amount.

**Comment by Slind14** [comment]
@HellFirePvP I believe he means that this happens for every enchantment. You can see at the very top the Magnet Enchantment, the others are not visible on the screenshot.

**Comment by Doomgull** [comment]
Then need the full thing. Because 2.1%, or fractions of a percent, is nothing when the server isn't dying.

And, again, not what the screenshots are indicating.

**Comment by Sir-Will** [comment]
![](https://i.imgur.com/G1Ce2EI.jpg)

**Comment by HellFirePvP** [comment]
Welp. As most of the overhead comes from the mod state lookup, i'll see to it to cache that as it shouldn't change to begin with after startup. Still, wouldn't expect that to take up the amount of time that it does.
