### ISSUE TITLE
Reduce player knowledge saving

### ISSUE THREAD

**Issue by Sir-Will** [HellFirePvP/AstralSorcery#976]
Can it be either reduced how often the knowledge gets saved or don't save it in the main thread?

![](https://i.imgur.com/vyywxR7.jpg)

**Comment by Doomgull** [comment]
It's not constantly saving to disk.

**Comment by HellFirePvP** [comment]
Again, same as #975 - what you're pointing at takes 0.6% of the time. You sure _that_ is what you're looking for? I'd doubt that.
