### ISSUE TITLE
Question: How to get Stardust from Starmetal Ingot?

### ISSUE THREAD

**Issue by DietmarKrause** [HellFirePvP/AstralSorcery#98]
There seems to be now way to grind star metal ingot to Stardust. JEI shows no way. I am playing it in the All the mods 1 pack. Am i missing something?

**Comment by HellFirePvP** [comment]
The grindstone is the way to 'grind it into dust'

**Comment by DietmarKrause** [comment]
thank you ! found it. Perhaps i am a little slow in thinking but as minecraft player you are conditioned to think in the way of "Sagmill" and "Crusher" when looking at ingots...... Perhaps for the slower of us it would help to have a more precise statement in the book. Something like " perhaps the grinder, which you used to grind your crystalls is helpfull in this task", and: JEI should show this somehow. Most of the users are "conditioned" to look in JEI, which is of now help in this case.

**Comment by HellFirePvP** [comment]
As i discussed yesterday with someone, i'll mention it "more directly" in the respective research-entry. However, i would like to refrain from adding something to JEI 'just for that' - since it's literally the only actual input -> output "recipe" on the grindstone.
