### ISSUE TITLE
celestial altar not working properly

### ISSUE THREAD

**Issue by SomeRandomPetey** [HellFirePvP/AstralSorcery#980]
For some reason, the celestial altar will only work with the tier 2 altar rather than the tier 3 altar, which it is supposed to use.

I'm using Enigmatica 2 Expert version 1.5.1, mod version 1.10.10

**Comment by azak1r** [comment]
i think the celestial altar is requires the Tier 2 altar. its the iridescent altar that requires the Tier 3 altar which is the biggest there is.

**Comment by Doomgull** [comment]
Iridescent is tier 4, technically. And if it isn't working, something is messing with it. Sponge on the server, user build error, etc.

I would recommend using a sextant to check it.
