### ISSUE TITLE
Holorogium Ritual effect reacting strangely with EnderIO cabling after change of configuration file.

### ISSUE THREAD

**Issue by Arcanien** [HellFirePvP/AstralSorcery#981]
So I was excited to try out the new Horologium effect for my machines. When I got the ritual going. At first it seemed to be working actually just fine. But I didn't like the radius of its effects. So I went to the configuration files and increased the range to the max of 64, and saw I could also increase the amount of machines effected and maxed it out. Reloaded game after saving changes and saw that the particles showing it was affecting the machines weren't there. I moved my ritual pedestal to somewhere farther, and put down a ritual anchor with it connected right next to the machines. Nothing happened. So I started messing around with changing the radius and machines affected, while also moving the anchor around and resyncing the anchor each time. Finally I changed everything to default in the configs. Then moved the anchor next to the machines. Tada they were working, but only part of them were getting the particles indicating that it was affecting the machines. I thought was strange so decided to do further testing. I changed the configs again to affect 64 machines, and the range to 32. Came back into game, same machines were affected, and nothing more. Decided to try moving the anchor to the middle of my base to affect all my machines since 32 would be the range to get them all, and I know I had less than 64 machines for the ritual to apply to. Afterwards the machines that were getting particles weren't showing up. However I did see some particles. Going around taking a look, I saw that enderIO cables were getting the particles. And only 4 cables I could find had them. 2 were vibrant power cables, and the other two were the Refined Storage compatibility cables. Last thing I did was change the config to max count of 4000 again but didn't change range and reloaded the game. Absolutely no particles anywhere I looked. Checked entire base and all cabling, using wrenches to see through facades to check, nothing. Is there a strange interaction between Horologium and the way EnderIO's cables are registered? Or is there something I'm doing I'm not supposed to with changing the configs?

Modpack: Direwolf20 1.12 (2.4.0) 
EnderIO: 5.0.39 (Custom updated with Endergy custom added to pack)
Astral Sorcery: 1.10.3
Forge: 14.23.5.2772

**Comment by Doomgull** [comment]
No, cables are tile entities. This is working as intended. Add things to the acceleration blacklist.

Also, that radius is insane.

**Comment by Arcanien** [comment]
Ok I had thought that was the case, so I wanted to ask. Thanks. Nice fast reply.

**Comment by Arcanien** [comment]
Ok so I know this place is meant for issue reporting and not quite a place to ask questions on how to do something. So I am curious since I don't want to bother you, where is a good place to find out how to add a blacklist like that? I'm an upcoming programmer and am looking into understanding how to make my own mods in the future.

**Comment by Doomgull** [comment]
The discord server for the mod, listed on the curse page.

**Comment by Arcanien** [comment]
Huh... wasn't expecting discord. Well awesome. And again, thank you and with the fast reply.
