### ISSUE TITLE
Items disappear on AS crafting tables if you pull recipe from JEI

### ISSUE THREAD

**Issue by rosareven** [HellFirePvP/AstralSorcery#982]
Pack: All The Magic 2.0 Beta
AS version: 1.10.10
Steps to reproduce: (tested with luminous table)
Open Luminous Crafting Table, then pick any recipe that is craftable at this table from JEI that you have the items for. Click on the plus sign in JEI. Nothing is placed on the table and your items for the recipe are lost. Breaking the table will not give the items back.

**Comment by Doomgull** [comment]
This is a jei bug. It is known.
