### ISSUE TITLE
Suggestion: Config setting for perk xp cap as well as perk level cap.

### ISSUE THREAD

**Issue by asteranx** [HellFirePvP/AstralSorcery#983]
I looked through the existing suggestion thread and outstanding issues and didn't see this anywhere. Apologies if I missed something and this is a repeat.

**Suggestion**
I'd like to suggest a config value for the absolute cap on xp necessary to max out your perk levels, regardless of what the perk cap is set to. The cost per level would scale based on a curve that ends with the specified maximum xp value. This would allow pack makers to specify the number of perks players are allowed and in rough terms how long it should take them to reach that point.

**Reasoning**
The cost to get from perk level N-1 to N right now is calculated at 150 + 2^(N/2 + 3), which balloons rapidly as N increases (doubling every two levels, ignoring the initial 150). The cost to go from 29 to 30 is 262,294 points, and feels quite grindy when you actually get around to it.

The issue though is that there is no mitigation of the progression based on the configured level cap, meaning that if you set your cap to 100, getting to level 30 costs the same, and progression simply continues from there. In the end, to go from level 99 to 100 you would need just over 9 quadrillion points, or roughly 34 billion times as much as the difference between 29 and 30. If it takes you one second to go from 29 to 30, this means it would take roughly 1100 years to go from 99 to 100. This makes the ability to increase the level cap basically pointless, since attaining the extra levels quickly becomes unreasonable. Bumping it to 35 even would raise the xp cap by more than 5 times.

Working backwards from an xp cap means that the difficulty of completing the progression can be fixed, regardless of what the level cap is set at.

**Maybe?**
I would also like to suggest making the curve more gentle. Exponential curves tend to get very steep very quickly. Specifically, it costs as much to get from level 28 to level 30 as it does to get from level 1 to level 28, and level 29->30 in particular costs a full third of the xp cap amount. On the other end, you'll get to perk level 15 before you've cleared 1% of the xp cap. A quadratic rather than exponential curve would allow for the costs of sequential levels to be closer to one another while still ramping up consistently, providing a more gradual power increase without the wall.

Further, increasing the absolute maximum level cap from 100 to be equal to the number of nodes in the perk tree would be nice, for people who really want to go nuts.

**Comment by Doomgull** [comment]
It has been discussed a few times, but the answer has akways come back to no, for various design, usage, and balance points.
