### ISSUE TITLE
Crash with Statues Rechiseled

### ISSUE THREAD

**Issue by MuckingAboutMC** [HellFirePvP/AstralSorcery#984]
**Mod Version**:  1.12.2-1.10.10
**Forge Version**: 14.23.5.2807

https://pastebin.com/ZgDD2VKE
**What happens**:
Statue builds fine, but crashes upon right-clicking it with anything. Not sure if this is fixable on your end or they have to change something. Will post to both.

**Comment by Doomgull** [comment]
Willing to bet they're using entityplayer instead of entityplayerMP like they should be, by forge docs. It's what's been causing this that we've seen recently.

**Comment by HellFirePvP** [comment]
"EntityStatuePlayer" is neither a clientside nor a serverside player. Also doesn't hold true to conventions for Fakeplayers. This isn't my fault, this is an implementation error from their side.

**Comment by MuckingAboutMC** [comment]
Thanks for taking a look. I've posted in their github as well. Close at your discretion.
