### ISSUE TITLE
Mantle of the Stars Octans bloating playerdata

### ISSUE THREAD

**Issue by cedmetal** [HellFirePvP/AstralSorcery#985]
When wearing a Mantle of the Start attuned with Octans,
the playerdata file seems to start bloating as soon as you enter the water.

I opened the file with NBTExplorer and it seems to stack some generic.knockback.resistance modifiers to the attributes tree. They keep stacking and increasing the playerdata file size to a point where any action updating the file just freezes the server for a moment. 

(This is after about 2min in the water with the mantle)
![playerdata](https://user-images.githubusercontent.com/23416447/51785396-08ffd000-2125-11e9-83c5-50914fa7df29.jpg)
![playerdatasize](https://user-images.githubusercontent.com/23416447/51785452-ed48f980-2125-11e9-8681-ce8a296875bd.jpg)

I tested this on a custom profile running only Astral sorcery and Baubles but on my custom modpack I host with All the Mods 3 - remixed it seemed to bloat faster and got my file to 12mo with about 1 200 000 entries in an evening where killing a mob would freeze the server shortly. I also tested other swimming gear like Dark Boots from EnderIO with lily pads or a Ring of Chordata from Botania and they didn't have this issue.

Mod Version: 1.12.2 - 1.10.2
Forge Version: 14.23.5.2808

**Comment by Hubry** [comment]
Reproduced it myself, this line is probably the culprit:
https://github.com/HellFirePvP/AstralSorcery/blob/7025d0498fba8af885dc87abcd258772cd077202/src/main/java/hellfirepvp/astralsorcery/common/item/wearable/ItemCape.java#L128

All the attribute entries are like this: random UUID and an unhelpful name that's made from a predefined UUID.
![obraz](https://user-images.githubusercontent.com/26120076/51786247-cb6d6800-2161-11e9-8cd7-807e6b51a773.png)
