### ISSUE TITLE
Ritual not working because of Feral Flare Lantern nearbye

### ISSUE THREAD

**Issue by D1amxnd** [HellFirePvP/AstralSorcery#986]
As the title says after doing some testing I found out that my ritual pedestal was not working because of a newarbye Feral Flare Lantern from Torchmaster - I don't know if its supposed to happen since the lantern creates a Light Source 'Block'. Still thought it might help you and/or other people

**Comment by Doomgull** [comment]
Yes, generally speaking anything that occupies space within the ritual "space" will make it not work. This is working as intended.

**Comment by Xalcon** [comment]
@Doomgull Can you please reconsider your stance on this? I'm placing pseudo air blocks which act like air blocks but just emit light. A lot of mods do similar things and there is no way for me to know if I'm allowed to place my blocks or not. My block even returns true on the generic `world.isAirBlock()` checks which should be the prefered way of checking if something is an air block.

**Comment by Doomgull** [comment]
Acting like air isn't the same as being air.

**Comment by Xalcon** [comment]
I'm sad to hear this, but I'll respect your stance on this. I'll update my mods description to reflect this.

**Comment by Doomgull** [comment]
If you want to have a discussion regarding why it should operate differently than everything else for space checks, drop by the discord for it, but this has been the stance since the mod released.

**Comment by McJty** [comment]
I also agree with @Xalcon here. Any mods that needs to have bigger light sources (like EnderIO, RXLux, Thaumcraft) does this with invisible light blocks as that is pretty much the only clean way to solve this. Adding a simply check for Material.AIR or calling isAir() would fix this on the end of AstralSorcery so I don't see why this can't be reconsidered.

**Comment by Doomgull** [comment]
It was an intentional design choice for how the mechanic was supposed to work for the mod: nothing intruding on the space. Again, feel free to discuss with HF on discord, I'm simply the gatekeeper from historicity on what has been said every time this has been brought up in the past about it, @McJty .
