### ISSUE TITLE
[Netty Epoll Server IO #4/ERROR] [FML] NetworkDispatcher timeout

### ISSUE THREAD

**Issue by NerdimusPrime** [HellFirePvP/AstralSorcery#987]
Minecraft 1.12.2
Forge 14.23.5.2807
Astral Sorcery 1.10.10

Last night while doing a series of teleports using celestial gateways I got booted from the server with the "Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host" message. I was standing on a gateway after arriving when I was disconnected.

Since then I've been unable to stay connected to the server, although everything was working fine up to that point. Sometimes I can load into the world, but everything is frozen. Usually, though, I don't get past the dirt screens (loading terrain...).

[Here ](https://pastebin.com/BYCxaDnD) is the record of my connection attempts from start to finish, which always ends on these lines:

[11:09:28] [Server thread/INFO] [Astral Sorcery]: [Astral Sorcery] Waiting for server synchronization on login for NerdimusPrime...
[11:09:28] [Server thread/INFO] [Astral Sorcery]: [Astral Sorcery] Synchronizing baseline information to NerdimusPrime
[11:12:28] [Netty Epoll Server IO #4/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.timeout.ReadTimeoutException: null
[11:12:28] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: NerdimusPrime lost connection: Disconnected
[11:12:28] [Server thread/INFO] [minecraft/DedicatedServer]: NerdimusPrime left the game

I have rebooted server and client, removed and reinstalled the AS jar from both server and client, installed the Random Patches mod to increase the timeout to 90 seconds, exported my profile in the Twitch launcher with only the folders config, mods, journeymap, resourcepacks, and servers.dat, and used it to create a new profile. Nothing works, although I've at least managed to teleport myself off the gateway to another location in between disconnects. I'm hoping someone might have a solution, because I'm at a loss.

Thanks

**Comment by Doomgull** [comment]
Do you have a client-side log, as well?

Try increasing the timeout about 90 seconds, if you can.

**Comment by NerdimusPrime** [comment]
Also interesting, the server owner has it running on a linux laptop in his office. His PC can connect and play with no problem. We've run speed tests at both ends and that's normal. My ping to the server is about 20ms.

**Comment by Doomgull** [comment]
Are you wearing a Mantle?

**Comment by NerdimusPrime** [comment]
Nope.

**Comment by Doomgull** [comment]
Hmm, I see that thaumicjei completed it's caching before some of those attempts, so likely not JEI delay. May want to try launching with Journeymap disabled to see if maybe there's some palette data caching involved.

Alternatively, have the server admin (backup first) blow away your player.dat and astral.dat files, see if it makes a difference. This is unfortunately vague as to what's going on. If that lets you in, though, would like to see those two files to see if I can find anything of value inside.

**Comment by NerdimusPrime** [comment]
I’ll give it a try after I get back to the house. Thanks for all your help so far.

**Comment by NerdimusPrime** [comment]
Disabling Journeymap had no effect. I'm having trouble finding the correct .dat files on the server. There are a number of "nerdimusprime.dat" files in different folders, so I'm not sure which one I need, and no astral.dat anywhere.

**Comment by NerdimusPrime** [comment]
Never mind, I think I found them. Both files have a long string of characters with my player name in it, one ending in .dat and the other ending in .astral?

**Comment by Doomgull** [comment]
Yup, that would be it, sorry for brainfarting on specifics for it earlier. Been one of those days.

**Comment by NerdimusPrime** [comment]
No problem whatsoever, I'm just grateful you're taking the time to help.

Blowing away the dat files had no effect, but I'm attaching them anyway. If that didn't do it then I don't know what's left. It seems like the server is bogged down trying to load the world for me, but the system monitor doesn't show cpu, memory, or network speeds are maxed out.

[apterraplayerandastraldatfiles.zip](https://github.com/HellFirePvP/AstralSorcery/files/2799538/apterraplayerandastraldatfiles.zip)

**Comment by NerdimusPrime** [comment]
After beating on the server, and my head, for a couple days, I no longer suspect this is an AS problem. The connection just happens to stall on AS the longest, but I've seen it hang on other mods since I opened this issue. Something is choking my connection to the server down to a trickle of data but I can't determine what. Doomgull, thanks very much for the help earlier.

**Comment by NerdimusPrime** [comment]
Holy s***, mystery solved. The server owner's ISP has a monthly cap on inbound connections to his network, probably to prevent people from running commercial services from their home. I was playing when the cap was hit so it throttled my connection to almost nothing. The cap reset today and now I can connect normally. First time I've ever run into that. *smh*
