### ISSUE TITLE
[Request] Config Option for Perk Tree

### ISSUE THREAD

**Issue by andr9528** [HellFirePvP/AstralSorcery#990]
It would be nice to be able to configure different parts of the perk tree, along with max level and experience needed for levels.

For the maximum level it would simply take a number, that is less than or equal to the amount of perks that exist. If a number is specified that is higher than the actual available perk count, because maybe some perks have been disabled via the same config file, the game would simply at load time, set the value to the highest possible value. The value would default to the current level cap of 30.

For the experience need, i'm thinking a multiplier for how fast the experience needed grows, As i suspect the needed experience is not a constant value at the moment. If it is a constant value, then this would also introduce a more RPG like effect to it, which is good right?

For the different perks in the tree, i'm thinking the possibility to turn on and off different mayor perks like "Chained Mining" or "Breaking Aim". Along with this possibility, it would be cool if how much the small, medium and large percentage based perks gave was configurable. Like instead of giving 3% increased movement speed, you could say that these small perks, should give 5% as a base.

All these config options would heavily benefit modpack creators, as they would be able to fine tune the tree to match the difficulty of the pack they are creating. It would also allow players who want as many shenanigans as possible, like myself, to crank up the number to absurd levels just for the fun of it.

**Comment by Doomgull** [comment]
Max level has been configurable since 1.10.4.

Experience per level will never be configurable.

You can already configure the perk values of existing perks using CT.

**Comment by andr9528** [comment]
Disregard all i said, didn't see the main astral sorcery config file, as it was not in the folder called astralsorcery, maybe move the main config file in there and change its name to main? to have all astral sorcery configuration files in one place.
