### ISSUE TITLE
Loading cache takes a huge amount of RAM

### ISSUE THREAD

**Issue by Nensec** [HellFirePvP/AstralSorcery#992]
Encounterd this while trying to troubleshoot an issue in the Enigmatica 2 modpack

https://github.com/NillerMedDild/Enigmatica2/issues/289#issuecomment-458751912

When the mod wants to load all structures of the overworld in a cache it results in a massive CPU bogged lagspike and the memory usage going to crazy amounts. In my case from 5gb used to 11gb used in the span of half a minute. In a previous instance where the server was configured to be only 8gb max it actually caused the entire server to hang.

```
[00:36:44] [Server thread/INFO] [Astral Sorcery]: Load CachedWorldData 'structures' for world 0
[00:36:45] [Server thread/INFO] [Astral Sorcery]: Loading of 'structures' for world 0 finished.
[00:36:45] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 16293ms behind, skipping 325 tick(s)
[00:37:41] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 17440ms behind, skipping 348 tick(s)
```

Our overworld has 450 chunks pre-genned, perhaps it is loading strctures that players have not even been to yet physically?

**Comment by Nensec** [comment]
Nope, just regular Forge that is part of the Enigmatica 2 modpack.
It could very well be that something else is causing the memory increase and CPU usage, this mod simply was the only thing that output anything in the log at the time.

**Comment by HellFirePvP** [comment]
6GB only for structure loading? You know all that's saved per structure are 12 byte.
That would mean the mod has generated 500 MILLION structures.
And that is the lower end of things, the file would - due to the way NBT as datastructure is saved - most likely be larger than 6GB.
500 Million structures in 450 chunks? you can BARELY fit them there. every 4th block in that would would basically be a structure. Unlikely to say the least.

**Comment by RonRicoSuave** [comment]
FWIW I was having this issue or something very similar with retrogen & an older world and and when  creating a new world.  Turning off retrogen fixed it in that world.   Structure frequency didn't seem to be out of control in new chunks.   In both cases (with ram set to 16GB for the instance) ram usage would reach the max and then nothing would happen.  In the case of creating a world, it never made it to a game screen. 

Mods are a random mix of lots of larger ones...  no idea what's in Enigmatica2 so I can't comment there.  

Anyway updating AS from 1.10.10 -> 1.10.11 fixed this issue for me in the case of worldgen, I haven't tested retrogen on anything.

**Comment by RonRicoSuave** [comment]
I did note the increased ram usage during world load that the reporter did and had to increase overall ram settings at the time from 12->16GB, but I'd been messing with mod installs and wrote it off as a different issue with Thaumic JEI going out of control caching new data.  Removing thaumic JEI didn't change ram use, but the mod update has lowered it considerably during the mod loading phase.

**Comment by Anton369** [comment]
I am running 1.10.11 and I am still having this issue and don't have retro gen on or Thaumic JEI installed on the server, though I did pre-gen my world to a 6000 block radius. After loading the cache, my server's memory usage went up by 5 gigabytes.
Log: https://pastebin.com/LUxcVqZd
