### ISSUE TITLE
Aevitas Attunment Altar Pattern looks confusing

### ISSUE THREAD

**Issue by ConnorMiner** [HellFirePvP/AstralSorcery#994]
While the Attunement Altar is a valid relay in the pattern, if the player doesn't know this (i.e. they didn't think anything or forgot about the relay in the recipe), it looks like a relay is conflicting with the altar, especially when Aevitas is not in the sky.
(Here I intentionally made it so that Aevitas wasn't in the sky so that the particles would appear)
![enigmatica2expert 2_1_2019 5_29_53 pm](https://user-images.githubusercontent.com/32756365/52156746-57dac780-2647-11e9-93b1-f813b722a667.png)

**Comment by Doomgull** [comment]
It is in the tome, that the altar is a valid relay.
