### ISSUE TITLE
Resplendent Prism creating funky interaction with COFH Holding Enchant

### ISSUE THREAD

**Issue by MuteTiefling** [HellFirePvP/AstralSorcery#995]
Astral Sorcery Version 1.10.10

When I equip a resplendent prism and hold a Flux-Infused Bow in my hand with Holding on it, the Holding level does appear to go up as does the total RF capacity of the bow. However, the bow's charge keeps fluctuating, going above the non boosted version of Holding and then draining. 

This causes a constant drain of power from the Flux capacitor in my inventory. 

For example, the bow has holding IV on it and can hold 960k RF. With the Prism equipped (and perks to boost it further) it goes to Holding VII and can hold 1.44m RF. While holding the bow in my hand, I can see it charges up to 1m RF, then drops to 960k, and up and down constantly. Meanwhile the charge on the Flux Capacitor keeps going down until I either switch to another inventory slot or remove the prism.

**Comment by HellFirePvP** [comment]
Not sure i can do something about this

**Comment by yagomont** [comment]
Blacklist holding from being enhanced?

**Comment by HellFirePvP** [comment]
It's (already been quite a while ago) blacklisted from being able to get it on a new amulet.
