### ISSUE TITLE
Mending III on bows with Pelotrio

### ISSUE THREAD

**Issue by artaksfx** [HellFirePvP/AstralSorcery#998]
Hi, i recently installed Astral sorcery (the last version), and when i put a bow in a stellar refraction table, it enchants my bow with mending III instead of Infinity :/

**Comment by HellFirePvP** [comment]
Aevitas gives mending. You're most likely using the wrong glass.

**Comment by artaksfx** [comment]
![1](https://user-images.githubusercontent.com/47391500/52358349-1c217280-2a38-11e9-95ad-47d803e737ff.png)
![2](https://user-images.githubusercontent.com/47391500/52358351-1d529f80-2a38-11e9-9e53-4b8b6c2014f4.png)
![3](https://user-images.githubusercontent.com/47391500/52358355-1e83cc80-2a38-11e9-90f0-733be34bd7b2.png)
![4](https://user-images.githubusercontent.com/47391500/52358364-1fb4f980-2a38-11e9-9d0d-a0d83a56947f.png)
![5](https://user-images.githubusercontent.com/47391500/52358372-20e62680-2a38-11e9-8868-0b63aec854e7.png)
![6](https://user-images.githubusercontent.com/47391500/52358379-25124400-2a38-11e9-8990-42ed399a655e.png)
![7](https://user-images.githubusercontent.com/47391500/52358397-2f344280-2a38-11e9-84e4-bc2cb0400bf8.png)
![8](https://user-images.githubusercontent.com/47391500/52358409-34918d00-2a38-11e9-91f7-fa764fb11556.png)

Sorry but i'm using Pelotrio, and if i use only Pelotrio on the engraved glass, it's mending III who appear too (on a bow)....

**Comment by HellFirePvP** [comment]
You're using an outdated version of AS. This was changed. https://github.com/HellFirePvP/AstralSorcery/commit/679fcfd8defbf281f5efd25e3b8e7d233ab71bf9#diff-73d87e2b1b2b24d4f40513e474002302

**Comment by Doomgull** [comment]
@artaksfx this is why it's important to give specific version numbers, and not things like "the last version".
