### ISSUE TITLE
[Interaction w/Integrated Tunnels] Odd Behavior between Lightwell and IT Fluid Exporters"

### ISSUE THREAD

**Issue by Targren** [HellFirePvP/AstralSorcery#999]
Astral Sorcery Version: 1.10.10
Integrated Tunnels Version: 1.12.2-1.6.2

I found a bit of a weird behavior with the IT fluid interface on the bottom of a lightwell. Normally, the exporter grabs fluid (up to the "transfer rate") every time it activates if the "exact amount" flag is false. On a lightwell, though, it behaves as if this flag was "true", so with default settings it doesn't export any fluid until the the lightwell has more than the "Transfer rate" worth - and then transfers it all as of that tick, so after the first successful export, the output tank might have 1004mb of starlight in it, instead of 1000. When the gem/stone in the lightwell breaks, the export is also triggered. 

The Fluid Interface and Exporter work as expected with other containers (TiC seared tanks, TE Portable tanks, etc..), and the Lightwell works as expected with other pipes (tested with TD Hardened Fluiduct+Server, EnderIO Fluid Conduit). Reversing the ID/IT setup, so that the Fluid Interface is on the tank and a Fluid Importer is on the Lightwell, also works as expected. 

The behavior doesn't appear to be limited to Liquid Starlight. I was able to reproduce the behavior with lava from a Magma block (netherrack broke too quickly to tell for sure)

[Issue as reported on Integrated Tunnels' tracker](https://github.com/CyclopsMC/IntegratedTunnels/issues/153#issuecomment-461442124)

**Comment by Doomgull** [comment]
I'm fairly certain that's due to intentional code to prevent dupe issues earlier on with some other mods. HellFire would need to confirm, however.

**Comment by Targren** [comment]
That would certainly make sense if IT's new movement logic is bumping up against that code. 

Thanks. I'll wait for that confirmation, but at least I can put a pin in trying to figure it out for now. :)

**Comment by HellFirePvP** [comment]
Any news on this?

**Comment by Targren** [comment]
@HellFirePvP I was actually waiting for confirmation that this was intentional behavior as @Doomgull suggested. If it's not, I can try testing it again with the latest versions in the next couple of days (when my Copious Free Time(TM) comes around again)

**Comment by Targren** [comment]
@HellFirePvP 

I just tested with Astral Sorcery 1.10.17  and Integrated Dynamics/Tunnels  1.0.11/1.6.8  and it looks like it's working as expected now, so whatever was causing it doesn't seem to be around in the latest versions.
